# Zero-shot text-to-video benchmark on ActivityNet Captions

Frozen image and video language models, scored zero-shot on ActivityNet Captions. Every caption is a query; its only positive is the gallery video it describes.

| Dataset | Gallery | Queries | What the captions describe |
|---|---|---|---|
| **ActivityNet Captions** (`paragraph`) | `val1` videos (random sample of `MAX_VIDEOS`, or all 4,917) | 1 per video: the sentences of the video joined into one paragraph | the whole video (long-form, ~180 s on average) |
| **ActivityNet Captions** (`sentence`) | same gallery | one per annotated event sentence (about 3.6 per video) | one event of the video |

Source: [`friedrichor/ActivityNet_Captions`](https://huggingface.co/datasets/friedrichor/ActivityNet_Captions) (official splits: train 10,009 / val1 4,917 / val2 4,885 videos). `val1` is the usual paragraph-to-video test split. Set `ANET_SPLIT = "val2"` to use the other one.

**How to run**

1. Kaggle GPU T4 x2, Internet on. Add a Kaggle secret named `hugging_face` and attach it to the notebook (used for the dataset download and gated InternVideo2-1B-s2 checkpoint).
2. This notebook runs InternVideo2-1B-s2, LanguageBind, and InternVideo2 CLIP-S.
3. Run All. On Kaggle, two workers run models concurrently, one pinned to each T4. Every result row is written as JSON the moment it finishes, so a restarted session skips what is done.
4. Results are saved under `/kaggle/working/zero_shot_results/base`; the tables include only the three selected models.

**Time and disk.** ActivityNet videos are long, so the sliding-window protocols are expensive. `MAX_VIDEOS` (default 1000, seeded) keeps a session inside the Kaggle time limit; set it to `None` for the full split. The videos live inside a 42 GB split archive on the Hub, which is streamed once and only the selected videos are kept on disk.

## 1. Configuration

In [1]:
from pathlib import Path

ENV_GROUP = "base"  # base dependencies are required for these three models
MODELS = ["internvideo2_s2_1b", "languagebind", "internvideo2"]

DATASETS = {
    "activitynet": {"label": "ActivityNet Captions", "subsets": ["paragraph", "sentence"], "protocols": "video"},
}
SPLIT = "test"

# ActivityNet Captions: "val1" is the standard paragraph-to-video test split, "val2" is the other one.
ANET_SPLIT = "val1"
MAX_VIDEOS = 1000  # random gallery sample (seeded); None keeps every video of the split
ANET_SEED = 0
DEVICE = "cuda"  # two visible GPUs run one model worker each
BATCH = 4
TEXT_BATCH = 16
POOLS = ("mean", "mean_s8", "max", "query_max")

# 1B-s2 is built for 4-frame clips; every other model uses 8.
NATIVE_FRAMES = {"internvideo2_s2_1b": 4}
MODEL_BATCH = {"internvideo2_s2_1b": 1, "languagebind": 2, "internvideo2": 2}
MODEL_TEXT_BATCH = {}

SINGLE_PROTOCOLS = [
    {"name": "uniform8", "num_frames": 8, "frame_sample": "uniform", "family": "clip8"},
    {"name": "uniform4", "num_frames": 4, "frame_sample": "uniform", "family": "s2"},
    {"name": "middle4", "num_frames": 4, "frame_sample": "middle", "family": "s2", "video_only": True},
]
WINDOW_PROTOCOLS = [
    {"name": "vt_1fps_n12", "sample_fps": 1.0, "max_frames": 12, "stride": 4},
    {"name": "vt_2fps_n32", "sample_fps": 2.0, "max_frames": 32, "stride": 4},
    {"name": "reid_8fps_n64", "sample_fps": 8.0, "max_frames": 64, "stride": 4},
]

PRETTY = {
    "internvideo2_s2_1b": "InternVideo2-1B-s2",
    "languagebind": "LanguageBind",
    "internvideo2": "InternVideo2 CLIP-S",
}

WORK = Path("/kaggle/working") if Path("/kaggle/working").is_dir() else Path("results")
# Videos and frame JPEGs are large and disposable, so they go to /kaggle/temp when it exists;
# only the small result JSONs stay in /kaggle/working.
DATA_ROOT = WORK
if Path("/kaggle/working").is_dir():
    try:
        Path("/kaggle/temp").mkdir(parents=True, exist_ok=True)
        DATA_ROOT = Path("/kaggle/temp")
    except OSError:
        DATA_ROOT = WORK
RESULTS_ROOT = WORK / "zero_shot_results"
RESULTS_DIR = RESULTS_ROOT / ENV_GROUP
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
print("Group", ENV_GROUP, "models", MODELS, flush=True)
print("Dataset ActivityNet Captions", "results", RESULTS_DIR, "data", DATA_ROOT, flush=True)

Group base models ['internvideo2_s2_1b', 'languagebind', 'internvideo2']
Dataset ActivityNet Captions results /kaggle/working/zero_shot_results/base data /kaggle/temp

## 2. Setup

Clones the repo (and OpenGVLab/InternVideo when 1B-s2 is in the group), installs the group's dependencies, checks the package version, and loads the Hugging Face token. If `transformers` was already imported with a different version, restart the session and run again.

In [2]:
import os
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version

SHAWAF_URL = "https://github.com/BASSAT-BASSAT/Benchmarking-Video-Image-language-models-for-Tracklet-retrieval-.git"
INTERNVIDEO_URL = "https://github.com/OpenGVLab/InternVideo.git"
EXPECTED = "0.1.18"
TORCH_INDEX = "https://download.pytorch.org/whl/cu126"


def run(cmd, cwd=None):
    print("+", " ".join(map(str, cmd)), flush=True)
    subprocess.check_call([str(part) for part in cmd], cwd=str(cwd) if cwd else None)


def installed(name):
    try:
        return version(name)
    except PackageNotFoundError:
        return None


def sync_repo(url, path):
    if path.exists():
        run(["git", "fetch", "origin"], cwd=path)
        run(["git", "reset", "--hard", "origin/main"], cwd=path)
    else:
        run(["git", "clone", url, str(path)])


NEEDS_INTERNVIDEO = "internvideo2_s2_1b" in MODELS
ON_KAGGLE = Path("/kaggle/working").is_dir()
transformers_before = installed("transformers")
transformers_loaded = "transformers" in sys.modules
torch_before = installed("torch")
torch_loaded = "torch" in sys.modules

if ON_KAGGLE:
    shawaf_dir = Path("/kaggle/working/shawaf-vlm")
    intern_dir = Path("/kaggle/working/InternVideo")
    sync_repo(SHAWAF_URL, shawaf_dir)
    if NEEDS_INTERNVIDEO:
        sync_repo(INTERNVIDEO_URL, intern_dir)
    if ENV_GROUP == "base":
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[all]"])
        run(
            [
                sys.executable, "-m", "pip", "install", "-q",
                "einops", "timm", "av", "imageio", "librosa", "soundfile",
                "pandas", "pyyaml", "scipy", "wandb", "gdown",
            ]
        )
        try:
            run([sys.executable, "-m", "pip", "install", "-q", "decord"])
        except subprocess.CalledProcessError:
            print("decord wheel failed; the 1B-s2 path stubs it and uses PyAV", flush=True)
    else:
        if not (installed("torch") or "").startswith("2.8.0"):
            run([sys.executable, "-m", "pip", "install", "-q", "--index-url", TORCH_INDEX, "torch==2.8.0", "torchvision==0.23.0"])
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[{ENV_GROUP}]", "gdown>=5.2", "pandas"])
else:
    here = Path.cwd().resolve()
    shawaf_dir = here
    for candidate in [here, *here.parents]:
        if (candidate / "shawaf_vlm").is_dir() and (candidate / "pyproject.toml").is_file():
            shawaf_dir = candidate
            break
    intern_dir = shawaf_dir / "InternVideo"
    if NEEDS_INTERNVIDEO and not intern_dir.is_dir():
        run(["git", "clone", INTERNVIDEO_URL, str(intern_dir)], cwd=shawaf_dir)

transformers_after = installed("transformers")
if transformers_loaded and transformers_after != transformers_before:
    raise RuntimeError(
        f"transformers changed from {transformers_before} to {transformers_after} after it was "
        "imported. Restart the session, then Run All again."
    )

torch_after = installed("torch")
print("torch", torch_after, flush=True)
if torch_loaded and torch_after != torch_before:
    raise RuntimeError(
        f"torch changed from {torch_before} to {torch_after} after it was imported. "
        "Restart the session, then Run All again."
    )

if NEEDS_INTERNVIDEO:
    os.environ["INTERNVIDEO_ROOT"] = str(intern_dir)
if str(shawaf_dir) not in sys.path:
    sys.path.insert(0, str(shawaf_dir))
for name in list(sys.modules):
    if name == "shawaf_vlm" or name.startswith("shawaf_vlm."):
        del sys.modules[name]

import shawaf_vlm

print("shawaf_vlm", shawaf_vlm.__version__, shawaf_vlm.__file__, flush=True)
print("transformers", transformers_after, flush=True)
if shawaf_vlm.__version__ != EXPECTED:
    raise RuntimeError(
        f"Expected shawaf_vlm {EXPECTED}, found {shawaf_vlm.__version__}. "
        "Restart the session and run this cell again after origin/main updates."
    )

token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
if not token and ON_KAGGLE:
    try:
        from kaggle_secrets import UserSecretsClient

        token = UserSecretsClient().get_secret("hugging_face")
    except Exception as exc:
        print("No hugging_face secret:", type(exc).__name__, flush=True)
if token:
    os.environ["HF_TOKEN"] = token
    os.environ["HUGGING_FACE_HUB_TOKEN"] = token
    from huggingface_hub import login

    login(token=token, add_to_git_credential=False)
    print("Hugging Face token loaded", flush=True)
elif NEEDS_INTERNVIDEO:
    raise RuntimeError(
        "Hugging Face token missing. InternVideo2-1B-s2 is gated: add a Kaggle secret "
        "named hugging_face and attach it to this notebook."
    )
else:
    print("No Hugging Face token; public datasets and models only", flush=True)

+ git clone https://github.com/BASSAT-BASSAT/Benchmarking-Video-Image-language-models-for-Tracklet-retrieval-.git /kaggle/working/shawaf-vlm

Cloning into '/kaggle/working/shawaf-vlm'...

+ git clone https://github.com/OpenGVLab/InternVideo.git /kaggle/working/InternVideo

Cloning into '/kaggle/working/InternVideo'...

+ /usr/bin/python3 -m pip install -q -e /kaggle/working/shawaf-vlm[all]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 29.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 2.1 MB/s eta 0:00:00
+ /usr/bin/python3 -m pip install -q einops timm av imageio librosa soundfile pandas pyyaml scipy wandb gdown
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 57.5 MB/s eta 0:00:00
+ /usr/bin/python3 -m pip install -q decord
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 85.4 MB/s eta 0:00:00
torch 2.11.0+cu128
shawaf_vlm 0.1.18 /kaggle/working/shawaf-vlm/shawaf_vlm/__init__.py
transformers 5.16.1

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face token loaded

## 3. Datasets

ActivityNet Captions ships its videos inside `ActivityNet_Videos.tar.part-000 ... 007` (about 42 GB). The next cell reads the split JSON, draws the gallery (`MAX_VIDEOS` seeded random `ANET_SPLIT` videos), streams the archive parts one after another (the next part downloads while the current one is read, and a finished part is deleted at once), keeps only the selected videos, and writes `metadata/paragraph-test.jsonl` and `metadata/sentence-test.jsonl`. A rerun finds the videos already extracted and downloads nothing.

Both subsets share one gallery, so gallery embeddings are reused between them (rows marked `gallery_cached`).

In [3]:
import io
import json
import os
import random
import shutil
import tarfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd
from huggingface_hub import hf_hub_download
from IPython.display import Markdown, display
from tqdm.auto import tqdm

from shawaf_vlm.data.hub_video import load_hub_video_split

ANET_REPO = "friedrichor/ActivityNet_Captions"
ANET_PARTS = [f"ActivityNet_Videos.tar.part-{i:03d}" for i in range(8)]
ANET_ROOT = DATA_ROOT / "ActivityNet_Captions"
ANET_VIDEOS = ANET_ROOT / "videos"
ANET_META = ANET_ROOT / "metadata"
ANET_PARTS_DIR = ANET_ROOT / "_parts"


class PartStream(io.RawIOBase):
    """Read the split tar as one byte stream, downloading one part ahead and deleting finished parts."""

    def __init__(self, names, dest, token=None):
        self.names = list(names)
        self.dest = Path(dest)
        self.token = token
        self.dest.mkdir(parents=True, exist_ok=True)
        self.pool = ThreadPoolExecutor(max_workers=1)
        self.index = -1
        self.handle = None
        self.current = None
        self.pending = None
        self._schedule(0)

    def _fetch(self, name):
        return Path(
            hf_hub_download(
                repo_id=ANET_REPO,
                filename=name,
                repo_type="dataset",
                token=self.token,
                local_dir=str(self.dest),
            )
        )

    def _schedule(self, index):
        self.pending = self.pool.submit(self._fetch, self.names[index]) if index < len(self.names) else None

    def _open_next(self):
        self.index += 1
        future = self.pending
        if future is None:
            return False
        path = future.result()
        self._schedule(self.index + 1)
        self.current = path
        self.handle = path.open("rb")
        print(f"reading {path.name} ({self.index + 1}/{len(self.names)})", flush=True)
        return True

    def _finish_part(self):
        if self.handle is not None:
            self.handle.close()
            self.handle = None
        if self.current is not None:
            self.current.unlink(missing_ok=True)
            self.current = None

    def readable(self):
        return True

    def readinto(self, buffer):
        while True:
            if self.handle is None and not self._open_next():
                return 0
            count = self.handle.readinto(buffer)
            if count:
                return count
            self._finish_part()

    def close(self):
        if not self.closed:
            self._finish_part()
            if self.pending is not None:
                self.pending.cancel()
            self.pool.shutdown(wait=True)
            shutil.rmtree(self.dest, ignore_errors=True)
        super().close()


def anet_select_rows():
    """Read the split JSON and draw the gallery (seeded, order kept)."""
    path = hf_hub_download(
        repo_id=ANET_REPO,
        filename=f"activitynet_captions_{ANET_SPLIT}.json",
        repo_type="dataset",
        token=os.environ.get("HF_TOKEN"),
    )
    rows = json.loads(Path(path).read_text(encoding="utf-8"))
    seen, unique = set(), []
    for row in rows:
        if row["video_id"] not in seen:
            seen.add(row["video_id"])
            unique.append(row)
    if MAX_VIDEOS is not None and len(unique) > MAX_VIDEOS:
        picked = sorted(random.Random(ANET_SEED).sample(range(len(unique)), MAX_VIDEOS))
        unique = [unique[i] for i in picked]
    return unique


def anet_local_videos():
    if not ANET_VIDEOS.is_dir():
        return {}
    return {p.stem: p for p in ANET_VIDEOS.iterdir() if p.is_file() and p.suffix != ".tmp"}


def anet_extract(video_ids):
    """Stream the split archive once and keep only ``video_ids`` (matched on file stem)."""
    remaining = set(video_ids)
    ANET_VIDEOS.mkdir(parents=True, exist_ok=True)
    stream = PartStream(ANET_PARTS, ANET_PARTS_DIR, token=os.environ.get("HF_TOKEN"))
    bar = tqdm(total=len(remaining), desc="Extract videos", unit="video")
    try:
        reader = io.BufferedReader(stream, buffer_size=8 * 1024 * 1024)
        with tarfile.open(fileobj=reader, mode="r|") as archive:
            for member in archive:
                if not member.isfile():
                    continue
                name = Path(member.name).name
                stem = Path(name).stem
                if stem not in remaining:
                    continue
                target = ANET_VIDEOS / name
                tmp = target.with_name(target.name + ".tmp")
                with archive.extractfile(member) as source, tmp.open("wb") as out:
                    shutil.copyfileobj(source, out, 4 * 1024 * 1024)
                os.replace(tmp, target)
                remaining.discard(stem)
                bar.update(1)
                if not remaining:
                    break
    finally:
        bar.close()
        stream.close()
    if remaining:
        print(f"{len(remaining)} selected videos were not found in the archive", flush=True)


def anet_write_metadata(rows, have):
    ANET_META.mkdir(parents=True, exist_ok=True)
    kept = [row for row in rows if row["video_id"] in have]
    for subset in DATASETS["activitynet"]["subsets"]:
        with (ANET_META / f"{subset}-{SPLIT}.jsonl").open("w", encoding="utf-8") as handle:
            for row in kept:
                if subset == "paragraph":
                    captions = [row["caption"].strip()]
                elif subset == "sentence":
                    captions = [s.strip() for s in row["sentences"] if s and s.strip()]
                else:
                    raise ValueError(f"Unknown ActivityNet subset {subset!r}")
                record = {
                    "video": f"videos/{have[row['video_id']].name}",
                    "video_id": row["video_id"],
                    "captions": captions,
                    "subset": ANET_SPLIT,
                }
                handle.write(json.dumps(record, ensure_ascii=False) + "\n")
    return len(kept)


def prepare_activitynet():
    rows = anet_select_rows()
    have = anet_local_videos()
    missing = [row["video_id"] for row in rows if row["video_id"] not in have]
    print(f"ActivityNet {ANET_SPLIT}: {len(rows)} selected videos, {len(rows) - len(missing)} already on disk", flush=True)
    if missing:
        anet_extract(missing)
        have = anet_local_videos()
    kept = anet_write_metadata(rows, have)
    print(f"Wrote metadata for {kept} videos under {ANET_META}", flush=True)
    return ANET_ROOT


# Hugging Face dataset import for Kaggle: download the selected split JSON and
# stream its video archive directly from the dataset repository.
DATA_ROOTS = {"activitynet": prepare_activitynet()}


def load_split(subset):
    return load_hub_video_split(
        DATA_ROOTS["activitynet"],
        config=subset,
        split=SPLIT,
        source=f"activitynet:{ANET_SPLIT}:{subset}",
        missing=lambda detail: FileNotFoundError(detail),
        name="ActivityNet Captions",
    )


summary = []
for subset in DATASETS["activitynet"]["subsets"]:
    splits = load_split(subset)
    per_id = pd.Series([g.person_id for g in splits.gallery]).value_counts()
    positives = pd.Series([per_id.get(q.person_id, 0) for q in splits.query])
    summary.append(
        {
            "dataset": "ActivityNet Captions",
            "subset": subset,
            "queries": len(splits.query),
            "gallery": len(splits.gallery),
            "identities": int(per_id.size),
            "positives / query": round(float(positives.mean()), 2),
            "root": str(DATA_ROOTS["activitynet"]),
        }
    )
DATASET_SUMMARY = pd.DataFrame(summary)
display(DATASET_SUMMARY)

activitynet_captions_val1.json:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

ActivityNet val1: 1000 selected videos, 0 already on disk

Extract videos:   0%|          | 0/1000 [00:00<?, ?video/s]

ActivityNet_Videos.tar.part-000: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-000: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-000 (1/8)

ActivityNet_Videos.tar.part-001: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-001: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-001 (2/8)

ActivityNet_Videos.tar.part-002: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-002: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-002 (3/8)

ActivityNet_Videos.tar.part-003: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-003: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-003 (4/8)

ActivityNet_Videos.tar.part-004: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-004: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-004 (5/8)

ActivityNet_Videos.tar.part-005: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-005: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-005 (6/8)

ActivityNet_Videos.tar.part-006: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-006: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-006 (7/8)

ActivityNet_Videos.tar.part-007: reconstructing file:   0%|          |  0.00B / 4.40GB

ActivityNet_Videos.tar.part-007: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-007 (8/8)
Wrote metadata for 1000 videos under /kaggle/temp/ActivityNet_Captions/metadata

,dataset,subset,queries,gallery,identities,positives / query,root
0,ActivityNet Captions,paragraph,1000,1000,1000,1.0,/kaggle/temp/ActivityNet_Captions
1,ActivityNet Captions,sentence,3617,1000,1000,1.0,/kaggle/temp/ActivityNet_Captions

## 4. Run

Each GPU worker takes the next model, then runs dataset, protocol, and subset in order. Each finished row is saved to `zero_shot_results/<group>/<dataset>/<model>_<subset>_<protocol>_<pool>.json` and skipped on rerun.

The ActivityNet `paragraph` and `sentence` subsets share one gallery, so gallery embeddings are reused between them within a protocol (those rows are marked `gallery_cached`; speed is read from the uncached row).

In [4]:
import torch
print(torch.__file__)
print(hasattr(torch, "device"), torch.__version__)

/usr/local/lib/python3.13/dist-packages/torch/__init__.py
True 2.11.0+cu128

In [5]:
import gc
import json
import traceback
from concurrent.futures import ThreadPoolExecutor
from queue import Empty, Queue
from datetime import datetime, timezone

from shawaf_vlm.eval_loop import evaluate_text_to_tracklet, evaluate_text_to_tracklet_windows
from shawaf_vlm.metrics import format_metrics
from shawaf_vlm.models import build_encoder
from shawaf_vlm.models.runtime import ensure_cuda_healthy

METRIC_KEYS = [
    "Rank-1", "Rank-5", "Rank-10", "Rank-20", "Rank-50",
    "mAP", "MdR", "MnR", "nDCG@10", "mINP",
    "num_valid_queries", "num_gallery", "num_clips",
    "decode_s", "video_s", "text_s", "score_s", "total_s",
    "video_ms_per_item", "peak_gpu_gb", "reserved_gpu_gb",
]


class StopModel(Exception):
    """CUDA OOM: stop this model, keep benchmark settings unchanged."""


class GalleryCache:
    """Reuse the last gallery embedding when the exact same frame lists come back."""

    def __init__(self, encoder):
        self.encoder = encoder
        self._key = None
        self._features = None
        self.last_hit = False

    def encode_videos(self, videos, batch_size=4):
        key = tuple(tuple(str(path) for path in clip) for clip in videos)
        if key == self._key:
            self.last_hit = True
            return self._features
        self.last_hit = False
        self._features = self.encoder.encode_videos(videos, batch_size=batch_size)
        self._key = key
        return self._features

    def encode_texts(self, texts, batch_size=32):
        return self.encoder.encode_texts(texts, batch_size=batch_size)

    def __getattr__(self, name):
        return getattr(self.encoder, name)


def family(model):
    return "s2" if model in NATIVE_FRAMES else "clip8"


def protocols_for(model):
    kind = "video"
    specs = []
    for spec in SINGLE_PROTOCOLS:
        if spec["family"] != family(model):
            continue
        if kind == "image" and spec.get("video_only"):
            continue
        specs.append({**spec, "type": "single"})
    if kind == "video":
        specs.extend({**spec, "type": "window"} for spec in WINDOW_PROTOCOLS)
    return specs


def sampling_text(model, spec):
    if spec["type"] == "single":
        return f"{spec['frame_sample']} {spec['num_frames']} frames"
    return (
        f"sliding windows of {NATIVE_FRAMES.get(model, 8)}, stride {spec['stride']}, "
        f"{spec['sample_fps']:g} fps, cap {spec['max_frames']} frames"
    )


def result_path(dataset, model, subset, protocol, pool):
    return RESULTS_DIR / dataset / f"{model}_{subset}_{protocol}_{pool}.json"


def expected_paths(dataset, model, subset, spec):
    pools = ["none"] if spec["type"] == "single" else list(POOLS)
    return [result_path(dataset, model, subset, spec["name"], pool) for pool in pools]


def is_complete(path):
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("status") == "complete"
    except Exception:
        return False


def save_row(dataset, model, subset, spec, pool, metrics=None, error=None, cached=False):
    row = {
        "group": ENV_GROUP,
        "dataset": dataset,
        "subset": subset,
        "model": model,
        "protocol": spec["name"],
        "protocol_type": spec["type"],
        "pool": pool,
        "sampling": sampling_text(model, spec),
        "gallery_cached": bool(cached),
        "status": "failed" if error else "complete",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    if metrics is not None:
        row.update({key: float(metrics[key]) for key in METRIC_KEYS if key in metrics})
    if error is not None:
        row["error"] = str(error)[:2000]
    path = result_path(dataset, model, subset, spec["name"], pool)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(row, indent=2), encoding="utf-8")


def clean_cuda():
    gc.collect()
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def run_one(encoder, model, dataset, subset, spec, gpu_index):
    paths = expected_paths(dataset, model, subset, spec)
    if all(is_complete(path) for path in paths):
        print(f"skip {model} {dataset}/{subset} {spec['name']}", flush=True)
        return
    splits = load_split(subset)
    cache = DATA_ROOT / "frame_cache" / f"gpu{gpu_index}" / dataset
    batch = MODEL_BATCH.get(model, BATCH)
    text_batch = MODEL_TEXT_BATCH.get(model, TEXT_BATCH)
    print(f"== {PRETTY.get(model, model)} | {dataset}/{subset} | {spec['name']} ({sampling_text(model, spec)})", flush=True)
    try:
        if spec["type"] == "single":
            scored = {
                "none": evaluate_text_to_tracklet(
                    encoder,
                    splits,
                    num_frames=spec["num_frames"],
                    batch_size=batch,
                    text_batch_size=text_batch,
                    junk_same_camera=False,
                    frame_cache=cache,
                    frame_sample=spec["frame_sample"],
                )
            }
        else:
            scored = evaluate_text_to_tracklet_windows(
                encoder,
                splits,
                num_frames=NATIVE_FRAMES.get(model, 8),
                stride=spec["stride"],
                sample_fps=spec["sample_fps"],
                max_frames=spec["max_frames"],
                pools=POOLS,
                batch_size=batch,
                text_batch_size=text_batch,
                junk_same_camera=False,
                frame_cache=cache,
            )
    except RuntimeError as exc:
        pools = ["none"] if spec["type"] == "single" else list(POOLS)
        for pool in pools:
            save_row(dataset, model, subset, spec, pool, error=exc)
        if "out of memory" in str(exc).lower():
            raise StopModel(str(exc)) from exc
        raise
    for pool, metrics in scored.items():
        save_row(dataset, model, subset, spec, pool, metrics=metrics, cached=encoder.last_hit)
        print(f"-- {pool}: R1 {metrics['Rank-1']:.2f}  mAP {metrics['mAP']:.2f}  mINP {metrics.get('mINP', float('nan')):.2f}", flush=True)

In [6]:
if not torch.cuda.is_available():
    raise RuntimeError("A CUDA GPU is required for this benchmark")
if ON_KAGGLE and torch.cuda.device_count() < 2:
    raise RuntimeError("Select Kaggle GPU T4 x2; this notebook needs two visible GPUs")
GPU_COUNT = min(2, torch.cuda.device_count())
print(f"Using {GPU_COUNT} GPU worker(s): " + ", ".join(torch.cuda.get_device_name(i) for i in range(GPU_COUNT)), flush=True)
model_queue = Queue()
for model in MODELS:
    model_queue.put(model)


def run_gpu_worker(gpu_index):
    torch.cuda.set_device(gpu_index)
    device = f"cuda:{gpu_index}"
    ensure_cuda_healthy(device)
    while True:
        try:
            model = model_queue.get_nowait()
        except Empty:
            return
        jobs = [
            (dataset, spec, subset)
            for dataset in ("activitynet",)
            for spec in protocols_for(model)
            for subset in DATASETS["activitynet"]["subsets"]
        ]
        todo = [job for job in jobs if not all(is_complete(p) for p in expected_paths(job[0], model, job[2], job[1]))]
        print(f"\n######## GPU {gpu_index} | {PRETTY.get(model, model)}: {len(todo)} of {len(jobs)} runs to do", flush=True)
        if not todo:
            continue
        try:
            encoder = GalleryCache(build_encoder(model, device=device))
        except Exception:
            traceback.print_exc()
            print(f"Could not build {model} on GPU {gpu_index}; skipping it", flush=True)
            clean_cuda()
            continue
        try:
            for dataset, spec, subset in todo:
                run_one(encoder, model, dataset, subset, spec, gpu_index)
        except StopModel as exc:
            print(f"CUDA OOM on {model} (GPU {gpu_index}); stopping this model: {exc}", flush=True)
        finally:
            del encoder
            clean_cuda()


with ThreadPoolExecutor(max_workers=GPU_COUNT) as workers:
    futures = [workers.submit(run_gpu_worker, i) for i in range(GPU_COUNT)]
    for future in futures:
        future.result()  # propagate worker failures to the notebook

print("Done", flush=True)

Using 2 GPU worker(s): Tesla T4, Tesla T4

######## GPU 0 | InternVideo2-1B-s2: 10 of 10 runs to do

######## GPU 1 | LanguageBind: 8 of 8 runs to do

/usr/local/lib/python3.13/dist-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvl_clip_vision.py:148: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvideo2.py:148: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)

config.json:   0%|          | 0.00/4.61k [00:00<?, ?B/s]

/usr/local/lib/python3.13/dist-packages/timm/models/registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvideo2_clip_vision.py:143: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)

No module named 'deepspeed'
deepspeed is not installed!!!
Building InternVideo2-1B-s2 on CPU (flash-attn off, 4 frames, fp16 on CUDA)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.13GB

pytorch_model.bin: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB

model.safetensors: downloading bytes:           |  0.00B

LanguageBind loaded 1047/1047 tensors from pytorch_model.bin

tokenizer_config.json:   0%|          | 0.00/814 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/394 [00:00<?, ?it/s]

special_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

Could not build internvideo2_s2_1b on GPU 0; skipping it

Traceback (most recent call last):
  File "/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/bert/builder.py", line 31, in build_bert
    text_encoder, loading_info = BertForMaskedLM.from_pretrained(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        model_config.text_encoder.pretrained,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        local_files_only=True
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/transformers/modeling_utils.py", line 4293, in from_pretrained
    checkpoint_files, sharded_metadata = _get_resolved_checkpoint_files(
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        pretrained_model_name_or_path=pretrained_model_name_or_path,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        tqdm_class=tqdm_class,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/transformers/modeling_utils.py", line 745, in _get_resolved_checkpoint_files
    raise OSError(
    ...<2 lines>...
    )
OSError: bert-large-uncased does not appear to have a file named pytorch_model.bin or model.safetensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ipykernel_49/1306154321.py", line 32, in run_gpu_worker
    encoder = GalleryCache(build_encoder(model, device=device))
                           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/kaggle/working/shawaf-vlm/shawaf_vlm/models/registry.py", line 128, in build_encoder
    return builder(device=device)
  File "/kaggle/working/shawaf-vlm/shawaf_vlm/models/registry.py", line 158, in _build_internvideo2_s2_1b
    return build_internvideo2_s2_1b(device=device)
  File "/kaggle/working/shawaf-vlm/shawaf_vlm/models/internvideo2.py", line 344, in build_internvideo2_s2_1b
    return InternVideo2S2Encoder(device=device)
  File "/kaggle/working/shawaf-vlm/shawaf_vlm/models/internvideo2_s2.py", line 484, in __init__
    self.model = InternVideo2_Stage2_visual(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        config=config,
        ^^^^^^^^^^^^^^
        tokenizer=self.tokenizer,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
        is_pretrain=True,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/kaggle/working/InternVideo/InternVideo2/multi_modality/models/internvideo2_stage2_visual.py", line 36, in __init__
    self.text_encoder = self.build_text_encoder()
                        ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/kaggle/working/InternVideo/InternVideo2/multi_modality/models/internvideo2_stage2_visual.py", line 348, in build_text_encoder
    text_encoder = build_bert(
        self.config.model,
        self.is_pretrain,
        self.config.gradient_checkpointing,
    )
  File "/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/bert/builder.py", line 38, in build_bert
    text_encoder, loading_info = BertForMaskedLM.from_pretrained(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        model_config.text_encoder.pretrained,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        local_files_only=False
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/transformers/modeling_utils.py", line 4394, in from_pretrained
    loading_info = cls._finalize_model_loading(model, load_config, loading_info)
  File "/usr/local/lib/python3.13/dist-packages/transformers/modeling_utils.py", line 4568, in _finalize_model_loading
    model._adjust_missing_and_unexpected_keys(loading_info)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/transformers/modeling_utils.py", line 4871, in _adjust_missing_and_unexpected_keys
    unexpected_patterns = (self._keys_to_ignore_on_load_unexpected or set()) | additional_unexpected_patterns
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for |: 'list' and 'set'

######## GPU 0 | InternVideo2 CLIP-S: 8 of 8 runs to do
Model device: cuda:1 dtype=torch.float16 requested=cuda:1 (Tesla T4)
== LanguageBind | activitynet/paragraph | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

config.json:   0%|          | 0.00/4.32k [00:00<?, ?B/s]

config.py:   0%|          | 0.00/8.45k [00:00<?, ?B/s]

modeling_internvideo2encoder.py:   0%|          | 0.00/6.95k [00:00<?, ?B/s]

internvideo2_clip_vision.py:   0%|          | 0.00/21.9k [00:00<?, ?B/s]

pos_embed.py:   0%|          | 0.00/14.6k [00:00<?, ?B/s]

flash_attention_class.py:   0%|          | 0.00/3.26k [00:00<?, ?B/s]

mobile_clip.py:   0%|          | 0.00/9.62k [00:00<?, ?B/s]

mobile_clip_transformer.py:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

InternVideo2Config {
  "architectures": [
    "InternVideo2_CLIP_small"
  ],
  "auto_map": {
    "AutoConfig": "config.InternVideo2Config",
    "AutoModel": "modeling_internvideo2encoder.InternVideo2_CLIP_small"
  },
  "auto_resume": false,
  "batch_size": 64,
  "batch_size_test": 4,
  "best_key": [
    "msrvtt_1k_test_match",
    "t2v_r1"
  ],
  "compile_model": false,
  "criterion": {
    "clip_loss_ratio": [
      1.0,
      1.0
    ],
    "distill_final_features": true,
    "loss_weight": {
      "mlm": 1.0,
      "mvm": 0.0,
      "uta": 0.0,
      "vtc": 1.0,
      "vtm": 1.0
    },
    "mlm_masking_prob": 0.5,
    "vtm_hard_neg": true
  },
  "debug": false,
  "deep_fusion": false,
  "deepspeed": {
    "enable": true,
    "stage": 1
  },
  "delete_ds_optim_states": true,
  "device": "cuda",
  "dist_url": "env://",
  "dtype": "float16",
  "evaluate": false,
  "evaluation": {
    "eval_frame_ensemble": "concat",
    "eval_offload": true,
    "eval_x_only": false,
    "k_test": 128
  },
  "gradient_checkpointing": true,
  "inputs": {
    "batch_size": {
      "image": 64,
      "video": 64
    },
    "batch_size_test": {
      "image": 4,
      "video": 4
    },
    "image_res": 224,
    "max_txt_l": {
      "image": 32,
      "video": 32
    },
    "video_input": {
      "num_frames": 8,
      "num_frames_test": 8,
      "random_aug": false,
      "sample_type": "middle",
      "sample_type_test": "middle"
    }
  },
  "jump_evaluate": false,
  "log_freq": 100,
  "max_txt_l": 32,
  "mode": "pt",
  "model": {
    "embed_dim": 1024,
    "find_unused_parameters": false,
    "freeze_text": true,
    "freeze_vision": true,
    "load_vision_ckpt_from_internvideo2_stage2": false,
    "model_cls": "InternVideo2_CLIP_small",
    "multimodal": {
      "enable": true
    },
    "open_text_projection": false,
    "open_vision_clip_projector": true,
    "temp": 0.01,
    "temp_min": 0.01,
    "text_encoder": {
      "embed_dim": 512,
      "image_cfg": {
        "image_size": 224,
        "model_name": "vit_b16"
      },
      "text_cfg": {
        "causal_masking": true,
        "context_length": 77,
        "dim": 512,
        "ffn_multiplier_per_layer": 4.0,
        "model_name": "base",
        "n_heads_per_layer": 8,
        "n_transformer_layers": 12,
        "norm_layer": "layer_norm_fp32",
        "vocab_size": 49408
      }
    },
    "vision_encoder": {
      "align_dim": 512,
      "attn_pool_num_heads": 16,
      "checkpoint_num": 0,
      "clip_embed_dim": 768,
      "depth": 24,
      "drop_cls_token": false,
      "drop_path_rate": 0.0,
      "embed_dim": 1024,
      "fused_mlp_heuristic": 1,
      "head_drop_path_rate": 0.0,
      "img_size": 224,
      "in_chans": 3,
      "init_values": 0.1,
      "layerscale_no_force_fp32": true,
      "mlp_ratio": 4,
      "name": "internvideo2_1B",
      "num_frames": 8,
      "num_heads": 16,
      "patch_size": 14,
      "qk_normalization": true,
      "qkv_bias": false,
      "sep_pos_embed": false,
      "tubelet_size": 1,
      "use_checkpoint": false,
      "use_flash_attn": false,
      "use_fused_mlp": false,
      "use_fused_rmsnorm": false
    }
  },
  "model_type": "internvideo2",
  "num_frames": 8,
  "num_frames_test": 8,
  "num_workers": 6,
  "optimizer": {
    "different_lr": {
      "enable": false,
      "lr": 0.001,
      "module_names": []
    },
    "lr": 5e-05,
    "max_grad_norm": 3.0,
    "opt": "adamW",
    "opt_betas": [
      0.9,
      0.98
    ],
    "weight_decay": 0.05
  },
  "output_dir": null,
  "pretrained_path": "",
  "resume": false,
  "save_ckpt_iter": null,
  "save_latest": true,
  "scheduler": {
    "epochs": 10,
    "min_lr_multi": 0.01,
    "sched": "cosine",
    "warmup_epochs": 1
  },
  "seed": 42,
  "test_file": {
    "didemo_ret_test": "available_corpus[\"didemo_ret_test\"]",
    "msrvtt_1k_test": "available_corpus[\"msrvtt_1k_test\"]"
  },
  "test_types": [
    "msrvtt_1k_test",
    "didemo_ret_test"
  ],
  "text_enc": "bert_large",
  "tokenizer": null,
  "train_file": "available_corpus[\"pretrain_example_data_1B\"]",
  "transformers_version": "5.16.1",
  "use_bf16": true,
  "use_flash_sdp": false,
  "use_half_precision": false,
  "use_mem_efficient_sdp": false,
  "wandb": {
    "enable": false,
    "entity": "opengvlab",
    "project": "InternVideo2-Stage2"
  }
}

model.safetensors: reconstructing file:   0%|          |  0.00B /  746MB

model.safetensors: downloading bytes:           |  0.00B

InternVideo2 loaded 484/484 tensors (missing=0 unexpected=0)
Model device: cuda:0 dtype=torch.float16 requested=cuda:0 (Tesla T4)
== InternVideo2 CLIP-S | activitynet/paragraph | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:   6%|▋         | 32/500 [00:12<02:47,  2.80batch/s]
languagebind videos:   7%|▋         | 35/500 [00:13<02:45,  2.82batch/s]
languagebind videos:   7%|▋         | 37/500 [00:14<02:43,  2.83batch/s][A
languagebind videos:   8%|▊         | 39/500 [00:15<02:41,  2.86batch/s][A
languagebind videos:   8%|▊         | 41/500 [00:15<02:41,  2.85batch/s][A
languagebind videos:   9%|▊         | 43/500 [00:16<02:41,  2.84batch/s][A
languagebind videos:   9%|▉         | 45/500 [00:17<02:41,  2.82batch/s][A
languagebind videos:   9%|▉         | 46/500 [00:17<02:52,  2.63batch/s][A
languagebind videos:  10%|▉         | 48/500 [00:18<02:46,  2.72batch/s][A
languagebind videos:  10%|█         | 50/500 [00:19<02:43,  2.75batch/s][A
languagebind videos:  10%|█         | 52/500 [00:19<02:41,  2.77batch/s][A
languagebind videos:  11%|█         | 54/500 [00:20<02:39,  2.79batch/s]
languagebind videos:  11%|█         | 56/500 [00:21<02:39,  2.79batch/s]
languagebind videos:  11%|█▏        | 57/500 [00:21<02:39,  2.77batch/s]
languagebind videos:  12%|█▏        | 59/500 [00:22<02:38,  2.78batch/s]
languagebind videos:  12%|█▏        | 61/500 [00:23<02:46,  2.63batch/s]
languagebind videos:  13%|█▎        | 63/500 [00:23<02:42,  2.70batch/s]
languagebind videos:  13%|█▎        | 65/500 [00:24<02:39,  2.73batch/s]
languagebind videos:  13%|█▎        | 67/500 [00:25<02:37,  2.75batch/s]
languagebind videos:  14%|█▎        | 68/500 [00:25<02:38,  2.73batch/s]
languagebind videos:  14%|█▍        | 70/500 [00:26<02:37,  2.74batch/s]
languagebind videos:  14%|█▍        | 72/500 [00:27<02:38,  2.70batch/s]
languagebind videos:  15%|█▍        | 74/500 [00:27<02:36,  2.72batch/s]
languagebind videos:  15%|█▌        | 76/500 [00:28<02:34,  2.74batch/s]
languagebind videos:  16%|█▌        | 78/500 [00:29<02:33,  2.75batch/s]
languagebind videos:  16%|█▌        | 80/500 [00:30<02:32,  2.75batch/s]
languagebind videos:  16%|█▋        | 82/500 [00:30<02:31,  2.75batch/s]
languagebind videos:  17%|█▋        | 83/500 [00:31<02:32,  2.74batch/s]
languagebind videos:  17%|█▋        | 85/500 [00:31<02:32,  2.72batch/s]
languagebind videos:  17%|█▋        | 87/500 [00:32<02:31,  2.72batch/s]
languagebind videos:  18%|█▊        | 89/500 [00:33<02:38,  2.59batch/s]
languagebind videos:  18%|█▊        | 91/500 [00:34<02:33,  2.67batch/s]
languagebind videos:  18%|█▊        | 92/500 [00:34<02:31,  2.69batch/s]
languagebind videos:  19%|█▉        | 94/500 [00:35<02:30,  2.70batch/s]
languagebind videos:  19%|█▉        | 96/500 [00:36<02:30,  2.69batch/s]
languagebind videos:  20%|█▉        | 98/500 [00:36<02:28,  2.70batch/s]
languagebind videos:  20%|██        | 100/500 [00:37<02:27,  2.72batch/s][A
languagebind videos:  20%|██        | 102/500 [00:38<02:27,  2.70batch/s][A
languagebind videos:  21%|██        | 104/500 [00:38<02:26,  2.71batch/s][A
languagebind videos:  21%|██        | 106/500 [00:39<02:25,  2.71batch/s][A
languagebind videos:  21%|██▏       | 107/500 [00:40<02:25,  2.70batch/s][A
languagebind videos:  22%|██▏       | 109/500 [00:40<02:25,  2.68batch/s][A
languagebind videos:  22%|██▏       | 111/500 [00:41<02:26,  2.66batch/s][A
languagebind videos:  23%|██▎       | 113/500 [00:42<02:25,  2.66batch/s][A
languagebind videos:  23%|██▎       | 115/500 [00:43<02:31,  2.53batch/s][A
languagebind videos:  23%|██▎       | 116/500 [00:43<02:29,  2.57batch/s][A
languagebind videos:  24%|██▎       | 118/500 [00:44<02:26,  2.61batch/s][A
languagebind videos:  24%|██▍       | 120/500 [00:45<02:25,  2.61batch/s][A
languagebind videos:  24%|██▍       | 122/500 [00:45<02:24,  2.61batch/s][A
languagebind videos:  25%|██▍       | 124/500 [00:46<02:23,  2.63batch/s][A
languagebind videos:  25%|██▌       | 126/500 [00:47<02:21,  2.65batch/s][A
languagebind videos:  25%|██▌       | 127/500 [00:47<02:21,  2.64batch/s][A
languagebind videos:  26%|██▌       | 129/500 [00:48<02:23,  2.59batch/s][A
languagebind videos:  26%|██▌       | 131/500 [00:49<02:22,  2.59batch/s][A
languagebind videos:  27%|██▋       | 133/500 [00:50<02:21,  2.60batch/s][A
languagebind videos:  27%|██▋       | 135/500 [00:50<02:19,  2.61batch/s][A
languagebind videos:  27%|██▋       | 137/500 [00:51<02:18,  2.61batch/s][A
languagebind videos:  28%|██▊       | 138/500 [00:51<02:19,  2.59batch/s][A
languagebind videos:  28%|██▊       | 140/500 [00:52<02:18,  2.59batch/s][A
languagebind videos:  28%|██▊       | 142/500 [00:53<02:17,  2.60batch/s][A
languagebind videos:  29%|██▉       | 144/500 [00:54<02:16,  2.61batch/s][A
languagebind videos:  29%|██▉       | 146/500 [00:55<02:15,  2.61batch/s][A
languagebind videos:  29%|██▉       | 147/500 [00:55<02:15,  2.61batch/s][A
languagebind videos:  30%|██▉       | 149/500 [00:56<02:16,  2.58batch/s][A
languagebind videos:  30%|███       | 151/500 [00:56<02:16,  2.55batch/s][A
languagebind videos:  31%|███       | 153/500 [00:57<02:15,  2.55batch/s][A
languagebind videos:  31%|███       | 155/500 [00:58<02:15,  2.55batch/s][A
languagebind videos:  31%|███       | 156/500 [00:58<02:14,  2.56batch/s][A
languagebind videos:  32%|███▏      | 158/500 [00:59<02:16,  2.51batch/s][A
languagebind videos:  32%|███▏      | 160/500 [01:00<02:14,  2.53batch/s][A
languagebind videos:  32%|███▏      | 162/500 [01:01<02:12,  2.55batch/s][A
languagebind videos:  33%|███▎      | 164/500 [01:02<02:10,  2.56batch/s][A
languagebind videos:  33%|███▎      | 166/500 [01:02<02:12,  2.51batch/s][A
languagebind videos:  33%|███▎      | 167/500 [01:03<02:13,  2.49batch/s][A
languagebind videos:  34%|███▍      | 169/500 [01:04<02:11,  2.51batch/s][A
languagebind videos:  34%|███▍      | 171/500 [01:04<02:10,  2.52batch/s][A
languagebind videos:  35%|███▍      | 173/500 [01:05<02:09,  2.52batch/s][A
languagebind videos:  35%|███▌      | 175/500 [01:06<02:09,  2.51batch/s][A
languagebind videos:  35%|███▌      | 176/500 [01:06<02:10,  2.48batch/s][A
languagebind videos:  36%|███▌      | 178/500 [01:07<02:09,  2.49batch/s][A
languagebind videos:  36%|███▌      | 180/500 [01:08<02:07,  2.51batch/s][A
languagebind videos:  36%|███▋      | 182/500 [01:09<02:07,  2.50batch/s][A
languagebind videos:  37%|███▋      | 184/500 [01:10<02:06,  2.51batch/s][A
languagebind videos:  37%|███▋      | 185/500 [01:10<02:06,  2.49batch/s][A
languagebind videos:  37%|███▋      | 187/500 [01:11<02:07,  2.46batch/s][A
languagebind videos:  38%|███▊      | 189/500 [01:12<02:05,  2.48batch/s][A
languagebind videos:  38%|███▊      | 191/500 [01:12<02:04,  2.48batch/s][A
languagebind videos:  38%|███▊      | 192/500 [01:13<02:04,  2.46batch/s][A
languagebind videos:  39%|███▉      | 194/500 [01:14<02:04,  2.46batch/s][A
languagebind videos:  39%|███▉      | 196/500 [01:14<02:03,  2.46batch/s][A
languagebind videos:  40%|███▉      | 198/500 [01:15<02:03,  2.45batch/s][A
languagebind videos:  40%|████      | 200/500 [01:16<02:02,  2.45batch/s][A
languagebind videos:  40%|████      | 201/500 [01:16<02:01,  2.45batch/s][A
languagebind videos:  41%|████      | 203/500 [01:17<02:01,  2.44batch/s][A
languagebind videos:  41%|████      | 205/500 [01:18<02:01,  2.43batch/s][A
languagebind videos:  41%|████▏     | 207/500 [01:19<02:01,  2.42batch/s][A
languagebind videos:  42%|████▏     | 208/500 [01:19<02:00,  2.43batch/s][A
languagebind videos:  42%|████▏     | 210/500 [01:20<01:59,  2.43batch/s][A
languagebind videos:  42%|████▏     | 212/500 [01:21<01:58,  2.43batch/s][A
languagebind videos:  43%|████▎     | 214/500 [01:22<01:58,  2.42batch/s][A
languagebind videos:  43%|████▎     | 216/500 [01:23<01:56,  2.44batch/s][A
languagebind videos:  43%|████▎     | 217/500 [01:23<01:56,  2.43batch/s]
languagebind videos:  44%|████▍     | 219/500 [01:24<01:56,  2.41batch/s]
languagebind videos:  44%|████▍     | 221/500 [01:25<01:56,  2.40batch/s]
languagebind videos:  45%|████▍     | 223/500 [01:26<01:54,  2.41batch/s]
languagebind videos:  45%|████▌     | 225/500 [01:26<01:53,  2.42batch/s]
languagebind videos:  45%|████▌     | 226/500 [01:27<01:54,  2.40batch/s]
languagebind videos:  46%|████▌     | 228/500 [01:28<01:53,  2.40batch/s]
languagebind videos:  46%|████▌     | 230/500 [01:28<01:52,  2.40batch/s]
languagebind videos:  46%|████▋     | 232/500 [01:29<01:51,  2.40batch/s]
languagebind videos:  47%|████▋     | 234/500 [01:30<01:50,  2.40batch/s]
languagebind videos:  47%|████▋     | 235/500 [01:31<01:50,  2.39batch/s]
languagebind videos:  47%|████▋     | 237/500 [01:31<01:50,  2.38batch/s]
languagebind videos:  48%|████▊     | 239/500 [01:32<01:50,  2.37batch/s]
languagebind videos:  48%|████▊     | 241/500 [01:33<01:49,  2.36batch/s]
languagebind videos:  48%|████▊     | 242/500 [01:34<01:49,  2.35batch/s]
languagebind videos:  49%|████▉     | 244/500 [01:34<01:48,  2.35batch/s]
languagebind videos:  49%|████▉     | 246/500 [01:35<01:48,  2.35batch/s]
languagebind videos:  50%|████▉     | 248/500 [01:36<01:47,  2.34batch/s]
languagebind videos:  50%|████▉     | 249/500 [01:37<01:47,  2.34batch/s]
languagebind videos:  50%|█████     | 251/500 [01:37<01:47,  2.33batch/s]
languagebind videos:  51%|█████     | 253/500 [01:38<01:46,  2.33batch/s]
languagebind videos:  51%|█████     | 255/500 [01:39<01:45,  2.32batch/s]
languagebind videos:  51%|█████     | 256/500 [01:40<01:45,  2.31batch/s]
languagebind videos:  52%|█████▏    | 258/500 [01:40<01:45,  2.30batch/s]
languagebind videos:  52%|█████▏    | 260/500 [01:41<01:44,  2.30batch/s]
languagebind videos:  52%|█████▏    | 262/500 [01:42<01:43,  2.30batch/s]
languagebind videos:  53%|█████▎    | 263/500 [01:43<01:43,  2.30batch/s]
languagebind videos:  53%|█████▎    | 265/500 [01:43<01:43,  2.26batch/s]
languagebind videos:  53%|█████▎    | 267/500 [01:44<01:42,  2.28batch/s]
languagebind videos:  54%|█████▍    | 269/500 [01:45<01:41,  2.28batch/s]
languagebind videos:  54%|█████▍    | 270/500 [01:46<01:40,  2.28batch/s]
languagebind videos:  54%|█████▍    | 272/500 [01:47<01:40,  2.27batch/s]
languagebind videos:  55%|█████▍    | 274/500 [01:47<01:40,  2.24batch/s]
languagebind videos:  55%|█████▌    | 275/500 [01:48<01:40,  2.24batch/s]
languagebind videos:  55%|█████▌    | 277/500 [01:49<01:39,  2.24batch/s]
languagebind videos:  56%|█████▌    | 279/500 [01:50<01:39,  2.22batch/s]
languagebind videos:  56%|█████▌    | 281/500 [01:51<01:39,  2.21batch/s]
languagebind videos:  56%|█████▋    | 282/500 [01:51<01:38,  2.22batch/s]
languagebind videos:  57%|█████▋    | 284/500 [01:52<01:37,  2.21batch/s]
languagebind videos:  57%|█████▋    | 286/500 [01:53<01:36,  2.22batch/s]
languagebind videos:  57%|█████▋    | 287/500 [01:53<01:35,  2.22batch/s]
languagebind videos:  58%|█████▊    | 289/500 [01:54<01:35,  2.21batch/s]
languagebind videos:  58%|█████▊    | 291/500 [01:55<01:34,  2.20batch/s]
languagebind videos:  59%|█████▊    | 293/500 [01:56<01:34,  2.20batch/s]
languagebind videos:  59%|█████▉    | 294/500 [01:57<01:33,  2.20batch/s]
languagebind videos:  59%|█████▉    | 296/500 [01:57<01:33,  2.19batch/s]
languagebind videos:  60%|█████▉    | 298/500 [01:58<01:32,  2.18batch/s]
languagebind videos:  60%|█████▉    | 299/500 [01:59<01:32,  2.18batch/s]
languagebind videos:  60%|██████    | 301/500 [02:00<01:32,  2.16batch/s]
languagebind videos:  61%|██████    | 303/500 [02:01<01:31,  2.15batch/s]
languagebind videos:  61%|██████    | 304/500 [02:01<01:31,  2.14batch/s]
languagebind videos:  61%|██████    | 306/500 [02:02<01:30,  2.13batch/s]
languagebind videos:  62%|██████▏   | 308/500 [02:03<01:30,  2.13batch/s]
languagebind videos:  62%|██████▏   | 309/500 [02:04<01:30,  2.12batch/s]
languagebind videos:  62%|██████▏   | 311/500 [02:04<01:29,  2.11batch/s]
languagebind videos:  63%|██████▎   | 313/500 [02:05<01:28,  2.11batch/s]
languagebind videos:  63%|██████▎   | 314/500 [02:06<01:28,  2.10batch/s]
languagebind videos:  63%|██████▎   | 316/500 [02:07<01:28,  2.08batch/s]
languagebind videos:  64%|██████▎   | 318/500 [02:08<01:27,  2.09batch/s]
languagebind videos:  64%|██████▍   | 319/500 [02:08<01:26,  2.09batch/s]
languagebind videos:  64%|██████▍   | 321/500 [02:09<01:25,  2.09batch/s]
languagebind videos:  65%|██████▍   | 323/500 [02:10<01:25,  2.08batch/s]
languagebind videos:  65%|██████▍   | 324/500 [02:11<01:24,  2.08batch/s]
languagebind videos:  65%|██████▌   | 326/500 [02:12<01:24,  2.07batch/s]
languagebind videos:  66%|██████▌   | 328/500 [02:13<01:22,  2.08batch/s]
languagebind videos:  66%|██████▌   | 329/500 [02:13<01:21,  2.09batch/s]
languagebind videos:  66%|██████▌   | 331/500 [02:14<01:20,  2.09batch/s]
languagebind videos:  67%|██████▋   | 333/500 [02:15<01:19,  2.11batch/s]
languagebind videos:  67%|██████▋   | 334/500 [02:15<01:18,  2.11batch/s]
languagebind videos:  67%|██████▋   | 336/500 [02:16<01:17,  2.11batch/s]
languagebind videos:  68%|██████▊   | 338/500 [02:17<01:16,  2.12batch/s]
languagebind videos:  68%|██████▊   | 339/500 [02:18<01:15,  2.13batch/s]
languagebind videos:  68%|██████▊   | 341/500 [02:19<01:14,  2.14batch/s]
languagebind videos:  69%|██████▊   | 343/500 [02:20<01:12,  2.16batch/s]
languagebind videos:  69%|██████▉   | 345/500 [02:21<01:11,  2.16batch/s]
languagebind videos:  69%|██████▉   | 346/500 [02:21<01:11,  2.15batch/s]
languagebind videos:  70%|██████▉   | 348/500 [02:22<01:10,  2.17batch/s]
languagebind videos:  70%|███████   | 350/500 [02:23<01:08,  2.18batch/s]
languagebind videos:  70%|███████   | 351/500 [02:23<01:08,  2.19batch/s]
languagebind videos:  71%|███████   | 353/500 [02:24<01:07,  2.19batch/s]
languagebind videos:  71%|███████   | 355/500 [02:25<01:06,  2.19batch/s]
languagebind videos:  71%|███████   | 356/500 [02:26<01:05,  2.20batch/s]
languagebind videos:  72%|███████▏  | 358/500 [02:27<01:04,  2.22batch/s]
languagebind videos:  72%|███████▏  | 360/500 [02:27<01:02,  2.23batch/s]
languagebind videos:  72%|███████▏  | 362/500 [02:28<01:01,  2.25batch/s]
languagebind videos:  73%|███████▎  | 363/500 [02:29<01:00,  2.25batch/s]
languagebind videos:  73%|███████▎  | 365/500 [02:30<01:00,  2.24batch/s]
languagebind videos:  73%|███████▎  | 367/500 [02:30<00:59,  2.25batch/s]
languagebind videos:  74%|███████▎  | 368/500 [02:31<00:58,  2.26batch/s]
languagebind videos:  74%|███████▍  | 370/500 [02:32<00:57,  2.26batch/s]
languagebind videos:  74%|███████▍  | 372/500 [02:33<00:56,  2.27batch/s]
languagebind videos:  75%|███████▍  | 374/500 [02:34<00:55,  2.27batch/s]
languagebind videos:  75%|███████▌  | 376/500 [02:34<00:54,  2.28batch/s]
languagebind videos:  75%|███████▌  | 377/500 [02:35<00:54,  2.27batch/s]
languagebind videos:  76%|███████▌  | 379/500 [02:36<00:53,  2.28batch/s]
languagebind videos:  76%|███████▌  | 381/500 [02:37<00:51,  2.30batch/s]
languagebind videos:  76%|███████▋  | 382/500 [02:37<00:51,  2.30batch/s]
languagebind videos:  77%|███████▋  | 384/500 [02:38<00:50,  2.30batch/s]
languagebind videos:  77%|███████▋  | 386/500 [02:39<00:49,  2.30batch/s]
languagebind videos:  78%|███████▊  | 388/500 [02:40<00:48,  2.30batch/s]
languagebind videos:  78%|███████▊  | 389/500 [02:40<00:48,  2.30batch/s]
languagebind videos:  78%|███████▊  | 391/500 [02:41<00:47,  2.29batch/s]
languagebind videos:  79%|███████▊  | 393/500 [02:42<00:46,  2.30batch/s]
languagebind videos:  79%|███████▉  | 395/500 [02:43<00:45,  2.30batch/s]
languagebind videos:  79%|███████▉  | 396/500 [02:43<00:45,  2.31batch/s]
languagebind videos:  80%|███████▉  | 398/500 [02:44<00:44,  2.31batch/s]
languagebind videos:  80%|████████  | 400/500 [02:45<00:43,  2.31batch/s]
languagebind videos:  80%|████████  | 402/500 [02:46<00:42,  2.32batch/s]
languagebind videos:  81%|████████  | 403/500 [02:46<00:41,  2.33batch/s]
languagebind videos:  81%|████████  | 405/500 [02:47<00:41,  2.30batch/s]
languagebind videos:  81%|████████▏ | 407/500 [02:48<00:40,  2.28batch/s]
languagebind videos:  82%|████████▏ | 409/500 [02:49<00:39,  2.30batch/s]
languagebind videos:  82%|████████▏ | 410/500 [02:49<00:38,  2.31batch/s]
languagebind videos:  82%|████████▏ | 412/500 [02:50<00:38,  2.31batch/s]
languagebind videos:  83%|████████▎ | 414/500 [02:51<00:37,  2.31batch/s]
languagebind videos:  83%|████████▎ | 416/500 [02:52<00:36,  2.32batch/s]
languagebind videos:  83%|████████▎ | 417/500 [02:52<00:35,  2.32batch/s]
languagebind videos:  84%|████████▍ | 419/500 [02:53<00:35,  2.31batch/s]
languagebind videos:  84%|████████▍ | 421/500 [02:54<00:34,  2.32batch/s]
languagebind videos:  85%|████████▍ | 423/500 [02:55<00:33,  2.32batch/s]
languagebind videos:  85%|████████▍ | 424/500 [02:55<00:32,  2.32batch/s]
languagebind videos:  85%|████████▌ | 426/500 [02:56<00:32,  2.30batch/s]
languagebind videos:  86%|████████▌ | 428/500 [02:57<00:31,  2.30batch/s]
languagebind videos:  86%|████████▌ | 430/500 [02:58<00:30,  2.30batch/s]
languagebind videos:  86%|████████▌ | 431/500 [02:58<00:30,  2.29batch/s]
languagebind videos:  87%|████████▋ | 433/500 [02:59<00:29,  2.28batch/s]
languagebind videos:  87%|████████▋ | 435/500 [03:00<00:28,  2.29batch/s]
languagebind videos:  87%|████████▋ | 437/500 [03:01<00:27,  2.28batch/s]
languagebind videos:  88%|████████▊ | 438/500 [03:01<00:27,  2.28batch/s]
languagebind videos:  88%|████████▊ | 440/500 [03:02<00:26,  2.28batch/s]
languagebind videos:  88%|████████▊ | 442/500 [03:03<00:25,  2.28batch/s]
languagebind videos:  89%|████████▊ | 443/500 [03:04<00:25,  2.27batch/s]
languagebind videos:  89%|████████▉ | 445/500 [03:04<00:24,  2.26batch/s]
languagebind videos:  89%|████████▉ | 447/500 [03:05<00:23,  2.26batch/s]
languagebind videos:  90%|████████▉ | 449/500 [03:06<00:22,  2.26batch/s]
languagebind videos:  90%|█████████ | 450/500 [03:07<00:22,  2.26batch/s]
languagebind videos:  90%|█████████ | 452/500 [03:08<00:21,  2.23batch/s]
languagebind videos:  91%|█████████ | 454/500 [03:08<00:20,  2.24batch/s]
languagebind videos:  91%|█████████ | 456/500 [03:09<00:19,  2.25batch/s]
languagebind videos:  91%|█████████▏| 457/500 [03:10<00:19,  2.25batch/s]
languagebind videos:  92%|█████████▏| 459/500 [03:11<00:18,  2.23batch/s]
languagebind videos:  92%|█████████▏| 461/500 [03:12<00:17,  2.22batch/s]
languagebind videos:  92%|█████████▏| 462/500 [03:12<00:17,  2.23batch/s]
languagebind videos:  93%|█████████▎| 464/500 [03:13<00:16,  2.23batch/s]
languagebind videos:  93%|█████████▎| 466/500 [03:14<00:15,  2.21batch/s]
languagebind videos:  94%|█████████▎| 468/500 [03:15<00:14,  2.22batch/s]
languagebind videos:  94%|█████████▍| 469/500 [03:15<00:14,  2.21batch/s]
languagebind videos:  94%|█████████▍| 471/500 [03:16<00:13,  2.21batch/s]
languagebind videos:  95%|█████████▍| 473/500 [03:17<00:12,  2.21batch/s]
languagebind videos:  95%|█████████▍| 474/500 [03:17<00:11,  2.20batch/s]
languagebind videos:  95%|█████████▌| 476/500 [03:18<00:10,  2.20batch/s]
languagebind videos:  96%|█████████▌| 478/500 [03:19<00:09,  2.20batch/s]
languagebind videos:  96%|█████████▌| 479/500 [03:20<00:09,  2.20batch/s]
languagebind videos:  96%|█████████▌| 481/500 [03:21<00:08,  2.18batch/s]
languagebind videos:  97%|█████████▋| 483/500 [03:22<00:07,  2.19batch/s]
languagebind videos:  97%|█████████▋| 485/500 [03:23<00:06,  2.19batch/s]
languagebind videos:  97%|█████████▋| 486/500 [03:23<00:06,  2.15batch/s]
languagebind videos:  98%|█████████▊| 488/500 [03:24<00:05,  2.17batch/s]
languagebind videos:  98%|█████████▊| 490/500 [03:25<00:04,  2.18batch/s]
languagebind videos:  98%|█████████▊| 491/500 [03:25<00:04,  2.16batch/s]
languagebind videos:  99%|█████████▊| 493/500 [03:26<00:03,  2.16batch/s]
languagebind videos:  99%|█████████▉| 495/500 [03:27<00:02,  2.17batch/s]
languagebind videos:  99%|█████████▉| 496/500 [03:28<00:01,  2.17batch/s]
languagebind videos: 100%|█████████▉| 498/500 [03:29<00:00,  2.18batch/s]
languagebind videos: 100%|██████████| 500/500 [03:29<00:00,  2.38batch/s]
languagebind texts:   0%|          | 0/63 [00:00<?, ?batch/s]
languagebind texts:  40%|███▉      | 25/63 [00:00<00:00, 39.50batch/s]/s]

-- none: R1 59.60  mAP 72.04  mINP 72.04
== LanguageBind | activitynet/sentence | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind texts:  11%|█         | 25/227 [00:00<00:04, 46.97batch/s]s]
languagebind texts:  26%|██▋       | 60/227 [00:01<00:03, 45.93batch/s]s]
languagebind texts:  42%|████▏     | 95/227 [00:02<00:02, 45.02batch/s]s]
languagebind texts:  57%|█████▋    | 130/227 [00:02<00:02, 45.31batch/s]]
languagebind texts:  73%|███████▎  | 165/227 [00:03<00:01, 44.35batch/s]]
languagebind texts:  86%|████████▌ | 195/227 [00:04<00:00, 44.81batch/s]]
languagebind texts: 100%|██████████| 227/227 [00:05<00:00, 44.75batch/s]]

internvideo2 videos:  55%|█████▌    | 275/500 [03:24<02:54,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 276/500 [03:25<03:00,  1.24batch/s]
internvideo2 videos:  55%|█████▌    | 277/500 [03:26<03:04,  1.21batch/s]

-- none: R1 31.68  mAP 44.46  mINP 44.46
== LanguageBind | activitynet/paragraph | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  56%|█████▌    | 278/500 [03:27<03:09,  1.17batch/s]
internvideo2 videos:  56%|█████▌    | 279/500 [03:28<03:03,  1.21batch/s]
internvideo2 videos:  56%|█████▌    | 280/500 [03:29<02:58,  1.23batch/s]
internvideo2 videos:  56%|█████▌    | 281/500 [03:29<02:54,  1.25batch/s]
internvideo2 videos:  56%|█████▋    | 282/500 [03:30<02:52,  1.27batch/s]
internvideo2 videos:  57%|█████▋    | 283/500 [03:31<02:49,  1.28batch/s]
internvideo2 videos:  57%|█████▋    | 284/500 [03:32<02:48,  1.28batch/s]
internvideo2 videos:  57%|█████▋    | 285/500 [03:32<02:46,  1.29batch/s]
internvideo2 videos:  57%|█████▋    | 286/500 [03:33<02:45,  1.29batch/s]
internvideo2 videos:  57%|█████▋    | 287/500 [03:34<02:44,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 288/500 [03:35<02:43,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 289/500 [03:35<02:43,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 290/500 [03:36<02:42,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 291/500 [03:37<02:41,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 292/500 [03:38<02:40,  1.29batch/s]
internvideo2 videos:  59%|█████▊    | 293/500 [03:39<02:39,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 294/500 [03:39<02:39,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 295/500 [03:40<02:38,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 296/500 [03:41<02:37,  1.29batch/s]
internvideo2 videos:  59%|█████▉    | 297/500 [03:42<02:36,  1.29batch/s]
internvideo2 videos:  60%|█████▉    | 298/500 [03:42<02:35,  1.30batch/s]
internvideo2 videos:  60%|█████▉    | 299/500 [03:43<02:35,  1.29batch/s]
internvideo2 videos:  60%|██████    | 300/500 [03:44<02:34,  1.30batch/s]
internvideo2 videos:  60%|██████    | 301/500 [03:45<02:33,  1.30batch/s]
internvideo2 videos:  60%|██████    | 302/500 [03:46<02:32,  1.30batch/s]
internvideo2 videos:  61%|██████    | 303/500 [03:46<02:32,  1.29batch/s]
internvideo2 videos:  61%|██████    | 304/500 [03:47<02:32,  1.29batch/s]
internvideo2 videos:  61%|██████    | 305/500 [03:48<02:30,  1.29batch/s]
internvideo2 videos:  61%|██████    | 306/500 [03:49<02:29,  1.29batch/s]
internvideo2 videos:  61%|██████▏   | 307/500 [03:49<02:29,  1.29batch/s]
internvideo2 videos:  62%|██████▏   | 308/500 [03:50<02:28,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 309/500 [03:51<02:26,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 310/500 [03:52<02:26,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 311/500 [03:52<02:25,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 312/500 [03:53<02:25,  1.30batch/s]
internvideo2 videos:  63%|██████▎   | 313/500 [03:54<02:24,  1.30batch/s]
internvideo2 videos:  63%|██████▎   | 314/500 [03:55<02:23,  1.30batch/s]
internvideo2 videos:  63%|██████▎   | 315/500 [03:56<02:23,  1.29batch/s]
internvideo2 videos:  63%|██████▎   | 316/500 [03:56<02:22,  1.29batch/s]
internvideo2 videos:  63%|██████▎   | 317/500 [03:57<02:21,  1.29batch/s]
internvideo2 videos:  64%|██████▎   | 318/500 [03:58<02:21,  1.29batch/s]
internvideo2 videos:  64%|██████▍   | 319/500 [03:59<02:20,  1.29batch/s]
internvideo2 videos:  64%|██████▍   | 320/500 [03:59<02:19,  1.29batch/s]
internvideo2 videos:  64%|██████▍   | 321/500 [04:00<02:18,  1.29batch/s]
internvideo2 videos:  64%|██████▍   | 322/500 [04:01<02:17,  1.29batch/s]
internvideo2 videos:  65%|██████▍   | 323/500 [04:02<02:16,  1.30batch/s]
internvideo2 videos:  65%|██████▍   | 324/500 [04:03<02:15,  1.30batch/s]
internvideo2 videos:  65%|██████▌   | 325/500 [04:03<02:15,  1.30batch/s]
internvideo2 videos:  65%|██████▌   | 326/500 [04:04<02:14,  1.30batch/s]
internvideo2 videos:  65%|██████▌   | 327/500 [04:05<02:13,  1.30batch/s]
internvideo2 videos:  66%|██████▌   | 328/500 [04:06<02:12,  1.30batch/s]
internvideo2 videos:  66%|██████▌   | 329/500 [04:06<02:11,  1.30batch/s]
internvideo2 videos:  66%|██████▌   | 330/500 [04:07<02:11,  1.30batch/s]
internvideo2 videos:  66%|██████▌   | 331/500 [04:08<02:10,  1.30batch/s]
internvideo2 videos:  66%|██████▋   | 332/500 [04:09<02:09,  1.30batch/s]
internvideo2 videos:  67%|██████▋   | 333/500 [04:09<02:08,  1.30batch/s]
internvideo2 videos:  67%|██████▋   | 334/500 [04:10<02:08,  1.29batch/s]
internvideo2 videos:  67%|██████▋   | 335/500 [04:11<02:08,  1.29batch/s]
internvideo2 videos:  67%|██████▋   | 336/500 [04:12<02:07,  1.29batch/s]
internvideo2 videos:  67%|██████▋   | 337/500 [04:13<02:06,  1.29batch/s]
internvideo2 videos:  68%|██████▊   | 338/500 [04:13<02:05,  1.29batch/s]
internvideo2 videos:  68%|██████▊   | 339/500 [04:14<02:04,  1.29batch/s]
internvideo2 videos:  68%|██████▊   | 340/500 [04:15<02:04,  1.29batch/s]
internvideo2 videos:  68%|██████▊   | 341/500 [04:16<02:03,  1.29batch/s]
internvideo2 videos:  68%|██████▊   | 342/500 [04:16<02:03,  1.28batch/s]
internvideo2 videos:  69%|██████▊   | 343/500 [04:17<02:02,  1.28batch/s]
internvideo2 videos:  69%|██████▉   | 344/500 [04:18<02:01,  1.28batch/s]
internvideo2 videos:  69%|██████▉   | 345/500 [04:19<02:00,  1.28batch/s]
internvideo2 videos:  69%|██████▉   | 346/500 [04:20<02:00,  1.28batch/s]
internvideo2 videos:  69%|██████▉   | 347/500 [04:20<01:59,  1.28batch/s]
internvideo2 videos:  70%|██████▉   | 348/500 [04:21<01:58,  1.28batch/s]
internvideo2 videos:  70%|██████▉   | 349/500 [04:22<01:57,  1.28batch/s]
internvideo2 videos:  70%|███████   | 350/500 [04:23<01:56,  1.29batch/s]
internvideo2 videos:  70%|███████   | 351/500 [04:23<01:55,  1.29batch/s]
internvideo2 videos:  70%|███████   | 352/500 [04:24<01:55,  1.28batch/s]
internvideo2 videos:  71%|███████   | 353/500 [04:25<01:54,  1.28batch/s]
internvideo2 videos:  71%|███████   | 354/500 [04:26<01:53,  1.28batch/s]
internvideo2 videos:  71%|███████   | 355/500 [04:27<01:53,  1.28batch/s]
internvideo2 videos:  71%|███████   | 356/500 [04:27<01:52,  1.28batch/s]
internvideo2 videos:  71%|███████▏  | 357/500 [04:28<01:51,  1.28batch/s]
internvideo2 videos:  72%|███████▏  | 358/500 [04:29<01:50,  1.28batch/s]
internvideo2 videos:  72%|███████▏  | 359/500 [04:30<01:49,  1.29batch/s]
internvideo2 videos:  72%|███████▏  | 360/500 [04:30<01:49,  1.28batch/s]
internvideo2 videos:  72%|███████▏  | 361/500 [04:31<01:48,  1.28batch/s]
internvideo2 videos:  72%|███████▏  | 362/500 [04:32<01:48,  1.28batch/s]
internvideo2 videos:  73%|███████▎  | 363/500 [04:33<01:47,  1.28batch/s]
internvideo2 videos:  73%|███████▎  | 364/500 [04:34<01:46,  1.28batch/s]
internvideo2 videos:  73%|███████▎  | 365/500 [04:34<01:45,  1.28batch/s]
internvideo2 videos:  73%|███████▎  | 366/500 [04:35<01:44,  1.28batch/s]
internvideo2 videos:  73%|███████▎  | 367/500 [04:36<01:44,  1.28batch/s]
internvideo2 videos:  74%|███████▎  | 368/500 [04:37<01:43,  1.28batch/s]
internvideo2 videos:  74%|███████▍  | 369/500 [04:38<01:42,  1.28batch/s]
internvideo2 videos:  74%|███████▍  | 370/500 [04:38<01:41,  1.29batch/s]
internvideo2 videos:  74%|███████▍  | 371/500 [04:39<01:40,  1.29batch/s]
internvideo2 videos:  74%|███████▍  | 372/500 [04:40<01:39,  1.29batch/s]
internvideo2 videos:  75%|███████▍  | 373/500 [04:41<01:38,  1.28batch/s]
internvideo2 videos:  75%|███████▍  | 374/500 [04:41<01:37,  1.29batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

languagebind videos:   0%|          | 0/995 [00:00<?, ?batch/s]
languagebind videos:   0%|          | 2/995 [00:00<06:27,  2.56batch/s]s]
languagebind videos:   0%|          | 4/995 [00:01<06:14,  2.64batch/s]s]
languagebind videos:   1%|          | 6/995 [00:02<06:13,  2.65batch/s]s]
languagebind videos:   1%|          | 8/995 [00:03<06:19,  2.60batch/s]s]
languagebind videos:   1%|          | 10/995 [00:03<06:16,  2.62batch/s]]
languagebind videos:   1%|          | 12/995 [00:04<06:14,  2.62batch/s]]
languagebind videos:   1%|▏         | 14/995 [00:05<06:13,  2.63batch/s]]
languagebind videos:   2%|▏         | 16/995 [00:06<06:12,  2.63batch/s]]
languagebind videos:   2%|▏         | 19/995 [00:07<06:11,  2.63batch/s]]
languagebind videos:   2%|▏         | 21/995 [00:08<06:12,  2.62batch/s]]
languagebind videos:   2%|▏         | 23/995 [00:08<06:10,  2.63batch/s]]
languagebind videos:   3%|▎         | 25/995 [00:09<06:13,  2.59batch/s]]
languagebind videos:   3%|▎         | 27/995 [00:10<06:11,  2.61batch/s]]
languagebind videos:   3%|▎         | 29/995 [00:11<06:09,  2.62batch/s]]
languagebind videos:   3%|▎         | 31/995 [00:11<06:10,  2.61batch/s]]
languagebind videos:   3%|▎         | 33/995 [00:12<06:06,  2.63batch/s]]
languagebind videos:   4%|▎         | 35/995 [00:13<06:05,  2.63batch/s]]
languagebind videos:   4%|▎         | 37/995 [00:14<06:10,  2.59batch/s]]
languagebind videos:   4%|▍         | 39/995 [00:14<06:07,  2.60batch/s]]
languagebind videos:   4%|▍         | 41/995 [00:15<06:08,  2.59batch/s]]
languagebind videos:   4%|▍         | 43/995 [00:16<06:06,  2.60batch/s]]
languagebind videos:   5%|▍         | 45/995 [00:17<06:05,  2.60batch/s]]
languagebind videos:   5%|▍         | 47/995 [00:18<06:06,  2.59batch/s]]
languagebind videos:   5%|▍         | 49/995 [00:18<06:05,  2.59batch/s]]
languagebind videos:   5%|▌         | 51/995 [00:19<06:04,  2.59batch/s]]
languagebind videos:   5%|▌         | 53/995 [00:20<06:03,  2.59batch/s]]
languagebind videos:   6%|▌         | 55/995 [00:21<06:04,  2.58batch/s]]
languagebind videos:   6%|▌         | 57/995 [00:21<06:02,  2.59batch/s]]
languagebind videos:   6%|▌         | 59/995 [00:22<06:00,  2.59batch/s]]
languagebind videos:   6%|▌         | 61/995 [00:23<05:57,  2.62batch/s]]
languagebind videos:   6%|▋         | 63/995 [00:24<06:03,  2.56batch/s]]
languagebind videos:   7%|▋         | 65/995 [00:24<06:01,  2.57batch/s]]
languagebind videos:   7%|▋         | 67/995 [00:25<06:00,  2.57batch/s]]
languagebind videos:   7%|▋         | 69/995 [00:26<06:01,  2.56batch/s]]
languagebind videos:   7%|▋         | 71/995 [00:27<06:01,  2.56batch/s]]
languagebind videos:   7%|▋         | 73/995 [00:28<06:00,  2.56batch/s]]
languagebind videos:   7%|▋         | 74/995 [00:28<06:02,  2.54batch/s]]
languagebind videos:   8%|▊         | 76/995 [00:29<06:01,  2.54batch/s]]
languagebind videos:   8%|▊         | 78/995 [00:30<06:00,  2.54batch/s]]
languagebind videos:   8%|▊         | 80/995 [00:30<06:00,  2.54batch/s]]
languagebind videos:   8%|▊         | 82/995 [00:31<06:02,  2.52batch/s]]
languagebind videos:   8%|▊         | 84/995 [00:32<06:02,  2.51batch/s]]
languagebind videos:   9%|▊         | 86/995 [00:33<05:59,  2.53batch/s]]
languagebind videos:   9%|▉         | 88/995 [00:34<05:56,  2.54batch/s]]
languagebind videos:   9%|▉         | 90/995 [00:34<05:54,  2.55batch/s]]
languagebind videos:   9%|▉         | 92/995 [00:35<05:54,  2.55batch/s]]
languagebind videos:   9%|▉         | 94/995 [00:36<05:55,  2.54batch/s]]
languagebind videos:  10%|▉         | 96/995 [00:37<05:54,  2.54batch/s]]
languagebind videos:  10%|▉         | 98/995 [00:37<05:52,  2.55batch/s]]
languagebind videos:  10%|█         | 100/995 [00:38<05:51,  2.55batch/s]
languagebind videos:  10%|█         | 102/995 [00:39<05:52,  2.54batch/s]
languagebind videos:  10%|█         | 104/995 [00:40<05:52,  2.53batch/s]
languagebind videos:  11%|█         | 106/995 [00:41<05:52,  2.52batch/s]
languagebind videos:  11%|█         | 108/995 [00:41<05:52,  2.52batch/s]
languagebind videos:  11%|█         | 110/995 [00:42<05:52,  2.51batch/s]
languagebind videos:  11%|█         | 111/995 [00:43<05:51,  2.51batch/s]
languagebind videos:  11%|█▏        | 113/995 [00:43<05:51,  2.51batch/s]
languagebind videos:  12%|█▏        | 115/995 [00:44<05:53,  2.49batch/s]
languagebind videos:  12%|█▏        | 117/995 [00:45<05:52,  2.49batch/s]
languagebind videos:  12%|█▏        | 119/995 [00:46<05:50,  2.50batch/s]
languagebind videos:  12%|█▏        | 121/995 [00:47<05:47,  2.51batch/s]
languagebind videos:  12%|█▏        | 123/995 [00:47<05:48,  2.51batch/s]
languagebind videos:  13%|█▎        | 125/995 [00:48<05:48,  2.49batch/s]
languagebind videos:  13%|█▎        | 127/995 [00:49<05:48,  2.49batch/s]
languagebind videos:  13%|█▎        | 129/995 [00:50<05:48,  2.48batch/s]
languagebind videos:  13%|█▎        | 131/995 [00:51<05:48,  2.48batch/s]
languagebind videos:  13%|█▎        | 133/995 [00:51<05:49,  2.47batch/s]
languagebind videos:  13%|█▎        | 134/995 [00:52<05:49,  2.47batch/s]
languagebind videos:  14%|█▎        | 136/995 [00:53<05:50,  2.45batch/s]
languagebind videos:  14%|█▍        | 138/995 [00:53<05:52,  2.43batch/s]
languagebind videos:  14%|█▍        | 140/995 [00:54<05:51,  2.43batch/s]
languagebind videos:  14%|█▍        | 142/995 [00:55<05:54,  2.41batch/s]
languagebind videos:  14%|█▍        | 144/995 [00:56<05:50,  2.43batch/s]
languagebind videos:  15%|█▍        | 146/995 [00:57<05:49,  2.43batch/s]
languagebind videos:  15%|█▍        | 148/995 [00:58<05:48,  2.43batch/s]
languagebind videos:  15%|█▌        | 150/995 [00:58<05:45,  2.45batch/s]
languagebind videos:  15%|█▌        | 151/995 [00:59<05:45,  2.45batch/s]
languagebind videos:  15%|█▌        | 153/995 [01:00<05:46,  2.43batch/s]
languagebind videos:  16%|█▌        | 155/995 [01:00<05:46,  2.42batch/s]
languagebind videos:  16%|█▌        | 157/995 [01:01<05:47,  2.41batch/s]
languagebind videos:  16%|█▌        | 159/995 [01:02<05:45,  2.42batch/s]
languagebind videos:  16%|█▌        | 161/995 [01:03<05:44,  2.42batch/s]
languagebind videos:  16%|█▋        | 163/995 [01:04<05:44,  2.42batch/s]
languagebind videos:  17%|█▋        | 165/995 [01:05<05:42,  2.43batch/s]
languagebind videos:  17%|█▋        | 167/995 [01:05<05:42,  2.42batch/s]
languagebind videos:  17%|█▋        | 168/995 [01:06<05:45,  2.39batch/s]
languagebind videos:  17%|█▋        | 170/995 [01:07<05:42,  2.41batch/s]
languagebind videos:  17%|█▋        | 172/995 [01:08<05:40,  2.42batch/s]
languagebind videos:  17%|█▋        | 174/995 [01:08<05:37,  2.43batch/s]
languagebind videos:  18%|█▊        | 176/995 [01:09<05:38,  2.42batch/s]
languagebind videos:  18%|█▊        | 178/995 [01:10<05:36,  2.43batch/s]
languagebind videos:  18%|█▊        | 180/995 [01:11<05:36,  2.42batch/s]
languagebind videos:  18%|█▊        | 182/995 [01:12<05:35,  2.42batch/s]
languagebind videos:  18%|█▊        | 183/995 [01:12<05:36,  2.41batch/s]
languagebind videos:  19%|█▊        | 185/995 [01:13<05:36,  2.41batch/s]
languagebind videos:  19%|█▉        | 187/995 [01:14<05:35,  2.41batch/s]
languagebind videos:  19%|█▉        | 189/995 [01:15<05:33,  2.42batch/s]
languagebind videos:  19%|█▉        | 191/995 [01:15<05:31,  2.42batch/s]
languagebind videos:  19%|█▉        | 193/995 [01:16<05:29,  2.43batch/s]
languagebind videos:  20%|█▉        | 195/995 [01:17<05:30,  2.42batch/s]
languagebind videos:  20%|█▉        | 196/995 [01:17<05:30,  2.41batch/s]
languagebind videos:  20%|█▉        | 198/995 [01:18<05:32,  2.40batch/s]
languagebind videos:  20%|██        | 200/995 [01:19<05:28,  2.42batch/s]
languagebind videos:  20%|██        | 202/995 [01:20<05:27,  2.42batch/s]
languagebind videos:  21%|██        | 204/995 [01:21<05:27,  2.42batch/s]
languagebind videos:  21%|██        | 206/995 [01:22<05:25,  2.43batch/s]
languagebind videos:  21%|██        | 208/995 [01:22<05:26,  2.41batch/s]
languagebind videos:  21%|██        | 209/995 [01:23<05:25,  2.41batch/s]
languagebind videos:  21%|██        | 211/995 [01:24<05:28,  2.39batch/s]
languagebind videos:  21%|██▏       | 213/995 [01:25<05:25,  2.40batch/s]
languagebind videos:  22%|██▏       | 215/995 [01:25<05:23,  2.41batch/s]
languagebind videos:  22%|██▏       | 217/995 [01:26<05:22,  2.42batch/s]
languagebind videos:  22%|██▏       | 219/995 [01:27<05:21,  2.41batch/s]
languagebind videos:  22%|██▏       | 221/995 [01:28<05:21,  2.41batch/s]
languagebind videos:  22%|██▏       | 222/995 [01:28<05:21,  2.40batch/s]
languagebind videos:  23%|██▎       | 224/995 [01:29<05:21,  2.40batch/s]
languagebind videos:  23%|██▎       | 226/995 [01:30<05:21,  2.39batch/s]
languagebind videos:  23%|██▎       | 228/995 [01:31<05:21,  2.38batch/s]
languagebind videos:  23%|██▎       | 230/995 [01:32<05:19,  2.40batch/s]
languagebind videos:  23%|██▎       | 232/995 [01:32<05:14,  2.43batch/s]
languagebind videos:  24%|██▎       | 234/995 [01:33<05:11,  2.44batch/s]
languagebind videos:  24%|██▎       | 235/995 [01:34<05:11,  2.44batch/s]
languagebind videos:  24%|██▍       | 237/995 [01:34<05:11,  2.43batch/s]
languagebind videos:  24%|██▍       | 239/995 [01:35<05:10,  2.43batch/s]
languagebind videos:  24%|██▍       | 241/995 [01:36<05:08,  2.44batch/s]
internvideo2 videos: 100%|██████████| 500/500 [06:19<00:00,  1.32batch/s]

internvideo2 texts:   0%|          | 0/63 [00:00<?, ?batch/s]
languagebind videos:  24%|██▍       | 242/995 [01:36<05:08,  2.44batch/s]
internvideo2 texts:  16%|█▌        | 10/63 [00:00<00:01, 41.95batch/s]
internvideo2 texts:  24%|██▍       | 15/63 [00:00<00:01, 38.00batch/s]
languagebind videos:  24%|██▍       | 243/995 [01:37<05:10,  2.42batch/s]
internvideo2 texts:  43%|████▎     | 27/63 [00:00<00:00, 44.05batch/s]
internvideo2 texts:  51%|█████     | 32/63 [00:00<00:00, 41.64batch/s]
internvideo2 texts:  59%|█████▊    | 37/63 [00:00<00:00, 43.74batch/s]
languagebind videos:  25%|██▍       | 244/995 [01:37<05:14,  2.39batch/s]
internvideo2 texts:  76%|███████▌  | 48/63 [00:01<00:00, 46.06batch/s]
internvideo2 texts:  84%|████████▍ | 53/63 [00:01<00:00, 42.03batch/s]
internvideo2 texts: 100%|██████████| 63/63 [00:01<00:00, 45.04batch/s]
languagebind videos:  25%|██▍       | 246/995 [01:38<05:45,  2.17batch/s]

-- none: R1 65.00  mAP 76.98  mINP 76.98
== InternVideo2 CLIP-S | activitynet/sentence | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:  25%|██▍       | 247/995 [01:39<07:02,  1.77batch/s]
internvideo2 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
internvideo2 texts:   2%|▏         | 5/227 [00:00<00:04, 48.76batch/s]
internvideo2 texts:   5%|▌         | 12/227 [00:00<00:03, 58.73batch/s]
languagebind videos:  25%|██▍       | 248/995 [01:40<06:38,  1.88batch/s]A
internvideo2 texts:  12%|█▏        | 27/227 [00:00<00:03, 60.83batch/s]
internvideo2 texts:  15%|█▍        | 34/227 [00:00<00:03, 54.17batch/s]
languagebind videos:  25%|██▌       | 249/995 [01:40<06:10,  2.01batch/s]A
internvideo2 texts:  21%|██        | 48/227 [00:00<00:02, 60.12batch/s]
internvideo2 texts:  24%|██▍       | 55/227 [00:01<00:03, 48.51batch/s]
languagebind videos:  25%|██▌       | 250/995 [01:40<05:54,  2.10batch/s]A
internvideo2 texts:  31%|███       | 70/227 [00:01<00:02, 58.50batch/s]
internvideo2 texts:  34%|███▍      | 77/227 [00:01<00:02, 53.37batch/s]
internvideo2 texts:  37%|███▋      | 83/227 [00:01<00:02, 54.00batch/s]
languagebind videos:  25%|██▌       | 251/995 [01:41<05:39,  2.19batch/s]A
internvideo2 texts:  42%|████▏     | 95/227 [00:01<00:02, 47.33batch/s]
internvideo2 texts:  44%|████▍     | 101/227 [00:01<00:02, 46.83batch/s]
languagebind videos:  25%|██▌       | 252/995 [01:41<05:32,  2.24batch/s][A
internvideo2 texts:  50%|████▉     | 113/227 [00:02<00:02, 49.34batch/s]
internvideo2 texts:  52%|█████▏    | 119/227 [00:02<00:02, 50.88batch/s]
internvideo2 texts:  56%|█████▌    | 127/227 [00:02<00:01, 57.45batch/s]
languagebind videos:  25%|██▌       | 253/995 [01:42<05:24,  2.29batch/s][A
internvideo2 texts:  63%|██████▎   | 142/227 [00:02<00:01, 55.41batch/s]
internvideo2 texts:  66%|██████▌   | 149/227 [00:02<00:01, 57.37batch/s]
languagebind videos:  26%|██▌       | 254/995 [01:42<05:21,  2.30batch/s][A
internvideo2 texts:  72%|███████▏  | 163/227 [00:02<00:01, 61.33batch/s]
internvideo2 texts:  75%|███████▍  | 170/227 [00:03<00:00, 57.44batch/s]
internvideo2 texts:  78%|███████▊  | 178/227 [00:03<00:00, 61.67batch/s]
languagebind videos:  26%|██▌       | 255/995 [01:43<05:20,  2.31batch/s][A
internvideo2 texts:  85%|████████▌ | 193/227 [00:03<00:00, 55.10batch/s]
internvideo2 texts:  88%|████████▊ | 200/227 [00:03<00:00, 57.11batch/s]
languagebind videos:  26%|██▌       | 256/995 [01:43<05:18,  2.32batch/s][A
internvideo2 texts:  95%|█████████▍| 215/227 [00:03<00:00, 57.12batch/s]
internvideo2 texts:  97%|█████████▋| 221/227 [00:03<00:00, 51.47batch/s]
internvideo2 texts: 100%|██████████| 227/227 [00:04<00:00, 55.50batch/s]
languagebind videos:  26%|██▋       | 262/995 [01:46<06:09,  1.98batch/s]

-- none: R1 33.78  mAP 47.44  mINP 47.44
== InternVideo2 CLIP-S | activitynet/paragraph | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:  43%|████▎     | 428/995 [03:01<04:10,  2.27batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

languagebind videos:  43%|████▎     | 430/995 [03:02<04:06,  2.29batch/s]
languagebind videos:  43%|████▎     | 431/995 [03:03<04:05,  2.30batch/s]A
languagebind videos:  44%|████▎     | 433/995 [03:04<04:04,  2.30batch/s]A
languagebind videos:  44%|████▎     | 435/995 [03:04<04:02,  2.30batch/s]A
languagebind videos:  44%|████▍     | 436/995 [03:05<04:03,  2.29batch/s]A
languagebind videos:  44%|████▍     | 438/995 [03:06<04:01,  2.30batch/s]A
languagebind videos:  44%|████▍     | 439/995 [03:06<04:00,  2.31batch/s]A
languagebind videos:  44%|████▍     | 441/995 [03:07<04:00,  2.30batch/s]A
languagebind videos:  45%|████▍     | 443/995 [03:08<03:59,  2.31batch/s]A
languagebind videos:  45%|████▍     | 444/995 [03:08<03:58,  2.31batch/s]A
languagebind videos:  45%|████▍     | 446/995 [03:09<03:57,  2.31batch/s][A
languagebind videos:  45%|████▍     | 447/995 [03:10<03:56,  2.32batch/s][A
languagebind videos:  45%|████▌     | 449/995 [03:11<03:57,  2.29batch/s][A
languagebind videos:  45%|████▌     | 451/995 [03:11<03:55,  2.31batch/s][A
languagebind videos:  45%|████▌     | 452/995 [03:12<03:54,  2.31batch/s][A
languagebind videos:  46%|████▌     | 454/995 [03:13<03:54,  2.31batch/s][A
languagebind videos:  46%|████▌     | 456/995 [03:14<03:52,  2.31batch/s][A
languagebind videos:  46%|████▌     | 457/995 [03:14<03:53,  2.31batch/s][A
languagebind videos:  46%|████▌     | 459/995 [03:15<03:52,  2.30batch/s][A
languagebind videos:  46%|████▌     | 460/995 [03:15<03:51,  2.31batch/s][A
languagebind videos:  46%|████▋     | 462/995 [03:16<03:51,  2.31batch/s][A
languagebind videos:  47%|████▋     | 464/995 [03:17<03:50,  2.30batch/s][A
languagebind videos:  47%|████▋     | 465/995 [03:17<03:49,  2.31batch/s][A
languagebind videos:  47%|████▋     | 467/995 [03:18<03:48,  2.32batch/s][A
languagebind videos:  47%|████▋     | 469/995 [03:19<03:47,  2.31batch/s][A
languagebind videos:  47%|████▋     | 470/995 [03:20<03:47,  2.31batch/s][A
languagebind videos:  47%|████▋     | 472/995 [03:21<03:47,  2.30batch/s][A
languagebind videos:  48%|████▊     | 473/995 [03:21<03:46,  2.30batch/s][A
languagebind videos:  48%|████▊     | 475/995 [03:22<03:47,  2.29batch/s][A
languagebind videos:  48%|████▊     | 477/995 [03:23<03:46,  2.28batch/s][A
languagebind videos:  48%|████▊     | 478/995 [03:23<03:47,  2.27batch/s][A
languagebind videos:  48%|████▊     | 480/995 [03:24<03:47,  2.26batch/s][A
languagebind videos:  48%|████▊     | 481/995 [03:24<03:46,  2.27batch/s][A
languagebind videos:  49%|████▊     | 483/995 [03:25<03:46,  2.26batch/s][A
languagebind videos:  49%|████▊     | 485/995 [03:26<03:45,  2.26batch/s][A
languagebind videos:  49%|████▉     | 486/995 [03:27<03:45,  2.26batch/s][A
languagebind videos:  49%|████▉     | 488/995 [03:28<03:44,  2.26batch/s][A
languagebind videos:  49%|████▉     | 489/995 [03:28<03:43,  2.26batch/s][A
languagebind videos:  49%|████▉     | 491/995 [03:29<03:44,  2.24batch/s][A
languagebind videos:  50%|████▉     | 493/995 [03:30<03:43,  2.25batch/s][A
languagebind videos:  50%|████▉     | 494/995 [03:30<03:42,  2.25batch/s][A
languagebind videos:  50%|████▉     | 496/995 [03:31<03:42,  2.24batch/s][A
languagebind videos:  50%|█████     | 498/995 [03:32<03:42,  2.24batch/s][A
languagebind videos:  50%|█████     | 499/995 [03:32<03:42,  2.23batch/s][A
languagebind videos:  50%|█████     | 501/995 [03:33<03:41,  2.23batch/s][A
languagebind videos:  50%|█████     | 502/995 [03:34<03:41,  2.23batch/s][A
languagebind videos:  51%|█████     | 504/995 [03:35<03:40,  2.22batch/s][A
languagebind videos:  51%|█████     | 506/995 [03:36<03:40,  2.22batch/s][A
languagebind videos:  51%|█████     | 507/995 [03:36<03:39,  2.22batch/s][A
languagebind videos:  51%|█████     | 509/995 [03:37<03:39,  2.21batch/s][A
languagebind videos:  51%|█████▏    | 510/995 [03:37<03:39,  2.21batch/s][A
languagebind videos:  51%|█████▏    | 512/995 [03:38<03:38,  2.21batch/s][A
languagebind videos:  52%|█████▏    | 514/995 [03:39<03:38,  2.21batch/s][A
languagebind videos:  52%|█████▏    | 515/995 [03:40<03:38,  2.20batch/s][A
languagebind videos:  52%|█████▏    | 517/995 [03:41<03:36,  2.21batch/s][A
languagebind videos:  52%|█████▏    | 518/995 [03:41<03:36,  2.21batch/s][A
languagebind videos:  52%|█████▏    | 520/995 [03:42<03:36,  2.20batch/s][A
languagebind videos:  52%|█████▏    | 522/995 [03:43<03:35,  2.19batch/s][A
languagebind videos:  53%|█████▎    | 523/995 [03:43<03:36,  2.18batch/s][A
languagebind videos:  53%|█████▎    | 525/995 [03:44<03:36,  2.17batch/s][A
languagebind videos:  53%|█████▎    | 526/995 [03:45<03:36,  2.17batch/s][A
languagebind videos:  53%|█████▎    | 528/995 [03:46<03:37,  2.15batch/s][A
languagebind videos:  53%|█████▎    | 529/995 [03:46<03:35,  2.16batch/s][A
languagebind videos:  53%|█████▎    | 531/995 [03:47<03:35,  2.15batch/s][A
languagebind videos:  54%|█████▎    | 533/995 [03:48<03:34,  2.15batch/s][A
languagebind videos:  54%|█████▎    | 534/995 [03:48<03:34,  2.15batch/s][A
languagebind videos:  54%|█████▍    | 536/995 [03:49<03:33,  2.15batch/s][A
languagebind videos:  54%|█████▍    | 537/995 [03:50<03:33,  2.15batch/s][A
languagebind videos:  54%|█████▍    | 539/995 [03:51<03:31,  2.16batch/s][A
languagebind videos:  54%|█████▍    | 540/995 [03:51<03:31,  2.16batch/s][A
languagebind videos:  54%|█████▍    | 542/995 [03:52<03:30,  2.15batch/s][A
languagebind videos:  55%|█████▍    | 544/995 [03:53<03:30,  2.14batch/s][A
languagebind videos:  55%|█████▍    | 545/995 [03:54<03:30,  2.14batch/s][A
languagebind videos:  55%|█████▍    | 547/995 [03:55<03:29,  2.14batch/s][A
languagebind videos:  55%|█████▌    | 548/995 [03:55<03:28,  2.14batch/s][A
languagebind videos:  55%|█████▌    | 550/995 [03:56<03:27,  2.14batch/s][A
languagebind videos:  55%|█████▌    | 551/995 [03:56<03:26,  2.15batch/s][A
languagebind videos:  56%|█████▌    | 553/995 [03:57<03:24,  2.16batch/s][A
languagebind videos:  56%|█████▌    | 555/995 [03:58<03:22,  2.17batch/s][A
languagebind videos:  56%|█████▌    | 556/995 [03:59<03:21,  2.18batch/s][A
languagebind videos:  56%|█████▌    | 558/995 [04:00<03:24,  2.14batch/s][A
languagebind videos:  56%|█████▌    | 559/995 [04:00<03:23,  2.14batch/s][A
languagebind videos:  56%|█████▋    | 561/995 [04:01<03:22,  2.14batch/s][A
languagebind videos:  57%|█████▋    | 563/995 [04:02<03:20,  2.16batch/s][A
languagebind videos:  57%|█████▋    | 564/995 [04:02<03:20,  2.15batch/s][A
languagebind videos:  57%|█████▋    | 566/995 [04:03<03:17,  2.17batch/s][A
languagebind videos:  57%|█████▋    | 567/995 [04:04<03:17,  2.17batch/s][A
languagebind videos:  57%|█████▋    | 569/995 [04:05<03:15,  2.18batch/s][A
languagebind videos:  57%|█████▋    | 571/995 [04:06<03:14,  2.18batch/s][A
languagebind videos:  57%|█████▋    | 572/995 [04:06<03:13,  2.18batch/s][A
languagebind videos:  58%|█████▊    | 574/995 [04:07<03:11,  2.19batch/s][A
languagebind videos:  58%|█████▊    | 575/995 [04:07<03:10,  2.20batch/s][A
languagebind videos:  58%|█████▊    | 577/995 [04:08<03:09,  2.20batch/s][A
languagebind videos:  58%|█████▊    | 579/995 [04:09<03:08,  2.21batch/s][A
languagebind videos:  58%|█████▊    | 580/995 [04:10<03:07,  2.21batch/s][A
languagebind videos:  58%|█████▊    | 582/995 [04:11<03:05,  2.22batch/s][A
languagebind videos:  59%|█████▊    | 583/995 [04:11<03:05,  2.22batch/s][A
languagebind videos:  59%|█████▉    | 585/995 [04:12<03:04,  2.22batch/s][A
languagebind videos:  59%|█████▉    | 587/995 [04:13<03:03,  2.23batch/s][A
languagebind videos:  59%|█████▉    | 588/995 [04:13<03:03,  2.22batch/s][A
languagebind videos:  59%|█████▉    | 590/995 [04:14<03:03,  2.21batch/s]
languagebind videos:  59%|█████▉    | 592/995 [04:15<03:00,  2.23batch/s]
languagebind videos:  60%|█████▉    | 593/995 [04:16<02:59,  2.23batch/s]
languagebind videos:  60%|█████▉    | 595/995 [04:16<02:58,  2.24batch/s]
languagebind videos:  60%|██████    | 597/995 [04:17<02:56,  2.25batch/s]
languagebind videos:  60%|██████    | 598/995 [04:18<02:56,  2.25batch/s]
languagebind videos:  60%|██████    | 600/995 [04:19<02:55,  2.25batch/s]
languagebind videos:  61%|██████    | 602/995 [04:20<02:54,  2.25batch/s]
languagebind videos:  61%|██████    | 603/995 [04:20<02:53,  2.25batch/s]
languagebind videos:  61%|██████    | 605/995 [04:21<02:52,  2.26batch/s]
languagebind videos:  61%|██████    | 607/995 [04:22<02:51,  2.27batch/s]
languagebind videos:  61%|██████    | 608/995 [04:22<02:51,  2.26batch/s]
languagebind videos:  61%|██████▏   | 610/995 [04:23<02:49,  2.27batch/s]
languagebind videos:  61%|██████▏   | 611/995 [04:23<02:49,  2.27batch/s]
languagebind videos:  62%|██████▏   | 613/995 [04:24<02:48,  2.26batch/s]
languagebind videos:  62%|██████▏   | 615/995 [04:25<02:47,  2.27batch/s]
languagebind videos:  62%|██████▏   | 616/995 [04:26<02:47,  2.27batch/s]
languagebind videos:  62%|██████▏   | 618/995 [04:27<02:46,  2.26batch/s]
languagebind videos:  62%|██████▏   | 620/995 [04:27<02:45,  2.27batch/s]
languagebind videos:  62%|██████▏   | 621/995 [04:28<02:44,  2.27batch/s]
languagebind videos:  63%|██████▎   | 623/995 [04:29<02:43,  2.27batch/s]
languagebind videos:  63%|██████▎   | 625/995 [04:30<02:42,  2.28batch/s]
languagebind videos:  63%|██████▎   | 626/995 [04:30<02:41,  2.28batch/s]
languagebind videos:  63%|██████▎   | 628/995 [04:31<02:41,  2.27batch/s]
languagebind videos:  63%|██████▎   | 630/995 [04:32<02:40,  2.28batch/s]
languagebind videos:  63%|██████▎   | 631/995 [04:32<02:39,  2.28batch/s]
languagebind videos:  64%|██████▎   | 633/995 [04:33<02:39,  2.27batch/s]
languagebind videos:  64%|██████▍   | 635/995 [04:34<02:38,  2.27batch/s]
languagebind videos:  64%|██████▍   | 636/995 [04:34<02:38,  2.27batch/s]
languagebind videos:  64%|██████▍   | 638/995 [04:35<02:37,  2.27batch/s]
languagebind videos:  64%|██████▍   | 640/995 [04:36<02:36,  2.27batch/s]
languagebind videos:  64%|██████▍   | 641/995 [04:37<02:36,  2.27batch/s]
languagebind videos:  65%|██████▍   | 643/995 [04:38<02:35,  2.26batch/s]
languagebind videos:  65%|██████▍   | 645/995 [04:38<02:34,  2.27batch/s]
languagebind videos:  65%|██████▍   | 646/995 [04:39<02:33,  2.27batch/s]
languagebind videos:  65%|██████▌   | 648/995 [04:40<02:32,  2.27batch/s]
languagebind videos:  65%|██████▌   | 650/995 [04:41<02:32,  2.27batch/s]
languagebind videos:  65%|██████▌   | 651/995 [04:41<02:31,  2.27batch/s]
languagebind videos:  66%|██████▌   | 653/995 [04:42<02:30,  2.27batch/s]
languagebind videos:  66%|██████▌   | 655/995 [04:43<02:29,  2.27batch/s]
languagebind videos:  66%|██████▌   | 656/995 [04:43<02:28,  2.28batch/s]
languagebind videos:  66%|██████▌   | 658/995 [04:44<02:29,  2.25batch/s]
languagebind videos:  66%|██████▋   | 660/995 [04:45<02:29,  2.24batch/s]
languagebind videos:  66%|██████▋   | 661/995 [04:46<02:29,  2.24batch/s]
languagebind videos:  67%|██████▋   | 663/995 [04:46<02:28,  2.24batch/s]
languagebind videos:  67%|██████▋   | 665/995 [04:47<02:27,  2.24batch/s]
languagebind videos:  67%|██████▋   | 666/995 [04:48<02:27,  2.24batch/s]
languagebind videos:  67%|██████▋   | 668/995 [04:49<02:26,  2.23batch/s]
languagebind videos:  67%|██████▋   | 670/995 [04:50<02:26,  2.21batch/s]
languagebind videos:  67%|██████▋   | 671/995 [04:50<02:27,  2.20batch/s]
languagebind videos:  68%|██████▊   | 673/995 [04:51<02:25,  2.21batch/s]
languagebind videos:  68%|██████▊   | 674/995 [04:51<02:24,  2.22batch/s]
languagebind videos:  68%|██████▊   | 676/995 [04:52<02:23,  2.22batch/s]
languagebind videos:  68%|██████▊   | 678/995 [04:53<02:22,  2.23batch/s]
languagebind videos:  68%|██████▊   | 679/995 [04:54<02:21,  2.23batch/s]
languagebind videos:  68%|██████▊   | 681/995 [04:55<02:20,  2.23batch/s]
languagebind videos:  69%|██████▊   | 683/995 [04:55<02:20,  2.22batch/s]
languagebind videos:  69%|██████▊   | 684/995 [04:56<02:20,  2.22batch/s]
languagebind videos:  69%|██████▉   | 686/995 [04:57<02:19,  2.21batch/s]
languagebind videos:  69%|██████▉   | 688/995 [04:58<02:18,  2.22batch/s]
languagebind videos:  69%|██████▉   | 689/995 [04:58<02:18,  2.21batch/s]
languagebind videos:  69%|██████▉   | 691/995 [04:59<02:17,  2.22batch/s]
languagebind videos:  70%|██████▉   | 693/995 [05:00<02:16,  2.22batch/s]
languagebind videos:  70%|██████▉   | 694/995 [05:00<02:15,  2.22batch/s]
languagebind videos:  70%|██████▉   | 696/995 [05:01<02:15,  2.21batch/s]
languagebind videos:  70%|███████   | 698/995 [05:02<02:14,  2.20batch/s]
languagebind videos:  70%|███████   | 699/995 [05:03<02:14,  2.20batch/s]
languagebind videos:  70%|███████   | 701/995 [05:04<02:13,  2.20batch/s]
languagebind videos:  71%|███████   | 703/995 [05:04<02:12,  2.21batch/s]
languagebind videos:  71%|███████   | 704/995 [05:05<02:12,  2.20batch/s]
languagebind videos:  71%|███████   | 706/995 [05:06<02:11,  2.20batch/s]
languagebind videos:  71%|███████   | 707/995 [05:06<02:11,  2.19batch/s]
languagebind videos:  71%|███████▏  | 709/995 [05:07<02:11,  2.18batch/s]
languagebind videos:  71%|███████▏  | 711/995 [05:08<02:09,  2.19batch/s]
languagebind videos:  72%|███████▏  | 712/995 [05:09<02:09,  2.18batch/s]
languagebind videos:  72%|███████▏  | 714/995 [05:10<02:08,  2.18batch/s]
languagebind videos:  72%|███████▏  | 716/995 [05:10<02:07,  2.19batch/s]
languagebind videos:  72%|███████▏  | 717/995 [05:11<02:06,  2.20batch/s]
languagebind videos:  72%|███████▏  | 719/995 [05:12<02:05,  2.19batch/s]
languagebind videos:  72%|███████▏  | 721/995 [05:13<02:04,  2.20batch/s]
languagebind videos:  73%|███████▎  | 722/995 [05:13<02:03,  2.20batch/s]
languagebind videos:  73%|███████▎  | 724/995 [05:14<02:03,  2.19batch/s]
languagebind videos:  73%|███████▎  | 726/995 [05:15<02:02,  2.19batch/s]
languagebind videos:  73%|███████▎  | 727/995 [05:15<02:02,  2.19batch/s]
languagebind videos:  73%|███████▎  | 729/995 [05:16<02:01,  2.19batch/s]
languagebind videos:  73%|███████▎  | 731/995 [05:17<02:00,  2.19batch/s]
languagebind videos:  74%|███████▎  | 732/995 [05:18<02:00,  2.19batch/s]
languagebind videos:  74%|███████▍  | 734/995 [05:19<01:58,  2.20batch/s]
languagebind videos:  74%|███████▍  | 736/995 [05:20<01:57,  2.21batch/s]
languagebind videos:  74%|███████▍  | 737/995 [05:20<01:56,  2.21batch/s]
languagebind videos:  74%|███████▍  | 739/995 [05:21<01:56,  2.20batch/s]
languagebind videos:  74%|███████▍  | 740/995 [05:21<01:55,  2.20batch/s]
languagebind videos:  75%|███████▍  | 742/995 [05:22<01:54,  2.21batch/s]
languagebind videos:  75%|███████▍  | 744/995 [05:23<01:54,  2.20batch/s]
languagebind videos:  75%|███████▍  | 746/995 [05:24<01:52,  2.21batch/s]
languagebind videos:  75%|███████▌  | 747/995 [05:25<01:53,  2.19batch/s]
languagebind videos:  75%|███████▌  | 749/995 [05:25<01:52,  2.19batch/s]
languagebind videos:  75%|███████▌  | 750/995 [05:26<01:51,  2.20batch/s]
languagebind videos:  76%|███████▌  | 752/995 [05:27<01:50,  2.20batch/s]
languagebind videos:  76%|███████▌  | 754/995 [05:28<01:49,  2.20batch/s]
languagebind videos:  76%|███████▌  | 755/995 [05:28<01:48,  2.22batch/s]
languagebind videos:  76%|███████▌  | 757/995 [05:29<01:47,  2.21batch/s]
languagebind videos:  76%|███████▋  | 759/995 [05:30<01:46,  2.22batch/s]
languagebind videos:  76%|███████▋  | 760/995 [05:30<01:45,  2.23batch/s]
languagebind videos:  77%|███████▋  | 762/995 [05:31<01:44,  2.23batch/s]
languagebind videos:  77%|███████▋  | 764/995 [05:32<01:44,  2.22batch/s]
languagebind videos:  77%|███████▋  | 765/995 [05:33<01:43,  2.22batch/s]
languagebind videos:  77%|███████▋  | 767/995 [05:34<01:42,  2.22batch/s]
languagebind videos:  77%|███████▋  | 769/995 [05:34<01:41,  2.23batch/s]
languagebind videos:  77%|███████▋  | 770/995 [05:35<01:40,  2.24batch/s]
languagebind videos:  78%|███████▊  | 772/995 [05:36<01:40,  2.23batch/s]
languagebind videos:  78%|███████▊  | 774/995 [05:37<01:38,  2.23batch/s]
languagebind videos:  78%|███████▊  | 775/995 [05:37<01:38,  2.23batch/s]
languagebind videos:  78%|███████▊  | 777/995 [05:38<01:37,  2.23batch/s]
languagebind videos:  78%|███████▊  | 779/995 [05:39<01:36,  2.24batch/s]
languagebind videos:  78%|███████▊  | 781/995 [05:40<01:35,  2.24batch/s]
languagebind videos:  79%|███████▊  | 782/995 [05:40<01:35,  2.23batch/s]
languagebind videos:  79%|███████▉  | 784/995 [05:41<01:34,  2.23batch/s]
languagebind videos:  79%|███████▉  | 786/995 [05:42<01:33,  2.24batch/s]
languagebind videos:  79%|███████▉  | 787/995 [05:43<01:32,  2.24batch/s]
languagebind videos:  79%|███████▉  | 789/995 [05:43<01:31,  2.24batch/s]
languagebind videos:  79%|███████▉  | 791/995 [05:44<01:31,  2.24batch/s]
languagebind videos:  80%|███████▉  | 792/995 [05:45<01:30,  2.24batch/s]
languagebind videos:  80%|███████▉  | 794/995 [05:46<01:29,  2.25batch/s]
languagebind videos:  80%|████████  | 796/995 [05:47<01:28,  2.25batch/s]
languagebind videos:  80%|████████  | 797/995 [05:47<01:28,  2.25batch/s]
languagebind videos:  80%|████████  | 799/995 [05:48<01:27,  2.24batch/s]
languagebind videos:  81%|████████  | 801/995 [05:49<01:26,  2.24batch/s]
languagebind videos:  81%|████████  | 802/995 [05:49<01:25,  2.25batch/s]
languagebind videos:  81%|████████  | 804/995 [05:50<01:25,  2.24batch/s]
languagebind videos:  81%|████████  | 806/995 [05:51<01:23,  2.25batch/s]
languagebind videos:  81%|████████  | 807/995 [05:51<01:23,  2.25batch/s]
languagebind videos:  81%|████████▏ | 809/995 [05:52<01:24,  2.21batch/s]
languagebind videos:  82%|████████▏ | 811/995 [05:53<01:23,  2.21batch/s]
languagebind videos:  82%|████████▏ | 812/995 [05:54<01:22,  2.23batch/s]
languagebind videos:  82%|████████▏ | 814/995 [05:55<01:21,  2.23batch/s]
languagebind videos:  82%|████████▏ | 816/995 [05:55<01:19,  2.24batch/s]
languagebind videos:  82%|████████▏ | 818/995 [05:56<01:18,  2.25batch/s]
languagebind videos:  82%|████████▏ | 819/995 [05:57<01:18,  2.24batch/s]
languagebind videos:  83%|████████▎ | 821/995 [05:58<01:17,  2.25batch/s]
languagebind videos:  83%|████████▎ | 823/995 [05:59<01:16,  2.26batch/s]
languagebind videos:  83%|████████▎ | 824/995 [05:59<01:15,  2.25batch/s]
languagebind videos:  83%|████████▎ | 826/995 [06:00<01:15,  2.25batch/s]
languagebind videos:  83%|████████▎ | 828/995 [06:01<01:14,  2.25batch/s]
languagebind videos:  83%|████████▎ | 829/995 [06:01<01:13,  2.25batch/s]
languagebind videos:  84%|████████▎ | 831/995 [06:02<01:13,  2.24batch/s]
languagebind videos:  84%|████████▎ | 833/995 [06:03<01:12,  2.24batch/s]
languagebind videos:  84%|████████▍ | 834/995 [06:03<01:11,  2.25batch/s]
languagebind videos:  84%|████████▍ | 836/995 [06:04<01:10,  2.25batch/s]
languagebind videos:  84%|████████▍ | 838/995 [06:05<01:09,  2.25batch/s]
languagebind videos:  84%|████████▍ | 839/995 [06:06<01:09,  2.25batch/s]
languagebind videos:  85%|████████▍ | 841/995 [06:07<01:08,  2.25batch/s]
languagebind videos:  85%|████████▍ | 843/995 [06:07<01:07,  2.25batch/s]
languagebind videos:  85%|████████▍ | 845/995 [06:08<01:06,  2.25batch/s]
languagebind videos:  85%|████████▌ | 846/995 [06:09<01:06,  2.24batch/s]
languagebind videos:  85%|████████▌ | 848/995 [06:10<01:05,  2.24batch/s]
languagebind videos:  85%|████████▌ | 850/995 [06:11<01:04,  2.24batch/s]
languagebind videos:  86%|████████▌ | 851/995 [06:11<01:04,  2.24batch/s]
languagebind videos:  86%|████████▌ | 853/995 [06:12<01:03,  2.25batch/s]
languagebind videos:  86%|████████▌ | 855/995 [06:13<01:02,  2.25batch/s]
languagebind videos:  86%|████████▌ | 856/995 [06:13<01:01,  2.24batch/s]
languagebind videos:  86%|████████▌ | 858/995 [06:14<01:01,  2.24batch/s]
languagebind videos:  86%|████████▋ | 860/995 [06:15<01:00,  2.24batch/s]
languagebind videos:  87%|████████▋ | 861/995 [06:15<00:59,  2.25batch/s]
languagebind videos:  87%|████████▋ | 863/995 [06:16<00:58,  2.25batch/s]
languagebind videos:  87%|████████▋ | 865/995 [06:17<00:57,  2.26batch/s]
languagebind videos:  87%|████████▋ | 866/995 [06:18<00:57,  2.25batch/s]

-- mean: R1 60.40  mAP 73.02  mINP 73.02
-- mean_s8: R1 60.40  mAP 73.02  mINP 73.02
-- max: R1 59.70  mAP 72.33  mINP 72.33
-- query_max: R1 60.70  mAP 73.13  mINP 73.13
== LanguageBind | activitynet/sentence | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  35%|███▌      | 349/995 [04:19<09:14,  1.17batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

languagebind texts:  12%|█▏        | 28/227 [00:00<00:04, 45.17batch/s]
languagebind texts:  28%|██▊       | 63/227 [00:01<00:03, 47.05batch/s]s]
languagebind texts:  43%|████▎     | 98/227 [00:02<00:02, 46.63batch/s]s]
languagebind texts:  59%|█████▊    | 133/227 [00:02<00:02, 45.62batch/s]]
languagebind texts:  74%|███████▍  | 168/227 [00:03<00:01, 45.59batch/s]]
languagebind texts:  89%|████████▉ | 203/227 [00:04<00:00, 44.81batch/s]]
languagebind texts: 100%|██████████| 227/227 [00:05<00:00, 45.11batch/s]]

internvideo2 videos:  36%|███▌      | 356/995 [04:24<08:17,  1.28batch/s]
internvideo2 videos:  36%|███▌      | 357/995 [04:25<08:29,  1.25batch/s]
internvideo2 videos:  36%|███▌      | 358/995 [04:26<08:41,  1.22batch/s]
internvideo2 videos:  36%|███▌      | 359/995 [04:27<08:47,  1.21batch/s]
internvideo2 videos:  36%|███▌      | 360/995 [04:28<08:56,  1.18batch/s]
internvideo2 videos:  36%|███▋      | 361/995 [04:28<08:58,  1.18batch/s]
internvideo2 videos:  36%|███▋      | 362/995 [04:29<09:04,  1.16batch/s]
internvideo2 videos:  36%|███▋      | 363/995 [04:30<08:59,  1.17batch/s]
internvideo2 videos:  37%|███▋      | 364/995 [04:31<08:54,  1.18batch/s]
internvideo2 videos:  37%|███▋      | 365/995 [04:32<08:54,  1.18batch/s]
internvideo2 videos:  37%|███▋      | 366/995 [04:33<08:58,  1.17batch/s]
internvideo2 videos:  37%|███▋      | 367/995 [04:34<09:15,  1.13batch/s]
internvideo2 videos:  37%|███▋      | 368/995 [04:35<09:10,  1.14batch/s]
internvideo2 videos:  37%|███▋      | 369/995 [04:35<09:06,  1.15batch/s]

-- mean: R1 31.90  mAP 45.07  mINP 45.07
-- mean_s8: R1 31.90  mAP 45.07  mINP 45.07
-- max: R1 32.26  mAP 45.10  mINP 45.10
-- query_max: R1 32.84  mAP 45.94  mINP 45.94
== LanguageBind | activitynet/paragraph | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  37%|███▋      | 370/995 [04:36<09:05,  1.15batch/s]
internvideo2 videos:  37%|███▋      | 371/995 [04:37<08:45,  1.19batch/s]
internvideo2 videos:  37%|███▋      | 372/995 [04:38<08:31,  1.22batch/s]
internvideo2 videos:  37%|███▋      | 373/995 [04:39<08:21,  1.24batch/s]
internvideo2 videos:  38%|███▊      | 374/995 [04:39<08:14,  1.26batch/s]
internvideo2 videos:  38%|███▊      | 375/995 [04:40<08:08,  1.27batch/s]
internvideo2 videos:  38%|███▊      | 376/995 [04:41<08:05,  1.28batch/s]
internvideo2 videos:  38%|███▊      | 377/995 [04:42<08:02,  1.28batch/s]
internvideo2 videos:  38%|███▊      | 378/995 [04:42<08:00,  1.28batch/s]
internvideo2 videos:  38%|███▊      | 379/995 [04:43<07:58,  1.29batch/s]
internvideo2 videos:  38%|███▊      | 380/995 [04:44<07:56,  1.29batch/s]
internvideo2 videos:  38%|███▊      | 381/995 [04:45<07:55,  1.29batch/s]
internvideo2 videos:  38%|███▊      | 382/995 [04:46<07:56,  1.29batch/s]
internvideo2 videos:  38%|███▊      | 383/995 [04:46<07:56,  1.28batch/s]
internvideo2 videos:  39%|███▊      | 384/995 [04:47<07:56,  1.28batch/s]
internvideo2 videos:  39%|███▊      | 385/995 [04:48<07:56,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 386/995 [04:49<07:53,  1.29batch/s]
internvideo2 videos:  39%|███▉      | 387/995 [04:49<07:55,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 388/995 [04:50<07:54,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 389/995 [04:51<07:53,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 390/995 [04:52<07:51,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 391/995 [04:53<07:51,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 392/995 [04:53<07:48,  1.29batch/s]
internvideo2 videos:  39%|███▉      | 393/995 [04:54<07:48,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 394/995 [04:55<07:46,  1.29batch/s]
internvideo2 videos:  40%|███▉      | 395/995 [04:56<07:45,  1.29batch/s]
internvideo2 videos:  40%|███▉      | 396/995 [04:56<07:45,  1.29batch/s]
internvideo2 videos:  40%|███▉      | 397/995 [04:57<07:45,  1.28batch/s]
internvideo2 videos:  40%|████      | 398/995 [04:58<07:43,  1.29batch/s]
internvideo2 videos:  40%|████      | 399/995 [04:59<07:42,  1.29batch/s]
internvideo2 videos:  40%|████      | 400/995 [05:00<07:42,  1.29batch/s]
internvideo2 videos:  40%|████      | 401/995 [05:00<07:40,  1.29batch/s]
internvideo2 videos:  40%|████      | 402/995 [05:01<07:40,  1.29batch/s]
internvideo2 videos:  41%|████      | 403/995 [05:02<07:40,  1.29batch/s]
internvideo2 videos:  41%|████      | 404/995 [05:03<07:40,  1.28batch/s]
internvideo2 videos:  41%|████      | 405/995 [05:03<07:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 406/995 [05:04<07:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 407/995 [05:05<07:38,  1.28batch/s]
internvideo2 videos:  41%|████      | 408/995 [05:06<07:36,  1.29batch/s]
internvideo2 videos:  41%|████      | 409/995 [05:07<07:36,  1.28batch/s]
internvideo2 videos:  41%|████      | 410/995 [05:07<07:33,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 411/995 [05:08<07:32,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 412/995 [05:09<07:30,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 413/995 [05:10<07:29,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 414/995 [05:10<07:28,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 415/995 [05:11<07:27,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 416/995 [05:12<07:30,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 417/995 [05:13<07:28,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 418/995 [05:13<07:26,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 419/995 [05:14<07:25,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 420/995 [05:15<07:24,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 421/995 [05:16<07:22,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 422/995 [05:17<07:22,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 423/995 [05:17<07:21,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 424/995 [05:18<07:18,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 425/995 [05:19<07:20,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 426/995 [05:20<07:19,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 427/995 [05:20<07:17,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 428/995 [05:21<07:17,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 429/995 [05:22<07:16,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 430/995 [05:23<07:15,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 431/995 [05:24<07:14,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 432/995 [05:24<07:14,  1.30batch/s]
internvideo2 videos:  44%|████▎     | 433/995 [05:25<07:13,  1.30batch/s]
internvideo2 videos:  44%|████▎     | 434/995 [05:26<07:12,  1.30batch/s]
internvideo2 videos:  44%|████▎     | 435/995 [05:27<07:13,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 436/995 [05:27<07:12,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 437/995 [05:28<07:11,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 438/995 [05:29<07:08,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 439/995 [05:30<07:07,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 440/995 [05:30<07:06,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 441/995 [05:31<07:07,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 442/995 [05:32<07:06,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 443/995 [05:33<07:04,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 444/995 [05:34<07:03,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 445/995 [05:34<07:03,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 446/995 [05:35<07:03,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 447/995 [05:36<07:04,  1.29batch/s]
internvideo2 videos:  45%|████▌     | 448/995 [05:37<07:04,  1.29batch/s]
internvideo2 videos:  45%|████▌     | 449/995 [05:37<07:01,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 450/995 [05:38<06:58,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 451/995 [05:39<06:58,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 452/995 [05:40<06:57,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 453/995 [05:40<06:57,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 454/995 [05:41<06:56,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 455/995 [05:42<06:56,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 456/995 [05:43<06:55,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 457/995 [05:44<06:54,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 458/995 [05:44<06:54,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 459/995 [05:45<06:53,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 460/995 [05:46<06:52,  1.30batch/s]
internvideo2 videos:  46%|████▋     | 461/995 [05:47<06:51,  1.30batch/s]
internvideo2 videos:  46%|████▋     | 462/995 [05:47<06:51,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 463/995 [05:48<06:50,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 464/995 [05:49<06:49,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 465/995 [05:50<06:49,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 466/995 [05:51<06:48,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 467/995 [05:51<06:47,  1.30batch/s]
internvideo2 videos:  47%|████▋     | 468/995 [05:52<06:48,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 469/995 [05:53<06:47,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 470/995 [05:54<06:47,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 471/995 [05:54<06:46,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 472/995 [05:55<06:45,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 473/995 [05:56<06:43,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 474/995 [05:57<06:42,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 475/995 [05:57<06:41,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 476/995 [05:58<06:40,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 477/995 [05:59<06:40,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 478/995 [06:00<06:39,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 479/995 [06:01<06:38,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 480/995 [06:01<06:37,  1.30batch/s]
internvideo2 videos:  48%|████▊     | 481/995 [06:02<06:36,  1.29batch/s]
internvideo2 videos:  48%|████▊     | 482/995 [06:03<06:36,  1.29batch/s]
internvideo2 videos:  49%|████▊     | 483/995 [06:04<06:35,  1.30batch/s]
internvideo2 videos:  49%|████▊     | 484/995 [06:04<06:34,  1.30batch/s]
internvideo2 videos:  49%|████▊     | 485/995 [06:05<06:35,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 486/995 [06:06<06:35,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 487/995 [06:07<06:34,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 488/995 [06:08<06:32,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 489/995 [06:08<06:32,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 490/995 [06:09<06:31,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 491/995 [06:10<06:29,  1.29batch/s]
internvideo2 videos:  49%|████▉     | 492/995 [06:11<06:28,  1.29batch/s]
internvideo2 videos:  50%|████▉     | 493/995 [06:11<06:27,  1.29batch/s]
internvideo2 videos:  50%|████▉     | 494/995 [06:12<06:26,  1.30batch/s]
internvideo2 videos:  50%|████▉     | 495/995 [06:13<06:25,  1.30batch/s]
internvideo2 videos:  50%|████▉     | 496/995 [06:14<06:25,  1.30batch/s]
internvideo2 videos:  50%|████▉     | 497/995 [06:14<06:25,  1.29batch/s]
internvideo2 videos:  50%|█████     | 498/995 [06:15<06:24,  1.29batch/s]
internvideo2 videos:  50%|█████     | 499/995 [06:16<06:23,  1.29batch/s]
internvideo2 videos:  50%|█████     | 500/995 [06:17<06:22,  1.29batch/s]
internvideo2 videos:  50%|█████     | 501/995 [06:18<06:21,  1.30batch/s]
internvideo2 videos:  50%|█████     | 502/995 [06:18<06:20,  1.30batch/s]
internvideo2 videos:  51%|█████     | 503/995 [06:19<06:19,  1.30batch/s]
internvideo2 videos:  51%|█████     | 504/995 [06:20<06:18,  1.30batch/s]
internvideo2 videos:  51%|█████     | 505/995 [06:21<06:19,  1.29batch/s]
internvideo2 videos:  51%|█████     | 506/995 [06:21<06:18,  1.29batch/s]
internvideo2 videos:  51%|█████     | 507/995 [06:22<06:16,  1.30batch/s]
internvideo2 videos:  51%|█████     | 508/995 [06:23<06:17,  1.29batch/s]
internvideo2 videos:  51%|█████     | 509/995 [06:24<06:15,  1.29batch/s]
internvideo2 videos:  51%|█████▏    | 510/995 [06:25<06:16,  1.29batch/s]
internvideo2 videos:  51%|█████▏    | 511/995 [06:25<06:14,  1.29batch/s]
internvideo2 videos:  51%|█████▏    | 512/995 [06:26<06:14,  1.29batch/s]
internvideo2 videos:  52%|█████▏    | 513/995 [06:27<06:13,  1.29batch/s]
internvideo2 videos:  52%|█████▏    | 514/995 [06:28<06:13,  1.29batch/s]
internvideo2 videos:  52%|█████▏    | 515/995 [06:28<06:11,  1.29batch/s]
internvideo2 videos:  52%|█████▏    | 516/995 [06:29<06:10,  1.29batch/s]
internvideo2 videos:  52%|█████▏    | 517/995 [06:30<06:07,  1.30batch/s]
internvideo2 videos:  52%|█████▏    | 518/995 [06:31<06:07,  1.30batch/s]
internvideo2 videos:  52%|█████▏    | 519/995 [06:31<06:06,  1.30batch/s]
internvideo2 videos:  52%|█████▏    | 520/995 [06:32<06:10,  1.28batch/s]
internvideo2 videos:  52%|█████▏    | 521/995 [06:33<06:09,  1.28batch/s]
internvideo2 videos:  52%|█████▏    | 522/995 [06:34<06:07,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 523/995 [06:35<06:05,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 524/995 [06:35<06:04,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 525/995 [06:36<06:03,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 526/995 [06:37<06:03,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 527/995 [06:38<06:02,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 528/995 [06:38<06:00,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 529/995 [06:39<06:00,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 530/995 [06:40<06:00,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 531/995 [06:41<06:00,  1.29batch/s]
internvideo2 videos:  53%|█████▎    | 532/995 [06:42<06:00,  1.29batch/s]
internvideo2 videos:  54%|█████▎    | 533/995 [06:42<05:58,  1.29batch/s]
internvideo2 videos:  54%|█████▎    | 534/995 [06:43<05:56,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 535/995 [06:44<05:58,  1.28batch/s]
internvideo2 videos:  54%|█████▍    | 536/995 [06:45<05:56,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 537/995 [06:45<05:54,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 538/995 [06:46<05:53,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 539/995 [06:47<05:52,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 540/995 [06:48<05:51,  1.29batch/s]
internvideo2 videos:  54%|█████▍    | 541/995 [06:49<05:50,  1.30batch/s]
internvideo2 videos:  54%|█████▍    | 542/995 [06:49<05:49,  1.30batch/s]
internvideo2 videos:  55%|█████▍    | 543/995 [06:50<05:47,  1.30batch/s]
internvideo2 videos:  55%|█████▍    | 544/995 [06:51<05:46,  1.30batch/s]
internvideo2 videos:  55%|█████▍    | 545/995 [06:52<05:47,  1.29batch/s]
internvideo2 videos:  55%|█████▍    | 546/995 [06:52<05:48,  1.29batch/s]
internvideo2 videos:  55%|█████▍    | 547/995 [06:53<05:46,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 548/995 [06:54<05:45,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 549/995 [06:55<05:44,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 550/995 [06:56<05:45,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 551/995 [06:56<05:43,  1.29batch/s]
internvideo2 videos:  55%|█████▌    | 552/995 [06:57<05:42,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 553/995 [06:58<05:41,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 554/995 [06:59<05:42,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 555/995 [06:59<05:41,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 556/995 [07:00<05:40,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 557/995 [07:01<05:39,  1.29batch/s]
internvideo2 videos:  56%|█████▌    | 558/995 [07:02<05:36,  1.30batch/s]
internvideo2 videos:  56%|█████▌    | 559/995 [07:02<05:36,  1.30batch/s]
internvideo2 videos:  56%|█████▋    | 560/995 [07:03<05:35,  1.30batch/s]
internvideo2 videos:  56%|█████▋    | 561/995 [07:04<05:34,  1.30batch/s]
internvideo2 videos:  56%|█████▋    | 562/995 [07:05<05:34,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 563/995 [07:06<05:32,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 564/995 [07:06<05:30,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 565/995 [07:07<05:30,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 566/995 [07:08<05:30,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 567/995 [07:09<05:29,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 568/995 [07:09<05:29,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 569/995 [07:10<05:28,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 570/995 [07:11<05:27,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 571/995 [07:12<05:27,  1.30batch/s]
internvideo2 videos:  57%|█████▋    | 572/995 [07:12<05:26,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 573/995 [07:13<05:27,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 574/995 [07:14<05:26,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 575/995 [07:15<05:25,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 576/995 [07:16<05:24,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 577/995 [07:16<05:22,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 578/995 [07:17<05:22,  1.29batch/s]
internvideo2 videos:  58%|█████▊    | 579/995 [07:18<05:21,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 580/995 [07:19<05:20,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 581/995 [07:19<05:19,  1.30batch/s]
internvideo2 videos:  58%|█████▊    | 582/995 [07:20<05:18,  1.30batch/s]
internvideo2 videos:  59%|█████▊    | 583/995 [07:21<05:17,  1.30batch/s]
internvideo2 videos:  59%|█████▊    | 584/995 [07:22<05:16,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 585/995 [07:23<05:16,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 586/995 [07:23<05:15,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 587/995 [07:24<05:14,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 588/995 [07:25<05:13,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 589/995 [07:26<05:13,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 590/995 [07:26<05:12,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 591/995 [07:27<05:11,  1.30batch/s]
internvideo2 videos:  59%|█████▉    | 592/995 [07:28<05:10,  1.30batch/s]
internvideo2 videos:  60%|█████▉    | 593/995 [07:29<05:10,  1.30batch/s]
internvideo2 videos:  60%|█████▉    | 594/995 [07:29<05:08,  1.30batch/s]
internvideo2 videos:  60%|█████▉    | 595/995 [07:30<05:08,  1.30batch/s]
internvideo2 videos:  60%|█████▉    | 596/995 [07:31<05:07,  1.30batch/s]
internvideo2 videos:  60%|██████    | 597/995 [07:32<05:06,  1.30batch/s]
internvideo2 videos:  60%|██████    | 598/995 [07:33<05:05,  1.30batch/s]
internvideo2 videos:  60%|██████    | 599/995 [07:33<05:05,  1.30batch/s]
internvideo2 videos:  60%|██████    | 600/995 [07:34<05:04,  1.30batch/s]
internvideo2 videos:  60%|██████    | 601/995 [07:35<05:03,  1.30batch/s]
internvideo2 videos:  61%|██████    | 602/995 [07:36<05:02,  1.30batch/s]
internvideo2 videos:  61%|██████    | 603/995 [07:36<05:03,  1.29batch/s]
internvideo2 videos:  61%|██████    | 604/995 [07:37<05:04,  1.28batch/s]
internvideo2 videos:  61%|██████    | 605/995 [07:38<05:03,  1.29batch/s]
internvideo2 videos:  61%|██████    | 606/995 [07:39<05:02,  1.29batch/s]
internvideo2 videos:  61%|██████    | 607/995 [07:40<05:00,  1.29batch/s]
internvideo2 videos:  61%|██████    | 608/995 [07:40<04:59,  1.29batch/s]
internvideo2 videos:  61%|██████    | 609/995 [07:41<04:58,  1.29batch/s]
internvideo2 videos:  61%|██████▏   | 610/995 [07:42<04:57,  1.29batch/s]
internvideo2 videos:  61%|██████▏   | 611/995 [07:43<04:56,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 612/995 [07:43<04:55,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 613/995 [07:44<04:54,  1.30batch/s]
internvideo2 videos:  62%|██████▏   | 614/995 [07:45<04:53,  1.30batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

languagebind videos:   0%|          | 0/3451 [00:00<?, ?batch/s]
languagebind videos:   0%|          | 2/3451 [00:00<21:10,  2.72batch/s]]
languagebind videos:   0%|          | 4/3451 [00:01<20:30,  2.80batch/s]]
languagebind videos:   0%|          | 6/3451 [00:02<20:11,  2.84batch/s]]
languagebind videos:   0%|          | 9/3451 [00:03<20:12,  2.84batch/s]]
languagebind videos:   0%|          | 11/3451 [00:03<20:07,  2.85batch/s]
languagebind videos:   0%|          | 13/3451 [00:04<20:08,  2.85batch/s]
languagebind videos:   0%|          | 15/3451 [00:05<20:03,  2.86batch/s]
languagebind videos:   0%|          | 17/3451 [00:06<20:28,  2.80batch/s]
languagebind videos:   1%|          | 19/3451 [00:06<20:21,  2.81batch/s]
languagebind videos:   1%|          | 22/3451 [00:07<21:04,  2.71batch/s]
languagebind videos:   1%|          | 24/3451 [00:08<21:01,  2.72batch/s]
languagebind videos:   1%|          | 26/3451 [00:09<20:31,  2.78batch/s]
languagebind videos:   1%|          | 28/3451 [00:10<20:33,  2.78batch/s]
languagebind videos:   1%|          | 30/3451 [00:10<20:33,  2.77batch/s]
languagebind videos:   1%|          | 32/3451 [00:11<20:26,  2.79batch/s]
languagebind videos:   1%|          | 34/3451 [00:12<20:15,  2.81batch/s]
languagebind videos:   1%|          | 37/3451 [00:13<20:16,  2.81batch/s]
languagebind videos:   1%|          | 39/3451 [00:13<20:26,  2.78batch/s]
languagebind videos:   1%|          | 41/3451 [00:14<20:21,  2.79batch/s]
languagebind videos:   1%|          | 43/3451 [00:15<20:29,  2.77batch/s]
languagebind videos:   1%|▏         | 45/3451 [00:16<20:31,  2.77batch/s]
languagebind videos:   1%|▏         | 47/3451 [00:16<20:42,  2.74batch/s]
languagebind videos:   1%|▏         | 49/3451 [00:17<20:37,  2.75batch/s]
languagebind videos:   1%|▏         | 51/3451 [00:18<20:41,  2.74batch/s]
languagebind videos:   2%|▏         | 54/3451 [00:19<20:43,  2.73batch/s]
languagebind videos:   2%|▏         | 56/3451 [00:20<20:38,  2.74batch/s]
languagebind videos:   2%|▏         | 58/3451 [00:20<20:34,  2.75batch/s]
languagebind videos:   2%|▏         | 60/3451 [00:21<20:45,  2.72batch/s]
languagebind videos:   2%|▏         | 62/3451 [00:22<20:45,  2.72batch/s]
languagebind videos:   2%|▏         | 64/3451 [00:23<20:41,  2.73batch/s]
languagebind videos:   2%|▏         | 66/3451 [00:23<20:40,  2.73batch/s]
languagebind videos:   2%|▏         | 68/3451 [00:24<20:51,  2.70batch/s]
languagebind videos:   2%|▏         | 70/3451 [00:25<20:40,  2.72batch/s]
languagebind videos:   2%|▏         | 72/3451 [00:26<20:57,  2.69batch/s]
languagebind videos:   2%|▏         | 74/3451 [00:26<20:50,  2.70batch/s]
languagebind videos:   2%|▏         | 77/3451 [00:27<20:41,  2.72batch/s]
languagebind videos:   2%|▏         | 79/3451 [00:28<20:43,  2.71batch/s]
languagebind videos:   2%|▏         | 81/3451 [00:29<21:00,  2.67batch/s]
languagebind videos:   2%|▏         | 83/3451 [00:30<21:14,  2.64batch/s]
languagebind videos:   2%|▏         | 85/3451 [00:30<20:55,  2.68batch/s]
languagebind videos:   3%|▎         | 87/3451 [00:31<20:41,  2.71batch/s]
languagebind videos:   3%|▎         | 89/3451 [00:32<20:37,  2.72batch/s]
languagebind videos:   3%|▎         | 91/3451 [00:33<20:40,  2.71batch/s]
languagebind videos:   3%|▎         | 93/3451 [00:33<20:37,  2.71batch/s]
languagebind videos:   3%|▎         | 95/3451 [00:34<20:36,  2.71batch/s]
languagebind videos:   3%|▎         | 97/3451 [00:35<20:38,  2.71batch/s]
languagebind videos:   3%|▎         | 99/3451 [00:36<20:54,  2.67batch/s]
languagebind videos:   3%|▎         | 102/3451 [00:37<20:46,  2.69batch/s][A
languagebind videos:   3%|▎         | 104/3451 [00:37<20:53,  2.67batch/s][A
languagebind videos:   3%|▎         | 106/3451 [00:38<20:47,  2.68batch/s][A
languagebind videos:   3%|▎         | 108/3451 [00:39<20:43,  2.69batch/s][A
languagebind videos:   3%|▎         | 110/3451 [00:40<20:44,  2.68batch/s][A
languagebind videos:   3%|▎         | 112/3451 [00:40<20:48,  2.67batch/s][A
languagebind videos:   3%|▎         | 114/3451 [00:41<20:42,  2.69batch/s][A
languagebind videos:   3%|▎         | 116/3451 [00:42<20:48,  2.67batch/s][A
languagebind videos:   3%|▎         | 118/3451 [00:43<20:44,  2.68batch/s][A
languagebind videos:   3%|▎         | 120/3451 [00:43<20:43,  2.68batch/s][A
languagebind videos:   4%|▎         | 122/3451 [00:44<20:53,  2.66batch/s][A
languagebind videos:   4%|▎         | 124/3451 [00:45<20:54,  2.65batch/s][A
languagebind videos:   4%|▎         | 126/3451 [00:46<20:53,  2.65batch/s][A
languagebind videos:   4%|▎         | 128/3451 [00:46<20:48,  2.66batch/s][A
languagebind videos:   4%|▍         | 130/3451 [00:47<20:45,  2.67batch/s][A
languagebind videos:   4%|▍         | 132/3451 [00:48<20:55,  2.64batch/s][A
languagebind videos:   4%|▍         | 134/3451 [00:49<20:54,  2.64batch/s][A
languagebind videos:   4%|▍         | 136/3451 [00:49<20:54,  2.64batch/s][A
languagebind videos:   4%|▍         | 138/3451 [00:50<21:07,  2.61batch/s][A
languagebind videos:   4%|▍         | 140/3451 [00:51<21:07,  2.61batch/s][A
languagebind videos:   4%|▍         | 142/3451 [00:52<21:02,  2.62batch/s][A
languagebind videos:   4%|▍         | 144/3451 [00:52<20:59,  2.62batch/s][A
languagebind videos:   4%|▍         | 146/3451 [00:53<20:57,  2.63batch/s][A
languagebind videos:   4%|▍         | 148/3451 [00:54<20:50,  2.64batch/s][A
languagebind videos:   4%|▍         | 150/3451 [00:55<20:55,  2.63batch/s][A
languagebind videos:   4%|▍         | 153/3451 [00:56<21:10,  2.60batch/s][A
languagebind videos:   4%|▍         | 155/3451 [00:57<21:00,  2.62batch/s][A
languagebind videos:   5%|▍         | 157/3451 [00:57<20:53,  2.63batch/s][A
languagebind videos:   5%|▍         | 159/3451 [00:58<20:59,  2.61batch/s][A
languagebind videos:   5%|▍         | 161/3451 [00:59<21:03,  2.60batch/s][A
languagebind videos:   5%|▍         | 163/3451 [01:00<20:52,  2.62batch/s][A
languagebind videos:   5%|▍         | 165/3451 [01:00<20:53,  2.62batch/s][A
languagebind videos:   5%|▍         | 167/3451 [01:01<20:56,  2.61batch/s][A
languagebind videos:   5%|▍         | 169/3451 [01:02<20:58,  2.61batch/s][A
languagebind videos:   5%|▍         | 171/3451 [01:03<20:56,  2.61batch/s][A
languagebind videos:   5%|▌         | 173/3451 [01:04<20:50,  2.62batch/s][A
languagebind videos:   5%|▌         | 175/3451 [01:04<20:51,  2.62batch/s][A
languagebind videos:   5%|▌         | 177/3451 [01:05<20:50,  2.62batch/s][A
languagebind videos:   5%|▌         | 179/3451 [01:06<20:52,  2.61batch/s][A
languagebind videos:   5%|▌         | 181/3451 [01:07<20:55,  2.61batch/s][A
languagebind videos:   5%|▌         | 183/3451 [01:07<21:02,  2.59batch/s][A
languagebind videos:   5%|▌         | 185/3451 [01:08<21:00,  2.59batch/s][A
languagebind videos:   5%|▌         | 187/3451 [01:09<20:53,  2.60batch/s][A
languagebind videos:   5%|▌         | 189/3451 [01:10<20:50,  2.61batch/s][A
languagebind videos:   6%|▌         | 191/3451 [01:10<20:54,  2.60batch/s][A
languagebind videos:   6%|▌         | 193/3451 [01:11<20:55,  2.60batch/s][A
languagebind videos:   6%|▌         | 195/3451 [01:12<21:02,  2.58batch/s][A
languagebind videos:   6%|▌         | 197/3451 [01:13<21:02,  2.58batch/s][A
languagebind videos:   6%|▌         | 199/3451 [01:14<20:59,  2.58batch/s][A
languagebind videos:   6%|▌         | 201/3451 [01:14<20:56,  2.59batch/s][A
languagebind videos:   6%|▌         | 203/3451 [01:15<20:55,  2.59batch/s][A
languagebind videos:   6%|▌         | 205/3451 [01:16<20:58,  2.58batch/s][A
languagebind videos:   6%|▌         | 207/3451 [01:17<20:58,  2.58batch/s][A
languagebind videos:   6%|▌         | 209/3451 [01:17<20:57,  2.58batch/s][A
languagebind videos:   6%|▌         | 211/3451 [01:18<20:50,  2.59batch/s][A
languagebind videos:   6%|▌         | 213/3451 [01:19<20:51,  2.59batch/s][A
languagebind videos:   6%|▌         | 215/3451 [01:20<20:58,  2.57batch/s][A
languagebind videos:   6%|▋         | 217/3451 [01:21<21:01,  2.56batch/s][A
languagebind videos:   6%|▋         | 219/3451 [01:21<21:02,  2.56batch/s][A
languagebind videos:   6%|▋         | 221/3451 [01:22<21:04,  2.55batch/s][A
languagebind videos:   6%|▋         | 223/3451 [01:23<21:04,  2.55batch/s][A
languagebind videos:   7%|▋         | 225/3451 [01:24<21:04,  2.55batch/s][A
languagebind videos:   7%|▋         | 226/3451 [01:24<21:10,  2.54batch/s][A
languagebind videos:   7%|▋         | 228/3451 [01:25<21:10,  2.54batch/s][A
languagebind videos:   7%|▋         | 230/3451 [01:26<21:15,  2.53batch/s][A
languagebind videos:   7%|▋         | 232/3451 [01:26<21:17,  2.52batch/s][A
languagebind videos:   7%|▋         | 234/3451 [01:27<21:13,  2.53batch/s][A
languagebind videos:   7%|▋         | 236/3451 [01:28<21:10,  2.53batch/s][A
languagebind videos:   7%|▋         | 238/3451 [01:29<21:14,  2.52batch/s][A
languagebind videos:   7%|▋         | 240/3451 [01:30<21:08,  2.53batch/s][A
languagebind videos:   7%|▋         | 242/3451 [01:30<20:59,  2.55batch/s][A
languagebind videos:   7%|▋         | 244/3451 [01:31<21:01,  2.54batch/s][A
languagebind videos:   7%|▋         | 246/3451 [01:32<21:02,  2.54batch/s][A
languagebind videos:   7%|▋         | 248/3451 [01:33<21:07,  2.53batch/s][A
languagebind videos:   7%|▋         | 250/3451 [01:34<21:09,  2.52batch/s][A
languagebind videos:   7%|▋         | 252/3451 [01:34<21:07,  2.52batch/s][A
languagebind videos:   7%|▋         | 254/3451 [01:35<21:04,  2.53batch/s][A
languagebind videos:   7%|▋         | 256/3451 [01:36<21:15,  2.51batch/s][A
languagebind videos:   7%|▋         | 258/3451 [01:37<21:13,  2.51batch/s][A
languagebind videos:   8%|▊         | 260/3451 [01:38<21:11,  2.51batch/s][A
languagebind videos:   8%|▊         | 261/3451 [01:38<21:20,  2.49batch/s][A
languagebind videos:   8%|▊         | 263/3451 [01:39<21:15,  2.50batch/s][A
languagebind videos:   8%|▊         | 265/3451 [01:40<21:11,  2.51batch/s][A
languagebind videos:   8%|▊         | 267/3451 [01:40<21:14,  2.50batch/s][A
languagebind videos:   8%|▊         | 269/3451 [01:41<21:14,  2.50batch/s][A
languagebind videos:   8%|▊         | 271/3451 [01:42<21:12,  2.50batch/s][A
languagebind videos:   8%|▊         | 273/3451 [01:43<21:12,  2.50batch/s][A
languagebind videos:   8%|▊         | 275/3451 [01:44<21:04,  2.51batch/s][A
languagebind videos:   8%|▊         | 277/3451 [01:44<21:01,  2.52batch/s][A
languagebind videos:   8%|▊         | 279/3451 [01:45<21:01,  2.52batch/s][A
languagebind videos:   8%|▊         | 281/3451 [01:46<21:06,  2.50batch/s][A
languagebind videos:   8%|▊         | 283/3451 [01:47<21:05,  2.50batch/s][A
languagebind videos:   8%|▊         | 285/3451 [01:48<21:09,  2.49batch/s][A
languagebind videos:   8%|▊         | 286/3451 [01:48<21:16,  2.48batch/s][A
languagebind videos:   8%|▊         | 288/3451 [01:49<21:15,  2.48batch/s][A
languagebind videos:   8%|▊         | 290/3451 [01:50<21:10,  2.49batch/s][A
languagebind videos:   8%|▊         | 292/3451 [01:50<21:13,  2.48batch/s][A
languagebind videos:   9%|▊         | 294/3451 [01:51<21:14,  2.48batch/s][A
languagebind videos:   9%|▊         | 296/3451 [01:52<21:13,  2.48batch/s][A
languagebind videos:   9%|▊         | 298/3451 [01:53<21:14,  2.47batch/s][A
languagebind videos:   9%|▊         | 300/3451 [01:54<21:15,  2.47batch/s][A
languagebind videos:   9%|▉         | 302/3451 [01:54<21:14,  2.47batch/s][A
languagebind videos:   9%|▉         | 304/3451 [01:55<21:14,  2.47batch/s][A
languagebind videos:   9%|▉         | 305/3451 [01:56<21:19,  2.46batch/s][A
languagebind videos:   9%|▉         | 307/3451 [01:56<21:29,  2.44batch/s][A
languagebind videos:   9%|▉         | 309/3451 [01:57<21:24,  2.45batch/s][A
languagebind videos:   9%|▉         | 311/3451 [01:58<21:22,  2.45batch/s][A
languagebind videos:   9%|▉         | 313/3451 [01:59<21:16,  2.46batch/s][A
languagebind videos:   9%|▉         | 315/3451 [02:00<21:11,  2.47batch/s][A
languagebind videos:   9%|▉         | 317/3451 [02:01<21:13,  2.46batch/s][A
languagebind videos:   9%|▉         | 319/3451 [02:01<21:12,  2.46batch/s][A
languagebind videos:   9%|▉         | 321/3451 [02:02<21:10,  2.46batch/s][A
languagebind videos:   9%|▉         | 322/3451 [02:03<21:20,  2.44batch/s][A
languagebind videos:   9%|▉         | 324/3451 [02:03<21:22,  2.44batch/s][A
languagebind videos:   9%|▉         | 326/3451 [02:04<21:17,  2.45batch/s][A
languagebind videos:  10%|▉         | 328/3451 [02:05<21:16,  2.45batch/s][A
languagebind videos:  10%|▉         | 330/3451 [02:06<21:22,  2.43batch/s][A
languagebind videos:  10%|▉         | 332/3451 [02:07<21:18,  2.44batch/s][A
languagebind videos:  10%|▉         | 334/3451 [02:07<21:16,  2.44batch/s][A
languagebind videos:  10%|▉         | 336/3451 [02:08<21:18,  2.44batch/s][A
languagebind videos:  10%|▉         | 337/3451 [02:09<21:22,  2.43batch/s][A
languagebind videos:  10%|▉         | 339/3451 [02:10<21:31,  2.41batch/s][A
languagebind videos:  10%|▉         | 341/3451 [02:10<21:28,  2.41batch/s][A
languagebind videos:  10%|▉         | 343/3451 [02:11<21:22,  2.42batch/s][A
languagebind videos:  10%|▉         | 345/3451 [02:12<21:18,  2.43batch/s][A
languagebind videos:  10%|█         | 347/3451 [02:13<21:18,  2.43batch/s][A
languagebind videos:  10%|█         | 349/3451 [02:14<21:19,  2.42batch/s][A
languagebind videos:  10%|█         | 351/3451 [02:14<21:15,  2.43batch/s][A
languagebind videos:  10%|█         | 352/3451 [02:15<21:14,  2.43batch/s][A
languagebind videos:  10%|█         | 354/3451 [02:16<21:23,  2.41batch/s][A
languagebind videos:  10%|█         | 356/3451 [02:17<21:31,  2.40batch/s][A
languagebind videos:  10%|█         | 358/3451 [02:17<21:25,  2.41batch/s][A
languagebind videos:  10%|█         | 360/3451 [02:18<21:18,  2.42batch/s][A
languagebind videos:  10%|█         | 362/3451 [02:19<21:17,  2.42batch/s][A
languagebind videos:  11%|█         | 364/3451 [02:20<21:14,  2.42batch/s][A
languagebind videos:  11%|█         | 365/3451 [02:20<21:15,  2.42batch/s][A
languagebind videos:  11%|█         | 367/3451 [02:21<21:22,  2.40batch/s][A
languagebind videos:  11%|█         | 369/3451 [02:22<21:20,  2.41batch/s][A
languagebind videos:  11%|█         | 371/3451 [02:23<21:10,  2.42batch/s][A
languagebind videos:  11%|█         | 373/3451 [02:24<21:08,  2.43batch/s][A
languagebind videos:  11%|█         | 375/3451 [02:24<21:08,  2.42batch/s][A
languagebind videos:  11%|█         | 377/3451 [02:25<21:02,  2.44batch/s][A
languagebind videos:  11%|█         | 379/3451 [02:26<21:05,  2.43batch/s][A
languagebind videos:  11%|█         | 380/3451 [02:26<21:07,  2.42batch/s][A
languagebind videos:  11%|█         | 382/3451 [02:27<21:07,  2.42batch/s][A
languagebind videos:  11%|█         | 384/3451 [02:28<21:01,  2.43batch/s][A
languagebind videos:  11%|█         | 386/3451 [02:29<20:58,  2.44batch/s][A
languagebind videos:  11%|█         | 388/3451 [02:30<20:56,  2.44batch/s][A
languagebind videos:  11%|█▏        | 390/3451 [02:31<20:54,  2.44batch/s][A
languagebind videos:  11%|█▏        | 392/3451 [02:31<20:52,  2.44batch/s][A
languagebind videos:  11%|█▏        | 393/3451 [02:32<20:55,  2.44batch/s][A
languagebind videos:  11%|█▏        | 395/3451 [02:33<20:59,  2.43batch/s][A
languagebind videos:  12%|█▏        | 397/3451 [02:33<21:03,  2.42batch/s][A
languagebind videos:  12%|█▏        | 399/3451 [02:34<21:00,  2.42batch/s][A
languagebind videos:  12%|█▏        | 401/3451 [02:35<20:55,  2.43batch/s][A
languagebind videos:  12%|█▏        | 403/3451 [02:36<20:54,  2.43batch/s][A
languagebind videos:  12%|█▏        | 405/3451 [02:37<20:56,  2.42batch/s][A
languagebind videos:  12%|█▏        | 407/3451 [02:38<20:58,  2.42batch/s][A
languagebind videos:  12%|█▏        | 408/3451 [02:38<20:56,  2.42batch/s][A
languagebind videos:  12%|█▏        | 410/3451 [02:39<20:53,  2.43batch/s][A
languagebind videos:  12%|█▏        | 412/3451 [02:40<20:49,  2.43batch/s][A
languagebind videos:  12%|█▏        | 414/3451 [02:40<20:46,  2.44batch/s][A
languagebind videos:  12%|█▏        | 416/3451 [02:41<20:46,  2.44batch/s][A
languagebind videos:  12%|█▏        | 418/3451 [02:42<20:49,  2.43batch/s][A
languagebind videos:  12%|█▏        | 420/3451 [02:43<20:48,  2.43batch/s][A
languagebind videos:  12%|█▏        | 422/3451 [02:44<20:47,  2.43batch/s][A
languagebind videos:  12%|█▏        | 423/3451 [02:44<20:51,  2.42batch/s][A
languagebind videos:  12%|█▏        | 425/3451 [02:45<20:59,  2.40batch/s][A
languagebind videos:  12%|█▏        | 427/3451 [02:46<21:00,  2.40batch/s][A
languagebind videos:  12%|█▏        | 429/3451 [02:47<20:56,  2.41batch/s][A
languagebind videos:  12%|█▏        | 431/3451 [02:48<20:48,  2.42batch/s][A
languagebind videos:  13%|█▎        | 433/3451 [02:48<20:43,  2.43batch/s][A
languagebind videos:  13%|█▎        | 435/3451 [02:49<20:45,  2.42batch/s][A
languagebind videos:  13%|█▎        | 436/3451 [02:50<20:47,  2.42batch/s][A
languagebind videos:  13%|█▎        | 438/3451 [02:50<20:54,  2.40batch/s][A
languagebind videos:  13%|█▎        | 440/3451 [02:51<20:53,  2.40batch/s][A
languagebind videos:  13%|█▎        | 442/3451 [02:52<20:46,  2.41batch/s][A
languagebind videos:  13%|█▎        | 444/3451 [02:53<20:44,  2.42batch/s][A
languagebind videos:  13%|█▎        | 446/3451 [02:54<20:48,  2.41batch/s][A
languagebind videos:  13%|█▎        | 448/3451 [02:55<20:51,  2.40batch/s][A
languagebind videos:  13%|█▎        | 449/3451 [02:55<20:51,  2.40batch/s][A
languagebind videos:  13%|█▎        | 451/3451 [02:56<21:00,  2.38batch/s][A
languagebind videos:  13%|█▎        | 453/3451 [02:57<20:53,  2.39batch/s][A
languagebind videos:  13%|█▎        | 455/3451 [02:57<20:50,  2.40batch/s][A
languagebind videos:  13%|█▎        | 457/3451 [02:58<20:46,  2.40batch/s][A
languagebind videos:  13%|█▎        | 459/3451 [02:59<20:44,  2.40batch/s][A
languagebind videos:  13%|█▎        | 460/3451 [03:00<20:45,  2.40batch/s][A
languagebind videos:  13%|█▎        | 462/3451 [03:00<20:48,  2.39batch/s][A
languagebind videos:  13%|█▎        | 464/3451 [03:01<20:53,  2.38batch/s][A
languagebind videos:  14%|█▎        | 466/3451 [03:02<20:50,  2.39batch/s][A
languagebind videos:  14%|█▎        | 468/3451 [03:03<20:44,  2.40batch/s][A
languagebind videos:  14%|█▎        | 470/3451 [03:04<20:43,  2.40batch/s][A
languagebind videos:  14%|█▎        | 472/3451 [03:05<20:44,  2.39batch/s][A
languagebind videos:  14%|█▎        | 473/3451 [03:05<20:44,  2.39batch/s][A
languagebind videos:  14%|█▍        | 475/3451 [03:06<20:50,  2.38batch/s][A
languagebind videos:  14%|█▍        | 477/3451 [03:07<20:51,  2.38batch/s][A
languagebind videos:  14%|█▍        | 479/3451 [03:08<20:49,  2.38batch/s][A
languagebind videos:  14%|█▍        | 481/3451 [03:08<20:45,  2.39batch/s][A
languagebind videos:  14%|█▍        | 483/3451 [03:09<20:45,  2.38batch/s][A
languagebind videos:  14%|█▍        | 484/3451 [03:10<20:50,  2.37batch/s][A
languagebind videos:  14%|█▍        | 486/3451 [03:11<21:19,  2.32batch/s][A
languagebind videos:  14%|█▍        | 488/3451 [03:11<21:07,  2.34batch/s][A
languagebind videos:  14%|█▍        | 490/3451 [03:12<20:48,  2.37batch/s][A
languagebind videos:  14%|█▍        | 492/3451 [03:13<20:41,  2.38batch/s][A
languagebind videos:  14%|█▍        | 494/3451 [03:14<20:33,  2.40batch/s][A
languagebind videos:  14%|█▍        | 495/3451 [03:14<20:40,  2.38batch/s][A
languagebind videos:  14%|█▍        | 497/3451 [03:15<20:45,  2.37batch/s][A
languagebind videos:  14%|█▍        | 499/3451 [03:16<20:51,  2.36batch/s][A
languagebind videos:  15%|█▍        | 501/3451 [03:17<20:52,  2.35batch/s][A
languagebind videos:  15%|█▍        | 503/3451 [03:18<20:43,  2.37batch/s][A
languagebind videos:  15%|█▍        | 504/3451 [03:18<20:33,  2.39batch/s][A
languagebind videos:  15%|█▍        | 506/3451 [03:19<20:38,  2.38batch/s][A
languagebind videos:  15%|█▍        | 508/3451 [03:20<20:41,  2.37batch/s][A

-- mean: R1 65.60  mAP 77.15  mINP 77.15
-- mean_s8: R1 65.60  mAP 77.15  mINP 77.15
-- max: R1 65.00  mAP 76.76  mINP 76.76
-- query_max: R1 65.50  mAP 77.07  mINP 77.07
== InternVideo2 CLIP-S | activitynet/sentence | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

languagebind videos:  21%|██        | 733/3451 [04:58<29:21,  1.54batch/s]
internvideo2 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
internvideo2 texts:   2%|▏         | 5/227 [00:00<00:05, 42.10batch/s]
internvideo2 texts:   4%|▍         | 10/227 [00:00<00:05, 42.57batch/s]
languagebind videos:  21%|██▏       | 734/3451 [04:59<27:11,  1.67batch/s]
internvideo2 texts:  10%|▉         | 22/227 [00:00<00:04, 50.51batch/s]
internvideo2 texts:  12%|█▏        | 28/227 [00:00<00:04, 49.18batch/s]
internvideo2 texts:  15%|█▌        | 35/227 [00:00<00:03, 54.75batch/s]
languagebind videos:  21%|██▏       | 735/3451 [04:59<25:02,  1.81batch/s]
internvideo2 texts:  22%|██▏       | 50/227 [00:00<00:02, 60.61batch/s]
internvideo2 texts:  25%|██▌       | 57/227 [00:01<00:03, 52.24batch/s]
internvideo2 texts:  28%|██▊       | 64/227 [00:01<00:02, 56.59batch/s]
languagebind videos:  21%|██▏       | 736/3451 [04:59<23:30,  1.92batch/s]
internvideo2 texts:  34%|███▍      | 78/227 [00:01<00:02, 55.72batch/s]
internvideo2 texts:  37%|███▋      | 84/227 [00:01<00:02, 53.02batch/s]
languagebind videos:  21%|██▏       | 737/3451 [05:00<22:22,  2.02batch/s]
internvideo2 texts:  44%|████▎     | 99/227 [00:01<00:02, 60.84batch/s]
internvideo2 texts:  47%|████▋     | 106/227 [00:01<00:02, 57.46batch/s]
internvideo2 texts:  50%|█████     | 114/227 [00:02<00:01, 61.69batch/s]
languagebind videos:  21%|██▏       | 738/3451 [05:00<21:36,  2.09batch/s]A
internvideo2 texts:  57%|█████▋    | 129/227 [00:02<00:01, 61.30batch/s]
internvideo2 texts:  60%|█████▉    | 136/227 [00:02<00:01, 59.60batch/s]
internvideo2 texts:  63%|██████▎   | 144/227 [00:02<00:01, 62.75batch/s]
languagebind videos:  21%|██▏       | 739/3451 [05:01<20:59,  2.15batch/s]A
internvideo2 texts:  70%|██████▉   | 158/227 [00:02<00:01, 56.64batch/s]
internvideo2 texts:  72%|███████▏  | 164/227 [00:02<00:01, 55.62batch/s]
languagebind videos:  21%|██▏       | 740/3451 [05:01<20:38,  2.19batch/s]A
internvideo2 texts:  79%|███████▉  | 179/227 [00:03<00:00, 59.26batch/s]
internvideo2 texts:  82%|████████▏ | 186/227 [00:03<00:00, 56.21batch/s]
internvideo2 texts:  85%|████████▍ | 192/227 [00:03<00:00, 56.48batch/s]
languagebind videos:  21%|██▏       | 741/3451 [05:02<20:25,  2.21batch/s]A
internvideo2 texts:  91%|█████████ | 207/227 [00:03<00:00, 57.13batch/s]
internvideo2 texts:  94%|█████████▍| 213/227 [00:03<00:00, 57.23batch/s]
internvideo2 texts: 100%|██████████| 227/227 [00:03<00:00, 58.05batch/s]
languagebind videos:  22%|██▏       | 763/3451 [05:14<32:24,  1.38batch/s]

-- mean: R1 34.97  mAP 48.15  mINP 48.15
-- mean_s8: R1 34.97  mAP 48.15  mINP 48.15
-- max: R1 34.78  mAP 47.84  mINP 47.84
-- query_max: R1 35.11  mAP 48.62  mINP 48.62
== InternVideo2 CLIP-S | activitynet/paragraph | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:  35%|███▌      | 1221/3451 [08:43<17:08,  2.17batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

languagebind videos:  35%|███▌      | 1222/3451 [08:44<17:16,  2.15batch/s]
languagebind videos:  35%|███▌      | 1223/3451 [08:44<18:45,  1.98batch/s]
languagebind videos:  35%|███▌      | 1225/3451 [08:45<17:41,  2.10batch/s]
languagebind videos:  36%|███▌      | 1226/3451 [08:46<17:28,  2.12batch/s]
languagebind videos:  36%|███▌      | 1228/3451 [08:47<17:07,  2.16batch/s]
languagebind videos:  36%|███▌      | 1229/3451 [08:47<16:56,  2.18batch/s]
languagebind videos:  36%|███▌      | 1231/3451 [08:48<16:48,  2.20batch/s]
languagebind videos:  36%|███▌      | 1232/3451 [08:48<16:46,  2.21batch/s]
languagebind videos:  36%|███▌      | 1234/3451 [08:49<16:40,  2.22batch/s]
languagebind videos:  36%|███▌      | 1235/3451 [08:50<16:43,  2.21batch/s]
languagebind videos:  36%|███▌      | 1237/3451 [08:51<16:45,  2.20batch/s]
languagebind videos:  36%|███▌      | 1238/3451 [08:51<16:44,  2.20batch/s]A
languagebind videos:  36%|███▌      | 1240/3451 [08:52<16:41,  2.21batch/s]A
languagebind videos:  36%|███▌      | 1241/3451 [08:52<16:39,  2.21batch/s]A
languagebind videos:  36%|███▌      | 1243/3451 [08:53<16:37,  2.21batch/s]A
languagebind videos:  36%|███▌      | 1244/3451 [08:54<16:35,  2.22batch/s]A
languagebind videos:  36%|███▌      | 1246/3451 [08:55<16:36,  2.21batch/s]A
languagebind videos:  36%|███▌      | 1247/3451 [08:55<16:39,  2.20batch/s]A
languagebind videos:  36%|███▌      | 1249/3451 [08:56<16:43,  2.19batch/s]A
languagebind videos:  36%|███▌      | 1250/3451 [08:56<16:53,  2.17batch/s]A
languagebind videos:  36%|███▋      | 1251/3451 [08:57<16:56,  2.16batch/s]A
languagebind videos:  36%|███▋      | 1253/3451 [08:58<16:50,  2.18batch/s]A
languagebind videos:  36%|███▋      | 1254/3451 [08:58<16:44,  2.19batch/s]A
languagebind videos:  36%|███▋      | 1256/3451 [08:59<16:45,  2.18batch/s]A
languagebind videos:  36%|███▋      | 1257/3451 [09:00<16:38,  2.20batch/s]A
languagebind videos:  36%|███▋      | 1259/3451 [09:01<16:36,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1260/3451 [09:01<16:36,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1262/3451 [09:02<16:31,  2.21batch/s]A
languagebind videos:  37%|███▋      | 1263/3451 [09:02<16:35,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1265/3451 [09:03<16:34,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1266/3451 [09:04<16:30,  2.21batch/s]A
languagebind videos:  37%|███▋      | 1268/3451 [09:05<16:34,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1269/3451 [09:05<16:36,  2.19batch/s]A
languagebind videos:  37%|███▋      | 1271/3451 [09:06<16:39,  2.18batch/s]A
languagebind videos:  37%|███▋      | 1272/3451 [09:07<16:38,  2.18batch/s]A
languagebind videos:  37%|███▋      | 1274/3451 [09:07<16:34,  2.19batch/s]A
languagebind videos:  37%|███▋      | 1275/3451 [09:08<16:31,  2.19batch/s]A
languagebind videos:  37%|███▋      | 1277/3451 [09:09<16:35,  2.18batch/s]A
languagebind videos:  37%|███▋      | 1278/3451 [09:09<16:29,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1280/3451 [09:10<16:26,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1282/3451 [09:11<16:28,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1283/3451 [09:12<16:32,  2.18batch/s]A
languagebind videos:  37%|███▋      | 1285/3451 [09:12<16:26,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1286/3451 [09:13<16:25,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1288/3451 [09:14<16:21,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1289/3451 [09:14<16:20,  2.21batch/s]A
languagebind videos:  37%|███▋      | 1291/3451 [09:15<16:17,  2.21batch/s]A
languagebind videos:  37%|███▋      | 1292/3451 [09:16<16:22,  2.20batch/s]A
languagebind videos:  37%|███▋      | 1294/3451 [09:17<16:14,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1295/3451 [09:17<16:17,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1297/3451 [09:18<16:15,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1298/3451 [09:18<16:15,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1300/3451 [09:19<16:18,  2.20batch/s]A
languagebind videos:  38%|███▊      | 1301/3451 [09:20<16:13,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1303/3451 [09:21<16:11,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1304/3451 [09:21<16:11,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1306/3451 [09:22<16:15,  2.20batch/s]A
languagebind videos:  38%|███▊      | 1308/3451 [09:23<16:10,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1309/3451 [09:23<16:10,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1311/3451 [09:24<16:04,  2.22batch/s]A
languagebind videos:  38%|███▊      | 1312/3451 [09:25<16:05,  2.22batch/s]A
languagebind videos:  38%|███▊      | 1314/3451 [09:26<16:06,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1315/3451 [09:26<16:05,  2.21batch/s]A
languagebind videos:  38%|███▊      | 1317/3451 [09:27<15:59,  2.22batch/s]A
languagebind videos:  38%|███▊      | 1318/3451 [09:27<15:54,  2.23batch/s]A
languagebind videos:  38%|███▊      | 1320/3451 [09:28<15:53,  2.23batch/s]A
languagebind videos:  38%|███▊      | 1321/3451 [09:29<15:52,  2.24batch/s]A
languagebind videos:  38%|███▊      | 1323/3451 [09:30<16:00,  2.22batch/s]A
languagebind videos:  38%|███▊      | 1325/3451 [09:31<15:55,  2.22batch/s]A
languagebind videos:  38%|███▊      | 1326/3451 [09:31<15:53,  2.23batch/s]A
languagebind videos:  38%|███▊      | 1328/3451 [09:32<15:48,  2.24batch/s]A
languagebind videos:  39%|███▊      | 1329/3451 [09:32<15:46,  2.24batch/s]A
languagebind videos:  39%|███▊      | 1331/3451 [09:33<15:51,  2.23batch/s]A
languagebind videos:  39%|███▊      | 1332/3451 [09:34<15:52,  2.22batch/s]A
languagebind videos:  39%|███▊      | 1334/3451 [09:35<15:56,  2.21batch/s]A
languagebind videos:  39%|███▊      | 1336/3451 [09:35<15:44,  2.24batch/s]A
languagebind videos:  39%|███▊      | 1337/3451 [09:36<15:43,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1339/3451 [09:37<15:44,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1340/3451 [09:37<15:41,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1342/3451 [09:38<15:40,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1343/3451 [09:39<15:38,  2.25batch/s]A
languagebind videos:  39%|███▉      | 1345/3451 [09:39<15:39,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1346/3451 [09:40<15:39,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1348/3451 [09:41<15:45,  2.23batch/s]A
languagebind videos:  39%|███▉      | 1350/3451 [09:42<15:40,  2.23batch/s]A
languagebind videos:  39%|███▉      | 1351/3451 [09:42<15:39,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1353/3451 [09:43<15:35,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1354/3451 [09:43<15:36,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1356/3451 [09:44<15:39,  2.23batch/s]A
languagebind videos:  39%|███▉      | 1357/3451 [09:45<15:36,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1359/3451 [09:46<15:37,  2.23batch/s]A
languagebind videos:  39%|███▉      | 1361/3451 [09:47<15:33,  2.24batch/s]A
languagebind videos:  39%|███▉      | 1362/3451 [09:47<15:29,  2.25batch/s]A
languagebind videos:  40%|███▉      | 1364/3451 [09:48<15:25,  2.25batch/s]A
languagebind videos:  40%|███▉      | 1365/3451 [09:48<15:27,  2.25batch/s]A
languagebind videos:  40%|███▉      | 1367/3451 [09:49<15:35,  2.23batch/s]A
languagebind videos:  40%|███▉      | 1369/3451 [09:50<15:30,  2.24batch/s]A
languagebind videos:  40%|███▉      | 1370/3451 [09:51<15:34,  2.23batch/s]A
languagebind videos:  40%|███▉      | 1372/3451 [09:52<15:27,  2.24batch/s]A
languagebind videos:  40%|███▉      | 1373/3451 [09:52<15:26,  2.24batch/s]A
languagebind videos:  40%|███▉      | 1375/3451 [09:53<15:24,  2.25batch/s]A
languagebind videos:  40%|███▉      | 1376/3451 [09:53<15:23,  2.25batch/s][A
languagebind videos:  40%|███▉      | 1378/3451 [09:54<15:25,  2.24batch/s][A
languagebind videos:  40%|███▉      | 1380/3451 [09:55<15:26,  2.24batch/s][A
languagebind videos:  40%|████      | 1381/3451 [09:56<15:23,  2.24batch/s][A
languagebind videos:  40%|████      | 1383/3451 [09:56<15:19,  2.25batch/s][A
languagebind videos:  40%|████      | 1384/3451 [09:57<15:24,  2.24batch/s][A
languagebind videos:  40%|████      | 1386/3451 [09:58<15:28,  2.22batch/s][A
languagebind videos:  40%|████      | 1387/3451 [09:58<15:25,  2.23batch/s][A
languagebind videos:  40%|████      | 1389/3451 [09:59<15:23,  2.23batch/s][A
languagebind videos:  40%|████      | 1391/3451 [10:00<15:17,  2.25batch/s][A
languagebind videos:  40%|████      | 1392/3451 [10:00<15:16,  2.25batch/s][A
languagebind videos:  40%|████      | 1394/3451 [10:01<15:12,  2.25batch/s][A
languagebind videos:  40%|████      | 1395/3451 [10:02<15:09,  2.26batch/s][A
languagebind videos:  40%|████      | 1397/3451 [10:03<15:12,  2.25batch/s][A
languagebind videos:  41%|████      | 1399/3451 [10:04<15:10,  2.25batch/s][A
languagebind videos:  41%|████      | 1400/3451 [10:04<15:11,  2.25batch/s][A
languagebind videos:  41%|████      | 1402/3451 [10:05<15:07,  2.26batch/s][A
languagebind videos:  41%|████      | 1403/3451 [10:05<15:06,  2.26batch/s][A
languagebind videos:  41%|████      | 1405/3451 [10:06<15:13,  2.24batch/s][A
languagebind videos:  41%|████      | 1407/3451 [10:07<15:08,  2.25batch/s][A
languagebind videos:  41%|████      | 1408/3451 [10:08<15:08,  2.25batch/s][A
languagebind videos:  41%|████      | 1410/3451 [10:08<15:09,  2.24batch/s][A
languagebind videos:  41%|████      | 1411/3451 [10:09<15:08,  2.24batch/s][A
languagebind videos:  41%|████      | 1413/3451 [10:10<15:15,  2.23batch/s][A
languagebind videos:  41%|████      | 1415/3451 [10:11<15:06,  2.25batch/s][A
languagebind videos:  41%|████      | 1416/3451 [10:11<15:11,  2.23batch/s][A
languagebind videos:  41%|████      | 1418/3451 [10:12<15:08,  2.24batch/s][A
languagebind videos:  41%|████      | 1419/3451 [10:12<15:06,  2.24batch/s][A
languagebind videos:  41%|████      | 1421/3451 [10:13<15:04,  2.24batch/s][A
languagebind videos:  41%|████      | 1422/3451 [10:14<15:00,  2.25batch/s][A
languagebind videos:  41%|████▏     | 1424/3451 [10:15<15:05,  2.24batch/s][A
languagebind videos:  41%|████▏     | 1426/3451 [10:16<15:08,  2.23batch/s][A
languagebind videos:  41%|████▏     | 1427/3451 [10:16<15:07,  2.23batch/s][A
languagebind videos:  41%|████▏     | 1429/3451 [10:17<15:05,  2.23batch/s][A
languagebind videos:  41%|████▏     | 1430/3451 [10:17<15:05,  2.23batch/s][A
languagebind videos:  41%|████▏     | 1432/3451 [10:18<15:08,  2.22batch/s][A
languagebind videos:  42%|████▏     | 1434/3451 [10:19<15:03,  2.23batch/s][A
languagebind videos:  42%|████▏     | 1435/3451 [10:20<14:59,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1437/3451 [10:20<15:00,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1439/3451 [10:21<14:56,  2.25batch/s][A
languagebind videos:  42%|████▏     | 1440/3451 [10:22<14:57,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1442/3451 [10:23<14:54,  2.25batch/s][A
languagebind videos:  42%|████▏     | 1443/3451 [10:23<14:51,  2.25batch/s][A
languagebind videos:  42%|████▏     | 1445/3451 [10:24<14:53,  2.25batch/s][A
languagebind videos:  42%|████▏     | 1447/3451 [10:25<14:54,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1448/3451 [10:25<14:52,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1450/3451 [10:26<14:51,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1451/3451 [10:27<14:50,  2.25batch/s][A
languagebind videos:  42%|████▏     | 1453/3451 [10:28<14:55,  2.23batch/s][A
languagebind videos:  42%|████▏     | 1455/3451 [10:29<14:51,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1456/3451 [10:29<14:52,  2.23batch/s][A
languagebind videos:  42%|████▏     | 1458/3451 [10:30<14:54,  2.23batch/s][A
languagebind videos:  42%|████▏     | 1460/3451 [10:31<14:48,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1461/3451 [10:31<14:51,  2.23batch/s][A
languagebind videos:  42%|████▏     | 1463/3451 [10:32<14:47,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1464/3451 [10:33<14:46,  2.24batch/s][A
languagebind videos:  42%|████▏     | 1466/3451 [10:33<14:45,  2.24batch/s][A
languagebind videos:  43%|████▎     | 1468/3451 [10:34<14:44,  2.24batch/s][A
languagebind videos:  43%|████▎     | 1469/3451 [10:35<14:47,  2.23batch/s][A
languagebind videos:  43%|████▎     | 1471/3451 [10:36<15:20,  2.15batch/s][A
languagebind videos:  43%|████▎     | 1472/3451 [10:36<15:18,  2.15batch/s][A
languagebind videos:  43%|████▎     | 1474/3451 [10:37<15:00,  2.20batch/s][A
languagebind videos:  43%|████▎     | 1476/3451 [10:38<14:51,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1477/3451 [10:38<14:51,  2.21batch/s][A
languagebind videos:  43%|████▎     | 1479/3451 [10:39<14:44,  2.23batch/s][A
languagebind videos:  43%|████▎     | 1480/3451 [10:40<14:47,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1482/3451 [10:41<14:51,  2.21batch/s][A
languagebind videos:  43%|████▎     | 1484/3451 [10:42<14:44,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1485/3451 [10:42<14:44,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1487/3451 [10:43<14:43,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1488/3451 [10:43<14:39,  2.23batch/s][A
languagebind videos:  43%|████▎     | 1490/3451 [10:44<14:40,  2.23batch/s][A
languagebind videos:  43%|████▎     | 1492/3451 [10:45<14:39,  2.23batch/s][A
languagebind videos:  43%|████▎     | 1493/3451 [10:46<14:43,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1495/3451 [10:47<14:39,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1496/3451 [10:47<14:38,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1498/3451 [10:48<14:40,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1500/3451 [10:49<14:36,  2.22batch/s][A
languagebind videos:  43%|████▎     | 1501/3451 [10:49<14:35,  2.23batch/s][A
languagebind videos:  44%|████▎     | 1503/3451 [10:50<14:33,  2.23batch/s][A
languagebind videos:  44%|████▎     | 1504/3451 [10:51<14:31,  2.23batch/s][A
languagebind videos:  44%|████▎     | 1506/3451 [10:51<14:32,  2.23batch/s][A
languagebind videos:  44%|████▎     | 1508/3451 [10:52<14:35,  2.22batch/s][A
languagebind videos:  44%|████▎     | 1509/3451 [10:53<14:35,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1511/3451 [10:54<14:37,  2.21batch/s][A
languagebind videos:  44%|████▍     | 1513/3451 [10:55<14:32,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1514/3451 [10:55<14:33,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1516/3451 [10:56<14:30,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1517/3451 [10:56<14:30,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1519/3451 [10:57<14:31,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1521/3451 [10:58<14:27,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1522/3451 [10:59<14:26,  2.23batch/s][A
languagebind videos:  44%|████▍     | 1524/3451 [11:00<14:26,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1526/3451 [11:00<14:25,  2.22batch/s][A
languagebind videos:  44%|████▍     | 1527/3451 [11:01<14:42,  2.18batch/s][A
languagebind videos:  44%|████▍     | 1529/3451 [11:02<14:46,  2.17batch/s][A
languagebind videos:  44%|████▍     | 1530/3451 [11:02<14:43,  2.18batch/s][A
languagebind videos:  44%|████▍     | 1532/3451 [11:03<14:36,  2.19batch/s][A
languagebind videos:  44%|████▍     | 1533/3451 [11:04<14:35,  2.19batch/s][A
languagebind videos:  44%|████▍     | 1535/3451 [11:05<14:27,  2.21batch/s][A
languagebind videos:  45%|████▍     | 1537/3451 [11:06<14:26,  2.21batch/s][A
languagebind videos:  45%|████▍     | 1538/3451 [11:06<14:24,  2.21batch/s][A
languagebind videos:  45%|████▍     | 1540/3451 [11:07<14:26,  2.21batch/s][A
languagebind videos:  45%|████▍     | 1542/3451 [11:08<14:20,  2.22batch/s][A
languagebind videos:  45%|████▍     | 1543/3451 [11:08<14:19,  2.22batch/s][A
languagebind videos:  45%|████▍     | 1545/3451 [11:09<14:17,  2.22batch/s][A
languagebind videos:  45%|████▍     | 1546/3451 [11:10<14:16,  2.23batch/s][A
languagebind videos:  45%|████▍     | 1548/3451 [11:10<14:19,  2.21batch/s][A
languagebind videos:  45%|████▍     | 1550/3451 [11:11<14:17,  2.22batch/s][A
languagebind videos:  45%|████▍     | 1551/3451 [11:12<14:14,  2.22batch/s][A
languagebind videos:  45%|████▌     | 1553/3451 [11:13<14:15,  2.22batch/s][A
languagebind videos:  45%|████▌     | 1555/3451 [11:14<14:18,  2.21batch/s][A
languagebind videos:  45%|████▌     | 1556/3451 [11:14<14:37,  2.16batch/s][A
languagebind videos:  45%|████▌     | 1558/3451 [11:15<14:38,  2.16batch/s][A
languagebind videos:  45%|████▌     | 1559/3451 [11:15<14:29,  2.18batch/s][A
languagebind videos:  45%|████▌     | 1561/3451 [11:16<14:21,  2.19batch/s][A
languagebind videos:  45%|████▌     | 1563/3451 [11:17<14:15,  2.21batch/s][A
languagebind videos:  45%|████▌     | 1564/3451 [11:18<14:13,  2.21batch/s][A
languagebind videos:  45%|████▌     | 1566/3451 [11:19<14:14,  2.21batch/s][A
languagebind videos:  45%|████▌     | 1567/3451 [11:19<14:11,  2.21batch/s][A
languagebind videos:  45%|████▌     | 1569/3451 [11:20<14:08,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1571/3451 [11:21<14:10,  2.21batch/s][A
languagebind videos:  46%|████▌     | 1572/3451 [11:21<14:09,  2.21batch/s][A
languagebind videos:  46%|████▌     | 1574/3451 [11:22<14:07,  2.21batch/s][A
languagebind videos:  46%|████▌     | 1576/3451 [11:23<14:03,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1577/3451 [11:24<14:04,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1579/3451 [11:25<14:04,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1581/3451 [11:25<14:00,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1582/3451 [11:26<14:01,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1584/3451 [11:27<14:02,  2.22batch/s][A
languagebind videos:  46%|████▌     | 1585/3451 [11:27<14:03,  2.21batch/s][A
languagebind videos:  46%|████▌     | 1587/3451 [11:28<14:07,  2.20batch/s][A
languagebind videos:  46%|████▌     | 1589/3451 [11:29<14:09,  2.19batch/s][A
languagebind videos:  46%|████▌     | 1590/3451 [11:30<14:08,  2.19batch/s][A
languagebind videos:  46%|████▌     | 1592/3451 [11:30<14:06,  2.20batch/s][A
languagebind videos:  46%|████▌     | 1594/3451 [11:31<14:02,  2.21batch/s][A
languagebind videos:  46%|████▌     | 1595/3451 [11:32<14:01,  2.21batch/s][A
languagebind videos:  46%|████▋     | 1597/3451 [11:33<13:57,  2.21batch/s][A
languagebind videos:  46%|████▋     | 1599/3451 [11:34<13:57,  2.21batch/s][A
languagebind videos:  46%|████▋     | 1600/3451 [11:34<14:01,  2.20batch/s][A
languagebind videos:  46%|████▋     | 1602/3451 [11:35<13:55,  2.21batch/s][A
languagebind videos:  46%|████▋     | 1603/3451 [11:35<13:53,  2.22batch/s][A
languagebind videos:  47%|████▋     | 1605/3451 [11:36<13:54,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1607/3451 [11:37<13:54,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1608/3451 [11:38<13:55,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1610/3451 [11:39<13:53,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1611/3451 [11:39<13:56,  2.20batch/s][A
languagebind videos:  47%|████▋     | 1613/3451 [11:40<13:51,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1615/3451 [11:41<13:49,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1616/3451 [11:41<13:45,  2.22batch/s][A
languagebind videos:  47%|████▋     | 1618/3451 [11:42<13:48,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1620/3451 [11:43<13:43,  2.22batch/s][A
languagebind videos:  47%|████▋     | 1621/3451 [11:44<13:42,  2.22batch/s][A
languagebind videos:  47%|████▋     | 1623/3451 [11:44<13:47,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1625/3451 [11:45<13:46,  2.21batch/s][A
languagebind videos:  47%|████▋     | 1626/3451 [11:46<13:45,  2.21batch/s][A

-- mean: R1 63.30  mAP 74.76  mINP 74.76
-- mean_s8: R1 64.10  mAP 75.18  mINP 75.18
-- max: R1 59.20  mAP 71.69  mINP 71.69
-- query_max: R1 63.30  mAP 74.74  mINP 74.74
== LanguageBind | activitynet/sentence | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  39%|███▉      | 1342/3451 [16:54<29:16,  1.20batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

languagebind texts:   4%|▎         | 8/227 [00:00<00:06, 34.09batch/s]
languagebind texts:  21%|██        | 48/227 [00:01<00:03, 46.13batch/s]h/s]
languagebind texts:  37%|███▋      | 83/227 [00:01<00:03, 46.67batch/s]h/s]
languagebind texts:  52%|█████▏    | 118/227 [00:02<00:02, 46.35batch/s]/s]
languagebind texts:  67%|██████▋   | 153/227 [00:03<00:01, 45.99batch/s]/s]
languagebind texts:  83%|████████▎ | 188/227 [00:04<00:00, 46.83batch/s]/s]
languagebind texts:  98%|█████████▊| 223/227 [00:04<00:00, 46.43batch/s]/s]
languagebind texts: 100%|██████████| 227/227 [00:04<00:00, 45.51batch/s]/s]

internvideo2 videos:  39%|███▉      | 1350/3451 [17:01<27:18,  1.28batch/s]
internvideo2 videos:  39%|███▉      | 1351/3451 [17:02<28:59,  1.21batch/s]
internvideo2 videos:  39%|███▉      | 1352/3451 [17:03<29:53,  1.17batch/s]
internvideo2 videos:  39%|███▉      | 1353/3451 [17:03<29:56,  1.17batch/s]
internvideo2 videos:  39%|███▉      | 1354/3451 [17:04<30:32,  1.14batch/s]
internvideo2 videos:  39%|███▉      | 1355/3451 [17:05<30:46,  1.14batch/s]
internvideo2 videos:  39%|███▉      | 1356/3451 [17:06<31:05,  1.12batch/s]
internvideo2 videos:  39%|███▉      | 1357/3451 [17:07<30:59,  1.13batch/s]
internvideo2 videos:  39%|███▉      | 1358/3451 [17:08<31:02,  1.12batch/s]
internvideo2 videos:  39%|███▉      | 1359/3451 [17:09<30:41,  1.14batch/s]
internvideo2 videos:  39%|███▉      | 1360/3451 [17:10<30:17,  1.15batch/s]
internvideo2 videos:  39%|███▉      | 1361/3451 [17:11<30:23,  1.15batch/s]
internvideo2 videos:  39%|███▉      | 1362/3451 [17:11<30:28,  1.14batch/s]
internvideo2 videos:  39%|███▉      | 1363/3451 [17:12<31:22,  1.11batch/s]

-- mean: R1 33.43  mAP 46.44  mINP 46.44
-- mean_s8: R1 33.31  mAP 46.41  mINP 46.41
-- max: R1 30.83  mAP 43.84  mINP 43.84
-- query_max: R1 35.36  mAP 48.15  mINP 48.15

internvideo2 videos:  40%|███▉      | 1364/3451 [17:13<30:49,  1.13batch/s]

== LanguageBind | activitynet/paragraph | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  40%|███▉      | 1365/3451 [17:14<29:47,  1.17batch/s]
internvideo2 videos:  40%|███▉      | 1366/3451 [17:15<28:54,  1.20batch/s]
internvideo2 videos:  40%|███▉      | 1367/3451 [17:16<28:21,  1.22batch/s]
internvideo2 videos:  40%|███▉      | 1368/3451 [17:16<27:58,  1.24batch/s]
internvideo2 videos:  40%|███▉      | 1369/3451 [17:17<27:41,  1.25batch/s]
internvideo2 videos:  40%|███▉      | 1370/3451 [17:18<27:27,  1.26batch/s]
internvideo2 videos:  40%|███▉      | 1371/3451 [17:19<27:20,  1.27batch/s]
internvideo2 videos:  40%|███▉      | 1372/3451 [17:19<27:11,  1.27batch/s]
internvideo2 videos:  40%|███▉      | 1373/3451 [17:20<27:02,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 1374/3451 [17:21<27:01,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 1375/3451 [17:22<27:00,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 1376/3451 [17:23<27:00,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 1377/3451 [17:23<26:59,  1.28batch/s]
internvideo2 videos:  40%|███▉      | 1378/3451 [17:24<26:53,  1.29batch/s]
internvideo2 videos:  40%|███▉      | 1379/3451 [17:25<26:49,  1.29batch/s]
internvideo2 videos:  40%|███▉      | 1380/3451 [17:26<26:44,  1.29batch/s]
internvideo2 videos:  40%|████      | 1381/3451 [17:26<26:42,  1.29batch/s]
internvideo2 videos:  40%|████      | 1382/3451 [17:27<26:40,  1.29batch/s]
internvideo2 videos:  40%|████      | 1383/3451 [17:28<26:39,  1.29batch/s]
internvideo2 videos:  40%|████      | 1384/3451 [17:29<26:43,  1.29batch/s]
internvideo2 videos:  40%|████      | 1385/3451 [17:30<26:47,  1.29batch/s]
internvideo2 videos:  40%|████      | 1386/3451 [17:30<26:49,  1.28batch/s]
internvideo2 videos:  40%|████      | 1387/3451 [17:31<26:51,  1.28batch/s]
internvideo2 videos:  40%|████      | 1388/3451 [17:32<26:51,  1.28batch/s]
internvideo2 videos:  40%|████      | 1389/3451 [17:33<26:50,  1.28batch/s]
internvideo2 videos:  40%|████      | 1390/3451 [17:33<26:50,  1.28batch/s]
internvideo2 videos:  40%|████      | 1391/3451 [17:34<26:50,  1.28batch/s]
internvideo2 videos:  40%|████      | 1392/3451 [17:35<26:50,  1.28batch/s]
internvideo2 videos:  40%|████      | 1393/3451 [17:36<26:49,  1.28batch/s]
internvideo2 videos:  40%|████      | 1394/3451 [17:37<26:48,  1.28batch/s]
internvideo2 videos:  40%|████      | 1395/3451 [17:37<26:47,  1.28batch/s]
internvideo2 videos:  40%|████      | 1396/3451 [17:38<26:46,  1.28batch/s]
internvideo2 videos:  40%|████      | 1397/3451 [17:39<26:46,  1.28batch/s]
internvideo2 videos:  41%|████      | 1398/3451 [17:40<26:51,  1.27batch/s]
internvideo2 videos:  41%|████      | 1399/3451 [17:40<26:42,  1.28batch/s]
internvideo2 videos:  41%|████      | 1400/3451 [17:41<26:47,  1.28batch/s]
internvideo2 videos:  41%|████      | 1401/3451 [17:42<26:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 1402/3451 [17:43<26:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 1403/3451 [17:44<26:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 1404/3451 [17:44<26:39,  1.28batch/s]
internvideo2 videos:  41%|████      | 1405/3451 [17:45<26:38,  1.28batch/s]
internvideo2 videos:  41%|████      | 1406/3451 [17:46<26:37,  1.28batch/s]
internvideo2 videos:  41%|████      | 1407/3451 [17:47<26:36,  1.28batch/s]
internvideo2 videos:  41%|████      | 1408/3451 [17:48<26:35,  1.28batch/s]
internvideo2 videos:  41%|████      | 1409/3451 [17:48<26:33,  1.28batch/s]
internvideo2 videos:  41%|████      | 1410/3451 [17:49<26:29,  1.28batch/s]
internvideo2 videos:  41%|████      | 1411/3451 [17:50<26:33,  1.28batch/s]
internvideo2 videos:  41%|████      | 1412/3451 [17:51<26:31,  1.28batch/s]
internvideo2 videos:  41%|████      | 1413/3451 [17:51<26:31,  1.28batch/s]
internvideo2 videos:  41%|████      | 1414/3451 [17:52<26:30,  1.28batch/s]
internvideo2 videos:  41%|████      | 1415/3451 [17:53<26:23,  1.29batch/s]
internvideo2 videos:  41%|████      | 1416/3451 [17:54<26:17,  1.29batch/s]
internvideo2 videos:  41%|████      | 1417/3451 [17:55<26:20,  1.29batch/s]
internvideo2 videos:  41%|████      | 1418/3451 [17:55<26:21,  1.29batch/s]
internvideo2 videos:  41%|████      | 1419/3451 [17:56<26:22,  1.28batch/s]
internvideo2 videos:  41%|████      | 1420/3451 [17:57<26:22,  1.28batch/s]
internvideo2 videos:  41%|████      | 1421/3451 [17:58<26:23,  1.28batch/s]
internvideo2 videos:  41%|████      | 1422/3451 [17:58<26:22,  1.28batch/s]
internvideo2 videos:  41%|████      | 1423/3451 [17:59<26:22,  1.28batch/s]
internvideo2 videos:  41%|████▏     | 1424/3451 [18:00<26:16,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1425/3451 [18:01<26:17,  1.28batch/s]
internvideo2 videos:  41%|████▏     | 1426/3451 [18:02<26:17,  1.28batch/s]
internvideo2 videos:  41%|████▏     | 1427/3451 [18:02<26:11,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1428/3451 [18:03<26:06,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1429/3451 [18:04<26:10,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1430/3451 [18:05<26:12,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1431/3451 [18:05<26:07,  1.29batch/s]
internvideo2 videos:  41%|████▏     | 1432/3451 [18:06<26:03,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1433/3451 [18:07<26:01,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1434/3451 [18:08<25:57,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1435/3451 [18:08<25:55,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1436/3451 [18:09<25:54,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1437/3451 [18:10<25:53,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1438/3451 [18:11<25:52,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1439/3451 [18:12<25:52,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1440/3451 [18:12<25:51,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1441/3451 [18:13<25:50,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1442/3451 [18:14<25:49,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1443/3451 [18:15<25:49,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1444/3451 [18:15<25:48,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1445/3451 [18:16<25:47,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1446/3451 [18:17<25:46,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1447/3451 [18:18<25:51,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1448/3451 [18:19<25:48,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1449/3451 [18:19<25:52,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1450/3451 [18:20<25:51,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1451/3451 [18:21<25:51,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1452/3451 [18:22<26:00,  1.28batch/s]
internvideo2 videos:  42%|████▏     | 1453/3451 [18:22<25:58,  1.28batch/s]
internvideo2 videos:  42%|████▏     | 1454/3451 [18:23<25:52,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1455/3451 [18:24<25:47,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1456/3451 [18:25<25:50,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1457/3451 [18:26<25:52,  1.28batch/s]
internvideo2 videos:  42%|████▏     | 1458/3451 [18:26<25:53,  1.28batch/s]
internvideo2 videos:  42%|████▏     | 1459/3451 [18:27<25:44,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1460/3451 [18:28<25:37,  1.29batch/s]
internvideo2 videos:  42%|████▏     | 1461/3451 [18:29<25:36,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1462/3451 [18:29<25:34,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1463/3451 [18:30<25:33,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1464/3451 [18:31<25:33,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1465/3451 [18:32<25:32,  1.30batch/s]
internvideo2 videos:  42%|████▏     | 1466/3451 [18:32<25:31,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1467/3451 [18:33<25:30,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1468/3451 [18:34<25:29,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1469/3451 [18:35<25:29,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1470/3451 [18:36<25:17,  1.31batch/s]
internvideo2 videos:  43%|████▎     | 1471/3451 [18:36<25:13,  1.31batch/s]
internvideo2 videos:  43%|████▎     | 1472/3451 [18:37<25:10,  1.31batch/s]
internvideo2 videos:  43%|████▎     | 1473/3451 [18:38<25:14,  1.31batch/s]
internvideo2 videos:  43%|████▎     | 1474/3451 [18:39<25:18,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1475/3451 [18:39<25:25,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1476/3451 [18:40<25:24,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1477/3451 [18:41<25:23,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1478/3451 [18:42<25:22,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1479/3451 [18:42<25:21,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1480/3451 [18:43<25:21,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1481/3451 [18:44<25:26,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1482/3451 [18:45<25:23,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1483/3451 [18:46<25:22,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1484/3451 [18:46<25:20,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1485/3451 [18:47<25:19,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1486/3451 [18:48<25:18,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1487/3451 [18:49<25:15,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1488/3451 [18:49<25:15,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1489/3451 [18:50<25:09,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1490/3451 [18:51<25:09,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1491/3451 [18:52<25:15,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1492/3451 [18:53<25:14,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1493/3451 [18:53<25:12,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1494/3451 [18:54<25:10,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1495/3451 [18:55<25:08,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1496/3451 [18:56<25:07,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1497/3451 [18:56<25:07,  1.30batch/s]
internvideo2 videos:  43%|████▎     | 1498/3451 [18:57<25:19,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1499/3451 [18:58<25:13,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1500/3451 [18:59<25:17,  1.29batch/s]
internvideo2 videos:  43%|████▎     | 1501/3451 [18:59<25:13,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1502/3451 [19:00<25:09,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1503/3451 [19:01<25:06,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1504/3451 [19:02<25:04,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1505/3451 [19:03<25:03,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1506/3451 [19:03<25:06,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1507/3451 [19:04<25:04,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1508/3451 [19:05<25:07,  1.29batch/s]
internvideo2 videos:  44%|████▎     | 1509/3451 [19:06<25:09,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1510/3451 [19:06<25:05,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1511/3451 [19:07<25:08,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1512/3451 [19:08<25:03,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1513/3451 [19:09<25:05,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1514/3451 [19:10<25:07,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1515/3451 [19:10<25:07,  1.28batch/s]
internvideo2 videos:  44%|████▍     | 1516/3451 [19:11<25:02,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1517/3451 [19:12<24:58,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1518/3451 [19:13<24:56,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1519/3451 [19:13<24:53,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1520/3451 [19:14<24:51,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1521/3451 [19:15<24:49,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1522/3451 [19:16<24:48,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1523/3451 [19:17<24:47,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1524/3451 [19:17<24:46,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1525/3451 [19:18<24:45,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1526/3451 [19:19<24:44,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1527/3451 [19:20<24:37,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1528/3451 [19:20<24:32,  1.31batch/s]
internvideo2 videos:  44%|████▍     | 1529/3451 [19:21<24:29,  1.31batch/s]
internvideo2 videos:  44%|████▍     | 1530/3451 [19:22<24:31,  1.31batch/s]
internvideo2 videos:  44%|████▍     | 1531/3451 [19:23<24:38,  1.30batch/s]
internvideo2 videos:  44%|████▍     | 1532/3451 [19:23<24:45,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1533/3451 [19:24<24:47,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1534/3451 [19:25<24:44,  1.29batch/s]
internvideo2 videos:  44%|████▍     | 1535/3451 [19:26<24:41,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1536/3451 [19:27<24:39,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1537/3451 [19:27<24:38,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1538/3451 [19:28<24:36,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1539/3451 [19:29<24:34,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1540/3451 [19:30<24:33,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1541/3451 [19:30<24:32,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1542/3451 [19:31<24:31,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1543/3451 [19:32<24:30,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1544/3451 [19:33<24:29,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1545/3451 [19:33<24:34,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1546/3451 [19:34<24:38,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1547/3451 [19:35<24:34,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1548/3451 [19:36<24:31,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1549/3451 [19:37<24:29,  1.29batch/s]
internvideo2 videos:  45%|████▍     | 1550/3451 [19:37<24:27,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1551/3451 [19:38<24:26,  1.30batch/s]
internvideo2 videos:  45%|████▍     | 1552/3451 [19:39<24:25,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1553/3451 [19:40<24:24,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1554/3451 [19:40<24:26,  1.29batch/s]
internvideo2 videos:  45%|████▌     | 1555/3451 [19:41<24:21,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1556/3451 [19:42<24:15,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1557/3451 [19:43<24:11,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1558/3451 [19:43<24:08,  1.31batch/s]
internvideo2 videos:  45%|████▌     | 1559/3451 [19:44<24:17,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1560/3451 [19:45<24:17,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1561/3451 [19:46<24:17,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1562/3451 [19:47<24:16,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1563/3451 [19:47<24:16,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1564/3451 [19:48<24:21,  1.29batch/s]
internvideo2 videos:  45%|████▌     | 1565/3451 [19:49<24:19,  1.29batch/s]
internvideo2 videos:  45%|████▌     | 1566/3451 [19:50<24:12,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1567/3451 [19:50<24:11,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1568/3451 [19:51<24:12,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1569/3451 [19:52<24:11,  1.30batch/s]
internvideo2 videos:  45%|████▌     | 1570/3451 [19:53<24:11,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1571/3451 [19:54<24:10,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1572/3451 [19:54<24:10,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1573/3451 [19:55<24:09,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1574/3451 [19:56<24:09,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1575/3451 [19:57<24:09,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1576/3451 [19:57<24:08,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1577/3451 [19:58<24:07,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1578/3451 [19:59<24:06,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1579/3451 [20:00<24:05,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1580/3451 [20:00<24:04,  1.30batch/s]
internvideo2 videos:  46%|████▌     | 1581/3451 [20:01<24:08,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1582/3451 [20:02<24:11,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1583/3451 [20:03<24:07,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1584/3451 [20:04<24:09,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1585/3451 [20:04<24:11,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1586/3451 [20:05<24:11,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1587/3451 [20:06<24:12,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1588/3451 [20:07<24:12,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1589/3451 [20:08<24:12,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1590/3451 [20:08<24:11,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1591/3451 [20:09<24:05,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1592/3451 [20:10<24:12,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1593/3451 [20:11<24:05,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1594/3451 [20:11<24:06,  1.28batch/s]
internvideo2 videos:  46%|████▌     | 1595/3451 [20:12<24:01,  1.29batch/s]
internvideo2 videos:  46%|████▌     | 1596/3451 [20:13<24:02,  1.29batch/s]
internvideo2 videos:  46%|████▋     | 1597/3451 [20:14<24:03,  1.28batch/s]
internvideo2 videos:  46%|████▋     | 1598/3451 [20:15<24:04,  1.28batch/s]
internvideo2 videos:  46%|████▋     | 1599/3451 [20:15<24:04,  1.28batch/s]
internvideo2 videos:  46%|████▋     | 1600/3451 [20:16<24:03,  1.28batch/s]
internvideo2 videos:  46%|████▋     | 1601/3451 [20:17<23:57,  1.29batch/s]
internvideo2 videos:  46%|████▋     | 1602/3451 [20:18<23:53,  1.29batch/s]
internvideo2 videos:  46%|████▋     | 1603/3451 [20:18<23:49,  1.29batch/s]
internvideo2 videos:  46%|████▋     | 1604/3451 [20:19<23:52,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1605/3451 [20:20<23:54,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1606/3451 [20:21<23:55,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1607/3451 [20:22<23:55,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1608/3451 [20:22<23:56,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1609/3451 [20:23<23:56,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1610/3451 [20:24<23:56,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1611/3451 [20:25<23:50,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1612/3451 [20:25<23:45,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1613/3451 [20:26<23:42,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1614/3451 [20:27<23:40,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1615/3451 [20:28<23:38,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1616/3451 [20:28<23:38,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1617/3451 [20:29<23:40,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1618/3451 [20:30<23:43,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1619/3451 [20:31<23:45,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1620/3451 [20:32<23:46,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1621/3451 [20:32<23:46,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1622/3451 [20:33<23:46,  1.28batch/s]
internvideo2 videos:  47%|████▋     | 1623/3451 [20:34<23:40,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1624/3451 [20:35<23:36,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1625/3451 [20:35<23:38,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1626/3451 [20:36<23:40,  1.29batch/s]
internvideo2 videos:  47%|████▋     | 1627/3451 [20:37<23:40,  1.28batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

languagebind videos:   0%|          | 0/7306 [00:00<?, ?batch/s]
languagebind videos:   0%|          | 2/7306 [00:00<44:12,  2.75batch/s]/s]
languagebind videos:   0%|          | 4/7306 [00:01<42:38,  2.85batch/s]/s]
languagebind videos:   0%|          | 7/7306 [00:02<42:08,  2.89batch/s]/s]
languagebind videos:   0%|          | 9/7306 [00:03<42:04,  2.89batch/s]/s]
languagebind videos:   0%|          | 11/7306 [00:03<41:56,  2.90batch/s]s]
languagebind videos:   0%|          | 13/7306 [00:04<41:55,  2.90batch/s]s]
languagebind videos:   0%|          | 15/7306 [00:05<41:52,  2.90batch/s]s]
languagebind videos:   0%|          | 18/7306 [00:06<42:01,  2.89batch/s]s]
languagebind videos:   0%|          | 20/7306 [00:06<41:54,  2.90batch/s]s]
languagebind videos:   0%|          | 22/7306 [00:07<41:51,  2.90batch/s]s]
languagebind videos:   0%|          | 24/7306 [00:08<42:05,  2.88batch/s]s]
languagebind videos:   0%|          | 26/7306 [00:09<42:21,  2.86batch/s]s]
languagebind videos:   0%|          | 29/7306 [00:10<42:09,  2.88batch/s]s]
languagebind videos:   0%|          | 31/7306 [00:10<41:54,  2.89batch/s]s]
languagebind videos:   0%|          | 33/7306 [00:11<42:02,  2.88batch/s]s]
languagebind videos:   0%|          | 35/7306 [00:12<42:04,  2.88batch/s]s]
languagebind videos:   1%|          | 38/7306 [00:13<42:31,  2.85batch/s]s]
languagebind videos:   1%|          | 40/7306 [00:13<43:26,  2.79batch/s]s]
languagebind videos:   1%|          | 42/7306 [00:14<44:00,  2.75batch/s]s]
languagebind videos:   1%|          | 44/7306 [00:15<45:01,  2.69batch/s]s]
languagebind videos:   1%|          | 46/7306 [00:16<45:10,  2.68batch/s]s]
languagebind videos:   1%|          | 48/7306 [00:16<44:14,  2.73batch/s]s]
languagebind videos:   1%|          | 50/7306 [00:17<43:18,  2.79batch/s]s]
languagebind videos:   1%|          | 52/7306 [00:18<43:01,  2.81batch/s]s]
languagebind videos:   1%|          | 55/7306 [00:19<42:54,  2.82batch/s]s]
languagebind videos:   1%|          | 57/7306 [00:20<43:25,  2.78batch/s]s]
languagebind videos:   1%|          | 59/7306 [00:20<43:00,  2.81batch/s]s]
languagebind videos:   1%|          | 61/7306 [00:21<43:25,  2.78batch/s]s]
languagebind videos:   1%|          | 63/7306 [00:22<43:18,  2.79batch/s]s]
languagebind videos:   1%|          | 65/7306 [00:22<43:22,  2.78batch/s]s]
languagebind videos:   1%|          | 67/7306 [00:23<43:27,  2.78batch/s]s]
languagebind videos:   1%|          | 69/7306 [00:24<43:25,  2.78batch/s]s]
languagebind videos:   1%|          | 72/7306 [00:25<43:21,  2.78batch/s]s]
languagebind videos:   1%|          | 74/7306 [00:26<43:22,  2.78batch/s]s]
languagebind videos:   1%|          | 76/7306 [00:26<43:13,  2.79batch/s]s]
languagebind videos:   1%|          | 78/7306 [00:27<43:17,  2.78batch/s]s]
languagebind videos:   1%|          | 80/7306 [00:28<43:21,  2.78batch/s]s]
languagebind videos:   1%|          | 82/7306 [00:29<43:52,  2.74batch/s]s]
languagebind videos:   1%|          | 84/7306 [00:29<43:51,  2.74batch/s]s]
languagebind videos:   1%|          | 86/7306 [00:30<44:12,  2.72batch/s]s]
languagebind videos:   1%|          | 89/7306 [00:31<43:54,  2.74batch/s]s]
languagebind videos:   1%|          | 91/7306 [00:32<43:57,  2.74batch/s]s]
languagebind videos:   1%|▏         | 93/7306 [00:33<43:53,  2.74batch/s]s]
languagebind videos:   1%|▏         | 95/7306 [00:33<43:52,  2.74batch/s]s]
languagebind videos:   1%|▏         | 97/7306 [00:34<43:50,  2.74batch/s]s]
languagebind videos:   1%|▏         | 99/7306 [00:35<43:46,  2.74batch/s]s]
languagebind videos:   1%|▏         | 101/7306 [00:36<43:41,  2.75batch/s]]
languagebind videos:   1%|▏         | 103/7306 [00:36<44:19,  2.71batch/s]]
languagebind videos:   1%|▏         | 105/7306 [00:37<44:26,  2.70batch/s]]
languagebind videos:   1%|▏         | 108/7306 [00:38<44:24,  2.70batch/s]]
languagebind videos:   2%|▏         | 110/7306 [00:39<44:18,  2.71batch/s]]
languagebind videos:   2%|▏         | 112/7306 [00:40<43:45,  2.74batch/s]]
languagebind videos:   2%|▏         | 114/7306 [00:40<43:30,  2.76batch/s]]
languagebind videos:   2%|▏         | 116/7306 [00:41<43:31,  2.75batch/s]]
languagebind videos:   2%|▏         | 118/7306 [00:42<43:21,  2.76batch/s]]
languagebind videos:   2%|▏         | 120/7306 [00:42<43:31,  2.75batch/s]]
languagebind videos:   2%|▏         | 122/7306 [00:43<43:56,  2.73batch/s]]
languagebind videos:   2%|▏         | 125/7306 [00:44<43:51,  2.73batch/s]]
languagebind videos:   2%|▏         | 127/7306 [00:45<43:58,  2.72batch/s]]
languagebind videos:   2%|▏         | 129/7306 [00:46<44:04,  2.71batch/s]]
languagebind videos:   2%|▏         | 131/7306 [00:47<43:48,  2.73batch/s]]
languagebind videos:   2%|▏         | 133/7306 [00:47<43:41,  2.74batch/s]]
languagebind videos:   2%|▏         | 135/7306 [00:48<43:32,  2.74batch/s]]
languagebind videos:   2%|▏         | 137/7306 [00:49<43:54,  2.72batch/s]]
languagebind videos:   2%|▏         | 139/7306 [00:49<43:56,  2.72batch/s]]
languagebind videos:   2%|▏         | 142/7306 [00:51<44:05,  2.71batch/s]]
languagebind videos:   2%|▏         | 144/7306 [00:51<44:24,  2.69batch/s]]
languagebind videos:   2%|▏         | 146/7306 [00:52<43:54,  2.72batch/s]]
languagebind videos:   2%|▏         | 148/7306 [00:53<43:52,  2.72batch/s]]
languagebind videos:   2%|▏         | 150/7306 [00:54<43:59,  2.71batch/s]]
languagebind videos:   2%|▏         | 152/7306 [00:54<44:02,  2.71batch/s]]
languagebind videos:   2%|▏         | 154/7306 [00:55<44:04,  2.70batch/s]]
languagebind videos:   2%|▏         | 156/7306 [00:56<44:12,  2.70batch/s]]
languagebind videos:   2%|▏         | 158/7306 [00:57<44:36,  2.67batch/s]]
languagebind videos:   2%|▏         | 160/7306 [00:57<44:28,  2.68batch/s]]
languagebind videos:   2%|▏         | 162/7306 [00:58<44:50,  2.66batch/s]]
languagebind videos:   2%|▏         | 164/7306 [00:59<45:10,  2.64batch/s]]
languagebind videos:   2%|▏         | 166/7306 [01:00<44:57,  2.65batch/s]]
languagebind videos:   2%|▏         | 168/7306 [01:00<46:25,  2.56batch/s]]
languagebind videos:   2%|▏         | 170/7306 [01:01<46:43,  2.55batch/s]]
languagebind videos:   2%|▏         | 172/7306 [01:02<47:35,  2.50batch/s]]
languagebind videos:   2%|▏         | 174/7306 [01:03<46:39,  2.55batch/s]]
languagebind videos:   2%|▏         | 176/7306 [01:03<45:28,  2.61batch/s]]
languagebind videos:   2%|▏         | 178/7306 [01:04<45:02,  2.64batch/s]]
languagebind videos:   2%|▏         | 180/7306 [01:05<44:44,  2.65batch/s]]
languagebind videos:   2%|▏         | 182/7306 [01:06<44:52,  2.65batch/s]]
languagebind videos:   3%|▎         | 184/7306 [01:06<44:56,  2.64batch/s]]
languagebind videos:   3%|▎         | 186/7306 [01:07<44:55,  2.64batch/s]]
languagebind videos:   3%|▎         | 188/7306 [01:08<45:25,  2.61batch/s]]
languagebind videos:   3%|▎         | 190/7306 [01:09<45:09,  2.63batch/s]]
languagebind videos:   3%|▎         | 192/7306 [01:10<44:50,  2.64batch/s]]
languagebind videos:   3%|▎         | 194/7306 [01:10<44:52,  2.64batch/s]]
languagebind videos:   3%|▎         | 196/7306 [01:11<44:58,  2.63batch/s]]
languagebind videos:   3%|▎         | 198/7306 [01:12<45:04,  2.63batch/s]]
languagebind videos:   3%|▎         | 200/7306 [01:13<45:06,  2.63batch/s]]
languagebind videos:   3%|▎         | 203/7306 [01:14<45:03,  2.63batch/s]]
languagebind videos:   3%|▎         | 205/7306 [01:14<45:05,  2.62batch/s]]
languagebind videos:   3%|▎         | 207/7306 [01:15<45:05,  2.62batch/s]]
languagebind videos:   3%|▎         | 209/7306 [01:16<45:12,  2.62batch/s]]
languagebind videos:   3%|▎         | 211/7306 [01:17<45:14,  2.61batch/s]]
languagebind videos:   3%|▎         | 213/7306 [01:18<45:28,  2.60batch/s]]
languagebind videos:   3%|▎         | 214/7306 [01:18<45:56,  2.57batch/s]]
languagebind videos:   3%|▎         | 216/7306 [01:19<46:23,  2.55batch/s]]
languagebind videos:   3%|▎         | 218/7306 [01:19<46:00,  2.57batch/s]]
languagebind videos:   3%|▎         | 220/7306 [01:20<45:46,  2.58batch/s]]
languagebind videos:   3%|▎         | 222/7306 [01:21<45:51,  2.57batch/s]]
languagebind videos:   3%|▎         | 224/7306 [01:22<45:44,  2.58batch/s]]
languagebind videos:   3%|▎         | 226/7306 [01:23<45:54,  2.57batch/s]]
languagebind videos:   3%|▎         | 228/7306 [01:23<45:40,  2.58batch/s]]
languagebind videos:   3%|▎         | 231/7306 [01:25<45:37,  2.58batch/s]]
languagebind videos:   3%|▎         | 233/7306 [01:25<45:36,  2.58batch/s]]
languagebind videos:   3%|▎         | 235/7306 [01:26<45:37,  2.58batch/s]]
languagebind videos:   3%|▎         | 237/7306 [01:27<45:53,  2.57batch/s]]
languagebind videos:   3%|▎         | 239/7306 [01:28<45:52,  2.57batch/s]]
languagebind videos:   3%|▎         | 240/7306 [01:28<46:12,  2.55batch/s]]
languagebind videos:   3%|▎         | 242/7306 [01:29<46:14,  2.55batch/s]]
languagebind videos:   3%|▎         | 244/7306 [01:30<46:01,  2.56batch/s]]
languagebind videos:   3%|▎         | 246/7306 [01:30<46:02,  2.56batch/s]]
languagebind videos:   3%|▎         | 248/7306 [01:31<46:01,  2.56batch/s]]
languagebind videos:   3%|▎         | 251/7306 [01:32<45:42,  2.57batch/s]]
languagebind videos:   3%|▎         | 253/7306 [01:33<45:40,  2.57batch/s]]
languagebind videos:   3%|▎         | 255/7306 [01:34<45:49,  2.56batch/s]]
languagebind videos:   4%|▎         | 256/7306 [01:34<46:00,  2.55batch/s]]
languagebind videos:   4%|▎         | 258/7306 [01:35<47:27,  2.47batch/s]]
languagebind videos:   4%|▎         | 260/7306 [01:36<47:13,  2.49batch/s]]
languagebind videos:   4%|▎         | 262/7306 [01:37<46:43,  2.51batch/s]]
languagebind videos:   4%|▎         | 264/7306 [01:37<46:12,  2.54batch/s]]
languagebind videos:   4%|▎         | 266/7306 [01:38<46:05,  2.55batch/s]]
languagebind videos:   4%|▎         | 268/7306 [01:39<46:08,  2.54batch/s]]
languagebind videos:   4%|▎         | 270/7306 [01:40<45:55,  2.55batch/s]]
languagebind videos:   4%|▎         | 272/7306 [01:41<45:38,  2.57batch/s]]
languagebind videos:   4%|▍         | 274/7306 [01:41<45:37,  2.57batch/s]]
languagebind videos:   4%|▍         | 276/7306 [01:42<45:41,  2.56batch/s]]
languagebind videos:   4%|▍         | 278/7306 [01:43<45:52,  2.55batch/s]]
languagebind videos:   4%|▍         | 280/7306 [01:44<46:04,  2.54batch/s]]
languagebind videos:   4%|▍         | 282/7306 [01:45<45:57,  2.55batch/s]]
languagebind videos:   4%|▍         | 284/7306 [01:45<45:58,  2.55batch/s]]
languagebind videos:   4%|▍         | 286/7306 [01:46<46:05,  2.54batch/s]]
languagebind videos:   4%|▍         | 288/7306 [01:47<45:53,  2.55batch/s]]
languagebind videos:   4%|▍         | 290/7306 [01:48<45:46,  2.55batch/s]]
languagebind videos:   4%|▍         | 292/7306 [01:48<45:57,  2.54batch/s]]
languagebind videos:   4%|▍         | 294/7306 [01:49<45:48,  2.55batch/s]]
languagebind videos:   4%|▍         | 296/7306 [01:50<45:56,  2.54batch/s]]
languagebind videos:   4%|▍         | 298/7306 [01:51<45:59,  2.54batch/s]]
languagebind videos:   4%|▍         | 300/7306 [01:52<46:03,  2.54batch/s]]
languagebind videos:   4%|▍         | 301/7306 [01:52<46:18,  2.52batch/s]]
languagebind videos:   4%|▍         | 303/7306 [01:53<47:03,  2.48batch/s]]
languagebind videos:   4%|▍         | 305/7306 [01:54<46:38,  2.50batch/s]]
languagebind videos:   4%|▍         | 307/7306 [01:54<46:27,  2.51batch/s]]
languagebind videos:   4%|▍         | 309/7306 [01:55<46:41,  2.50batch/s]]
languagebind videos:   4%|▍         | 311/7306 [01:56<46:14,  2.52batch/s]]
languagebind videos:   4%|▍         | 313/7306 [01:57<46:08,  2.53batch/s]]
languagebind videos:   4%|▍         | 315/7306 [01:58<46:03,  2.53batch/s]]
languagebind videos:   4%|▍         | 317/7306 [01:58<46:12,  2.52batch/s]]
languagebind videos:   4%|▍         | 319/7306 [01:59<46:08,  2.52batch/s]]
languagebind videos:   4%|▍         | 321/7306 [02:00<46:17,  2.51batch/s]]
languagebind videos:   4%|▍         | 323/7306 [02:01<46:17,  2.51batch/s]]
languagebind videos:   4%|▍         | 325/7306 [02:02<46:23,  2.51batch/s]]
languagebind videos:   4%|▍         | 327/7306 [02:02<46:20,  2.51batch/s]]
languagebind videos:   5%|▍         | 329/7306 [02:03<46:28,  2.50batch/s]]
languagebind videos:   5%|▍         | 330/7306 [02:04<46:38,  2.49batch/s]]
languagebind videos:   5%|▍         | 332/7306 [02:04<46:50,  2.48batch/s]]
languagebind videos:   5%|▍         | 334/7306 [02:05<46:59,  2.47batch/s]]
languagebind videos:   5%|▍         | 336/7306 [02:06<47:04,  2.47batch/s]]
languagebind videos:   5%|▍         | 338/7306 [02:07<47:14,  2.46batch/s]]
languagebind videos:   5%|▍         | 340/7306 [02:08<47:00,  2.47batch/s]]
languagebind videos:   5%|▍         | 342/7306 [02:08<46:46,  2.48batch/s]]
languagebind videos:   5%|▍         | 344/7306 [02:09<46:45,  2.48batch/s]]
languagebind videos:   5%|▍         | 346/7306 [02:10<46:25,  2.50batch/s]]
languagebind videos:   5%|▍         | 348/7306 [02:11<46:23,  2.50batch/s]]
languagebind videos:   5%|▍         | 350/7306 [02:12<46:29,  2.49batch/s]]
languagebind videos:   5%|▍         | 351/7306 [02:12<46:33,  2.49batch/s]]
languagebind videos:   5%|▍         | 353/7306 [02:13<46:48,  2.48batch/s]]
languagebind videos:   5%|▍         | 355/7306 [02:14<46:55,  2.47batch/s]]
languagebind videos:   5%|▍         | 357/7306 [02:14<46:53,  2.47batch/s]]
languagebind videos:   5%|▍         | 359/7306 [02:15<46:46,  2.48batch/s]]
languagebind videos:   5%|▍         | 361/7306 [02:16<46:39,  2.48batch/s]]
languagebind videos:   5%|▍         | 363/7306 [02:17<46:29,  2.49batch/s]]
languagebind videos:   5%|▍         | 365/7306 [02:18<46:19,  2.50batch/s]]
languagebind videos:   5%|▌         | 367/7306 [02:18<46:28,  2.49batch/s]]
languagebind videos:   5%|▌         | 369/7306 [02:19<46:31,  2.49batch/s]]
languagebind videos:   5%|▌         | 371/7306 [02:20<46:25,  2.49batch/s]]
languagebind videos:   5%|▌         | 373/7306 [02:21<46:21,  2.49batch/s]]
languagebind videos:   5%|▌         | 374/7306 [02:21<46:28,  2.49batch/s]]
languagebind videos:   5%|▌         | 376/7306 [02:22<46:43,  2.47batch/s]]
languagebind videos:   5%|▌         | 378/7306 [02:23<47:03,  2.45batch/s]]
languagebind videos:   5%|▌         | 380/7306 [02:24<47:05,  2.45batch/s]]
languagebind videos:   5%|▌         | 382/7306 [02:25<47:08,  2.45batch/s]]
languagebind videos:   5%|▌         | 384/7306 [02:25<47:00,  2.45batch/s]]
languagebind videos:   5%|▌         | 386/7306 [02:26<47:13,  2.44batch/s]]
languagebind videos:   5%|▌         | 388/7306 [02:27<47:01,  2.45batch/s]]
languagebind videos:   5%|▌         | 390/7306 [02:28<47:08,  2.45batch/s]]
languagebind videos:   5%|▌         | 392/7306 [02:29<46:50,  2.46batch/s]]
languagebind videos:   5%|▌         | 393/7306 [02:29<47:06,  2.45batch/s]]
languagebind videos:   5%|▌         | 395/7306 [02:30<47:15,  2.44batch/s]]
languagebind videos:   5%|▌         | 397/7306 [02:31<47:26,  2.43batch/s]]
languagebind videos:   5%|▌         | 399/7306 [02:31<47:17,  2.43batch/s]]
languagebind videos:   5%|▌         | 401/7306 [02:32<47:18,  2.43batch/s]]
languagebind videos:   6%|▌         | 403/7306 [02:33<47:09,  2.44batch/s]]
languagebind videos:   6%|▌         | 405/7306 [02:34<47:03,  2.44batch/s]]
languagebind videos:   6%|▌         | 407/7306 [02:35<47:09,  2.44batch/s]]
languagebind videos:   6%|▌         | 408/7306 [02:35<47:01,  2.44batch/s]]
languagebind videos:   6%|▌         | 410/7306 [02:36<47:07,  2.44batch/s]]
languagebind videos:   6%|▌         | 412/7306 [02:37<47:19,  2.43batch/s]]
languagebind videos:   6%|▌         | 414/7306 [02:38<47:19,  2.43batch/s]]
languagebind videos:   6%|▌         | 416/7306 [02:38<47:26,  2.42batch/s]]
languagebind videos:   6%|▌         | 418/7306 [02:39<47:27,  2.42batch/s]]
languagebind videos:   6%|▌         | 420/7306 [02:40<47:29,  2.42batch/s]]
languagebind videos:   6%|▌         | 422/7306 [02:41<47:17,  2.43batch/s]]
languagebind videos:   6%|▌         | 424/7306 [02:42<47:15,  2.43batch/s]]
languagebind videos:   6%|▌         | 425/7306 [02:42<47:28,  2.42batch/s]]
languagebind videos:   6%|▌         | 427/7306 [02:43<47:44,  2.40batch/s]]
languagebind videos:   6%|▌         | 429/7306 [02:44<47:30,  2.41batch/s]]
languagebind videos:   6%|▌         | 431/7306 [02:45<47:16,  2.42batch/s]]
languagebind videos:   6%|▌         | 433/7306 [02:45<46:56,  2.44batch/s]]
languagebind videos:   6%|▌         | 435/7306 [02:46<46:49,  2.45batch/s]]
languagebind videos:   6%|▌         | 437/7306 [02:47<46:53,  2.44batch/s]]
languagebind videos:   6%|▌         | 439/7306 [02:48<46:47,  2.45batch/s]]
languagebind videos:   6%|▌         | 440/7306 [02:48<46:47,  2.45batch/s]]
languagebind videos:   6%|▌         | 442/7306 [02:49<46:45,  2.45batch/s]]
languagebind videos:   6%|▌         | 444/7306 [02:50<46:45,  2.45batch/s]]
languagebind videos:   6%|▌         | 446/7306 [02:51<46:45,  2.45batch/s]]
languagebind videos:   6%|▌         | 448/7306 [02:52<46:43,  2.45batch/s]]
languagebind videos:   6%|▌         | 450/7306 [02:52<46:51,  2.44batch/s]]
languagebind videos:   6%|▌         | 452/7306 [02:53<46:55,  2.43batch/s]]
languagebind videos:   6%|▌         | 454/7306 [02:54<46:55,  2.43batch/s]]
languagebind videos:   6%|▌         | 456/7306 [02:55<46:51,  2.44batch/s]]
languagebind videos:   6%|▋         | 457/7306 [02:55<46:52,  2.44batch/s]]
languagebind videos:   6%|▋         | 459/7306 [02:56<47:01,  2.43batch/s]]
languagebind videos:   6%|▋         | 461/7306 [02:57<46:50,  2.44batch/s]]
languagebind videos:   6%|▋         | 463/7306 [02:58<46:51,  2.43batch/s]]
languagebind videos:   6%|▋         | 465/7306 [02:59<46:44,  2.44batch/s]]
languagebind videos:   6%|▋         | 467/7306 [02:59<46:40,  2.44batch/s]]
languagebind videos:   6%|▋         | 469/7306 [03:00<46:56,  2.43batch/s]]
languagebind videos:   6%|▋         | 471/7306 [03:01<46:59,  2.42batch/s]]
languagebind videos:   6%|▋         | 472/7306 [03:01<46:52,  2.43batch/s]]
languagebind videos:   6%|▋         | 474/7306 [03:02<47:10,  2.41batch/s]]
languagebind videos:   7%|▋         | 476/7306 [03:03<46:55,  2.43batch/s]]
languagebind videos:   7%|▋         | 478/7306 [03:04<46:42,  2.44batch/s]]
languagebind videos:   7%|▋         | 480/7306 [03:05<46:47,  2.43batch/s]]
languagebind videos:   7%|▋         | 482/7306 [03:06<46:49,  2.43batch/s]]
languagebind videos:   7%|▋         | 484/7306 [03:06<46:42,  2.43batch/s]]
languagebind videos:   7%|▋         | 486/7306 [03:07<47:01,  2.42batch/s]]
languagebind videos:   7%|▋         | 488/7306 [03:08<46:59,  2.42batch/s]]
languagebind videos:   7%|▋         | 489/7306 [03:08<47:01,  2.42batch/s]]
languagebind videos:   7%|▋         | 491/7306 [03:09<47:07,  2.41batch/s]]
languagebind videos:   7%|▋         | 493/7306 [03:10<47:14,  2.40batch/s]]
languagebind videos:   7%|▋         | 495/7306 [03:11<47:14,  2.40batch/s]]
languagebind videos:   7%|▋         | 497/7306 [03:12<47:10,  2.41batch/s]]
languagebind videos:   7%|▋         | 499/7306 [03:13<47:15,  2.40batch/s]]
languagebind videos:   7%|▋         | 501/7306 [03:13<47:12,  2.40batch/s]]
languagebind videos:   7%|▋         | 502/7306 [03:14<47:10,  2.40batch/s]]
languagebind videos:   7%|▋         | 504/7306 [03:15<47:16,  2.40batch/s]]
languagebind videos:   7%|▋         | 506/7306 [03:16<47:21,  2.39batch/s]]
languagebind videos:   7%|▋         | 508/7306 [03:16<47:10,  2.40batch/s]]
languagebind videos:   7%|▋         | 510/7306 [03:17<47:00,  2.41batch/s]]
languagebind videos:   7%|▋         | 512/7306 [03:18<46:55,  2.41batch/s]]
languagebind videos:   7%|▋         | 514/7306 [03:19<46:54,  2.41batch/s]]
languagebind videos:   7%|▋         | 515/7306 [03:19<46:58,  2.41batch/s]]
languagebind videos:   7%|▋         | 517/7306 [03:20<47:04,  2.40batch/s]]
languagebind videos:   7%|▋         | 519/7306 [03:21<47:09,  2.40batch/s]]
languagebind videos:   7%|▋         | 521/7306 [03:22<47:13,  2.39batch/s]]

-- mean: R1 69.10  mAP 79.78  mINP 79.78
-- mean_s8: R1 69.80  mAP 80.24  mINP 80.24
-- max: R1 60.20  mAP 73.13  mINP 73.13
-- query_max: R1 67.20  mAP 78.41  mINP 78.41
== InternVideo2 CLIP-S | activitynet/sentence | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:  39%|███▉      | 2833/7306 [20:37<57:05,  1.31batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

internvideo2 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
internvideo2 texts:   2%|▏         | 5/227 [00:00<00:04, 48.78batch/s]
languagebind videos:  39%|███▉      | 2834/7306 [20:38<55:17,  1.35batch/s]
internvideo2 texts:   8%|▊         | 18/227 [00:00<00:03, 56.60batch/s]
internvideo2 texts:  11%|█         | 24/227 [00:00<00:03, 51.16batch/s]
internvideo2 texts:  13%|█▎        | 30/227 [00:00<00:03, 52.69batch/s]
languagebind videos:  39%|███▉      | 2835/7306 [20:38<48:43,  1.53batch/s]
internvideo2 texts:  19%|█▊        | 42/227 [00:00<00:03, 52.06batch/s]
internvideo2 texts:  21%|██        | 48/227 [00:00<00:03, 51.46batch/s]
internvideo2 texts:  24%|██▍       | 55/227 [00:01<00:03, 55.47batch/s]
languagebind videos:  39%|███▉      | 2836/7306 [20:39<44:19,  1.68batch/s]
internvideo2 texts:  30%|███       | 69/227 [00:01<00:02, 58.80batch/s]
internvideo2 texts:  33%|███▎      | 75/227 [00:01<00:02, 55.53batch/s]
internvideo2 texts:  36%|███▌      | 82/227 [00:01<00:02, 58.12batch/s]
languagebind videos:  39%|███▉      | 2837/7306 [20:39<41:14,  1.81batch/s]
internvideo2 texts:  42%|████▏     | 96/227 [00:01<00:02, 62.12batch/s]
internvideo2 texts:  45%|████▌     | 103/227 [00:01<00:02, 57.07batch/s]
internvideo2 texts:  48%|████▊     | 109/227 [00:01<00:02, 55.50batch/s]
languagebind videos:  39%|███▉      | 2838/7306 [20:40<39:02,  1.91batch/s]
internvideo2 texts:  53%|█████▎    | 121/227 [00:02<00:01, 55.19batch/s]
internvideo2 texts:  56%|█████▌    | 127/227 [00:02<00:02, 47.19batch/s]
internvideo2 texts:  59%|█████▉    | 135/227 [00:02<00:01, 53.85batch/s]
languagebind videos:  39%|███▉      | 2839/7306 [20:40<37:24,  1.99batch/s]
internvideo2 texts:  66%|██████▌   | 150/227 [00:02<00:01, 55.56batch/s]
internvideo2 texts:  69%|██████▊   | 156/227 [00:02<00:01, 52.54batch/s]
languagebind videos:  39%|███▉      | 2840/7306 [20:41<36:13,  2.05batch/s]
internvideo2 texts:  74%|███████▍  | 168/227 [00:03<00:01, 54.09batch/s]
internvideo2 texts:  77%|███████▋  | 174/227 [00:03<00:01, 51.58batch/s]
internvideo2 texts:  80%|███████▉  | 181/227 [00:03<00:00, 55.04batch/s]
languagebind videos:  39%|███▉      | 2841/7306 [20:41<35:34,  2.09batch/s]
internvideo2 texts:  86%|████████▌ | 195/227 [00:03<00:00, 56.52batch/s]
internvideo2 texts:  89%|████████▊ | 201/227 [00:03<00:00, 53.45batch/s]
internvideo2 texts:  92%|█████████▏| 208/227 [00:03<00:00, 57.10batch/s]
languagebind videos:  39%|███▉      | 2842/7306 [20:42<35:16,  2.11batch/s]
internvideo2 texts: 100%|██████████| 227/227 [00:04<00:00, 55.80batch/s]
languagebind videos:  39%|███▉      | 2864/7306 [20:54<55:00,  1.35batch/s]

-- mean: R1 36.60  mAP 49.98  mINP 49.98
-- mean_s8: R1 36.22  mAP 49.91  mINP 49.91
-- max: R1 32.76  mAP 46.33  mINP 46.33
-- query_max: R1 39.01  mAP 52.09  mINP 52.09
== InternVideo2 CLIP-S | activitynet/paragraph | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos:  51%|█████     | 3702/7306 [27:16<27:18,  2.20batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

languagebind videos:  51%|█████     | 3703/7306 [27:16<27:37,  2.17batch/s]
languagebind videos:  51%|█████     | 3704/7306 [27:18<41:52,  1.43batch/s]
languagebind videos:  51%|█████     | 3706/7306 [27:19<34:15,  1.75batch/s][A
languagebind videos:  51%|█████     | 3707/7306 [27:19<32:06,  1.87batch/s][A
languagebind videos:  51%|█████     | 3709/7306 [27:20<29:28,  2.03batch/s][A
languagebind videos:  51%|█████     | 3710/7306 [27:20<28:41,  2.09batch/s][A
languagebind videos:  51%|█████     | 3712/7306 [27:21<27:54,  2.15batch/s][A
languagebind videos:  51%|█████     | 3713/7306 [27:22<27:40,  2.16batch/s][A
languagebind videos:  51%|█████     | 3715/7306 [27:23<27:13,  2.20batch/s][A
languagebind videos:  51%|█████     | 3716/7306 [27:23<27:07,  2.21batch/s][A
languagebind videos:  51%|█████     | 3718/7306 [27:24<27:01,  2.21batch/s][A
languagebind videos:  51%|█████     | 3719/7306 [27:24<27:09,  2.20batch/s]
languagebind videos:  51%|█████     | 3720/7306 [27:25<27:07,  2.20batch/s]
languagebind videos:  51%|█████     | 3722/7306 [27:26<27:09,  2.20batch/s]
languagebind videos:  51%|█████     | 3723/7306 [27:26<27:07,  2.20batch/s]
languagebind videos:  51%|█████     | 3725/7306 [27:27<27:01,  2.21batch/s]
languagebind videos:  51%|█████     | 3726/7306 [27:28<26:56,  2.21batch/s]
languagebind videos:  51%|█████     | 3728/7306 [27:29<26:58,  2.21batch/s]
languagebind videos:  51%|█████     | 3729/7306 [27:29<26:59,  2.21batch/s]
languagebind videos:  51%|█████     | 3731/7306 [27:30<27:05,  2.20batch/s]
languagebind videos:  51%|█████     | 3732/7306 [27:30<27:02,  2.20batch/s]
languagebind videos:  51%|█████     | 3734/7306 [27:31<26:53,  2.21batch/s]
languagebind videos:  51%|█████     | 3735/7306 [27:32<26:49,  2.22batch/s]
languagebind videos:  51%|█████     | 3737/7306 [27:33<26:52,  2.21batch/s]
languagebind videos:  51%|█████     | 3738/7306 [27:33<26:54,  2.21batch/s]
languagebind videos:  51%|█████     | 3740/7306 [27:34<26:55,  2.21batch/s]
languagebind videos:  51%|█████     | 3741/7306 [27:34<26:50,  2.21batch/s]
languagebind videos:  51%|█████     | 3743/7306 [27:35<26:50,  2.21batch/s]
languagebind videos:  51%|█████     | 3744/7306 [27:36<26:45,  2.22batch/s]
languagebind videos:  51%|█████▏    | 3746/7306 [27:37<26:39,  2.23batch/s]
languagebind videos:  51%|█████▏    | 3747/7306 [27:37<26:39,  2.23batch/s]
languagebind videos:  51%|█████▏    | 3749/7306 [27:38<26:54,  2.20batch/s]
languagebind videos:  51%|█████▏    | 3750/7306 [27:38<26:52,  2.21batch/s]
languagebind videos:  51%|█████▏    | 3752/7306 [27:39<26:53,  2.20batch/s]
languagebind videos:  51%|█████▏    | 3753/7306 [27:40<26:55,  2.20batch/s]
languagebind videos:  51%|█████▏    | 3755/7306 [27:41<26:54,  2.20batch/s]
languagebind videos:  51%|█████▏    | 3756/7306 [27:41<26:53,  2.20batch/s]
languagebind videos:  51%|█████▏    | 3758/7306 [27:42<26:41,  2.22batch/s]
languagebind videos:  51%|█████▏    | 3759/7306 [27:43<26:38,  2.22batch/s]
languagebind videos:  51%|█████▏    | 3761/7306 [27:43<26:36,  2.22batch/s]
languagebind videos:  51%|█████▏    | 3762/7306 [27:44<26:32,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3764/7306 [27:45<26:32,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3765/7306 [27:45<26:36,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3767/7306 [27:46<26:40,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3768/7306 [27:47<26:39,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3770/7306 [27:47<26:33,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3771/7306 [27:48<26:41,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3773/7306 [27:49<26:43,  2.20batch/s]
languagebind videos:  52%|█████▏    | 3774/7306 [27:49<26:40,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3776/7306 [27:50<26:40,  2.20batch/s]
languagebind videos:  52%|█████▏    | 3777/7306 [27:51<26:37,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3779/7306 [27:52<26:38,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3780/7306 [27:52<26:39,  2.20batch/s]
languagebind videos:  52%|█████▏    | 3782/7306 [27:53<26:29,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3783/7306 [27:53<26:29,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3785/7306 [27:54<26:25,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3786/7306 [27:55<26:21,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3788/7306 [27:56<26:17,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3789/7306 [27:56<26:13,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3791/7306 [27:57<26:12,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3792/7306 [27:57<26:12,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3794/7306 [27:58<26:18,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3795/7306 [27:59<26:31,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3797/7306 [28:00<26:31,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3799/7306 [28:01<26:17,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3800/7306 [28:01<26:17,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3802/7306 [28:02<26:15,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3803/7306 [28:02<26:10,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3805/7306 [28:03<26:14,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3806/7306 [28:04<26:16,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3808/7306 [28:05<26:08,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3809/7306 [28:05<26:06,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3811/7306 [28:06<26:07,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3812/7306 [28:06<26:05,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3814/7306 [28:07<26:06,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3815/7306 [28:08<26:10,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3817/7306 [28:09<26:12,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3819/7306 [28:10<26:12,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3820/7306 [28:10<26:10,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3822/7306 [28:11<25:58,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3823/7306 [28:11<25:57,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3825/7306 [28:12<25:57,  2.24batch/s]
languagebind videos:  52%|█████▏    | 3826/7306 [28:13<26:03,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3828/7306 [28:14<26:01,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3829/7306 [28:14<25:58,  2.23batch/s]
languagebind videos:  52%|█████▏    | 3831/7306 [28:15<26:13,  2.21batch/s]
languagebind videos:  52%|█████▏    | 3832/7306 [28:15<26:06,  2.22batch/s]
languagebind videos:  52%|█████▏    | 3834/7306 [28:16<26:09,  2.21batch/s]
languagebind videos:  53%|█████▎    | 3836/7306 [28:17<25:55,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3837/7306 [28:18<25:55,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3839/7306 [28:19<25:50,  2.24batch/s]
languagebind videos:  53%|█████▎    | 3840/7306 [28:19<25:54,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3842/7306 [28:20<25:59,  2.22batch/s]
languagebind videos:  53%|█████▎    | 3843/7306 [28:20<25:53,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3845/7306 [28:21<25:54,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3846/7306 [28:22<25:52,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3848/7306 [28:23<25:53,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3850/7306 [28:23<25:49,  2.23batch/s]
languagebind videos:  53%|█████▎    | 3851/7306 [28:24<25:54,  2.22batch/s]
languagebind videos:  53%|█████▎    | 3853/7306 [28:25<25:52,  2.22batch/s]
languagebind videos:  53%|█████▎    | 3854/7306 [28:25<25:51,  2.22batch/s]
languagebind videos:  53%|█████▎    | 3856/7306 [28:26<25:53,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3857/7306 [28:27<25:49,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3859/7306 [28:28<25:46,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3861/7306 [28:28<25:45,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3862/7306 [28:29<25:47,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3864/7306 [28:30<25:43,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3865/7306 [28:30<25:47,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3867/7306 [28:31<26:17,  2.18batch/s]]
languagebind videos:  53%|█████▎    | 3868/7306 [28:32<26:14,  2.18batch/s]]
languagebind videos:  53%|█████▎    | 3870/7306 [28:33<26:23,  2.17batch/s]]
languagebind videos:  53%|█████▎    | 3871/7306 [28:33<26:24,  2.17batch/s]]
languagebind videos:  53%|█████▎    | 3873/7306 [28:34<26:23,  2.17batch/s]]
languagebind videos:  53%|█████▎    | 3874/7306 [28:34<26:10,  2.19batch/s]]
languagebind videos:  53%|█████▎    | 3876/7306 [28:35<25:51,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3878/7306 [28:36<25:43,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3879/7306 [28:37<25:41,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3881/7306 [28:37<25:35,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3882/7306 [28:38<25:33,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3884/7306 [28:39<25:34,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3885/7306 [28:39<25:33,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3887/7306 [28:40<25:35,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3889/7306 [28:41<25:33,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3890/7306 [28:42<25:32,  2.23batch/s]]
languagebind videos:  53%|█████▎    | 3892/7306 [28:42<25:38,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3893/7306 [28:43<25:41,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3895/7306 [28:44<25:42,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3897/7306 [28:45<25:35,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3898/7306 [28:45<25:46,  2.20batch/s]]
languagebind videos:  53%|█████▎    | 3900/7306 [28:46<25:41,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3901/7306 [28:47<25:40,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3903/7306 [28:47<25:36,  2.21batch/s]]
languagebind videos:  53%|█████▎    | 3904/7306 [28:48<25:32,  2.22batch/s]]
languagebind videos:  53%|█████▎    | 3906/7306 [28:49<25:45,  2.20batch/s]]
languagebind videos:  53%|█████▎    | 3908/7306 [28:50<25:35,  2.21batch/s]]
languagebind videos:  54%|█████▎    | 3909/7306 [28:50<25:44,  2.20batch/s]]
languagebind videos:  54%|█████▎    | 3911/7306 [28:51<25:28,  2.22batch/s]]
languagebind videos:  54%|█████▎    | 3912/7306 [28:51<25:23,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3914/7306 [28:52<25:18,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3915/7306 [28:53<25:18,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3917/7306 [28:54<25:26,  2.22batch/s]]
languagebind videos:  54%|█████▎    | 3919/7306 [28:55<25:19,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3920/7306 [28:55<25:19,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3922/7306 [28:56<25:18,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3923/7306 [28:56<25:19,  2.23batch/s]]
languagebind videos:  54%|█████▎    | 3925/7306 [28:57<25:23,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3927/7306 [28:58<25:22,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3928/7306 [28:59<25:21,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3930/7306 [29:00<25:22,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3931/7306 [29:00<25:21,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3933/7306 [29:01<25:22,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3935/7306 [29:02<25:16,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3936/7306 [29:02<25:19,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3938/7306 [29:03<25:10,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3939/7306 [29:04<25:07,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3941/7306 [29:05<25:08,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3943/7306 [29:05<25:08,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3944/7306 [29:06<25:05,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3946/7306 [29:07<25:07,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3947/7306 [29:07<25:07,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3949/7306 [29:08<25:08,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3951/7306 [29:09<25:09,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3952/7306 [29:09<25:12,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3954/7306 [29:10<25:04,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3955/7306 [29:11<25:04,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3957/7306 [29:12<25:11,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3959/7306 [29:13<25:12,  2.21batch/s]]
languagebind videos:  54%|█████▍    | 3960/7306 [29:13<25:12,  2.21batch/s]]
languagebind videos:  54%|█████▍    | 3962/7306 [29:14<25:13,  2.21batch/s]]
languagebind videos:  54%|█████▍    | 3963/7306 [29:14<25:09,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3965/7306 [29:15<25:12,  2.21batch/s]]
languagebind videos:  54%|█████▍    | 3966/7306 [29:16<25:08,  2.21batch/s]]
languagebind videos:  54%|█████▍    | 3968/7306 [29:17<25:01,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3970/7306 [29:18<24:57,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3971/7306 [29:18<25:03,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3973/7306 [29:19<24:56,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3974/7306 [29:19<24:53,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3976/7306 [29:20<24:58,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3978/7306 [29:21<24:52,  2.23batch/s]]
languagebind videos:  54%|█████▍    | 3979/7306 [29:22<24:58,  2.22batch/s]]
languagebind videos:  54%|█████▍    | 3981/7306 [29:23<24:56,  2.22batch/s]]
languagebind videos:  55%|█████▍    | 3982/7306 [29:23<24:51,  2.23batch/s]]
languagebind videos:  55%|█████▍    | 3984/7306 [29:24<24:53,  2.22batch/s]]
languagebind videos:  55%|█████▍    | 3985/7306 [29:24<24:57,  2.22batch/s]]
languagebind videos:  55%|█████▍    | 3987/7306 [29:25<25:56,  2.13batch/s]]
languagebind videos:  55%|█████▍    | 3989/7306 [29:26<25:46,  2.15batch/s]]
languagebind videos:  55%|█████▍    | 3990/7306 [29:27<25:50,  2.14batch/s]]
languagebind videos:  55%|█████▍    | 3992/7306 [29:28<25:43,  2.15batch/s]]
languagebind videos:  55%|█████▍    | 3993/7306 [29:28<25:32,  2.16batch/s]]
languagebind videos:  55%|█████▍    | 3995/7306 [29:29<25:13,  2.19batch/s]]
languagebind videos:  55%|█████▍    | 3997/7306 [29:30<24:56,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 3998/7306 [29:30<25:02,  2.20batch/s]]
languagebind videos:  55%|█████▍    | 4000/7306 [29:31<24:54,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4001/7306 [29:32<24:58,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4003/7306 [29:33<24:54,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4004/7306 [29:33<24:54,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4006/7306 [29:34<24:56,  2.20batch/s]]
languagebind videos:  55%|█████▍    | 4008/7306 [29:35<24:55,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4009/7306 [29:35<24:53,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4011/7306 [29:36<24:56,  2.20batch/s]]
languagebind videos:  55%|█████▍    | 4012/7306 [29:37<24:53,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4014/7306 [29:38<24:52,  2.21batch/s]]
languagebind videos:  55%|█████▍    | 4016/7306 [29:38<24:53,  2.20batch/s]]
languagebind videos:  55%|█████▍    | 4017/7306 [29:39<24:49,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4019/7306 [29:40<24:51,  2.20batch/s]]
languagebind videos:  55%|█████▌    | 4021/7306 [29:41<24:46,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4022/7306 [29:41<24:53,  2.20batch/s]]
languagebind videos:  55%|█████▌    | 4024/7306 [29:42<24:46,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4025/7306 [29:43<24:43,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4027/7306 [29:43<24:42,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4029/7306 [29:44<24:42,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4030/7306 [29:45<24:57,  2.19batch/s]]
languagebind videos:  55%|█████▌    | 4032/7306 [29:46<24:43,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4033/7306 [29:46<24:42,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4035/7306 [29:47<24:39,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4037/7306 [29:48<24:37,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4038/7306 [29:48<24:36,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4040/7306 [29:49<24:35,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4042/7306 [29:50<24:29,  2.22batch/s]]
languagebind videos:  55%|█████▌    | 4043/7306 [29:51<24:35,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4045/7306 [29:52<24:22,  2.23batch/s]]
languagebind videos:  55%|█████▌    | 4046/7306 [29:52<24:23,  2.23batch/s]]
languagebind videos:  55%|█████▌    | 4048/7306 [29:53<24:33,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4050/7306 [29:54<24:30,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4051/7306 [29:54<24:31,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4053/7306 [29:55<24:34,  2.21batch/s]]
languagebind videos:  55%|█████▌    | 4054/7306 [29:56<24:29,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4056/7306 [29:57<24:37,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4058/7306 [29:57<24:35,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4059/7306 [29:58<24:31,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4061/7306 [29:59<24:29,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4063/7306 [30:00<24:30,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4064/7306 [30:00<24:31,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4066/7306 [30:01<24:23,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4067/7306 [30:02<24:21,  2.22batch/s]]
languagebind videos:  56%|█████▌    | 4069/7306 [30:02<24:32,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4071/7306 [30:03<24:33,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4072/7306 [30:04<24:29,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4074/7306 [30:05<24:27,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4076/7306 [30:06<24:11,  2.22batch/s]]
languagebind videos:  56%|█████▌    | 4077/7306 [30:06<24:26,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4079/7306 [30:07<24:17,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4080/7306 [30:07<24:16,  2.21batch/s]]
languagebind videos:  56%|█████▌    | 4082/7306 [30:08<24:30,  2.19batch/s]]
languagebind videos:  56%|█████▌    | 4084/7306 [30:09<24:36,  2.18batch/s]]
languagebind videos:  56%|█████▌    | 4085/7306 [30:10<24:32,  2.19batch/s]]
languagebind videos:  56%|█████▌    | 4087/7306 [30:11<24:26,  2.19batch/s]]
languagebind videos:  56%|█████▌    | 4088/7306 [30:11<24:20,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4090/7306 [30:12<24:33,  2.18batch/s]]
languagebind videos:  56%|█████▌    | 4092/7306 [30:13<24:27,  2.19batch/s]]
languagebind videos:  56%|█████▌    | 4093/7306 [30:13<24:22,  2.20batch/s]]
languagebind videos:  56%|█████▌    | 4095/7306 [30:14<24:32,  2.18batch/s]]
languagebind videos:  56%|█████▌    | 4097/7306 [30:15<24:22,  2.19batch/s]]
languagebind videos:  56%|█████▌    | 4098/7306 [30:16<24:40,  2.17batch/s]]
languagebind videos:  56%|█████▌    | 4100/7306 [30:17<24:59,  2.14batch/s]]
languagebind videos:  56%|█████▌    | 4101/7306 [30:17<24:57,  2.14batch/s]]
languagebind videos:  56%|█████▌    | 4103/7306 [30:18<25:06,  2.13batch/s]]
languagebind videos:  56%|█████▌    | 4104/7306 [30:19<25:07,  2.12batch/s]]
languagebind videos:  56%|█████▌    | 4106/7306 [30:19<24:54,  2.14batch/s]]
languagebind videos:  56%|█████▌    | 4108/7306 [30:20<24:34,  2.17batch/s]]

-- mean: R1 63.50  mAP 74.79  mINP 74.79
-- mean_s8: R1 63.20  mAP 74.74  mINP 74.74
-- max: R1 52.00  mAP 66.13  mINP 66.13
-- query_max: R1 63.40  mAP 74.81  mINP 74.81
== LanguageBind | activitynet/sentence | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos:  29%|██▉       | 2146/7306 [27:12<1:15:13,  1.14batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

languagebind texts:   2%|▏         | 4/227 [00:00<00:06, 33.25batch/s]
languagebind texts:  17%|█▋        | 38/227 [00:00<00:03, 47.45batch/s]tch/s]
languagebind texts:  32%|███▏      | 73/227 [00:01<00:03, 47.29batch/s]tch/s]
languagebind texts:  48%|████▊     | 108/227 [00:02<00:02, 47.75batch/s]ch/s]
languagebind texts:  65%|██████▌   | 148/227 [00:03<00:01, 48.44batch/s]ch/s]
languagebind texts:  81%|████████  | 183/227 [00:03<00:00, 47.08batch/s]ch/s]
languagebind texts:  96%|█████████▌| 218/227 [00:04<00:00, 46.32batch/s]ch/s]
languagebind texts: 100%|██████████| 227/227 [00:04<00:00, 46.26batch/s]ch/s]

internvideo2 videos:  29%|██▉       | 2154/7306 [27:18<1:07:01,  1.28batch/s]
internvideo2 videos:  29%|██▉       | 2155/7306 [27:19<1:11:10,  1.21batch/s]
internvideo2 videos:  30%|██▉       | 2156/7306 [27:20<1:13:18,  1.17batch/s]
internvideo2 videos:  30%|██▉       | 2157/7306 [27:21<1:13:21,  1.17batch/s]
internvideo2 videos:  30%|██▉       | 2158/7306 [27:22<1:14:26,  1.15batch/s]
internvideo2 videos:  30%|██▉       | 2159/7306 [27:23<1:14:07,  1.16batch/s]
internvideo2 videos:  30%|██▉       | 2160/7306 [27:23<1:14:32,  1.15batch/s]
internvideo2 videos:  30%|██▉       | 2161/7306 [27:24<1:14:09,  1.16batch/s]
internvideo2 videos:  30%|██▉       | 2162/7306 [27:25<1:14:01,  1.16batch/s]
internvideo2 videos:  30%|██▉       | 2163/7306 [27:26<1:14:32,  1.15batch/s]
internvideo2 videos:  30%|██▉       | 2164/7306 [27:27<1:13:39,  1.16batch/s]
internvideo2 videos:  30%|██▉       | 2165/7306 [27:28<1:14:24,  1.15batch/s]
internvideo2 videos:  30%|██▉       | 2166/7306 [27:29<1:13:17,  1.17batch/s]
internvideo2 videos:  30%|██▉       | 2167/7306 [27:30<1:19:08,  1.08batch/s]
internvideo2 videos:  30%|██▉       | 2168/7306 [27:31<1:17:50,  1.10batch/s]

-- mean: R1 34.84  mAP 47.36  mINP 47.36
-- mean_s8: R1 34.53  mAP 47.26  mINP 47.26
-- max: R1 28.12  mAP 41.27  mINP 41.27
-- query_max: R1 36.96  mAP 49.82  mINP 49.82

internvideo2 videos:  30%|██▉       | 2169/7306 [27:32<1:25:36,  1.00batch/s]
internvideo2 videos:  30%|██▉       | 2170/7306 [27:33<1:19:13,  1.08batch/s]
internvideo2 videos:  30%|██▉       | 2171/7306 [27:33<1:14:44,  1.15batch/s]
internvideo2 videos:  30%|██▉       | 2172/7306 [27:34<1:11:35,  1.20batch/s]
internvideo2 videos:  30%|██▉       | 2173/7306 [27:35<1:09:31,  1.23batch/s]
internvideo2 videos:  30%|██▉       | 2174/7306 [27:36<1:08:03,  1.26batch/s]
internvideo2 videos:  30%|██▉       | 2175/7306 [27:36<1:06:56,  1.28batch/s]
internvideo2 videos:  30%|██▉       | 2176/7306 [27:37<1:06:06,  1.29batch/s]
internvideo2 videos:  30%|██▉       | 2177/7306 [27:38<1:05:32,  1.30batch/s]
internvideo2 videos:  30%|██▉       | 2178/7306 [27:39<1:05:09,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2179/7306 [27:39<1:04:52,  1.32batch/s]
internvideo2 videos:  30%|██▉       | 2180/7306 [27:40<1:04:40,  1.32batch/s]
internvideo2 videos:  30%|██▉       | 2181/7306 [27:41<1:04:43,  1.32batch/s]
internvideo2 videos:  30%|██▉       | 2182/7306 [27:42<1:04:52,  1.32batch/s]
internvideo2 videos:  30%|██▉       | 2183/7306 [27:42<1:04:54,  1.32batch/s]
internvideo2 videos:  30%|██▉       | 2184/7306 [27:43<1:04:55,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2185/7306 [27:44<1:05:12,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2186/7306 [27:45<1:05:06,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2187/7306 [27:45<1:05:00,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2188/7306 [27:46<1:05:07,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2189/7306 [27:47<1:04:53,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2190/7306 [27:48<1:05:07,  1.31batch/s]
internvideo2 videos:  30%|██▉       | 2191/7306 [27:48<1:05:00,  1.31batch/s]
internvideo2 videos:  30%|███       | 2192/7306 [27:49<1:04:57,  1.31batch/s]
internvideo2 videos:  30%|███       | 2193/7306 [27:50<1:04:54,  1.31batch/s]
internvideo2 videos:  30%|███       | 2194/7306 [27:51<1:04:52,  1.31batch/s]
internvideo2 videos:  30%|███       | 2195/7306 [27:51<1:04:48,  1.31batch/s]
internvideo2 videos:  30%|███       | 2196/7306 [27:52<1:04:49,  1.31batch/s]
internvideo2 videos:  30%|███       | 2197/7306 [27:53<1:05:03,  1.31batch/s]
internvideo2 videos:  30%|███       | 2198/7306 [27:54<1:04:58,  1.31batch/s]
internvideo2 videos:  30%|███       | 2199/7306 [27:55<1:04:52,  1.31batch/s]
internvideo2 videos:  30%|███       | 2200/7306 [27:55<1:04:49,  1.31batch/s]
internvideo2 videos:  30%|███       | 2201/7306 [27:56<1:04:48,  1.31batch/s]
internvideo2 videos:  30%|███       | 2202/7306 [27:57<1:04:46,  1.31batch/s]
internvideo2 videos:  30%|███       | 2203/7306 [27:58<1:04:40,  1.32batch/s]
internvideo2 videos:  30%|███       | 2204/7306 [27:58<1:04:42,  1.31batch/s]
internvideo2 videos:  30%|███       | 2205/7306 [27:59<1:04:38,  1.32batch/s]
internvideo2 videos:  30%|███       | 2206/7306 [28:00<1:04:38,  1.32batch/s]
internvideo2 videos:  30%|███       | 2207/7306 [28:01<1:04:39,  1.31batch/s]
internvideo2 videos:  30%|███       | 2208/7306 [28:01<1:04:37,  1.31batch/s]
internvideo2 videos:  30%|███       | 2209/7306 [28:02<1:04:35,  1.32batch/s]
internvideo2 videos:  30%|███       | 2210/7306 [28:03<1:04:35,  1.31batch/s]
internvideo2 videos:  30%|███       | 2211/7306 [28:04<1:04:32,  1.32batch/s]
internvideo2 videos:  30%|███       | 2212/7306 [28:04<1:04:31,  1.32batch/s]
internvideo2 videos:  30%|███       | 2213/7306 [28:05<1:04:32,  1.32batch/s]
internvideo2 videos:  30%|███       | 2214/7306 [28:06<1:04:31,  1.32batch/s]
internvideo2 videos:  30%|███       | 2215/7306 [28:07<1:04:30,  1.32batch/s]
internvideo2 videos:  30%|███       | 2216/7306 [28:07<1:04:31,  1.31batch/s]
internvideo2 videos:  30%|███       | 2217/7306 [28:08<1:04:29,  1.32batch/s]
internvideo2 videos:  30%|███       | 2218/7306 [28:09<1:04:28,  1.32batch/s]
internvideo2 videos:  30%|███       | 2219/7306 [28:10<1:04:29,  1.31batch/s]
internvideo2 videos:  30%|███       | 2220/7306 [28:11<1:04:29,  1.31batch/s]
internvideo2 videos:  30%|███       | 2221/7306 [28:11<1:04:44,  1.31batch/s]
internvideo2 videos:  30%|███       | 2222/7306 [28:12<1:04:40,  1.31batch/s]
internvideo2 videos:  30%|███       | 2223/7306 [28:13<1:04:36,  1.31batch/s]
internvideo2 videos:  30%|███       | 2224/7306 [28:14<1:04:32,  1.31batch/s]
internvideo2 videos:  30%|███       | 2225/7306 [28:14<1:04:29,  1.31batch/s]
internvideo2 videos:  30%|███       | 2226/7306 [28:15<1:04:25,  1.31batch/s]
internvideo2 videos:  30%|███       | 2227/7306 [28:16<1:04:24,  1.31batch/s]
internvideo2 videos:  30%|███       | 2228/7306 [28:17<1:04:23,  1.31batch/s]
internvideo2 videos:  31%|███       | 2229/7306 [28:17<1:04:17,  1.32batch/s]
internvideo2 videos:  31%|███       | 2230/7306 [28:18<1:04:23,  1.31batch/s]
internvideo2 videos:  31%|███       | 2231/7306 [28:19<1:04:20,  1.31batch/s]
internvideo2 videos:  31%|███       | 2232/7306 [28:20<1:04:20,  1.31batch/s]
internvideo2 videos:  31%|███       | 2233/7306 [28:20<1:04:02,  1.32batch/s]
internvideo2 videos:  31%|███       | 2234/7306 [28:21<1:03:51,  1.32batch/s]
internvideo2 videos:  31%|███       | 2235/7306 [28:22<1:03:42,  1.33batch/s]
internvideo2 videos:  31%|███       | 2236/7306 [28:23<1:03:36,  1.33batch/s]
internvideo2 videos:  31%|███       | 2237/7306 [28:23<1:03:33,  1.33batch/s]
internvideo2 videos:  31%|███       | 2238/7306 [28:24<1:03:30,  1.33batch/s]
internvideo2 videos:  31%|███       | 2239/7306 [28:25<1:03:28,  1.33batch/s]
internvideo2 videos:  31%|███       | 2240/7306 [28:26<1:03:41,  1.33batch/s]
internvideo2 videos:  31%|███       | 2241/7306 [28:26<1:03:36,  1.33batch/s]
internvideo2 videos:  31%|███       | 2242/7306 [28:27<1:03:42,  1.32batch/s]
internvideo2 videos:  31%|███       | 2243/7306 [28:28<1:03:35,  1.33batch/s]
internvideo2 videos:  31%|███       | 2244/7306 [28:29<1:03:31,  1.33batch/s]
internvideo2 videos:  31%|███       | 2245/7306 [28:29<1:03:27,  1.33batch/s]
internvideo2 videos:  31%|███       | 2246/7306 [28:30<1:03:25,  1.33batch/s]
internvideo2 videos:  31%|███       | 2247/7306 [28:31<1:03:38,  1.32batch/s]
internvideo2 videos:  31%|███       | 2248/7306 [28:32<1:03:47,  1.32batch/s]
internvideo2 videos:  31%|███       | 2249/7306 [28:32<1:03:52,  1.32batch/s]
internvideo2 videos:  31%|███       | 2250/7306 [28:33<1:03:43,  1.32batch/s]
internvideo2 videos:  31%|███       | 2251/7306 [28:34<1:03:47,  1.32batch/s]
internvideo2 videos:  31%|███       | 2252/7306 [28:35<1:03:37,  1.32batch/s]
internvideo2 videos:  31%|███       | 2253/7306 [28:35<1:03:30,  1.33batch/s]
internvideo2 videos:  31%|███       | 2254/7306 [28:36<1:03:26,  1.33batch/s]
internvideo2 videos:  31%|███       | 2255/7306 [28:37<1:03:25,  1.33batch/s]
internvideo2 videos:  31%|███       | 2256/7306 [28:38<1:03:21,  1.33batch/s]
internvideo2 videos:  31%|███       | 2257/7306 [28:38<1:03:17,  1.33batch/s]
internvideo2 videos:  31%|███       | 2258/7306 [28:39<1:03:16,  1.33batch/s]
internvideo2 videos:  31%|███       | 2259/7306 [28:40<1:03:14,  1.33batch/s]
internvideo2 videos:  31%|███       | 2260/7306 [28:41<1:03:26,  1.33batch/s]
internvideo2 videos:  31%|███       | 2261/7306 [28:42<1:03:36,  1.32batch/s]
internvideo2 videos:  31%|███       | 2262/7306 [28:42<1:03:30,  1.32batch/s]
internvideo2 videos:  31%|███       | 2263/7306 [28:43<1:03:21,  1.33batch/s]
internvideo2 videos:  31%|███       | 2264/7306 [28:44<1:03:32,  1.32batch/s]
internvideo2 videos:  31%|███       | 2265/7306 [28:45<1:03:25,  1.32batch/s]
internvideo2 videos:  31%|███       | 2266/7306 [28:45<1:03:33,  1.32batch/s]
internvideo2 videos:  31%|███       | 2267/7306 [28:46<1:03:23,  1.32batch/s]
internvideo2 videos:  31%|███       | 2268/7306 [28:47<1:03:19,  1.33batch/s]
internvideo2 videos:  31%|███       | 2269/7306 [28:48<1:03:14,  1.33batch/s]
internvideo2 videos:  31%|███       | 2270/7306 [28:48<1:03:11,  1.33batch/s]
internvideo2 videos:  31%|███       | 2271/7306 [28:49<1:03:07,  1.33batch/s]
internvideo2 videos:  31%|███       | 2272/7306 [28:50<1:03:04,  1.33batch/s]
internvideo2 videos:  31%|███       | 2273/7306 [28:51<1:03:01,  1.33batch/s]
internvideo2 videos:  31%|███       | 2274/7306 [28:51<1:03:29,  1.32batch/s]
internvideo2 videos:  31%|███       | 2275/7306 [28:52<1:03:17,  1.32batch/s]
internvideo2 videos:  31%|███       | 2276/7306 [28:53<1:03:11,  1.33batch/s]
internvideo2 videos:  31%|███       | 2277/7306 [28:54<1:03:05,  1.33batch/s]
internvideo2 videos:  31%|███       | 2278/7306 [28:54<1:02:59,  1.33batch/s]
internvideo2 videos:  31%|███       | 2279/7306 [28:55<1:02:56,  1.33batch/s]
internvideo2 videos:  31%|███       | 2280/7306 [28:56<1:02:46,  1.33batch/s]
internvideo2 videos:  31%|███       | 2281/7306 [28:57<1:02:37,  1.34batch/s]
internvideo2 videos:  31%|███       | 2282/7306 [28:57<1:02:26,  1.34batch/s]
internvideo2 videos:  31%|███       | 2283/7306 [28:58<1:02:34,  1.34batch/s]
internvideo2 videos:  31%|███▏      | 2284/7306 [28:59<1:02:52,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2285/7306 [29:00<1:02:56,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2286/7306 [29:00<1:03:17,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2287/7306 [29:01<1:03:22,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2288/7306 [29:02<1:03:33,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2289/7306 [29:03<1:03:37,  1.31batch/s]
internvideo2 videos:  31%|███▏      | 2290/7306 [29:03<1:03:37,  1.31batch/s]
internvideo2 videos:  31%|███▏      | 2291/7306 [29:04<1:03:21,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2292/7306 [29:05<1:03:09,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2293/7306 [29:06<1:02:59,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2294/7306 [29:06<1:02:55,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2295/7306 [29:07<1:02:51,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2296/7306 [29:08<1:02:49,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2297/7306 [29:09<1:02:45,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2298/7306 [29:09<1:02:58,  1.33batch/s]
internvideo2 videos:  31%|███▏      | 2299/7306 [29:10<1:03:06,  1.32batch/s]
internvideo2 videos:  31%|███▏      | 2300/7306 [29:11<1:03:28,  1.31batch/s]
internvideo2 videos:  31%|███▏      | 2301/7306 [29:12<1:03:27,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2302/7306 [29:12<1:03:24,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2303/7306 [29:13<1:03:24,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2304/7306 [29:14<1:03:24,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2305/7306 [29:15<1:03:23,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2306/7306 [29:15<1:03:23,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2307/7306 [29:16<1:03:21,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2308/7306 [29:17<1:03:21,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2309/7306 [29:18<1:03:03,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2310/7306 [29:19<1:02:53,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2311/7306 [29:19<1:02:46,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2312/7306 [29:20<1:02:38,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2313/7306 [29:21<1:02:35,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2314/7306 [29:22<1:02:40,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2315/7306 [29:22<1:02:41,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2316/7306 [29:23<1:02:51,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2317/7306 [29:24<1:03:10,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2318/7306 [29:25<1:03:12,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2319/7306 [29:25<1:03:11,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2320/7306 [29:26<1:03:11,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2321/7306 [29:27<1:03:11,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2322/7306 [29:28<1:03:10,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2323/7306 [29:28<1:03:08,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2324/7306 [29:29<1:03:09,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2325/7306 [29:30<1:03:07,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2326/7306 [29:31<1:03:18,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2327/7306 [29:31<1:03:17,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2328/7306 [29:32<1:03:12,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2329/7306 [29:33<1:02:56,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2330/7306 [29:34<1:02:57,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2331/7306 [29:34<1:02:59,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2332/7306 [29:35<1:02:45,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2333/7306 [29:36<1:02:50,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2334/7306 [29:37<1:02:55,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2335/7306 [29:37<1:02:42,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2336/7306 [29:38<1:02:46,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2337/7306 [29:39<1:02:51,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2338/7306 [29:40<1:02:54,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2339/7306 [29:41<1:02:57,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2340/7306 [29:41<1:03:31,  1.30batch/s]
internvideo2 videos:  32%|███▏      | 2341/7306 [29:42<1:03:22,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2342/7306 [29:43<1:03:17,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2343/7306 [29:44<1:03:11,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2344/7306 [29:44<1:02:53,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2345/7306 [29:45<1:02:39,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2346/7306 [29:46<1:02:28,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2347/7306 [29:47<1:02:22,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2348/7306 [29:47<1:02:18,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2349/7306 [29:48<1:02:14,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2350/7306 [29:49<1:02:12,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2351/7306 [29:50<1:02:38,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2352/7306 [29:50<1:02:56,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2353/7306 [29:51<1:02:54,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2354/7306 [29:52<1:02:52,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2355/7306 [29:53<1:02:52,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2356/7306 [29:53<1:02:52,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2357/7306 [29:54<1:02:48,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2358/7306 [29:55<1:02:46,  1.31batch/s]
internvideo2 videos:  32%|███▏      | 2359/7306 [29:56<1:02:33,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2360/7306 [29:56<1:02:23,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2361/7306 [29:57<1:02:25,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2362/7306 [29:58<1:02:31,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2363/7306 [29:59<1:02:19,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2364/7306 [29:59<1:02:11,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2365/7306 [30:00<1:02:03,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2366/7306 [30:01<1:02:12,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2367/7306 [30:02<1:02:19,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2368/7306 [30:03<1:02:09,  1.32batch/s]
internvideo2 videos:  32%|███▏      | 2369/7306 [30:03<1:02:01,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2370/7306 [30:04<1:01:55,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2371/7306 [30:05<1:01:50,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2372/7306 [30:06<1:01:48,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2373/7306 [30:06<1:01:59,  1.33batch/s]
internvideo2 videos:  32%|███▏      | 2374/7306 [30:07<1:02:08,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2375/7306 [30:08<1:02:00,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2376/7306 [30:09<1:01:54,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2377/7306 [30:09<1:01:47,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2378/7306 [30:10<1:01:58,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2379/7306 [30:11<1:02:06,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2380/7306 [30:12<1:02:13,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2381/7306 [30:12<1:02:16,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2382/7306 [30:13<1:02:17,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2383/7306 [30:14<1:02:17,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2384/7306 [30:15<1:02:18,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2385/7306 [30:15<1:02:17,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2386/7306 [30:16<1:02:19,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2387/7306 [30:17<1:02:19,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2388/7306 [30:18<1:02:03,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2389/7306 [30:18<1:01:53,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2390/7306 [30:19<1:01:59,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2391/7306 [30:20<1:02:05,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2392/7306 [30:21<1:02:22,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2393/7306 [30:21<1:02:20,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2394/7306 [30:22<1:02:18,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2395/7306 [30:23<1:02:33,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2396/7306 [30:24<1:02:27,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2397/7306 [30:24<1:02:21,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2398/7306 [30:25<1:02:06,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2399/7306 [30:26<1:01:52,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2400/7306 [30:27<1:01:57,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2401/7306 [30:28<1:02:00,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2402/7306 [30:28<1:01:53,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2403/7306 [30:29<1:01:53,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2404/7306 [30:30<1:01:58,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2405/7306 [30:31<1:02:00,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2406/7306 [30:31<1:02:32,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2407/7306 [30:32<1:02:23,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2408/7306 [30:33<1:02:15,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2409/7306 [30:34<1:02:09,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2410/7306 [30:34<1:02:08,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2411/7306 [30:35<1:02:06,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2412/7306 [30:36<1:02:05,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2413/7306 [30:37<1:02:03,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2414/7306 [30:37<1:02:01,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2415/7306 [30:38<1:02:02,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2416/7306 [30:39<1:01:59,  1.31batch/s]
internvideo2 videos:  33%|███▎      | 2417/7306 [30:40<1:01:42,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2418/7306 [30:40<1:01:29,  1.32batch/s]
internvideo2 videos:  33%|███▎      | 2419/7306 [30:41<1:01:24,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2420/7306 [30:42<1:01:18,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2421/7306 [30:43<1:01:10,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2422/7306 [30:43<1:01:05,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2423/7306 [30:44<1:01:02,  1.33batch/s]
internvideo2 videos:  33%|███▎      | 2424/7306 [30:45<1:00:52,  1.34batch/s]

-- mean: R1 69.10  mAP 79.86  mINP 79.86
-- mean_s8: R1 69.40  mAP 80.00  mINP 80.00
-- max: R1 52.10  mAP 65.98  mINP 65.98
-- query_max: R1 67.90  mAP 78.84  mINP 78.84
== InternVideo2 CLIP-S | activitynet/sentence | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

internvideo2 texts: 100%|██████████| 227/227 [00:03<00:00, 74.66batch/s]

-- mean: R1 36.91  mAP 50.24  mINP 50.24
-- mean_s8: R1 36.83  mAP 50.21  mINP 50.21
-- max: R1 28.12  mAP 41.66  mINP 41.66
-- query_max: R1 39.73  mAP 52.87  mINP 52.87
Done

## 5. Tables

Reads ActivityNet results from every results folder it can find: this session's `zero_shot_results/`, plus any attached Kaggle inputs that contain a `zero_shot_results` folder (other groups, earlier runs). Each table is shown here and saved as CSV and Markdown under `zero_shot_results/tables/`.

Accuracy cells use each model's **best Rank-1 setting** per ActivityNet subset (protocol and pool are shown in the settings table). All numbers are percentages except MdR (median rank).

In [7]:
import numpy as np

KEY = ["dataset", "subset", "model", "protocol", "pool"]


def collect_rows():
    roots = [RESULTS_ROOT]
    if Path("/kaggle/input").is_dir():
        roots += [p for p in Path("/kaggle/input").rglob("zero_shot_results") if p.is_dir()]
    rows = []
    for root in dict.fromkeys(roots):
        for path in root.rglob("*.json"):
            try:
                row = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(row, dict) or "Rank-1" not in row:
                continue
            if row.get("status", "complete") != "complete" or row.get("dataset") != "activitynet" or row.get("model") not in MODELS:
                continue
            rows.append(row)
    if not rows:
        return pd.DataFrame(
            columns=KEY + ["Rank-1", "mAP", "mINP", "protocol_type", "gallery_cached", "Model", "Dataset",
                           "video_ms_per_item", "peak_gpu_gb", "total_s"]
        )
    frame = pd.DataFrame(rows)
    if "protocol_type" not in frame:
        frame["protocol_type"] = np.where(frame["pool"] == "none", "single", "window")
    frame["protocol_type"] = frame["protocol_type"].fillna(
        pd.Series(np.where(frame["pool"] == "none", "single", "window"), index=frame.index)
    )
    frame["created_at"] = frame.get("created_at", pd.Series(dtype=str)).fillna("")
    frame["gallery_cached"] = frame.get("gallery_cached", False)
    frame["gallery_cached"] = frame["gallery_cached"].fillna(False).astype(bool)
    frame = frame.sort_values("created_at").drop_duplicates(KEY, keep="last")
    frame["Model"] = frame["model"].map(lambda m: PRETTY.get(m, m))
    frame["Dataset"] = frame["dataset"].map(lambda d: DATASETS.get(d, {}).get("label", d))
    return frame.reset_index(drop=True)


RESULTS = collect_rows()
print(f"{len(RESULTS)} result rows from {RESULTS['model'].nunique() if len(RESULTS) else 0} models", flush=True)
BEST = (
    RESULTS.sort_values(["Rank-1", "mAP"], ascending=False, kind="mergesort")
    .groupby(["dataset", "subset", "model"], as_index=False)
    .head(1)
    .reset_index(drop=True)
)
TABLES = {}


def column_order(dataset):
    return [s for s in DATASETS.get(dataset, {}).get("subsets", []) if s in set(BEST.loc[BEST.dataset == dataset, "subset"])]


def setting_text(row):
    return row["protocol"] if row["pool"] in ("none", None) or pd.isna(row["pool"]) else f"{row['protocol']} / {row['pool']}"

52 result rows from 2 models

### 5.1 Leaderboard per dataset (Rank-1 / mAP / mINP)

In [8]:
for dataset in [d for d in DATASETS if d in set(BEST["dataset"])]:
    part = BEST[BEST.dataset == dataset].copy()
    subsets = column_order(dataset)
    part["cell"] = part.apply(lambda r: f"{r['Rank-1']:.2f} / {r['mAP']:.2f} / {r.get('mINP', np.nan):.2f}", axis=1)
    part["setting"] = part.apply(setting_text, axis=1)
    order = part.groupby("Model")["Rank-1"].mean().sort_values(ascending=False).index
    board = part.pivot(index="Model", columns="subset", values="cell").reindex(index=order, columns=subsets)
    board["mean Rank-1"] = part.groupby("Model")["Rank-1"].mean().reindex(order).round(2)
    settings = part.pivot(index="Model", columns="subset", values="setting").reindex(index=order, columns=subsets)
    label = DATASETS[dataset]["label"]
    TABLES[f"leaderboard_{dataset}"] = board
    TABLES[f"best_setting_{dataset}"] = settings
    display(Markdown(f"#### {label}"))
    display(board)
    display(Markdown(f"Best setting per cell ({label})"))
    display(settings)

#### ActivityNet Captions

subset                           paragraph               sentence  mean Rank-1
Model
InternVideo2 CLIP-S  69.80 / 80.24 / 80.24  39.73 / 52.87 / 52.87        54.76
LanguageBind         64.10 / 75.18 / 75.18  36.96 / 49.82 / 49.82        50.53

Best setting per cell (ActivityNet Captions)

subset                           paragraph                   sentence
Model
InternVideo2 CLIP-S  vt_2fps_n32 / mean_s8  reid_8fps_n64 / query_max
LanguageBind         vt_2fps_n32 / mean_s8  reid_8fps_n64 / query_max

### 5.2 Protocol and pool comparison (top three models, Rank-1)

In [9]:
for dataset in [d for d in DATASETS if DATASETS[d]["protocols"] == "video" and d in set(RESULTS["dataset"])]:
    part = RESULTS[RESULTS.dataset == dataset].copy()
    top = part.groupby("Model")["Rank-1"].max().sort_values(ascending=False).head(3).index
    part = part[part.Model.isin(top)]
    part["pool"] = part["pool"].replace({"none": "-"})
    table = part.pivot_table(index=["Model", "protocol", "pool"], columns="subset", values="Rank-1", aggfunc="max")
    table = table.reindex(columns=column_order(dataset)).round(2)
    table = table.reindex(top, level=0)
    TABLES[f"protocols_{dataset}"] = table
    display(Markdown(f"#### {DATASETS[dataset]['label']}"))
    display(table)

#### ActivityNet Captions

subset                                       paragraph  sentence
Model               protocol      pool
InternVideo2 CLIP-S reid_8fps_n64 max             52.1     28.12
                                  mean            69.1     36.91
                                  mean_s8         69.4     36.83
                                  query_max       67.9     39.73
                    uniform8      -               65.0     33.78
                    vt_1fps_n12   max             65.0     34.78
                                  mean            65.6     34.97
                                  mean_s8         65.6     34.97
                                  query_max       65.5     35.11
                    vt_2fps_n32   max             60.2     32.76
                                  mean            69.1     36.60
                                  mean_s8         69.8     36.22
                                  query_max       67.2     39.01
LanguageBind        reid_8fps_n64 max             52.0     28.12
                                  mean            63.5     34.84
                                  mean_s8         63.2     34.53
                                  query_max       63.4     36.96
                    uniform8      -               59.6     31.68
                    vt_1fps_n12   max             59.7     32.26
                                  mean            60.4     31.90
                                  mean_s8         60.4     31.90
                                  query_max       60.7     32.84
                    vt_2fps_n32   max             59.2     30.83
                                  mean            63.3     33.43
                                  mean_s8         64.1     33.31
                                  query_max       63.3     35.36

### 5.3 ActivityNet Captions: paragraph vs sentence queries

Same gallery, different queries. Paragraph queries describe the whole video and are mostly longer than the 32 to 77 token text window of the CLIP-style encoders (the tail is truncated); sentence queries describe one event of the video.

In [10]:
anet = BEST[BEST.dataset == "activitynet"]
if len(anet):
    gap = anet.pivot(index="Model", columns="subset", values="Rank-1").reindex(columns=["paragraph", "sentence"])
    gap["paragraph - sentence"] = gap["paragraph"] - gap["sentence"]
    gap = gap.sort_values("paragraph", ascending=False).round(2)
    TABLES["activitynet_paragraph_vs_sentence"] = gap
    display(gap)
else:
    print("No ActivityNet rows yet")

subset               paragraph  sentence  paragraph - sentence
Model
InternVideo2 CLIP-S       69.8     39.73                 30.07
LanguageBind              64.1     36.96                 27.14

### 5.4 Speed and GPU (Tesla T4)

In [11]:
if len(RESULTS):
    fresh = RESULTS[~RESULTS["gallery_cached"]]
    single = fresh[fresh["protocol_type"] == "single"]
    windows = fresh[fresh["protocol_type"] == "window"]
    speed = pd.DataFrame(
        {
            "ms / clip (single clip)": single.groupby("Model")["video_ms_per_item"].median(),
            "ms / clip (windows)": windows.groupby("Model")["video_ms_per_item"].median(),
            "peak GPU GB": RESULTS.groupby("Model")["peak_gpu_gb"].max(),
            "total minutes": RESULTS.groupby("Model")["total_s"].sum() / 60.0,
            "rows": RESULTS.groupby("Model").size(),
        }
    )
    speed = speed.sort_values("ms / clip (single clip)").round(2)
    TABLES["speed_gpu"] = speed
    display(speed)

,ms / clip (single clip),ms / clip (windows),peak GPU GB,total minutes,rows
Model,,,,,
LanguageBind,209.93,222.12,1.22,398.73,26
InternVideo2 CLIP-S,379.22,381.57,1.54,650.72,26

### 5.5 Save tables

In [12]:
def markdown_table(frame):
    frame = frame.reset_index() if not isinstance(frame.index, pd.RangeIndex) else frame
    headers = [str(c) for c in frame.columns]

    def cell(value):
        if isinstance(value, float):
            return "-" if np.isnan(value) else f"{value:.2f}"
        return str(value)

    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for _, row in frame.iterrows():
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


TABLE_DIR = RESULTS_ROOT / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)
RESULTS.to_csv(TABLE_DIR / "all_rows.csv", index=False)
DATASET_SUMMARY.to_csv(TABLE_DIR / "datasets.csv", index=False)
report = ["# Zero-shot results", "", "## Datasets", "", markdown_table(DATASET_SUMMARY.drop(columns=["root"]))]
for name, table in TABLES.items():
    table.to_csv(TABLE_DIR / f"{name}.csv")
    report += ["", f"## {name}", "", markdown_table(table)]
(TABLE_DIR / "report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
print("Wrote", sorted(p.name for p in TABLE_DIR.iterdir()), flush=True)

Wrote ['activitynet_paragraph_vs_sentence.csv', 'all_rows.csv', 'best_setting_activitynet.csv', 'datasets.csv', 'leaderboard_activitynet.csv', 'protocols_activitynet.csv', 'report.md', 'speed_gpu.csv']