# Zero-shot text-to-video benchmark on ActivityNet Captions

Frozen image and video language models, scored zero-shot on ActivityNet Captions. Every caption is a query; its only positive is the gallery video it describes.

| Dataset | Gallery | Queries | What the captions describe |
|---|---|---|---|
| **ActivityNet Captions** (`paragraph`) | `val1` videos (random sample of `MAX_VIDEOS`, or all 4,917) | 1 per video: the sentences of the video joined into one paragraph | the whole video (long-form, ~180 s on average) |
| **ActivityNet Captions** (`sentence`) | same gallery | one per annotated event sentence (about 3.6 per video) | one event of the video |

Source: [`friedrichor/ActivityNet_Captions`](https://huggingface.co/datasets/friedrichor/ActivityNet_Captions) (official splits: train 10,009 / val1 4,917 / val2 4,885 videos). `val1` is the usual paragraph-to-video test split. Set `ANET_SPLIT = "val2"` to use the other one.

**How to run**

1. Kaggle GPU T4 x2, Internet on. Add a Kaggle secret named `hugging_face` and attach it to the notebook (used for the dataset download).
2. Pick `ENV_GROUP` in the configuration cell. The groups need different `transformers` versions, so each group is its own Kaggle session:
   - `base`: SigLIP 2, Perception Encoder, IRRA, X-CLIP
   - `extended_modern`: OpenAI CLIP ViT-L/14, Jina CLIP v2, Qwen3-VL-Embedding-2B
   - `extended_gme`: GME-Qwen2-VL-2B
3. Run All. On Kaggle, two workers run models concurrently, one pinned to each T4. Every result row is written as JSON the moment it finishes, so a restarted session skips what is done.
4. To combine groups, save each session's `/kaggle/working/zero_shot_results` as a Kaggle dataset and attach it; the tables section merges every results folder it finds.

**Time and disk.** ActivityNet videos are long, so the sliding-window protocols are expensive. `MAX_VIDEOS` (default 1000, seeded) keeps a session inside the Kaggle time limit; set it to `None` for the full split. The videos live inside a 42 GB split archive on the Hub, which is streamed once and only the selected videos are kept on disk.

## 1. Configuration

In [1]:
from pathlib import Path

ENV_GROUP = "base"  # "base", "extended_modern", or "extended_gme" (one Kaggle session each)

MODEL_GROUPS = {
    "base": ["siglip2", "pe_core_l14", "irra", "xclip"],
    "extended_modern": ["openai_clip_vit_l14", "jina_clip_v2", "qwen3_vl_embed_2b"],
    "extended_gme": ["gme_qwen2_vl_2b"],
}
MODELS = MODEL_GROUPS[ENV_GROUP]

DATASETS = {
    "activitynet": {"label": "ActivityNet Captions", "subsets": ["paragraph", "sentence"], "protocols": "video"},
}
SPLIT = "test"

# ActivityNet Captions: "val1" is the standard paragraph-to-video test split, "val2" is the other one.
ANET_SPLIT = "val1"
MAX_VIDEOS = 1000  # random gallery sample (seeded); None keeps every video of the split
ANET_SEED = 0
DEVICE = "cuda"  # two visible GPUs run one model worker each
BATCH = 4
TEXT_BATCH = 16
POOLS = ("mean", "mean_s8", "max", "query_max")

# 1B-s2 is built for 4-frame clips; every other model uses 8.
NATIVE_FRAMES = {"internvideo2_s2_1b": 4}
MODEL_BATCH = {
    "siglip2": 1,
    "pe_core_l14": 1,
    "irra": 2,
    "internvideo2_s2_1b": 1,
    "internvideo2": 2,
    "languagebind": 2,
    "openai_clip_vit_l14": 4,
    "jina_clip_v2": 1,
    "gme_qwen2_vl_2b": 1,
    "qwen3_vl_embed_2b": 1,
}
MODEL_TEXT_BATCH = {"jina_clip_v2": 8, "gme_qwen2_vl_2b": 8, "qwen3_vl_embed_2b": 1}

SINGLE_PROTOCOLS = [
    {"name": "uniform8", "num_frames": 8, "frame_sample": "uniform", "family": "clip8"},
    {"name": "uniform4", "num_frames": 4, "frame_sample": "uniform", "family": "s2"},
    {"name": "middle4", "num_frames": 4, "frame_sample": "middle", "family": "s2", "video_only": True},
]
WINDOW_PROTOCOLS = [
    {"name": "vt_1fps_n12", "sample_fps": 1.0, "max_frames": 12, "stride": 4},
    {"name": "vt_2fps_n32", "sample_fps": 2.0, "max_frames": 32, "stride": 4},
    {"name": "reid_8fps_n64", "sample_fps": 8.0, "max_frames": 64, "stride": 4},
]

PRETTY = {
    "irra": "IRRA",
    "pe_core_l14": "Perception Encoder L/14",
    "siglip2": "SigLIP 2 So400m",
    "internvideo2": "InternVideo2 CLIP-S",
    "internvideo2_s2_1b": "InternVideo2-1B-s2",
    "languagebind": "LanguageBind",
    "xclip": "X-CLIP",
    "openai_clip_vit_l14": "OpenAI CLIP L/14",
    "jina_clip_v2": "Jina CLIP v2",
    "gme_qwen2_vl_2b": "GME-Qwen2-VL-2B",
    "qwen3_vl_embed_2b": "Qwen3-VL-Embedding-2B",
}

WORK = Path("/kaggle/working") if Path("/kaggle/working").is_dir() else Path("results")
# Videos and frame JPEGs are large and disposable, so they go to /kaggle/temp when it exists;
# only the small result JSONs stay in /kaggle/working.
DATA_ROOT = WORK
if Path("/kaggle/working").is_dir():
    try:
        Path("/kaggle/temp").mkdir(parents=True, exist_ok=True)
        DATA_ROOT = Path("/kaggle/temp")
    except OSError:
        DATA_ROOT = WORK
RESULTS_ROOT = WORK / "zero_shot_results"
RESULTS_DIR = RESULTS_ROOT / ENV_GROUP
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
print("Group", ENV_GROUP, "models", MODELS, flush=True)
print("Dataset ActivityNet Captions", "results", RESULTS_DIR, "data", DATA_ROOT, flush=True)

Group base models ['siglip2', 'pe_core_l14', 'irra', 'xclip']
Dataset ActivityNet Captions results /kaggle/working/zero_shot_results/base data /kaggle/temp

## 2. Setup

Clones the repo (and OpenGVLab/InternVideo when 1B-s2 is in the group), installs the group's dependencies, checks the package version, and loads the Hugging Face token. If `transformers` was already imported with a different version, restart the session and run again.

In [3]:
import os
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version

SHAWAF_URL = "https://github.com/BASSAT-BASSAT/Benchmarking-Video-Image-language-models-for-Tracklet-retrieval-.git"
INTERNVIDEO_URL = "https://github.com/OpenGVLab/InternVideo.git"
EXPECTED = "0.1.18"
TORCH_INDEX = "https://download.pytorch.org/whl/cu126"


def run(cmd, cwd=None):
    print("+", " ".join(map(str, cmd)), flush=True)
    subprocess.check_call([str(part) for part in cmd], cwd=str(cwd) if cwd else None)


def installed(name):
    try:
        return version(name)
    except PackageNotFoundError:
        return None


def sync_repo(url, path):
    if path.exists():
        run(["git", "fetch", "origin"], cwd=path)
        run(["git", "reset", "--hard", "origin/main"], cwd=path)
    else:
        run(["git", "clone", url, str(path)])


NEEDS_INTERNVIDEO = "internvideo2_s2_1b" in MODELS
ON_KAGGLE = Path("/kaggle/working").is_dir()
transformers_before = installed("transformers")
transformers_loaded = "transformers" in sys.modules
torch_before = installed("torch")
torch_loaded = "torch" in sys.modules

if ON_KAGGLE:
    shawaf_dir = Path("/kaggle/working/shawaf-vlm")
    intern_dir = Path("/kaggle/working/InternVideo")
    sync_repo(SHAWAF_URL, shawaf_dir)
    if NEEDS_INTERNVIDEO:
        sync_repo(INTERNVIDEO_URL, intern_dir)
    if ENV_GROUP == "base":
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[all]"])
        run(
            [
                sys.executable, "-m", "pip", "install", "-q",
                "einops", "timm", "av", "imageio", "librosa", "soundfile",
                "pandas", "pyyaml", "scipy", "wandb", "gdown",
            ]
        )
        try:
            run([sys.executable, "-m", "pip", "install", "-q", "decord"])
        except subprocess.CalledProcessError:
            print("decord wheel failed; the 1B-s2 path stubs it and uses PyAV", flush=True)
    else:
        if not (installed("torch") or "").startswith("2.8.0"):
            run([sys.executable, "-m", "pip", "install", "-q", "--index-url", TORCH_INDEX, "torch==2.8.0", "torchvision==0.23.0"])
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[{ENV_GROUP}]", "gdown>=5.2", "pandas"])
else:
    here = Path.cwd().resolve()
    shawaf_dir = here
    for candidate in [here, *here.parents]:
        if (candidate / "shawaf_vlm").is_dir() and (candidate / "pyproject.toml").is_file():
            shawaf_dir = candidate
            break
    intern_dir = shawaf_dir / "InternVideo"
    if NEEDS_INTERNVIDEO and not intern_dir.is_dir():
        run(["git", "clone", INTERNVIDEO_URL, str(intern_dir)], cwd=shawaf_dir)

transformers_after = installed("transformers")
if transformers_loaded and transformers_after != transformers_before:
    raise RuntimeError(
        f"transformers changed from {transformers_before} to {transformers_after} after it was "
        "imported. Restart the session, then Run All again."
    )

torch_after = installed("torch")
print("torch", torch_after, flush=True)
if torch_loaded and torch_after != torch_before:
    raise RuntimeError(
        f"torch changed from {torch_before} to {torch_after} after it was imported. "
        "Restart the session, then Run All again."
    )

if NEEDS_INTERNVIDEO:
    os.environ["INTERNVIDEO_ROOT"] = str(intern_dir)
if str(shawaf_dir) not in sys.path:
    sys.path.insert(0, str(shawaf_dir))
for name in list(sys.modules):
    if name == "shawaf_vlm" or name.startswith("shawaf_vlm."):
        del sys.modules[name]

import shawaf_vlm

print("shawaf_vlm", shawaf_vlm.__version__, shawaf_vlm.__file__, flush=True)
print("transformers", transformers_after, flush=True)
if shawaf_vlm.__version__ != EXPECTED:
    raise RuntimeError(
        f"Expected shawaf_vlm {EXPECTED}, found {shawaf_vlm.__version__}. "
        "Restart the session and run this cell again after origin/main updates."
    )

token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
if not token and ON_KAGGLE:
    try:
        from kaggle_secrets import UserSecretsClient

        token = UserSecretsClient().get_secret("hugging_face")
    except Exception as exc:
        print("No hugging_face secret:", type(exc).__name__, flush=True)
if token:
    os.environ["HF_TOKEN"] = token
    os.environ["HUGGING_FACE_HUB_TOKEN"] = token
    from huggingface_hub import login

    login(token=token, add_to_git_credential=False)
    print("Hugging Face token loaded", flush=True)
elif NEEDS_INTERNVIDEO:
    raise RuntimeError(
        "Hugging Face token missing. InternVideo2-1B-s2 is gated: add a Kaggle secret "
        "named hugging_face and attach it to this notebook."
    )
else:
    print("No Hugging Face token; public datasets and models only", flush=True)

+ git fetch origin
+ git reset --hard origin/main
HEAD is now at d553da9 evaluated initial models on our 3 datasets
+ /usr/bin/python3 -m pip install -q -e /kaggle/working/shawaf-vlm[all]
+ /usr/bin/python3 -m pip install -q einops timm av imageio librosa soundfile pandas pyyaml scipy wandb gdown
+ /usr/bin/python3 -m pip install -q decord
torch 2.11.0+cu128
shawaf_vlm 0.1.18 /kaggle/working/shawaf-vlm/shawaf_vlm/__init__.py
transformers 5.16.1

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face token loaded

## 3. Datasets

ActivityNet Captions ships its videos inside `ActivityNet_Videos.tar.part-000 ... 007` (about 42 GB). The next cell reads the split JSON, draws the gallery (`MAX_VIDEOS` seeded random `ANET_SPLIT` videos), streams the archive parts one after another (the next part downloads while the current one is read, and a finished part is deleted at once), keeps only the selected videos, and writes `metadata/paragraph-test.jsonl` and `metadata/sentence-test.jsonl`. A rerun finds the videos already extracted and downloads nothing.

Both subsets share one gallery, so gallery embeddings are reused between them (rows marked `gallery_cached`).

In [4]:
import io
import json
import os
import random
import shutil
import tarfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd
from huggingface_hub import hf_hub_download
from IPython.display import Markdown, display
from tqdm.auto import tqdm

from shawaf_vlm.data.hub_video import load_hub_video_split

ANET_REPO = "friedrichor/ActivityNet_Captions"
ANET_PARTS = [f"ActivityNet_Videos.tar.part-{i:03d}" for i in range(8)]
ANET_ROOT = DATA_ROOT / "ActivityNet_Captions"
ANET_VIDEOS = ANET_ROOT / "videos"
ANET_META = ANET_ROOT / "metadata"
ANET_PARTS_DIR = ANET_ROOT / "_parts"


class PartStream(io.RawIOBase):
    """Read the split tar as one byte stream, downloading one part ahead and deleting finished parts."""

    def __init__(self, names, dest, token=None):
        self.names = list(names)
        self.dest = Path(dest)
        self.token = token
        self.dest.mkdir(parents=True, exist_ok=True)
        self.pool = ThreadPoolExecutor(max_workers=1)
        self.index = -1
        self.handle = None
        self.current = None
        self.pending = None
        self._schedule(0)

    def _fetch(self, name):
        return Path(
            hf_hub_download(
                repo_id=ANET_REPO,
                filename=name,
                repo_type="dataset",
                token=self.token,
                local_dir=str(self.dest),
            )
        )

    def _schedule(self, index):
        self.pending = self.pool.submit(self._fetch, self.names[index]) if index < len(self.names) else None

    def _open_next(self):
        self.index += 1
        future = self.pending
        if future is None:
            return False
        path = future.result()
        self._schedule(self.index + 1)
        self.current = path
        self.handle = path.open("rb")
        print(f"reading {path.name} ({self.index + 1}/{len(self.names)})", flush=True)
        return True

    def _finish_part(self):
        if self.handle is not None:
            self.handle.close()
            self.handle = None
        if self.current is not None:
            self.current.unlink(missing_ok=True)
            self.current = None

    def readable(self):
        return True

    def readinto(self, buffer):
        while True:
            if self.handle is None and not self._open_next():
                return 0
            count = self.handle.readinto(buffer)
            if count:
                return count
            self._finish_part()

    def close(self):
        if not self.closed:
            self._finish_part()
            if self.pending is not None:
                self.pending.cancel()
            self.pool.shutdown(wait=True)
            shutil.rmtree(self.dest, ignore_errors=True)
        super().close()


def anet_select_rows():
    """Read the split JSON and draw the gallery (seeded, order kept)."""
    path = hf_hub_download(
        repo_id=ANET_REPO,
        filename=f"activitynet_captions_{ANET_SPLIT}.json",
        repo_type="dataset",
        token=os.environ.get("HF_TOKEN"),
    )
    rows = json.loads(Path(path).read_text(encoding="utf-8"))
    seen, unique = set(), []
    for row in rows:
        if row["video_id"] not in seen:
            seen.add(row["video_id"])
            unique.append(row)
    if MAX_VIDEOS is not None and len(unique) > MAX_VIDEOS:
        picked = sorted(random.Random(ANET_SEED).sample(range(len(unique)), MAX_VIDEOS))
        unique = [unique[i] for i in picked]
    return unique


def anet_local_videos():
    if not ANET_VIDEOS.is_dir():
        return {}
    return {p.stem: p for p in ANET_VIDEOS.iterdir() if p.is_file() and p.suffix != ".tmp"}


def anet_extract(video_ids):
    """Stream the split archive once and keep only ``video_ids`` (matched on file stem)."""
    remaining = set(video_ids)
    ANET_VIDEOS.mkdir(parents=True, exist_ok=True)
    stream = PartStream(ANET_PARTS, ANET_PARTS_DIR, token=os.environ.get("HF_TOKEN"))
    bar = tqdm(total=len(remaining), desc="Extract videos", unit="video")
    try:
        reader = io.BufferedReader(stream, buffer_size=8 * 1024 * 1024)
        with tarfile.open(fileobj=reader, mode="r|") as archive:
            for member in archive:
                if not member.isfile():
                    continue
                name = Path(member.name).name
                stem = Path(name).stem
                if stem not in remaining:
                    continue
                target = ANET_VIDEOS / name
                tmp = target.with_name(target.name + ".tmp")
                with archive.extractfile(member) as source, tmp.open("wb") as out:
                    shutil.copyfileobj(source, out, 4 * 1024 * 1024)
                os.replace(tmp, target)
                remaining.discard(stem)
                bar.update(1)
                if not remaining:
                    break
    finally:
        bar.close()
        stream.close()
    if remaining:
        print(f"{len(remaining)} selected videos were not found in the archive", flush=True)


def anet_write_metadata(rows, have):
    ANET_META.mkdir(parents=True, exist_ok=True)
    kept = [row for row in rows if row["video_id"] in have]
    for subset in DATASETS["activitynet"]["subsets"]:
        with (ANET_META / f"{subset}-{SPLIT}.jsonl").open("w", encoding="utf-8") as handle:
            for row in kept:
                if subset == "paragraph":
                    captions = [row["caption"].strip()]
                elif subset == "sentence":
                    captions = [s.strip() for s in row["sentences"] if s and s.strip()]
                else:
                    raise ValueError(f"Unknown ActivityNet subset {subset!r}")
                record = {
                    "video": f"videos/{have[row['video_id']].name}",
                    "video_id": row["video_id"],
                    "captions": captions,
                    "subset": ANET_SPLIT,
                }
                handle.write(json.dumps(record, ensure_ascii=False) + "\n")
    return len(kept)


def prepare_activitynet():
    rows = anet_select_rows()
    have = anet_local_videos()
    missing = [row["video_id"] for row in rows if row["video_id"] not in have]
    print(f"ActivityNet {ANET_SPLIT}: {len(rows)} selected videos, {len(rows) - len(missing)} already on disk", flush=True)
    if missing:
        anet_extract(missing)
        have = anet_local_videos()
    kept = anet_write_metadata(rows, have)
    print(f"Wrote metadata for {kept} videos under {ANET_META}", flush=True)
    return ANET_ROOT


# Hugging Face dataset import for Kaggle: download the selected split JSON and
# stream its video archive directly from the dataset repository.
DATA_ROOTS = {"activitynet": prepare_activitynet()}


def load_split(subset):
    return load_hub_video_split(
        DATA_ROOTS["activitynet"],
        config=subset,
        split=SPLIT,
        source=f"activitynet:{ANET_SPLIT}:{subset}",
        missing=lambda detail: FileNotFoundError(detail),
        name="ActivityNet Captions",
    )


summary = []
for subset in DATASETS["activitynet"]["subsets"]:
    splits = load_split(subset)
    per_id = pd.Series([g.person_id for g in splits.gallery]).value_counts()
    positives = pd.Series([per_id.get(q.person_id, 0) for q in splits.query])
    summary.append(
        {
            "dataset": "ActivityNet Captions",
            "subset": subset,
            "queries": len(splits.query),
            "gallery": len(splits.gallery),
            "identities": int(per_id.size),
            "positives / query": round(float(positives.mean()), 2),
            "root": str(DATA_ROOTS["activitynet"]),
        }
    )
DATASET_SUMMARY = pd.DataFrame(summary)
display(DATASET_SUMMARY)

activitynet_captions_val1.json:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

ActivityNet val1: 1000 selected videos, 0 already on disk

Extract videos:   0%|          | 0/1000 [00:00<?, ?video/s]

ActivityNet_Videos.tar.part-000: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-000: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-000 (1/8)

ActivityNet_Videos.tar.part-001: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-001: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-001 (2/8)

ActivityNet_Videos.tar.part-002: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-002: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-002 (3/8)

ActivityNet_Videos.tar.part-003: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-003: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-003 (4/8)

ActivityNet_Videos.tar.part-004: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-004: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-004 (5/8)

ActivityNet_Videos.tar.part-005: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-005: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-005 (6/8)

ActivityNet_Videos.tar.part-006: reconstructing file:   0%|          |  0.00B / 5.37GB

ActivityNet_Videos.tar.part-006: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-006 (7/8)

ActivityNet_Videos.tar.part-007: reconstructing file:   0%|          |  0.00B / 4.40GB

ActivityNet_Videos.tar.part-007: downloading bytes:           |  0.00B

reading ActivityNet_Videos.tar.part-007 (8/8)
Wrote metadata for 1000 videos under /kaggle/temp/ActivityNet_Captions/metadata

,dataset,subset,queries,gallery,identities,positives / query,root
0,ActivityNet Captions,paragraph,1000,1000,1000,1.0,/kaggle/temp/ActivityNet_Captions
1,ActivityNet Captions,sentence,3617,1000,1000,1.0,/kaggle/temp/ActivityNet_Captions

## 4. Run

Each GPU worker takes the next model, then runs dataset, protocol, and subset in order. Each finished row is saved to `zero_shot_results/<group>/<dataset>/<model>_<subset>_<protocol>_<pool>.json` and skipped on rerun.

The ActivityNet `paragraph` and `sentence` subsets share one gallery, so gallery embeddings are reused between them within a protocol (those rows are marked `gallery_cached`; speed is read from the uncached row).

In [5]:
import torch
print(torch.__file__)
print(hasattr(torch, "device"), torch.__version__)

/usr/local/lib/python3.13/dist-packages/torch/__init__.py
True 2.11.0+cu128

In [6]:
import gc
import json
import traceback
from concurrent.futures import ThreadPoolExecutor
from queue import Empty, Queue
from datetime import datetime, timezone

from shawaf_vlm.eval_loop import evaluate_text_to_tracklet, evaluate_text_to_tracklet_windows
from shawaf_vlm.metrics import format_metrics
from shawaf_vlm.models import build_encoder
from shawaf_vlm.models.runtime import ensure_cuda_healthy

METRIC_KEYS = [
    "Rank-1", "Rank-5", "Rank-10", "Rank-20", "Rank-50",
    "mAP", "MdR", "MnR", "nDCG@10", "mINP",
    "num_valid_queries", "num_gallery", "num_clips",
    "decode_s", "video_s", "text_s", "score_s", "total_s",
    "video_ms_per_item", "peak_gpu_gb", "reserved_gpu_gb",
]


class StopModel(Exception):
    """CUDA OOM: stop this model, keep benchmark settings unchanged."""


class GalleryCache:
    """Reuse the last gallery embedding when the exact same frame lists come back."""

    def __init__(self, encoder):
        self.encoder = encoder
        self._key = None
        self._features = None
        self.last_hit = False

    def encode_videos(self, videos, batch_size=4):
        key = tuple(tuple(str(path) for path in clip) for clip in videos)
        if key == self._key:
            self.last_hit = True
            return self._features
        self.last_hit = False
        self._features = self.encoder.encode_videos(videos, batch_size=batch_size)
        self._key = key
        return self._features

    def encode_texts(self, texts, batch_size=32):
        return self.encoder.encode_texts(texts, batch_size=batch_size)

    def __getattr__(self, name):
        return getattr(self.encoder, name)


def family(model):
    return "s2" if model in NATIVE_FRAMES else "clip8"


def protocols_for(model):
    kind = "video"
    specs = []
    for spec in SINGLE_PROTOCOLS:
        if spec["family"] != family(model):
            continue
        if kind == "image" and spec.get("video_only"):
            continue
        specs.append({**spec, "type": "single"})
    if kind == "video":
        specs.extend({**spec, "type": "window"} for spec in WINDOW_PROTOCOLS)
    return specs


def sampling_text(model, spec):
    if spec["type"] == "single":
        return f"{spec['frame_sample']} {spec['num_frames']} frames"
    return (
        f"sliding windows of {NATIVE_FRAMES.get(model, 8)}, stride {spec['stride']}, "
        f"{spec['sample_fps']:g} fps, cap {spec['max_frames']} frames"
    )


def result_path(dataset, model, subset, protocol, pool):
    return RESULTS_DIR / dataset / f"{model}_{subset}_{protocol}_{pool}.json"


def expected_paths(dataset, model, subset, spec):
    pools = ["none"] if spec["type"] == "single" else list(POOLS)
    return [result_path(dataset, model, subset, spec["name"], pool) for pool in pools]


def is_complete(path):
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("status") == "complete"
    except Exception:
        return False


def save_row(dataset, model, subset, spec, pool, metrics=None, error=None, cached=False):
    row = {
        "group": ENV_GROUP,
        "dataset": dataset,
        "subset": subset,
        "model": model,
        "protocol": spec["name"],
        "protocol_type": spec["type"],
        "pool": pool,
        "sampling": sampling_text(model, spec),
        "gallery_cached": bool(cached),
        "status": "failed" if error else "complete",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    if metrics is not None:
        row.update({key: float(metrics[key]) for key in METRIC_KEYS if key in metrics})
    if error is not None:
        row["error"] = str(error)[:2000]
    path = result_path(dataset, model, subset, spec["name"], pool)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(row, indent=2), encoding="utf-8")


def clean_cuda():
    gc.collect()
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def run_one(encoder, model, dataset, subset, spec, gpu_index):
    paths = expected_paths(dataset, model, subset, spec)
    if all(is_complete(path) for path in paths):
        print(f"skip {model} {dataset}/{subset} {spec['name']}", flush=True)
        return
    splits = load_split(subset)
    cache = DATA_ROOT / "frame_cache" / f"gpu{gpu_index}" / dataset
    batch = MODEL_BATCH.get(model, BATCH)
    text_batch = MODEL_TEXT_BATCH.get(model, TEXT_BATCH)
    print(f"== {PRETTY.get(model, model)} | {dataset}/{subset} | {spec['name']} ({sampling_text(model, spec)})", flush=True)
    try:
        if spec["type"] == "single":
            scored = {
                "none": evaluate_text_to_tracklet(
                    encoder,
                    splits,
                    num_frames=spec["num_frames"],
                    batch_size=batch,
                    text_batch_size=text_batch,
                    junk_same_camera=False,
                    frame_cache=cache,
                    frame_sample=spec["frame_sample"],
                )
            }
        else:
            scored = evaluate_text_to_tracklet_windows(
                encoder,
                splits,
                num_frames=NATIVE_FRAMES.get(model, 8),
                stride=spec["stride"],
                sample_fps=spec["sample_fps"],
                max_frames=spec["max_frames"],
                pools=POOLS,
                batch_size=batch,
                text_batch_size=text_batch,
                junk_same_camera=False,
                frame_cache=cache,
            )
    except RuntimeError as exc:
        pools = ["none"] if spec["type"] == "single" else list(POOLS)
        for pool in pools:
            save_row(dataset, model, subset, spec, pool, error=exc)
        if "out of memory" in str(exc).lower():
            raise StopModel(str(exc)) from exc
        raise
    for pool, metrics in scored.items():
        save_row(dataset, model, subset, spec, pool, metrics=metrics, cached=encoder.last_hit)
        print(f"-- {pool}: R1 {metrics['Rank-1']:.2f}  mAP {metrics['mAP']:.2f}  mINP {metrics.get('mINP', float('nan')):.2f}", flush=True)

In [ ]:
if not torch.cuda.is_available():
    raise RuntimeError("A CUDA GPU is required for this benchmark")
if ON_KAGGLE and torch.cuda.device_count() < 2:
    raise RuntimeError("Select Kaggle GPU T4 x2; this notebook needs two visible GPUs")
GPU_COUNT = min(2, torch.cuda.device_count())
print(f"Using {GPU_COUNT} GPU worker(s): " + ", ".join(torch.cuda.get_device_name(i) for i in range(GPU_COUNT)), flush=True)
model_queue = Queue()
for model in MODELS:
    model_queue.put(model)


def run_gpu_worker(gpu_index):
    torch.cuda.set_device(gpu_index)
    device = f"cuda:{gpu_index}"
    ensure_cuda_healthy(device)
    while True:
        try:
            model = model_queue.get_nowait()
        except Empty:
            return
        jobs = [
            (dataset, spec, subset)
            for dataset in ("activitynet",)
            for spec in protocols_for(model)
            for subset in DATASETS["activitynet"]["subsets"]
        ]
        todo = [job for job in jobs if not all(is_complete(p) for p in expected_paths(job[0], model, job[2], job[1]))]
        print(f"\n######## GPU {gpu_index} | {PRETTY.get(model, model)}: {len(todo)} of {len(jobs)} runs to do", flush=True)
        if not todo:
            continue
        try:
            encoder = GalleryCache(build_encoder(model, device=device))
        except Exception:
            traceback.print_exc()
            print(f"Could not build {model} on GPU {gpu_index}; skipping it", flush=True)
            clean_cuda()
            continue
        try:
            for dataset, spec, subset in todo:
                run_one(encoder, model, dataset, subset, spec, gpu_index)
        except StopModel as exc:
            print(f"CUDA OOM on {model} (GPU {gpu_index}); stopping this model: {exc}", flush=True)
        finally:
            del encoder
            clean_cuda()


with ThreadPoolExecutor(max_workers=GPU_COUNT) as workers:
    futures = [workers.submit(run_gpu_worker, i) for i in range(GPU_COUNT)]
    for future in futures:
        future.result()  # propagate worker failures to the notebook

print("Done", flush=True)

Using 2 GPU worker(s): Tesla T4, Tesla T4

######## GPU 0 | SigLIP 2 So400m: 8 of 8 runs to do

######## GPU 1 | Perception Encoder L/14: 8 of 8 runs to do

preprocessor_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/559 [00:00<?, ?B/s]

[transformers] Model config: bos_token_id must be `None` or an integer within the vocabulary (between 0 and 31999), got 49406. This may result in unexpected behavior.
[transformers] Model config: eos_token_id must be `None` or an integer within the vocabulary (between 0 and 31999), got 49407. This may result in unexpected behavior.

tokenizer_config.json:   0%|          | 0.00/47.2k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 34.4MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 4.54GB

model.safetensors: downloading bytes:           |  0.00B

open_clip_config.json:   0%|          | 0.00/601 [00:00<?, ?B/s]

open_clip_model.safetensors: reconstructing file:   0%|          |  0.00B / 2.68GB

open_clip_model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/888 [00:00<?, ?it/s]

Model device: cuda:0 dtype=torch.float16 requested=cuda:0 (Tesla T4)
== SigLIP 2 So400m | activitynet/paragraph | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

Model device: cuda:1 dtype=torch.float16 requested=cuda:1 (Tesla T4)
== Perception Encoder L/14 | activitynet/paragraph | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:   2%|▏         | 20/1000 [00:09<06:37,  2.46batch/s]
siglip2 videos:   2%|▏         | 21/1000 [00:10<06:53,  2.37batch/s]
siglip2 videos:   2%|▏         | 22/1000 [00:10<07:04,  2.31batch/s]/s]
pe_core_l14 videos:   0%|          | 2/1000 [00:00<05:39,  2.94batch/s]
siglip2 videos:   2%|▏         | 23/1000 [00:11<06:55,  2.35batch/s]/s]
siglip2 videos:   2%|▏         | 24/1000 [00:11<06:48,  2.39batch/s]/s]
siglip2 videos:   2%|▎         | 25/1000 [00:12<06:43,  2.41batch/s]/s]
siglip2 videos:   3%|▎         | 26/1000 [00:12<06:40,  2.43batch/s]/s]
siglip2 videos:   3%|▎         | 27/1000 [00:12<06:54,  2.34batch/s]/s]
siglip2 videos:   3%|▎         | 28/1000 [00:13<07:03,  2.30batch/s]/s]
pe_core_l14 videos:   1%|          | 9/1000 [00:03<05:23,  3.06batch/s]
siglip2 videos:   3%|▎         | 29/1000 [00:13<06:54,  2.34batch/s]h/s]
siglip2 videos:   3%|▎         | 30/1000 [00:14<06:49,  2.37batch/s]h/s]
siglip2 videos:   3%|▎         | 31/1000 [00:14<06:45,  2.39batch/s]h/s]
siglip2 videos:   3%|▎         | 32/1000 [00:15<06:42,  2.40batch/s]h/s]
siglip2 videos:   3%|▎         | 33/1000 [00:15<06:39,  2.42batch/s]h/s]
siglip2 videos:   3%|▎         | 34/1000 [00:15<06:38,  2.43batch/s]h/s]
siglip2 videos:   4%|▎         | 35/1000 [00:16<06:36,  2.43batch/s]h/s]
siglip2 videos:   4%|▎         | 36/1000 [00:16<06:37,  2.43batch/s]h/s]
siglip2 videos:   4%|▎         | 37/1000 [00:17<06:37,  2.42batch/s]h/s]
siglip2 videos:   4%|▍         | 38/1000 [00:17<06:38,  2.41batch/s]h/s]
siglip2 videos:   4%|▍         | 39/1000 [00:17<06:52,  2.33batch/s]h/s]
pe_core_l14 videos:   2%|▏         | 21/1000 [00:07<05:23,  3.02batch/s]
siglip2 videos:   4%|▍         | 40/1000 [00:18<06:44,  2.37batch/s]h/s]
siglip2 videos:   4%|▍         | 41/1000 [00:18<06:42,  2.38batch/s]h/s]
siglip2 videos:   4%|▍         | 42/1000 [00:19<06:52,  2.32batch/s]h/s]
siglip2 videos:   4%|▍         | 43/1000 [00:19<07:05,  2.25batch/s]h/s]
pe_core_l14 videos:   3%|▎         | 26/1000 [00:09<05:18,  3.06batch/s]
siglip2 videos:   4%|▍         | 44/1000 [00:20<06:55,  2.30batch/s]h/s]
siglip2 videos:   4%|▍         | 45/1000 [00:20<06:49,  2.33batch/s]h/s]
siglip2 videos:   5%|▍         | 46/1000 [00:20<06:44,  2.36batch/s]h/s]
siglip2 videos:   5%|▍         | 47/1000 [00:21<06:41,  2.37batch/s]h/s]
siglip2 videos:   5%|▍         | 48/1000 [00:21<06:38,  2.39batch/s]h/s]
siglip2 videos:   5%|▍         | 49/1000 [00:22<06:36,  2.40batch/s]h/s]
siglip2 videos:   5%|▌         | 50/1000 [00:22<06:35,  2.40batch/s]h/s]
siglip2 videos:   5%|▌         | 51/1000 [00:23<06:33,  2.41batch/s]h/s]
siglip2 videos:   5%|▌         | 52/1000 [00:23<06:32,  2.42batch/s]h/s]
siglip2 videos:   5%|▌         | 53/1000 [00:23<06:31,  2.42batch/s]h/s]
siglip2 videos:   5%|▌         | 54/1000 [00:24<06:50,  2.30batch/s]h/s]
siglip2 videos:   6%|▌         | 55/1000 [00:24<06:58,  2.26batch/s]h/s]
pe_core_l14 videos:   4%|▍         | 39/1000 [00:14<05:26,  2.94batch/s]
siglip2 videos:   6%|▌         | 56/1000 [00:25<06:50,  2.30batch/s]h/s]
siglip2 videos:   6%|▌         | 57/1000 [00:25<06:44,  2.33batch/s]h/s]
siglip2 videos:   6%|▌         | 58/1000 [00:26<06:41,  2.35batch/s]h/s]
siglip2 videos:   6%|▌         | 59/1000 [00:26<06:38,  2.36batch/s]h/s]
siglip2 videos:   6%|▌         | 60/1000 [00:26<06:35,  2.38batch/s]h/s]
siglip2 videos:   6%|▌         | 61/1000 [00:27<06:35,  2.38batch/s]h/s]
siglip2 videos:   6%|▌         | 62/1000 [00:27<06:31,  2.39batch/s]h/s]
siglip2 videos:   6%|▋         | 63/1000 [00:28<06:33,  2.38batch/s]h/s]
siglip2 videos:   6%|▋         | 64/1000 [00:28<06:32,  2.38batch/s]h/s]
siglip2 videos:   6%|▋         | 65/1000 [00:28<06:31,  2.39batch/s]h/s]
siglip2 videos:   7%|▋         | 66/1000 [00:29<06:33,  2.38batch/s]h/s]
siglip2 videos:   7%|▋         | 67/1000 [00:29<06:32,  2.38batch/s]h/s]
siglip2 videos:   7%|▋         | 68/1000 [00:30<06:32,  2.37batch/s]h/s]
siglip2 videos:   7%|▋         | 69/1000 [00:30<06:32,  2.37batch/s]h/s]
siglip2 videos:   7%|▋         | 70/1000 [00:31<06:32,  2.37batch/s]h/s]
siglip2 videos:   7%|▋         | 71/1000 [00:31<06:30,  2.38batch/s]h/s]
siglip2 videos:   7%|▋         | 72/1000 [00:31<06:31,  2.37batch/s]h/s]
siglip2 videos:   7%|▋         | 73/1000 [00:32<06:53,  2.24batch/s]h/s]
pe_core_l14 videos:   6%|▌         | 58/1000 [00:22<05:16,  2.98batch/s]
siglip2 videos:   7%|▋         | 74/1000 [00:32<06:46,  2.28batch/s]h/s]
siglip2 videos:   8%|▊         | 75/1000 [00:33<06:40,  2.31batch/s]h/s]
siglip2 videos:   8%|▊         | 76/1000 [00:33<06:36,  2.33batch/s]h/s]
siglip2 videos:   8%|▊         | 77/1000 [00:34<06:52,  2.24batch/s]h/s]
siglip2 videos:   8%|▊         | 78/1000 [00:34<06:57,  2.21batch/s]h/s]
pe_core_l14 videos:   6%|▋         | 64/1000 [00:24<05:13,  2.98batch/s]
siglip2 videos:   8%|▊         | 79/1000 [00:35<06:49,  2.25batch/s]h/s]
siglip2 videos:   8%|▊         | 80/1000 [00:35<06:44,  2.28batch/s]h/s]
siglip2 videos:   8%|▊         | 81/1000 [00:35<06:42,  2.29batch/s]h/s]
siglip2 videos:   8%|▊         | 82/1000 [00:36<06:50,  2.23batch/s]h/s]
pe_core_l14 videos:   7%|▋         | 69/1000 [00:26<04:56,  3.14batch/s]
siglip2 videos:   8%|▊         | 83/1000 [00:36<06:43,  2.27batch/s]h/s]
siglip2 videos:   8%|▊         | 84/1000 [00:37<06:42,  2.28batch/s]h/s]
siglip2 videos:   8%|▊         | 85/1000 [00:37<06:42,  2.28batch/s]h/s]
siglip2 videos:   9%|▊         | 86/1000 [00:38<06:48,  2.24batch/s]h/s]
pe_core_l14 videos:   7%|▋         | 74/1000 [00:28<04:58,  3.10batch/s]
siglip2 videos:   9%|▊         | 87/1000 [00:38<06:43,  2.26batch/s]h/s]
siglip2 videos:   9%|▉         | 88/1000 [00:39<06:44,  2.26batch/s]h/s]
siglip2 videos:   9%|▉         | 89/1000 [00:39<06:53,  2.20batch/s]h/s]
pe_core_l14 videos:   8%|▊         | 78/1000 [00:29<04:49,  3.18batch/s]
siglip2 videos:   9%|▉         | 90/1000 [00:39<06:49,  2.22batch/s]h/s]
siglip2 videos:   9%|▉         | 91/1000 [00:40<06:43,  2.25batch/s]h/s]
siglip2 videos:   9%|▉         | 92/1000 [00:40<06:39,  2.27batch/s]h/s]
siglip2 videos:   9%|▉         | 93/1000 [00:41<06:39,  2.27batch/s]h/s]
siglip2 videos:   9%|▉         | 94/1000 [00:41<06:44,  2.24batch/s]h/s]
siglip2 videos:  10%|▉         | 95/1000 [00:42<06:49,  2.21batch/s]h/s]
pe_core_l14 videos:   8%|▊         | 85/1000 [00:32<05:07,  2.98batch/s]
siglip2 videos:  10%|▉         | 96/1000 [00:42<06:43,  2.24batch/s]h/s]
siglip2 videos:  10%|▉         | 97/1000 [00:43<06:43,  2.24batch/s]h/s]
siglip2 videos:  10%|▉         | 98/1000 [00:43<06:53,  2.18batch/s]h/s]
pe_core_l14 videos:   9%|▉         | 89/1000 [00:33<04:51,  3.13batch/s]
siglip2 videos:  10%|▉         | 99/1000 [00:44<06:54,  2.18batch/s]h/s]
siglip2 videos:  10%|█         | 100/1000 [00:44<06:57,  2.15batch/s]/s]
pe_core_l14 videos:   9%|▉         | 92/1000 [00:34<04:35,  3.30batch/s]
siglip2 videos:  10%|█         | 101/1000 [00:44<06:49,  2.20batch/s]/s]
siglip2 videos:  10%|█         | 102/1000 [00:45<06:45,  2.21batch/s]/s]
siglip2 videos:  10%|█         | 103/1000 [00:45<06:48,  2.19batch/s]/s]
siglip2 videos:  10%|█         | 104/1000 [00:46<06:52,  2.17batch/s]/s]
pe_core_l14 videos:  10%|▉         | 97/1000 [00:36<04:54,  3.07batch/s]
siglip2 videos:  10%|█         | 105/1000 [00:46<06:45,  2.20batch/s]/s]
siglip2 videos:  11%|█         | 106/1000 [00:47<06:40,  2.23batch/s]/s]
siglip2 videos:  11%|█         | 107/1000 [00:47<06:55,  2.15batch/s]h/s]
pe_core_l14 videos:  10%|█         | 101/1000 [00:37<04:44,  3.15batch/s]
siglip2 videos:  11%|█         | 108/1000 [00:48<06:50,  2.17batch/s]h/s]
siglip2 videos:  11%|█         | 109/1000 [00:48<06:56,  2.14batch/s]h/s]
siglip2 videos:  11%|█         | 110/1000 [00:49<06:58,  2.13batch/s]h/s]
pe_core_l14 videos:  10%|█         | 105/1000 [00:38<04:50,  3.08batch/s]
siglip2 videos:  11%|█         | 111/1000 [00:49<06:53,  2.15batch/s]h/s]
siglip2 videos:  11%|█         | 112/1000 [00:50<07:02,  2.10batch/s]h/s]
pe_core_l14 videos:  11%|█         | 108/1000 [00:39<04:33,  3.26batch/s]
siglip2 videos:  11%|█▏        | 113/1000 [00:50<06:52,  2.15batch/s]h/s]
siglip2 videos:  11%|█▏        | 114/1000 [00:50<06:47,  2.17batch/s]h/s]
siglip2 videos:  12%|█▏        | 115/1000 [00:51<06:55,  2.13batch/s]h/s]
pe_core_l14 videos:  11%|█         | 112/1000 [00:41<04:36,  3.21batch/s]
siglip2 videos:  12%|█▏        | 116/1000 [00:51<06:47,  2.17batch/s]h/s]
siglip2 videos:  12%|█▏        | 117/1000 [00:52<07:05,  2.07batch/s]h/s]
pe_core_l14 videos:  12%|█▏        | 115/1000 [00:42<04:32,  3.25batch/s]
siglip2 videos:  12%|█▏        | 118/1000 [00:52<06:55,  2.12batch/s]h/s]
siglip2 videos:  12%|█▏        | 119/1000 [00:53<06:49,  2.15batch/s]h/s]
siglip2 videos:  12%|█▏        | 120/1000 [00:53<06:55,  2.12batch/s]h/s]
pe_core_l14 videos:  12%|█▏        | 119/1000 [00:43<04:36,  3.18batch/s]
siglip2 videos:  12%|█▏        | 121/1000 [00:54<06:45,  2.17batch/s]h/s]
siglip2 videos:  12%|█▏        | 122/1000 [00:54<06:42,  2.18batch/s]h/s]
siglip2 videos:  12%|█▏        | 123/1000 [00:55<06:47,  2.15batch/s]h/s]
pe_core_l14 videos:  12%|█▏        | 123/1000 [00:45<04:34,  3.19batch/s]
siglip2 videos:  12%|█▏        | 124/1000 [00:55<06:45,  2.16batch/s]h/s]
siglip2 videos:  12%|█▎        | 125/1000 [00:56<06:50,  2.13batch/s]h/s]
pe_core_l14 videos:  13%|█▎        | 126/1000 [00:45<04:24,  3.31batch/s]
siglip2 videos:  13%|█▎        | 126/1000 [00:56<06:42,  2.17batch/s]h/s]
siglip2 videos:  13%|█▎        | 127/1000 [00:56<06:38,  2.19batch/s]h/s]
siglip2 videos:  13%|█▎        | 128/1000 [00:57<06:35,  2.21batch/s]h/s]
siglip2 videos:  13%|█▎        | 129/1000 [00:57<06:30,  2.23batch/s]h/s]
siglip2 videos:  13%|█▎        | 130/1000 [00:58<06:29,  2.24batch/s]h/s]
siglip2 videos:  13%|█▎        | 131/1000 [00:58<06:32,  2.22batch/s]h/s]
siglip2 videos:  13%|█▎        | 132/1000 [00:59<06:42,  2.16batch/s]h/s]
pe_core_l14 videos:  13%|█▎        | 134/1000 [00:49<04:55,  2.93batch/s]
siglip2 videos:  13%|█▎        | 133/1000 [00:59<06:44,  2.14batch/s]h/s]
siglip2 videos:  13%|█▎        | 134/1000 [01:00<06:48,  2.12batch/s]h/s]
pe_core_l14 videos:  14%|█▎        | 137/1000 [00:50<04:32,  3.16batch/s]
siglip2 videos:  14%|█▎        | 135/1000 [01:00<06:42,  2.15batch/s]h/s]
siglip2 videos:  14%|█▎        | 136/1000 [01:01<06:38,  2.17batch/s]h/s]
siglip2 videos:  14%|█▎        | 137/1000 [01:01<06:35,  2.18batch/s]h/s]
siglip2 videos:  14%|█▍        | 138/1000 [01:02<06:32,  2.19batch/s]h/s]
siglip2 videos:  14%|█▍        | 139/1000 [01:02<06:42,  2.14batch/s]h/s]
pe_core_l14 videos:  14%|█▍        | 143/1000 [00:52<04:45,  3.00batch/s]
siglip2 videos:  14%|█▍        | 140/1000 [01:02<06:39,  2.15batch/s]h/s]
siglip2 videos:  14%|█▍        | 141/1000 [01:03<06:45,  2.12batch/s]h/s]
siglip2 videos:  14%|█▍        | 142/1000 [01:03<06:49,  2.10batch/s]h/s]
pe_core_l14 videos:  15%|█▍        | 147/1000 [00:53<04:41,  3.03batch/s]
siglip2 videos:  14%|█▍        | 143/1000 [01:04<06:43,  2.12batch/s]h/s]
siglip2 videos:  14%|█▍        | 144/1000 [01:04<06:38,  2.15batch/s]h/s]
siglip2 videos:  14%|█▍        | 145/1000 [01:05<06:47,  2.10batch/s]h/s]
siglip2 videos:  15%|█▍        | 146/1000 [01:05<06:51,  2.08batch/s]h/s]
pe_core_l14 videos:  15%|█▌        | 152/1000 [00:55<04:52,  2.90batch/s]
siglip2 videos:  15%|█▍        | 147/1000 [01:06<06:43,  2.11batch/s]h/s]
siglip2 videos:  15%|█▍        | 148/1000 [01:06<06:38,  2.14batch/s]h/s]
siglip2 videos:  15%|█▍        | 149/1000 [01:07<06:35,  2.15batch/s]h/s]
siglip2 videos:  15%|█▌        | 150/1000 [01:07<06:33,  2.16batch/s]h/s]
siglip2 videos:  15%|█▌        | 151/1000 [01:08<06:31,  2.17batch/s]h/s]
siglip2 videos:  15%|█▌        | 152/1000 [01:08<06:32,  2.16batch/s]h/s]
siglip2 videos:  15%|█▌        | 153/1000 [01:09<06:31,  2.16batch/s]h/s]
siglip2 videos:  15%|█▌        | 154/1000 [01:09<06:31,  2.16batch/s]h/s]
siglip2 videos:  16%|█▌        | 155/1000 [01:10<06:45,  2.08batch/s]h/s]
pe_core_l14 videos:  16%|█▌        | 162/1000 [00:59<05:00,  2.79batch/s]
siglip2 videos:  16%|█▌        | 156/1000 [01:10<06:41,  2.10batch/s]h/s]
siglip2 videos:  16%|█▌        | 157/1000 [01:10<06:38,  2.12batch/s]h/s]
siglip2 videos:  16%|█▌        | 158/1000 [01:11<06:34,  2.13batch/s]h/s]
siglip2 videos:  16%|█▌        | 159/1000 [01:11<06:48,  2.06batch/s]h/s]
siglip2 videos:  16%|█▌        | 160/1000 [01:12<06:54,  2.03batch/s]h/s]
pe_core_l14 videos:  17%|█▋        | 168/1000 [01:02<05:01,  2.76batch/s]
siglip2 videos:  16%|█▌        | 161/1000 [01:12<06:48,  2.05batch/s]h/s]
siglip2 videos:  16%|█▌        | 162/1000 [01:13<07:01,  1.99batch/s]h/s]
siglip2 videos:  16%|█▋        | 163/1000 [01:14<07:02,  1.98batch/s]h/s]
pe_core_l14 videos:  17%|█▋        | 172/1000 [01:03<04:53,  2.82batch/s]
siglip2 videos:  16%|█▋        | 164/1000 [01:14<07:13,  1.93batch/s]h/s]
pe_core_l14 videos:  17%|█▋        | 174/1000 [01:04<04:18,  3.20batch/s]
siglip2 videos:  16%|█▋        | 165/1000 [01:15<07:00,  1.98batch/s]h/s]
siglip2 videos:  17%|█▋        | 166/1000 [01:15<07:00,  1.99batch/s]h/s]
pe_core_l14 videos:  18%|█▊        | 177/1000 [01:05<04:12,  3.25batch/s]
siglip2 videos:  17%|█▋        | 167/1000 [01:16<06:52,  2.02batch/s]h/s]
siglip2 videos:  17%|█▋        | 168/1000 [01:16<06:50,  2.03batch/s]h/s]
siglip2 videos:  17%|█▋        | 169/1000 [01:16<06:51,  2.02batch/s]h/s]
pe_core_l14 videos:  18%|█▊        | 181/1000 [01:06<04:27,  3.06batch/s]
siglip2 videos:  17%|█▋        | 170/1000 [01:17<06:46,  2.04batch/s]h/s]
siglip2 videos:  17%|█▋        | 171/1000 [01:17<06:37,  2.09batch/s]h/s]
siglip2 videos:  17%|█▋        | 172/1000 [01:18<06:36,  2.09batch/s]h/s]
siglip2 videos:  17%|█▋        | 173/1000 [01:18<06:48,  2.02batch/s]h/s]
pe_core_l14 videos:  19%|█▊        | 186/1000 [01:08<04:38,  2.92batch/s]
siglip2 videos:  17%|█▋        | 174/1000 [01:19<06:45,  2.04batch/s]h/s]
siglip2 videos:  18%|█▊        | 175/1000 [01:19<06:51,  2.01batch/s]h/s]
pe_core_l14 videos:  19%|█▉        | 189/1000 [01:09<04:22,  3.09batch/s]
siglip2 videos:  18%|█▊        | 176/1000 [01:20<06:48,  2.02batch/s]h/s]
siglip2 videos:  18%|█▊        | 177/1000 [01:20<06:54,  1.99batch/s]h/s]
pe_core_l14 videos:  19%|█▉        | 192/1000 [01:10<04:18,  3.13batch/s]
siglip2 videos:  18%|█▊        | 178/1000 [01:21<06:47,  2.02batch/s]h/s]
siglip2 videos:  18%|█▊        | 179/1000 [01:21<06:49,  2.00batch/s]h/s]
siglip2 videos:  18%|█▊        | 180/1000 [01:22<06:53,  1.98batch/s]h/s]
pe_core_l14 videos:  20%|█▉        | 196/1000 [01:12<04:35,  2.92batch/s]
siglip2 videos:  18%|█▊        | 181/1000 [01:22<06:47,  2.01batch/s]h/s]
siglip2 videos:  18%|█▊        | 182/1000 [01:23<07:00,  1.94batch/s]h/s]
siglip2 videos:  18%|█▊        | 183/1000 [01:23<07:00,  1.94batch/s]h/s]
pe_core_l14 videos:  20%|██        | 200/1000 [01:13<04:43,  2.82batch/s]
siglip2 videos:  18%|█▊        | 184/1000 [01:24<06:51,  1.98batch/s]h/s]
siglip2 videos:  18%|█▊        | 185/1000 [01:25<07:01,  1.93batch/s]h/s]
pe_core_l14 videos:  20%|██        | 203/1000 [01:14<04:25,  3.01batch/s]
siglip2 videos:  19%|█▊        | 186/1000 [01:25<06:53,  1.97batch/s]h/s]
siglip2 videos:  19%|█▊        | 187/1000 [01:26<07:06,  1.91batch/s]h/s]
siglip2 videos:  19%|█▉        | 188/1000 [01:26<07:02,  1.92batch/s]h/s]
pe_core_l14 videos:  21%|██        | 207/1000 [01:16<04:39,  2.84batch/s]
siglip2 videos:  19%|█▉        | 189/1000 [01:27<06:52,  1.97batch/s]h/s]
siglip2 videos:  19%|█▉        | 190/1000 [01:27<06:45,  2.00batch/s]h/s]
siglip2 videos:  19%|█▉        | 191/1000 [01:28<06:52,  1.96batch/s]h/s]
siglip2 videos:  19%|█▉        | 192/1000 [01:28<06:52,  1.96batch/s]h/s]
pe_core_l14 videos:  21%|██        | 212/1000 [01:18<04:42,  2.79batch/s]
siglip2 videos:  19%|█▉        | 193/1000 [01:29<06:47,  1.98batch/s]h/s]
siglip2 videos:  19%|█▉        | 194/1000 [01:29<06:44,  1.99batch/s]h/s]
siglip2 videos:  20%|█▉        | 195/1000 [01:30<06:49,  1.97batch/s]h/s]
pe_core_l14 videos:  22%|██▏       | 216/1000 [01:19<04:36,  2.84batch/s]
siglip2 videos:  20%|█▉        | 196/1000 [01:30<07:03,  1.90batch/s]h/s]
siglip2 videos:  20%|█▉        | 197/1000 [01:31<06:59,  1.91batch/s]h/s]
pe_core_l14 videos:  22%|██▏       | 219/1000 [01:21<04:28,  2.90batch/s]
siglip2 videos:  20%|█▉        | 198/1000 [01:31<07:06,  1.88batch/s]h/s]
siglip2 videos:  20%|█▉        | 199/1000 [01:32<07:06,  1.88batch/s]h/s]
pe_core_l14 videos:  22%|██▏       | 222/1000 [01:22<04:29,  2.89batch/s]
siglip2 videos:  20%|██        | 200/1000 [01:32<07:18,  1.82batch/s]h/s]
siglip2 videos:  20%|██        | 201/1000 [01:33<07:12,  1.85batch/s]h/s]
pe_core_l14 videos:  22%|██▎       | 225/1000 [01:23<04:29,  2.87batch/s]
siglip2 videos:  20%|██        | 202/1000 [01:33<06:59,  1.90batch/s]h/s]
siglip2 videos:  20%|██        | 203/1000 [01:34<07:09,  1.86batch/s]h/s]
siglip2 videos:  20%|██        | 204/1000 [01:34<07:04,  1.87batch/s]h/s]
pe_core_l14 videos:  23%|██▎       | 229/1000 [01:24<04:37,  2.78batch/s]
siglip2 videos:  20%|██        | 205/1000 [01:35<06:54,  1.92batch/s]h/s]
siglip2 videos:  21%|██        | 206/1000 [01:35<06:48,  1.94batch/s]h/s]
siglip2 videos:  21%|██        | 207/1000 [01:36<06:44,  1.96batch/s]h/s]
siglip2 videos:  21%|██        | 208/1000 [01:36<06:39,  1.98batch/s]h/s]
siglip2 videos:  21%|██        | 209/1000 [01:37<06:44,  1.96batch/s]h/s]
pe_core_l14 videos:  24%|██▎       | 235/1000 [01:27<04:38,  2.75batch/s]
siglip2 videos:  21%|██        | 210/1000 [01:37<06:39,  1.98batch/s]h/s]
siglip2 videos:  21%|██        | 211/1000 [01:38<06:44,  1.95batch/s]h/s]
siglip2 videos:  21%|██        | 212/1000 [01:39<06:46,  1.94batch/s]h/s]
pe_core_l14 videos:  24%|██▍       | 239/1000 [01:28<04:33,  2.79batch/s]
siglip2 videos:  21%|██▏       | 213/1000 [01:39<06:44,  1.95batch/s]h/s]
siglip2 videos:  21%|██▏       | 214/1000 [01:40<06:40,  1.96batch/s]h/s]
siglip2 videos:  22%|██▏       | 215/1000 [01:40<06:44,  1.94batch/s]h/s]
siglip2 videos:  22%|██▏       | 216/1000 [01:41<06:47,  1.92batch/s]h/s]
pe_core_l14 videos:  24%|██▍       | 244/1000 [01:30<04:38,  2.72batch/s]
siglip2 videos:  22%|██▏       | 217/1000 [01:41<06:40,  1.96batch/s]h/s]
siglip2 videos:  22%|██▏       | 218/1000 [01:42<06:44,  1.93batch/s]h/s]
pe_core_l14 videos:  25%|██▍       | 247/1000 [01:31<04:13,  2.98batch/s]
siglip2 videos:  22%|██▏       | 219/1000 [01:42<06:52,  1.89batch/s]h/s]
siglip2 videos:  22%|██▏       | 220/1000 [01:43<06:51,  1.90batch/s]h/s]
pe_core_l14 videos:  25%|██▌       | 250/1000 [01:33<04:15,  2.94batch/s]
siglip2 videos:  22%|██▏       | 221/1000 [01:43<06:46,  1.91batch/s]h/s]
siglip2 videos:  22%|██▏       | 222/1000 [01:44<06:46,  1.91batch/s]h/s]
pe_core_l14 videos:  25%|██▌       | 253/1000 [01:34<04:06,  3.03batch/s]
siglip2 videos:  22%|██▏       | 223/1000 [01:44<06:40,  1.94batch/s]h/s]
siglip2 videos:  22%|██▏       | 224/1000 [01:45<06:42,  1.93batch/s]h/s]
siglip2 videos:  22%|██▎       | 225/1000 [01:45<06:41,  1.93batch/s]h/s]
pe_core_l14 videos:  26%|██▌       | 257/1000 [01:35<04:19,  2.86batch/s]
siglip2 videos:  23%|██▎       | 226/1000 [01:46<06:34,  1.96batch/s]h/s]
siglip2 videos:  23%|██▎       | 227/1000 [01:46<06:30,  1.98batch/s]h/s]
siglip2 videos:  23%|██▎       | 228/1000 [01:47<06:34,  1.96batch/s]h/s]
pe_core_l14 videos:  26%|██▌       | 261/1000 [01:37<04:20,  2.84batch/s]
siglip2 videos:  23%|██▎       | 229/1000 [01:47<06:46,  1.90batch/s]h/s]
siglip2 videos:  23%|██▎       | 230/1000 [01:48<06:43,  1.91batch/s]h/s]
pe_core_l14 videos:  26%|██▋       | 264/1000 [01:38<04:13,  2.91batch/s]
siglip2 videos:  23%|██▎       | 231/1000 [01:48<06:33,  1.95batch/s]h/s]
siglip2 videos:  23%|██▎       | 232/1000 [01:49<06:25,  1.99batch/s]h/s]
siglip2 videos:  23%|██▎       | 233/1000 [01:49<06:29,  1.97batch/s]h/s]
pe_core_l14 videos:  27%|██▋       | 268/1000 [01:39<04:07,  2.96batch/s]
siglip2 videos:  23%|██▎       | 234/1000 [01:50<06:22,  2.00batch/s]h/s]

-- none: R1 62.10  mAP 74.58  mINP 74.58
== Perception Encoder L/14 | activitynet/sentence | uniform8 (uniform 8 frames)

siglip2 videos:  79%|███████▉  | 793/1000 [06:27<01:44,  1.99batch/s]

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
siglip2 videos:  79%|███████▉  | 794/1000 [06:28<01:42,  2.00batch/s]
pe_core_l14 texts:   4%|▎         | 8/227 [00:00<00:05, 37.18batch/s]
pe_core_l14 texts:   5%|▌         | 12/227 [00:00<00:05, 36.63batch/s]
pe_core_l14 texts:   7%|▋         | 16/227 [00:00<00:05, 37.55batch/s]
pe_core_l14 texts:   9%|▉         | 20/227 [00:00<00:05, 36.33batch/s]
siglip2 videos:  80%|███████▉  | 795/1000 [06:28<01:40,  2.03batch/s]]
pe_core_l14 texts:  12%|█▏        | 28/227 [00:00<00:05, 33.44batch/s]
pe_core_l14 texts:  15%|█▍        | 33/227 [00:00<00:05, 35.70batch/s]
pe_core_l14 texts:  16%|█▋        | 37/227 [00:01<00:05, 35.86batch/s]
siglip2 videos:  80%|███████▉  | 796/1000 [06:29<01:39,  2.05batch/s]]
pe_core_l14 texts:  20%|█▉        | 45/227 [00:01<00:05, 35.08batch/s]
pe_core_l14 texts:  22%|██▏       | 49/227 [00:01<00:04, 36.21batch/s]
pe_core_l14 texts:  23%|██▎       | 53/227 [00:01<00:04, 36.27batch/s]
siglip2 videos:  80%|███████▉  | 797/1000 [06:29<01:37,  2.07batch/s]]
pe_core_l14 texts:  27%|██▋       | 61/227 [00:01<00:05, 31.12batch/s]
pe_core_l14 texts:  29%|██▊       | 65/227 [00:01<00:04, 33.25batch/s]
pe_core_l14 texts:  30%|███       | 69/227 [00:01<00:04, 34.06batch/s]
siglip2 videos:  80%|███████▉  | 798/1000 [06:29<01:37,  2.08batch/s]]
pe_core_l14 texts:  34%|███▍      | 77/227 [00:02<00:04, 33.37batch/s]
pe_core_l14 texts:  36%|███▌      | 82/227 [00:02<00:04, 35.67batch/s]
pe_core_l14 texts:  38%|███▊      | 86/227 [00:02<00:03, 35.74batch/s]
siglip2 videos:  80%|███████▉  | 799/1000 [06:30<01:36,  2.09batch/s]]
pe_core_l14 texts:  41%|████▏     | 94/227 [00:02<00:03, 35.26batch/s]
pe_core_l14 texts:  44%|████▎     | 99/227 [00:02<00:03, 36.94batch/s]
pe_core_l14 texts:  45%|████▌     | 103/227 [00:02<00:03, 36.99batch/s]
siglip2 videos:  80%|████████  | 800/1000 [06:30<01:35,  2.09batch/s]s]
pe_core_l14 texts:  49%|████▉     | 111/227 [00:03<00:03, 36.59batch/s]
pe_core_l14 texts:  51%|█████     | 115/227 [00:03<00:03, 35.75batch/s]
pe_core_l14 texts:  52%|█████▏    | 119/227 [00:03<00:03, 35.73batch/s]
siglip2 videos:  80%|████████  | 801/1000 [06:31<01:34,  2.11batch/s]s]
pe_core_l14 texts:  56%|█████▌    | 127/227 [00:03<00:02, 36.28batch/s]
pe_core_l14 texts:  58%|█████▊    | 131/227 [00:03<00:02, 36.14batch/s]
pe_core_l14 texts:  59%|█████▉    | 135/227 [00:03<00:02, 36.25batch/s]
siglip2 videos:  80%|████████  | 802/1000 [06:31<01:33,  2.12batch/s]s]
pe_core_l14 texts:  63%|██████▎   | 143/227 [00:03<00:02, 36.63batch/s]
pe_core_l14 texts:  65%|██████▍   | 147/227 [00:04<00:02, 35.52batch/s]
pe_core_l14 texts:  67%|██████▋   | 151/227 [00:04<00:02, 36.26batch/s]
pe_core_l14 texts:  68%|██████▊   | 155/227 [00:04<00:02, 35.21batch/s]
siglip2 videos:  80%|████████  | 803/1000 [06:32<01:33,  2.12batch/s]s]
pe_core_l14 texts:  72%|███████▏  | 163/227 [00:04<00:01, 35.05batch/s]
pe_core_l14 texts:  74%|███████▎  | 167/227 [00:04<00:01, 36.04batch/s]
pe_core_l14 texts:  75%|███████▌  | 171/227 [00:04<00:01, 35.79batch/s]
siglip2 videos:  80%|████████  | 804/1000 [06:32<01:32,  2.12batch/s]s]
pe_core_l14 texts:  79%|███████▉  | 179/227 [00:05<00:01, 35.31batch/s]
pe_core_l14 texts:  81%|████████  | 183/227 [00:05<00:01, 36.37batch/s]
pe_core_l14 texts:  82%|████████▏ | 187/227 [00:05<00:01, 36.36batch/s]
siglip2 videos:  80%|████████  | 805/1000 [06:33<01:32,  2.12batch/s]s]
pe_core_l14 texts:  86%|████████▌ | 195/227 [00:05<00:00, 36.16batch/s]
pe_core_l14 texts:  88%|████████▊ | 199/227 [00:05<00:00, 36.06batch/s]
pe_core_l14 texts:  89%|████████▉ | 203/227 [00:05<00:00, 36.48batch/s]
pe_core_l14 texts:  91%|█████████ | 207/227 [00:05<00:00, 36.93batch/s]
siglip2 videos:  81%|████████  | 806/1000 [06:33<01:31,  2.12batch/s]s]
pe_core_l14 texts:  95%|█████████▍| 215/227 [00:06<00:00, 34.55batch/s]
pe_core_l14 texts:  96%|█████████▋| 219/227 [00:06<00:00, 35.58batch/s]
siglip2 videos:  81%|████████  | 807/1000 [06:34<01:31,  2.12batch/s]s]
pe_core_l14 texts: 100%|██████████| 227/227 [00:06<00:00, 35.70batch/s]
siglip2 videos:  81%|████████  | 812/1000 [06:36<01:43,  1.82batch/s]

-- none: R1 36.25  mAP 49.36  mINP 49.36
== Perception Encoder L/14 | activitynet/paragraph | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  99%|█████████▉| 991/1000 [08:01<00:04,  2.13batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos:  99%|█████████▉| 992/1000 [08:02<00:04,  1.96batch/s]
pe_core_l14 videos:   0%|          | 1/1989 [00:00<10:00,  3.31batch/s]
siglip2 videos:  99%|█████████▉| 993/1000 [08:02<00:03,  1.91batch/s]s]
pe_core_l14 videos:   0%|          | 3/1989 [00:00<09:12,  3.60batch/s]
siglip2 videos:  99%|█████████▉| 994/1000 [08:03<00:03,  1.94batch/s]s]
pe_core_l14 videos:   0%|          | 5/1989 [00:01<08:34,  3.86batch/s]
siglip2 videos: 100%|█████████▉| 995/1000 [08:03<00:02,  1.96batch/s]s]
pe_core_l14 videos:   0%|          | 7/1989 [00:01<08:23,  3.94batch/s]
siglip2 videos: 100%|█████████▉| 996/1000 [08:04<00:02,  1.93batch/s]s]
pe_core_l14 videos:   0%|          | 9/1989 [00:02<08:32,  3.87batch/s]
siglip2 videos: 100%|█████████▉| 997/1000 [08:04<00:01,  1.92batch/s]/s]
pe_core_l14 videos:   1%|          | 11/1989 [00:02<08:35,  3.84batch/s]
siglip2 videos: 100%|█████████▉| 998/1000 [08:05<00:01,  1.92batch/s]/s]
pe_core_l14 videos:   1%|          | 13/1989 [00:03<08:30,  3.87batch/s]
siglip2 videos: 100%|█████████▉| 999/1000 [08:05<00:00,  1.95batch/s]/s]
pe_core_l14 videos:   1%|          | 15/1989 [00:03<08:19,  3.95batch/s]
siglip2 videos: 100%|██████████| 1000/1000 [08:06<00:00,  1.91batch/s]s]
siglip2 videos: 100%|██████████| 1000/1000 [08:06<00:00,  2.06batch/s]s]
siglip2 texts:   6%|▋         | 4/63 [00:00<00:03, 17.07batch/s]
siglip2 texts:  13%|█▎        | 8/63 [00:00<00:03, 16.79batch/s]batch/s]
siglip2 texts:  19%|█▉        | 12/63 [00:00<00:03, 16.67batch/s]atch/s]
siglip2 texts:  25%|██▌       | 16/63 [00:00<00:02, 16.75batch/s]atch/s]
siglip2 texts:  32%|███▏      | 20/63 [00:01<00:02, 16.93batch/s]atch/s]
siglip2 texts:  38%|███▊      | 24/63 [00:01<00:02, 16.79batch/s]atch/s]
siglip2 texts:  48%|████▊     | 30/63 [00:01<00:01, 16.64batch/s]atch/s]
siglip2 texts:  54%|█████▍    | 34/63 [00:02<00:01, 16.61batch/s]atch/s]
siglip2 texts:  60%|██████    | 38/63 [00:02<00:01, 16.53batch/s]atch/s]
siglip2 texts:  67%|██████▋   | 42/63 [00:02<00:01, 16.51batch/s]atch/s]
siglip2 texts:  73%|███████▎  | 46/63 [00:02<00:01, 16.46batch/s]atch/s]
siglip2 texts:  79%|███████▉  | 50/63 [00:03<00:00, 16.42batch/s]atch/s]
siglip2 texts:  86%|████████▌ | 54/63 [00:03<00:00, 16.29batch/s]atch/s]
siglip2 texts:  95%|█████████▌| 60/63 [00:03<00:00, 16.56batch/s]atch/s]
siglip2 texts: 100%|██████████| 63/63 [00:03<00:00, 16.69batch/s]atch/s]

pe_core_l14 videos:   2%|▏         | 32/1989 [00:08<08:30,  3.83batch/s]
pe_core_l14 videos:   2%|▏         | 33/1989 [00:08<10:35,  3.08batch/s]

-- none: R1 51.80  mAP 66.04  mINP 66.04
== SigLIP 2 So400m | activitynet/sentence | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 texts:   0%|          | 0/227 [00:00<?, ?batch/s],  2.77batch/s]
siglip2 texts:   2%|▏         | 4/227 [00:00<00:12, 17.96batch/s]atch/s]
siglip2 texts:   4%|▎         | 8/227 [00:00<00:12, 17.36batch/s]atch/s]
siglip2 texts:   6%|▌         | 14/227 [00:00<00:12, 17.25batch/s]tch/s]
siglip2 texts:   8%|▊         | 18/227 [00:01<00:12, 17.05batch/s]tch/s]
siglip2 texts:  10%|▉         | 22/227 [00:01<00:11, 17.20batch/s]tch/s]
siglip2 texts:  11%|█▏        | 26/227 [00:01<00:11, 17.15batch/s]tch/s]
siglip2 texts:  13%|█▎        | 30/227 [00:01<00:11, 17.25batch/s]tch/s]
siglip2 texts:  16%|█▌        | 36/227 [00:02<00:11, 17.23batch/s]tch/s]
siglip2 texts:  18%|█▊        | 40/227 [00:02<00:10, 17.21batch/s]tch/s]
siglip2 texts:  19%|█▉        | 44/227 [00:02<00:10, 17.30batch/s]tch/s]
siglip2 texts:  21%|██        | 48/227 [00:02<00:10, 17.16batch/s]tch/s]
siglip2 texts:  23%|██▎       | 52/227 [00:03<00:10, 17.22batch/s]tch/s]
siglip2 texts:  26%|██▌       | 58/227 [00:03<00:09, 17.03batch/s]tch/s]
siglip2 texts:  27%|██▋       | 62/227 [00:03<00:09, 17.17batch/s]tch/s]
siglip2 texts:  29%|██▉       | 66/227 [00:03<00:09, 17.08batch/s]tch/s]
siglip2 texts:  31%|███       | 70/227 [00:04<00:09, 16.85batch/s]tch/s]
siglip2 texts:  33%|███▎      | 76/227 [00:04<00:08, 17.02batch/s]tch/s]
siglip2 texts:  35%|███▌      | 80/227 [00:04<00:08, 16.98batch/s]tch/s]
siglip2 texts:  37%|███▋      | 84/227 [00:04<00:08, 17.17batch/s]tch/s]
siglip2 texts:  39%|███▉      | 88/227 [00:05<00:08, 16.95batch/s]tch/s]
siglip2 texts:  41%|████▏     | 94/227 [00:05<00:07, 17.09batch/s]tch/s]
siglip2 texts:  43%|████▎     | 98/227 [00:05<00:07, 17.02batch/s]tch/s]
siglip2 texts:  45%|████▍     | 102/227 [00:05<00:07, 16.79batch/s]ch/s]
siglip2 texts:  47%|████▋     | 106/227 [00:06<00:07, 16.91batch/s]ch/s]
siglip2 texts:  49%|████▉     | 112/227 [00:06<00:06, 16.98batch/s]ch/s]
siglip2 texts:  51%|█████     | 116/227 [00:06<00:06, 17.15batch/s]ch/s]
siglip2 texts:  53%|█████▎    | 120/227 [00:07<00:06, 17.01batch/s]ch/s]
siglip2 texts:  56%|█████▌    | 126/227 [00:07<00:05, 16.96batch/s]ch/s]
siglip2 texts:  57%|█████▋    | 130/227 [00:07<00:05, 17.09batch/s]ch/s]
siglip2 texts:  59%|█████▉    | 134/227 [00:07<00:05, 17.10batch/s]ch/s]
siglip2 texts:  61%|██████    | 138/227 [00:08<00:05, 17.07batch/s]ch/s]
siglip2 texts:  63%|██████▎   | 144/227 [00:08<00:04, 17.03batch/s]ch/s]
siglip2 texts:  65%|██████▌   | 148/227 [00:08<00:04, 17.10batch/s]ch/s]
siglip2 texts:  67%|██████▋   | 152/227 [00:08<00:04, 16.87batch/s]ch/s]
siglip2 texts:  69%|██████▊   | 156/227 [00:09<00:04, 16.92batch/s]ch/s]
siglip2 texts:  71%|███████▏  | 162/227 [00:09<00:03, 16.95batch/s]ch/s]
siglip2 texts:  73%|███████▎  | 166/227 [00:09<00:03, 16.78batch/s]ch/s]
siglip2 texts:  75%|███████▍  | 170/227 [00:09<00:03, 17.05batch/s]ch/s]
siglip2 texts:  77%|███████▋  | 174/227 [00:10<00:03, 16.94batch/s]ch/s]
siglip2 texts:  79%|███████▉  | 180/227 [00:10<00:02, 16.96batch/s]ch/s]
siglip2 texts:  81%|████████  | 184/227 [00:10<00:02, 17.01batch/s]ch/s]
siglip2 texts:  83%|████████▎ | 188/227 [00:11<00:02, 16.87batch/s]ch/s]
siglip2 texts:  85%|████████▍ | 192/227 [00:11<00:02, 16.94batch/s]ch/s]
siglip2 texts:  87%|████████▋ | 198/227 [00:11<00:01, 16.94batch/s]ch/s]
siglip2 texts:  89%|████████▉ | 202/227 [00:11<00:01, 16.88batch/s]ch/s]
siglip2 texts:  91%|█████████ | 206/227 [00:12<00:01, 17.07batch/s]ch/s]
siglip2 texts:  93%|█████████▎| 210/227 [00:12<00:01, 16.92batch/s]ch/s]
siglip2 texts:  95%|█████████▌| 216/227 [00:12<00:00, 17.10batch/s]ch/s]
siglip2 texts:  97%|█████████▋| 220/227 [00:12<00:00, 16.97batch/s]ch/s]
siglip2 texts:  99%|█████████▊| 224/227 [00:13<00:00, 16.82batch/s]ch/s]
siglip2 texts: 100%|██████████| 227/227 [00:13<00:00, 17.01batch/s]ch/s]

pe_core_l14 videos:   4%|▍         | 86/1989 [00:23<08:19,  3.81batch/s]
pe_core_l14 videos:   4%|▍         | 87/1989 [00:23<09:40,  3.28batch/s]
pe_core_l14 videos:   4%|▍         | 88/1989 [00:23<11:41,  2.71batch/s]
pe_core_l14 videos:   4%|▍         | 89/1989 [00:24<12:39,  2.50batch/s]
pe_core_l14 videos:   5%|▍         | 90/1989 [00:24<12:51,  2.46batch/s]
pe_core_l14 videos:   5%|▍         | 91/1989 [00:25<13:26,  2.35batch/s]
pe_core_l14 videos:   5%|▍         | 92/1989 [00:25<14:24,  2.19batch/s]

-- none: R1 28.50  mAP 41.70  mINP 41.70
== SigLIP 2 So400m | activitynet/paragraph | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

pe_core_l14 videos:   5%|▍         | 93/1989 [00:26<14:34,  2.17batch/s]

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos:   5%|▍         | 94/1989 [00:26<12:36,  2.50batch/s]
pe_core_l14 videos:   5%|▍         | 95/1989 [00:26<11:14,  2.81batch/s]
pe_core_l14 videos:   5%|▍         | 96/1989 [00:27<10:18,  3.06batch/s]
pe_core_l14 videos:   5%|▍         | 97/1989 [00:27<09:37,  3.28batch/s]
pe_core_l14 videos:   5%|▍         | 98/1989 [00:27<09:04,  3.48batch/s]
pe_core_l14 videos:   5%|▍         | 99/1989 [00:27<08:51,  3.55batch/s]
pe_core_l14 videos:   5%|▌         | 100/1989 [00:28<08:39,  3.64batch/s]
pe_core_l14 videos:   5%|▌         | 101/1989 [00:28<08:27,  3.72batch/s]
pe_core_l14 videos:   5%|▌         | 102/1989 [00:28<08:18,  3.79batch/s]
pe_core_l14 videos:   5%|▌         | 103/1989 [00:28<08:10,  3.85batch/s]
pe_core_l14 videos:   5%|▌         | 104/1989 [00:29<08:05,  3.88batch/s]
pe_core_l14 videos:   5%|▌         | 105/1989 [00:29<08:06,  3.87batch/s]
pe_core_l14 videos:   5%|▌         | 106/1989 [00:29<08:07,  3.86batch/s]
pe_core_l14 videos:   5%|▌         | 107/1989 [00:29<08:04,  3.89batch/s]
pe_core_l14 videos:   5%|▌         | 108/1989 [00:30<08:04,  3.88batch/s]
pe_core_l14 videos:   5%|▌         | 109/1989 [00:30<08:02,  3.90batch/s]
pe_core_l14 videos:   6%|▌         | 110/1989 [00:30<08:02,  3.89batch/s]
pe_core_l14 videos:   6%|▌         | 111/1989 [00:30<08:00,  3.91batch/s]
pe_core_l14 videos:   6%|▌         | 112/1989 [00:31<08:00,  3.90batch/s]
pe_core_l14 videos:   6%|▌         | 113/1989 [00:31<08:01,  3.89batch/s]
pe_core_l14 videos:   6%|▌         | 114/1989 [00:31<07:59,  3.91batch/s]
pe_core_l14 videos:   6%|▌         | 115/1989 [00:31<07:57,  3.93batch/s]
pe_core_l14 videos:   6%|▌         | 116/1989 [00:32<07:56,  3.93batch/s]
pe_core_l14 videos:   6%|▌         | 117/1989 [00:32<07:48,  3.99batch/s]
pe_core_l14 videos:   6%|▌         | 118/1989 [00:32<07:50,  3.98batch/s]
pe_core_l14 videos:   6%|▌         | 119/1989 [00:32<07:51,  3.97batch/s]
pe_core_l14 videos:   6%|▌         | 120/1989 [00:33<07:54,  3.94batch/s]
pe_core_l14 videos:   6%|▌         | 121/1989 [00:33<07:54,  3.93batch/s]
pe_core_l14 videos:   6%|▌         | 122/1989 [00:33<07:55,  3.93batch/s]
pe_core_l14 videos:   6%|▌         | 123/1989 [00:33<07:56,  3.92batch/s]
pe_core_l14 videos:   6%|▌         | 124/1989 [00:34<07:55,  3.92batch/s]
pe_core_l14 videos:   6%|▋         | 125/1989 [00:34<07:50,  3.96batch/s]
pe_core_l14 videos:   6%|▋         | 126/1989 [00:34<07:52,  3.94batch/s]
pe_core_l14 videos:   6%|▋         | 127/1989 [00:34<07:52,  3.94batch/s]
pe_core_l14 videos:   6%|▋         | 128/1989 [00:35<07:52,  3.94batch/s]
pe_core_l14 videos:   6%|▋         | 129/1989 [00:35<07:52,  3.94batch/s]
pe_core_l14 videos:   7%|▋         | 130/1989 [00:35<07:53,  3.92batch/s]
pe_core_l14 videos:   7%|▋         | 131/1989 [00:35<07:55,  3.91batch/s]
pe_core_l14 videos:   7%|▋         | 132/1989 [00:36<07:57,  3.89batch/s]
pe_core_l14 videos:   7%|▋         | 133/1989 [00:36<07:56,  3.89batch/s]
pe_core_l14 videos:   7%|▋         | 134/1989 [00:36<07:57,  3.88batch/s]
pe_core_l14 videos:   7%|▋         | 135/1989 [00:37<07:57,  3.89batch/s]
pe_core_l14 videos:   7%|▋         | 136/1989 [00:37<07:55,  3.90batch/s]
pe_core_l14 videos:   7%|▋         | 137/1989 [00:37<07:55,  3.90batch/s]
pe_core_l14 videos:   7%|▋         | 138/1989 [00:37<08:01,  3.85batch/s]
pe_core_l14 videos:   7%|▋         | 139/1989 [00:38<07:59,  3.86batch/s]
pe_core_l14 videos:   7%|▋         | 140/1989 [00:38<07:57,  3.87batch/s]
pe_core_l14 videos:   7%|▋         | 141/1989 [00:38<07:54,  3.90batch/s]
pe_core_l14 videos:   7%|▋         | 142/1989 [00:38<07:51,  3.91batch/s]
pe_core_l14 videos:   7%|▋         | 143/1989 [00:39<07:54,  3.89batch/s]
pe_core_l14 videos:   7%|▋         | 144/1989 [00:39<07:52,  3.91batch/s]
pe_core_l14 videos:   7%|▋         | 145/1989 [00:39<07:55,  3.88batch/s]
pe_core_l14 videos:   7%|▋         | 146/1989 [00:39<07:52,  3.90batch/s]
pe_core_l14 videos:   7%|▋         | 147/1989 [00:40<07:51,  3.91batch/s]
pe_core_l14 videos:   7%|▋         | 148/1989 [00:40<07:51,  3.91batch/s]
pe_core_l14 videos:   7%|▋         | 149/1989 [00:40<07:52,  3.89batch/s]
pe_core_l14 videos:   8%|▊         | 150/1989 [00:40<07:50,  3.91batch/s]
pe_core_l14 videos:   8%|▊         | 151/1989 [00:41<07:50,  3.91batch/s]
pe_core_l14 videos:   8%|▊         | 152/1989 [00:41<07:52,  3.89batch/s]
pe_core_l14 videos:   8%|▊         | 153/1989 [00:41<07:55,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 154/1989 [00:41<07:55,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 155/1989 [00:42<07:53,  3.87batch/s]
pe_core_l14 videos:   8%|▊         | 156/1989 [00:42<07:52,  3.88batch/s]
pe_core_l14 videos:   8%|▊         | 157/1989 [00:42<07:54,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 158/1989 [00:42<07:53,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 159/1989 [00:43<07:55,  3.85batch/s]
pe_core_l14 videos:   8%|▊         | 160/1989 [00:43<07:53,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 161/1989 [00:43<07:51,  3.88batch/s]
pe_core_l14 videos:   8%|▊         | 162/1989 [00:43<07:50,  3.88batch/s]
pe_core_l14 videos:   8%|▊         | 163/1989 [00:44<07:52,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 164/1989 [00:44<07:52,  3.86batch/s]
pe_core_l14 videos:   8%|▊         | 165/1989 [00:44<07:54,  3.84batch/s]
pe_core_l14 videos:   8%|▊         | 166/1989 [00:45<07:53,  3.85batch/s]
pe_core_l14 videos:   8%|▊         | 167/1989 [00:45<07:55,  3.83batch/s]
pe_core_l14 videos:   8%|▊         | 168/1989 [00:45<07:55,  3.83batch/s]
pe_core_l14 videos:   8%|▊         | 169/1989 [00:45<07:55,  3.83batch/s]
pe_core_l14 videos:   9%|▊         | 170/1989 [00:46<07:54,  3.83batch/s]
pe_core_l14 videos:   9%|▊         | 171/1989 [00:46<07:56,  3.82batch/s]
pe_core_l14 videos:   9%|▊         | 172/1989 [00:46<07:56,  3.81batch/s]
pe_core_l14 videos:   9%|▊         | 173/1989 [00:46<07:53,  3.84batch/s]
pe_core_l14 videos:   9%|▊         | 174/1989 [00:47<07:51,  3.85batch/s]
pe_core_l14 videos:   9%|▉         | 175/1989 [00:47<07:50,  3.86batch/s]
pe_core_l14 videos:   9%|▉         | 176/1989 [00:47<07:50,  3.86batch/s]
pe_core_l14 videos:   9%|▉         | 177/1989 [00:47<07:52,  3.84batch/s]
pe_core_l14 videos:   9%|▉         | 178/1989 [00:48<07:51,  3.84batch/s]
pe_core_l14 videos:   9%|▉         | 179/1989 [00:48<07:50,  3.84batch/s]
pe_core_l14 videos:   9%|▉         | 180/1989 [00:48<07:52,  3.83batch/s]
pe_core_l14 videos:   9%|▉         | 181/1989 [00:48<07:52,  3.83batch/s]
pe_core_l14 videos:   9%|▉         | 182/1989 [00:49<07:53,  3.82batch/s]
pe_core_l14 videos:   9%|▉         | 183/1989 [00:49<07:54,  3.80batch/s]
pe_core_l14 videos:   9%|▉         | 184/1989 [00:49<07:57,  3.78batch/s]
pe_core_l14 videos:   9%|▉         | 185/1989 [00:50<07:59,  3.76batch/s]
pe_core_l14 videos:   9%|▉         | 186/1989 [00:50<07:57,  3.78batch/s]
pe_core_l14 videos:   9%|▉         | 187/1989 [00:50<07:56,  3.78batch/s]
pe_core_l14 videos:   9%|▉         | 188/1989 [00:50<07:53,  3.80batch/s]
pe_core_l14 videos:  10%|▉         | 189/1989 [00:51<07:52,  3.81batch/s]
pe_core_l14 videos:  10%|▉         | 190/1989 [00:51<07:53,  3.80batch/s]
pe_core_l14 videos:  10%|▉         | 191/1989 [00:51<07:52,  3.80batch/s]
pe_core_l14 videos:  10%|▉         | 192/1989 [00:51<07:52,  3.81batch/s]
pe_core_l14 videos:  10%|▉         | 193/1989 [00:52<07:56,  3.77batch/s]
pe_core_l14 videos:  10%|▉         | 194/1989 [00:52<07:59,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 195/1989 [00:52<07:59,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 196/1989 [00:52<07:58,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 197/1989 [00:53<07:57,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 198/1989 [00:53<07:55,  3.76batch/s]
pe_core_l14 videos:  10%|█         | 199/1989 [00:53<07:53,  3.78batch/s]
pe_core_l14 videos:  10%|█         | 200/1989 [00:53<07:52,  3.79batch/s]
pe_core_l14 videos:  10%|█         | 201/1989 [00:54<07:51,  3.79batch/s]
pe_core_l14 videos:  10%|█         | 202/1989 [00:54<07:51,  3.79batch/s]
pe_core_l14 videos:  10%|█         | 203/1989 [00:54<07:51,  3.79batch/s]
pe_core_l14 videos:  10%|█         | 204/1989 [00:55<07:53,  3.77batch/s]
pe_core_l14 videos:  10%|█         | 205/1989 [00:55<07:55,  3.75batch/s]
pe_core_l14 videos:  10%|█         | 206/1989 [00:55<07:56,  3.74batch/s]
pe_core_l14 videos:  10%|█         | 207/1989 [00:55<07:56,  3.74batch/s]
pe_core_l14 videos:  10%|█         | 208/1989 [00:56<07:56,  3.74batch/s]
pe_core_l14 videos:  11%|█         | 209/1989 [00:56<07:57,  3.73batch/s]
pe_core_l14 videos:  11%|█         | 210/1989 [00:56<07:59,  3.71batch/s]
pe_core_l14 videos:  11%|█         | 211/1989 [00:56<07:59,  3.71batch/s]
pe_core_l14 videos:  11%|█         | 212/1989 [00:57<07:57,  3.72batch/s]
pe_core_l14 videos:  11%|█         | 213/1989 [00:57<07:56,  3.73batch/s]
pe_core_l14 videos:  11%|█         | 214/1989 [00:57<08:00,  3.70batch/s]
pe_core_l14 videos:  11%|█         | 215/1989 [00:58<08:00,  3.69batch/s]
pe_core_l14 videos:  11%|█         | 216/1989 [00:58<08:02,  3.67batch/s]
pe_core_l14 videos:  11%|█         | 217/1989 [00:58<08:02,  3.67batch/s]
pe_core_l14 videos:  11%|█         | 218/1989 [00:58<08:03,  3.66batch/s]
pe_core_l14 videos:  11%|█         | 219/1989 [00:59<08:02,  3.67batch/s]
pe_core_l14 videos:  11%|█         | 220/1989 [00:59<08:05,  3.65batch/s]
pe_core_l14 videos:  11%|█         | 221/1989 [00:59<08:02,  3.66batch/s]
pe_core_l14 videos:  11%|█         | 222/1989 [00:59<08:02,  3.66batch/s]
pe_core_l14 videos:  11%|█         | 223/1989 [01:00<08:02,  3.66batch/s]
pe_core_l14 videos:  11%|█▏        | 224/1989 [01:00<07:59,  3.68batch/s]
pe_core_l14 videos:  11%|█▏        | 225/1989 [01:00<08:00,  3.67batch/s]
pe_core_l14 videos:  11%|█▏        | 226/1989 [01:01<08:02,  3.65batch/s]
pe_core_l14 videos:  11%|█▏        | 227/1989 [01:01<08:01,  3.66batch/s]
pe_core_l14 videos:  11%|█▏        | 228/1989 [01:01<07:59,  3.67batch/s]
pe_core_l14 videos:  12%|█▏        | 229/1989 [01:01<08:01,  3.66batch/s]
pe_core_l14 videos:  12%|█▏        | 230/1989 [01:02<08:02,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 231/1989 [01:02<08:04,  3.63batch/s]
pe_core_l14 videos:  12%|█▏        | 232/1989 [01:02<08:03,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 233/1989 [01:02<08:01,  3.65batch/s]
pe_core_l14 videos:  12%|█▏        | 234/1989 [01:03<08:00,  3.65batch/s]
pe_core_l14 videos:  12%|█▏        | 235/1989 [01:03<07:57,  3.67batch/s]
pe_core_l14 videos:  12%|█▏        | 236/1989 [01:03<08:01,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 237/1989 [01:04<08:03,  3.62batch/s]
pe_core_l14 videos:  12%|█▏        | 238/1989 [01:04<08:03,  3.63batch/s]
pe_core_l14 videos:  12%|█▏        | 239/1989 [01:04<08:00,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 240/1989 [01:04<07:59,  3.65batch/s]
pe_core_l14 videos:  12%|█▏        | 241/1989 [01:05<07:58,  3.65batch/s]
pe_core_l14 videos:  12%|█▏        | 242/1989 [01:05<07:59,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 243/1989 [01:05<08:00,  3.64batch/s]
pe_core_l14 videos:  12%|█▏        | 244/1989 [01:05<08:03,  3.61batch/s]
pe_core_l14 videos:  12%|█▏        | 245/1989 [01:06<08:04,  3.60batch/s]
pe_core_l14 videos:  12%|█▏        | 246/1989 [01:06<08:05,  3.59batch/s]
pe_core_l14 videos:  12%|█▏        | 247/1989 [01:06<08:06,  3.58batch/s]
pe_core_l14 videos:  12%|█▏        | 248/1989 [01:07<08:05,  3.59batch/s]
pe_core_l14 videos:  13%|█▎        | 249/1989 [01:07<08:05,  3.59batch/s]
pe_core_l14 videos:  13%|█▎        | 250/1989 [01:07<08:12,  3.53batch/s]
pe_core_l14 videos:  13%|█▎        | 251/1989 [01:07<08:10,  3.54batch/s]
pe_core_l14 videos:  13%|█▎        | 252/1989 [01:08<08:07,  3.56batch/s]
pe_core_l14 videos:  13%|█▎        | 253/1989 [01:08<08:07,  3.56batch/s]
pe_core_l14 videos:  13%|█▎        | 254/1989 [01:08<08:05,  3.57batch/s]
pe_core_l14 videos:  13%|█▎        | 255/1989 [01:09<08:08,  3.55batch/s]
pe_core_l14 videos:  13%|█▎        | 256/1989 [01:09<08:08,  3.55batch/s]
pe_core_l14 videos:  13%|█▎        | 257/1989 [01:09<08:07,  3.55batch/s]
pe_core_l14 videos:  13%|█▎        | 258/1989 [01:09<08:06,  3.56batch/s]
pe_core_l14 videos:  13%|█▎        | 259/1989 [01:10<08:06,  3.56batch/s]
pe_core_l14 videos:  13%|█▎        | 260/1989 [01:10<08:07,  3.55batch/s]
pe_core_l14 videos:  13%|█▎        | 261/1989 [01:10<08:07,  3.54batch/s]
pe_core_l14 videos:  13%|█▎        | 262/1989 [01:11<08:08,  3.53batch/s]
pe_core_l14 videos:  13%|█▎        | 263/1989 [01:11<08:10,  3.52batch/s]
pe_core_l14 videos:  13%|█▎        | 264/1989 [01:11<08:08,  3.53batch/s]
pe_core_l14 videos:  13%|█▎        | 265/1989 [01:11<08:08,  3.53batch/s]
pe_core_l14 videos:  13%|█▎        | 266/1989 [01:12<08:09,  3.52batch/s]
pe_core_l14 videos:  13%|█▎        | 267/1989 [01:12<08:07,  3.53batch/s]
pe_core_l14 videos:  13%|█▎        | 268/1989 [01:12<08:08,  3.52batch/s]
pe_core_l14 videos:  14%|█▎        | 269/1989 [01:13<08:09,  3.51batch/s]
pe_core_l14 videos:  14%|█▎        | 270/1989 [01:13<08:09,  3.51batch/s]
pe_core_l14 videos:  14%|█▎        | 271/1989 [01:13<08:08,  3.52batch/s]
pe_core_l14 videos:  14%|█▎        | 272/1989 [01:13<08:08,  3.52batch/s]
pe_core_l14 videos:  14%|█▎        | 273/1989 [01:14<08:07,  3.52batch/s]
pe_core_l14 videos:  14%|█▍        | 274/1989 [01:14<08:07,  3.51batch/s]
pe_core_l14 videos:  14%|█▍        | 275/1989 [01:14<08:09,  3.50batch/s]
pe_core_l14 videos:  14%|█▍        | 276/1989 [01:15<08:09,  3.50batch/s]
pe_core_l14 videos:  14%|█▍        | 277/1989 [01:15<08:10,  3.49batch/s]
pe_core_l14 videos:  14%|█▍        | 278/1989 [01:15<08:13,  3.47batch/s]
pe_core_l14 videos:  14%|█▍        | 279/1989 [01:15<08:12,  3.47batch/s]
pe_core_l14 videos:  14%|█▍        | 280/1989 [01:16<08:10,  3.48batch/s]
pe_core_l14 videos:  14%|█▍        | 281/1989 [01:16<08:12,  3.46batch/s]
pe_core_l14 videos:  14%|█▍        | 282/1989 [01:16<08:10,  3.48batch/s]
pe_core_l14 videos:  14%|█▍        | 283/1989 [01:17<08:09,  3.49batch/s]
pe_core_l14 videos:  14%|█▍        | 284/1989 [01:17<08:08,  3.49batch/s]
pe_core_l14 videos:  14%|█▍        | 285/1989 [01:17<08:07,  3.50batch/s]
pe_core_l14 videos:  14%|█▍        | 286/1989 [01:17<08:12,  3.46batch/s]
pe_core_l14 videos:  14%|█▍        | 287/1989 [01:18<08:10,  3.47batch/s]
pe_core_l14 videos:  14%|█▍        | 288/1989 [01:18<08:11,  3.46batch/s]
pe_core_l14 videos:  15%|█▍        | 289/1989 [01:18<08:08,  3.48batch/s]
pe_core_l14 videos:  15%|█▍        | 290/1989 [01:19<08:11,  3.46batch/s]
pe_core_l14 videos:  15%|█▍        | 291/1989 [01:19<08:09,  3.47batch/s]
pe_core_l14 videos:  15%|█▍        | 292/1989 [01:19<08:09,  3.46batch/s]
pe_core_l14 videos:  15%|█▍        | 293/1989 [01:19<08:08,  3.48batch/s]
pe_core_l14 videos:  15%|█▍        | 294/1989 [01:20<08:05,  3.49batch/s]
pe_core_l14 videos:  15%|█▍        | 295/1989 [01:20<08:06,  3.48batch/s]
pe_core_l14 videos:  15%|█▍        | 296/1989 [01:20<08:06,  3.48batch/s]
pe_core_l14 videos:  15%|█▍        | 297/1989 [01:21<08:05,  3.49batch/s]
pe_core_l14 videos:  15%|█▍        | 298/1989 [01:21<08:04,  3.49batch/s]
pe_core_l14 videos:  15%|█▌        | 299/1989 [01:21<08:09,  3.45batch/s]
pe_core_l14 videos:  15%|█▌        | 300/1989 [01:21<08:06,  3.47batch/s]
pe_core_l14 videos:  15%|█▌        | 301/1989 [01:22<08:06,  3.47batch/s]
pe_core_l14 videos:  15%|█▌        | 302/1989 [01:22<08:05,  3.47batch/s]
pe_core_l14 videos:  15%|█▌        | 303/1989 [01:22<08:04,  3.48batch/s]
pe_core_l14 videos:  15%|█▌        | 304/1989 [01:23<08:03,  3.49batch/s]
pe_core_l14 videos:  15%|█▌        | 305/1989 [01:23<08:03,  3.48batch/s]
pe_core_l14 videos:  15%|█▌        | 306/1989 [01:23<08:04,  3.47batch/s]
pe_core_l14 videos:  15%|█▌        | 307/1989 [01:23<08:05,  3.46batch/s]
pe_core_l14 videos:  15%|█▌        | 308/1989 [01:24<08:05,  3.46batch/s]
pe_core_l14 videos:  16%|█▌        | 309/1989 [01:24<08:09,  3.44batch/s]
pe_core_l14 videos:  16%|█▌        | 310/1989 [01:24<08:06,  3.45batch/s]
pe_core_l14 videos:  16%|█▌        | 311/1989 [01:25<08:05,  3.46batch/s]
pe_core_l14 videos:  16%|█▌        | 312/1989 [01:25<08:04,  3.46batch/s]
pe_core_l14 videos:  16%|█▌        | 313/1989 [01:25<08:02,  3.47batch/s]
pe_core_l14 videos:  16%|█▌        | 314/1989 [01:25<07:59,  3.50batch/s]
pe_core_l14 videos:  16%|█▌        | 315/1989 [01:26<07:59,  3.49batch/s]
pe_core_l14 videos:  16%|█▌        | 316/1989 [01:26<07:58,  3.50batch/s]
pe_core_l14 videos:  16%|█▌        | 317/1989 [01:26<07:58,  3.49batch/s]
pe_core_l14 videos:  16%|█▌        | 318/1989 [01:27<07:57,  3.50batch/s]
pe_core_l14 videos:  16%|█▌        | 319/1989 [01:27<07:57,  3.50batch/s]
pe_core_l14 videos:  16%|█▌        | 320/1989 [01:27<07:57,  3.50batch/s]
pe_core_l14 videos:  16%|█▌        | 321/1989 [01:27<07:59,  3.48batch/s]
pe_core_l14 videos:  16%|█▌        | 322/1989 [01:28<07:59,  3.48batch/s]
pe_core_l14 videos:  16%|█▌        | 323/1989 [01:28<07:55,  3.51batch/s]
pe_core_l14 videos:  16%|█▋        | 324/1989 [01:28<07:53,  3.51batch/s]
pe_core_l14 videos:  16%|█▋        | 325/1989 [01:29<07:53,  3.52batch/s]
pe_core_l14 videos:  16%|█▋        | 326/1989 [01:29<07:54,  3.51batch/s]
pe_core_l14 videos:  16%|█▋        | 327/1989 [01:29<07:54,  3.50batch/s]
pe_core_l14 videos:  16%|█▋        | 328/1989 [01:29<07:52,  3.51batch/s]
pe_core_l14 videos:  17%|█▋        | 329/1989 [01:30<07:50,  3.53batch/s]
pe_core_l14 videos:  17%|█▋        | 330/1989 [01:30<07:48,  3.54batch/s]
pe_core_l14 videos:  17%|█▋        | 331/1989 [01:30<07:47,  3.54batch/s]
pe_core_l14 videos:  17%|█▋        | 332/1989 [01:31<07:48,  3.54batch/s]
pe_core_l14 videos:  17%|█▋        | 333/1989 [01:31<07:47,  3.54batch/s]
pe_core_l14 videos:  17%|█▋        | 334/1989 [01:31<07:45,  3.56batch/s]
pe_core_l14 videos:  17%|█▋        | 335/1989 [01:31<07:41,  3.58batch/s]
pe_core_l14 videos:  17%|█▋        | 336/1989 [01:32<07:43,  3.57batch/s]
pe_core_l14 videos:  17%|█▋        | 337/1989 [01:32<07:42,  3.57batch/s]
pe_core_l14 videos:  17%|█▋        | 338/1989 [01:32<07:42,  3.57batch/s]
pe_core_l14 videos:  17%|█▋        | 339/1989 [01:33<07:40,  3.58batch/s]
pe_core_l14 videos:  17%|█▋        | 340/1989 [01:33<07:43,  3.55batch/s]
pe_core_l14 videos:  17%|█▋        | 341/1989 [01:33<07:44,  3.55batch/s]
pe_core_l14 videos:  17%|█▋        | 342/1989 [01:33<07:41,  3.57batch/s]
pe_core_l14 videos:  17%|█▋        | 343/1989 [01:34<07:38,  3.59batch/s]
pe_core_l14 videos:  17%|█▋        | 344/1989 [01:34<07:36,  3.60batch/s]
pe_core_l14 videos:  17%|█▋        | 345/1989 [01:34<07:36,  3.60batch/s]
pe_core_l14 videos:  17%|█▋        | 346/1989 [01:34<07:32,  3.63batch/s]
pe_core_l14 videos:  17%|█▋        | 347/1989 [01:35<07:33,  3.62batch/s]
pe_core_l14 videos:  17%|█▋        | 348/1989 [01:35<07:33,  3.62batch/s]
pe_core_l14 videos:  18%|█▊        | 349/1989 [01:35<07:34,  3.61batch/s]
pe_core_l14 videos:  18%|█▊        | 350/1989 [01:36<07:32,  3.62batch/s]
pe_core_l14 videos:  18%|█▊        | 351/1989 [01:36<07:33,  3.61batch/s]
pe_core_l14 videos:  18%|█▊        | 352/1989 [01:36<07:34,  3.61batch/s]
pe_core_l14 videos:  18%|█▊        | 353/1989 [01:36<07:35,  3.59batch/s]
pe_core_l14 videos:  18%|█▊        | 354/1989 [01:37<07:33,  3.61batch/s]
pe_core_l14 videos:  18%|█▊        | 355/1989 [01:37<07:32,  3.61batch/s]
pe_core_l14 videos:  18%|█▊        | 356/1989 [01:37<07:30,  3.63batch/s]
pe_core_l14 videos:  18%|█▊        | 357/1989 [01:38<07:28,  3.64batch/s]
pe_core_l14 videos:  18%|█▊        | 358/1989 [01:38<07:27,  3.64batch/s]
pe_core_l14 videos:  18%|█▊        | 359/1989 [01:38<07:28,  3.63batch/s]
pe_core_l14 videos:  18%|█▊        | 360/1989 [01:38<07:28,  3.63batch/s]
pe_core_l14 videos:  18%|█▊        | 361/1989 [01:39<07:28,  3.63batch/s]
pe_core_l14 videos:  18%|█▊        | 362/1989 [01:39<07:29,  3.62batch/s]
pe_core_l14 videos:  18%|█▊        | 363/1989 [01:39<07:33,  3.59batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos:   0%|          | 0/1989 [00:00<?, ?batch/s]  3.67batch/s]
siglip2 videos:   0%|          | 1/1989 [00:00<19:06,  1.73batch/s]tch/s]
pe_core_l14 videos:  21%|██        | 411/1989 [01:52<07:54,  3.33batch/s]
siglip2 videos:   0%|          | 2/1989 [00:00<16:01,  2.07batch/s]tch/s]
siglip2 videos:   0%|          | 3/1989 [00:01<14:58,  2.21batch/s]tch/s]
siglip2 videos:   0%|          | 4/1989 [00:01<14:31,  2.28batch/s]tch/s]
siglip2 videos:   0%|          | 5/1989 [00:02<14:16,  2.32batch/s]tch/s]
siglip2 videos:   0%|          | 6/1989 [00:02<14:02,  2.35batch/s]tch/s]
siglip2 videos:   0%|          | 7/1989 [00:03<13:58,  2.36batch/s]tch/s]
siglip2 videos:   0%|          | 8/1989 [00:03<13:58,  2.36batch/s]tch/s]
siglip2 videos:   0%|          | 9/1989 [00:03<13:56,  2.37batch/s]tch/s]
siglip2 videos:   1%|          | 10/1989 [00:04<13:52,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 11/1989 [00:04<13:50,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 12/1989 [00:05<13:49,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 13/1989 [00:05<13:55,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 14/1989 [00:06<13:49,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 15/1989 [00:06<13:48,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 16/1989 [00:06<13:50,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 17/1989 [00:07<13:52,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 18/1989 [00:07<13:53,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 19/1989 [00:08<13:50,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 20/1989 [00:08<13:51,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 21/1989 [00:08<13:51,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 22/1989 [00:09<13:52,  2.36batch/s]ch/s]
siglip2 videos:   1%|          | 23/1989 [00:09<13:50,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 24/1989 [00:10<13:49,  2.37batch/s]ch/s]
siglip2 videos:   1%|▏         | 25/1989 [00:10<13:49,  2.37batch/s]ch/s]
siglip2 videos:   1%|▏         | 26/1989 [00:11<13:52,  2.36batch/s]ch/s]
siglip2 videos:   1%|▏         | 27/1989 [00:11<13:55,  2.35batch/s]ch/s]
siglip2 videos:   1%|▏         | 28/1989 [00:11<13:54,  2.35batch/s]ch/s]
siglip2 videos:   1%|▏         | 29/1989 [00:12<13:53,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 30/1989 [00:12<13:57,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 31/1989 [00:13<13:56,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 32/1989 [00:13<14:00,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 33/1989 [00:14<13:56,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 34/1989 [00:14<13:57,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 35/1989 [00:14<13:56,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 36/1989 [00:15<13:55,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 37/1989 [00:15<13:54,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 38/1989 [00:16<13:50,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 39/1989 [00:16<13:52,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 40/1989 [00:17<13:53,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 41/1989 [00:17<13:54,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 42/1989 [00:17<13:56,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 43/1989 [00:18<13:59,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 44/1989 [00:18<14:03,  2.31batch/s]ch/s]
siglip2 videos:   2%|▏         | 45/1989 [00:19<13:59,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 46/1989 [00:19<13:58,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 47/1989 [00:20<14:00,  2.31batch/s]ch/s]
siglip2 videos:   2%|▏         | 48/1989 [00:20<13:55,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 49/1989 [00:20<13:55,  2.32batch/s]ch/s]
siglip2 videos:   3%|▎         | 50/1989 [00:21<13:59,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 51/1989 [00:21<14:02,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 52/1989 [00:22<13:58,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 53/1989 [00:22<14:00,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 54/1989 [00:23<14:01,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 55/1989 [00:23<13:59,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 56/1989 [00:24<14:02,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 57/1989 [00:24<14:02,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 58/1989 [00:24<14:02,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 59/1989 [00:25<14:02,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 60/1989 [00:25<14:01,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 61/1989 [00:26<13:56,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 62/1989 [00:26<13:56,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 63/1989 [00:27<14:00,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 64/1989 [00:27<14:00,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 65/1989 [00:27<13:58,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 66/1989 [00:28<14:03,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 67/1989 [00:28<14:06,  2.27batch/s]ch/s]
siglip2 videos:   3%|▎         | 68/1989 [00:29<14:04,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 69/1989 [00:29<14:03,  2.28batch/s]ch/s]
siglip2 videos:   4%|▎         | 70/1989 [00:30<14:08,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 71/1989 [00:30<14:06,  2.27batch/s]ch/s]
siglip2 videos:   4%|▎         | 72/1989 [00:31<14:03,  2.27batch/s]ch/s]
siglip2 videos:   4%|▎         | 73/1989 [00:31<14:05,  2.27batch/s]ch/s]
siglip2 videos:   4%|▎         | 74/1989 [00:31<14:07,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 75/1989 [00:32<14:06,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 76/1989 [00:32<14:05,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 77/1989 [00:33<14:06,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 78/1989 [00:33<14:11,  2.24batch/s]ch/s]
siglip2 videos:   4%|▍         | 79/1989 [00:34<14:10,  2.24batch/s]ch/s]
siglip2 videos:   4%|▍         | 80/1989 [00:34<14:08,  2.25batch/s]ch/s]
siglip2 videos:   4%|▍         | 81/1989 [00:35<14:11,  2.24batch/s]ch/s]
siglip2 videos:   4%|▍         | 82/1989 [00:35<14:13,  2.24batch/s]ch/s]
siglip2 videos:   4%|▍         | 83/1989 [00:35<14:13,  2.23batch/s]ch/s]
siglip2 videos:   4%|▍         | 84/1989 [00:36<14:11,  2.24batch/s]ch/s]
siglip2 videos:   4%|▍         | 85/1989 [00:36<14:12,  2.23batch/s]ch/s]
siglip2 videos:   4%|▍         | 86/1989 [00:37<14:13,  2.23batch/s]ch/s]
siglip2 videos:   4%|▍         | 87/1989 [00:37<14:02,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 88/1989 [00:38<14:00,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 89/1989 [00:38<14:00,  2.26batch/s]ch/s]
siglip2 videos:   5%|▍         | 90/1989 [00:39<14:01,  2.26batch/s]ch/s]
siglip2 videos:   5%|▍         | 91/1989 [00:39<14:04,  2.25batch/s]ch/s]
siglip2 videos:   5%|▍         | 92/1989 [00:39<14:04,  2.25batch/s]ch/s]
siglip2 videos:   5%|▍         | 93/1989 [00:40<14:05,  2.24batch/s]ch/s]
siglip2 videos:   5%|▍         | 94/1989 [00:40<14:09,  2.23batch/s]ch/s]
siglip2 videos:   5%|▍         | 95/1989 [00:41<14:11,  2.22batch/s]ch/s]
siglip2 videos:   5%|▍         | 96/1989 [00:41<14:12,  2.22batch/s]ch/s]
siglip2 videos:   5%|▍         | 97/1989 [00:42<14:08,  2.23batch/s]ch/s]
siglip2 videos:   5%|▍         | 98/1989 [00:42<14:09,  2.23batch/s]ch/s]
siglip2 videos:   5%|▍         | 99/1989 [00:43<14:08,  2.23batch/s]ch/s]
siglip2 videos:   5%|▌         | 100/1989 [00:43<14:06,  2.23batch/s]h/s]
siglip2 videos:   5%|▌         | 101/1989 [00:43<14:07,  2.23batch/s]h/s]
siglip2 videos:   5%|▌         | 102/1989 [00:44<14:06,  2.23batch/s]h/s]
siglip2 videos:   5%|▌         | 103/1989 [00:44<14:07,  2.23batch/s]h/s]
siglip2 videos:   5%|▌         | 104/1989 [00:45<14:08,  2.22batch/s]h/s]
siglip2 videos:   5%|▌         | 105/1989 [00:45<14:10,  2.21batch/s]h/s]
siglip2 videos:   5%|▌         | 106/1989 [00:46<14:09,  2.22batch/s]h/s]
siglip2 videos:   5%|▌         | 107/1989 [00:46<14:08,  2.22batch/s]h/s]
siglip2 videos:   5%|▌         | 108/1989 [00:47<14:11,  2.21batch/s]h/s]
siglip2 videos:   5%|▌         | 109/1989 [00:47<14:10,  2.21batch/s]h/s]
siglip2 videos:   6%|▌         | 110/1989 [00:48<14:12,  2.21batch/s]h/s]
siglip2 videos:   6%|▌         | 111/1989 [00:48<14:10,  2.21batch/s]h/s]
siglip2 videos:   6%|▌         | 112/1989 [00:48<14:09,  2.21batch/s]h/s]
siglip2 videos:   6%|▌         | 113/1989 [00:49<14:05,  2.22batch/s]h/s]
siglip2 videos:   6%|▌         | 114/1989 [00:49<14:05,  2.22batch/s]h/s]
siglip2 videos:   6%|▌         | 115/1989 [00:50<14:08,  2.21batch/s]h/s]
siglip2 videos:   6%|▌         | 116/1989 [00:50<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 117/1989 [00:51<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 118/1989 [00:51<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 119/1989 [00:52<14:11,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 120/1989 [00:52<14:12,  2.19batch/s]h/s]
siglip2 videos:   6%|▌         | 121/1989 [00:53<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 122/1989 [00:53<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 123/1989 [00:53<14:09,  2.20batch/s]h/s]
siglip2 videos:   6%|▌         | 124/1989 [00:54<14:08,  2.20batch/s]h/s]
siglip2 videos:   6%|▋         | 125/1989 [00:54<14:08,  2.20batch/s]h/s]
siglip2 videos:   6%|▋         | 126/1989 [00:55<14:12,  2.19batch/s]h/s]
siglip2 videos:   6%|▋         | 127/1989 [00:55<14:13,  2.18batch/s]h/s]
siglip2 videos:   6%|▋         | 128/1989 [00:56<14:16,  2.17batch/s]h/s]
siglip2 videos:   6%|▋         | 129/1989 [00:56<14:15,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 130/1989 [00:57<14:14,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 131/1989 [00:57<14:12,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 132/1989 [00:58<14:16,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 133/1989 [00:58<14:15,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 134/1989 [00:59<14:12,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 135/1989 [00:59<14:13,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 136/1989 [00:59<14:12,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 137/1989 [01:00<14:12,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 138/1989 [01:00<14:10,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 139/1989 [01:01<14:09,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 140/1989 [01:01<14:07,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 141/1989 [01:02<14:06,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 142/1989 [01:02<14:03,  2.19batch/s]h/s]
siglip2 videos:   7%|▋         | 143/1989 [01:03<14:05,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 144/1989 [01:03<14:07,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 145/1989 [01:04<14:05,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 146/1989 [01:04<14:07,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 147/1989 [01:04<14:05,  2.18batch/s]h/s]
siglip2 videos:   7%|▋         | 148/1989 [01:05<14:09,  2.17batch/s]h/s]
siglip2 videos:   7%|▋         | 149/1989 [01:05<14:06,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 150/1989 [01:06<14:07,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 151/1989 [01:06<14:06,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 152/1989 [01:07<14:07,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 153/1989 [01:07<14:03,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 154/1989 [01:08<14:01,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 155/1989 [01:08<14:02,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 156/1989 [01:09<14:01,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 157/1989 [01:09<14:00,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 158/1989 [01:10<14:03,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 159/1989 [01:10<14:03,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 160/1989 [01:10<14:00,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 161/1989 [01:11<13:59,  2.18batch/s]h/s]
siglip2 videos:   8%|▊         | 162/1989 [01:11<14:02,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 163/1989 [01:12<14:05,  2.16batch/s]h/s]
siglip2 videos:   8%|▊         | 164/1989 [01:12<14:05,  2.16batch/s]h/s]
siglip2 videos:   8%|▊         | 165/1989 [01:13<14:03,  2.16batch/s]h/s]
siglip2 videos:   8%|▊         | 166/1989 [01:13<14:01,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 167/1989 [01:14<13:59,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 168/1989 [01:14<14:00,  2.17batch/s]h/s]
siglip2 videos:   8%|▊         | 169/1989 [01:15<13:59,  2.17batch/s]h/s]
siglip2 videos:   9%|▊         | 170/1989 [01:15<13:57,  2.17batch/s]h/s]
siglip2 videos:   9%|▊         | 171/1989 [01:16<13:58,  2.17batch/s]h/s]
siglip2 videos:   9%|▊         | 172/1989 [01:16<13:58,  2.17batch/s]h/s]
siglip2 videos:   9%|▊         | 173/1989 [01:16<13:58,  2.17batch/s]h/s]
siglip2 videos:   9%|▊         | 174/1989 [01:17<13:58,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 175/1989 [01:17<13:56,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 176/1989 [01:18<13:59,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 177/1989 [01:18<13:56,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 178/1989 [01:19<13:54,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 179/1989 [01:19<13:52,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 180/1989 [01:20<13:53,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 181/1989 [01:20<13:55,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 182/1989 [01:21<13:56,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 183/1989 [01:21<13:57,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 184/1989 [01:22<13:57,  2.15batch/s]h/s]
siglip2 videos:   9%|▉         | 185/1989 [01:22<13:55,  2.16batch/s]h/s]
siglip2 videos:   9%|▉         | 186/1989 [01:22<13:51,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 187/1989 [01:23<13:52,  2.17batch/s]h/s]
siglip2 videos:   9%|▉         | 188/1989 [01:23<13:51,  2.17batch/s]h/s]
siglip2 videos:  10%|▉         | 189/1989 [01:24<13:50,  2.17batch/s]h/s]
siglip2 videos:  10%|▉         | 190/1989 [01:24<13:48,  2.17batch/s]h/s]
siglip2 videos:  10%|▉         | 191/1989 [01:25<13:50,  2.16batch/s]h/s]
siglip2 videos:  10%|▉         | 192/1989 [01:25<13:50,  2.16batch/s]h/s]
siglip2 videos:  10%|▉         | 193/1989 [01:26<13:53,  2.15batch/s]h/s]
siglip2 videos:  10%|▉         | 194/1989 [01:26<13:51,  2.16batch/s]h/s]
siglip2 videos:  10%|▉         | 195/1989 [01:27<13:55,  2.15batch/s]h/s]
siglip2 videos:  10%|▉         | 196/1989 [01:27<13:55,  2.15batch/s]h/s]
siglip2 videos:  10%|▉         | 197/1989 [01:28<13:57,  2.14batch/s]h/s]
siglip2 videos:  10%|▉         | 198/1989 [01:28<13:53,  2.15batch/s]h/s]
siglip2 videos:  10%|█         | 199/1989 [01:29<13:51,  2.15batch/s]h/s]
siglip2 videos:  10%|█         | 200/1989 [01:29<13:52,  2.15batch/s]h/s]
siglip2 videos:  10%|█         | 201/1989 [01:29<13:49,  2.15batch/s]h/s]
siglip2 videos:  10%|█         | 202/1989 [01:30<13:48,  2.16batch/s]h/s]
siglip2 videos:  10%|█         | 203/1989 [01:30<13:47,  2.16batch/s]h/s]
siglip2 videos:  10%|█         | 204/1989 [01:31<13:48,  2.15batch/s]h/s]
siglip2 videos:  10%|█         | 205/1989 [01:31<13:54,  2.14batch/s]h/s]
siglip2 videos:  10%|█         | 206/1989 [01:32<13:55,  2.13batch/s]h/s]
siglip2 videos:  10%|█         | 207/1989 [01:32<13:52,  2.14batch/s]h/s]
siglip2 videos:  10%|█         | 208/1989 [01:33<13:54,  2.13batch/s]h/s]
siglip2 videos:  11%|█         | 209/1989 [01:33<13:51,  2.14batch/s]h/s]
siglip2 videos:  11%|█         | 210/1989 [01:34<13:49,  2.14batch/s]h/s]
siglip2 videos:  11%|█         | 211/1989 [01:34<13:49,  2.14batch/s]h/s]
siglip2 videos:  11%|█         | 212/1989 [01:35<13:48,  2.14batch/s]h/s]
siglip2 videos:  11%|█         | 213/1989 [01:35<14:24,  2.05batch/s]h/s]
siglip2 videos:  11%|█         | 214/1989 [01:36<14:47,  2.00batch/s]h/s]
pe_core_l14 videos:  31%|███▏      | 625/1989 [03:28<08:44,  2.60batch/s]
siglip2 videos:  11%|█         | 215/1989 [01:36<14:30,  2.04batch/s]h/s]
siglip2 videos:  11%|█         | 216/1989 [01:37<14:19,  2.06batch/s]h/s]
siglip2 videos:  11%|█         | 217/1989 [01:37<14:09,  2.09batch/s]h/s]
siglip2 videos:  11%|█         | 218/1989 [01:38<14:32,  2.03batch/s]h/s]
siglip2 videos:  11%|█         | 219/1989 [01:38<14:37,  2.02batch/s]h/s]
pe_core_l14 videos:  32%|███▏      | 631/1989 [03:30<08:18,  2.73batch/s]
siglip2 videos:  11%|█         | 220/1989 [01:39<14:24,  2.05batch/s]h/s]
siglip2 videos:  11%|█         | 221/1989 [01:39<14:12,  2.07batch/s]h/s]
siglip2 videos:  11%|█         | 222/1989 [01:39<14:03,  2.10batch/s]h/s]
siglip2 videos:  11%|█         | 223/1989 [01:40<13:57,  2.11batch/s]h/s]
siglip2 videos:  11%|█▏        | 224/1989 [01:40<13:49,  2.13batch/s]h/s]
siglip2 videos:  11%|█▏        | 225/1989 [01:41<13:47,  2.13batch/s]h/s]
siglip2 videos:  11%|█▏        | 226/1989 [01:41<13:46,  2.13batch/s]h/s]
siglip2 videos:  11%|█▏        | 227/1989 [01:42<13:46,  2.13batch/s]h/s]
siglip2 videos:  11%|█▏        | 228/1989 [01:42<13:42,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 229/1989 [01:43<13:40,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 230/1989 [01:43<13:42,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 231/1989 [01:44<13:45,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 232/1989 [01:44<13:45,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 233/1989 [01:45<13:46,  2.12batch/s]h/s]
siglip2 videos:  12%|█▏        | 234/1989 [01:45<13:42,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 235/1989 [01:46<13:41,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 236/1989 [01:46<13:43,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 237/1989 [01:47<13:43,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 238/1989 [01:47<13:42,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 239/1989 [01:47<13:41,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 240/1989 [01:48<13:36,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 241/1989 [01:48<13:34,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 242/1989 [01:49<13:35,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 243/1989 [01:49<13:35,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 244/1989 [01:50<13:37,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 245/1989 [01:50<13:36,  2.14batch/s]h/s]
siglip2 videos:  12%|█▏        | 246/1989 [01:51<13:37,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 247/1989 [01:51<13:38,  2.13batch/s]h/s]
siglip2 videos:  12%|█▏        | 248/1989 [01:52<13:36,  2.13batch/s]h/s]
siglip2 videos:  13%|█▎        | 249/1989 [01:52<13:40,  2.12batch/s]h/s]
siglip2 videos:  13%|█▎        | 250/1989 [01:53<13:54,  2.08batch/s]h/s]
siglip2 videos:  13%|█▎        | 251/1989 [01:53<14:16,  2.03batch/s]h/s]
pe_core_l14 videos:  33%|███▎      | 664/1989 [03:46<08:18,  2.66batch/s]
siglip2 videos:  13%|█▎        | 252/1989 [01:54<14:02,  2.06batch/s]h/s]
siglip2 videos:  13%|█▎        | 253/1989 [01:54<13:57,  2.07batch/s]h/s]
siglip2 videos:  13%|█▎        | 254/1989 [01:55<13:51,  2.09batch/s]h/s]
siglip2 videos:  13%|█▎        | 255/1989 [01:55<13:49,  2.09batch/s]h/s]
siglip2 videos:  13%|█▎        | 256/1989 [01:56<13:44,  2.10batch/s]h/s]
siglip2 videos:  13%|█▎        | 257/1989 [01:56<13:39,  2.11batch/s]h/s]
siglip2 videos:  13%|█▎        | 258/1989 [01:56<13:34,  2.12batch/s]h/s]
siglip2 videos:  13%|█▎        | 259/1989 [01:57<13:38,  2.11batch/s]h/s]
siglip2 videos:  13%|█▎        | 260/1989 [01:57<13:38,  2.11batch/s]h/s]
siglip2 videos:  13%|█▎        | 261/1989 [01:58<13:36,  2.12batch/s]h/s]
siglip2 videos:  13%|█▎        | 262/1989 [01:58<13:37,  2.11batch/s]h/s]
siglip2 videos:  13%|█▎        | 263/1989 [01:59<13:30,  2.13batch/s]h/s]
siglip2 videos:  13%|█▎        | 264/1989 [01:59<13:31,  2.13batch/s]h/s]
siglip2 videos:  13%|█▎        | 265/1989 [02:00<13:35,  2.12batch/s]h/s]

-- mean: R1 63.20  mAP 75.02  mINP 75.02
-- mean_s8: R1 63.20  mAP 75.02  mINP 75.02
-- max: R1 63.10  mAP 74.89  mINP 74.89
-- query_max: R1 64.90  mAP 76.24  mINP 76.24
== Perception Encoder L/14 | activitynet/sentence | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos:  67%|██████▋   | 1325/1989 [10:42<06:07,  1.81batch/s]
pe_core_l14 texts:   1%|▏         | 3/227 [00:00<00:08, 26.94batch/s]
pe_core_l14 texts:   3%|▎         | 7/227 [00:00<00:07, 29.95batch/s]
pe_core_l14 texts:   5%|▍         | 11/227 [00:00<00:06, 31.61batch/s]
siglip2 videos:  67%|██████▋   | 1326/1989 [10:43<05:49,  1.90batch/s]
pe_core_l14 texts:   8%|▊         | 19/227 [00:00<00:06, 33.77batch/s]
pe_core_l14 texts:  10%|█         | 23/227 [00:00<00:05, 35.50batch/s]
pe_core_l14 texts:  12%|█▏        | 27/227 [00:00<00:05, 36.14batch/s]
siglip2 videos:  67%|██████▋   | 1327/1989 [10:43<05:37,  1.96batch/s]
pe_core_l14 texts:  15%|█▌        | 35/227 [00:01<00:05, 36.65batch/s]
pe_core_l14 texts:  17%|█▋        | 39/227 [00:01<00:05, 36.51batch/s]
pe_core_l14 texts:  19%|█▉        | 43/227 [00:01<00:04, 37.07batch/s]
pe_core_l14 texts:  21%|██        | 47/227 [00:01<00:04, 37.32batch/s]
siglip2 videos:  67%|██████▋   | 1328/1989 [10:44<05:28,  2.01batch/s]
pe_core_l14 texts:  24%|██▍       | 55/227 [00:01<00:04, 36.54batch/s]
pe_core_l14 texts:  26%|██▋       | 60/227 [00:01<00:04, 37.71batch/s]
pe_core_l14 texts:  28%|██▊       | 64/227 [00:01<00:04, 37.70batch/s]
siglip2 videos:  67%|██████▋   | 1329/1989 [10:44<05:21,  2.06batch/s]
pe_core_l14 texts:  32%|███▏      | 72/227 [00:01<00:04, 36.41batch/s]
pe_core_l14 texts:  33%|███▎      | 76/227 [00:02<00:04, 37.39batch/s]
pe_core_l14 texts:  35%|███▌      | 80/227 [00:02<00:03, 37.45batch/s]
siglip2 videos:  67%|██████▋   | 1330/1989 [10:44<05:16,  2.08batch/s]
pe_core_l14 texts:  39%|███▉      | 88/227 [00:02<00:03, 36.01batch/s]
pe_core_l14 texts:  41%|████      | 92/227 [00:02<00:03, 36.59batch/s]
pe_core_l14 texts:  42%|████▏     | 96/227 [00:02<00:03, 33.09batch/s]
siglip2 videos:  67%|██████▋   | 1331/1989 [10:45<05:15,  2.09batch/s]]
pe_core_l14 texts:  46%|████▌     | 104/227 [00:02<00:03, 34.47batch/s]
pe_core_l14 texts:  48%|████▊     | 109/227 [00:03<00:03, 36.51batch/s]
pe_core_l14 texts:  50%|████▉     | 113/227 [00:03<00:03, 36.66batch/s]
siglip2 videos:  67%|██████▋   | 1332/1989 [10:45<05:13,  2.10batch/s]]
pe_core_l14 texts:  53%|█████▎    | 121/227 [00:03<00:02, 36.63batch/s]
pe_core_l14 texts:  55%|█████▌    | 125/227 [00:03<00:02, 36.49batch/s]
pe_core_l14 texts:  57%|█████▋    | 129/227 [00:03<00:02, 36.98batch/s]
siglip2 videos:  67%|██████▋   | 1333/1989 [10:46<05:11,  2.10batch/s]]
pe_core_l14 texts:  60%|██████    | 137/227 [00:03<00:02, 37.01batch/s]
pe_core_l14 texts:  62%|██████▏   | 141/227 [00:03<00:02, 33.79batch/s]
pe_core_l14 texts:  64%|██████▍   | 145/227 [00:04<00:02, 35.25batch/s]
pe_core_l14 texts:  66%|██████▌   | 149/227 [00:04<00:02, 35.38batch/s]
siglip2 videos:  67%|██████▋   | 1334/1989 [10:46<05:11,  2.10batch/s]]
pe_core_l14 texts:  69%|██████▉   | 157/227 [00:04<00:01, 35.94batch/s]
pe_core_l14 texts:  71%|███████▏  | 162/227 [00:04<00:01, 37.23batch/s]
pe_core_l14 texts:  73%|███████▎  | 166/227 [00:04<00:01, 36.95batch/s]
siglip2 videos:  67%|██████▋   | 1335/1989 [10:47<05:08,  2.12batch/s]]
pe_core_l14 texts:  77%|███████▋  | 174/227 [00:04<00:01, 36.69batch/s]
pe_core_l14 texts:  79%|███████▉  | 179/227 [00:04<00:01, 37.74batch/s]
pe_core_l14 texts:  81%|████████  | 183/227 [00:05<00:01, 37.75batch/s]
siglip2 videos:  67%|██████▋   | 1336/1989 [10:47<05:07,  2.12batch/s]]
pe_core_l14 texts:  84%|████████▍ | 191/227 [00:05<00:00, 36.65batch/s]
pe_core_l14 texts:  86%|████████▌ | 195/227 [00:05<00:00, 37.55batch/s]
pe_core_l14 texts:  88%|████████▊ | 199/227 [00:05<00:00, 36.38batch/s]
siglip2 videos:  67%|██████▋   | 1337/1989 [10:48<05:06,  2.13batch/s]]
pe_core_l14 texts:  92%|█████████▏| 208/227 [00:05<00:00, 35.36batch/s]
pe_core_l14 texts:  93%|█████████▎| 212/227 [00:05<00:00, 35.18batch/s]
pe_core_l14 texts:  95%|█████████▌| 216/227 [00:05<00:00, 35.34batch/s]
siglip2 videos:  67%|██████▋   | 1338/1989 [10:48<05:06,  2.12batch/s]]
pe_core_l14 texts: 100%|██████████| 227/227 [00:06<00:00, 36.22batch/s]
siglip2 videos:  69%|██████▊   | 1365/1989 [11:03<06:52,  1.51batch/s]

-- mean: R1 37.30  mAP 50.25  mINP 50.25
-- mean_s8: R1 37.30  mAP 50.25  mINP 50.25
-- max: R1 37.43  mAP 50.27  mINP 50.27
-- query_max: R1 37.79  mAP 50.94  mINP 50.94
== Perception Encoder L/14 | activitynet/paragraph | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  91%|█████████ | 1814/1989 [14:36<01:22,  2.12batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos:  91%|█████████▏| 1815/1989 [14:37<01:23,  2.08batch/s]
pe_core_l14 videos:   0%|          | 0/6902 [00:00<?, ?batch/s]
siglip2 videos:  91%|█████████▏| 1816/1989 [14:37<01:28,  1.96batch/s]]
siglip2 videos:  91%|█████████▏| 1817/1989 [14:38<01:26,  1.99batch/s]]
pe_core_l14 videos:   0%|          | 3/6902 [00:00<33:39,  3.42batch/s]
siglip2 videos:  91%|█████████▏| 1818/1989 [14:38<01:25,  2.00batch/s]]
pe_core_l14 videos:   0%|          | 5/6902 [00:01<30:19,  3.79batch/s]
siglip2 videos:  91%|█████████▏| 1819/1989 [14:39<01:24,  2.01batch/s]]
pe_core_l14 videos:   0%|          | 7/6902 [00:01<29:09,  3.94batch/s]
siglip2 videos:  92%|█████████▏| 1820/1989 [14:39<01:23,  2.03batch/s]]
pe_core_l14 videos:   0%|          | 9/6902 [00:02<28:24,  4.04batch/s]
siglip2 videos:  92%|█████████▏| 1821/1989 [14:40<01:22,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 11/6902 [00:02<28:06,  4.09batch/s]
siglip2 videos:  92%|█████████▏| 1822/1989 [14:40<01:22,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 13/6902 [00:03<28:15,  4.06batch/s]
siglip2 videos:  92%|█████████▏| 1823/1989 [14:41<01:22,  2.02batch/s]s]
pe_core_l14 videos:   0%|          | 15/6902 [00:03<28:19,  4.05batch/s]
siglip2 videos:  92%|█████████▏| 1824/1989 [14:41<01:21,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 17/6902 [00:04<28:07,  4.08batch/s]
siglip2 videos:  92%|█████████▏| 1825/1989 [14:42<01:20,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 19/6902 [00:04<28:02,  4.09batch/s]
siglip2 videos:  92%|█████████▏| 1826/1989 [14:42<01:19,  2.04batch/s]s]
pe_core_l14 videos:   0%|          | 21/6902 [00:05<27:55,  4.11batch/s]
siglip2 videos:  92%|█████████▏| 1827/1989 [14:43<01:19,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 23/6902 [00:05<28:03,  4.09batch/s]
siglip2 videos:  92%|█████████▏| 1828/1989 [14:43<01:19,  2.03batch/s]s]
pe_core_l14 videos:   0%|          | 25/6902 [00:06<28:01,  4.09batch/s]
siglip2 videos:  92%|█████████▏| 1829/1989 [14:44<01:18,  2.04batch/s]s]
pe_core_l14 videos:   0%|          | 27/6902 [00:06<28:04,  4.08batch/s]
siglip2 videos:  92%|█████████▏| 1830/1989 [14:44<01:18,  2.04batch/s]s]
pe_core_l14 videos:   0%|          | 29/6902 [00:07<28:01,  4.09batch/s]
siglip2 videos:  92%|█████████▏| 1831/1989 [14:45<01:17,  2.05batch/s]s]
pe_core_l14 videos:   0%|          | 31/6902 [00:07<27:42,  4.13batch/s]
siglip2 videos:  92%|█████████▏| 1832/1989 [14:45<01:16,  2.05batch/s]s]
pe_core_l14 videos:   0%|          | 33/6902 [00:08<27:50,  4.11batch/s]
siglip2 videos:  92%|█████████▏| 1833/1989 [14:45<01:16,  2.04batch/s]s]
pe_core_l14 videos:   1%|          | 35/6902 [00:08<27:52,  4.11batch/s]
siglip2 videos:  92%|█████████▏| 1834/1989 [14:46<01:15,  2.06batch/s]s]
pe_core_l14 videos:   1%|          | 37/6902 [00:09<27:37,  4.14batch/s]
siglip2 videos:  92%|█████████▏| 1835/1989 [14:46<01:14,  2.06batch/s]s]
pe_core_l14 videos:   1%|          | 39/6902 [00:09<27:37,  4.14batch/s]
siglip2 videos:  92%|█████████▏| 1836/1989 [14:47<01:14,  2.06batch/s]s]
pe_core_l14 videos:   1%|          | 41/6902 [00:10<27:30,  4.16batch/s]
siglip2 videos:  92%|█████████▏| 1837/1989 [14:47<01:13,  2.06batch/s]s]
pe_core_l14 videos:   1%|          | 43/6902 [00:10<27:32,  4.15batch/s]
siglip2 videos:  92%|█████████▏| 1838/1989 [14:48<01:13,  2.05batch/s]s]
pe_core_l14 videos:   1%|          | 45/6902 [00:11<27:45,  4.12batch/s]
siglip2 videos:  92%|█████████▏| 1839/1989 [14:48<01:13,  2.04batch/s]s]
pe_core_l14 videos:   1%|          | 47/6902 [00:11<28:01,  4.08batch/s]
siglip2 videos:  93%|█████████▎| 1840/1989 [14:49<01:12,  2.05batch/s]s]
pe_core_l14 videos:   1%|          | 49/6902 [00:12<27:43,  4.12batch/s]
siglip2 videos:  93%|█████████▎| 1841/1989 [14:49<01:12,  2.05batch/s]s]
pe_core_l14 videos:   1%|          | 51/6902 [00:12<27:47,  4.11batch/s]
siglip2 videos:  93%|█████████▎| 1842/1989 [14:50<01:11,  2.06batch/s]s]
pe_core_l14 videos:   1%|          | 53/6902 [00:13<27:37,  4.13batch/s]
siglip2 videos:  93%|█████████▎| 1843/1989 [14:50<01:12,  2.01batch/s]s]
pe_core_l14 videos:   1%|          | 55/6902 [00:13<28:29,  4.01batch/s]
siglip2 videos:  93%|█████████▎| 1844/1989 [14:51<01:11,  2.02batch/s]s]
pe_core_l14 videos:   1%|          | 57/6902 [00:14<28:05,  4.06batch/s]
siglip2 videos:  93%|█████████▎| 1845/1989 [14:51<01:12,  1.99batch/s]s]
pe_core_l14 videos:   1%|          | 59/6902 [00:14<28:35,  3.99batch/s]
siglip2 videos:  93%|█████████▎| 1846/1989 [14:52<01:11,  2.00batch/s]s]
pe_core_l14 videos:   1%|          | 61/6902 [00:15<28:16,  4.03batch/s]
siglip2 videos:  93%|█████████▎| 1847/1989 [14:52<01:12,  1.97batch/s]s]
pe_core_l14 videos:   1%|          | 63/6902 [00:15<28:54,  3.94batch/s]
siglip2 videos:  93%|█████████▎| 1848/1989 [14:53<01:10,  1.99batch/s]s]
pe_core_l14 videos:   1%|          | 65/6902 [00:16<28:29,  4.00batch/s]
siglip2 videos:  93%|█████████▎| 1849/1989 [14:53<01:10,  1.97batch/s]s]
pe_core_l14 videos:   1%|          | 67/6902 [00:16<28:43,  3.97batch/s]
siglip2 videos:  93%|█████████▎| 1850/1989 [14:54<01:11,  1.95batch/s]s]
pe_core_l14 videos:   1%|          | 69/6902 [00:17<29:11,  3.90batch/s]
siglip2 videos:  93%|█████████▎| 1851/1989 [14:54<01:09,  1.98batch/s]s]
pe_core_l14 videos:   1%|          | 71/6902 [00:17<28:31,  3.99batch/s]
siglip2 videos:  93%|█████████▎| 1852/1989 [14:55<01:09,  1.97batch/s]s]
pe_core_l14 videos:   1%|          | 73/6902 [00:18<28:52,  3.94batch/s]
siglip2 videos:  93%|█████████▎| 1853/1989 [14:55<01:08,  1.97batch/s]s]
pe_core_l14 videos:   1%|          | 75/6902 [00:18<28:39,  3.97batch/s]
siglip2 videos:  93%|█████████▎| 1854/1989 [14:56<01:07,  1.99batch/s]s]
pe_core_l14 videos:   1%|          | 77/6902 [00:19<28:15,  4.02batch/s]
siglip2 videos:  93%|█████████▎| 1855/1989 [14:56<01:06,  2.01batch/s]s]
pe_core_l14 videos:   1%|          | 79/6902 [00:19<27:52,  4.08batch/s]
siglip2 videos:  93%|█████████▎| 1856/1989 [14:57<01:05,  2.02batch/s]s]
pe_core_l14 videos:   1%|          | 81/6902 [00:20<27:52,  4.08batch/s]
siglip2 videos:  93%|█████████▎| 1857/1989 [14:57<01:06,  1.99batch/s]s]
pe_core_l14 videos:   1%|          | 83/6902 [00:20<28:23,  4.00batch/s]
siglip2 videos:  93%|█████████▎| 1858/1989 [14:58<01:06,  1.97batch/s]s]
pe_core_l14 videos:   1%|          | 85/6902 [00:21<28:53,  3.93batch/s]
siglip2 videos:  93%|█████████▎| 1859/1989 [14:58<01:06,  1.97batch/s]s]
siglip2 videos:  94%|█████████▎| 1860/1989 [14:59<01:04,  2.00batch/s]s]
pe_core_l14 videos:   1%|▏         | 88/6902 [00:22<33:30,  3.39batch/s]
siglip2 videos:  94%|█████████▎| 1861/1989 [14:59<01:05,  1.96batch/s]s]
pe_core_l14 videos:   1%|▏         | 90/6902 [00:22<31:40,  3.59batch/s]
siglip2 videos:  94%|█████████▎| 1862/1989 [15:00<01:05,  1.95batch/s]s]
pe_core_l14 videos:   1%|▏         | 92/6902 [00:23<30:13,  3.75batch/s]
siglip2 videos:  94%|█████████▎| 1863/1989 [15:00<01:03,  1.98batch/s]s]
siglip2 videos:  94%|█████████▎| 1864/1989 [15:01<01:02,  2.01batch/s]s]
pe_core_l14 videos:   1%|▏         | 95/6902 [00:24<33:34,  3.38batch/s]
siglip2 videos:  94%|█████████▍| 1865/1989 [15:01<01:01,  2.01batch/s]s]
pe_core_l14 videos:   1%|▏         | 97/6902 [00:24<30:47,  3.68batch/s]
siglip2 videos:  94%|█████████▍| 1866/1989 [15:02<01:01,  1.99batch/s]s]
siglip2 videos:  94%|█████████▍| 1867/1989 [15:02<01:00,  2.00batch/s]s]
pe_core_l14 videos:   1%|▏         | 100/6902 [00:25<34:43,  3.26batch/s]
siglip2 videos:  94%|█████████▍| 1868/1989 [15:03<01:01,  1.97batch/s]/s]
pe_core_l14 videos:   1%|▏         | 102/6902 [00:26<32:03,  3.54batch/s]
siglip2 videos:  94%|█████████▍| 1869/1989 [15:03<01:00,  1.99batch/s]/s]
pe_core_l14 videos:   2%|▏         | 104/6902 [00:26<29:51,  3.79batch/s]
siglip2 videos:  94%|█████████▍| 1870/1989 [15:04<01:00,  1.97batch/s]/s]
pe_core_l14 videos:   2%|▏         | 106/6902 [00:27<29:30,  3.84batch/s]
siglip2 videos:  94%|█████████▍| 1871/1989 [15:05<01:01,  1.93batch/s]/s]
pe_core_l14 videos:   2%|▏         | 108/6902 [00:27<29:49,  3.80batch/s]
siglip2 videos:  94%|█████████▍| 1872/1989 [15:05<01:01,  1.91batch/s]/s]
pe_core_l14 videos:   2%|▏         | 110/6902 [00:28<29:58,  3.78batch/s]
siglip2 videos:  94%|█████████▍| 1873/1989 [15:06<01:00,  1.93batch/s]/s]
pe_core_l14 videos:   2%|▏         | 112/6902 [00:28<29:12,  3.87batch/s]
siglip2 videos:  94%|█████████▍| 1874/1989 [15:06<00:59,  1.94batch/s]/s]
pe_core_l14 videos:   2%|▏         | 114/6902 [00:29<28:48,  3.93batch/s]
siglip2 videos:  94%|█████████▍| 1875/1989 [15:07<01:00,  1.89batch/s]/s]
pe_core_l14 videos:   2%|▏         | 116/6902 [00:29<29:53,  3.78batch/s]
siglip2 videos:  94%|█████████▍| 1876/1989 [15:07<01:00,  1.87batch/s]/s]
pe_core_l14 videos:   2%|▏         | 118/6902 [00:30<30:25,  3.72batch/s]
siglip2 videos:  94%|█████████▍| 1877/1989 [15:08<00:59,  1.90batch/s]/s]
siglip2 videos:  94%|█████████▍| 1878/1989 [15:08<00:57,  1.93batch/s]/s]
pe_core_l14 videos:   2%|▏         | 121/6902 [00:31<34:05,  3.32batch/s]
siglip2 videos:  94%|█████████▍| 1879/1989 [15:09<00:56,  1.95batch/s]/s]
pe_core_l14 videos:   2%|▏         | 123/6902 [00:32<31:04,  3.64batch/s]
siglip2 videos:  95%|█████████▍| 1880/1989 [15:09<00:56,  1.95batch/s]/s]
pe_core_l14 videos:   2%|▏         | 125/6902 [00:32<30:02,  3.76batch/s]
siglip2 videos:  95%|█████████▍| 1881/1989 [15:10<00:55,  1.95batch/s]/s]
pe_core_l14 videos:   2%|▏         | 127/6902 [00:33<29:10,  3.87batch/s]
siglip2 videos:  95%|█████████▍| 1882/1989 [15:10<00:54,  1.98batch/s]/s]
pe_core_l14 videos:   2%|▏         | 129/6902 [00:33<28:15,  3.99batch/s]
siglip2 videos:  95%|█████████▍| 1883/1989 [15:11<00:55,  1.92batch/s]/s]
pe_core_l14 videos:   2%|▏         | 131/6902 [00:34<29:36,  3.81batch/s]
siglip2 videos:  95%|█████████▍| 1884/1989 [15:11<00:54,  1.92batch/s]/s]
pe_core_l14 videos:   2%|▏         | 133/6902 [00:34<29:15,  3.86batch/s]
siglip2 videos:  95%|█████████▍| 1885/1989 [15:12<00:55,  1.89batch/s]/s]
pe_core_l14 videos:   2%|▏         | 135/6902 [00:35<29:47,  3.78batch/s]
siglip2 videos:  95%|█████████▍| 1886/1989 [15:12<00:55,  1.86batch/s]/s]
pe_core_l14 videos:   2%|▏         | 137/6902 [00:35<30:16,  3.72batch/s]
siglip2 videos:  95%|█████████▍| 1887/1989 [15:13<00:53,  1.90batch/s]/s]
pe_core_l14 videos:   2%|▏         | 139/6902 [00:36<29:16,  3.85batch/s]
siglip2 videos:  95%|█████████▍| 1888/1989 [15:13<00:52,  1.92batch/s]/s]
pe_core_l14 videos:   2%|▏         | 141/6902 [00:36<28:52,  3.90batch/s]
siglip2 videos:  95%|█████████▍| 1889/1989 [15:14<00:51,  1.93batch/s]/s]
pe_core_l14 videos:   2%|▏         | 143/6902 [00:37<28:45,  3.92batch/s]
siglip2 videos:  95%|█████████▌| 1890/1989 [15:14<00:51,  1.91batch/s]/s]
pe_core_l14 videos:   2%|▏         | 145/6902 [00:37<29:10,  3.86batch/s]
siglip2 videos:  95%|█████████▌| 1891/1989 [15:15<00:50,  1.93batch/s]/s]
pe_core_l14 videos:   2%|▏         | 147/6902 [00:38<28:46,  3.91batch/s]
siglip2 videos:  95%|█████████▌| 1892/1989 [15:16<00:51,  1.88batch/s]/s]
pe_core_l14 videos:   2%|▏         | 149/6902 [00:38<29:52,  3.77batch/s]
siglip2 videos:  95%|█████████▌| 1893/1989 [15:16<00:50,  1.91batch/s]/s]
pe_core_l14 videos:   2%|▏         | 151/6902 [00:39<35:56,  3.13batch/s]
siglip2 videos:  95%|█████████▌| 1894/1989 [15:17<00:48,  1.97batch/s]/s]
siglip2 videos:  95%|█████████▌| 1895/1989 [15:17<00:47,  1.99batch/s]/s]
pe_core_l14 videos:   2%|▏         | 154/6902 [00:40<30:14,  3.72batch/s]
siglip2 videos:  95%|█████████▌| 1896/1989 [15:17<00:46,  2.02batch/s]/s]
siglip2 videos:  95%|█████████▌| 1897/1989 [15:18<00:45,  2.03batch/s]/s]
pe_core_l14 videos:   2%|▏         | 157/6902 [00:41<32:08,  3.50batch/s]
siglip2 videos:  95%|█████████▌| 1898/1989 [15:18<00:44,  2.03batch/s]/s]
pe_core_l14 videos:   2%|▏         | 159/6902 [00:41<29:53,  3.76batch/s]
siglip2 videos:  95%|█████████▌| 1899/1989 [15:19<00:44,  2.02batch/s]/s]
pe_core_l14 videos:   2%|▏         | 161/6902 [00:42<28:54,  3.89batch/s]
siglip2 videos:  96%|█████████▌| 1900/1989 [15:19<00:44,  1.99batch/s]/s]
pe_core_l14 videos:   2%|▏         | 163/6902 [00:42<28:55,  3.88batch/s]
siglip2 videos:  96%|█████████▌| 1901/1989 [15:20<00:43,  2.00batch/s]/s]
pe_core_l14 videos:   2%|▏         | 165/6902 [00:43<28:10,  3.99batch/s]
siglip2 videos:  96%|█████████▌| 1902/1989 [15:21<00:44,  1.97batch/s]/s]
pe_core_l14 videos:   2%|▏         | 167/6902 [00:43<28:45,  3.90batch/s]
siglip2 videos:  96%|█████████▌| 1903/1989 [15:21<00:44,  1.95batch/s]/s]
pe_core_l14 videos:   2%|▏         | 169/6902 [00:44<28:55,  3.88batch/s]
siglip2 videos:  96%|█████████▌| 1904/1989 [15:22<00:42,  2.00batch/s]/s]
siglip2 videos:  96%|█████████▌| 1905/1989 [15:22<00:41,  2.02batch/s]/s]
pe_core_l14 videos:   2%|▏         | 172/6902 [00:45<32:17,  3.47batch/s]
siglip2 videos:  96%|█████████▌| 1906/1989 [15:23<00:42,  1.95batch/s]/s]
pe_core_l14 videos:   3%|▎         | 174/6902 [00:45<31:31,  3.56batch/s]
siglip2 videos:  96%|█████████▌| 1907/1989 [15:23<00:42,  1.93batch/s]/s]
pe_core_l14 videos:   3%|▎         | 176/6902 [00:46<30:14,  3.71batch/s]
siglip2 videos:  96%|█████████▌| 1908/1989 [15:24<00:41,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 178/6902 [00:46<29:22,  3.82batch/s]
siglip2 videos:  96%|█████████▌| 1909/1989 [15:24<00:41,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 180/6902 [00:47<28:47,  3.89batch/s]
siglip2 videos:  96%|█████████▌| 1910/1989 [15:25<00:40,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 182/6902 [00:47<28:50,  3.88batch/s]
siglip2 videos:  96%|█████████▌| 1911/1989 [15:25<00:41,  1.90batch/s]/s]
pe_core_l14 videos:   3%|▎         | 184/6902 [00:48<29:28,  3.80batch/s]
siglip2 videos:  96%|█████████▌| 1912/1989 [15:26<00:40,  1.90batch/s]/s]
pe_core_l14 videos:   3%|▎         | 186/6902 [00:49<29:19,  3.82batch/s]
siglip2 videos:  96%|█████████▌| 1913/1989 [15:26<00:40,  1.89batch/s]/s]
pe_core_l14 videos:   3%|▎         | 188/6902 [00:49<29:24,  3.81batch/s]
siglip2 videos:  96%|█████████▌| 1914/1989 [15:27<00:39,  1.90batch/s]/s]
pe_core_l14 videos:   3%|▎         | 190/6902 [00:50<29:01,  3.85batch/s]
siglip2 videos:  96%|█████████▋| 1915/1989 [15:27<00:38,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 192/6902 [00:50<28:17,  3.95batch/s]
siglip2 videos:  96%|█████████▋| 1916/1989 [15:28<00:37,  1.94batch/s]/s]
siglip2 videos:  96%|█████████▋| 1917/1989 [15:28<00:36,  1.97batch/s]/s]
pe_core_l14 videos:   3%|▎         | 195/6902 [00:51<33:20,  3.35batch/s]
siglip2 videos:  96%|█████████▋| 1918/1989 [15:29<00:35,  2.01batch/s]/s]
siglip2 videos:  96%|█████████▋| 1919/1989 [15:29<00:34,  2.02batch/s]/s]
pe_core_l14 videos:   3%|▎         | 198/6902 [00:52<34:03,  3.28batch/s]
siglip2 videos:  97%|█████████▋| 1920/1989 [15:30<00:35,  1.95batch/s]/s]
pe_core_l14 videos:   3%|▎         | 200/6902 [00:53<32:05,  3.48batch/s]
siglip2 videos:  97%|█████████▋| 1921/1989 [15:30<00:35,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 202/6902 [00:53<30:29,  3.66batch/s]
siglip2 videos:  97%|█████████▋| 1922/1989 [15:31<00:34,  1.92batch/s]/s]
pe_core_l14 videos:   3%|▎         | 204/6902 [00:54<29:49,  3.74batch/s]
siglip2 videos:  97%|█████████▋| 1923/1989 [15:31<00:35,  1.88batch/s]/s]
pe_core_l14 videos:   3%|▎         | 206/6902 [00:54<30:05,  3.71batch/s]
siglip2 videos:  97%|█████████▋| 1924/1989 [15:32<00:34,  1.87batch/s]/s]
pe_core_l14 videos:   3%|▎         | 208/6902 [00:55<30:25,  3.67batch/s]
siglip2 videos:  97%|█████████▋| 1925/1989 [15:32<00:32,  1.95batch/s]/s]
siglip2 videos:  97%|█████████▋| 1926/1989 [15:33<00:32,  1.96batch/s]/s]
pe_core_l14 videos:   3%|▎         | 211/6902 [00:56<31:52,  3.50batch/s]
siglip2 videos:  97%|█████████▋| 1927/1989 [15:33<00:31,  1.94batch/s]/s]
pe_core_l14 videos:   3%|▎         | 213/6902 [00:56<30:25,  3.66batch/s]
siglip2 videos:  97%|█████████▋| 1928/1989 [15:34<00:31,  1.93batch/s]/s]
pe_core_l14 videos:   3%|▎         | 215/6902 [00:57<29:46,  3.74batch/s]
siglip2 videos:  97%|█████████▋| 1929/1989 [15:34<00:30,  1.96batch/s]/s]
siglip2 videos:  97%|█████████▋| 1930/1989 [15:35<00:29,  1.97batch/s]/s]
pe_core_l14 videos:   3%|▎         | 218/6902 [00:58<33:22,  3.34batch/s]
siglip2 videos:  97%|█████████▋| 1931/1989 [15:35<00:29,  1.98batch/s]/s]
siglip2 videos:  97%|█████████▋| 1932/1989 [15:36<00:28,  2.00batch/s]/s]
pe_core_l14 videos:   3%|▎         | 221/6902 [00:59<34:46,  3.20batch/s]
siglip2 videos:  97%|█████████▋| 1933/1989 [15:36<00:28,  1.96batch/s]/s]
pe_core_l14 videos:   3%|▎         | 223/6902 [00:59<32:02,  3.47batch/s]
siglip2 videos:  97%|█████████▋| 1934/1989 [15:37<00:28,  1.93batch/s]/s]
pe_core_l14 videos:   3%|▎         | 225/6902 [01:00<30:42,  3.62batch/s]
siglip2 videos:  97%|█████████▋| 1935/1989 [15:37<00:27,  1.95batch/s]/s]
pe_core_l14 videos:   3%|▎         | 227/6902 [01:00<29:07,  3.82batch/s]
siglip2 videos:  97%|█████████▋| 1936/1989 [15:38<00:27,  1.90batch/s]/s]
pe_core_l14 videos:   3%|▎         | 229/6902 [01:01<29:41,  3.75batch/s]
siglip2 videos:  97%|█████████▋| 1937/1989 [15:39<00:27,  1.90batch/s]/s]
pe_core_l14 videos:   3%|▎         | 231/6902 [01:01<29:28,  3.77batch/s]
siglip2 videos:  97%|█████████▋| 1938/1989 [15:39<00:27,  1.86batch/s]/s]
pe_core_l14 videos:   3%|▎         | 233/6902 [01:02<29:55,  3.71batch/s]
siglip2 videos:  97%|█████████▋| 1939/1989 [15:40<00:26,  1.86batch/s]/s]
pe_core_l14 videos:   3%|▎         | 235/6902 [01:03<30:55,  3.59batch/s]
siglip2 videos:  98%|█████████▊| 1940/1989 [15:40<00:25,  1.93batch/s]/s]
siglip2 videos:  98%|█████████▊| 1941/1989 [15:41<00:24,  1.96batch/s]/s]
pe_core_l14 videos:   3%|▎         | 238/6902 [01:03<31:38,  3.51batch/s]
siglip2 videos:  98%|█████████▊| 1942/1989 [15:41<00:23,  2.01batch/s]/s]
siglip2 videos:  98%|█████████▊| 1943/1989 [15:42<00:22,  2.02batch/s]/s]
pe_core_l14 videos:   3%|▎         | 241/6902 [01:04<33:21,  3.33batch/s]
siglip2 videos:  98%|█████████▊| 1944/1989 [15:42<00:23,  1.94batch/s]/s]
pe_core_l14 videos:   4%|▎         | 243/6902 [01:05<31:43,  3.50batch/s]
siglip2 videos:  98%|█████████▊| 1945/1989 [15:43<00:22,  1.93batch/s]/s]
pe_core_l14 videos:   4%|▎         | 245/6902 [01:05<30:21,  3.65batch/s]
siglip2 videos:  98%|█████████▊| 1946/1989 [15:43<00:22,  1.90batch/s]/s]
pe_core_l14 videos:   4%|▎         | 247/6902 [01:06<30:38,  3.62batch/s]
siglip2 videos:  98%|█████████▊| 1947/1989 [15:44<00:21,  1.97batch/s]/s]
siglip2 videos:  98%|█████████▊| 1948/1989 [15:44<00:21,  1.94batch/s]/s]
pe_core_l14 videos:   4%|▎         | 250/6902 [01:07<38:39,  2.87batch/s]
siglip2 videos:  98%|█████████▊| 1949/1989 [15:45<00:19,  2.00batch/s]/s]
siglip2 videos:  98%|█████████▊| 1950/1989 [15:45<00:19,  1.97batch/s]/s]
pe_core_l14 videos:   4%|▎         | 253/6902 [01:08<32:23,  3.42batch/s]
siglip2 videos:  98%|█████████▊| 1951/1989 [15:46<00:19,  1.92batch/s]/s]
pe_core_l14 videos:   4%|▎         | 255/6902 [01:09<31:39,  3.50batch/s]
siglip2 videos:  98%|█████████▊| 1952/1989 [15:46<00:18,  1.98batch/s]/s]
siglip2 videos:  98%|█████████▊| 1953/1989 [15:47<00:18,  1.95batch/s]/s]
pe_core_l14 videos:   4%|▎         | 258/6902 [01:10<32:49,  3.37batch/s]
siglip2 videos:  98%|█████████▊| 1954/1989 [15:47<00:17,  1.99batch/s]/s]
siglip2 videos:  98%|█████████▊| 1955/1989 [15:48<00:17,  2.00batch/s]/s]
pe_core_l14 videos:   4%|▍         | 261/6902 [01:11<34:06,  3.25batch/s]
siglip2 videos:  98%|█████████▊| 1956/1989 [15:48<00:16,  1.96batch/s]/s]
siglip2 videos:  98%|█████████▊| 1957/1989 [15:49<00:16,  2.00batch/s]/s]
pe_core_l14 videos:   4%|▍         | 264/6902 [01:12<35:23,  3.13batch/s]
siglip2 videos:  98%|█████████▊| 1958/1989 [15:49<00:15,  1.97batch/s]/s]
siglip2 videos:  98%|█████████▊| 1959/1989 [15:50<00:15,  1.99batch/s]/s]
pe_core_l14 videos:   4%|▍         | 267/6902 [01:13<35:26,  3.12batch/s]
siglip2 videos:  99%|█████████▊| 1960/1989 [15:50<00:14,  1.95batch/s]/s]
siglip2 videos:  99%|█████████▊| 1961/1989 [15:51<00:14,  1.98batch/s]/s]

-- mean: R1 52.20  mAP 66.66  mINP 66.66
-- mean_s8: R1 52.20  mAP 66.66  mINP 66.66
-- max: R1 51.80  mAP 66.41  mINP 66.41
-- query_max: R1 53.20  mAP 67.22  mINP 67.22
== SigLIP 2 So400m | activitynet/sentence | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos:   5%|▍         | 341/6902 [01:36<44:22,  2.46batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

siglip2 texts:   1%|          | 2/227 [00:00<00:15, 14.23batch/s]
siglip2 texts:   3%|▎         | 6/227 [00:00<00:14, 15.56batch/s]batch/s]
siglip2 texts:   4%|▍         | 10/227 [00:00<00:12, 16.86batch/s]atch/s]
siglip2 texts:   6%|▌         | 14/227 [00:00<00:12, 17.25batch/s]atch/s]
siglip2 texts:   9%|▉         | 20/227 [00:01<00:11, 17.45batch/s]atch/s]
siglip2 texts:  11%|█         | 24/227 [00:01<00:11, 17.67batch/s]atch/s]
siglip2 texts:  13%|█▎        | 30/227 [00:01<00:11, 17.51batch/s]atch/s]
siglip2 texts:  15%|█▍        | 34/227 [00:01<00:11, 17.51batch/s]atch/s]
siglip2 texts:  17%|█▋        | 38/227 [00:02<00:10, 17.54batch/s]atch/s]
siglip2 texts:  19%|█▉        | 44/227 [00:02<00:10, 17.36batch/s]atch/s]
siglip2 texts:  21%|██        | 48/227 [00:02<00:10, 17.44batch/s]atch/s]
siglip2 texts:  23%|██▎       | 52/227 [00:03<00:10, 17.23batch/s]atch/s]
siglip2 texts:  26%|██▌       | 58/227 [00:03<00:09, 17.32batch/s]atch/s]
siglip2 texts:  27%|██▋       | 62/227 [00:03<00:09, 17.45batch/s]atch/s]
siglip2 texts:  30%|██▉       | 68/227 [00:03<00:09, 17.38batch/s]atch/s]
siglip2 texts:  32%|███▏      | 72/227 [00:04<00:08, 17.43batch/s]atch/s]
siglip2 texts:  33%|███▎      | 76/227 [00:04<00:08, 17.45batch/s]atch/s]
siglip2 texts:  35%|███▌      | 80/227 [00:04<00:08, 17.43batch/s]atch/s]
siglip2 texts:  38%|███▊      | 86/227 [00:04<00:08, 17.50batch/s]atch/s]
siglip2 texts:  40%|███▉      | 90/227 [00:05<00:07, 17.46batch/s]atch/s]
siglip2 texts:  41%|████▏     | 94/227 [00:05<00:07, 17.30batch/s]atch/s]
siglip2 texts:  44%|████▍     | 100/227 [00:05<00:07, 17.37batch/s]tch/s]
siglip2 texts:  46%|████▌     | 104/227 [00:06<00:07, 17.50batch/s]tch/s]
siglip2 texts:  48%|████▊     | 110/227 [00:06<00:06, 17.35batch/s]tch/s]
siglip2 texts:  50%|█████     | 114/227 [00:06<00:06, 17.35batch/s]tch/s]
siglip2 texts:  53%|█████▎    | 120/227 [00:06<00:06, 17.35batch/s]tch/s]
siglip2 texts:  55%|█████▍    | 124/227 [00:07<00:05, 17.44batch/s]tch/s]
siglip2 texts:  56%|█████▋    | 128/227 [00:07<00:05, 17.24batch/s]tch/s]
siglip2 texts:  59%|█████▉    | 134/227 [00:07<00:05, 17.24batch/s]tch/s]
siglip2 texts:  62%|██████▏   | 140/227 [00:08<00:05, 17.24batch/s]tch/s]
siglip2 texts:  63%|██████▎   | 144/227 [00:08<00:04, 17.38batch/s]tch/s]
siglip2 texts:  66%|██████▌   | 150/227 [00:08<00:04, 17.33batch/s]tch/s]
siglip2 texts:  68%|██████▊   | 154/227 [00:08<00:04, 17.24batch/s]tch/s]
siglip2 texts:  70%|██████▉   | 158/227 [00:09<00:03, 17.33batch/s]tch/s]
siglip2 texts:  72%|███████▏  | 164/227 [00:09<00:03, 17.14batch/s]tch/s]
siglip2 texts:  74%|███████▍  | 168/227 [00:09<00:03, 17.32batch/s]tch/s]
siglip2 texts:  76%|███████▌  | 172/227 [00:09<00:03, 17.38batch/s]tch/s]
siglip2 texts:  78%|███████▊  | 178/227 [00:10<00:02, 17.15batch/s]tch/s]
siglip2 texts:  80%|████████  | 182/227 [00:10<00:02, 17.27batch/s]tch/s]
siglip2 texts:  82%|████████▏ | 186/227 [00:10<00:02, 17.10batch/s]tch/s]
siglip2 texts:  85%|████████▍ | 192/227 [00:11<00:02, 17.17batch/s]tch/s]
siglip2 texts:  86%|████████▋ | 196/227 [00:11<00:01, 17.21batch/s]tch/s]
siglip2 texts:  89%|████████▉ | 202/227 [00:11<00:01, 17.14batch/s]tch/s]
siglip2 texts:  91%|█████████ | 206/227 [00:11<00:01, 17.25batch/s]tch/s]
siglip2 texts:  93%|█████████▎| 210/227 [00:12<00:00, 17.00batch/s]tch/s]
siglip2 texts:  95%|█████████▌| 216/227 [00:12<00:00, 17.15batch/s]tch/s]
siglip2 texts:  97%|█████████▋| 220/227 [00:12<00:00, 17.16batch/s]tch/s]
siglip2 texts: 100%|█████████▉| 226/227 [00:13<00:00, 17.10batch/s]tch/s]
siglip2 texts: 100%|██████████| 227/227 [00:13<00:00, 17.27batch/s]tch/s]

pe_core_l14 videos:   6%|▌         | 390/6902 [01:50<37:03,  2.93batch/s]
pe_core_l14 videos:   6%|▌         | 391/6902 [01:50<35:58,  3.02batch/s]
pe_core_l14 videos:   6%|▌         | 392/6902 [01:51<39:22,  2.76batch/s]
pe_core_l14 videos:   6%|▌         | 393/6902 [01:51<38:10,  2.84batch/s]
pe_core_l14 videos:   6%|▌         | 394/6902 [01:52<37:43,  2.88batch/s]
pe_core_l14 videos:   6%|▌         | 395/6902 [01:52<39:48,  2.72batch/s]
pe_core_l14 videos:   6%|▌         | 396/6902 [01:52<39:44,  2.73batch/s]
pe_core_l14 videos:   6%|▌         | 397/6902 [01:53<39:04,  2.77batch/s]
pe_core_l14 videos:   6%|▌         | 398/6902 [01:53<40:39,  2.67batch/s]
pe_core_l14 videos:   6%|▌         | 399/6902 [01:53<40:05,  2.70batch/s]
pe_core_l14 videos:   6%|▌         | 400/6902 [01:54<40:16,  2.69batch/s]
pe_core_l14 videos:   6%|▌         | 401/6902 [01:54<45:11,  2.40batch/s]
pe_core_l14 videos:   6%|▌         | 402/6902 [01:55<42:01,  2.58batch/s]
pe_core_l14 videos:   6%|▌         | 403/6902 [01:55<42:48,  2.53batch/s]
pe_core_l14 videos:   6%|▌         | 404/6902 [01:56<45:25,  2.38batch/s]
pe_core_l14 videos:   6%|▌         | 405/6902 [01:56<46:02,  2.35batch/s]
pe_core_l14 videos:   6%|▌         | 406/6902 [01:56<45:08,  2.40batch/s]
pe_core_l14 videos:   6%|▌         | 407/6902 [01:57<46:39,  2.32batch/s]
pe_core_l14 videos:   6%|▌         | 408/6902 [01:57<47:36,  2.27batch/s]
pe_core_l14 videos:   6%|▌         | 409/6902 [01:58<45:28,  2.38batch/s]
pe_core_l14 videos:   6%|▌         | 410/6902 [01:58<43:04,  2.51batch/s]
pe_core_l14 videos:   6%|▌         | 411/6902 [01:59<44:09,  2.45batch/s]
pe_core_l14 videos:   6%|▌         | 412/6902 [01:59<41:42,  2.59batch/s]
pe_core_l14 videos:   6%|▌         | 413/6902 [01:59<40:41,  2.66batch/s]
pe_core_l14 videos:   6%|▌         | 414/6902 [01:59<37:32,  2.88batch/s]
pe_core_l14 videos:   6%|▌         | 415/6902 [02:00<35:43,  3.03batch/s]
pe_core_l14 videos:   6%|▌         | 416/6902 [02:00<34:39,  3.12batch/s]
pe_core_l14 videos:   6%|▌         | 417/6902 [02:00<33:48,  3.20batch/s]
pe_core_l14 videos:   6%|▌         | 418/6902 [02:01<33:54,  3.19batch/s]
pe_core_l14 videos:   6%|▌         | 419/6902 [02:01<33:10,  3.26batch/s]
pe_core_l14 videos:   6%|▌         | 420/6902 [02:01<32:37,  3.31batch/s]
pe_core_l14 videos:   6%|▌         | 421/6902 [02:02<33:56,  3.18batch/s]
pe_core_l14 videos:   6%|▌         | 422/6902 [02:02<33:11,  3.25batch/s]
pe_core_l14 videos:   6%|▌         | 423/6902 [02:02<32:26,  3.33batch/s]
pe_core_l14 videos:   6%|▌         | 424/6902 [02:02<32:18,  3.34batch/s]
pe_core_l14 videos:   6%|▌         | 425/6902 [02:03<31:52,  3.39batch/s]
pe_core_l14 videos:   6%|▌         | 426/6902 [02:03<31:16,  3.45batch/s]
pe_core_l14 videos:   6%|▌         | 427/6902 [02:04<52:52,  2.04batch/s]

-- mean: R1 29.91  mAP 42.99  mINP 42.99
-- mean_s8: R1 29.91  mAP 42.99  mINP 42.99
-- max: R1 29.97  mAP 43.03  mINP 43.03
-- query_max: R1 30.61  mAP 43.90  mINP 43.90
== SigLIP 2 So400m | activitynet/paragraph | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos:   6%|▌         | 428/6902 [02:05<1:06:16,  1.63batch/s]
pe_core_l14 videos:   6%|▌         | 429/6902 [02:05<54:51,  1.97batch/s]
pe_core_l14 videos:   6%|▌         | 430/6902 [02:05<46:53,  2.30batch/s]
pe_core_l14 videos:   6%|▌         | 431/6902 [02:06<41:19,  2.61batch/s]
pe_core_l14 videos:   6%|▋         | 432/6902 [02:06<36:51,  2.93batch/s]
pe_core_l14 videos:   6%|▋         | 433/6902 [02:06<34:18,  3.14batch/s]
pe_core_l14 videos:   6%|▋         | 434/6902 [02:06<32:30,  3.32batch/s]
pe_core_l14 videos:   6%|▋         | 435/6902 [02:07<31:18,  3.44batch/s]
pe_core_l14 videos:   6%|▋         | 436/6902 [02:07<30:24,  3.54batch/s]
pe_core_l14 videos:   6%|▋         | 437/6902 [02:07<29:51,  3.61batch/s]
pe_core_l14 videos:   6%|▋         | 438/6902 [02:08<29:23,  3.67batch/s]
pe_core_l14 videos:   6%|▋         | 439/6902 [02:08<29:21,  3.67batch/s]
pe_core_l14 videos:   6%|▋         | 440/6902 [02:08<29:07,  3.70batch/s]
pe_core_l14 videos:   6%|▋         | 441/6902 [02:08<28:55,  3.72batch/s]
pe_core_l14 videos:   6%|▋         | 442/6902 [02:09<28:41,  3.75batch/s]
pe_core_l14 videos:   6%|▋         | 443/6902 [02:09<28:39,  3.76batch/s]
pe_core_l14 videos:   6%|▋         | 444/6902 [02:09<28:43,  3.75batch/s]
pe_core_l14 videos:   6%|▋         | 445/6902 [02:09<28:41,  3.75batch/s]
pe_core_l14 videos:   6%|▋         | 446/6902 [02:10<28:27,  3.78batch/s]
pe_core_l14 videos:   6%|▋         | 447/6902 [02:10<28:37,  3.76batch/s]
pe_core_l14 videos:   6%|▋         | 448/6902 [02:10<28:42,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 449/6902 [02:10<28:36,  3.76batch/s]
pe_core_l14 videos:   7%|▋         | 450/6902 [02:11<28:38,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 451/6902 [02:11<28:42,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 452/6902 [02:11<28:40,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 453/6902 [02:11<28:39,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 454/6902 [02:12<28:39,  3.75batch/s]
pe_core_l14 videos:   7%|▋         | 455/6902 [02:12<28:43,  3.74batch/s]
pe_core_l14 videos:   7%|▋         | 456/6902 [02:12<28:43,  3.74batch/s]
pe_core_l14 videos:   7%|▋         | 457/6902 [02:13<28:45,  3.74batch/s]
pe_core_l14 videos:   7%|▋         | 458/6902 [02:13<28:46,  3.73batch/s]
pe_core_l14 videos:   7%|▋         | 459/6902 [02:13<28:44,  3.74batch/s]
pe_core_l14 videos:   7%|▋         | 460/6902 [02:13<28:48,  3.73batch/s]
pe_core_l14 videos:   7%|▋         | 461/6902 [02:14<28:48,  3.73batch/s]
pe_core_l14 videos:   7%|▋         | 462/6902 [02:14<28:51,  3.72batch/s]
pe_core_l14 videos:   7%|▋         | 463/6902 [02:14<28:51,  3.72batch/s]
pe_core_l14 videos:   7%|▋         | 464/6902 [02:14<28:52,  3.72batch/s]
pe_core_l14 videos:   7%|▋         | 465/6902 [02:15<28:53,  3.71batch/s]
pe_core_l14 videos:   7%|▋         | 466/6902 [02:15<28:57,  3.70batch/s]
pe_core_l14 videos:   7%|▋         | 467/6902 [02:15<29:03,  3.69batch/s]
pe_core_l14 videos:   7%|▋         | 468/6902 [02:16<29:05,  3.69batch/s]
pe_core_l14 videos:   7%|▋         | 469/6902 [02:16<29:01,  3.69batch/s]
pe_core_l14 videos:   7%|▋         | 470/6902 [02:16<29:06,  3.68batch/s]
pe_core_l14 videos:   7%|▋         | 471/6902 [02:16<29:04,  3.69batch/s]
pe_core_l14 videos:   7%|▋         | 472/6902 [02:17<29:00,  3.69batch/s]
pe_core_l14 videos:   7%|▋         | 473/6902 [02:17<29:04,  3.68batch/s]
pe_core_l14 videos:   7%|▋         | 474/6902 [02:17<29:05,  3.68batch/s]
pe_core_l14 videos:   7%|▋         | 475/6902 [02:17<29:39,  3.61batch/s]
pe_core_l14 videos:   7%|▋         | 476/6902 [02:18<29:31,  3.63batch/s]
pe_core_l14 videos:   7%|▋         | 477/6902 [02:18<29:25,  3.64batch/s]
pe_core_l14 videos:   7%|▋         | 478/6902 [02:18<29:22,  3.64batch/s]
pe_core_l14 videos:   7%|▋         | 479/6902 [02:19<29:17,  3.65batch/s]
pe_core_l14 videos:   7%|▋         | 480/6902 [02:19<29:10,  3.67batch/s]
pe_core_l14 videos:   7%|▋         | 481/6902 [02:19<29:06,  3.68batch/s]
pe_core_l14 videos:   7%|▋         | 482/6902 [02:19<29:10,  3.67batch/s]
pe_core_l14 videos:   7%|▋         | 483/6902 [02:20<29:03,  3.68batch/s]
pe_core_l14 videos:   7%|▋         | 484/6902 [02:20<29:07,  3.67batch/s]
pe_core_l14 videos:   7%|▋         | 485/6902 [02:20<29:12,  3.66batch/s]
pe_core_l14 videos:   7%|▋         | 486/6902 [02:20<29:15,  3.65batch/s]
pe_core_l14 videos:   7%|▋         | 487/6902 [02:21<29:30,  3.62batch/s]
pe_core_l14 videos:   7%|▋         | 488/6902 [02:21<29:26,  3.63batch/s]
pe_core_l14 videos:   7%|▋         | 489/6902 [02:21<29:29,  3.62batch/s]
pe_core_l14 videos:   7%|▋         | 490/6902 [02:22<29:38,  3.60batch/s]
pe_core_l14 videos:   7%|▋         | 491/6902 [02:22<29:34,  3.61batch/s]
pe_core_l14 videos:   7%|▋         | 492/6902 [02:22<29:32,  3.62batch/s]
pe_core_l14 videos:   7%|▋         | 493/6902 [02:22<29:32,  3.62batch/s]
pe_core_l14 videos:   7%|▋         | 494/6902 [02:23<29:37,  3.60batch/s]
pe_core_l14 videos:   7%|▋         | 495/6902 [02:23<29:35,  3.61batch/s]
pe_core_l14 videos:   7%|▋         | 496/6902 [02:23<29:34,  3.61batch/s]
pe_core_l14 videos:   7%|▋         | 497/6902 [02:24<29:46,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 498/6902 [02:24<29:53,  3.57batch/s]
pe_core_l14 videos:   7%|▋         | 499/6902 [02:24<29:52,  3.57batch/s]
pe_core_l14 videos:   7%|▋         | 500/6902 [02:24<29:20,  3.64batch/s]
pe_core_l14 videos:   7%|▋         | 501/6902 [02:25<29:39,  3.60batch/s]
pe_core_l14 videos:   7%|▋         | 502/6902 [02:25<29:48,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 503/6902 [02:25<29:48,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 504/6902 [02:25<29:45,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 505/6902 [02:26<29:48,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 506/6902 [02:26<29:48,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 507/6902 [02:26<29:51,  3.57batch/s]
pe_core_l14 videos:   7%|▋         | 508/6902 [02:27<29:49,  3.57batch/s]
pe_core_l14 videos:   7%|▋         | 509/6902 [02:27<29:55,  3.56batch/s]
pe_core_l14 videos:   7%|▋         | 510/6902 [02:27<29:44,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 511/6902 [02:27<29:44,  3.58batch/s]
pe_core_l14 videos:   7%|▋         | 512/6902 [02:28<29:55,  3.56batch/s]
pe_core_l14 videos:   7%|▋         | 513/6902 [02:28<30:03,  3.54batch/s]
pe_core_l14 videos:   7%|▋         | 514/6902 [02:28<29:57,  3.55batch/s]
pe_core_l14 videos:   7%|▋         | 515/6902 [02:29<29:54,  3.56batch/s]
pe_core_l14 videos:   7%|▋         | 516/6902 [02:29<29:55,  3.56batch/s]
pe_core_l14 videos:   7%|▋         | 517/6902 [02:29<30:03,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 518/6902 [02:29<30:04,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 519/6902 [02:30<30:01,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 520/6902 [02:30<30:09,  3.53batch/s]
pe_core_l14 videos:   8%|▊         | 521/6902 [02:30<30:26,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 522/6902 [02:31<30:21,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 523/6902 [02:31<30:21,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 524/6902 [02:31<30:11,  3.52batch/s]
pe_core_l14 videos:   8%|▊         | 525/6902 [02:31<30:10,  3.52batch/s]
pe_core_l14 videos:   8%|▊         | 526/6902 [02:32<30:23,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 527/6902 [02:32<30:26,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 528/6902 [02:32<30:22,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 529/6902 [02:33<30:22,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 530/6902 [02:33<30:20,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 531/6902 [02:33<30:23,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 532/6902 [02:33<30:22,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 533/6902 [02:34<30:19,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 534/6902 [02:34<30:27,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 535/6902 [02:34<30:32,  3.47batch/s]
pe_core_l14 videos:   8%|▊         | 536/6902 [02:35<30:29,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 537/6902 [02:35<30:21,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 538/6902 [02:35<30:22,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 539/6902 [02:35<30:23,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 540/6902 [02:36<30:20,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 541/6902 [02:36<30:28,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 542/6902 [02:36<30:26,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 543/6902 [02:37<30:18,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 544/6902 [02:37<30:29,  3.47batch/s]
pe_core_l14 videos:   8%|▊         | 545/6902 [02:37<30:24,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 546/6902 [02:37<30:20,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 547/6902 [02:38<30:19,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 548/6902 [02:38<30:24,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 549/6902 [02:38<30:15,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 550/6902 [02:39<30:13,  3.50batch/s]
pe_core_l14 videos:   8%|▊         | 551/6902 [02:39<30:03,  3.52batch/s]
pe_core_l14 videos:   8%|▊         | 552/6902 [02:39<30:18,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 553/6902 [02:39<30:21,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 554/6902 [02:40<30:22,  3.48batch/s]
pe_core_l14 videos:   8%|▊         | 555/6902 [02:40<30:18,  3.49batch/s]
pe_core_l14 videos:   8%|▊         | 556/6902 [02:40<30:09,  3.51batch/s]
pe_core_l14 videos:   8%|▊         | 557/6902 [02:41<30:07,  3.51batch/s]
pe_core_l14 videos:   8%|▊         | 558/6902 [02:41<29:59,  3.52batch/s]
pe_core_l14 videos:   8%|▊         | 559/6902 [02:41<29:46,  3.55batch/s]
pe_core_l14 videos:   8%|▊         | 560/6902 [02:41<29:50,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 561/6902 [02:42<29:49,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 562/6902 [02:42<29:35,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 563/6902 [02:42<29:34,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 564/6902 [02:43<29:38,  3.56batch/s]
pe_core_l14 videos:   8%|▊         | 565/6902 [02:43<29:37,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 566/6902 [02:43<29:31,  3.58batch/s]
pe_core_l14 videos:   8%|▊         | 567/6902 [02:43<29:32,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 568/6902 [02:44<29:39,  3.56batch/s]
pe_core_l14 videos:   8%|▊         | 569/6902 [02:44<29:32,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 570/6902 [02:44<29:39,  3.56batch/s]
pe_core_l14 videos:   8%|▊         | 571/6902 [02:44<29:58,  3.52batch/s]
pe_core_l14 videos:   8%|▊         | 572/6902 [02:45<29:47,  3.54batch/s]
pe_core_l14 videos:   8%|▊         | 573/6902 [02:45<29:40,  3.55batch/s]
pe_core_l14 videos:   8%|▊         | 574/6902 [02:45<29:33,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 575/6902 [02:46<29:31,  3.57batch/s]
pe_core_l14 videos:   8%|▊         | 576/6902 [02:46<29:23,  3.59batch/s]
pe_core_l14 videos:   8%|▊         | 577/6902 [02:46<29:08,  3.62batch/s]
pe_core_l14 videos:   8%|▊         | 578/6902 [02:46<29:06,  3.62batch/s]
pe_core_l14 videos:   8%|▊         | 579/6902 [02:47<28:59,  3.64batch/s]
pe_core_l14 videos:   8%|▊         | 580/6902 [02:47<28:55,  3.64batch/s]
pe_core_l14 videos:   8%|▊         | 581/6902 [02:47<28:50,  3.65batch/s]
pe_core_l14 videos:   8%|▊         | 582/6902 [02:48<29:01,  3.63batch/s]
pe_core_l14 videos:   8%|▊         | 583/6902 [02:48<29:05,  3.62batch/s]
pe_core_l14 videos:   8%|▊         | 584/6902 [02:48<29:04,  3.62batch/s]
pe_core_l14 videos:   8%|▊         | 585/6902 [02:48<28:57,  3.63batch/s]
pe_core_l14 videos:   8%|▊         | 586/6902 [02:49<28:53,  3.64batch/s]
pe_core_l14 videos:   9%|▊         | 587/6902 [02:49<28:49,  3.65batch/s]
pe_core_l14 videos:   9%|▊         | 588/6902 [02:49<28:48,  3.65batch/s]
pe_core_l14 videos:   9%|▊         | 589/6902 [02:49<28:47,  3.65batch/s]
pe_core_l14 videos:   9%|▊         | 590/6902 [02:50<28:43,  3.66batch/s]
pe_core_l14 videos:   9%|▊         | 591/6902 [02:50<28:52,  3.64batch/s]
pe_core_l14 videos:   9%|▊         | 592/6902 [02:50<28:52,  3.64batch/s]
pe_core_l14 videos:   9%|▊         | 593/6902 [02:51<28:48,  3.65batch/s]
pe_core_l14 videos:   9%|▊         | 594/6902 [02:51<28:46,  3.65batch/s]
pe_core_l14 videos:   9%|▊         | 595/6902 [02:51<28:51,  3.64batch/s]
pe_core_l14 videos:   9%|▊         | 596/6902 [02:51<28:51,  3.64batch/s]
pe_core_l14 videos:   9%|▊         | 597/6902 [02:52<28:40,  3.67batch/s]
pe_core_l14 videos:   9%|▊         | 598/6902 [02:52<28:42,  3.66batch/s]
pe_core_l14 videos:   9%|▊         | 599/6902 [02:52<28:32,  3.68batch/s]
pe_core_l14 videos:   9%|▊         | 600/6902 [02:52<28:35,  3.67batch/s]
pe_core_l14 videos:   9%|▊         | 601/6902 [02:53<28:32,  3.68batch/s]
pe_core_l14 videos:   9%|▊         | 602/6902 [02:53<28:42,  3.66batch/s]
pe_core_l14 videos:   9%|▊         | 603/6902 [02:53<28:48,  3.64batch/s]
pe_core_l14 videos:   9%|▉         | 604/6902 [02:54<28:45,  3.65batch/s]
pe_core_l14 videos:   9%|▉         | 605/6902 [02:54<28:42,  3.65batch/s]
pe_core_l14 videos:   9%|▉         | 606/6902 [02:54<28:35,  3.67batch/s]
pe_core_l14 videos:   9%|▉         | 607/6902 [02:54<28:25,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 608/6902 [02:55<28:28,  3.68batch/s]
pe_core_l14 videos:   9%|▉         | 609/6902 [02:55<28:28,  3.68batch/s]
pe_core_l14 videos:   9%|▉         | 610/6902 [02:55<28:22,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 611/6902 [02:55<28:19,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 612/6902 [02:56<28:23,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 613/6902 [02:56<28:20,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 614/6902 [02:56<28:22,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 615/6902 [02:57<28:27,  3.68batch/s]
pe_core_l14 videos:   9%|▉         | 616/6902 [02:57<28:21,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 617/6902 [02:57<28:22,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 618/6902 [02:57<28:16,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 619/6902 [02:58<28:18,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 620/6902 [02:58<28:16,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 621/6902 [02:58<28:21,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 622/6902 [02:58<28:15,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 623/6902 [02:59<28:18,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 624/6902 [02:59<28:22,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 625/6902 [02:59<28:16,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 626/6902 [02:59<28:09,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 627/6902 [03:00<28:08,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 628/6902 [03:00<28:07,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 629/6902 [03:00<28:12,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 630/6902 [03:01<28:13,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 631/6902 [03:01<28:13,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 632/6902 [03:01<28:11,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 633/6902 [03:01<28:15,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 634/6902 [03:02<28:10,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 635/6902 [03:02<28:10,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 636/6902 [03:02<28:14,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 637/6902 [03:02<28:13,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 638/6902 [03:03<28:15,  3.69batch/s]
pe_core_l14 videos:   9%|▉         | 639/6902 [03:03<28:10,  3.70batch/s]
pe_core_l14 videos:   9%|▉         | 640/6902 [03:03<28:05,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 641/6902 [03:04<28:00,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 642/6902 [03:04<28:00,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 643/6902 [03:04<28:00,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 644/6902 [03:04<27:58,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 645/6902 [03:05<27:55,  3.74batch/s]
pe_core_l14 videos:   9%|▉         | 646/6902 [03:05<28:05,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 647/6902 [03:05<28:04,  3.71batch/s]
pe_core_l14 videos:   9%|▉         | 648/6902 [03:05<28:00,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 649/6902 [03:06<27:58,  3.72batch/s]
pe_core_l14 videos:   9%|▉         | 650/6902 [03:06<27:57,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 651/6902 [03:06<27:55,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 652/6902 [03:06<27:54,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 653/6902 [03:07<27:56,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 654/6902 [03:07<27:57,  3.73batch/s]
pe_core_l14 videos:   9%|▉         | 655/6902 [03:07<27:56,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 656/6902 [03:08<27:55,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 657/6902 [03:08<27:43,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 658/6902 [03:08<27:42,  3.76batch/s]
pe_core_l14 videos:  10%|▉         | 659/6902 [03:08<27:45,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 660/6902 [03:09<27:47,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 661/6902 [03:09<27:42,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 662/6902 [03:09<27:36,  3.77batch/s]
pe_core_l14 videos:  10%|▉         | 663/6902 [03:09<27:46,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 664/6902 [03:10<27:46,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 665/6902 [03:10<27:48,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 666/6902 [03:10<27:50,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 667/6902 [03:11<27:49,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 668/6902 [03:11<27:50,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 669/6902 [03:11<27:45,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 670/6902 [03:11<27:51,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 671/6902 [03:12<27:50,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 672/6902 [03:12<27:51,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 673/6902 [03:12<27:50,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 674/6902 [03:12<27:54,  3.72batch/s]
pe_core_l14 videos:  10%|▉         | 675/6902 [03:13<27:54,  3.72batch/s]
pe_core_l14 videos:  10%|▉         | 676/6902 [03:13<28:00,  3.70batch/s]
pe_core_l14 videos:  10%|▉         | 677/6902 [03:13<27:58,  3.71batch/s]
pe_core_l14 videos:  10%|▉         | 678/6902 [03:13<27:44,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 679/6902 [03:14<27:44,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 680/6902 [03:14<27:40,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 681/6902 [03:14<27:49,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 682/6902 [03:15<27:46,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 683/6902 [03:15<27:47,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 684/6902 [03:15<27:45,  3.73batch/s]
pe_core_l14 videos:  10%|▉         | 685/6902 [03:15<27:40,  3.74batch/s]
pe_core_l14 videos:  10%|▉         | 686/6902 [03:16<27:33,  3.76batch/s]
pe_core_l14 videos:  10%|▉         | 687/6902 [03:16<27:37,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 688/6902 [03:16<27:33,  3.76batch/s]
pe_core_l14 videos:  10%|▉         | 689/6902 [03:16<27:36,  3.75batch/s]
pe_core_l14 videos:  10%|▉         | 690/6902 [03:17<27:30,  3.76batch/s]
pe_core_l14 videos:  10%|█         | 691/6902 [03:17<27:24,  3.78batch/s]
pe_core_l14 videos:  10%|█         | 692/6902 [03:17<27:28,  3.77batch/s]
pe_core_l14 videos:  10%|█         | 693/6902 [03:17<27:44,  3.73batch/s]
pe_core_l14 videos:  10%|█         | 694/6902 [03:18<27:56,  3.70batch/s]
pe_core_l14 videos:  10%|█         | 695/6902 [03:18<27:56,  3.70batch/s]
pe_core_l14 videos:  10%|█         | 696/6902 [03:18<27:54,  3.71batch/s]
pe_core_l14 videos:  10%|█         | 697/6902 [03:19<27:50,  3.71batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos:   0%|          | 0/6902 [00:00<?, ?batch/s]
siglip2 videos:   0%|          | 1/6902 [00:00<1:01:58,  1.86batch/s]ch/s]
pe_core_l14 videos:  17%|█▋        | 1166/6902 [05:26<33:38,  2.84batch/s]
siglip2 videos:   0%|          | 2/6902 [00:00<52:12,  2.20batch/s]  ch/s]
siglip2 videos:   0%|          | 3/6902 [00:01<49:21,  2.33batch/s]atch/s]
siglip2 videos:   0%|          | 4/6902 [00:01<47:51,  2.40batch/s]atch/s]
siglip2 videos:   0%|          | 5/6902 [00:02<46:59,  2.45batch/s]atch/s]
siglip2 videos:   0%|          | 6/6902 [00:02<46:19,  2.48batch/s]atch/s]
siglip2 videos:   0%|          | 7/6902 [00:02<46:07,  2.49batch/s]atch/s]
siglip2 videos:   0%|          | 8/6902 [00:03<45:57,  2.50batch/s]atch/s]
siglip2 videos:   0%|          | 9/6902 [00:03<45:50,  2.51batch/s]atch/s]
siglip2 videos:   0%|          | 10/6902 [00:04<45:49,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 11/6902 [00:04<45:44,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 12/6902 [00:04<45:31,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 13/6902 [00:05<45:35,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 14/6902 [00:05<45:39,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 15/6902 [00:06<45:35,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 16/6902 [00:06<45:29,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 17/6902 [00:06<45:29,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 18/6902 [00:07<45:31,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 19/6902 [00:07<45:28,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 20/6902 [00:08<45:34,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 21/6902 [00:08<45:36,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 22/6902 [00:08<45:37,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 23/6902 [00:09<45:36,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 24/6902 [00:09<45:39,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 25/6902 [00:10<45:36,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 26/6902 [00:10<45:49,  2.50batch/s]tch/s]
siglip2 videos:   0%|          | 27/6902 [00:10<45:59,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 28/6902 [00:11<46:02,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 29/6902 [00:11<46:11,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 30/6902 [00:12<46:02,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 31/6902 [00:12<45:59,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 32/6902 [00:12<46:02,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 33/6902 [00:13<46:06,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 34/6902 [00:13<45:58,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 35/6902 [00:14<46:02,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 36/6902 [00:14<45:57,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 37/6902 [00:14<45:51,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 38/6902 [00:15<45:56,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 39/6902 [00:15<46:03,  2.48batch/s]tch/s]
siglip2 videos:   1%|          | 40/6902 [00:16<45:52,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 41/6902 [00:16<45:43,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 42/6902 [00:16<45:44,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 43/6902 [00:17<45:36,  2.51batch/s]tch/s]
siglip2 videos:   1%|          | 44/6902 [00:17<45:38,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 45/6902 [00:18<45:41,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 46/6902 [00:18<45:40,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 47/6902 [00:18<45:42,  2.50batch/s]tch/s]
siglip2 videos:   1%|          | 48/6902 [00:19<45:48,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 49/6902 [00:19<45:57,  2.49batch/s]tch/s]
siglip2 videos:   1%|          | 50/6902 [00:20<45:59,  2.48batch/s]tch/s]
siglip2 videos:   1%|          | 51/6902 [00:20<46:17,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 52/6902 [00:20<46:12,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 53/6902 [00:21<46:21,  2.46batch/s]tch/s]
siglip2 videos:   1%|          | 54/6902 [00:21<46:35,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 55/6902 [00:22<46:30,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 56/6902 [00:22<46:38,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 58/6902 [00:23<46:29,  2.45batch/s]tch/s]
pe_core_l14 videos:  18%|█▊        | 1223/6902 [05:49<38:34,  2.45batch/s]
siglip2 videos:   1%|          | 59/6902 [00:23<46:41,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 60/6902 [00:24<46:39,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 61/6902 [00:24<46:38,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 62/6902 [00:25<46:46,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 63/6902 [00:25<46:53,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 64/6902 [00:25<46:43,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 65/6902 [00:26<46:42,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 66/6902 [00:26<46:45,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 67/6902 [00:27<46:48,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 68/6902 [00:27<46:39,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 69/6902 [00:27<46:45,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 70/6902 [00:28<46:41,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 71/6902 [00:28<46:40,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 72/6902 [00:29<46:45,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 73/6902 [00:29<46:44,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 74/6902 [00:29<46:50,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 75/6902 [00:30<46:50,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 76/6902 [00:30<46:57,  2.42batch/s]tch/s]
siglip2 videos:   1%|          | 77/6902 [00:31<46:51,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 78/6902 [00:31<46:57,  2.42batch/s]tch/s]
siglip2 videos:   1%|          | 79/6902 [00:32<46:51,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 80/6902 [00:32<46:49,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 81/6902 [00:32<46:37,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 82/6902 [00:33<46:42,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 83/6902 [00:33<46:53,  2.42batch/s]tch/s]
siglip2 videos:   1%|          | 84/6902 [00:34<46:56,  2.42batch/s]tch/s]
siglip2 videos:   1%|          | 85/6902 [00:34<46:54,  2.42batch/s]tch/s]
siglip2 videos:   1%|          | 86/6902 [00:34<46:54,  2.42batch/s]tch/s]
siglip2 videos:   1%|▏         | 87/6902 [00:35<47:06,  2.41batch/s]tch/s]
siglip2 videos:   1%|▏         | 88/6902 [00:35<47:01,  2.41batch/s]tch/s]
siglip2 videos:   1%|▏         | 89/6902 [00:36<46:56,  2.42batch/s]tch/s]
siglip2 videos:   1%|▏         | 90/6902 [00:36<47:16,  2.40batch/s]tch/s]
siglip2 videos:   1%|▏         | 91/6902 [00:36<47:08,  2.41batch/s]tch/s]
siglip2 videos:   1%|▏         | 92/6902 [00:37<47:07,  2.41batch/s]tch/s]
siglip2 videos:   1%|▏         | 93/6902 [00:37<47:04,  2.41batch/s]tch/s]
siglip2 videos:   1%|▏         | 94/6902 [00:38<47:19,  2.40batch/s]tch/s]
siglip2 videos:   1%|▏         | 95/6902 [00:38<47:17,  2.40batch/s]tch/s]
siglip2 videos:   1%|▏         | 96/6902 [00:39<47:16,  2.40batch/s]tch/s]
siglip2 videos:   1%|▏         | 97/6902 [00:39<47:23,  2.39batch/s]tch/s]
siglip2 videos:   1%|▏         | 98/6902 [00:39<47:24,  2.39batch/s]tch/s]
siglip2 videos:   1%|▏         | 99/6902 [00:40<47:20,  2.39batch/s]tch/s]
siglip2 videos:   1%|▏         | 100/6902 [00:40<47:32,  2.38batch/s]ch/s]
siglip2 videos:   1%|▏         | 101/6902 [00:41<47:32,  2.38batch/s]ch/s]
siglip2 videos:   1%|▏         | 102/6902 [00:41<47:36,  2.38batch/s]ch/s]
siglip2 videos:   1%|▏         | 103/6902 [00:41<47:24,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 104/6902 [00:42<47:25,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 105/6902 [00:42<47:55,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 106/6902 [00:43<47:45,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 107/6902 [00:43<47:42,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 108/6902 [00:44<47:39,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 109/6902 [00:44<47:44,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 110/6902 [00:44<47:35,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 111/6902 [00:45<47:33,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 112/6902 [00:45<47:27,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 113/6902 [00:46<47:23,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 114/6902 [00:46<47:16,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 115/6902 [00:47<47:17,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 116/6902 [00:47<47:18,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 117/6902 [00:47<47:19,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 118/6902 [00:48<47:24,  2.39batch/s]ch/s]
siglip2 videos:   2%|▏         | 119/6902 [00:48<47:32,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 120/6902 [00:49<47:31,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 121/6902 [00:49<47:38,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 122/6902 [00:49<47:53,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 123/6902 [00:50<47:50,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 124/6902 [00:50<47:51,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 125/6902 [00:51<47:54,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 126/6902 [00:51<47:49,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 127/6902 [00:52<47:41,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 128/6902 [00:52<47:36,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 129/6902 [00:52<47:38,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 130/6902 [00:53<47:36,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 131/6902 [00:53<47:42,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 132/6902 [00:54<47:48,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 133/6902 [00:54<47:50,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 134/6902 [00:55<47:56,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 135/6902 [00:55<48:07,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 136/6902 [00:55<47:59,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 137/6902 [00:56<48:02,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 138/6902 [00:56<47:59,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 139/6902 [00:57<47:55,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 140/6902 [00:57<48:01,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 141/6902 [00:58<47:21,  2.38batch/s]ch/s]
siglip2 videos:   2%|▏         | 142/6902 [00:58<47:34,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 143/6902 [00:58<47:32,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 144/6902 [00:59<47:31,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 145/6902 [00:59<47:34,  2.37batch/s]ch/s]
siglip2 videos:   2%|▏         | 146/6902 [01:00<47:43,  2.36batch/s]ch/s]
siglip2 videos:   2%|▏         | 147/6902 [01:00<47:57,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 148/6902 [01:01<47:59,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 149/6902 [01:01<47:52,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 150/6902 [01:01<47:55,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 151/6902 [01:02<47:56,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 152/6902 [01:02<48:00,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 153/6902 [01:03<47:58,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 154/6902 [01:03<48:00,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 155/6902 [01:04<48:01,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 156/6902 [01:04<48:04,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 157/6902 [01:04<48:06,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 158/6902 [01:05<48:02,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 159/6902 [01:05<47:51,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 160/6902 [01:06<47:48,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 161/6902 [01:06<47:51,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 162/6902 [01:06<47:52,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 163/6902 [01:07<47:52,  2.35batch/s]ch/s]
siglip2 videos:   2%|▏         | 164/6902 [01:07<48:00,  2.34batch/s]ch/s]
siglip2 videos:   2%|▏         | 165/6902 [01:08<48:14,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 166/6902 [01:08<48:12,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 167/6902 [01:09<48:16,  2.33batch/s]ch/s]
siglip2 videos:   2%|▏         | 168/6902 [01:09<48:18,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 169/6902 [01:10<48:17,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 170/6902 [01:10<48:16,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 171/6902 [01:10<48:21,  2.32batch/s]ch/s]
siglip2 videos:   2%|▏         | 172/6902 [01:11<48:21,  2.32batch/s]ch/s]
siglip2 videos:   3%|▎         | 173/6902 [01:11<48:19,  2.32batch/s]ch/s]
siglip2 videos:   3%|▎         | 174/6902 [01:12<48:30,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 175/6902 [01:12<48:45,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 176/6902 [01:13<48:44,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 177/6902 [01:13<48:39,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 178/6902 [01:13<48:44,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 179/6902 [01:14<48:43,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 180/6902 [01:14<48:34,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 181/6902 [01:15<48:38,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 182/6902 [01:15<48:28,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 183/6902 [01:16<48:23,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 185/6902 [01:16<48:28,  2.31batch/s]ch/s]
pe_core_l14 videos:  20%|█▉        | 1350/6902 [06:42<40:04,  2.31batch/s]
siglip2 videos:   3%|▎         | 186/6902 [01:17<48:23,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 187/6902 [01:17<48:31,  2.31batch/s]ch/s]
siglip2 videos:   3%|▎         | 188/6902 [01:18<48:40,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 189/6902 [01:18<48:46,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 190/6902 [01:19<48:46,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 191/6902 [01:19<48:50,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 192/6902 [01:19<48:44,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 193/6902 [01:20<48:43,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 194/6902 [01:20<48:41,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 195/6902 [01:21<48:42,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 196/6902 [01:21<48:48,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 197/6902 [01:22<48:41,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 198/6902 [01:22<48:49,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 199/6902 [01:23<48:42,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 200/6902 [01:23<48:38,  2.30batch/s]ch/s]
siglip2 videos:   3%|▎         | 201/6902 [01:23<48:55,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 202/6902 [01:24<48:49,  2.29batch/s]ch/s]
siglip2 videos:   3%|▎         | 203/6902 [01:24<48:57,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 204/6902 [01:25<48:54,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 205/6902 [01:25<49:00,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 206/6902 [01:26<49:06,  2.27batch/s]ch/s]
siglip2 videos:   3%|▎         | 207/6902 [01:26<49:17,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 208/6902 [01:27<49:07,  2.27batch/s]ch/s]
siglip2 videos:   3%|▎         | 209/6902 [01:27<49:03,  2.27batch/s]ch/s]
siglip2 videos:   3%|▎         | 210/6902 [01:27<48:57,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 211/6902 [01:28<48:58,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 212/6902 [01:28<48:53,  2.28batch/s]ch/s]
siglip2 videos:   3%|▎         | 213/6902 [01:29<49:01,  2.27batch/s]ch/s]
siglip2 videos:   3%|▎         | 214/6902 [01:29<49:15,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 215/6902 [01:30<49:13,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 216/6902 [01:30<49:19,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 217/6902 [01:30<49:23,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 218/6902 [01:31<49:20,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 219/6902 [01:31<49:15,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 220/6902 [01:32<49:14,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 221/6902 [01:32<49:25,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 222/6902 [01:33<49:19,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 223/6902 [01:33<49:22,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 224/6902 [01:34<49:17,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 225/6902 [01:34<49:18,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 226/6902 [01:34<49:14,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 227/6902 [01:35<49:13,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 228/6902 [01:35<49:11,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 229/6902 [01:36<49:11,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 230/6902 [01:36<49:21,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 231/6902 [01:37<49:24,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 232/6902 [01:37<49:30,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 233/6902 [01:38<49:31,  2.24batch/s]ch/s]
siglip2 videos:   3%|▎         | 234/6902 [01:38<49:29,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 235/6902 [01:38<49:28,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 237/6902 [01:39<49:29,  2.24batch/s]ch/s]
pe_core_l14 videos:  20%|██        | 1402/6902 [07:05<40:50,  2.24batch/s]
siglip2 videos:   3%|▎         | 238/6902 [01:40<49:16,  2.25batch/s]ch/s]
siglip2 videos:   3%|▎         | 239/6902 [01:40<49:13,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 240/6902 [01:41<49:07,  2.26batch/s]ch/s]
siglip2 videos:   3%|▎         | 241/6902 [01:41<49:08,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 242/6902 [01:42<49:07,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 243/6902 [01:42<49:05,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 244/6902 [01:42<49:04,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 245/6902 [01:43<48:59,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 246/6902 [01:43<49:08,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 247/6902 [01:44<49:10,  2.26batch/s]ch/s]
siglip2 videos:   4%|▎         | 248/6902 [01:44<49:25,  2.24batch/s]ch/s]
siglip2 videos:   4%|▎         | 249/6902 [01:45<49:31,  2.24batch/s]ch/s]
siglip2 videos:   4%|▎         | 250/6902 [01:45<49:45,  2.23batch/s]ch/s]
siglip2 videos:   4%|▎         | 251/6902 [01:46<49:50,  2.22batch/s]ch/s]
siglip2 videos:   4%|▎         | 252/6902 [01:46<49:41,  2.23batch/s]ch/s]
siglip2 videos:   4%|▎         | 253/6902 [01:46<49:43,  2.23batch/s]ch/s]
siglip2 videos:   4%|▎         | 254/6902 [01:47<49:32,  2.24batch/s]ch/s]
siglip2 videos:   4%|▎         | 255/6902 [01:47<49:22,  2.24batch/s]ch/s]
siglip2 videos:   4%|▎         | 256/6902 [01:48<49:15,  2.25batch/s]ch/s]
siglip2 videos:   4%|▎         | 257/6902 [01:48<49:09,  2.25batch/s]ch/s]
siglip2 videos:   4%|▎         | 258/6902 [01:49<49:10,  2.25batch/s]ch/s]
siglip2 videos:   4%|▍         | 259/6902 [01:49<49:03,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 260/6902 [01:50<48:57,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 261/6902 [01:50<48:16,  2.29batch/s]ch/s]
siglip2 videos:   4%|▍         | 262/6902 [01:50<48:41,  2.27batch/s]ch/s]
siglip2 videos:   4%|▍         | 263/6902 [01:51<49:01,  2.26batch/s]ch/s]
siglip2 videos:   4%|▍         | 264/6902 [01:51<49:03,  2.26batch/s]ch/s]

-- mean: R1 64.80  mAP 76.19  mINP 76.19
-- mean_s8: R1 64.90  mAP 76.66  mINP 76.66
-- max: R1 64.00  mAP 75.55  mINP 75.55
-- query_max: R1 68.10  mAP 78.87  mINP 78.87
== Perception Encoder L/14 | activitynet/sentence | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  68%|██████▊   | 4677/6902 [37:55<19:46,  1.87batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
siglip2 videos:  68%|██████▊   | 4678/6902 [37:56<20:55,  1.77batch/s][A
pe_core_l14 texts:   3%|▎         | 7/227 [00:00<00:07, 29.33batch/s]
pe_core_l14 texts:   5%|▍         | 11/227 [00:00<00:06, 30.87batch/s]
pe_core_l14 texts:   7%|▋         | 16/227 [00:00<00:06, 34.08batch/s]
siglip2 videos:  68%|██████▊   | 4679/6902 [37:56<19:53,  1.86batch/s]
pe_core_l14 texts:  11%|█         | 25/227 [00:00<00:05, 36.35batch/s]
pe_core_l14 texts:  13%|█▎        | 29/227 [00:00<00:05, 35.75batch/s]
pe_core_l14 texts:  15%|█▍        | 33/227 [00:00<00:05, 36.21batch/s]
siglip2 videos:  68%|██████▊   | 4680/6902 [37:57<19:08,  1.94batch/s]
pe_core_l14 texts:  18%|█▊        | 41/227 [00:01<00:04, 37.57batch/s]
pe_core_l14 texts:  20%|█▉        | 45/227 [00:01<00:04, 37.22batch/s]
pe_core_l14 texts:  22%|██▏       | 49/227 [00:01<00:04, 37.56batch/s]
pe_core_l14 texts:  23%|██▎       | 53/227 [00:01<00:04, 37.25batch/s]
siglip2 videos:  68%|██████▊   | 4681/6902 [37:57<18:33,  1.99batch/s]
pe_core_l14 texts:  27%|██▋       | 61/227 [00:01<00:04, 34.95batch/s]
pe_core_l14 texts:  29%|██▉       | 66/227 [00:01<00:04, 36.91batch/s]
pe_core_l14 texts:  31%|███       | 70/227 [00:01<00:04, 37.25batch/s]
siglip2 videos:  68%|██████▊   | 4682/6902 [37:58<18:08,  2.04batch/s]
pe_core_l14 texts:  35%|███▍      | 79/227 [00:02<00:03, 37.38batch/s]
pe_core_l14 texts:  37%|███▋      | 84/227 [00:02<00:03, 38.53batch/s]
pe_core_l14 texts:  39%|███▉      | 88/227 [00:02<00:03, 38.31batch/s]
siglip2 videos:  68%|██████▊   | 4683/6902 [37:58<17:52,  2.07batch/s]
pe_core_l14 texts:  42%|████▏     | 96/227 [00:02<00:03, 37.81batch/s]
pe_core_l14 texts:  44%|████▍     | 101/227 [00:02<00:03, 38.68batch/s]
pe_core_l14 texts:  46%|████▋     | 105/227 [00:02<00:03, 38.09batch/s]
siglip2 videos:  68%|██████▊   | 4684/6902 [37:59<17:42,  2.09batch/s]]
pe_core_l14 texts:  50%|█████     | 114/227 [00:03<00:03, 37.46batch/s]
pe_core_l14 texts:  52%|█████▏    | 119/227 [00:03<00:02, 38.64batch/s]
pe_core_l14 texts:  54%|█████▍    | 123/227 [00:03<00:02, 38.24batch/s]
siglip2 videos:  68%|██████▊   | 4685/6902 [37:59<17:30,  2.11batch/s]]
pe_core_l14 texts:  58%|█████▊    | 132/227 [00:03<00:02, 38.32batch/s]
pe_core_l14 texts:  60%|█████▉    | 136/227 [00:03<00:02, 38.70batch/s]
pe_core_l14 texts:  62%|██████▏   | 140/227 [00:03<00:02, 38.38batch/s]
siglip2 videos:  68%|██████▊   | 4686/6902 [38:00<17:24,  2.12batch/s]]
pe_core_l14 texts:  65%|██████▌   | 148/227 [00:03<00:02, 38.29batch/s]
pe_core_l14 texts:  67%|██████▋   | 152/227 [00:04<00:02, 36.41batch/s]
pe_core_l14 texts:  69%|██████▉   | 157/227 [00:04<00:01, 37.01batch/s]
siglip2 videos:  68%|██████▊   | 4687/6902 [38:00<17:22,  2.12batch/s]]
pe_core_l14 texts:  73%|███████▎  | 165/227 [00:04<00:01, 38.10batch/s]
pe_core_l14 texts:  74%|███████▍  | 169/227 [00:04<00:01, 37.10batch/s]
pe_core_l14 texts:  76%|███████▌  | 173/227 [00:04<00:01, 37.79batch/s]
pe_core_l14 texts:  78%|███████▊  | 177/227 [00:04<00:01, 37.89batch/s]
siglip2 videos:  68%|██████▊   | 4688/6902 [38:01<17:22,  2.12batch/s]]
pe_core_l14 texts:  81%|████████▏ | 185/227 [00:04<00:01, 37.48batch/s]
pe_core_l14 texts:  84%|████████▎ | 190/227 [00:05<00:00, 38.66batch/s]
pe_core_l14 texts:  85%|████████▌ | 194/227 [00:05<00:00, 38.38batch/s]
siglip2 videos:  68%|██████▊   | 4689/6902 [38:01<17:20,  2.13batch/s]]
pe_core_l14 texts:  89%|████████▉ | 202/227 [00:05<00:00, 37.80batch/s]
pe_core_l14 texts:  91%|█████████ | 207/227 [00:05<00:00, 38.57batch/s]
pe_core_l14 texts:  93%|█████████▎| 211/227 [00:05<00:00, 38.26batch/s]
siglip2 videos:  68%|██████▊   | 4690/6902 [38:02<17:17,  2.13batch/s]]
pe_core_l14 texts:  96%|█████████▋| 219/227 [00:05<00:00, 38.15batch/s]
pe_core_l14 texts:  98%|█████████▊| 223/227 [00:05<00:00, 36.63batch/s]
pe_core_l14 texts: 100%|██████████| 227/227 [00:06<00:00, 37.29batch/s]
siglip2 videos:  68%|██████▊   | 4718/6902 [38:17<24:26,  1.49batch/s]

-- mean: R1 38.62  mAP 51.25  mINP 51.25
-- mean_s8: R1 38.40  mAP 51.37  mINP 51.37
-- max: R1 36.80  mAP 50.01  mINP 50.01
-- query_max: R1 41.17  mAP 53.82  mINP 53.82
== Perception Encoder L/14 | activitynet/paragraph | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  81%|████████  | 5560/6902 [44:56<10:31,  2.12batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos:  81%|████████  | 5561/6902 [44:57<13:32,  1.65batch/s]
siglip2 videos:  81%|████████  | 5562/6902 [44:57<12:39,  1.76batch/s]h/s]
pe_core_l14 videos:   0%|          | 2/14612 [00:00<1:15:00,  3.25batch/s]
siglip2 videos:  81%|████████  | 5563/6902 [44:58<12:06,  1.84batch/s]h/s]
pe_core_l14 videos:   0%|          | 4/14612 [00:01<1:04:04,  3.80batch/s]
siglip2 videos:  81%|████████  | 5564/6902 [44:58<11:41,  1.91batch/s]h/s]
pe_core_l14 videos:   0%|          | 6/14612 [00:01<1:00:59,  3.99batch/s]
siglip2 videos:  81%|████████  | 5565/6902 [44:59<11:26,  1.95batch/s]h/s]
pe_core_l14 videos:   0%|          | 8/14612 [00:02<59:48,  4.07batch/s]
siglip2 videos:  81%|████████  | 5566/6902 [44:59<11:14,  1.98batch/s]s]
pe_core_l14 videos:   0%|          | 10/14612 [00:02<59:20,  4.10batch/s]
siglip2 videos:  81%|████████  | 5567/6902 [45:00<11:06,  2.00batch/s]/s]
pe_core_l14 videos:   0%|          | 12/14612 [00:03<59:09,  4.11batch/s]
siglip2 videos:  81%|████████  | 5568/6902 [45:00<10:59,  2.02batch/s]/s]
pe_core_l14 videos:   0%|          | 14/14612 [00:03<58:54,  4.13batch/s]
siglip2 videos:  81%|████████  | 5569/6902 [45:01<10:55,  2.03batch/s]/s]
pe_core_l14 videos:   0%|          | 16/14612 [00:04<58:47,  4.14batch/s]
siglip2 videos:  81%|████████  | 5570/6902 [45:01<10:49,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 18/14612 [00:04<58:12,  4.18batch/s]
siglip2 videos:  81%|████████  | 5571/6902 [45:02<10:46,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 20/14612 [00:05<58:13,  4.18batch/s]
siglip2 videos:  81%|████████  | 5572/6902 [45:02<10:48,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 22/14612 [00:05<58:50,  4.13batch/s]
siglip2 videos:  81%|████████  | 5573/6902 [45:03<10:46,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 24/14612 [00:05<58:44,  4.14batch/s]
siglip2 videos:  81%|████████  | 5574/6902 [45:03<10:44,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 26/14612 [00:06<58:30,  4.15batch/s]
siglip2 videos:  81%|████████  | 5575/6902 [45:04<10:42,  2.07batch/s]/s]
pe_core_l14 videos:   0%|          | 28/14612 [00:06<58:23,  4.16batch/s]
siglip2 videos:  81%|████████  | 5576/6902 [45:04<10:40,  2.07batch/s]/s]
pe_core_l14 videos:   0%|          | 30/14612 [00:07<58:17,  4.17batch/s]
siglip2 videos:  81%|████████  | 5577/6902 [45:05<10:38,  2.07batch/s]/s]
pe_core_l14 videos:   0%|          | 32/14612 [00:07<58:10,  4.18batch/s]
siglip2 videos:  81%|████████  | 5578/6902 [45:05<10:40,  2.07batch/s]/s]
pe_core_l14 videos:   0%|          | 34/14612 [00:08<58:35,  4.15batch/s]
siglip2 videos:  81%|████████  | 5579/6902 [45:06<10:42,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 36/14612 [00:08<58:54,  4.12batch/s]
siglip2 videos:  81%|████████  | 5580/6902 [45:06<10:43,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 38/14612 [00:09<59:02,  4.11batch/s]
siglip2 videos:  81%|████████  | 5581/6902 [45:07<10:39,  2.07batch/s]/s]
pe_core_l14 videos:   0%|          | 40/14612 [00:09<58:25,  4.16batch/s]
siglip2 videos:  81%|████████  | 5582/6902 [45:07<10:41,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 42/14612 [00:10<58:59,  4.12batch/s]
siglip2 videos:  81%|████████  | 5583/6902 [45:08<10:38,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 44/14612 [00:10<58:27,  4.15batch/s]
siglip2 videos:  81%|████████  | 5584/6902 [45:08<10:41,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 46/14612 [00:11<58:58,  4.12batch/s]
siglip2 videos:  81%|████████  | 5585/6902 [45:09<10:40,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 48/14612 [00:11<58:48,  4.13batch/s]
siglip2 videos:  81%|████████  | 5586/6902 [45:09<10:40,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 50/14612 [00:12<58:56,  4.12batch/s]
siglip2 videos:  81%|████████  | 5587/6902 [45:10<10:39,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 52/14612 [00:12<58:37,  4.14batch/s]
siglip2 videos:  81%|████████  | 5588/6902 [45:10<10:41,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 54/14612 [00:13<59:06,  4.10batch/s]
siglip2 videos:  81%|████████  | 5589/6902 [45:11<10:44,  2.04batch/s]/s]
pe_core_l14 videos:   0%|          | 56/14612 [00:13<59:40,  4.07batch/s]
siglip2 videos:  81%|████████  | 5590/6902 [45:11<10:40,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 58/14612 [00:14<58:50,  4.12batch/s]
siglip2 videos:  81%|████████  | 5591/6902 [45:12<10:40,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 60/14612 [00:14<58:59,  4.11batch/s]
siglip2 videos:  81%|████████  | 5592/6902 [45:12<10:41,  2.04batch/s]/s]
pe_core_l14 videos:   0%|          | 62/14612 [00:15<59:16,  4.09batch/s]
siglip2 videos:  81%|████████  | 5593/6902 [45:13<10:40,  2.04batch/s]/s]
pe_core_l14 videos:   0%|          | 64/14612 [00:15<59:11,  4.10batch/s]
siglip2 videos:  81%|████████  | 5594/6902 [45:13<10:39,  2.04batch/s]/s]
pe_core_l14 videos:   0%|          | 66/14612 [00:16<59:04,  4.10batch/s]
siglip2 videos:  81%|████████  | 5595/6902 [45:13<10:37,  2.05batch/s]/s]
pe_core_l14 videos:   0%|          | 68/14612 [00:16<58:43,  4.13batch/s]
siglip2 videos:  81%|████████  | 5596/6902 [45:14<10:35,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 70/14612 [00:17<58:34,  4.14batch/s]
siglip2 videos:  81%|████████  | 5597/6902 [45:14<10:33,  2.06batch/s]/s]
pe_core_l14 videos:   0%|          | 72/14612 [00:17<58:22,  4.15batch/s]
siglip2 videos:  81%|████████  | 5598/6902 [45:15<10:31,  2.07batch/s]/s]
pe_core_l14 videos:   1%|          | 74/14612 [00:18<58:13,  4.16batch/s]
siglip2 videos:  81%|████████  | 5599/6902 [45:15<10:31,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 76/14612 [00:18<58:33,  4.14batch/s]
siglip2 videos:  81%|████████  | 5600/6902 [45:16<10:32,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 78/14612 [00:19<58:35,  4.13batch/s]
siglip2 videos:  81%|████████  | 5601/6902 [45:16<10:31,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 80/14612 [00:19<58:26,  4.14batch/s]
siglip2 videos:  81%|████████  | 5602/6902 [45:17<10:30,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 82/14612 [00:20<58:30,  4.14batch/s]
siglip2 videos:  81%|████████  | 5603/6902 [45:17<10:27,  2.07batch/s]/s]
pe_core_l14 videos:   1%|          | 84/14612 [00:20<58:02,  4.17batch/s]
siglip2 videos:  81%|████████  | 5604/6902 [45:18<10:26,  2.07batch/s]/s]
pe_core_l14 videos:   1%|          | 86/14612 [00:21<58:03,  4.17batch/s]
siglip2 videos:  81%|████████  | 5605/6902 [45:18<10:25,  2.07batch/s]/s]
pe_core_l14 videos:   1%|          | 88/14612 [00:21<58:04,  4.17batch/s]
siglip2 videos:  81%|████████  | 5606/6902 [45:19<10:23,  2.08batch/s]/s]
pe_core_l14 videos:   1%|          | 90/14612 [00:21<57:49,  4.19batch/s]
siglip2 videos:  81%|████████  | 5607/6902 [45:19<10:24,  2.08batch/s]/s]
pe_core_l14 videos:   1%|          | 92/14612 [00:22<58:03,  4.17batch/s]
siglip2 videos:  81%|████████▏ | 5608/6902 [45:20<10:28,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 94/14612 [00:22<58:48,  4.11batch/s]
siglip2 videos:  81%|████████▏ | 5609/6902 [45:20<10:28,  2.06batch/s]/s]
pe_core_l14 videos:   1%|          | 96/14612 [00:23<58:51,  4.11batch/s]
siglip2 videos:  81%|████████▏ | 5610/6902 [45:21<10:29,  2.05batch/s]/s]
pe_core_l14 videos:   1%|          | 98/14612 [00:23<59:06,  4.09batch/s]
siglip2 videos:  81%|████████▏ | 5611/6902 [45:21<10:28,  2.05batch/s]/s]
pe_core_l14 videos:   1%|          | 100/14612 [00:24<58:46,  4.12batch/s]
siglip2 videos:  81%|████████▏ | 5612/6902 [45:22<10:44,  2.00batch/s]tch/s]
pe_core_l14 videos:   1%|          | 102/14612 [00:25<1:04:04,  3.77batch/s]
siglip2 videos:  81%|████████▏ | 5613/6902 [45:22<10:33,  2.03batch/s]tch/s]
siglip2 videos:  81%|████████▏ | 5614/6902 [45:23<10:49,  1.98batch/s]tch/s]
pe_core_l14 videos:   1%|          | 105/14612 [00:25<1:09:13,  3.49batch/s]
siglip2 videos:  81%|████████▏ | 5615/6902 [45:23<10:39,  2.01batch/s]tch/s]
pe_core_l14 videos:   1%|          | 107/14612 [00:26<1:03:19,  3.82batch/s]
siglip2 videos:  81%|████████▏ | 5616/6902 [45:24<10:35,  2.02batch/s]tch/s]
pe_core_l14 videos:   1%|          | 109/14612 [00:26<1:00:54,  3.97batch/s]
siglip2 videos:  81%|████████▏ | 5617/6902 [45:24<10:55,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 111/14612 [00:27<1:02:57,  3.84batch/s]
siglip2 videos:  81%|████████▏ | 5618/6902 [45:25<11:06,  1.93batch/s]tch/s]
pe_core_l14 videos:   1%|          | 113/14612 [00:28<1:03:32,  3.80batch/s]
siglip2 videos:  81%|████████▏ | 5619/6902 [45:25<10:43,  1.99batch/s]tch/s]
siglip2 videos:  81%|████████▏ | 5620/6902 [45:26<10:51,  1.97batch/s]tch/s]
pe_core_l14 videos:   1%|          | 116/14612 [00:29<1:09:33,  3.47batch/s]
siglip2 videos:  81%|████████▏ | 5621/6902 [45:26<11:07,  1.92batch/s]tch/s]
pe_core_l14 videos:   1%|          | 118/14612 [00:29<1:07:10,  3.60batch/s]
siglip2 videos:  81%|████████▏ | 5622/6902 [45:27<11:16,  1.89batch/s]tch/s]
pe_core_l14 videos:   1%|          | 120/14612 [00:30<1:05:50,  3.67batch/s]
siglip2 videos:  81%|████████▏ | 5623/6902 [45:27<11:07,  1.92batch/s]tch/s]
pe_core_l14 videos:   1%|          | 122/14612 [00:30<1:03:07,  3.83batch/s]
siglip2 videos:  81%|████████▏ | 5624/6902 [45:28<11:17,  1.89batch/s]tch/s]
pe_core_l14 videos:   1%|          | 124/14612 [00:31<1:03:57,  3.78batch/s]
siglip2 videos:  81%|████████▏ | 5625/6902 [45:28<11:10,  1.90batch/s]tch/s]
pe_core_l14 videos:   1%|          | 126/14612 [00:31<1:02:33,  3.86batch/s]
siglip2 videos:  82%|████████▏ | 5626/6902 [45:29<11:12,  1.90batch/s]tch/s]
pe_core_l14 videos:   1%|          | 128/14612 [00:32<1:02:40,  3.85batch/s]
siglip2 videos:  82%|████████▏ | 5627/6902 [45:30<11:01,  1.93batch/s]tch/s]
pe_core_l14 videos:   1%|          | 130/14612 [00:32<1:01:16,  3.94batch/s]
siglip2 videos:  82%|████████▏ | 5628/6902 [45:30<11:07,  1.91batch/s]tch/s]
pe_core_l14 videos:   1%|          | 132/14612 [00:33<1:02:17,  3.87batch/s]
siglip2 videos:  82%|████████▏ | 5629/6902 [45:31<10:59,  1.93batch/s]tch/s]
pe_core_l14 videos:   1%|          | 134/14612 [00:33<1:01:14,  3.94batch/s]
siglip2 videos:  82%|████████▏ | 5630/6902 [45:31<10:48,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 136/14612 [00:34<1:00:02,  4.02batch/s]
siglip2 videos:  82%|████████▏ | 5631/6902 [45:32<10:40,  1.99batch/s]h/s]
pe_core_l14 videos:   1%|          | 138/14612 [00:34<59:28,  4.06batch/s]
siglip2 videos:  82%|████████▏ | 5632/6902 [45:32<10:34,  2.00batch/s]h/s]
pe_core_l14 videos:   1%|          | 140/14612 [00:35<59:20,  4.06batch/s]
siglip2 videos:  82%|████████▏ | 5633/6902 [45:33<10:36,  1.99batch/s]tch/s]
pe_core_l14 videos:   1%|          | 142/14612 [00:35<59:47,  4.03batch/s]
siglip2 videos:  82%|████████▏ | 5634/6902 [45:33<10:49,  1.95batch/s]tch/s]
pe_core_l14 videos:   1%|          | 144/14612 [00:36<1:01:50,  3.90batch/s]
siglip2 videos:  82%|████████▏ | 5635/6902 [45:34<10:39,  1.98batch/s]tch/s]
pe_core_l14 videos:   1%|          | 146/14612 [00:36<1:00:09,  4.01batch/s]
siglip2 videos:  82%|████████▏ | 5636/6902 [45:34<10:42,  1.97batch/s]tch/s]
pe_core_l14 videos:   1%|          | 148/14612 [00:37<1:00:39,  3.97batch/s]
siglip2 videos:  82%|████████▏ | 5637/6902 [45:35<10:45,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 150/14612 [00:37<1:01:04,  3.95batch/s]
siglip2 videos:  82%|████████▏ | 5638/6902 [45:35<10:37,  1.98batch/s]tch/s]
pe_core_l14 videos:   1%|          | 152/14612 [00:38<1:00:05,  4.01batch/s]
siglip2 videos:  82%|████████▏ | 5639/6902 [45:36<10:44,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 154/14612 [00:38<1:01:16,  3.93batch/s]
siglip2 videos:  82%|████████▏ | 5640/6902 [45:36<10:36,  1.98batch/s]tch/s]
pe_core_l14 videos:   1%|          | 156/14612 [00:39<59:58,  4.02batch/s]
siglip2 videos:  82%|████████▏ | 5641/6902 [45:37<10:30,  2.00batch/s]h/s]
pe_core_l14 videos:   1%|          | 158/14612 [00:39<59:29,  4.05batch/s]
siglip2 videos:  82%|████████▏ | 5642/6902 [45:37<10:33,  1.99batch/s]tch/s]
pe_core_l14 videos:   1%|          | 160/14612 [00:40<1:00:04,  4.01batch/s]
siglip2 videos:  82%|████████▏ | 5643/6902 [45:38<10:42,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 162/14612 [00:40<1:01:13,  3.93batch/s]
siglip2 videos:  82%|████████▏ | 5644/6902 [45:38<10:41,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 164/14612 [00:41<1:01:03,  3.94batch/s]
siglip2 videos:  82%|████████▏ | 5645/6902 [45:39<10:35,  1.98batch/s]tch/s]
pe_core_l14 videos:   1%|          | 166/14612 [00:41<1:00:04,  4.01batch/s]
siglip2 videos:  82%|████████▏ | 5646/6902 [45:39<10:29,  2.00batch/s]h/s]
pe_core_l14 videos:   1%|          | 168/14612 [00:42<59:34,  4.04batch/s]
siglip2 videos:  82%|████████▏ | 5647/6902 [45:40<10:49,  1.93batch/s]tch/s]
pe_core_l14 videos:   1%|          | 170/14612 [00:42<1:03:14,  3.81batch/s]
siglip2 videos:  82%|████████▏ | 5648/6902 [45:40<10:48,  1.93batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5649/6902 [45:41<10:38,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|          | 173/14612 [00:43<1:11:43,  3.36batch/s]
siglip2 videos:  82%|████████▏ | 5650/6902 [45:41<10:30,  1.99batch/s]tch/s]
pe_core_l14 videos:   1%|          | 175/14612 [00:44<1:05:03,  3.70batch/s]
siglip2 videos:  82%|████████▏ | 5651/6902 [45:42<10:44,  1.94batch/s]tch/s]
pe_core_l14 videos:   1%|          | 177/14612 [00:44<1:04:38,  3.72batch/s]
siglip2 videos:  82%|████████▏ | 5652/6902 [45:42<10:39,  1.95batch/s]tch/s]
pe_core_l14 videos:   1%|          | 179/14612 [00:45<1:02:25,  3.85batch/s]
siglip2 videos:  82%|████████▏ | 5653/6902 [45:43<10:46,  1.93batch/s]tch/s]
pe_core_l14 videos:   1%|          | 181/14612 [00:45<1:02:42,  3.84batch/s]
siglip2 videos:  82%|████████▏ | 5654/6902 [45:43<10:52,  1.91batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 183/14612 [00:46<1:03:07,  3.81batch/s]
siglip2 videos:  82%|████████▏ | 5655/6902 [45:44<10:50,  1.92batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 185/14612 [00:46<1:02:21,  3.86batch/s]
siglip2 videos:  82%|████████▏ | 5656/6902 [45:44<11:00,  1.89batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 187/14612 [00:47<1:03:39,  3.78batch/s]
siglip2 videos:  82%|████████▏ | 5657/6902 [45:45<10:39,  1.95batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5658/6902 [45:45<10:30,  1.97batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 190/14612 [00:48<1:10:43,  3.40batch/s]
siglip2 videos:  82%|████████▏ | 5659/6902 [45:46<10:32,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 192/14612 [00:49<1:06:02,  3.64batch/s]
siglip2 videos:  82%|████████▏ | 5660/6902 [45:46<10:40,  1.94batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 194/14612 [00:49<1:18:23,  3.07batch/s]
siglip2 videos:  82%|████████▏ | 5661/6902 [45:47<10:22,  1.99batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5662/6902 [45:47<10:32,  1.96batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 197/14612 [00:50<1:08:07,  3.53batch/s]
siglip2 videos:  82%|████████▏ | 5663/6902 [45:48<10:40,  1.94batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 199/14612 [00:51<1:07:51,  3.54batch/s]
siglip2 videos:  82%|████████▏ | 5664/6902 [45:48<10:23,  1.98batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5665/6902 [45:49<10:43,  1.92batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 202/14612 [00:52<1:11:55,  3.34batch/s]
siglip2 videos:  82%|████████▏ | 5666/6902 [45:49<10:50,  1.90batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5667/6902 [45:50<10:35,  1.94batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 205/14612 [00:53<1:15:44,  3.17batch/s]
siglip2 videos:  82%|████████▏ | 5668/6902 [45:50<10:49,  1.90batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 207/14612 [00:53<1:10:23,  3.41batch/s]
siglip2 videos:  82%|████████▏ | 5669/6902 [45:51<10:58,  1.87batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 209/14612 [00:54<1:07:38,  3.55batch/s]
siglip2 videos:  82%|████████▏ | 5670/6902 [45:52<10:50,  1.90batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 211/14612 [00:54<1:04:14,  3.74batch/s]
siglip2 videos:  82%|████████▏ | 5671/6902 [45:52<10:46,  1.90batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 213/14612 [00:55<1:02:54,  3.82batch/s]
siglip2 videos:  82%|████████▏ | 5672/6902 [45:53<10:45,  1.91batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 215/14612 [00:55<1:02:25,  3.84batch/s]
siglip2 videos:  82%|████████▏ | 5673/6902 [45:53<10:50,  1.89batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 217/14612 [00:56<1:03:14,  3.79batch/s]
siglip2 videos:  82%|████████▏ | 5674/6902 [45:54<11:00,  1.86batch/s]tch/s]
pe_core_l14 videos:   1%|▏         | 219/14612 [00:56<1:04:20,  3.73batch/s]
siglip2 videos:  82%|████████▏ | 5675/6902 [45:54<11:03,  1.85batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 221/14612 [00:57<1:04:24,  3.72batch/s]
siglip2 videos:  82%|████████▏ | 5676/6902 [45:55<10:43,  1.91batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5677/6902 [45:55<10:28,  1.95batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 224/14612 [00:58<1:11:00,  3.38batch/s]
siglip2 videos:  82%|████████▏ | 5678/6902 [45:56<10:39,  1.91batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 226/14612 [00:58<1:07:32,  3.55batch/s]
siglip2 videos:  82%|████████▏ | 5679/6902 [45:56<10:31,  1.94batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5680/6902 [45:57<10:18,  1.97batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 229/14612 [00:59<1:12:51,  3.29batch/s]
siglip2 videos:  82%|████████▏ | 5681/6902 [45:57<10:07,  2.01batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5682/6902 [45:58<10:03,  2.02batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 232/14612 [01:00<1:13:46,  3.25batch/s]
siglip2 videos:  82%|████████▏ | 5683/6902 [45:58<10:27,  1.94batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 234/14612 [01:01<1:09:50,  3.43batch/s]
siglip2 videos:  82%|████████▏ | 5684/6902 [45:59<10:11,  1.99batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 236/14612 [01:02<1:18:48,  3.04batch/s]
siglip2 videos:  82%|████████▏ | 5685/6902 [45:59<10:03,  2.02batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5686/6902 [46:00<10:15,  1.98batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 239/14612 [01:02<1:07:10,  3.57batch/s]
siglip2 videos:  82%|████████▏ | 5687/6902 [46:00<10:27,  1.94batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 241/14612 [01:03<1:05:21,  3.66batch/s]
siglip2 videos:  82%|████████▏ | 5688/6902 [46:01<10:37,  1.90batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 243/14612 [01:04<1:04:53,  3.69batch/s]
siglip2 videos:  82%|████████▏ | 5689/6902 [46:01<10:32,  1.92batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 245/14612 [01:04<1:02:56,  3.80batch/s]
siglip2 videos:  82%|████████▏ | 5690/6902 [46:02<10:17,  1.96batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5691/6902 [46:02<10:09,  1.99batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 248/14612 [01:05<1:10:26,  3.40batch/s]
siglip2 videos:  82%|████████▏ | 5692/6902 [46:03<10:03,  2.01batch/s]tch/s]
siglip2 videos:  82%|████████▏ | 5693/6902 [46:03<10:02,  2.01batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 251/14612 [01:06<1:13:48,  3.24batch/s]
siglip2 videos:  82%|████████▏ | 5694/6902 [46:04<09:55,  2.03batch/s]tch/s]
siglip2 videos:  83%|████████▎ | 5695/6902 [46:04<09:52,  2.04batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 254/14612 [01:07<1:13:48,  3.24batch/s]
siglip2 videos:  83%|████████▎ | 5696/6902 [46:05<09:56,  2.02batch/s]tch/s]
siglip2 videos:  83%|████████▎ | 5697/6902 [46:05<09:54,  2.03batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 257/14612 [01:08<1:14:59,  3.19batch/s]
siglip2 videos:  83%|████████▎ | 5698/6902 [46:06<10:04,  1.99batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 259/14612 [01:09<1:08:13,  3.51batch/s]
siglip2 videos:  83%|████████▎ | 5699/6902 [46:06<10:07,  1.98batch/s]tch/s]
pe_core_l14 videos:   2%|▏         | 261/14612 [01:09<1:04:29,  3.71batch/s]
siglip2 videos:  83%|████████▎ | 5700/6902 [46:07<10:09,  1.97batch/s]tch/s]

-- mean: R1 54.80  mAP 68.28  mINP 68.28
-- mean_s8: R1 54.40  mAP 68.22  mINP 68.22
-- max: R1 52.90  mAP 67.19  mINP 67.19
-- query_max: R1 56.10  mAP 69.42  mINP 69.42
== SigLIP 2 So400m | activitynet/sentence | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos:  13%|█▎        | 1932/14612 [11:18<1:37:40,  2.16batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

siglip2 texts:   1%|          | 2/227 [00:00<00:15, 14.21batch/s]
siglip2 texts:   3%|▎         | 6/227 [00:00<00:14, 15.70batch/s]2.02batch/s]
siglip2 texts:   5%|▌         | 12/227 [00:00<00:12, 17.01batch/s].32batch/s]
siglip2 texts:   7%|▋         | 16/227 [00:00<00:12, 17.45batch/s].59batch/s]
siglip2 texts:  10%|▉         | 22/227 [00:01<00:11, 17.53batch/s].82batch/s]
siglip2 texts:  11%|█▏        | 26/227 [00:01<00:11, 17.57batch/s].00batch/s]
siglip2 texts:  14%|█▍        | 32/227 [00:01<00:11, 17.52batch/s].13batch/s]
siglip2 texts:  16%|█▌        | 36/227 [00:02<00:10, 17.59batch/s].24batch/s]
siglip2 texts:  19%|█▊        | 42/227 [00:02<00:10, 17.59batch/s].31batch/s]
siglip2 texts:  20%|██        | 46/227 [00:02<00:10, 17.58batch/s].37batch/s]
siglip2 texts:  23%|██▎       | 52/227 [00:03<00:09, 17.57batch/s].41batch/s]
siglip2 texts:  25%|██▍       | 56/227 [00:03<00:09, 17.57batch/s].44batch/s]
siglip2 texts:  27%|██▋       | 62/227 [00:03<00:09, 17.56batch/s].46batch/s]
siglip2 texts:  29%|██▉       | 66/227 [00:03<00:09, 17.52batch/s].47batch/s]
siglip2 texts:  32%|███▏      | 72/227 [00:04<00:08, 17.50batch/s].48batch/s]
siglip2 texts:  33%|███▎      | 76/227 [00:04<00:08, 17.52batch/s].49batch/s]
siglip2 texts:  36%|███▌      | 82/227 [00:04<00:08, 17.46batch/s].50batch/s]
siglip2 texts:  38%|███▊      | 86/227 [00:04<00:08, 17.57batch/s].50batch/s]
siglip2 texts:  41%|████      | 92/227 [00:05<00:07, 17.46batch/s].50batch/s]
siglip2 texts:  42%|████▏     | 96/227 [00:05<00:07, 17.46batch/s].50batch/s]
siglip2 texts:  45%|████▍     | 102/227 [00:05<00:07, 17.51batch/s]49batch/s]
siglip2 texts:  47%|████▋     | 106/227 [00:06<00:06, 17.37batch/s]49batch/s]
siglip2 texts:  49%|████▉     | 112/227 [00:06<00:06, 17.31batch/s]48batch/s]
siglip2 texts:  51%|█████     | 116/227 [00:06<00:06, 17.46batch/s]48batch/s]
siglip2 texts:  54%|█████▎    | 122/227 [00:07<00:06, 17.41batch/s]49batch/s]
siglip2 texts:  56%|█████▌    | 126/227 [00:07<00:05, 17.34batch/s]48batch/s]
siglip2 texts:  58%|█████▊    | 132/227 [00:07<00:05, 17.41batch/s]48batch/s]
siglip2 texts:  60%|█████▉    | 136/227 [00:07<00:05, 17.42batch/s]48batch/s]
siglip2 texts:  63%|██████▎   | 142/227 [00:08<00:04, 17.34batch/s]48batch/s]
siglip2 texts:  64%|██████▍   | 146/227 [00:08<00:04, 17.41batch/s]48batch/s]
siglip2 texts:  67%|██████▋   | 152/227 [00:08<00:04, 17.43batch/s]48batch/s]
siglip2 texts:  69%|██████▊   | 156/227 [00:08<00:04, 17.39batch/s]48batch/s]
siglip2 texts:  71%|███████▏  | 162/227 [00:09<00:03, 17.35batch/s]48batch/s]
siglip2 texts:  73%|███████▎  | 166/227 [00:09<00:03, 17.44batch/s]48batch/s]
siglip2 texts:  76%|███████▌  | 172/227 [00:09<00:03, 17.32batch/s]48batch/s]
siglip2 texts:  78%|███████▊  | 176/227 [00:10<00:02, 17.24batch/s]47batch/s]
siglip2 texts:  80%|████████  | 182/227 [00:10<00:02, 17.28batch/s]46batch/s]
siglip2 texts:  82%|████████▏ | 186/227 [00:10<00:02, 17.45batch/s]46batch/s]
siglip2 texts:  85%|████████▍ | 192/227 [00:11<00:02, 17.32batch/s]47batch/s]
siglip2 texts:  86%|████████▋ | 196/227 [00:11<00:01, 17.24batch/s]46batch/s]
siglip2 texts:  89%|████████▉ | 202/227 [00:11<00:01, 17.24batch/s]45batch/s]
siglip2 texts:  91%|█████████ | 206/227 [00:11<00:01, 17.37batch/s]46batch/s]
siglip2 texts:  93%|█████████▎| 212/227 [00:12<00:00, 17.32batch/s]46batch/s]
siglip2 texts:  95%|█████████▌| 216/227 [00:12<00:00, 17.28batch/s]46batch/s]
siglip2 texts:  98%|█████████▊| 222/227 [00:12<00:00, 17.28batch/s]46batch/s]
siglip2 texts: 100%|██████████| 227/227 [00:13<00:00, 17.40batch/s]46batch/s]

pe_core_l14 videos:  14%|█▎        | 1978/14612 [11:32<59:22,  3.55batch/s]
pe_core_l14 videos:  14%|█▎        | 1979/14612 [11:32<59:02,  3.57batch/s]
pe_core_l14 videos:  14%|█▎        | 1980/14612 [11:32<1:05:26,  3.22batch/s]
pe_core_l14 videos:  14%|█▎        | 1981/14612 [11:33<1:11:48,  2.93batch/s]
pe_core_l14 videos:  14%|█▎        | 1982/14612 [11:33<1:16:35,  2.75batch/s]
pe_core_l14 videos:  14%|█▎        | 1983/14612 [11:34<1:26:13,  2.44batch/s]
pe_core_l14 videos:  14%|█▎        | 1984/14612 [11:34<1:27:25,  2.41batch/s]
pe_core_l14 videos:  14%|█▎        | 1985/14612 [11:34<1:23:07,  2.53batch/s]
pe_core_l14 videos:  14%|█▎        | 1986/14612 [11:35<1:23:49,  2.51batch/s]
pe_core_l14 videos:  14%|█▎        | 1987/14612 [11:35<1:19:40,  2.64batch/s]
pe_core_l14 videos:  14%|█▎        | 1988/14612 [11:36<1:22:04,  2.56batch/s]
pe_core_l14 videos:  14%|█▎        | 1989/14612 [11:36<1:35:50,  2.20batch/s]
pe_core_l14 videos:  14%|█▎        | 1990/14612 [11:37<1:28:14,  2.38batch/s]
pe_core_l14 videos:  14%|█▎        | 1991/14612 [11:37<1:30:43,  2.32batch/s]
pe_core_l14 videos:  14%|█▎        | 1992/14612 [11:37<1:35:43,  2.20batch/s]
pe_core_l14 videos:  14%|█▎        | 1993/14612 [11:38<1:30:33,  2.32batch/s]
pe_core_l14 videos:  14%|█▎        | 1994/14612 [11:38<1:26:43,  2.42batch/s]
pe_core_l14 videos:  14%|█▎        | 1995/14612 [11:39<1:31:39,  2.29batch/s]
pe_core_l14 videos:  14%|█▎        | 1996/14612 [11:39<1:32:33,  2.27batch/s]
pe_core_l14 videos:  14%|█▎        | 1997/14612 [11:40<1:30:57,  2.31batch/s]
pe_core_l14 videos:  14%|█▎        | 1998/14612 [11:40<1:34:29,  2.23batch/s]
pe_core_l14 videos:  14%|█▎        | 1999/14612 [11:41<1:36:05,  2.19batch/s]
pe_core_l14 videos:  14%|█▎        | 2000/14612 [11:41<1:35:44,  2.20batch/s]
pe_core_l14 videos:  14%|█▎        | 2001/14612 [11:41<1:28:47,  2.37batch/s]
pe_core_l14 videos:  14%|█▎        | 2002/14612 [11:42<1:21:45,  2.57batch/s]
pe_core_l14 videos:  14%|█▎        | 2003/14612 [11:42<1:23:34,  2.51batch/s]
pe_core_l14 videos:  14%|█▎        | 2004/14612 [11:42<1:20:45,  2.60batch/s]
pe_core_l14 videos:  14%|█▎        | 2005/14612 [11:43<1:17:45,  2.70batch/s]
pe_core_l14 videos:  14%|█▎        | 2006/14612 [11:43<1:14:29,  2.82batch/s]
pe_core_l14 videos:  14%|█▎        | 2007/14612 [11:43<1:13:17,  2.87batch/s]
pe_core_l14 videos:  14%|█▎        | 2008/14612 [11:44<1:09:50,  3.01batch/s]
pe_core_l14 videos:  14%|█▎        | 2009/14612 [11:44<1:14:13,  2.83batch/s]
pe_core_l14 videos:  14%|█▍        | 2010/14612 [11:44<1:11:59,  2.92batch/s]
pe_core_l14 videos:  14%|█▍        | 2011/14612 [11:45<1:13:10,  2.87batch/s]
pe_core_l14 videos:  14%|█▍        | 2012/14612 [11:45<1:11:58,  2.92batch/s]
pe_core_l14 videos:  14%|█▍        | 2013/14612 [11:45<1:08:45,  3.05batch/s]
pe_core_l14 videos:  14%|█▍        | 2014/14612 [11:46<1:10:59,  2.96batch/s]
pe_core_l14 videos:  14%|█▍        | 2015/14612 [11:46<1:09:17,  3.03batch/s]
pe_core_l14 videos:  14%|█▍        | 2016/14612 [11:47<1:56:56,  1.80batch/s]

-- mean: R1 30.94  mAP 44.07  mINP 44.07
-- mean_s8: R1 30.58  mAP 43.83  mINP 43.83
-- max: R1 29.89  mAP 43.16  mINP 43.16
-- query_max: R1 33.78  mAP 46.90  mINP 46.90
== SigLIP 2 So400m | activitynet/paragraph | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos:  14%|█▍        | 2017/14612 [11:48<2:12:01,  1.59batch/s]
pe_core_l14 videos:  14%|█▍        | 2018/14612 [11:48<1:50:04,  1.91batch/s]
pe_core_l14 videos:  14%|█▍        | 2019/14612 [11:49<1:34:36,  2.22batch/s]
pe_core_l14 videos:  14%|█▍        | 2020/14612 [11:49<1:23:43,  2.51batch/s]
pe_core_l14 videos:  14%|█▍        | 2021/14612 [11:49<1:15:59,  2.76batch/s]
pe_core_l14 videos:  14%|█▍        | 2022/14612 [11:49<1:10:19,  2.98batch/s]
pe_core_l14 videos:  14%|█▍        | 2023/14612 [11:50<1:06:41,  3.15batch/s]
pe_core_l14 videos:  14%|█▍        | 2024/14612 [11:50<1:04:04,  3.27batch/s]
pe_core_l14 videos:  14%|█▍        | 2025/14612 [11:50<1:02:16,  3.37batch/s]
pe_core_l14 videos:  14%|█▍        | 2026/14612 [11:50<1:01:00,  3.44batch/s]
pe_core_l14 videos:  14%|█▍        | 2027/14612 [11:51<1:00:17,  3.48batch/s]
pe_core_l14 videos:  14%|█▍        | 2028/14612 [11:51<59:29,  3.53batch/s]
pe_core_l14 videos:  14%|█▍        | 2029/14612 [11:51<59:09,  3.54batch/s]
pe_core_l14 videos:  14%|█▍        | 2030/14612 [11:52<58:32,  3.58batch/s]
pe_core_l14 videos:  14%|█▍        | 2031/14612 [11:52<58:28,  3.59batch/s]
pe_core_l14 videos:  14%|█▍        | 2032/14612 [11:52<58:22,  3.59batch/s]
pe_core_l14 videos:  14%|█▍        | 2033/14612 [11:52<58:13,  3.60batch/s]
pe_core_l14 videos:  14%|█▍        | 2034/14612 [11:53<57:46,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2035/14612 [11:53<57:43,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2036/14612 [11:53<57:42,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2037/14612 [11:53<57:36,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2038/14612 [11:54<57:52,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2039/14612 [11:54<57:45,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2040/14612 [11:54<57:59,  3.61batch/s]
pe_core_l14 videos:  14%|█▍        | 2041/14612 [11:55<57:54,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2042/14612 [11:55<57:52,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2043/14612 [11:55<57:34,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2044/14612 [11:55<57:41,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2045/14612 [11:56<57:13,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2046/14612 [11:56<57:12,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2047/14612 [11:56<56:49,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2048/14612 [11:57<56:37,  3.70batch/s]
pe_core_l14 videos:  14%|█▍        | 2049/14612 [11:57<56:29,  3.71batch/s]
pe_core_l14 videos:  14%|█▍        | 2050/14612 [11:57<57:02,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2051/14612 [11:57<56:59,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2052/14612 [11:58<57:04,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2053/14612 [11:58<56:51,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2054/14612 [11:58<56:48,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2055/14612 [11:58<56:48,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2056/14612 [11:59<56:52,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2057/14612 [11:59<56:53,  3.68batch/s]
pe_core_l14 videos:  14%|█▍        | 2058/14612 [11:59<56:44,  3.69batch/s]
pe_core_l14 videos:  14%|█▍        | 2059/14612 [11:59<56:40,  3.69batch/s]
pe_core_l14 videos:  14%|█▍        | 2060/14612 [12:00<56:57,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2061/14612 [12:00<57:04,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2062/14612 [12:00<57:07,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2063/14612 [12:01<56:57,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2064/14612 [12:01<57:07,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2065/14612 [12:01<57:09,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2066/14612 [12:01<57:12,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2067/14612 [12:02<57:10,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2068/14612 [12:02<57:25,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2069/14612 [12:02<57:19,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2070/14612 [12:03<58:07,  3.60batch/s]
pe_core_l14 videos:  14%|█▍        | 2071/14612 [12:03<57:35,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2072/14612 [12:03<57:23,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2073/14612 [12:03<57:29,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2074/14612 [12:04<57:19,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2075/14612 [12:04<57:37,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2076/14612 [12:04<57:39,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2077/14612 [12:04<57:54,  3.61batch/s]
pe_core_l14 videos:  14%|█▍        | 2078/14612 [12:05<59:23,  3.52batch/s]
pe_core_l14 videos:  14%|█▍        | 2079/14612 [12:05<58:49,  3.55batch/s]
pe_core_l14 videos:  14%|█▍        | 2080/14612 [12:05<58:15,  3.58batch/s]
pe_core_l14 videos:  14%|█▍        | 2081/14612 [12:06<57:55,  3.61batch/s]
pe_core_l14 videos:  14%|█▍        | 2082/14612 [12:06<57:41,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2083/14612 [12:06<57:35,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2084/14612 [12:06<57:32,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2085/14612 [12:07<57:22,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2086/14612 [12:07<57:17,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2087/14612 [12:07<57:40,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2088/14612 [12:07<57:31,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2089/14612 [12:08<57:18,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2090/14612 [12:08<57:16,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2091/14612 [12:08<57:03,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2092/14612 [12:09<56:48,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2093/14612 [12:09<57:05,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2094/14612 [12:09<57:18,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2095/14612 [12:09<57:08,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2096/14612 [12:10<57:04,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2097/14612 [12:10<56:53,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2098/14612 [12:10<56:54,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2099/14612 [12:10<57:01,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2100/14612 [12:11<57:01,  3.66batch/s]
pe_core_l14 videos:  14%|█▍        | 2101/14612 [12:11<56:47,  3.67batch/s]
pe_core_l14 videos:  14%|█▍        | 2102/14612 [12:11<57:09,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2103/14612 [12:12<57:14,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2104/14612 [12:12<57:04,  3.65batch/s]
pe_core_l14 videos:  14%|█▍        | 2105/14612 [12:12<57:13,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2106/14612 [12:12<57:23,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2107/14612 [12:13<57:17,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2108/14612 [12:13<57:24,  3.63batch/s]
pe_core_l14 videos:  14%|█▍        | 2109/14612 [12:13<57:19,  3.64batch/s]
pe_core_l14 videos:  14%|█▍        | 2110/14612 [12:14<57:36,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2111/14612 [12:14<57:54,  3.60batch/s]
pe_core_l14 videos:  14%|█▍        | 2112/14612 [12:14<57:29,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2113/14612 [12:14<57:42,  3.61batch/s]
pe_core_l14 videos:  14%|█▍        | 2114/14612 [12:15<57:49,  3.60batch/s]
pe_core_l14 videos:  14%|█▍        | 2115/14612 [12:15<58:08,  3.58batch/s]
pe_core_l14 videos:  14%|█▍        | 2116/14612 [12:15<57:59,  3.59batch/s]
pe_core_l14 videos:  14%|█▍        | 2117/14612 [12:15<57:30,  3.62batch/s]
pe_core_l14 videos:  14%|█▍        | 2118/14612 [12:16<57:42,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2119/14612 [12:16<58:09,  3.58batch/s]
pe_core_l14 videos:  15%|█▍        | 2120/14612 [12:16<57:32,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2121/14612 [12:17<57:30,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2122/14612 [12:17<57:20,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2123/14612 [12:17<57:10,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2124/14612 [12:17<57:15,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2125/14612 [12:18<56:55,  3.66batch/s]
pe_core_l14 videos:  15%|█▍        | 2126/14612 [12:18<56:53,  3.66batch/s]
pe_core_l14 videos:  15%|█▍        | 2127/14612 [12:18<56:50,  3.66batch/s]
pe_core_l14 videos:  15%|█▍        | 2128/14612 [12:18<56:44,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2129/14612 [12:19<56:59,  3.65batch/s]
pe_core_l14 videos:  15%|█▍        | 2130/14612 [12:19<56:43,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2131/14612 [12:19<56:43,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2132/14612 [12:20<56:41,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2133/14612 [12:20<56:42,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2134/14612 [12:20<56:37,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2135/14612 [12:20<57:00,  3.65batch/s]
pe_core_l14 videos:  15%|█▍        | 2136/14612 [12:21<57:12,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2137/14612 [12:21<57:12,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2138/14612 [12:21<57:24,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2139/14612 [12:22<57:30,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2140/14612 [12:22<57:23,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2141/14612 [12:22<57:29,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2142/14612 [12:22<57:42,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2143/14612 [12:23<57:47,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2144/14612 [12:23<57:47,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2145/14612 [12:23<57:28,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2146/14612 [12:23<57:35,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2147/14612 [12:24<57:44,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2148/14612 [12:24<57:19,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2149/14612 [12:24<57:28,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2150/14612 [12:25<57:37,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2151/14612 [12:25<57:33,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2152/14612 [12:25<57:26,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2153/14612 [12:25<56:42,  3.66batch/s]
pe_core_l14 videos:  15%|█▍        | 2154/14612 [12:26<57:02,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2155/14612 [12:26<56:55,  3.65batch/s]
pe_core_l14 videos:  15%|█▍        | 2156/14612 [12:26<57:06,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2157/14612 [12:26<57:14,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2158/14612 [12:27<57:02,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2159/14612 [12:27<59:46,  3.47batch/s]
pe_core_l14 videos:  15%|█▍        | 2160/14612 [12:27<58:50,  3.53batch/s]
pe_core_l14 videos:  15%|█▍        | 2161/14612 [12:28<58:12,  3.57batch/s]
pe_core_l14 videos:  15%|█▍        | 2162/14612 [12:28<57:43,  3.59batch/s]
pe_core_l14 videos:  15%|█▍        | 2163/14612 [12:28<57:28,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2164/14612 [12:28<57:12,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2165/14612 [12:29<57:15,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2166/14612 [12:29<57:13,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2167/14612 [12:29<57:14,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2168/14612 [12:30<57:01,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2169/14612 [12:30<57:09,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2170/14612 [12:30<57:07,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2171/14612 [12:30<56:51,  3.65batch/s]
pe_core_l14 videos:  15%|█▍        | 2172/14612 [12:31<56:59,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2173/14612 [12:31<56:59,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2174/14612 [12:31<57:07,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2175/14612 [12:31<57:08,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2176/14612 [12:32<56:50,  3.65batch/s]
pe_core_l14 videos:  15%|█▍        | 2177/14612 [12:32<56:25,  3.67batch/s]
pe_core_l14 videos:  15%|█▍        | 2178/14612 [12:32<59:40,  3.47batch/s]
pe_core_l14 videos:  15%|█▍        | 2179/14612 [12:33<58:51,  3.52batch/s]
pe_core_l14 videos:  15%|█▍        | 2180/14612 [12:33<58:10,  3.56batch/s]
pe_core_l14 videos:  15%|█▍        | 2181/14612 [12:33<57:32,  3.60batch/s]
pe_core_l14 videos:  15%|█▍        | 2182/14612 [12:33<57:14,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2183/14612 [12:34<57:25,  3.61batch/s]
pe_core_l14 videos:  15%|█▍        | 2184/14612 [12:34<57:08,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2185/14612 [12:34<57:01,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2186/14612 [12:35<56:50,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2187/14612 [12:35<56:53,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2188/14612 [12:35<56:54,  3.64batch/s]
pe_core_l14 videos:  15%|█▍        | 2189/14612 [12:35<57:07,  3.62batch/s]
pe_core_l14 videos:  15%|█▍        | 2190/14612 [12:36<57:00,  3.63batch/s]
pe_core_l14 videos:  15%|█▍        | 2191/14612 [12:36<56:50,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2192/14612 [12:36<56:26,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2193/14612 [12:36<56:42,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2194/14612 [12:37<56:43,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2195/14612 [12:37<56:39,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2196/14612 [12:37<56:38,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2197/14612 [12:38<59:21,  3.49batch/s]
pe_core_l14 videos:  15%|█▌        | 2198/14612 [12:38<58:29,  3.54batch/s]
pe_core_l14 videos:  15%|█▌        | 2199/14612 [12:38<57:59,  3.57batch/s]
pe_core_l14 videos:  15%|█▌        | 2200/14612 [12:38<57:25,  3.60batch/s]
pe_core_l14 videos:  15%|█▌        | 2201/14612 [12:39<57:07,  3.62batch/s]
pe_core_l14 videos:  15%|█▌        | 2202/14612 [12:39<56:40,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2203/14612 [12:39<56:20,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2204/14612 [12:39<56:14,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2205/14612 [12:40<56:26,  3.66batch/s]
pe_core_l14 videos:  15%|█▌        | 2206/14612 [12:40<56:07,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2207/14612 [12:40<56:06,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2208/14612 [12:41<56:14,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2209/14612 [12:41<56:05,  3.69batch/s]
pe_core_l14 videos:  15%|█▌        | 2210/14612 [12:41<56:08,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2211/14612 [12:41<56:13,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2212/14612 [12:42<55:56,  3.69batch/s]
pe_core_l14 videos:  15%|█▌        | 2213/14612 [12:42<56:08,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2214/14612 [12:42<56:09,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2215/14612 [12:42<55:57,  3.69batch/s]
pe_core_l14 videos:  15%|█▌        | 2216/14612 [12:43<56:00,  3.69batch/s]
pe_core_l14 videos:  15%|█▌        | 2217/14612 [12:43<56:07,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2218/14612 [12:43<56:20,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2219/14612 [12:44<56:20,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2220/14612 [12:44<56:18,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2221/14612 [12:44<56:20,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2222/14612 [12:44<56:24,  3.66batch/s]
pe_core_l14 videos:  15%|█▌        | 2223/14612 [12:45<56:04,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2224/14612 [12:45<56:13,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2225/14612 [12:45<56:10,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2226/14612 [12:45<56:15,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2227/14612 [12:46<56:34,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2228/14612 [12:46<56:46,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2229/14612 [12:46<56:23,  3.66batch/s]
pe_core_l14 videos:  15%|█▌        | 2230/14612 [12:47<56:28,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2231/14612 [12:47<56:43,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2232/14612 [12:47<56:35,  3.65batch/s]
pe_core_l14 videos:  15%|█▌        | 2233/14612 [12:47<56:43,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2234/14612 [12:48<56:45,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2235/14612 [12:48<56:52,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2236/14612 [12:48<56:45,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2237/14612 [12:48<56:37,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2238/14612 [12:49<56:44,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2239/14612 [12:49<57:18,  3.60batch/s]
pe_core_l14 videos:  15%|█▌        | 2240/14612 [12:49<57:22,  3.59batch/s]
pe_core_l14 videos:  15%|█▌        | 2241/14612 [12:50<57:20,  3.60batch/s]
pe_core_l14 videos:  15%|█▌        | 2242/14612 [12:50<57:35,  3.58batch/s]
pe_core_l14 videos:  15%|█▌        | 2243/14612 [12:50<57:32,  3.58batch/s]
pe_core_l14 videos:  15%|█▌        | 2244/14612 [12:50<56:55,  3.62batch/s]
pe_core_l14 videos:  15%|█▌        | 2245/14612 [12:51<57:01,  3.61batch/s]
pe_core_l14 videos:  15%|█▌        | 2246/14612 [12:51<56:47,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2247/14612 [12:51<56:36,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2248/14612 [12:52<56:37,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2249/14612 [12:52<56:42,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2250/14612 [12:52<56:32,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2251/14612 [12:52<56:49,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2252/14612 [12:53<59:53,  3.44batch/s]
pe_core_l14 videos:  15%|█▌        | 2253/14612 [12:53<58:58,  3.49batch/s]
pe_core_l14 videos:  15%|█▌        | 2254/14612 [12:53<58:31,  3.52batch/s]
pe_core_l14 videos:  15%|█▌        | 2255/14612 [12:54<58:07,  3.54batch/s]
pe_core_l14 videos:  15%|█▌        | 2256/14612 [12:54<57:21,  3.59batch/s]
pe_core_l14 videos:  15%|█▌        | 2257/14612 [12:54<56:56,  3.62batch/s]
pe_core_l14 videos:  15%|█▌        | 2258/14612 [12:54<56:39,  3.63batch/s]
pe_core_l14 videos:  15%|█▌        | 2259/14612 [12:55<56:31,  3.64batch/s]
pe_core_l14 videos:  15%|█▌        | 2260/14612 [12:55<56:07,  3.67batch/s]
pe_core_l14 videos:  15%|█▌        | 2261/14612 [12:55<55:53,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2262/14612 [12:55<55:57,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2263/14612 [12:56<55:59,  3.68batch/s]
pe_core_l14 videos:  15%|█▌        | 2264/14612 [12:56<56:07,  3.67batch/s]
pe_core_l14 videos:  16%|█▌        | 2265/14612 [12:56<56:00,  3.67batch/s]
pe_core_l14 videos:  16%|█▌        | 2266/14612 [12:57<56:04,  3.67batch/s]
pe_core_l14 videos:  16%|█▌        | 2267/14612 [12:57<56:03,  3.67batch/s]
pe_core_l14 videos:  16%|█▌        | 2268/14612 [12:57<55:58,  3.68batch/s]
pe_core_l14 videos:  16%|█▌        | 2269/14612 [12:57<56:07,  3.67batch/s]
pe_core_l14 videos:  16%|█▌        | 2270/14612 [12:58<55:53,  3.68batch/s]
pe_core_l14 videos:  16%|█▌        | 2271/14612 [12:58<55:57,  3.68batch/s]
pe_core_l14 videos:  16%|█▌        | 2272/14612 [12:58<56:20,  3.65batch/s]
pe_core_l14 videos:  16%|█▌        | 2273/14612 [12:58<56:33,  3.64batch/s]
pe_core_l14 videos:  16%|█▌        | 2274/14612 [12:59<56:28,  3.64batch/s]
pe_core_l14 videos:  16%|█▌        | 2275/14612 [12:59<56:22,  3.65batch/s]
pe_core_l14 videos:  16%|█▌        | 2276/14612 [12:59<56:15,  3.65batch/s]
pe_core_l14 videos:  16%|█▌        | 2277/14612 [13:00<56:32,  3.64batch/s]
pe_core_l14 videos:  16%|█▌        | 2278/14612 [13:00<56:16,  3.65batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos:   0%|          | 0/14612 [00:00<?, ?batch/s]
siglip2 videos:   0%|          | 1/14612 [00:00<2:15:10,  1.80batch/s]atch/s]
pe_core_l14 videos:  24%|██▍       | 3517/14612 [18:39<1:12:38,  2.55batch/s]
siglip2 videos:   0%|          | 2/14612 [00:00<1:51:37,  2.18batch/s]atch/s]
siglip2 videos:   0%|          | 3/14612 [00:01<1:44:06,  2.34batch/s]atch/s]
siglip2 videos:   0%|          | 4/14612 [00:01<1:40:45,  2.42batch/s]atch/s]
siglip2 videos:   0%|          | 5/14612 [00:02<1:39:18,  2.45batch/s]atch/s]
siglip2 videos:   0%|          | 6/14612 [00:02<1:37:57,  2.49batch/s]atch/s]
siglip2 videos:   0%|          | 7/14612 [00:02<1:37:01,  2.51batch/s]atch/s]
siglip2 videos:   0%|          | 8/14612 [00:03<1:36:24,  2.52batch/s]atch/s]
siglip2 videos:   0%|          | 9/14612 [00:03<1:36:36,  2.52batch/s]atch/s]
siglip2 videos:   0%|          | 10/14612 [00:04<1:36:25,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 11/14612 [00:04<1:36:38,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 12/14612 [00:04<1:36:15,  2.53batch/s]tch/s]
siglip2 videos:   0%|          | 13/14612 [00:05<1:36:24,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 14/14612 [00:05<1:36:28,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 15/14612 [00:06<1:36:39,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 16/14612 [00:06<1:36:51,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 17/14612 [00:06<1:36:28,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 18/14612 [00:07<1:35:57,  2.53batch/s]tch/s]
siglip2 videos:   0%|          | 19/14612 [00:07<1:35:47,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 20/14612 [00:08<1:35:49,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 21/14612 [00:08<1:35:52,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 22/14612 [00:08<1:35:50,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 23/14612 [00:09<1:35:44,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 24/14612 [00:09<1:35:42,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 25/14612 [00:10<1:35:48,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 26/14612 [00:10<1:35:48,  2.54batch/s]tch/s]
siglip2 videos:   0%|          | 27/14612 [00:10<1:36:10,  2.53batch/s]tch/s]
siglip2 videos:   0%|          | 28/14612 [00:11<1:36:12,  2.53batch/s]tch/s]
siglip2 videos:   0%|          | 29/14612 [00:11<1:36:17,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 30/14612 [00:12<1:36:23,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 31/14612 [00:12<1:36:35,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 32/14612 [00:12<1:36:37,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 33/14612 [00:13<1:36:27,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 34/14612 [00:13<1:36:39,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 35/14612 [00:13<1:36:35,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 36/14612 [00:14<1:36:34,  2.52batch/s]tch/s]
siglip2 videos:   0%|          | 37/14612 [00:14<1:36:37,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 38/14612 [00:15<1:36:38,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 39/14612 [00:15<1:36:40,  2.51batch/s]tch/s]
siglip2 videos:   0%|          | 40/14612 [00:15<1:37:05,  2.50batch/s]tch/s]
siglip2 videos:   0%|          | 41/14612 [00:16<1:37:22,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 42/14612 [00:16<1:37:20,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 43/14612 [00:17<1:37:59,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 44/14612 [00:17<1:37:56,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 45/14612 [00:18<1:37:32,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 46/14612 [00:18<1:37:45,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 47/14612 [00:18<1:37:23,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 48/14612 [00:19<1:37:36,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 49/14612 [00:19<1:37:49,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 50/14612 [00:20<1:37:30,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 51/14612 [00:20<1:38:05,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 52/14612 [00:20<1:38:01,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 54/14612 [00:21<1:38:10,  2.47batch/s]tch/s]
pe_core_l14 videos:  24%|██▍       | 3570/14612 [19:00<1:14:29,  2.47batch/s]
siglip2 videos:   0%|          | 55/14612 [00:22<1:37:47,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 56/14612 [00:22<1:37:52,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 57/14612 [00:22<1:37:56,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 58/14612 [00:23<1:37:58,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 59/14612 [00:23<1:37:34,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 60/14612 [00:24<1:37:19,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 61/14612 [00:24<1:37:35,  2.49batch/s]tch/s]
siglip2 videos:   0%|          | 62/14612 [00:24<1:37:50,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 63/14612 [00:25<1:37:57,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 64/14612 [00:25<1:38:04,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 65/14612 [00:26<1:38:08,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 66/14612 [00:26<1:38:07,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 67/14612 [00:26<1:38:07,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 68/14612 [00:27<1:37:52,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 69/14612 [00:27<1:37:57,  2.47batch/s]tch/s]
siglip2 videos:   0%|          | 70/14612 [00:28<1:37:49,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 71/14612 [00:28<1:37:52,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 72/14612 [00:28<1:37:34,  2.48batch/s]tch/s]
siglip2 videos:   0%|          | 73/14612 [00:29<1:37:50,  2.48batch/s]tch/s]
siglip2 videos:   1%|          | 74/14612 [00:29<1:37:56,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 75/14612 [00:30<1:37:51,  2.48batch/s]tch/s]
siglip2 videos:   1%|          | 76/14612 [00:30<1:37:57,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 77/14612 [00:30<1:38:00,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 78/14612 [00:31<1:39:02,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 79/14612 [00:31<1:38:41,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 80/14612 [00:32<1:38:14,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 81/14612 [00:32<1:38:12,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 82/14612 [00:32<1:37:57,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 83/14612 [00:33<1:37:51,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 84/14612 [00:33<1:37:47,  2.48batch/s]tch/s]
siglip2 videos:   1%|          | 85/14612 [00:34<1:38:00,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 86/14612 [00:34<1:38:04,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 87/14612 [00:34<1:38:05,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 88/14612 [00:35<1:38:04,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 89/14612 [00:35<1:37:59,  2.47batch/s]tch/s]
siglip2 videos:   1%|          | 90/14612 [00:36<1:39:22,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 91/14612 [00:36<1:38:56,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 92/14612 [00:37<1:38:43,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 93/14612 [00:37<1:38:25,  2.46batch/s]tch/s]
siglip2 videos:   1%|          | 94/14612 [00:37<1:38:30,  2.46batch/s]tch/s]
siglip2 videos:   1%|          | 95/14612 [00:38<1:38:37,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 96/14612 [00:38<1:38:52,  2.45batch/s]tch/s]
siglip2 videos:   1%|          | 97/14612 [00:39<1:39:16,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 98/14612 [00:39<1:39:09,  2.44batch/s]tch/s]
siglip2 videos:   1%|          | 99/14612 [00:39<1:39:25,  2.43batch/s]tch/s]
siglip2 videos:   1%|          | 100/14612 [00:40<1:39:57,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 101/14612 [00:40<1:40:00,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 102/14612 [00:41<1:38:47,  2.45batch/s]ch/s]
siglip2 videos:   1%|          | 103/14612 [00:41<1:39:07,  2.44batch/s]ch/s]
siglip2 videos:   1%|          | 104/14612 [00:41<1:39:09,  2.44batch/s]ch/s]
siglip2 videos:   1%|          | 105/14612 [00:42<1:39:22,  2.43batch/s]ch/s]
siglip2 videos:   1%|          | 106/14612 [00:42<1:39:16,  2.44batch/s]ch/s]
siglip2 videos:   1%|          | 107/14612 [00:43<1:38:47,  2.45batch/s]ch/s]
siglip2 videos:   1%|          | 108/14612 [00:43<1:38:38,  2.45batch/s]ch/s]
siglip2 videos:   1%|          | 109/14612 [00:43<1:38:54,  2.44batch/s]ch/s]
siglip2 videos:   1%|          | 110/14612 [00:44<1:39:13,  2.44batch/s]ch/s]
siglip2 videos:   1%|          | 111/14612 [00:44<1:39:30,  2.43batch/s]ch/s]
siglip2 videos:   1%|          | 112/14612 [00:45<1:39:41,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 113/14612 [00:45<1:40:07,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 114/14612 [00:46<1:40:15,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 115/14612 [00:46<1:40:20,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 116/14612 [00:46<1:40:02,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 117/14612 [00:47<1:40:18,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 118/14612 [00:47<1:39:59,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 119/14612 [00:48<1:40:08,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 120/14612 [00:48<1:39:53,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 121/14612 [00:48<1:39:47,  2.42batch/s]ch/s]
siglip2 videos:   1%|          | 122/14612 [00:49<1:40:25,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 123/14612 [00:49<1:40:23,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 124/14612 [00:50<1:40:13,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 125/14612 [00:50<1:40:03,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 126/14612 [00:51<1:40:10,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 127/14612 [00:51<1:40:10,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 128/14612 [00:51<1:40:13,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 129/14612 [00:52<1:40:24,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 130/14612 [00:52<1:40:16,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 131/14612 [00:53<1:40:08,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 132/14612 [00:53<1:40:15,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 133/14612 [00:53<1:40:13,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 134/14612 [00:54<1:40:12,  2.41batch/s]ch/s]
siglip2 videos:   1%|          | 135/14612 [00:54<1:40:24,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 136/14612 [00:55<1:40:27,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 137/14612 [00:55<1:40:38,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 138/14612 [00:56<1:40:47,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 139/14612 [00:56<1:40:39,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 140/14612 [00:56<1:40:34,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 141/14612 [00:57<1:40:54,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 142/14612 [00:57<1:40:40,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 143/14612 [00:58<1:40:55,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 144/14612 [00:58<1:41:05,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 145/14612 [00:58<1:40:46,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 146/14612 [00:59<1:40:23,  2.40batch/s]ch/s]
siglip2 videos:   1%|          | 147/14612 [00:59<1:40:46,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 148/14612 [01:00<1:41:01,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 149/14612 [01:00<1:40:46,  2.39batch/s]ch/s]
siglip2 videos:   1%|          | 150/14612 [01:01<1:41:13,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 151/14612 [01:01<1:41:14,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 152/14612 [01:01<1:41:06,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 153/14612 [01:02<1:41:31,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 154/14612 [01:02<1:41:24,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 155/14612 [01:03<1:41:23,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 156/14612 [01:03<1:41:18,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 157/14612 [01:04<1:41:33,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 158/14612 [01:04<1:41:33,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 159/14612 [01:04<1:41:23,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 160/14612 [01:05<1:41:24,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 161/14612 [01:05<1:41:16,  2.38batch/s]ch/s]
siglip2 videos:   1%|          | 162/14612 [01:06<1:41:39,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 163/14612 [01:06<1:41:41,  2.37batch/s]ch/s]
siglip2 videos:   1%|          | 164/14612 [01:06<1:41:51,  2.36batch/s]ch/s]
siglip2 videos:   1%|          | 165/14612 [01:07<1:42:09,  2.36batch/s]ch/s]
siglip2 videos:   1%|          | 166/14612 [01:07<1:42:19,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 167/14612 [01:08<1:42:45,  2.34batch/s]ch/s]
siglip2 videos:   1%|          | 168/14612 [01:08<1:42:19,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 169/14612 [01:09<1:42:15,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 170/14612 [01:09<1:42:19,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 171/14612 [01:09<1:42:28,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 172/14612 [01:10<1:42:37,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 173/14612 [01:10<1:42:38,  2.34batch/s]ch/s]
siglip2 videos:   1%|          | 174/14612 [01:11<1:42:21,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 175/14612 [01:11<1:42:08,  2.36batch/s]ch/s]
siglip2 videos:   1%|          | 176/14612 [01:12<1:42:24,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 177/14612 [01:12<1:42:24,  2.35batch/s]ch/s]
siglip2 videos:   1%|          | 178/14612 [01:12<1:42:43,  2.34batch/s]ch/s]
siglip2 videos:   1%|          | 179/14612 [01:13<1:42:50,  2.34batch/s]ch/s]
siglip2 videos:   1%|          | 180/14612 [01:13<1:43:03,  2.33batch/s]ch/s]
siglip2 videos:   1%|          | 181/14612 [01:14<1:43:11,  2.33batch/s]ch/s]
siglip2 videos:   1%|          | 182/14612 [01:14<1:43:13,  2.33batch/s]ch/s]
siglip2 videos:   1%|▏         | 183/14612 [01:15<1:43:32,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 184/14612 [01:15<1:43:28,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 185/14612 [01:15<1:43:41,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 186/14612 [01:16<1:43:52,  2.31batch/s]ch/s]
siglip2 videos:   1%|▏         | 187/14612 [01:16<1:43:37,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 188/14612 [01:17<1:43:15,  2.33batch/s]ch/s]
siglip2 videos:   1%|▏         | 189/14612 [01:17<1:43:26,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 190/14612 [01:18<1:43:32,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 191/14612 [01:18<1:43:28,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 192/14612 [01:18<1:43:34,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 193/14612 [01:19<1:43:26,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 194/14612 [01:19<1:43:37,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 195/14612 [01:20<1:43:26,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 196/14612 [01:20<1:43:30,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 197/14612 [01:21<1:43:38,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 198/14612 [01:21<1:43:29,  2.32batch/s]ch/s]
siglip2 videos:   1%|▏         | 199/14612 [01:21<1:43:49,  2.31batch/s]ch/s]
siglip2 videos:   1%|▏         | 200/14612 [01:22<1:43:54,  2.31batch/s]ch/s]
siglip2 videos:   1%|▏         | 201/14612 [01:22<1:43:50,  2.31batch/s]ch/s]
siglip2 videos:   1%|▏         | 202/14612 [01:23<1:43:53,  2.31batch/s]ch/s]
siglip2 videos:   1%|▏         | 203/14612 [01:23<1:44:21,  2.30batch/s]ch/s]
siglip2 videos:   1%|▏         | 204/14612 [01:24<1:44:56,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 205/14612 [01:24<1:45:00,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 206/14612 [01:25<1:44:52,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 207/14612 [01:25<1:44:48,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 208/14612 [01:25<1:44:34,  2.30batch/s]ch/s]
siglip2 videos:   1%|▏         | 209/14612 [01:26<1:44:38,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 210/14612 [01:26<1:44:47,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 211/14612 [01:27<1:44:35,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 212/14612 [01:27<1:44:33,  2.30batch/s]ch/s]
siglip2 videos:   1%|▏         | 213/14612 [01:28<1:44:49,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 214/14612 [01:28<1:44:35,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 215/14612 [01:28<1:44:25,  2.30batch/s]ch/s]
siglip2 videos:   1%|▏         | 216/14612 [01:29<1:44:43,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 217/14612 [01:29<1:44:53,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 218/14612 [01:30<1:44:35,  2.29batch/s]ch/s]
siglip2 videos:   1%|▏         | 219/14612 [01:30<1:44:28,  2.30batch/s]ch/s]
siglip2 videos:   2%|▏         | 220/14612 [01:31<1:44:27,  2.30batch/s]ch/s]
siglip2 videos:   2%|▏         | 221/14612 [01:31<1:44:22,  2.30batch/s]ch/s]
siglip2 videos:   2%|▏         | 222/14612 [01:32<1:44:31,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 223/14612 [01:32<1:44:46,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 224/14612 [01:32<1:44:51,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 225/14612 [01:33<1:44:49,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 226/14612 [01:33<1:44:51,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 227/14612 [01:34<1:45:02,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 228/14612 [01:34<1:45:26,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 229/14612 [01:35<1:45:25,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 230/14612 [01:35<1:45:17,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 231/14612 [01:35<1:44:59,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 232/14612 [01:36<1:44:49,  2.29batch/s]ch/s]
siglip2 videos:   2%|▏         | 233/14612 [01:36<1:45:19,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 234/14612 [01:37<1:45:55,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 235/14612 [01:37<1:45:56,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 236/14612 [01:38<1:45:45,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 237/14612 [01:38<1:45:24,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 238/14612 [01:39<1:45:14,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 239/14612 [01:39<1:45:32,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 240/14612 [01:39<1:45:09,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 241/14612 [01:40<1:45:01,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 242/14612 [01:40<1:45:14,  2.28batch/s]ch/s]
siglip2 videos:   2%|▏         | 243/14612 [01:41<1:45:28,  2.27batch/s]ch/s]
siglip2 videos:   2%|▏         | 244/14612 [01:41<1:45:55,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 245/14612 [01:42<1:46:06,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 246/14612 [01:42<1:45:43,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 247/14612 [01:43<1:46:04,  2.26batch/s]ch/s]
siglip2 videos:   2%|▏         | 248/14612 [01:43<1:46:36,  2.25batch/s]ch/s]
siglip2 videos:   2%|▏         | 249/14612 [01:43<1:47:02,  2.24batch/s]ch/s]
siglip2 videos:   2%|▏         | 250/14612 [01:44<1:47:16,  2.23batch/s]ch/s]
siglip2 videos:   2%|▏         | 251/14612 [01:44<1:47:19,  2.23batch/s]ch/s]
siglip2 videos:   2%|▏         | 252/14612 [01:45<1:47:37,  2.22batch/s]ch/s]
siglip2 videos:   2%|▏         | 253/14612 [01:45<1:47:10,  2.23batch/s]ch/s]
siglip2 videos:   2%|▏         | 254/14612 [01:46<1:47:36,  2.22batch/s]ch/s]

-- none: R1 13.50  mAP 23.71  mINP 23.71
== IRRA | activitynet/sentence | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  62%|██████▏   | 9111/14612 [1:14:34<46:33,  1.97batch/s]
irra texts:   0%|          | 0/227 [00:00<?, ?batch/s]
irra texts:   4%|▎         | 8/227 [00:00<00:03, 70.55batch/s]
siglip2 videos:  62%|██████▏   | 9112/14612 [1:14:35<45:48,  2.00batch/s]
irra texts:  11%|█         | 24/227 [00:00<00:02, 74.44batch/s]
irra texts:  14%|█▍        | 32/227 [00:00<00:02, 72.45batch/s]
irra texts:  18%|█▊        | 40/227 [00:00<00:02, 71.36batch/s]
siglip2 videos:  62%|██████▏   | 9113/14612 [1:14:35<45:11,  2.03batch/s]
irra texts:  25%|██▍       | 56/227 [00:00<00:02, 69.08batch/s]
irra texts:  28%|██▊       | 63/227 [00:00<00:02, 59.20batch/s]
irra texts:  31%|███▏      | 71/227 [00:01<00:02, 62.62batch/s]
siglip2 videos:  62%|██████▏   | 9114/14612 [1:14:36<44:47,  2.05batch/s]
irra texts:  38%|███▊      | 87/227 [00:01<00:02, 67.81batch/s]
irra texts:  41%|████▏     | 94/227 [00:01<00:02, 66.22batch/s]
irra texts:  45%|████▍     | 102/227 [00:01<00:01, 69.68batch/s]
irra texts:  48%|████▊     | 110/227 [00:01<00:01, 67.49batch/s]
siglip2 videos:  62%|██████▏   | 9115/14612 [1:14:36<44:26,  2.06batch/s]
irra texts:  56%|█████▌    | 126/227 [00:01<00:01, 67.10batch/s]
irra texts:  59%|█████▉    | 134/227 [00:01<00:01, 70.35batch/s]
irra texts:  63%|██████▎   | 142/227 [00:02<00:01, 66.81batch/s]
siglip2 videos:  62%|██████▏   | 9116/14612 [1:14:37<44:02,  2.08batch/s]
irra texts:  70%|██████▉   | 158/227 [00:02<00:01, 67.53batch/s]
irra texts:  73%|███████▎  | 166/227 [00:02<00:00, 70.21batch/s]
irra texts:  77%|███████▋  | 174/227 [00:02<00:00, 70.55batch/s]
siglip2 videos:  62%|██████▏   | 9117/14612 [1:14:37<43:43,  2.09batch/s]
irra texts:  84%|████████▎ | 190/227 [00:02<00:00, 68.49batch/s]
irra texts:  87%|████████▋ | 198/227 [00:02<00:00, 70.87batch/s]
irra texts:  91%|█████████ | 206/227 [00:02<00:00, 70.41batch/s]
siglip2 videos:  62%|██████▏   | 9118/14612 [1:14:38<43:31,  2.10batch/s]
irra texts: 100%|██████████| 227/227 [00:03<00:00, 68.96batch/s]
siglip2 videos:  62%|██████▏   | 9123/14612 [1:14:40<49:00,  1.87batch/s]

-- none: R1 6.50  mAP 12.87  mINP 12.87
== IRRA | activitynet/paragraph | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  62%|██████▏   | 9124/14612 [1:14:41<49:16,  1.86batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

irra videos:   0%|          | 0/995 [00:00<?, ?batch/s]
irra videos:   0%|          | 1/995 [00:00<03:44,  4.43batch/s]
siglip2 videos:  62%|██████▏   | 9125/14612 [1:14:41<49:51,  1.83batch/s]
irra videos:   0%|          | 3/995 [00:00<03:55,  4.22batch/s]
siglip2 videos:  62%|██████▏   | 9126/14612 [1:14:42<47:53,  1.91batch/s]
irra videos:   1%|          | 5/995 [00:01<03:57,  4.17batch/s]
siglip2 videos:  62%|██████▏   | 9127/14612 [1:14:42<46:36,  1.96batch/s]
irra videos:   1%|          | 7/995 [00:01<03:56,  4.18batch/s]
siglip2 videos:  62%|██████▏   | 9128/14612 [1:14:43<45:38,  2.00batch/s]
irra videos:   1%|          | 9/995 [00:02<03:54,  4.20batch/s]
siglip2 videos:  62%|██████▏   | 9129/14612 [1:14:43<44:55,  2.03batch/s]
irra videos:   1%|          | 11/995 [00:02<03:54,  4.19batch/s]
siglip2 videos:  62%|██████▏   | 9130/14612 [1:14:44<44:26,  2.06batch/s]
irra videos:   1%|▏         | 13/995 [00:03<03:54,  4.19batch/s]
siglip2 videos:  62%|██████▏   | 9131/14612 [1:14:44<44:11,  2.07batch/s]
irra videos:   2%|▏         | 15/995 [00:03<03:56,  4.14batch/s]
siglip2 videos:  62%|██████▏   | 9132/14612 [1:14:45<44:08,  2.07batch/s]
irra videos:   2%|▏         | 17/995 [00:04<03:56,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9133/14612 [1:14:45<44:05,  2.07batch/s]
irra videos:   2%|▏         | 19/995 [00:04<03:55,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9134/14612 [1:14:46<43:55,  2.08batch/s]
irra videos:   2%|▏         | 21/995 [00:05<03:54,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9135/14612 [1:14:46<43:44,  2.09batch/s]
irra videos:   2%|▏         | 23/995 [00:05<03:54,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9136/14612 [1:14:47<43:45,  2.09batch/s]
irra videos:   3%|▎         | 25/995 [00:05<03:53,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9137/14612 [1:14:47<43:43,  2.09batch/s]
irra videos:   3%|▎         | 27/995 [00:06<03:52,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9138/14612 [1:14:48<43:39,  2.09batch/s]
irra videos:   3%|▎         | 29/995 [00:06<03:51,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9139/14612 [1:14:48<43:35,  2.09batch/s]
irra videos:   3%|▎         | 31/995 [00:07<03:51,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9140/14612 [1:14:49<43:29,  2.10batch/s]
irra videos:   3%|▎         | 33/995 [00:07<03:50,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9141/14612 [1:14:49<43:27,  2.10batch/s]
irra videos:   4%|▎         | 35/995 [00:08<03:50,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9142/14612 [1:14:49<43:30,  2.10batch/s]
irra videos:   4%|▎         | 37/995 [00:08<03:51,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9143/14612 [1:14:50<43:35,  2.09batch/s]
irra videos:   4%|▍         | 39/995 [00:09<03:49,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9144/14612 [1:14:50<43:28,  2.10batch/s]
irra videos:   4%|▍         | 41/995 [00:09<03:49,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9145/14612 [1:14:51<43:28,  2.10batch/s]
irra videos:   4%|▍         | 43/995 [00:10<03:48,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9146/14612 [1:14:51<43:31,  2.09batch/s]
irra videos:   5%|▍         | 45/995 [00:10<03:48,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9147/14612 [1:14:52<43:32,  2.09batch/s]
irra videos:   5%|▍         | 47/995 [00:11<03:49,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9148/14612 [1:14:52<43:29,  2.09batch/s]
irra videos:   5%|▍         | 49/995 [00:11<03:46,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9149/14612 [1:14:53<43:20,  2.10batch/s]
irra videos:   5%|▌         | 51/995 [00:12<03:46,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9150/14612 [1:14:53<43:28,  2.09batch/s]
irra videos:   5%|▌         | 53/995 [00:12<03:45,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9151/14612 [1:14:54<43:19,  2.10batch/s]
irra videos:   6%|▌         | 55/995 [00:13<03:45,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9152/14612 [1:14:54<43:20,  2.10batch/s]
irra videos:   6%|▌         | 57/995 [00:13<03:46,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9153/14612 [1:14:55<43:31,  2.09batch/s]
irra videos:   6%|▌         | 59/995 [00:14<03:45,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9154/14612 [1:14:55<43:28,  2.09batch/s]
irra videos:   6%|▌         | 61/995 [00:14<03:45,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9155/14612 [1:14:56<43:27,  2.09batch/s]
irra videos:   6%|▋         | 63/995 [00:15<03:42,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9156/14612 [1:14:56<43:14,  2.10batch/s]
irra videos:   7%|▋         | 65/995 [00:15<03:42,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9157/14612 [1:14:57<43:15,  2.10batch/s]
irra videos:   7%|▋         | 67/995 [00:15<03:41,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9158/14612 [1:14:57<43:11,  2.10batch/s]
irra videos:   7%|▋         | 69/995 [00:16<03:41,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9159/14612 [1:14:58<43:14,  2.10batch/s]
irra videos:   7%|▋         | 71/995 [00:16<03:42,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9160/14612 [1:14:58<43:20,  2.10batch/s]
irra videos:   7%|▋         | 73/995 [00:17<03:40,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9161/14612 [1:14:59<43:15,  2.10batch/s]
irra videos:   8%|▊         | 75/995 [00:17<03:39,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9162/14612 [1:14:59<43:07,  2.11batch/s]
irra videos:   8%|▊         | 77/995 [00:18<03:41,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9163/14612 [1:14:59<43:23,  2.09batch/s]
irra videos:   8%|▊         | 79/995 [00:18<03:40,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9164/14612 [1:15:00<43:24,  2.09batch/s]
irra videos:   8%|▊         | 81/995 [00:19<03:39,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9165/14612 [1:15:00<43:13,  2.10batch/s]
irra videos:   8%|▊         | 83/995 [00:19<03:37,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9166/14612 [1:15:01<43:05,  2.11batch/s]
irra videos:   9%|▊         | 85/995 [00:20<03:37,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9167/14612 [1:15:01<43:08,  2.10batch/s]
irra videos:   9%|▊         | 87/995 [00:20<03:37,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9168/14612 [1:15:02<43:14,  2.10batch/s]
irra videos:   9%|▉         | 89/995 [00:21<03:38,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9169/14612 [1:15:02<43:16,  2.10batch/s]
irra videos:   9%|▉         | 91/995 [00:21<03:37,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9170/14612 [1:15:03<43:13,  2.10batch/s]
irra videos:   9%|▉         | 93/995 [00:22<03:37,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9171/14612 [1:15:03<43:10,  2.10batch/s]
irra videos:  10%|▉         | 95/995 [00:22<03:34,  4.20batch/s]
siglip2 videos:  63%|██████▎   | 9172/14612 [1:15:04<43:05,  2.10batch/s]
irra videos:  10%|▉         | 97/995 [00:23<03:34,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9173/14612 [1:15:04<43:07,  2.10batch/s]
irra videos:  10%|▉         | 99/995 [00:23<03:35,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9174/14612 [1:15:05<43:10,  2.10batch/s]
irra videos:  10%|█         | 101/995 [00:24<03:34,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9175/14612 [1:15:05<43:10,  2.10batch/s]
irra videos:  10%|█         | 103/995 [00:24<03:33,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9176/14612 [1:15:06<43:06,  2.10batch/s]
irra videos:  11%|█         | 105/995 [00:25<03:32,  4.20batch/s]
siglip2 videos:  63%|██████▎   | 9177/14612 [1:15:06<43:04,  2.10batch/s]
irra videos:  11%|█         | 107/995 [00:25<03:33,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9178/14612 [1:15:07<43:08,  2.10batch/s]
irra videos:  11%|█         | 109/995 [00:25<03:32,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9179/14612 [1:15:07<43:06,  2.10batch/s]
irra videos:  11%|█         | 111/995 [00:26<03:31,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9180/14612 [1:15:08<43:06,  2.10batch/s]
irra videos:  11%|█▏        | 113/995 [00:26<03:32,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9181/14612 [1:15:08<43:07,  2.10batch/s]
irra videos:  12%|█▏        | 115/995 [00:27<03:30,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9182/14612 [1:15:09<43:01,  2.10batch/s]
irra videos:  12%|█▏        | 117/995 [00:27<03:29,  4.20batch/s]
siglip2 videos:  63%|██████▎   | 9183/14612 [1:15:09<42:53,  2.11batch/s]
irra videos:  12%|█▏        | 119/995 [00:28<03:29,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9184/14612 [1:15:09<42:57,  2.11batch/s]
irra videos:  12%|█▏        | 121/995 [00:28<03:30,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9185/14612 [1:15:10<43:05,  2.10batch/s]
irra videos:  12%|█▏        | 123/995 [00:29<03:28,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9186/14612 [1:15:10<42:58,  2.10batch/s]
irra videos:  13%|█▎        | 125/995 [00:29<03:28,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9187/14612 [1:15:11<43:05,  2.10batch/s]
irra videos:  13%|█▎        | 127/995 [00:30<03:29,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9188/14612 [1:15:11<43:10,  2.09batch/s]
irra videos:  13%|█▎        | 129/995 [00:30<03:27,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9189/14612 [1:15:12<43:05,  2.10batch/s]
irra videos:  13%|█▎        | 131/995 [00:31<03:28,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9190/14612 [1:15:12<43:11,  2.09batch/s]
irra videos:  13%|█▎        | 133/995 [00:31<03:28,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9191/14612 [1:15:13<43:12,  2.09batch/s]
irra videos:  14%|█▎        | 135/995 [00:32<03:27,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9192/14612 [1:15:13<43:15,  2.09batch/s]
irra videos:  14%|█▍        | 137/995 [00:32<03:27,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9193/14612 [1:15:14<43:11,  2.09batch/s]
irra videos:  14%|█▍        | 139/995 [00:33<03:27,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9194/14612 [1:15:14<43:15,  2.09batch/s]
irra videos:  14%|█▍        | 141/995 [00:33<03:25,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9195/14612 [1:15:15<43:03,  2.10batch/s]
irra videos:  14%|█▍        | 143/995 [00:34<03:24,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9196/14612 [1:15:15<43:04,  2.10batch/s]
irra videos:  15%|█▍        | 145/995 [00:34<03:24,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9197/14612 [1:15:16<43:05,  2.09batch/s]
irra videos:  15%|█▍        | 147/995 [00:35<03:23,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9198/14612 [1:15:16<43:00,  2.10batch/s]
irra videos:  15%|█▍        | 149/995 [00:35<03:22,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9199/14612 [1:15:17<42:57,  2.10batch/s]
irra videos:  15%|█▌        | 151/995 [00:35<03:23,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9200/14612 [1:15:17<43:07,  2.09batch/s]
irra videos:  15%|█▌        | 153/995 [00:36<03:23,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9201/14612 [1:15:18<43:14,  2.09batch/s]
irra videos:  16%|█▌        | 155/995 [00:36<03:22,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9202/14612 [1:15:18<43:11,  2.09batch/s]
irra videos:  16%|█▌        | 157/995 [00:37<03:21,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9203/14612 [1:15:19<43:04,  2.09batch/s]
irra videos:  16%|█▌        | 159/995 [00:37<03:19,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9204/14612 [1:15:19<42:55,  2.10batch/s]
irra videos:  16%|█▌        | 161/995 [00:38<03:20,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9205/14612 [1:15:19<43:01,  2.09batch/s]
irra videos:  16%|█▋        | 163/995 [00:38<03:20,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9206/14612 [1:15:20<43:05,  2.09batch/s]
irra videos:  17%|█▋        | 165/995 [00:39<03:19,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9207/14612 [1:15:20<43:04,  2.09batch/s]
irra videos:  17%|█▋        | 167/995 [00:39<03:19,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9208/14612 [1:15:21<43:05,  2.09batch/s]
irra videos:  17%|█▋        | 169/995 [00:40<03:19,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9209/14612 [1:15:21<43:11,  2.08batch/s]
irra videos:  17%|█▋        | 171/995 [00:40<03:19,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9210/14612 [1:15:22<43:10,  2.09batch/s]
irra videos:  17%|█▋        | 173/995 [00:41<03:19,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9211/14612 [1:15:22<43:04,  2.09batch/s]
irra videos:  18%|█▊        | 175/995 [00:41<03:16,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9212/14612 [1:15:23<43:00,  2.09batch/s]
irra videos:  18%|█▊        | 177/995 [00:42<03:17,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9213/14612 [1:15:23<43:02,  2.09batch/s]
irra videos:  18%|█▊        | 179/995 [00:42<03:16,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9214/14612 [1:15:24<43:01,  2.09batch/s]
irra videos:  18%|█▊        | 181/995 [00:43<03:15,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9215/14612 [1:15:24<42:49,  2.10batch/s]
irra videos:  18%|█▊        | 183/995 [00:43<03:15,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9216/14612 [1:15:25<42:57,  2.09batch/s]
irra videos:  19%|█▊        | 185/995 [00:44<03:14,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9217/14612 [1:15:25<42:56,  2.09batch/s]
irra videos:  19%|█▉        | 187/995 [00:44<03:15,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9218/14612 [1:15:26<43:02,  2.09batch/s]
irra videos:  19%|█▉        | 189/995 [00:45<03:14,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9219/14612 [1:15:26<43:03,  2.09batch/s]
irra videos:  19%|█▉        | 191/995 [00:45<03:13,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9220/14612 [1:15:27<43:00,  2.09batch/s]
irra videos:  19%|█▉        | 193/995 [00:46<03:13,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9221/14612 [1:15:27<42:57,  2.09batch/s]
irra videos:  20%|█▉        | 195/995 [00:46<03:11,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9222/14612 [1:15:28<42:53,  2.09batch/s]
irra videos:  20%|█▉        | 197/995 [00:46<03:13,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9223/14612 [1:15:28<42:59,  2.09batch/s]
irra videos:  20%|██        | 199/995 [00:47<03:11,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9224/14612 [1:15:29<42:57,  2.09batch/s]
irra videos:  20%|██        | 201/995 [00:47<03:12,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9225/14612 [1:15:29<43:04,  2.08batch/s]
irra videos:  20%|██        | 203/995 [00:48<03:11,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9226/14612 [1:15:30<42:59,  2.09batch/s]
irra videos:  21%|██        | 205/995 [00:48<03:08,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9227/14612 [1:15:30<42:48,  2.10batch/s]
irra videos:  21%|██        | 207/995 [00:49<03:09,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9228/14612 [1:15:31<42:51,  2.09batch/s]
irra videos:  21%|██        | 209/995 [00:49<03:08,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9229/14612 [1:15:31<42:50,  2.09batch/s]
irra videos:  21%|██        | 211/995 [00:50<03:08,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9230/14612 [1:15:31<42:47,  2.10batch/s]
irra videos:  21%|██▏       | 213/995 [00:50<03:06,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9231/14612 [1:15:32<42:47,  2.10batch/s]
irra videos:  22%|██▏       | 215/995 [00:51<03:07,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9232/14612 [1:15:32<42:41,  2.10batch/s]
irra videos:  22%|██▏       | 217/995 [00:51<03:05,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9233/14612 [1:15:33<42:43,  2.10batch/s]
irra videos:  22%|██▏       | 219/995 [00:52<03:06,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9234/14612 [1:15:33<42:45,  2.10batch/s]
irra videos:  22%|██▏       | 221/995 [00:52<03:06,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9235/14612 [1:15:34<42:46,  2.09batch/s]
irra videos:  22%|██▏       | 223/995 [00:53<03:04,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9236/14612 [1:15:34<42:38,  2.10batch/s]
irra videos:  23%|██▎       | 225/995 [00:53<03:03,  4.20batch/s]
siglip2 videos:  63%|██████▎   | 9237/14612 [1:15:35<42:35,  2.10batch/s]
irra videos:  23%|██▎       | 227/995 [00:54<03:04,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9238/14612 [1:15:35<42:38,  2.10batch/s]
irra videos:  23%|██▎       | 229/995 [00:54<03:05,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9239/14612 [1:15:36<42:54,  2.09batch/s]
irra videos:  23%|██▎       | 231/995 [00:55<03:03,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9240/14612 [1:15:36<42:47,  2.09batch/s]
irra videos:  23%|██▎       | 233/995 [00:55<03:06,  4.09batch/s]
siglip2 videos:  63%|██████▎   | 9241/14612 [1:15:37<43:04,  2.08batch/s]
irra videos:  24%|██▎       | 235/995 [00:56<03:03,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9242/14612 [1:15:37<42:55,  2.08batch/s]
irra videos:  24%|██▍       | 237/995 [00:56<03:03,  4.14batch/s]
siglip2 videos:  63%|██████▎   | 9243/14612 [1:15:38<42:51,  2.09batch/s]
irra videos:  24%|██▍       | 239/995 [00:57<03:02,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9244/14612 [1:15:38<42:55,  2.08batch/s]
irra videos:  24%|██▍       | 241/995 [00:57<03:02,  4.13batch/s]
siglip2 videos:  63%|██████▎   | 9245/14612 [1:15:39<42:54,  2.09batch/s]
irra videos:  24%|██▍       | 243/995 [00:57<03:00,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9246/14612 [1:15:39<42:43,  2.09batch/s]
irra videos:  25%|██▍       | 245/995 [00:58<02:59,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9247/14612 [1:15:40<42:38,  2.10batch/s]
irra videos:  25%|██▍       | 247/995 [00:58<02:58,  4.20batch/s]
siglip2 videos:  63%|██████▎   | 9248/14612 [1:15:40<42:29,  2.10batch/s]
irra videos:  25%|██▌       | 249/995 [00:59<02:58,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9249/14612 [1:15:41<42:30,  2.10batch/s]
irra videos:  25%|██▌       | 251/995 [00:59<02:57,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9250/14612 [1:15:41<42:31,  2.10batch/s]
irra videos:  25%|██▌       | 253/995 [01:00<02:57,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9251/14612 [1:15:41<42:28,  2.10batch/s]
irra videos:  26%|██▌       | 255/995 [01:00<02:57,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9252/14612 [1:15:42<42:34,  2.10batch/s]
irra videos:  26%|██▌       | 257/995 [01:01<02:59,  4.10batch/s]
siglip2 videos:  63%|██████▎   | 9253/14612 [1:15:42<42:52,  2.08batch/s]
irra videos:  26%|██▌       | 259/995 [01:01<02:57,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9254/14612 [1:15:43<42:42,  2.09batch/s]
irra videos:  26%|██▌       | 261/995 [01:02<02:56,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9255/14612 [1:15:43<42:39,  2.09batch/s]
irra videos:  26%|██▋       | 263/995 [01:02<02:55,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9256/14612 [1:15:44<42:34,  2.10batch/s]
irra videos:  27%|██▋       | 265/995 [01:03<02:55,  4.15batch/s]
siglip2 videos:  63%|██████▎   | 9257/14612 [1:15:44<42:39,  2.09batch/s]
irra videos:  27%|██▋       | 267/995 [01:03<02:54,  4.18batch/s]
siglip2 videos:  63%|██████▎   | 9258/14612 [1:15:45<42:29,  2.10batch/s]
irra videos:  27%|██▋       | 269/995 [01:04<02:52,  4.21batch/s]
siglip2 videos:  63%|██████▎   | 9259/14612 [1:15:45<42:21,  2.11batch/s]
irra videos:  27%|██▋       | 271/995 [01:04<02:53,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9260/14612 [1:15:46<42:31,  2.10batch/s]
irra videos:  27%|██▋       | 273/995 [01:05<02:53,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9261/14612 [1:15:46<42:27,  2.10batch/s]
irra videos:  28%|██▊       | 275/995 [01:05<02:52,  4.17batch/s]
siglip2 videos:  63%|██████▎   | 9262/14612 [1:15:47<42:21,  2.10batch/s]
irra videos:  28%|██▊       | 277/995 [01:06<02:51,  4.19batch/s]
siglip2 videos:  63%|██████▎   | 9263/14612 [1:15:47<42:25,  2.10batch/s]
irra videos:  28%|██▊       | 279/995 [01:06<02:52,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9264/14612 [1:15:48<42:28,  2.10batch/s]
siglip2 videos:  63%|██████▎   | 9265/14612 [1:15:48<42:32,  2.09batch/s]
irra videos:  28%|██▊       | 282/995 [01:07<02:49,  4.21batch/s]
irra videos:  28%|██▊       | 283/995 [01:07<02:51,  4.16batch/s]
siglip2 videos:  63%|██████▎   | 9266/14612 [1:15:49<42:35,  2.09batch/s]
irra videos:  29%|██▊       | 285/995 [01:07<02:49,  4.18batch/s]

-- mean: R1 13.60  mAP 23.75  mINP 23.75
-- mean_s8: R1 13.60  mAP 23.75  mINP 23.75
-- max: R1 13.30  mAP 23.49  mINP 23.49
-- query_max: R1 13.50  mAP 23.87  mINP 23.87

siglip2 videos:  66%|██████▌   | 9631/14612 [1:18:43<46:00,  1.80batch/s]

== IRRA | activitynet/sentence | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

irra texts:   0%|          | 0/227 [00:00<?, ?batch/s]
siglip2 videos:  66%|██████▌   | 9632/14612 [1:18:44<45:50,  1.81batch/s]
irra texts:   6%|▌         | 13/227 [00:00<00:03, 59.29batch/s]
irra texts:   8%|▊         | 19/227 [00:00<00:03, 55.45batch/s]
irra texts:  12%|█▏        | 27/227 [00:00<00:03, 62.95batch/s]
irra texts:  15%|█▍        | 34/227 [00:00<00:03, 62.83batch/s]
siglip2 videos:  66%|██████▌   | 9633/14612 [1:18:44<43:48,  1.89batch/s]
irra texts:  22%|██▏       | 49/227 [00:00<00:02, 63.22batch/s]
irra texts:  25%|██▌       | 57/227 [00:00<00:02, 67.86batch/s]
irra texts:  29%|██▊       | 65/227 [00:00<00:02, 69.45batch/s]
siglip2 videos:  66%|██████▌   | 9634/14612 [1:18:45<42:21,  1.96batch/s]
irra texts:  36%|███▌      | 82/227 [00:01<00:02, 65.22batch/s]
irra texts:  40%|███▉      | 90/227 [00:01<00:01, 68.66batch/s]
irra texts:  43%|████▎     | 98/227 [00:01<00:01, 69.32batch/s]
siglip2 videos:  66%|██████▌   | 9635/14612 [1:18:45<41:24,  2.00batch/s]
irra texts:  50%|████▉     | 113/227 [00:01<00:01, 62.06batch/s]
irra texts:  53%|█████▎    | 121/227 [00:01<00:01, 66.66batch/s]
irra texts:  57%|█████▋    | 129/227 [00:01<00:01, 68.81batch/s]
siglip2 videos:  66%|██████▌   | 9636/14612 [1:18:46<40:39,  2.04batch/s]
irra texts:  64%|██████▍   | 146/227 [00:02<00:01, 69.78batch/s]
irra texts:  68%|██████▊   | 155/227 [00:02<00:00, 73.74batch/s]
irra texts:  72%|███████▏  | 163/227 [00:02<00:00, 73.35batch/s]
siglip2 videos:  66%|██████▌   | 9637/14612 [1:18:46<40:10,  2.06batch/s]
irra texts:  79%|███████▉  | 180/227 [00:02<00:00, 69.09batch/s]
irra texts:  83%|████████▎ | 188/227 [00:02<00:00, 70.64batch/s]
irra texts:  86%|████████▋ | 196/227 [00:02<00:00, 68.90batch/s]
siglip2 videos:  66%|██████▌   | 9638/14612 [1:18:47<39:51,  2.08batch/s]
irra texts:  94%|█████████▍| 213/227 [00:03<00:00, 69.39batch/s]
irra texts: 100%|██████████| 227/227 [00:03<00:00, 68.73batch/s]
siglip2 videos:  66%|██████▌   | 9660/14612 [1:18:59<49:45,  1.66batch/s]

-- mean: R1 6.47  mAP 12.88  mINP 12.88
-- mean_s8: R1 6.47  mAP 12.88  mINP 12.88
-- max: R1 6.22  mAP 12.65  mINP 12.65
-- query_max: R1 6.61  mAP 13.21  mINP 13.21
== IRRA | activitynet/paragraph | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  66%|██████▌   | 9661/14612 [1:19:00<47:40,  1.73batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

irra videos:   0%|          | 0/3451 [00:00<?, ?batch/s]
siglip2 videos:  66%|██████▌   | 9662/14612 [1:19:01<1:00:05,  1.37batch/s]
irra videos:   0%|          | 2/3451 [00:00<13:26,  4.28batch/s]
siglip2 videos:  66%|██████▌   | 9663/14612 [1:19:01<53:49,  1.53batch/s]
irra videos:   0%|          | 4/3451 [00:00<13:43,  4.19batch/s]
siglip2 videos:  66%|██████▌   | 9664/14612 [1:19:02<49:31,  1.67batch/s]
irra videos:   0%|          | 6/3451 [00:01<13:44,  4.18batch/s]
siglip2 videos:  66%|██████▌   | 9665/14612 [1:19:02<46:24,  1.78batch/s]
irra videos:   0%|          | 8/3451 [00:01<13:45,  4.17batch/s]
siglip2 videos:  66%|██████▌   | 9666/14612 [1:19:03<44:18,  1.86batch/s]
irra videos:   0%|          | 10/3451 [00:02<13:42,  4.18batch/s]
siglip2 videos:  66%|██████▌   | 9667/14612 [1:19:03<42:45,  1.93batch/s]
irra videos:   0%|          | 12/3451 [00:02<13:44,  4.17batch/s]
siglip2 videos:  66%|██████▌   | 9668/14612 [1:19:04<41:38,  1.98batch/s]
irra videos:   0%|          | 14/3451 [00:03<13:43,  4.18batch/s]
siglip2 videos:  66%|██████▌   | 9669/14612 [1:19:04<40:55,  2.01batch/s]
irra videos:   0%|          | 16/3451 [00:03<13:43,  4.17batch/s]
siglip2 videos:  66%|██████▌   | 9670/14612 [1:19:05<40:26,  2.04batch/s]
irra videos:   1%|          | 18/3451 [00:04<13:39,  4.19batch/s]
siglip2 videos:  66%|██████▌   | 9671/14612 [1:19:05<39:53,  2.06batch/s]
irra videos:   1%|          | 20/3451 [00:04<13:42,  4.17batch/s]
siglip2 videos:  66%|██████▌   | 9672/14612 [1:19:06<39:46,  2.07batch/s]
irra videos:   1%|          | 22/3451 [00:05<13:47,  4.14batch/s]
siglip2 videos:  66%|██████▌   | 9673/14612 [1:19:06<39:43,  2.07batch/s]
irra videos:   1%|          | 24/3451 [00:05<13:43,  4.16batch/s]
siglip2 videos:  66%|██████▌   | 9674/14612 [1:19:07<39:34,  2.08batch/s]
irra videos:   1%|          | 26/3451 [00:06<13:47,  4.14batch/s]
siglip2 videos:  66%|██████▌   | 9675/14612 [1:19:07<39:31,  2.08batch/s]
irra videos:   1%|          | 28/3451 [00:06<13:38,  4.18batch/s]
siglip2 videos:  66%|██████▌   | 9676/14612 [1:19:07<39:18,  2.09batch/s]
irra videos:   1%|          | 30/3451 [00:07<13:38,  4.18batch/s]
siglip2 videos:  66%|██████▌   | 9677/14612 [1:19:08<39:15,  2.10batch/s]
irra videos:   1%|          | 32/3451 [00:07<13:40,  4.17batch/s]
siglip2 videos:  66%|██████▌   | 9678/14612 [1:19:08<39:16,  2.09batch/s]
irra videos:   1%|          | 34/3451 [00:08<13:41,  4.16batch/s]
siglip2 videos:  66%|██████▌   | 9679/14612 [1:19:09<39:17,  2.09batch/s]
irra videos:   1%|          | 36/3451 [00:08<13:41,  4.16batch/s]
siglip2 videos:  66%|██████▌   | 9680/14612 [1:19:09<39:16,  2.09batch/s]
irra videos:   1%|          | 38/3451 [00:09<13:40,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9681/14612 [1:19:10<39:12,  2.10batch/s]
irra videos:   1%|          | 40/3451 [00:09<13:37,  4.17batch/s]
siglip2 videos:  66%|██████▋   | 9682/14612 [1:19:10<39:06,  2.10batch/s]
irra videos:   1%|          | 42/3451 [00:09<13:35,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9683/14612 [1:19:11<39:09,  2.10batch/s]
irra videos:   1%|▏         | 44/3451 [00:10<13:40,  4.15batch/s]
siglip2 videos:  66%|██████▋   | 9684/14612 [1:19:11<39:17,  2.09batch/s]
irra videos:   1%|▏         | 46/3451 [00:10<13:42,  4.14batch/s]
siglip2 videos:  66%|██████▋   | 9685/14612 [1:19:12<39:16,  2.09batch/s]
irra videos:   1%|▏         | 48/3451 [00:11<13:43,  4.13batch/s]
siglip2 videos:  66%|██████▋   | 9686/14612 [1:19:12<39:16,  2.09batch/s]
irra videos:   1%|▏         | 50/3451 [00:11<13:42,  4.13batch/s]
siglip2 videos:  66%|██████▋   | 9687/14612 [1:19:13<39:24,  2.08batch/s]
irra videos:   2%|▏         | 52/3451 [00:12<13:42,  4.13batch/s]
siglip2 videos:  66%|██████▋   | 9688/14612 [1:19:13<39:19,  2.09batch/s]
irra videos:   2%|▏         | 54/3451 [00:12<13:34,  4.17batch/s]
siglip2 videos:  66%|██████▋   | 9689/14612 [1:19:14<39:12,  2.09batch/s]
irra videos:   2%|▏         | 56/3451 [00:13<13:37,  4.15batch/s]
siglip2 videos:  66%|██████▋   | 9690/14612 [1:19:14<39:13,  2.09batch/s]
irra videos:   2%|▏         | 58/3451 [00:13<13:38,  4.15batch/s]
siglip2 videos:  66%|██████▋   | 9691/14612 [1:19:15<39:14,  2.09batch/s]
irra videos:   2%|▏         | 60/3451 [00:14<13:42,  4.12batch/s]
siglip2 videos:  66%|██████▋   | 9692/14612 [1:19:15<39:21,  2.08batch/s]
irra videos:   2%|▏         | 62/3451 [00:14<13:39,  4.13batch/s]
siglip2 videos:  66%|██████▋   | 9693/14612 [1:19:16<39:18,  2.09batch/s]
irra videos:   2%|▏         | 64/3451 [00:15<13:38,  4.14batch/s]
siglip2 videos:  66%|██████▋   | 9694/14612 [1:19:16<39:16,  2.09batch/s]
irra videos:   2%|▏         | 66/3451 [00:15<13:35,  4.15batch/s]
siglip2 videos:  66%|██████▋   | 9695/14612 [1:19:17<39:11,  2.09batch/s]
siglip2 videos:  66%|██████▋   | 9696/14612 [1:19:17<39:10,  2.09batch/s]
irra videos:   2%|▏         | 69/3451 [00:16<13:22,  4.22batch/s]
irra videos:   2%|▏         | 70/3451 [00:16<13:35,  4.15batch/s]
siglip2 videos:  66%|██████▋   | 9697/14612 [1:19:18<39:07,  2.09batch/s]
irra videos:   2%|▏         | 72/3451 [00:17<13:28,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9698/14612 [1:19:18<39:02,  2.10batch/s]
irra videos:   2%|▏         | 74/3451 [00:17<13:29,  4.17batch/s]
siglip2 videos:  66%|██████▋   | 9699/14612 [1:19:18<39:02,  2.10batch/s]
irra videos:   2%|▏         | 76/3451 [00:18<13:27,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9700/14612 [1:19:19<39:02,  2.10batch/s]
irra videos:   2%|▏         | 78/3451 [00:18<13:27,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9701/14612 [1:19:19<39:00,  2.10batch/s]
irra videos:   2%|▏         | 80/3451 [00:19<13:31,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9702/14612 [1:19:20<39:03,  2.10batch/s]
irra videos:   2%|▏         | 82/3451 [00:19<13:30,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9703/14612 [1:19:20<38:59,  2.10batch/s]
irra videos:   2%|▏         | 84/3451 [00:20<13:26,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9704/14612 [1:19:21<39:00,  2.10batch/s]
irra videos:   2%|▏         | 86/3451 [00:20<13:28,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9705/14612 [1:19:21<39:00,  2.10batch/s]
irra videos:   3%|▎         | 88/3451 [00:20<13:32,  4.14batch/s]
siglip2 videos:  66%|██████▋   | 9706/14612 [1:19:22<39:03,  2.09batch/s]
irra videos:   3%|▎         | 90/3451 [00:21<13:28,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9707/14612 [1:19:22<38:59,  2.10batch/s]
irra videos:   3%|▎         | 92/3451 [00:21<13:23,  4.18batch/s]
siglip2 videos:  66%|██████▋   | 9708/14612 [1:19:23<38:56,  2.10batch/s]
irra videos:   3%|▎         | 94/3451 [00:22<13:27,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9709/14612 [1:19:23<39:03,  2.09batch/s]
irra videos:   3%|▎         | 96/3451 [00:22<13:30,  4.14batch/s]
siglip2 videos:  66%|██████▋   | 9710/14612 [1:19:24<39:05,  2.09batch/s]
irra videos:   3%|▎         | 98/3451 [00:23<13:25,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9711/14612 [1:19:24<39:02,  2.09batch/s]
irra videos:   3%|▎         | 100/3451 [00:23<13:26,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9712/14612 [1:19:25<38:55,  2.10batch/s]
irra videos:   3%|▎         | 102/3451 [00:24<13:22,  4.17batch/s]
siglip2 videos:  66%|██████▋   | 9713/14612 [1:19:25<38:57,  2.10batch/s]
irra videos:   3%|▎         | 104/3451 [00:24<13:24,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9714/14612 [1:19:26<38:52,  2.10batch/s]
irra videos:   3%|▎         | 106/3451 [00:25<13:19,  4.19batch/s]
siglip2 videos:  66%|██████▋   | 9715/14612 [1:19:26<38:57,  2.09batch/s]
irra videos:   3%|▎         | 108/3451 [00:25<13:22,  4.16batch/s]
siglip2 videos:  66%|██████▋   | 9716/14612 [1:19:27<38:54,  2.10batch/s]
irra videos:   3%|▎         | 110/3451 [00:26<13:25,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9717/14612 [1:19:27<38:54,  2.10batch/s]
irra videos:   3%|▎         | 112/3451 [00:26<13:20,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9718/14612 [1:19:28<38:51,  2.10batch/s]
irra videos:   3%|▎         | 114/3451 [00:27<13:19,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9719/14612 [1:19:28<38:53,  2.10batch/s]
irra videos:   3%|▎         | 116/3451 [00:27<13:18,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9720/14612 [1:19:28<38:49,  2.10batch/s]
siglip2 videos:  67%|██████▋   | 9721/14612 [1:19:29<38:51,  2.10batch/s]
irra videos:   3%|▎         | 119/3451 [00:28<13:09,  4.22batch/s]
irra videos:   3%|▎         | 120/3451 [00:28<13:18,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9722/14612 [1:19:29<38:44,  2.10batch/s]
irra videos:   4%|▎         | 122/3451 [00:29<13:15,  4.19batch/s]
siglip2 videos:  67%|██████▋   | 9723/14612 [1:19:30<38:46,  2.10batch/s]
irra videos:   4%|▎         | 124/3451 [00:29<13:16,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9724/14612 [1:19:30<38:44,  2.10batch/s]
irra videos:   4%|▎         | 126/3451 [00:30<13:15,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9725/14612 [1:19:31<38:48,  2.10batch/s]
irra videos:   4%|▎         | 128/3451 [00:30<13:16,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9726/14612 [1:19:31<38:46,  2.10batch/s]
irra videos:   4%|▍         | 130/3451 [00:30<13:16,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9727/14612 [1:19:32<38:49,  2.10batch/s]
irra videos:   4%|▍         | 132/3451 [00:31<13:17,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9728/14612 [1:19:32<38:50,  2.10batch/s]
irra videos:   4%|▍         | 134/3451 [00:31<13:16,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9729/14612 [1:19:33<38:48,  2.10batch/s]
irra videos:   4%|▍         | 136/3451 [00:32<13:19,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9730/14612 [1:19:33<38:53,  2.09batch/s]
irra videos:   4%|▍         | 138/3451 [00:32<13:16,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9731/14612 [1:19:34<38:52,  2.09batch/s]
irra videos:   4%|▍         | 140/3451 [00:33<13:16,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9732/14612 [1:19:34<38:53,  2.09batch/s]
irra videos:   4%|▍         | 142/3451 [00:33<13:15,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9733/14612 [1:19:35<38:49,  2.09batch/s]
irra videos:   4%|▍         | 144/3451 [00:34<13:16,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9734/14612 [1:19:35<38:52,  2.09batch/s]
irra videos:   4%|▍         | 146/3451 [00:34<13:15,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9735/14612 [1:19:36<38:53,  2.09batch/s]
irra videos:   4%|▍         | 148/3451 [00:35<13:11,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9736/14612 [1:19:36<38:43,  2.10batch/s]
irra videos:   4%|▍         | 150/3451 [00:35<13:11,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9737/14612 [1:19:37<38:45,  2.10batch/s]
irra videos:   4%|▍         | 152/3451 [00:36<13:10,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9738/14612 [1:19:37<38:43,  2.10batch/s]
irra videos:   4%|▍         | 154/3451 [00:36<13:12,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9739/14612 [1:19:38<38:47,  2.09batch/s]
irra videos:   5%|▍         | 156/3451 [00:37<13:08,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9740/14612 [1:19:38<38:37,  2.10batch/s]
irra videos:   5%|▍         | 158/3451 [00:37<13:04,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9741/14612 [1:19:38<38:28,  2.11batch/s]
irra videos:   5%|▍         | 160/3451 [00:38<13:03,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9742/14612 [1:19:39<38:24,  2.11batch/s]
irra videos:   5%|▍         | 162/3451 [00:38<13:03,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9743/14612 [1:19:39<38:26,  2.11batch/s]
irra videos:   5%|▍         | 164/3451 [00:39<13:02,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9744/14612 [1:19:40<38:25,  2.11batch/s]
irra videos:   5%|▍         | 166/3451 [00:39<13:00,  4.21batch/s]
siglip2 videos:  67%|██████▋   | 9745/14612 [1:19:40<38:25,  2.11batch/s]
irra videos:   5%|▍         | 168/3451 [00:40<13:06,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9746/14612 [1:19:41<38:26,  2.11batch/s]
irra videos:   5%|▍         | 170/3451 [00:40<13:03,  4.19batch/s]
siglip2 videos:  67%|██████▋   | 9747/14612 [1:19:41<38:32,  2.10batch/s]
irra videos:   5%|▍         | 172/3451 [00:40<13:06,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9748/14612 [1:19:42<38:34,  2.10batch/s]
irra videos:   5%|▌         | 174/3451 [00:41<13:03,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9749/14612 [1:19:42<38:28,  2.11batch/s]
irra videos:   5%|▌         | 176/3451 [00:41<12:56,  4.22batch/s]
siglip2 videos:  67%|██████▋   | 9750/14612 [1:19:43<38:23,  2.11batch/s]
irra videos:   5%|▌         | 178/3451 [00:42<13:00,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9751/14612 [1:19:43<38:23,  2.11batch/s]
irra videos:   5%|▌         | 180/3451 [00:42<13:02,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9752/14612 [1:19:44<38:31,  2.10batch/s]
irra videos:   5%|▌         | 182/3451 [00:43<13:03,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9753/14612 [1:19:44<38:31,  2.10batch/s]
irra videos:   5%|▌         | 184/3451 [00:43<13:00,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9754/14612 [1:19:45<38:26,  2.11batch/s]
irra videos:   5%|▌         | 186/3451 [00:44<13:01,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9755/14612 [1:19:45<38:27,  2.10batch/s]
irra videos:   5%|▌         | 188/3451 [00:44<12:56,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9756/14612 [1:19:46<38:20,  2.11batch/s]
irra videos:   6%|▌         | 190/3451 [00:45<12:54,  4.21batch/s]
siglip2 videos:  67%|██████▋   | 9757/14612 [1:19:46<38:24,  2.11batch/s]
irra videos:   6%|▌         | 192/3451 [00:45<13:00,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9758/14612 [1:19:47<38:22,  2.11batch/s]
irra videos:   6%|▌         | 194/3451 [00:46<12:58,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9759/14612 [1:19:47<38:24,  2.11batch/s]
irra videos:   6%|▌         | 196/3451 [00:46<13:01,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9760/14612 [1:19:48<38:29,  2.10batch/s]
irra videos:   6%|▌         | 198/3451 [00:47<13:02,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9761/14612 [1:19:48<38:34,  2.10batch/s]
irra videos:   6%|▌         | 200/3451 [00:47<13:00,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9762/14612 [1:19:48<38:26,  2.10batch/s]
irra videos:   6%|▌         | 202/3451 [00:48<12:58,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9763/14612 [1:19:49<38:22,  2.11batch/s]
irra videos:   6%|▌         | 204/3451 [00:48<12:57,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9764/14612 [1:19:49<38:26,  2.10batch/s]
irra videos:   6%|▌         | 206/3451 [00:49<12:54,  4.19batch/s]
siglip2 videos:  67%|██████▋   | 9765/14612 [1:19:50<38:22,  2.10batch/s]
irra videos:   6%|▌         | 208/3451 [00:49<12:58,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9766/14612 [1:19:50<38:18,  2.11batch/s]
irra videos:   6%|▌         | 210/3451 [00:50<12:50,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9767/14612 [1:19:51<38:18,  2.11batch/s]
irra videos:   6%|▌         | 212/3451 [00:50<12:56,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9768/14612 [1:19:51<38:24,  2.10batch/s]
irra videos:   6%|▌         | 214/3451 [00:50<13:01,  4.14batch/s]
siglip2 videos:  67%|██████▋   | 9769/14612 [1:19:52<38:35,  2.09batch/s]
irra videos:   6%|▋         | 216/3451 [00:51<12:59,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9770/14612 [1:19:52<38:31,  2.09batch/s]
irra videos:   6%|▋         | 218/3451 [00:51<12:55,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9771/14612 [1:19:53<38:26,  2.10batch/s]
irra videos:   6%|▋         | 220/3451 [00:52<12:56,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9772/14612 [1:19:53<38:28,  2.10batch/s]
irra videos:   6%|▋         | 222/3451 [00:52<12:59,  4.14batch/s]
siglip2 videos:  67%|██████▋   | 9773/14612 [1:19:54<38:35,  2.09batch/s]
irra videos:   6%|▋         | 224/3451 [00:53<12:57,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9774/14612 [1:19:54<38:32,  2.09batch/s]
irra videos:   7%|▋         | 226/3451 [00:53<12:56,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9775/14612 [1:19:55<38:33,  2.09batch/s]
irra videos:   7%|▋         | 228/3451 [00:54<12:57,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9776/14612 [1:19:55<38:33,  2.09batch/s]
irra videos:   7%|▋         | 230/3451 [00:54<12:58,  4.14batch/s]
siglip2 videos:  67%|██████▋   | 9777/14612 [1:19:56<38:37,  2.09batch/s]
irra videos:   7%|▋         | 232/3451 [00:55<12:59,  4.13batch/s]
siglip2 videos:  67%|██████▋   | 9778/14612 [1:19:56<38:38,  2.09batch/s]
irra videos:   7%|▋         | 234/3451 [00:55<12:57,  4.14batch/s]
siglip2 videos:  67%|██████▋   | 9779/14612 [1:19:57<38:41,  2.08batch/s]
irra videos:   7%|▋         | 236/3451 [00:56<12:55,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9780/14612 [1:19:57<38:38,  2.08batch/s]
irra videos:   7%|▋         | 238/3451 [00:56<12:57,  4.13batch/s]
siglip2 videos:  67%|██████▋   | 9781/14612 [1:19:58<38:36,  2.09batch/s]
irra videos:   7%|▋         | 240/3451 [00:57<12:51,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9782/14612 [1:19:58<38:30,  2.09batch/s]
irra videos:   7%|▋         | 242/3451 [00:57<12:53,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9783/14612 [1:19:58<38:33,  2.09batch/s]
irra videos:   7%|▋         | 244/3451 [00:58<12:51,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9784/14612 [1:19:59<38:25,  2.09batch/s]
irra videos:   7%|▋         | 246/3451 [00:58<12:46,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9785/14612 [1:19:59<38:20,  2.10batch/s]
irra videos:   7%|▋         | 248/3451 [00:59<12:49,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9786/14612 [1:20:00<38:22,  2.10batch/s]
irra videos:   7%|▋         | 250/3451 [00:59<12:46,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9787/14612 [1:20:00<38:18,  2.10batch/s]
irra videos:   7%|▋         | 252/3451 [01:00<12:52,  4.14batch/s]
siglip2 videos:  67%|██████▋   | 9788/14612 [1:20:01<38:24,  2.09batch/s]
irra videos:   7%|▋         | 254/3451 [01:00<12:49,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9789/14612 [1:20:01<38:26,  2.09batch/s]
irra videos:   7%|▋         | 256/3451 [01:01<12:47,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9790/14612 [1:20:02<38:20,  2.10batch/s]
irra videos:   7%|▋         | 258/3451 [01:01<12:46,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9791/14612 [1:20:02<38:20,  2.10batch/s]
irra videos:   8%|▊         | 260/3451 [01:01<12:44,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9792/14612 [1:20:03<38:15,  2.10batch/s]
irra videos:   8%|▊         | 262/3451 [01:02<12:47,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9793/14612 [1:20:03<38:20,  2.09batch/s]
irra videos:   8%|▊         | 264/3451 [01:02<12:46,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9794/14612 [1:20:04<38:19,  2.10batch/s]
siglip2 videos:  67%|██████▋   | 9795/14612 [1:20:04<38:25,  2.09batch/s]
irra videos:   8%|▊         | 267/3451 [01:03<12:38,  4.20batch/s]
irra videos:   8%|▊         | 268/3451 [01:03<12:43,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9796/14612 [1:20:05<38:19,  2.09batch/s]
irra videos:   8%|▊         | 270/3451 [01:04<12:43,  4.17batch/s]
siglip2 videos:  67%|██████▋   | 9797/14612 [1:20:05<38:13,  2.10batch/s]
irra videos:   8%|▊         | 272/3451 [01:04<12:37,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9798/14612 [1:20:06<38:07,  2.10batch/s]
irra videos:   8%|▊         | 274/3451 [01:05<12:36,  4.20batch/s]
siglip2 videos:  67%|██████▋   | 9799/14612 [1:20:06<38:08,  2.10batch/s]
irra videos:   8%|▊         | 276/3451 [01:05<12:39,  4.18batch/s]
siglip2 videos:  67%|██████▋   | 9800/14612 [1:20:07<38:09,  2.10batch/s]
irra videos:   8%|▊         | 278/3451 [01:06<12:44,  4.15batch/s]
siglip2 videos:  67%|██████▋   | 9801/14612 [1:20:07<38:15,  2.10batch/s]
irra videos:   8%|▊         | 280/3451 [01:06<12:42,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9802/14612 [1:20:08<38:17,  2.09batch/s]
irra videos:   8%|▊         | 282/3451 [01:07<12:41,  4.16batch/s]
siglip2 videos:  67%|██████▋   | 9803/14612 [1:20:08<38:13,  2.10batch/s]

-- mean: R1 14.40  mAP 25.07  mINP 25.07
-- mean_s8: R1 14.50  mAP 25.22  mINP 25.22
-- max: R1 12.30  mAP 21.85  mINP 21.85
-- query_max: R1 15.10  mAP 25.77  mINP 25.77
== IRRA | activitynet/sentence | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  78%|███████▊  | 11399/14612 [1:32:49<29:11,  1.83batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

irra texts:   0%|          | 0/227 [00:00<?, ?batch/s]
siglip2 videos:  78%|███████▊  | 11400/14612 [1:32:50<30:01,  1.78batch/s]
irra texts:   5%|▌         | 12/227 [00:00<00:03, 55.64batch/s]
irra texts:   9%|▉         | 20/227 [00:00<00:03, 63.46batch/s]
irra texts:  12%|█▏        | 28/227 [00:00<00:02, 66.90batch/s]
siglip2 videos:  78%|███████▊  | 11401/14612 [1:32:50<28:34,  1.87batch/s]
irra texts:  20%|█▉        | 45/227 [00:00<00:02, 65.04batch/s]
irra texts:  24%|██▍       | 54/227 [00:00<00:02, 71.03batch/s]
irra texts:  27%|██▋       | 62/227 [00:00<00:02, 72.15batch/s]
siglip2 videos:  78%|███████▊  | 11402/14612 [1:32:51<27:37,  1.94batch/s]
irra texts:  35%|███▍      | 79/227 [00:01<00:02, 71.25batch/s]
irra texts:  39%|███▉      | 88/227 [00:01<00:01, 74.56batch/s]
irra texts:  42%|████▏     | 96/227 [00:01<00:01, 73.72batch/s]
siglip2 videos:  78%|███████▊  | 11403/14612 [1:32:51<26:52,  1.99batch/s]
irra texts:  49%|████▉     | 112/227 [00:01<00:01, 66.58batch/s]
irra texts:  53%|█████▎    | 121/227 [00:01<00:01, 71.46batch/s]
irra texts:  57%|█████▋    | 129/227 [00:01<00:01, 72.05batch/s]
siglip2 videos:  78%|███████▊  | 11404/14612 [1:32:52<26:19,  2.03batch/s]
irra texts:  64%|██████▍   | 146/227 [00:02<00:01, 70.92batch/s]
irra texts:  68%|██████▊   | 154/227 [00:02<00:00, 73.30batch/s]
irra texts:  71%|███████▏  | 162/227 [00:02<00:00, 73.59batch/s]
siglip2 videos:  78%|███████▊  | 11405/14612 [1:32:52<25:54,  2.06batch/s]
irra texts:  79%|███████▉  | 179/227 [00:02<00:00, 74.35batch/s]
irra texts:  82%|████████▏ | 187/227 [00:02<00:00, 69.50batch/s]
irra texts:  86%|████████▌ | 195/227 [00:02<00:00, 69.73batch/s]
siglip2 videos:  78%|███████▊  | 11406/14612 [1:32:53<25:43,  2.08batch/s]
irra texts:  93%|█████████▎| 212/227 [00:02<00:00, 71.61batch/s]
irra texts: 100%|██████████| 227/227 [00:03<00:00, 71.03batch/s]
siglip2 videos:  78%|███████▊  | 11431/14612 [1:33:06<33:51,  1.57batch/s]

-- mean: R1 7.08  mAP 13.82  mINP 13.82
-- mean_s8: R1 7.30  mAP 13.99  mINP 13.99
-- max: R1 5.97  mAP 12.46  mINP 12.46
-- query_max: R1 7.82  mAP 14.82  mINP 14.82
== IRRA | activitynet/paragraph | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos:  78%|███████▊  | 11432/14612 [1:33:07<32:01,  1.65batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

irra videos:   0%|          | 0/7306 [00:00<?, ?batch/s]
siglip2 videos:  78%|███████▊  | 11433/14612 [1:33:08<43:27,  1.22batch/s]
irra videos:   0%|          | 2/7306 [00:00<24:50,  4.90batch/s]
siglip2 videos:  78%|███████▊  | 11434/14612 [1:33:09<37:55,  1.40batch/s]
irra videos:   0%|          | 4/7306 [00:00<27:32,  4.42batch/s]
siglip2 videos:  78%|███████▊  | 11435/14612 [1:33:09<34:02,  1.56batch/s]
irra videos:   0%|          | 6/7306 [00:01<28:30,  4.27batch/s]
siglip2 videos:  78%|███████▊  | 11436/14612 [1:33:10<31:23,  1.69batch/s]
irra videos:   0%|          | 8/7306 [00:01<28:47,  4.23batch/s]
siglip2 videos:  78%|███████▊  | 11437/14612 [1:33:10<29:30,  1.79batch/s]
irra videos:   0%|          | 10/7306 [00:02<29:04,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11438/14612 [1:33:11<28:11,  1.88batch/s]
irra videos:   0%|          | 12/7306 [00:02<28:53,  4.21batch/s]
siglip2 videos:  78%|███████▊  | 11439/14612 [1:33:11<27:10,  1.95batch/s]
irra videos:   0%|          | 14/7306 [00:03<29:06,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11440/14612 [1:33:12<26:35,  1.99batch/s]
irra videos:   0%|          | 16/7306 [00:03<29:00,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11441/14612 [1:33:12<26:09,  2.02batch/s]
irra videos:   0%|          | 18/7306 [00:04<29:04,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11442/14612 [1:33:13<25:50,  2.05batch/s]
irra videos:   0%|          | 20/7306 [00:04<29:06,  4.17batch/s]
siglip2 videos:  78%|███████▊  | 11443/14612 [1:33:13<25:39,  2.06batch/s]
irra videos:   0%|          | 22/7306 [00:05<29:04,  4.17batch/s]
siglip2 videos:  78%|███████▊  | 11444/14612 [1:33:14<25:28,  2.07batch/s]
irra videos:   0%|          | 24/7306 [00:05<29:02,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11445/14612 [1:33:14<25:19,  2.08batch/s]
irra videos:   0%|          | 26/7306 [00:06<29:00,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11446/14612 [1:33:14<25:16,  2.09batch/s]
irra videos:   0%|          | 28/7306 [00:06<28:58,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11447/14612 [1:33:15<25:10,  2.10batch/s]
irra videos:   0%|          | 30/7306 [00:07<29:10,  4.16batch/s]
siglip2 videos:  78%|███████▊  | 11448/14612 [1:33:15<25:16,  2.09batch/s]
irra videos:   0%|          | 32/7306 [00:07<29:12,  4.15batch/s]
siglip2 videos:  78%|███████▊  | 11449/14612 [1:33:16<25:13,  2.09batch/s]
irra videos:   0%|          | 34/7306 [00:08<29:14,  4.14batch/s]
siglip2 videos:  78%|███████▊  | 11450/14612 [1:33:16<25:10,  2.09batch/s]
siglip2 videos:  78%|███████▊  | 11451/14612 [1:33:17<25:06,  2.10batch/s]
irra videos:   1%|          | 37/7306 [00:08<28:37,  4.23batch/s]
irra videos:   1%|          | 38/7306 [00:08<28:51,  4.20batch/s]
siglip2 videos:  78%|███████▊  | 11452/14612 [1:33:17<25:04,  2.10batch/s]
irra videos:   1%|          | 40/7306 [00:09<29:09,  4.15batch/s]
siglip2 videos:  78%|███████▊  | 11453/14612 [1:33:18<25:07,  2.10batch/s]
irra videos:   1%|          | 42/7306 [00:09<29:08,  4.15batch/s]
siglip2 videos:  78%|███████▊  | 11454/14612 [1:33:18<25:10,  2.09batch/s]
irra videos:   1%|          | 44/7306 [00:10<29:13,  4.14batch/s]
siglip2 videos:  78%|███████▊  | 11455/14612 [1:33:19<25:11,  2.09batch/s]
irra videos:   1%|          | 46/7306 [00:10<29:06,  4.16batch/s]
siglip2 videos:  78%|███████▊  | 11456/14612 [1:33:19<25:05,  2.10batch/s]
irra videos:   1%|          | 48/7306 [00:11<28:55,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11457/14612 [1:33:20<25:01,  2.10batch/s]
irra videos:   1%|          | 50/7306 [00:11<28:41,  4.22batch/s]
siglip2 videos:  78%|███████▊  | 11458/14612 [1:33:20<24:59,  2.10batch/s]
irra videos:   1%|          | 52/7306 [00:12<28:52,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11459/14612 [1:33:21<24:57,  2.11batch/s]
irra videos:   1%|          | 54/7306 [00:12<28:44,  4.21batch/s]
siglip2 videos:  78%|███████▊  | 11460/14612 [1:33:21<24:53,  2.11batch/s]
irra videos:   1%|          | 56/7306 [00:13<28:46,  4.20batch/s]
siglip2 videos:  78%|███████▊  | 11461/14612 [1:33:22<24:54,  2.11batch/s]
irra videos:   1%|          | 58/7306 [00:13<28:53,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11462/14612 [1:33:22<24:54,  2.11batch/s]
irra videos:   1%|          | 60/7306 [00:14<28:45,  4.20batch/s]
siglip2 videos:  78%|███████▊  | 11463/14612 [1:33:23<24:53,  2.11batch/s]
irra videos:   1%|          | 62/7306 [00:14<28:52,  4.18batch/s]
siglip2 videos:  78%|███████▊  | 11464/14612 [1:33:23<24:53,  2.11batch/s]
irra videos:   1%|          | 64/7306 [00:15<28:49,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11465/14612 [1:33:24<24:56,  2.10batch/s]
irra videos:   1%|          | 66/7306 [00:15<28:54,  4.17batch/s]
siglip2 videos:  78%|███████▊  | 11466/14612 [1:33:24<24:52,  2.11batch/s]
irra videos:   1%|          | 68/7306 [00:16<28:46,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11467/14612 [1:33:24<24:49,  2.11batch/s]
irra videos:   1%|          | 70/7306 [00:16<28:43,  4.20batch/s]
siglip2 videos:  78%|███████▊  | 11468/14612 [1:33:25<24:51,  2.11batch/s]
irra videos:   1%|          | 72/7306 [00:17<28:44,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11469/14612 [1:33:25<24:50,  2.11batch/s]
irra videos:   1%|          | 74/7306 [00:17<28:44,  4.19batch/s]
siglip2 videos:  78%|███████▊  | 11470/14612 [1:33:26<24:51,  2.11batch/s]
irra videos:   1%|          | 76/7306 [00:17<28:36,  4.21batch/s]
siglip2 videos:  79%|███████▊  | 11471/14612 [1:33:26<24:43,  2.12batch/s]
irra videos:   1%|          | 78/7306 [00:18<28:36,  4.21batch/s]
siglip2 videos:  79%|███████▊  | 11472/14612 [1:33:27<24:43,  2.12batch/s]
irra videos:   1%|          | 80/7306 [00:18<28:39,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11473/14612 [1:33:27<24:47,  2.11batch/s]
irra videos:   1%|          | 82/7306 [00:19<28:48,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11474/14612 [1:33:28<24:47,  2.11batch/s]
irra videos:   1%|          | 84/7306 [00:19<28:53,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11475/14612 [1:33:28<24:51,  2.10batch/s]
irra videos:   1%|          | 86/7306 [00:20<29:00,  4.15batch/s]
siglip2 videos:  79%|███████▊  | 11476/14612 [1:33:29<24:54,  2.10batch/s]
irra videos:   1%|          | 88/7306 [00:20<28:46,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11477/14612 [1:33:29<24:49,  2.10batch/s]
irra videos:   1%|          | 90/7306 [00:21<28:51,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11478/14612 [1:33:30<24:50,  2.10batch/s]
irra videos:   1%|▏         | 92/7306 [00:21<28:43,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11479/14612 [1:33:30<24:53,  2.10batch/s]
irra videos:   1%|▏         | 94/7306 [00:22<28:57,  4.15batch/s]
siglip2 videos:  79%|███████▊  | 11480/14612 [1:33:31<24:52,  2.10batch/s]
siglip2 videos:  79%|███████▊  | 11481/14612 [1:33:31<24:49,  2.10batch/s]
irra videos:   1%|▏         | 97/7306 [00:22<28:23,  4.23batch/s]
irra videos:   1%|▏         | 98/7306 [00:23<28:40,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11482/14612 [1:33:32<24:46,  2.11batch/s]
irra videos:   1%|▏         | 100/7306 [00:23<28:41,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11483/14612 [1:33:32<24:49,  2.10batch/s]
irra videos:   1%|▏         | 102/7306 [00:24<28:48,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11484/14612 [1:33:33<24:48,  2.10batch/s]
irra videos:   1%|▏         | 104/7306 [00:24<28:38,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11485/14612 [1:33:33<24:47,  2.10batch/s]
irra videos:   1%|▏         | 106/7306 [00:25<28:46,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11486/14612 [1:33:33<24:47,  2.10batch/s]
irra videos:   1%|▏         | 108/7306 [00:25<28:43,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11487/14612 [1:33:34<24:47,  2.10batch/s]
irra videos:   2%|▏         | 110/7306 [00:26<28:48,  4.16batch/s]
siglip2 videos:  79%|███████▊  | 11488/14612 [1:33:34<24:48,  2.10batch/s]
irra videos:   2%|▏         | 112/7306 [00:26<28:48,  4.16batch/s]
siglip2 videos:  79%|███████▊  | 11489/14612 [1:33:35<24:46,  2.10batch/s]
irra videos:   2%|▏         | 114/7306 [00:27<28:34,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11490/14612 [1:33:35<24:44,  2.10batch/s]
irra videos:   2%|▏         | 116/7306 [00:27<28:39,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11491/14612 [1:33:36<24:45,  2.10batch/s]
irra videos:   2%|▏         | 118/7306 [00:27<28:35,  4.19batch/s]
siglip2 videos:  79%|███████▊  | 11492/14612 [1:33:36<24:40,  2.11batch/s]
irra videos:   2%|▏         | 120/7306 [00:28<28:37,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11493/14612 [1:33:37<24:45,  2.10batch/s]
irra videos:   2%|▏         | 122/7306 [00:28<28:37,  4.18batch/s]
siglip2 videos:  79%|███████▊  | 11494/14612 [1:33:37<24:40,  2.11batch/s]
irra videos:   2%|▏         | 124/7306 [00:29<28:29,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11495/14612 [1:33:38<24:37,  2.11batch/s]
irra videos:   2%|▏         | 126/7306 [00:29<28:24,  4.21batch/s]
siglip2 videos:  79%|███████▊  | 11496/14612 [1:33:38<24:35,  2.11batch/s]
irra videos:   2%|▏         | 128/7306 [00:30<28:27,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11497/14612 [1:33:39<24:35,  2.11batch/s]
irra videos:   2%|▏         | 130/7306 [00:30<28:26,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11498/14612 [1:33:39<24:33,  2.11batch/s]
irra videos:   2%|▏         | 132/7306 [00:31<28:28,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11499/14612 [1:33:40<24:33,  2.11batch/s]
irra videos:   2%|▏         | 134/7306 [00:31<28:23,  4.21batch/s]
siglip2 videos:  79%|███████▊  | 11500/14612 [1:33:40<24:32,  2.11batch/s]
irra videos:   2%|▏         | 136/7306 [00:32<28:26,  4.20batch/s]
siglip2 videos:  79%|███████▊  | 11501/14612 [1:33:41<24:38,  2.10batch/s]
irra videos:   2%|▏         | 138/7306 [00:32<28:39,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11502/14612 [1:33:41<24:37,  2.11batch/s]
irra videos:   2%|▏         | 140/7306 [00:33<28:43,  4.16batch/s]
siglip2 videos:  79%|███████▊  | 11503/14612 [1:33:42<24:40,  2.10batch/s]
irra videos:   2%|▏         | 142/7306 [00:33<28:37,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11504/14612 [1:33:42<24:39,  2.10batch/s]
irra videos:   2%|▏         | 144/7306 [00:34<28:36,  4.17batch/s]
siglip2 videos:  79%|███████▊  | 11505/14612 [1:33:43<24:39,  2.10batch/s]
irra videos:   2%|▏         | 146/7306 [00:34<28:45,  4.15batch/s]
siglip2 videos:  79%|███████▊  | 11506/14612 [1:33:43<24:44,  2.09batch/s]
irra videos:   2%|▏         | 148/7306 [00:35<28:42,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11507/14612 [1:33:43<24:43,  2.09batch/s]
irra videos:   2%|▏         | 150/7306 [00:35<28:42,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11508/14612 [1:33:44<24:43,  2.09batch/s]
irra videos:   2%|▏         | 152/7306 [00:36<28:43,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11509/14612 [1:33:44<24:45,  2.09batch/s]
siglip2 videos:  79%|███████▉  | 11510/14612 [1:33:45<24:44,  2.09batch/s]
irra videos:   2%|▏         | 155/7306 [00:36<28:21,  4.20batch/s]
irra videos:   2%|▏         | 156/7306 [00:37<28:35,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11511/14612 [1:33:45<24:40,  2.09batch/s]
irra videos:   2%|▏         | 158/7306 [00:37<28:31,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11512/14612 [1:33:46<24:39,  2.10batch/s]
irra videos:   2%|▏         | 160/7306 [00:37<28:44,  4.14batch/s]
siglip2 videos:  79%|███████▉  | 11513/14612 [1:33:46<24:40,  2.09batch/s]
irra videos:   2%|▏         | 162/7306 [00:38<28:34,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11514/14612 [1:33:47<24:39,  2.09batch/s]
irra videos:   2%|▏         | 164/7306 [00:38<28:31,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11515/14612 [1:33:47<24:35,  2.10batch/s]
irra videos:   2%|▏         | 166/7306 [00:39<28:24,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11516/14612 [1:33:48<24:33,  2.10batch/s]
irra videos:   2%|▏         | 168/7306 [00:39<28:18,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11517/14612 [1:33:48<24:28,  2.11batch/s]
irra videos:   2%|▏         | 170/7306 [00:40<28:19,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11518/14612 [1:33:49<24:26,  2.11batch/s]
irra videos:   2%|▏         | 172/7306 [00:40<28:15,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11519/14612 [1:33:49<24:25,  2.11batch/s]
irra videos:   2%|▏         | 174/7306 [00:41<28:18,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11520/14612 [1:33:50<24:24,  2.11batch/s]
irra videos:   2%|▏         | 176/7306 [00:41<28:16,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11521/14612 [1:33:50<24:23,  2.11batch/s]
irra videos:   2%|▏         | 178/7306 [00:42<28:13,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11522/14612 [1:33:51<24:23,  2.11batch/s]
irra videos:   2%|▏         | 180/7306 [00:42<28:18,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11523/14612 [1:33:51<24:23,  2.11batch/s]
irra videos:   2%|▏         | 182/7306 [00:43<28:03,  4.23batch/s]
siglip2 videos:  79%|███████▉  | 11524/14612 [1:33:52<24:17,  2.12batch/s]
irra videos:   3%|▎         | 184/7306 [00:43<28:11,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11525/14612 [1:33:52<24:19,  2.11batch/s]
irra videos:   3%|▎         | 186/7306 [00:44<28:06,  4.22batch/s]
siglip2 videos:  79%|███████▉  | 11526/14612 [1:33:52<24:18,  2.12batch/s]
irra videos:   3%|▎         | 188/7306 [00:44<27:54,  4.25batch/s]
siglip2 videos:  79%|███████▉  | 11527/14612 [1:33:53<24:09,  2.13batch/s]
irra videos:   3%|▎         | 190/7306 [00:45<28:05,  4.22batch/s]
siglip2 videos:  79%|███████▉  | 11528/14612 [1:33:53<24:12,  2.12batch/s]
irra videos:   3%|▎         | 192/7306 [00:45<28:09,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11529/14612 [1:33:54<24:16,  2.12batch/s]
irra videos:   3%|▎         | 194/7306 [00:45<28:11,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11530/14612 [1:33:54<24:14,  2.12batch/s]
irra videos:   3%|▎         | 196/7306 [00:46<28:10,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11531/14612 [1:33:55<24:18,  2.11batch/s]
irra videos:   3%|▎         | 198/7306 [00:46<28:28,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11532/14612 [1:33:55<24:23,  2.10batch/s]
irra videos:   3%|▎         | 200/7306 [00:47<28:16,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11533/14612 [1:33:56<24:24,  2.10batch/s]
irra videos:   3%|▎         | 202/7306 [00:47<28:21,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11534/14612 [1:33:56<24:21,  2.11batch/s]
irra videos:   3%|▎         | 204/7306 [00:48<28:25,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11535/14612 [1:33:57<24:24,  2.10batch/s]
irra videos:   3%|▎         | 206/7306 [00:48<28:16,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11536/14612 [1:33:57<24:21,  2.10batch/s]
irra videos:   3%|▎         | 208/7306 [00:49<28:10,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11537/14612 [1:33:58<24:22,  2.10batch/s]
irra videos:   3%|▎         | 210/7306 [00:49<28:24,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11538/14612 [1:33:58<24:21,  2.10batch/s]
irra videos:   3%|▎         | 212/7306 [00:50<28:11,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11539/14612 [1:33:59<24:19,  2.10batch/s]
irra videos:   3%|▎         | 214/7306 [00:50<28:17,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11540/14612 [1:33:59<24:20,  2.10batch/s]
irra videos:   3%|▎         | 216/7306 [00:51<28:14,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11541/14612 [1:34:00<24:21,  2.10batch/s]
irra videos:   3%|▎         | 218/7306 [00:51<28:21,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11542/14612 [1:34:00<24:22,  2.10batch/s]
irra videos:   3%|▎         | 220/7306 [00:52<28:09,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11543/14612 [1:34:01<24:19,  2.10batch/s]
irra videos:   3%|▎         | 222/7306 [00:52<28:14,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11544/14612 [1:34:01<24:13,  2.11batch/s]
irra videos:   3%|▎         | 224/7306 [00:53<28:03,  4.21batch/s]
siglip2 videos:  79%|███████▉  | 11545/14612 [1:34:02<24:15,  2.11batch/s]
irra videos:   3%|▎         | 226/7306 [00:53<28:18,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11546/14612 [1:34:02<24:17,  2.10batch/s]
irra videos:   3%|▎         | 228/7306 [00:54<28:16,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11547/14612 [1:34:02<24:23,  2.09batch/s]
irra videos:   3%|▎         | 230/7306 [00:54<28:21,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11548/14612 [1:34:03<24:20,  2.10batch/s]
irra videos:   3%|▎         | 232/7306 [00:55<28:15,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11549/14612 [1:34:03<24:18,  2.10batch/s]
irra videos:   3%|▎         | 234/7306 [00:55<28:23,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11550/14612 [1:34:04<24:24,  2.09batch/s]
siglip2 videos:  79%|███████▉  | 11551/14612 [1:34:04<24:22,  2.09batch/s]
irra videos:   3%|▎         | 237/7306 [00:56<27:59,  4.21batch/s]
irra videos:   3%|▎         | 238/7306 [00:56<28:17,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11552/14612 [1:34:05<24:22,  2.09batch/s]
irra videos:   3%|▎         | 240/7306 [00:56<28:27,  4.14batch/s]
siglip2 videos:  79%|███████▉  | 11553/14612 [1:34:05<24:26,  2.09batch/s]
irra videos:   3%|▎         | 242/7306 [00:57<28:24,  4.14batch/s]
siglip2 videos:  79%|███████▉  | 11554/14612 [1:34:06<24:23,  2.09batch/s]
irra videos:   3%|▎         | 244/7306 [00:57<28:19,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11555/14612 [1:34:06<24:22,  2.09batch/s]
irra videos:   3%|▎         | 246/7306 [00:58<28:11,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11556/14612 [1:34:07<24:17,  2.10batch/s]
irra videos:   3%|▎         | 248/7306 [00:58<28:06,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11557/14612 [1:34:07<24:15,  2.10batch/s]
irra videos:   3%|▎         | 250/7306 [00:59<28:14,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11558/14612 [1:34:08<24:17,  2.09batch/s]
irra videos:   3%|▎         | 252/7306 [00:59<28:14,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11559/14612 [1:34:08<24:15,  2.10batch/s]
irra videos:   3%|▎         | 254/7306 [01:00<28:00,  4.20batch/s]
siglip2 videos:  79%|███████▉  | 11560/14612 [1:34:09<24:08,  2.11batch/s]
siglip2 videos:  79%|███████▉  | 11561/14612 [1:34:09<24:09,  2.10batch/s]
irra videos:   4%|▎         | 257/7306 [01:00<27:44,  4.24batch/s]
irra videos:   4%|▎         | 258/7306 [01:01<28:02,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11562/14612 [1:34:10<24:08,  2.11batch/s]
irra videos:   4%|▎         | 260/7306 [01:01<28:06,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11563/14612 [1:34:10<24:10,  2.10batch/s]
irra videos:   4%|▎         | 262/7306 [01:02<28:03,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11564/14612 [1:34:11<24:08,  2.10batch/s]
irra videos:   4%|▎         | 264/7306 [01:02<28:06,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11565/14612 [1:34:11<24:11,  2.10batch/s]
irra videos:   4%|▎         | 266/7306 [01:03<28:11,  4.16batch/s]
siglip2 videos:  79%|███████▉  | 11566/14612 [1:34:12<24:11,  2.10batch/s]
irra videos:   4%|▎         | 268/7306 [01:03<27:59,  4.19batch/s]
siglip2 videos:  79%|███████▉  | 11567/14612 [1:34:12<24:09,  2.10batch/s]
irra videos:   4%|▎         | 270/7306 [01:04<28:14,  4.15batch/s]
siglip2 videos:  79%|███████▉  | 11568/14612 [1:34:12<24:10,  2.10batch/s]
irra videos:   4%|▎         | 272/7306 [01:04<28:01,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11569/14612 [1:34:13<24:08,  2.10batch/s]
irra videos:   4%|▍         | 274/7306 [01:05<28:02,  4.18batch/s]
siglip2 videos:  79%|███████▉  | 11570/14612 [1:34:13<24:05,  2.11batch/s]
irra videos:   4%|▍         | 276/7306 [01:05<28:04,  4.17batch/s]
siglip2 videos:  79%|███████▉  | 11571/14612 [1:34:14<24:11,  2.10batch/s]
irra videos:   4%|▍         | 278/7306 [01:06<28:26,  4.12batch/s]
siglip2 videos:  79%|███████▉  | 11572/14612 [1:34:14<24:15,  2.09batch/s]
irra videos:   4%|▍         | 280/7306 [01:06<28:15,  4.14batch/s]
siglip2 videos:  79%|███████▉  | 11573/14612 [1:34:15<24:11,  2.09batch/s]

-- mean: R1 54.40  mAP 68.25  mINP 68.25
-- mean_s8: R1 53.90  mAP 68.02  mINP 68.02
-- max: R1 50.40  mAP 64.56  mINP 64.56
-- query_max: R1 57.10  mAP 70.18  mINP 70.18
== SigLIP 2 So400m | activitynet/sentence | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  88%|████████▊ | 6412/7306 [25:23<06:28,  2.30batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

siglip2 texts:   0%|          | 0/227 [00:00<?, ?batch/s]
siglip2 texts:   1%|          | 2/227 [00:00<00:16, 13.88batch/s]s]
siglip2 texts:   2%|▏         | 4/227 [00:00<00:15, 14.62batch/s]s]
siglip2 texts:   3%|▎         | 6/227 [00:00<00:13, 15.81batch/s]s]
siglip2 texts:   4%|▎         | 8/227 [00:00<00:13, 16.52batch/s]s]
siglip2 texts:   4%|▍         | 10/227 [00:00<00:12, 16.96batch/s]]
siglip2 texts:   6%|▌         | 14/227 [00:00<00:12, 17.44batch/s]]
siglip2 texts:   7%|▋         | 16/227 [00:00<00:12, 17.47batch/s]]
siglip2 texts:   8%|▊         | 18/227 [00:01<00:11, 17.66batch/s]]
siglip2 texts:  10%|▉         | 22/227 [00:01<00:11, 17.58batch/s]]
siglip2 texts:  11%|█         | 24/227 [00:01<00:11, 17.64batch/s]]
siglip2 texts:  11%|█▏        | 26/227 [00:01<00:11, 17.56batch/s]]
siglip2 texts:  12%|█▏        | 28/227 [00:01<00:11, 17.65batch/s]]
siglip2 texts:  13%|█▎        | 30/227 [00:01<00:11, 17.53batch/s]]
siglip2 texts:  14%|█▍        | 32/227 [00:01<00:11, 17.44batch/s]]
siglip2 texts:  15%|█▍        | 34/227 [00:01<00:11, 17.48batch/s]]
siglip2 texts:  16%|█▌        | 36/227 [00:02<00:10, 17.47batch/s]]
siglip2 texts:  17%|█▋        | 38/227 [00:02<00:10, 17.37batch/s]]
siglip2 texts:  18%|█▊        | 40/227 [00:02<00:10, 17.54batch/s]]
siglip2 texts:  19%|█▊        | 42/227 [00:02<00:10, 17.46batch/s]]
siglip2 texts:  19%|█▉        | 44/227 [00:02<00:10, 17.45batch/s]]
siglip2 texts:  20%|██        | 46/227 [00:02<00:10, 17.51batch/s]]
siglip2 texts:  21%|██        | 48/227 [00:02<00:10, 17.40batch/s]]
siglip2 texts:  22%|██▏       | 50/227 [00:02<00:10, 17.43batch/s]]
siglip2 texts:  24%|██▍       | 54/227 [00:03<00:09, 17.61batch/s]]
siglip2 texts:  25%|██▍       | 56/227 [00:03<00:09, 17.66batch/s]]
siglip2 texts:  26%|██▌       | 58/227 [00:03<00:09, 17.52batch/s]]
siglip2 texts:  26%|██▋       | 60/227 [00:03<00:09, 17.34batch/s]]
siglip2 texts:  27%|██▋       | 62/227 [00:03<00:09, 17.48batch/s]]
siglip2 texts:  28%|██▊       | 64/227 [00:03<00:09, 17.39batch/s]]
siglip2 texts:  29%|██▉       | 66/227 [00:03<00:09, 17.31batch/s]]
siglip2 texts:  30%|██▉       | 68/227 [00:03<00:09, 17.51batch/s]]
siglip2 texts:  32%|███▏      | 72/227 [00:04<00:08, 17.59batch/s]]
siglip2 texts:  33%|███▎      | 74/227 [00:04<00:08, 17.66batch/s]]
siglip2 texts:  33%|███▎      | 76/227 [00:04<00:08, 17.43batch/s]]
siglip2 texts:  34%|███▍      | 78/227 [00:04<00:08, 17.25batch/s]]
siglip2 texts:  35%|███▌      | 80/227 [00:04<00:08, 17.37batch/s]]
siglip2 texts:  36%|███▌      | 82/227 [00:04<00:08, 17.39batch/s]]
siglip2 texts:  37%|███▋      | 84/227 [00:04<00:08, 17.30batch/s]]
siglip2 texts:  38%|███▊      | 86/227 [00:04<00:08, 17.40batch/s]]
siglip2 texts:  39%|███▉      | 88/227 [00:05<00:08, 17.37batch/s]]
siglip2 texts:  40%|███▉      | 90/227 [00:05<00:07, 17.36batch/s]]
siglip2 texts:  41%|████      | 92/227 [00:05<00:07, 17.50batch/s]]
siglip2 texts:  41%|████▏     | 94/227 [00:05<00:07, 17.43batch/s]]
siglip2 texts:  42%|████▏     | 96/227 [00:05<00:07, 17.23batch/s]]
siglip2 texts:  44%|████▍     | 100/227 [00:05<00:07, 17.37batch/s]
siglip2 texts:  45%|████▍     | 102/227 [00:05<00:07, 17.35batch/s]
siglip2 texts:  46%|████▌     | 104/227 [00:05<00:07, 17.31batch/s]
siglip2 texts:  47%|████▋     | 106/227 [00:06<00:06, 17.48batch/s]
siglip2 texts:  48%|████▊     | 108/227 [00:06<00:06, 17.48batch/s]
siglip2 texts:  48%|████▊     | 110/227 [00:06<00:06, 17.49batch/s]
siglip2 texts:  49%|████▉     | 112/227 [00:06<00:06, 17.45batch/s]
siglip2 texts:  51%|█████     | 116/227 [00:06<00:06, 17.50batch/s]
siglip2 texts:  52%|█████▏    | 118/227 [00:06<00:06, 17.47batch/s]
siglip2 texts:  53%|█████▎    | 120/227 [00:06<00:06, 17.37batch/s]
siglip2 texts:  54%|█████▎    | 122/227 [00:07<00:06, 17.29batch/s]
siglip2 texts:  55%|█████▍    | 124/227 [00:07<00:05, 17.38batch/s]
siglip2 texts:  56%|█████▌    | 126/227 [00:07<00:05, 17.34batch/s]
siglip2 texts:  56%|█████▋    | 128/227 [00:07<00:05, 17.18batch/s]
siglip2 texts:  57%|█████▋    | 130/227 [00:07<00:05, 17.20batch/s]
siglip2 texts:  58%|█████▊    | 132/227 [00:07<00:05, 17.29batch/s]
siglip2 texts:  59%|█████▉    | 134/227 [00:07<00:05, 17.27batch/s]
siglip2 texts:  60%|█████▉    | 136/227 [00:07<00:05, 17.13batch/s]
siglip2 texts:  61%|██████    | 138/227 [00:07<00:05, 17.19batch/s]
siglip2 texts:  62%|██████▏   | 140/227 [00:08<00:05, 17.20batch/s]
siglip2 texts:  63%|██████▎   | 142/227 [00:08<00:04, 17.08batch/s]
siglip2 texts:  63%|██████▎   | 144/227 [00:08<00:04, 17.01batch/s]
siglip2 texts:  64%|██████▍   | 146/227 [00:08<00:04, 16.90batch/s]
siglip2 texts:  65%|██████▌   | 148/227 [00:08<00:04, 16.96batch/s]
siglip2 texts:  66%|██████▌   | 150/227 [00:08<00:04, 17.12batch/s]
siglip2 texts:  67%|██████▋   | 152/227 [00:08<00:04, 17.10batch/s]
siglip2 texts:  68%|██████▊   | 154/227 [00:08<00:04, 17.01batch/s]
siglip2 texts:  70%|██████▉   | 158/227 [00:09<00:04, 17.20batch/s]
siglip2 texts:  70%|███████   | 160/227 [00:09<00:03, 17.24batch/s]
siglip2 texts:  71%|███████▏  | 162/227 [00:09<00:03, 17.18batch/s]
siglip2 texts:  72%|███████▏  | 164/227 [00:09<00:03, 17.18batch/s]
siglip2 texts:  73%|███████▎  | 166/227 [00:09<00:03, 17.20batch/s]
siglip2 texts:  74%|███████▍  | 168/227 [00:09<00:03, 17.18batch/s]
siglip2 texts:  75%|███████▍  | 170/227 [00:09<00:03, 17.09batch/s]
siglip2 texts:  76%|███████▌  | 172/227 [00:09<00:03, 16.94batch/s]
siglip2 texts:  77%|███████▋  | 174/227 [00:10<00:03, 16.91batch/s]
siglip2 texts:  78%|███████▊  | 176/227 [00:10<00:03, 16.93batch/s]
siglip2 texts:  79%|███████▉  | 180/227 [00:10<00:02, 17.14batch/s]
siglip2 texts:  80%|████████  | 182/227 [00:10<00:02, 17.05batch/s]
siglip2 texts:  81%|████████  | 184/227 [00:10<00:02, 17.07batch/s]
siglip2 texts:  82%|████████▏ | 186/227 [00:10<00:02, 17.10batch/s]
siglip2 texts:  83%|████████▎ | 188/227 [00:10<00:02, 17.08batch/s]
siglip2 texts:  84%|████████▎ | 190/227 [00:11<00:02, 16.99batch/s]
siglip2 texts:  85%|████████▌ | 194/227 [00:11<00:01, 16.97batch/s]
siglip2 texts:  86%|████████▋ | 196/227 [00:11<00:01, 17.04batch/s]
siglip2 texts:  87%|████████▋ | 198/227 [00:11<00:01, 17.05batch/s]
siglip2 texts:  88%|████████▊ | 200/227 [00:11<00:01, 17.01batch/s]
siglip2 texts:  89%|████████▉ | 202/227 [00:11<00:01, 16.86batch/s]
irra videos:  89%|████████▉ | 6505/7306 [25:36<01:38,  8.16batch/s]
siglip2 texts:  91%|█████████ | 206/227 [00:11<00:01, 16.65batch/s]
siglip2 texts:  92%|█████████▏| 208/227 [00:12<00:01, 16.58batch/s]
siglip2 texts:  93%|█████████▎| 210/227 [00:12<00:01, 16.58batch/s]
siglip2 texts:  93%|█████████▎| 212/227 [00:12<00:00, 16.64batch/s]
siglip2 texts:  94%|█████████▍| 214/227 [00:12<00:00, 16.55batch/s]
siglip2 texts:  96%|█████████▌| 218/227 [00:12<00:00, 16.70batch/s]
siglip2 texts:  97%|█████████▋| 220/227 [00:12<00:00, 16.77batch/s]
siglip2 texts:  98%|█████████▊| 222/227 [00:12<00:00, 16.89batch/s]
siglip2 texts:  99%|█████████▊| 224/227 [00:13<00:00, 16.94batch/s]
siglip2 texts: 100%|██████████| 227/227 [00:13<00:00, 17.22batch/s]

irra videos:  89%|████████▉ | 6516/7306 [25:38<01:45,  7.48batch/s]
irra videos:  89%|████████▉ | 6517/7306 [25:38<01:51,  7.07batch/s]
irra videos:  89%|████████▉ | 6518/7306 [25:39<02:46,  4.74batch/s]
irra videos:  89%|████████▉ | 6519/7306 [25:39<04:00,  3.27batch/s]
irra videos:  89%|████████▉ | 6520/7306 [25:40<04:42,  2.78batch/s]
irra videos:  89%|████████▉ | 6521/7306 [25:40<05:48,  2.25batch/s]
irra videos:  89%|████████▉ | 6522/7306 [25:41<05:50,  2.24batch/s]
irra videos:  89%|████████▉ | 6523/7306 [25:41<05:46,  2.26batch/s]
irra videos:  89%|████████▉ | 6524/7306 [25:41<05:01,  2.59batch/s]
irra videos:  89%|████████▉ | 6525/7306 [25:42<05:07,  2.54batch/s]
irra videos:  89%|████████▉ | 6526/7306 [25:42<05:32,  2.34batch/s]
irra videos:  89%|████████▉ | 6527/7306 [25:43<05:59,  2.17batch/s]
irra videos:  89%|████████▉ | 6528/7306 [25:43<06:06,  2.12batch/s]
irra videos:  89%|████████▉ | 6529/7306 [25:44<06:35,  1.96batch/s]
irra videos:  89%|████████▉ | 6530/7306 [25:44<07:04,  1.83batch/s]
irra videos:  89%|████████▉ | 6531/7306 [25:45<07:08,  1.81batch/s]
irra videos:  89%|████████▉ | 6532/7306 [25:46<06:56,  1.86batch/s]
irra videos:  89%|████████▉ | 6533/7306 [25:46<07:22,  1.75batch/s]
irra videos:  89%|████████▉ | 6534/7306 [25:47<06:28,  1.99batch/s]
irra videos:  89%|████████▉ | 6535/7306 [25:47<05:57,  2.16batch/s]
irra videos:  89%|████████▉ | 6536/7306 [25:47<06:09,  2.08batch/s]
irra videos:  89%|████████▉ | 6537/7306 [25:48<05:39,  2.27batch/s]
irra videos:  89%|████████▉ | 6538/7306 [25:48<04:54,  2.61batch/s]
irra videos:  90%|████████▉ | 6539/7306 [25:48<04:16,  2.99batch/s]
irra videos:  90%|████████▉ | 6540/7306 [25:48<03:53,  3.28batch/s]
irra videos:  90%|████████▉ | 6541/7306 [25:49<03:35,  3.55batch/s]
irra videos:  90%|████████▉ | 6542/7306 [25:49<03:29,  3.65batch/s]
irra videos:  90%|████████▉ | 6543/7306 [25:49<03:47,  3.36batch/s]
irra videos:  90%|████████▉ | 6544/7306 [25:50<03:29,  3.64batch/s]
irra videos:  90%|████████▉ | 6545/7306 [25:50<03:34,  3.55batch/s]
irra videos:  90%|████████▉ | 6546/7306 [25:50<03:34,  3.55batch/s]
irra videos:  90%|████████▉ | 6547/7306 [25:51<04:33,  2.77batch/s]
irra videos:  90%|████████▉ | 6548/7306 [25:51<04:17,  2.95batch/s]
irra videos:  90%|████████▉ | 6549/7306 [25:51<04:06,  3.07batch/s]
irra videos:  90%|████████▉ | 6550/7306 [25:52<03:56,  3.20batch/s]
irra videos:  90%|████████▉ | 6551/7306 [25:52<03:46,  3.34batch/s]
irra videos:  90%|████████▉ | 6552/7306 [25:52<03:35,  3.49batch/s]
irra videos:  90%|████████▉ | 6553/7306 [25:52<03:26,  3.65batch/s]
irra videos:  90%|████████▉ | 6554/7306 [25:53<03:27,  3.62batch/s]
irra videos:  90%|████████▉ | 6555/7306 [25:53<03:32,  3.54batch/s]
irra videos:  90%|████████▉ | 6556/7306 [25:53<03:25,  3.65batch/s]
irra videos:  90%|████████▉ | 6557/7306 [25:54<04:11,  2.98batch/s]
irra videos:  90%|████████▉ | 6558/7306 [25:55<07:27,  1.67batch/s]

-- mean: R1 31.08  mAP 44.24  mINP 44.24
-- mean_s8: R1 30.69  mAP 44.02  mINP 44.02
-- max: R1 28.12  mAP 41.56  mINP 41.56
-- query_max: R1 35.11  mAP 48.51  mINP 48.51

######## GPU 0 | X-CLIP: 8 of 8 runs to do

irra videos:  90%|████████▉ | 6559/7306 [25:56<09:01,  1.38batch/s]
irra videos:  90%|████████▉ | 6561/7306 [25:56<05:24,  2.29batch/s]

preprocessor_config.json:   0%|          | 0.00/309 [00:00<?, ?B/s]

irra videos:  90%|████████▉ | 6563/7306 [25:56<03:43,  3.32batch/s]
irra videos:  90%|████████▉ | 6564/7306 [25:56<03:11,  3.88batch/s]
irra videos:  90%|████████▉ | 6566/7306 [25:57<02:22,  5.19batch/s]
irra videos:  90%|████████▉ | 6567/7306 [25:57<02:09,  5.69batch/s]
irra videos:  90%|████████▉ | 6569/7306 [25:57<01:46,  6.95batch/s][transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.

irra videos:  90%|████████▉ | 6571/7306 [25:57<01:33,  7.90batch/s]
irra videos:  90%|████████▉ | 6573/7306 [25:57<01:23,  8.74batch/s]

config.json:   0%|          | 0.00/4.72k [00:00<?, ?B/s]

irra videos:  90%|████████▉ | 6575/7306 [25:57<01:22,  8.85batch/s]

tokenizer_config.json:   0%|          | 0.00/965 [00:00<?, ?B/s]

irra videos:  90%|█████████ | 6577/7306 [25:58<01:19,  9.18batch/s]
irra videos:  90%|█████████ | 6579/7306 [25:58<01:16,  9.52batch/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

irra videos:  90%|█████████ | 6580/7306 [25:58<01:17,  9.31batch/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

irra videos:  90%|█████████ | 6582/7306 [25:58<01:15,  9.59batch/s]
irra videos:  90%|█████████ | 6584/7306 [25:58<01:12,  9.98batch/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

irra videos:  90%|█████████ | 6586/7306 [25:59<01:13,  9.74batch/s]

special_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

irra videos:  90%|█████████ | 6588/7306 [25:59<01:30,  7.92batch/s]
irra videos:  90%|█████████ | 6589/7306 [25:59<01:31,  7.86batch/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  786MB

model.safetensors: downloading bytes:           |  0.00B

irra videos:  90%|█████████ | 6591/7306 [25:59<01:25,  8.33batch/s]
irra videos:  90%|█████████ | 6593/7306 [25:59<01:17,  9.17batch/s]
irra videos:  90%|█████████ | 6595/7306 [26:00<01:12,  9.82batch/s]
irra videos:  90%|█████████ | 6597/7306 [26:00<01:27,  8.08batch/s]
irra videos:  90%|█████████ | 6598/7306 [26:00<01:55,  6.15batch/s]
irra videos:  90%|█████████ | 6599/7306 [26:00<02:01,  5.81batch/s]
irra videos:  90%|█████████ | 6600/7306 [26:01<02:04,  5.66batch/s]
irra videos:  90%|█████████ | 6601/7306 [26:01<02:26,  4.82batch/s]
irra videos:  90%|█████████ | 6602/7306 [26:01<02:13,  5.26batch/s]
irra videos:  90%|█████████ | 6603/7306 [26:01<02:01,  5.79batch/s]
irra videos:  90%|█████████ | 6604/7306 [26:01<01:47,  6.51batch/s]
irra videos:  90%|█████████ | 6605/7306 [26:01<01:38,  7.13batch/s]

Loading weights:   0%|          | 0/591 [00:00<?, ?it/s]

irra videos:  90%|█████████ | 6606/7306 [26:02<04:38,  2.51batch/s]
irra videos:  90%|█████████ | 6607/7306 [26:03<03:49,  3.05batch/s]

Model device: cuda:0 dtype=torch.float16 requested=cuda:0 (Tesla T4)
== X-CLIP | activitynet/paragraph | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:   0%|          | 0/250 [00:00<?, ?batch/s].18batch/s]
xclip videos:   0%|          | 1/250 [00:02<11:07,  2.68s/batch]ch]
xclip videos:   1%|          | 3/250 [00:02<02:52,  1.44batch/s]/s]
xclip videos:   2%|▏         | 4/250 [00:03<01:56,  2.11batch/s]/s]
xclip videos:   2%|▏         | 5/250 [00:03<01:25,  2.85batch/s]/s]
xclip videos:   2%|▏         | 6/250 [00:03<01:08,  3.58batch/s]/s]
xclip videos:   3%|▎         | 8/250 [00:03<00:46,  5.16batch/s]/s]
xclip videos:   4%|▎         | 9/250 [00:03<00:43,  5.51batch/s]/s]
xclip videos:   4%|▍         | 11/250 [00:03<00:35,  6.77batch/s]s]
xclip videos:   5%|▍         | 12/250 [00:04<00:33,  7.13batch/s]s]
xclip videos:   6%|▌         | 14/250 [00:04<00:30,  7.73batch/s]s]
xclip videos:   6%|▌         | 15/250 [00:04<00:29,  7.91batch/s]s]
xclip videos:   7%|▋         | 17/250 [00:04<00:27,  8.49batch/s]s]
xclip videos:   7%|▋         | 18/250 [00:04<00:26,  8.77batch/s]s]
xclip videos:   8%|▊         | 19/250 [00:04<00:25,  9.01batch/s]s]
xclip videos:   8%|▊         | 20/250 [00:04<00:25,  9.10batch/s]s]
xclip videos:   9%|▉         | 22/250 [00:05<00:25,  8.87batch/s]s]
xclip videos:   9%|▉         | 23/250 [00:05<00:26,  8.49batch/s]s]
xclip videos:  10%|█         | 25/250 [00:05<00:26,  8.52batch/s]s]
xclip videos:  10%|█         | 26/250 [00:05<00:25,  8.89batch/s]s]
xclip videos:  11%|█         | 27/250 [00:05<00:24,  9.09batch/s]s]
xclip videos:  11%|█         | 28/250 [00:05<00:24,  9.24batch/s]s]
xclip videos:  12%|█▏        | 30/250 [00:06<00:23,  9.24batch/s]s]
xclip videos:  12%|█▏        | 31/250 [00:06<00:23,  9.26batch/s]s]
xclip videos:  13%|█▎        | 32/250 [00:06<00:23,  9.26batch/s]s]
xclip videos:  13%|█▎        | 33/250 [00:06<00:24,  9.02batch/s]s]
xclip videos:  14%|█▍        | 35/250 [00:06<00:23,  9.03batch/s]s]
xclip videos:  14%|█▍        | 36/250 [00:06<00:24,  8.87batch/s]s]
xclip videos:  15%|█▍        | 37/250 [00:06<00:23,  8.92batch/s]s]
xclip videos:  15%|█▌        | 38/250 [00:07<00:23,  8.98batch/s]s]
xclip videos:  16%|█▌        | 39/250 [00:07<00:23,  8.99batch/s]s]
xclip videos:  16%|█▌        | 40/250 [00:07<00:23,  8.99batch/s]s]
xclip videos:  17%|█▋        | 42/250 [00:07<00:24,  8.34batch/s]s]
xclip videos:  17%|█▋        | 43/250 [00:07<00:24,  8.41batch/s]s]
xclip videos:  18%|█▊        | 44/250 [00:07<00:24,  8.47batch/s]s]
xclip videos:  18%|█▊        | 45/250 [00:07<00:23,  8.59batch/s]s]
xclip videos:  19%|█▉        | 47/250 [00:08<00:22,  8.85batch/s]s]
xclip videos:  19%|█▉        | 48/250 [00:08<00:22,  8.86batch/s]s]
xclip videos:  20%|█▉        | 49/250 [00:08<00:22,  8.91batch/s]s]
xclip videos:  20%|██        | 50/250 [00:08<00:22,  8.98batch/s]s]
xclip videos:  20%|██        | 51/250 [00:08<00:22,  8.88batch/s]s]
xclip videos:  21%|██        | 52/250 [00:08<00:22,  8.90batch/s]s]
xclip videos:  22%|██▏       | 54/250 [00:08<00:21,  9.02batch/s]s]
xclip videos:  22%|██▏       | 55/250 [00:08<00:21,  8.96batch/s]s]
xclip videos:  22%|██▏       | 56/250 [00:09<00:21,  9.03batch/s]s]
xclip videos:  23%|██▎       | 57/250 [00:09<00:21,  8.91batch/s]s]
xclip videos:  23%|██▎       | 58/250 [00:09<00:21,  8.96batch/s]s]
xclip videos:  24%|██▎       | 59/250 [00:09<00:21,  8.83batch/s]s]
xclip videos:  24%|██▍       | 60/250 [00:09<00:22,  8.55batch/s]s]
xclip videos:  24%|██▍       | 61/250 [00:09<00:22,  8.29batch/s]s]
xclip videos:  25%|██▌       | 63/250 [00:09<00:21,  8.63batch/s]s]
xclip videos:  26%|██▌       | 64/250 [00:10<00:22,  8.31batch/s]s]
xclip videos:  26%|██▌       | 65/250 [00:10<00:22,  8.32batch/s]s]
xclip videos:  27%|██▋       | 67/250 [00:10<00:22,  8.28batch/s]s]
xclip videos:  27%|██▋       | 68/250 [00:10<00:21,  8.31batch/s]s]
xclip videos:  28%|██▊       | 69/250 [00:10<00:21,  8.33batch/s]s]
xclip videos:  28%|██▊       | 70/250 [00:10<00:21,  8.44batch/s]s]
xclip videos:  28%|██▊       | 71/250 [00:10<00:20,  8.56batch/s]s]
xclip videos:  29%|██▉       | 72/250 [00:10<00:20,  8.73batch/s]s]
xclip videos:  29%|██▉       | 73/250 [00:11<00:20,  8.58batch/s]s]
xclip videos:  30%|███       | 75/250 [00:11<00:20,  8.51batch/s]s]
xclip videos:  30%|███       | 76/250 [00:11<00:20,  8.56batch/s]s]
xclip videos:  31%|███       | 77/250 [00:11<00:20,  8.64batch/s]s]
xclip videos:  31%|███       | 78/250 [00:11<00:20,  8.50batch/s]s]
xclip videos:  32%|███▏      | 79/250 [00:11<00:20,  8.44batch/s]s]
xclip videos:  32%|███▏      | 81/250 [00:11<00:18,  8.91batch/s]s]
xclip videos:  33%|███▎      | 82/250 [00:12<00:18,  8.94batch/s]s]
xclip videos:  33%|███▎      | 83/250 [00:12<00:19,  8.74batch/s]s]
xclip videos:  34%|███▎      | 84/250 [00:12<00:19,  8.71batch/s]s]
xclip videos:  34%|███▍      | 86/250 [00:12<00:19,  8.52batch/s]s]
xclip videos:  35%|███▍      | 87/250 [00:12<00:19,  8.24batch/s]s]
xclip videos:  35%|███▌      | 88/250 [00:12<00:19,  8.26batch/s]s]
xclip videos:  36%|███▌      | 89/250 [00:12<00:19,  8.38batch/s]s]
xclip videos:  36%|███▋      | 91/250 [00:13<00:18,  8.61batch/s]s]
irra videos:  91%|█████████▏| 6682/7306 [26:16<01:27,  7.09batch/s]
xclip videos:  37%|███▋      | 93/250 [00:13<00:17,  9.15batch/s]s]
xclip videos:  38%|███▊      | 95/250 [00:13<00:17,  8.63batch/s]s]
xclip videos:  38%|███▊      | 96/250 [00:13<00:18,  8.17batch/s]s]
xclip videos:  39%|███▉      | 97/250 [00:13<00:18,  8.49batch/s]s]
xclip videos:  40%|███▉      | 99/250 [00:14<00:17,  8.55batch/s]s]
xclip videos:  40%|████      | 100/250 [00:14<00:17,  8.37batch/s]]
xclip videos:  40%|████      | 101/250 [00:14<00:18,  8.22batch/s]]
xclip videos:  41%|████      | 103/250 [00:14<00:18,  8.15batch/s]]
xclip videos:  42%|████▏     | 104/250 [00:14<00:17,  8.46batch/s]]
xclip videos:  42%|████▏     | 106/250 [00:14<00:17,  8.24batch/s]]
xclip videos:  43%|████▎     | 107/250 [00:15<00:17,  8.00batch/s]]
xclip videos:  43%|████▎     | 108/250 [00:15<00:17,  8.14batch/s]]
xclip videos:  44%|████▎     | 109/250 [00:15<00:16,  8.48batch/s]]
xclip videos:  44%|████▍     | 111/250 [00:15<00:16,  8.44batch/s]]
xclip videos:  45%|████▍     | 112/250 [00:15<00:16,  8.54batch/s]]
xclip videos:  45%|████▌     | 113/250 [00:15<00:16,  8.49batch/s]]
xclip videos:  46%|████▌     | 114/250 [00:15<00:15,  8.59batch/s]]
xclip videos:  46%|████▌     | 115/250 [00:16<00:16,  8.37batch/s]]
xclip videos:  46%|████▋     | 116/250 [00:16<00:15,  8.41batch/s]]
xclip videos:  47%|████▋     | 117/250 [00:16<00:15,  8.60batch/s]]
xclip videos:  47%|████▋     | 118/250 [00:16<00:16,  8.03batch/s]]
xclip videos:  48%|████▊     | 119/250 [00:16<00:15,  8.25batch/s]]
xclip videos:  48%|████▊     | 120/250 [00:16<00:15,  8.44batch/s]]
xclip videos:  48%|████▊     | 121/250 [00:16<00:14,  8.60batch/s]]
xclip videos:  49%|████▉     | 123/250 [00:16<00:15,  8.44batch/s]]
xclip videos:  50%|████▉     | 124/250 [00:17<00:14,  8.70batch/s]]
xclip videos:  50%|█████     | 125/250 [00:17<00:14,  8.81batch/s]]
xclip videos:  50%|█████     | 126/250 [00:17<00:13,  8.98batch/s]]
xclip videos:  51%|█████     | 128/250 [00:17<00:13,  8.78batch/s]]
xclip videos:  52%|█████▏    | 129/250 [00:17<00:13,  8.94batch/s]]
xclip videos:  52%|█████▏    | 130/250 [00:17<00:13,  8.70batch/s]]
xclip videos:  53%|█████▎    | 132/250 [00:17<00:13,  9.02batch/s]]
xclip videos:  53%|█████▎    | 133/250 [00:18<00:12,  9.05batch/s]]
xclip videos:  54%|█████▎    | 134/250 [00:18<00:12,  9.16batch/s]]
xclip videos:  54%|█████▍    | 136/250 [00:18<00:12,  9.11batch/s]]
xclip videos:  55%|█████▍    | 137/250 [00:18<00:13,  8.64batch/s]]
xclip videos:  56%|█████▌    | 139/250 [00:18<00:12,  8.66batch/s]]
xclip videos:  56%|█████▌    | 140/250 [00:18<00:12,  8.59batch/s]]
xclip videos:  56%|█████▋    | 141/250 [00:19<00:13,  8.23batch/s]]
xclip videos:  57%|█████▋    | 143/250 [00:19<00:13,  8.12batch/s]]
xclip videos:  58%|█████▊    | 144/250 [00:19<00:12,  8.16batch/s]]
xclip videos:  58%|█████▊    | 146/250 [00:19<00:12,  8.55batch/s]]
xclip videos:  59%|█████▉    | 147/250 [00:19<00:11,  8.77batch/s]]
xclip videos:  59%|█████▉    | 148/250 [00:19<00:11,  8.68batch/s]]
xclip videos:  60%|█████▉    | 149/250 [00:19<00:11,  8.62batch/s]]
xclip videos:  60%|██████    | 151/250 [00:20<00:11,  8.54batch/s]]
xclip videos:  61%|██████    | 152/250 [00:20<00:11,  8.49batch/s]]
xclip videos:  61%|██████    | 153/250 [00:20<00:11,  8.58batch/s]]
xclip videos:  62%|██████▏   | 154/250 [00:20<00:11,  8.60batch/s]]
xclip videos:  62%|██████▏   | 155/250 [00:20<00:10,  8.86batch/s]]
xclip videos:  62%|██████▏   | 156/250 [00:20<00:10,  8.87batch/s]]
xclip videos:  63%|██████▎   | 158/250 [00:20<00:10,  9.00batch/s]]
xclip videos:  64%|██████▎   | 159/250 [00:21<00:10,  9.01batch/s]]
xclip videos:  64%|██████▍   | 160/250 [00:21<00:09,  9.04batch/s]]
xclip videos:  64%|██████▍   | 161/250 [00:21<00:10,  8.69batch/s]]
xclip videos:  65%|██████▍   | 162/250 [00:21<00:10,  8.51batch/s]]
xclip videos:  66%|██████▌   | 164/250 [00:21<00:09,  8.79batch/s]]
xclip videos:  66%|██████▌   | 165/250 [00:21<00:09,  8.69batch/s]]
xclip videos:  66%|██████▋   | 166/250 [00:21<00:09,  8.65batch/s]]
xclip videos:  67%|██████▋   | 168/250 [00:22<00:09,  8.77batch/s]]
xclip videos:  68%|██████▊   | 169/250 [00:22<00:09,  8.53batch/s]]
xclip videos:  68%|██████▊   | 170/250 [00:22<00:09,  8.85batch/s]]
xclip videos:  68%|██████▊   | 171/250 [00:22<00:08,  8.99batch/s]]
xclip videos:  69%|██████▉   | 173/250 [00:22<00:08,  8.99batch/s]]
xclip videos:  70%|██████▉   | 174/250 [00:22<00:08,  8.69batch/s]]
xclip videos:  70%|███████   | 175/250 [00:22<00:08,  8.56batch/s]]
xclip videos:  71%|███████   | 177/250 [00:23<00:08,  8.79batch/s]]
xclip videos:  71%|███████   | 178/250 [00:23<00:08,  8.89batch/s]]
xclip videos:  72%|███████▏  | 179/250 [00:23<00:08,  8.84batch/s]]
xclip videos:  72%|███████▏  | 180/250 [00:23<00:07,  8.79batch/s]]
xclip videos:  73%|███████▎  | 182/250 [00:23<00:08,  8.16batch/s]]
xclip videos:  73%|███████▎  | 183/250 [00:23<00:08,  7.99batch/s]]
xclip videos:  74%|███████▎  | 184/250 [00:24<00:08,  7.98batch/s]]
xclip videos:  74%|███████▍  | 186/250 [00:24<00:07,  8.35batch/s]]
xclip videos:  75%|███████▍  | 187/250 [00:24<00:07,  8.45batch/s]]
xclip videos:  75%|███████▌  | 188/250 [00:24<00:07,  8.67batch/s]]
xclip videos:  76%|███████▌  | 189/250 [00:24<00:06,  8.73batch/s]]
xclip videos:  76%|███████▋  | 191/250 [00:24<00:06,  8.45batch/s]]
xclip videos:  77%|███████▋  | 192/250 [00:24<00:06,  8.34batch/s]]
xclip videos:  78%|███████▊  | 194/250 [00:25<00:06,  8.24batch/s]]
xclip videos:  78%|███████▊  | 195/250 [00:25<00:06,  8.08batch/s]]
xclip videos:  79%|███████▉  | 197/250 [00:25<00:06,  8.10batch/s]]
xclip videos:  79%|███████▉  | 198/250 [00:25<00:06,  8.22batch/s]]
xclip videos:  80%|███████▉  | 199/250 [00:25<00:06,  8.31batch/s]]
xclip videos:  80%|████████  | 200/250 [00:25<00:05,  8.44batch/s]]
xclip videos:  80%|████████  | 201/250 [00:26<00:05,  8.54batch/s]]
xclip videos:  81%|████████  | 202/250 [00:26<00:05,  8.67batch/s]]
xclip videos:  81%|████████  | 203/250 [00:26<00:05,  8.62batch/s]]
xclip videos:  82%|████████▏ | 204/250 [00:26<00:05,  8.39batch/s]]
xclip videos:  82%|████████▏ | 205/250 [00:26<00:05,  8.36batch/s]]
xclip videos:  82%|████████▏ | 206/250 [00:26<00:05,  8.40batch/s]]
xclip videos:  83%|████████▎ | 207/250 [00:26<00:05,  8.19batch/s]]
xclip videos:  84%|████████▎ | 209/250 [00:26<00:04,  8.32batch/s]]
xclip videos:  84%|████████▍ | 210/250 [00:27<00:04,  8.30batch/s]]
xclip videos:  84%|████████▍ | 211/250 [00:27<00:04,  8.28batch/s]]
xclip videos:  85%|████████▌ | 213/250 [00:27<00:04,  8.14batch/s]]
xclip videos:  86%|████████▌ | 214/250 [00:27<00:04,  8.27batch/s]]
xclip videos:  86%|████████▌ | 215/250 [00:27<00:04,  8.34batch/s]]
xclip videos:  86%|████████▋ | 216/250 [00:27<00:03,  8.57batch/s]]
xclip videos:  87%|████████▋ | 218/250 [00:28<00:03,  8.90batch/s]]
xclip videos:  88%|████████▊ | 219/250 [00:28<00:03,  8.80batch/s]]
xclip videos:  88%|████████▊ | 220/250 [00:28<00:03,  8.83batch/s]]
xclip videos:  88%|████████▊ | 221/250 [00:28<00:03,  8.75batch/s]]
xclip videos:  89%|████████▉ | 222/250 [00:28<00:03,  8.54batch/s]]
xclip videos:  89%|████████▉ | 223/250 [00:28<00:03,  8.63batch/s]]
xclip videos:  90%|████████▉ | 224/250 [00:28<00:02,  8.77batch/s]]
xclip videos:  90%|█████████ | 226/250 [00:28<00:02,  8.54batch/s]]
xclip videos:  91%|█████████ | 227/250 [00:29<00:02,  8.64batch/s]]
xclip videos:  91%|█████████ | 228/250 [00:29<00:02,  8.92batch/s]]
xclip videos:  92%|█████████▏| 229/250 [00:29<00:02,  8.93batch/s]]
xclip videos:  92%|█████████▏| 231/250 [00:29<00:02,  8.86batch/s]]
xclip videos:  93%|█████████▎| 232/250 [00:29<00:02,  8.64batch/s]]
xclip videos:  93%|█████████▎| 233/250 [00:29<00:01,  8.54batch/s]]
xclip videos:  94%|█████████▎| 234/250 [00:29<00:01,  8.78batch/s]]
xclip videos:  94%|█████████▍| 236/250 [00:30<00:01,  8.53batch/s]]
xclip videos:  95%|█████████▍| 237/250 [00:30<00:01,  8.26batch/s]]
xclip videos:  95%|█████████▌| 238/250 [00:30<00:01,  8.37batch/s]]
xclip videos:  96%|█████████▌| 240/250 [00:30<00:01,  8.76batch/s]]
xclip videos:  96%|█████████▋| 241/250 [00:30<00:01,  8.96batch/s]]
irra videos:  93%|█████████▎| 6802/7306 [26:34<01:15,  6.72batch/s]
xclip videos:  98%|█████████▊| 244/250 [00:31<00:00,  9.08batch/s]]
xclip videos:  98%|█████████▊| 245/250 [00:31<00:00,  8.87batch/s]]
xclip videos:  98%|█████████▊| 246/250 [00:31<00:00,  8.87batch/s]]
xclip videos:  99%|█████████▉| 247/250 [00:31<00:00,  8.76batch/s]]
xclip videos:  99%|█████████▉| 248/250 [00:31<00:00,  8.88batch/s]]
xclip videos: 100%|█████████▉| 249/250 [00:31<00:00,  8.96batch/s]]
xclip videos: 100%|██████████| 250/250 [00:31<00:00,  7.89batch/s]]
xclip texts:   0%|          | 0/63 [00:00<?, ?batch/s]
xclip texts:   2%|▏         | 1/63 [00:00<00:11,  5.62batch/s]ch/s]
xclip texts:   8%|▊         | 5/63 [00:00<00:02, 20.06batch/s]ch/s]
xclip texts:  22%|██▏       | 14/63 [00:00<00:01, 30.86batch/s]h/s]
xclip texts:  30%|███       | 19/63 [00:00<00:01, 34.55batch/s]h/s]
xclip texts:  37%|███▋      | 23/63 [00:00<00:01, 34.89batch/s]h/s]
xclip texts:  43%|████▎     | 27/63 [00:00<00:01, 35.72batch/s]h/s]
xclip texts:  51%|█████     | 32/63 [00:00<00:00, 38.18batch/s]h/s]
xclip texts:  59%|█████▊    | 37/63 [00:01<00:00, 39.18batch/s]h/s]
xclip texts:  73%|███████▎  | 46/63 [00:01<00:00, 41.32batch/s]h/s]
xclip texts:  81%|████████  | 51/63 [00:01<00:00, 42.70batch/s]h/s]
xclip texts:  89%|████████▉ | 56/63 [00:01<00:00, 44.11batch/s]h/s]
xclip texts: 100%|██████████| 63/63 [00:01<00:00, 36.48batch/s]h/s]

irra videos:  93%|█████████▎| 6822/7306 [26:37<01:11,  6.73batch/s]
irra videos:  93%|█████████▎| 6823/7306 [26:37<02:16,  3.54batch/s]

-- none: R1 21.20  mAP 33.98  mINP 33.98
== X-CLIP | activitynet/sentence | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip texts:   0%|          | 0/227 [00:00<?, ?batch/s]3.32batch/s]
xclip texts:   2%|▏         | 4/227 [00:00<00:05, 38.51batch/s]h/s]
xclip texts:   4%|▎         | 8/227 [00:00<00:05, 39.29batch/s]h/s]
xclip texts:   6%|▌         | 14/227 [00:00<00:04, 47.32batch/s]/s]
xclip texts:  11%|█▏        | 26/227 [00:00<00:03, 53.62batch/s]/s]
xclip texts:  14%|█▍        | 32/227 [00:00<00:03, 51.88batch/s]/s]
xclip texts:  17%|█▋        | 38/227 [00:00<00:03, 52.47batch/s]/s]
xclip texts:  19%|█▉        | 44/227 [00:00<00:03, 47.70batch/s]/s]
xclip texts:  22%|██▏       | 49/227 [00:01<00:03, 46.54batch/s]/s]
xclip texts:  24%|██▍       | 54/227 [00:01<00:03, 46.80batch/s]/s]
xclip texts:  26%|██▋       | 60/227 [00:01<00:03, 48.45batch/s]/s]
xclip texts:  29%|██▉       | 66/227 [00:01<00:03, 49.19batch/s]/s]
xclip texts:  31%|███▏      | 71/227 [00:01<00:03, 45.67batch/s]/s]
xclip texts:  36%|███▌      | 82/227 [00:01<00:03, 45.65batch/s]/s]
irra videos:  94%|█████████▎| 6838/7306 [26:39<01:03,  7.33batch/s]
xclip texts:  38%|███▊      | 87/227 [00:01<00:03, 39.43batch/s]/s]
xclip texts:  41%|████      | 93/227 [00:02<00:03, 43.04batch/s]/s]
xclip texts:  43%|████▎     | 98/227 [00:02<00:02, 43.48batch/s]/s]
xclip texts:  48%|████▊     | 108/227 [00:02<00:02, 43.31batch/s]s]
xclip texts:  50%|█████     | 114/227 [00:02<00:02, 47.05batch/s]s]
xclip texts:  53%|█████▎    | 120/227 [00:02<00:02, 48.86batch/s]s]
xclip texts:  55%|█████▌    | 125/227 [00:02<00:02, 47.99batch/s]s]
xclip texts:  58%|█████▊    | 131/227 [00:02<00:01, 49.66batch/s]s]
xclip texts:  60%|█████▉    | 136/227 [00:02<00:01, 48.33batch/s]s]
xclip texts:  65%|██████▍   | 147/227 [00:03<00:01, 45.66batch/s]s]
xclip texts:  67%|██████▋   | 152/227 [00:03<00:01, 46.80batch/s]s]
xclip texts:  70%|██████▉   | 158/227 [00:03<00:01, 49.05batch/s]s]
irra videos:  94%|█████████▍| 6851/7306 [26:41<01:00,  7.57batch/s]

In [10]:
# Run this cell directly after Step 4 setup/helpers are loaded; skip the main run cell.
# Recompute IRRA and X-CLIP even if their previous result rows say complete.
retry_models = ("irra", "xclip")
def retry_run_one(encoder, model, dataset, subset, spec, gpu_index):
    splits = load_split(subset)
    cache = DATA_ROOT / "frame_cache" / f"gpu{gpu_index}" / dataset
    batch = MODEL_BATCH.get(model, BATCH)
    text_batch = MODEL_TEXT_BATCH.get(model, TEXT_BATCH)
    print(f"== {PRETTY.get(model, model)} | {dataset}/{subset} | {spec['name']}", flush=True)
    try:
        if spec["type"] == "single":
            scored = {
                "none": evaluate_text_to_tracklet(
                    encoder, splits, num_frames=spec["num_frames"], batch_size=batch,
                    text_batch_size=text_batch, junk_same_camera=False,
                    frame_cache=cache, frame_sample=spec["frame_sample"],
                )
            }
        else:
            scored = evaluate_text_to_tracklet_windows(
                encoder, splits, num_frames=NATIVE_FRAMES.get(model, 8),
                stride=spec["stride"], sample_fps=spec["sample_fps"],
                max_frames=spec["max_frames"], pools=POOLS,
                batch_size=batch, text_batch_size=text_batch,
                junk_same_camera=False, frame_cache=cache,
            )
    except RuntimeError as exc:
        pools = ["none"] if spec["type"] == "single" else list(POOLS)
        for pool in pools:
            save_row(dataset, model, subset, spec, pool, error=exc)
        if "out of memory" in str(exc).lower():
            raise StopModel(str(exc)) from exc
        raise
    for pool, metrics in scored.items():
        save_row(dataset, model, subset, spec, pool, metrics=metrics, cached=encoder.last_hit)
        print(f"-- {pool}: R1 {metrics['Rank-1']:.2f}  mAP {metrics['mAP']:.2f}", flush=True)


def retry_gpu_worker(gpu_index, model):
    torch.cuda.set_device(gpu_index)
    device = f"cuda:{gpu_index}"
    ensure_cuda_healthy(device)
    jobs = [
        (dataset, spec, subset)
        for dataset in ("activitynet",)
        for spec in protocols_for(model)
        for subset in DATASETS["activitynet"]["subsets"]
    ]
    print(f"\n######## GPU {gpu_index} | {PRETTY.get(model, model)}: forcing all {len(jobs)} runs", flush=True)
    try:
        encoder = GalleryCache(build_encoder(model, device=device))
    except Exception:
        traceback.print_exc()
        print(f"Could not build {model} on GPU {gpu_index}; skipping it", flush=True)
        clean_cuda()
        return
    try:
        for dataset, spec, subset in jobs:
            retry_run_one(encoder, model, dataset, subset, spec, gpu_index)
    except StopModel as exc:
        print(f"CUDA OOM on {model} (GPU {gpu_index}); stopping this model: {exc}", flush=True)
    finally:
        del encoder
        clean_cuda()

if not torch.cuda.is_available():
    raise RuntimeError("A CUDA GPU is required for this benchmark")
if ON_KAGGLE and torch.cuda.device_count() < 2:
    raise RuntimeError("Select Kaggle GPU T4 x2; this notebook needs two visible GPUs")
retry_gpu_count = min(2, torch.cuda.device_count())
print("Retrying IRRA on GPU 0 and X-CLIP on GPU 1 in parallel", flush=True)
with ThreadPoolExecutor(max_workers=2) as workers:
    retry_futures = [
        workers.submit(retry_gpu_worker, gpu_index, model)
        for gpu_index, model in enumerate(retry_models)
    ]
    for future in retry_futures:
        future.result()
print("IRRA and X-CLIP retry done", flush=True)

Retrying IRRA on GPU 0 and X-CLIP on GPU 1 in parallel

######## GPU 0 | IRRA: forcing all 8 runs

######## GPU 1 | X-CLIP: forcing all 8 runs

Loading weights:   0%|          | 0/591 [00:00<?, ?it/s]

Model device: cuda:1 dtype=torch.float16 requested=cuda:1 (Tesla T4)
== X-CLIP | activitynet/paragraph | uniform8

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:   6%|▌         | 14/250 [00:01<00:31,  7.51batch/s]

Model device: cuda:0 dtype=torch.float16 requested=cuda:0 (Tesla T4)
== IRRA | activitynet/paragraph | uniform8

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:   6%|▌         | 15/250 [00:01<00:38,  6.18batch/s]
xclip videos:   7%|▋         | 17/250 [00:02<00:37,  6.14batch/s]
xclip videos:   7%|▋         | 18/250 [00:02<00:35,  6.57batch/s]A
xclip videos:   8%|▊         | 19/250 [00:02<00:33,  6.99batch/s]A
irra videos:   1%|          | 3/500 [00:00<01:06,  7.50batch/s]
xclip videos:   8%|▊         | 20/250 [00:02<00:35,  6.47batch/s]A
xclip videos:   9%|▉         | 22/250 [00:02<00:33,  6.89batch/s]A
xclip videos:   9%|▉         | 23/250 [00:03<00:32,  7.09batch/s]A
xclip videos:  10%|▉         | 24/250 [00:03<00:31,  7.18batch/s]A
xclip videos:  10%|█         | 25/250 [00:03<00:31,  7.17batch/s]A
xclip videos:  11%|█         | 27/250 [00:03<00:29,  7.69batch/s]A
xclip videos:  11%|█         | 28/250 [00:03<00:28,  7.77batch/s][A
xclip videos:  12%|█▏        | 29/250 [00:03<00:29,  7.42batch/s][A
xclip videos:  12%|█▏        | 30/250 [00:04<00:28,  7.71batch/s][A
xclip videos:  12%|█▏        | 31/250 [00:04<00:27,  7.89batch/s][A
xclip videos:  13%|█▎        | 32/250 [00:04<00:27,  7.88batch/s][A
xclip videos:  13%|█▎        | 33/250 [00:04<00:27,  7.91batch/s][A
xclip videos:  14%|█▎        | 34/250 [00:04<00:27,  7.84batch/s][A
xclip videos:  14%|█▍        | 35/250 [00:04<00:27,  7.78batch/s][A
xclip videos:  14%|█▍        | 36/250 [00:04<00:27,  7.80batch/s][A
xclip videos:  15%|█▍        | 37/250 [00:04<00:27,  7.86batch/s][A
xclip videos:  15%|█▌        | 38/250 [00:05<00:26,  7.99batch/s][A
xclip videos:  16%|█▌        | 39/250 [00:05<00:27,  7.59batch/s][A
xclip videos:  16%|█▌        | 40/250 [00:05<00:27,  7.70batch/s][A
xclip videos:  16%|█▋        | 41/250 [00:05<00:26,  7.90batch/s][A
xclip videos:  17%|█▋        | 42/250 [00:05<00:30,  6.87batch/s][A
xclip videos:  17%|█▋        | 43/250 [00:05<00:29,  6.94batch/s][A
xclip videos:  18%|█▊        | 44/250 [00:05<00:29,  7.04batch/s][A
xclip videos:  18%|█▊        | 45/250 [00:06<00:28,  7.16batch/s][A
xclip videos:  18%|█▊        | 46/250 [00:06<00:27,  7.47batch/s][A
xclip videos:  19%|█▉        | 47/250 [00:06<00:26,  7.69batch/s][A
xclip videos:  20%|█▉        | 49/250 [00:06<00:24,  8.06batch/s][A
xclip videos:  20%|██        | 50/250 [00:06<00:24,  8.01batch/s][A
xclip videos:  20%|██        | 51/250 [00:06<00:25,  7.89batch/s][A
xclip videos:  21%|██        | 52/250 [00:06<00:24,  7.92batch/s][A
xclip videos:  21%|██        | 53/250 [00:07<00:24,  8.02batch/s][A
xclip videos:  22%|██▏       | 54/250 [00:07<00:24,  8.15batch/s][A
xclip videos:  22%|██▏       | 55/250 [00:07<00:23,  8.15batch/s][A
xclip videos:  22%|██▏       | 56/250 [00:07<00:23,  8.34batch/s][A
xclip videos:  23%|██▎       | 57/250 [00:07<00:23,  8.37batch/s][A
xclip videos:  23%|██▎       | 58/250 [00:07<00:23,  8.27batch/s][A
xclip videos:  24%|██▎       | 59/250 [00:07<00:22,  8.32batch/s][A
xclip videos:  24%|██▍       | 60/250 [00:07<00:23,  8.11batch/s][A
xclip videos:  24%|██▍       | 61/250 [00:07<00:23,  8.17batch/s][A
xclip videos:  25%|██▍       | 62/250 [00:08<00:22,  8.23batch/s][A
xclip videos:  25%|██▌       | 63/250 [00:08<00:23,  7.85batch/s][A
xclip videos:  26%|██▌       | 65/250 [00:08<00:22,  8.12batch/s][A
xclip videos:  26%|██▋       | 66/250 [00:08<00:22,  8.13batch/s][A
xclip videos:  27%|██▋       | 67/250 [00:08<00:22,  8.20batch/s][A
xclip videos:  27%|██▋       | 68/250 [00:08<00:22,  8.27batch/s][A
xclip videos:  28%|██▊       | 69/250 [00:08<00:21,  8.24batch/s][A
xclip videos:  28%|██▊       | 70/250 [00:09<00:21,  8.33batch/s][A
xclip videos:  28%|██▊       | 71/250 [00:09<00:21,  8.48batch/s][A
xclip videos:  29%|██▉       | 72/250 [00:09<00:20,  8.52batch/s][A
xclip videos:  30%|██▉       | 74/250 [00:09<00:20,  8.64batch/s][A
xclip videos:  30%|███       | 75/250 [00:09<00:20,  8.59batch/s][A
xclip videos:  30%|███       | 76/250 [00:09<00:20,  8.49batch/s][A
xclip videos:  31%|███       | 77/250 [00:09<00:20,  8.39batch/s][A
xclip videos:  31%|███       | 78/250 [00:10<00:20,  8.42batch/s][A
xclip videos:  32%|███▏      | 79/250 [00:10<00:20,  8.20batch/s][A
xclip videos:  32%|███▏      | 80/250 [00:10<00:20,  8.20batch/s][A
xclip videos:  32%|███▏      | 81/250 [00:10<00:20,  8.33batch/s][A
xclip videos:  33%|███▎      | 82/250 [00:10<00:19,  8.41batch/s][A
xclip videos:  34%|███▎      | 84/250 [00:10<00:19,  8.38batch/s][A
xclip videos:  34%|███▍      | 85/250 [00:10<00:20,  8.17batch/s][A
xclip videos:  34%|███▍      | 86/250 [00:11<00:20,  8.09batch/s][A
xclip videos:  35%|███▍      | 87/250 [00:11<00:20,  7.89batch/s][A
xclip videos:  36%|███▌      | 89/250 [00:11<00:19,  8.17batch/s][A
xclip videos:  36%|███▌      | 90/250 [00:11<00:19,  8.11batch/s][A
xclip videos:  36%|███▋      | 91/250 [00:11<00:19,  8.21batch/s][A
xclip videos:  37%|███▋      | 93/250 [00:11<00:19,  8.19batch/s][A
xclip videos:  38%|███▊      | 94/250 [00:11<00:18,  8.24batch/s][A
xclip videos:  38%|███▊      | 95/250 [00:12<00:18,  8.32batch/s][A
xclip videos:  38%|███▊      | 96/250 [00:12<00:18,  8.19batch/s][A
xclip videos:  39%|███▉      | 97/250 [00:12<00:18,  8.20batch/s][A
xclip videos:  39%|███▉      | 98/250 [00:12<00:18,  8.23batch/s][A
xclip videos:  40%|███▉      | 99/250 [00:12<00:18,  8.26batch/s][A
xclip videos:  40%|████      | 101/250 [00:12<00:18,  7.98batch/s]A
xclip videos:  41%|████      | 102/250 [00:12<00:18,  7.93batch/s]A
xclip videos:  41%|████      | 103/250 [00:13<00:18,  7.88batch/s]A
xclip videos:  42%|████▏     | 105/250 [00:13<00:18,  7.97batch/s]A
xclip videos:  42%|████▏     | 106/250 [00:13<00:17,  8.03batch/s]A
xclip videos:  43%|████▎     | 107/250 [00:13<00:17,  8.10batch/s]A
xclip videos:  43%|████▎     | 108/250 [00:13<00:16,  8.45batch/s]A
xclip videos:  44%|████▎     | 109/250 [00:13<00:16,  8.45batch/s]A
xclip videos:  44%|████▍     | 111/250 [00:14<00:17,  8.06batch/s]A
xclip videos:  45%|████▍     | 112/250 [00:14<00:16,  8.28batch/s]A
xclip videos:  45%|████▌     | 113/250 [00:14<00:16,  8.46batch/s]A
xclip videos:  46%|████▌     | 114/250 [00:14<00:15,  8.72batch/s]A
xclip videos:  46%|████▋     | 116/250 [00:14<00:15,  8.85batch/s]A
xclip videos:  47%|████▋     | 117/250 [00:14<00:15,  8.87batch/s]A
xclip videos:  47%|████▋     | 118/250 [00:14<00:15,  8.71batch/s]A
xclip videos:  48%|████▊     | 119/250 [00:14<00:15,  8.53batch/s]A
xclip videos:  48%|████▊     | 121/250 [00:15<00:15,  8.21batch/s]A
xclip videos:  49%|████▉     | 122/250 [00:15<00:15,  8.15batch/s]A
xclip videos:  49%|████▉     | 123/250 [00:15<00:16,  7.67batch/s]A
xclip videos:  50%|████▉     | 124/250 [00:15<00:16,  7.43batch/s]A
xclip videos:  50%|█████     | 125/250 [00:15<00:16,  7.79batch/s]A
xclip videos:  51%|█████     | 127/250 [00:16<00:15,  7.97batch/s]A
xclip videos:  51%|█████     | 128/250 [00:16<00:15,  8.08batch/s]A
xclip videos:  52%|█████▏    | 129/250 [00:16<00:14,  8.33batch/s]A
xclip videos:  52%|█████▏    | 130/250 [00:16<00:14,  8.40batch/s][A
xclip videos:  53%|█████▎    | 132/250 [00:16<00:14,  8.36batch/s][A
xclip videos:  53%|█████▎    | 133/250 [00:16<00:14,  8.08batch/s][A
xclip videos:  54%|█████▎    | 134/250 [00:16<00:14,  8.25batch/s][A
xclip videos:  54%|█████▍    | 135/250 [00:16<00:14,  8.15batch/s][A
xclip videos:  55%|█████▍    | 137/250 [00:17<00:14,  7.86batch/s][A
xclip videos:  55%|█████▌    | 138/250 [00:17<00:14,  7.77batch/s][A
xclip videos:  56%|█████▌    | 140/250 [00:17<00:14,  7.82batch/s][A
xclip videos:  56%|█████▋    | 141/250 [00:17<00:13,  7.91batch/s][A
xclip videos:  57%|█████▋    | 142/250 [00:17<00:13,  8.12batch/s][A
xclip videos:  57%|█████▋    | 143/250 [00:17<00:13,  8.16batch/s][A
xclip videos:  58%|█████▊    | 144/250 [00:18<00:12,  8.35batch/s][A
xclip videos:  58%|█████▊    | 145/250 [00:18<00:12,  8.53batch/s][A
xclip videos:  58%|█████▊    | 146/250 [00:18<00:11,  8.67batch/s][A
xclip videos:  59%|█████▉    | 148/250 [00:18<00:11,  8.61batch/s][A
xclip videos:  60%|█████▉    | 149/250 [00:18<00:11,  8.53batch/s][A
xclip videos:  60%|██████    | 150/250 [00:18<00:11,  8.49batch/s][A
xclip videos:  60%|██████    | 151/250 [00:18<00:11,  8.42batch/s][A
xclip videos:  61%|██████    | 152/250 [00:19<00:11,  8.41batch/s][A
xclip videos:  61%|██████    | 153/250 [00:19<00:11,  8.13batch/s][A
xclip videos:  62%|██████▏   | 154/250 [00:19<00:11,  8.06batch/s][A
xclip videos:  62%|██████▏   | 156/250 [00:19<00:11,  7.98batch/s][A
xclip videos:  63%|██████▎   | 157/250 [00:19<00:11,  7.89batch/s][A
xclip videos:  63%|██████▎   | 158/250 [00:19<00:11,  7.77batch/s][A
xclip videos:  64%|██████▍   | 160/250 [00:20<00:11,  7.95batch/s][A
xclip videos:  64%|██████▍   | 161/250 [00:20<00:11,  7.86batch/s][A
xclip videos:  65%|██████▍   | 162/250 [00:20<00:10,  8.10batch/s][A
xclip videos:  65%|██████▌   | 163/250 [00:20<00:10,  8.27batch/s][A
xclip videos:  66%|██████▌   | 164/250 [00:20<00:10,  8.31batch/s][A
xclip videos:  66%|██████▋   | 166/250 [00:20<00:09,  8.54batch/s][A
xclip videos:  67%|██████▋   | 167/250 [00:20<00:09,  8.63batch/s][A
xclip videos:  67%|██████▋   | 168/250 [00:21<00:09,  8.45batch/s][A
xclip videos:  68%|██████▊   | 170/250 [00:21<00:09,  8.24batch/s][A
xclip videos:  68%|██████▊   | 171/250 [00:21<00:09,  8.17batch/s][A
xclip videos:  69%|██████▉   | 173/250 [00:21<00:09,  8.30batch/s][A
xclip videos:  70%|██████▉   | 174/250 [00:21<00:08,  8.52batch/s][A
xclip videos:  70%|███████   | 175/250 [00:21<00:08,  8.58batch/s][A
xclip videos:  70%|███████   | 176/250 [00:21<00:08,  8.47batch/s][A
xclip videos:  71%|███████   | 177/250 [00:22<00:08,  8.56batch/s][A
xclip videos:  72%|███████▏  | 179/250 [00:22<00:08,  8.26batch/s][A
xclip videos:  72%|███████▏  | 180/250 [00:22<00:08,  8.16batch/s][A
xclip videos:  72%|███████▏  | 181/250 [00:22<00:08,  7.97batch/s][A
xclip videos:  73%|███████▎  | 183/250 [00:22<00:07,  8.41batch/s][A
xclip videos:  74%|███████▎  | 184/250 [00:22<00:08,  8.20batch/s][A
xclip videos:  74%|███████▍  | 185/250 [00:23<00:07,  8.16batch/s][A
xclip videos:  75%|███████▍  | 187/250 [00:23<00:07,  8.46batch/s][A
xclip videos:  75%|███████▌  | 188/250 [00:23<00:07,  8.54batch/s][A
xclip videos:  76%|███████▌  | 189/250 [00:23<00:06,  8.75batch/s][A
xclip videos:  76%|███████▌  | 190/250 [00:23<00:06,  8.79batch/s][A
xclip videos:  76%|███████▋  | 191/250 [00:23<00:06,  8.74batch/s][A
xclip videos:  77%|███████▋  | 192/250 [00:23<00:06,  8.73batch/s][A
xclip videos:  78%|███████▊  | 194/250 [00:24<00:06,  8.70batch/s][A
xclip videos:  78%|███████▊  | 195/250 [00:24<00:06,  8.65batch/s][A
xclip videos:  78%|███████▊  | 196/250 [00:24<00:06,  8.44batch/s][A
xclip videos:  79%|███████▉  | 197/250 [00:24<00:06,  8.23batch/s][A
xclip videos:  79%|███████▉  | 198/250 [00:24<00:06,  8.45batch/s][A
xclip videos:  80%|███████▉  | 199/250 [00:24<00:06,  8.43batch/s][A
xclip videos:  80%|████████  | 201/250 [00:24<00:05,  8.45batch/s][A
xclip videos:  81%|████████  | 202/250 [00:25<00:05,  8.21batch/s][A
xclip videos:  81%|████████  | 203/250 [00:25<00:05,  8.04batch/s][A
xclip videos:  82%|████████▏ | 204/250 [00:25<00:05,  7.88batch/s][A
xclip videos:  82%|████████▏ | 206/250 [00:25<00:05,  7.43batch/s][A
xclip videos:  83%|████████▎ | 207/250 [00:25<00:05,  7.68batch/s][A
xclip videos:  83%|████████▎ | 208/250 [00:25<00:05,  8.10batch/s][A
xclip videos:  84%|████████▎ | 209/250 [00:25<00:04,  8.36batch/s][A
xclip videos:  84%|████████▍ | 210/250 [00:26<00:04,  8.28batch/s][A
xclip videos:  84%|████████▍ | 211/250 [00:26<00:04,  8.34batch/s][A
xclip videos:  85%|████████▍ | 212/250 [00:26<00:04,  8.47batch/s][A
xclip videos:  85%|████████▌ | 213/250 [00:26<00:04,  8.52batch/s][A
xclip videos:  86%|████████▌ | 215/250 [00:26<00:04,  8.66batch/s][A
xclip videos:  86%|████████▋ | 216/250 [00:26<00:03,  8.61batch/s][A
xclip videos:  87%|████████▋ | 217/250 [00:26<00:03,  8.60batch/s][A
xclip videos:  87%|████████▋ | 218/250 [00:26<00:03,  8.55batch/s][A
xclip videos:  88%|████████▊ | 219/250 [00:27<00:03,  8.58batch/s][A
xclip videos:  88%|████████▊ | 221/250 [00:27<00:03,  8.27batch/s][A
xclip videos:  89%|████████▉ | 222/250 [00:27<00:03,  8.30batch/s][A
xclip videos:  89%|████████▉ | 223/250 [00:27<00:03,  8.51batch/s][A
xclip videos:  90%|████████▉ | 224/250 [00:27<00:02,  8.69batch/s][A
xclip videos:  90%|█████████ | 225/250 [00:27<00:02,  8.77batch/s][A
xclip videos:  90%|█████████ | 226/250 [00:27<00:02,  8.70batch/s][A
xclip videos:  91%|█████████ | 227/250 [00:28<00:02,  8.67batch/s][A
xclip videos:  91%|█████████ | 228/250 [00:28<00:02,  8.70batch/s][A
xclip videos:  92%|█████████▏| 229/250 [00:28<00:02,  8.61batch/s][A
xclip videos:  92%|█████████▏| 231/250 [00:28<00:02,  8.62batch/s][A
xclip videos:  93%|█████████▎| 232/250 [00:28<00:02,  8.61batch/s][A
xclip videos:  93%|█████████▎| 233/250 [00:28<00:01,  8.55batch/s][A
xclip videos:  94%|█████████▎| 234/250 [00:28<00:01,  8.62batch/s][A
xclip videos:  94%|█████████▍| 235/250 [00:28<00:01,  8.66batch/s][A
xclip videos:  94%|█████████▍| 236/250 [00:29<00:01,  8.83batch/s][A
xclip videos:  95%|█████████▌| 238/250 [00:29<00:01,  8.84batch/s][A
xclip videos:  96%|█████████▌| 239/250 [00:29<00:01,  8.72batch/s][A
xclip videos:  96%|█████████▌| 240/250 [00:29<00:01,  8.55batch/s][A
xclip videos:  96%|█████████▋| 241/250 [00:29<00:01,  8.59batch/s][A
xclip videos:  97%|█████████▋| 242/250 [00:29<00:00,  8.68batch/s][A
xclip videos:  97%|█████████▋| 243/250 [00:29<00:00,  8.53batch/s][A
xclip videos:  98%|█████████▊| 244/250 [00:30<00:00,  8.32batch/s][A
xclip videos:  98%|█████████▊| 245/250 [00:30<00:00,  8.20batch/s][A
xclip videos:  98%|█████████▊| 246/250 [00:30<00:00,  8.34batch/s][A
xclip videos:  99%|█████████▉| 247/250 [00:30<00:00,  8.24batch/s][A
xclip videos:  99%|█████████▉| 248/250 [00:30<00:00,  8.25batch/s][A
xclip videos: 100%|█████████▉| 249/250 [00:30<00:00,  8.39batch/s][A
xclip videos: 100%|██████████| 250/250 [00:30<00:00,  8.13batch/s][A
xclip texts:   0%|          | 0/63 [00:00<?, ?batch/s]
xclip texts:   8%|▊         | 5/63 [00:00<00:01, 41.89batch/s]/s]
xclip texts:  24%|██▍       | 15/63 [00:00<00:01, 42.70batch/s]s]
xclip texts:  32%|███▏      | 20/63 [00:00<00:01, 42.44batch/s]s]
xclip texts:  40%|███▉      | 25/63 [00:00<00:00, 44.49batch/s]s]
xclip texts:  48%|████▊     | 30/63 [00:00<00:00, 45.90batch/s]s]
xclip texts:  56%|█████▌    | 35/63 [00:00<00:00, 46.15batch/s]s]
xclip texts:  63%|██████▎   | 40/63 [00:00<00:00, 46.38batch/s]s]
xclip texts:  71%|███████▏  | 45/63 [00:01<00:00, 44.22batch/s]s]
xclip texts:  79%|███████▉  | 50/63 [00:01<00:00, 44.09batch/s]s]
xclip texts:  95%|█████████▌| 60/63 [00:01<00:00, 45.46batch/s]s]
xclip texts: 100%|██████████| 63/63 [00:01<00:00, 43.90batch/s]s]

irra videos:  43%|████▎     | 213/500 [00:30<00:48,  5.90batch/s]
irra videos:  43%|████▎     | 214/500 [00:30<01:12,  3.95batch/s]

-- none: R1 21.20  mAP 33.98
== X-CLIP | activitynet/sentence | uniform8

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip texts:   0%|          | 0/227 [00:00<?, ?batch/s]45batch/s]
xclip texts:   2%|▏         | 5/227 [00:00<00:04, 49.30batch/s]s]
xclip texts:   4%|▍         | 10/227 [00:00<00:04, 48.77batch/s]]
xclip texts:   7%|▋         | 15/227 [00:00<00:04, 49.19batch/s]]
xclip texts:  11%|█         | 25/227 [00:00<00:04, 46.70batch/s]]
xclip texts:  14%|█▎        | 31/227 [00:00<00:04, 48.62batch/s]]
xclip texts:  16%|█▋        | 37/227 [00:00<00:03, 49.65batch/s]]
xclip texts:  19%|█▉        | 43/227 [00:00<00:03, 50.75batch/s]]
xclip texts:  22%|██▏       | 49/227 [00:00<00:03, 49.26batch/s]]
xclip texts:  24%|██▍       | 55/227 [00:01<00:03, 50.32batch/s]]
xclip texts:  27%|██▋       | 61/227 [00:01<00:03, 46.31batch/s]]
xclip texts:  30%|██▉       | 67/227 [00:01<00:03, 48.68batch/s]]
xclip texts:  34%|███▍      | 77/227 [00:01<00:03, 46.32batch/s]]
xclip texts:  36%|███▌      | 82/227 [00:01<00:03, 46.63batch/s]]
xclip texts:  38%|███▊      | 87/227 [00:01<00:03, 44.80batch/s]]
xclip texts:  41%|████      | 92/227 [00:01<00:02, 45.44batch/s]]
xclip texts:  43%|████▎     | 98/227 [00:02<00:02, 45.28batch/s]]
xclip texts:  45%|████▌     | 103/227 [00:02<00:02, 42.77batch/s]
xclip texts:  50%|█████     | 114/227 [00:02<00:02, 46.34batch/s]
xclip texts:  52%|█████▏    | 119/227 [00:02<00:02, 46.50batch/s]
xclip texts:  55%|█████▍    | 124/227 [00:02<00:02, 47.22batch/s]
xclip texts:  57%|█████▋    | 129/227 [00:02<00:02, 46.38batch/s]
xclip texts:  59%|█████▉    | 134/227 [00:02<00:01, 46.72batch/s]
xclip texts:  62%|██████▏   | 140/227 [00:02<00:01, 48.14batch/s]
xclip texts:  64%|██████▍   | 146/227 [00:03<00:01, 49.01batch/s]
xclip texts:  69%|██████▉   | 157/227 [00:03<00:01, 51.54batch/s]
xclip texts:  72%|███████▏  | 163/227 [00:03<00:01, 50.86batch/s]
xclip texts:  74%|███████▍  | 169/227 [00:03<00:01, 47.07batch/s]
xclip texts:  77%|███████▋  | 174/227 [00:03<00:01, 46.84batch/s]
xclip texts:  79%|███████▉  | 179/227 [00:03<00:01, 46.38batch/s]
xclip texts:  81%|████████  | 184/227 [00:03<00:00, 45.13batch/s]
xclip texts:  83%|████████▎ | 189/227 [00:04<00:00, 43.39batch/s]
xclip texts:  88%|████████▊ | 200/227 [00:04<00:00, 45.14batch/s]
xclip texts:  90%|█████████ | 205/227 [00:04<00:00, 45.03batch/s]
xclip texts:  93%|█████████▎| 210/227 [00:04<00:00, 44.55batch/s]
xclip texts:  95%|█████████▍| 215/227 [00:04<00:00, 45.64batch/s]
xclip texts: 100%|██████████| 227/227 [00:04<00:00, 47.04batch/s]

irra videos:  50%|█████     | 252/500 [00:36<00:34,  7.21batch/s]
irra videos:  51%|█████     | 253/500 [00:36<00:58,  4.26batch/s]
irra videos:  51%|█████     | 254/500 [00:37<01:26,  2.84batch/s]
irra videos:  51%|█████     | 255/500 [00:37<01:34,  2.60batch/s]
irra videos:  51%|█████     | 256/500 [00:38<01:39,  2.45batch/s]
irra videos:  51%|█████▏    | 257/500 [00:38<01:37,  2.49batch/s]
irra videos:  52%|█████▏    | 258/500 [00:38<01:42,  2.36batch/s]

-- none: R1 9.81  mAP 18.09
== X-CLIP | activitynet/paragraph | vt_1fps_n12

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  52%|█████▏    | 259/500 [00:39<01:34,  2.55batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

xclip videos:   0%|          | 0/498 [00:00<?, ?batch/s]
xclip videos:   0%|          | 1/498 [00:00<01:01,  8.10batch/s]]
xclip videos:   1%|          | 3/498 [00:00<00:52,  9.50batch/s]]
xclip videos:   1%|          | 4/498 [00:00<00:54,  9.06batch/s]]
xclip videos:   1%|          | 5/498 [00:00<00:56,  8.70batch/s]]
xclip videos:   1%|▏         | 7/498 [00:00<00:55,  8.81batch/s]]
xclip videos:   2%|▏         | 8/498 [00:00<00:55,  8.86batch/s]]
xclip videos:   2%|▏         | 9/498 [00:01<00:54,  8.92batch/s]]
xclip videos:   2%|▏         | 10/498 [00:01<00:55,  8.77batch/s]
xclip videos:   2%|▏         | 12/498 [00:01<00:59,  8.20batch/s]
xclip videos:   3%|▎         | 13/498 [00:01<00:58,  8.31batch/s]
xclip videos:   3%|▎         | 15/498 [00:01<00:57,  8.38batch/s]
xclip videos:   3%|▎         | 16/498 [00:01<00:55,  8.67batch/s]
xclip videos:   3%|▎         | 17/498 [00:01<00:56,  8.56batch/s]
xclip videos:   4%|▎         | 18/498 [00:02<00:58,  8.20batch/s]
xclip videos:   4%|▍         | 20/498 [00:02<00:54,  8.74batch/s]
xclip videos:   4%|▍         | 21/498 [00:02<00:53,  8.83batch/s]
xclip videos:   4%|▍         | 22/498 [00:02<00:52,  9.09batch/s]
xclip videos:   5%|▍         | 24/498 [00:02<00:51,  9.27batch/s]
xclip videos:   5%|▌         | 25/498 [00:02<00:51,  9.24batch/s]
irra videos:  56%|█████▌    | 279/500 [00:42<00:30,  7.27batch/s]
xclip videos:   5%|▌         | 27/498 [00:03<00:49,  9.53batch/s]
xclip videos:   6%|▌         | 28/498 [00:03<00:49,  9.55batch/s]
xclip videos:   6%|▌         | 30/498 [00:03<00:47,  9.82batch/s]
xclip videos:   6%|▌         | 31/498 [00:03<00:48,  9.67batch/s]
xclip videos:   6%|▋         | 32/498 [00:03<00:51,  9.05batch/s]
xclip videos:   7%|▋         | 34/498 [00:03<00:49,  9.29batch/s]
xclip videos:   7%|▋         | 35/498 [00:03<00:55,  8.36batch/s]
xclip videos:   7%|▋         | 36/498 [00:04<00:54,  8.49batch/s]
xclip videos:   8%|▊         | 38/498 [00:04<00:55,  8.32batch/s]
xclip videos:   8%|▊         | 39/498 [00:04<00:54,  8.43batch/s]
xclip videos:   8%|▊         | 41/498 [00:04<00:53,  8.52batch/s]
xclip videos:   8%|▊         | 42/498 [00:04<00:53,  8.52batch/s]
xclip videos:   9%|▉         | 44/498 [00:05<00:51,  8.78batch/s]
xclip videos:   9%|▉         | 45/498 [00:05<00:49,  9.07batch/s]
xclip videos:   9%|▉         | 46/498 [00:05<00:51,  8.86batch/s]
xclip videos:   9%|▉         | 47/498 [00:05<00:52,  8.65batch/s]
xclip videos:  10%|▉         | 49/498 [00:05<00:49,  9.01batch/s]
xclip videos:  10%|█         | 51/498 [00:05<00:50,  8.86batch/s]
xclip videos:  10%|█         | 52/498 [00:05<00:48,  9.14batch/s]
xclip videos:  11%|█         | 53/498 [00:05<00:48,  9.16batch/s]
xclip videos:  11%|█         | 55/498 [00:06<00:47,  9.24batch/s]
xclip videos:  11%|█▏        | 57/498 [00:06<00:48,  9.05batch/s]
xclip videos:  12%|█▏        | 58/498 [00:06<00:48,  9.00batch/s]
xclip videos:  12%|█▏        | 59/498 [00:06<00:47,  9.18batch/s]
xclip videos:  12%|█▏        | 61/498 [00:06<00:45,  9.55batch/s]
xclip videos:  12%|█▏        | 62/498 [00:06<00:45,  9.50batch/s]
xclip videos:  13%|█▎        | 63/498 [00:07<00:45,  9.53batch/s]
xclip videos:  13%|█▎        | 65/498 [00:07<00:44,  9.66batch/s]
xclip videos:  13%|█▎        | 66/498 [00:07<00:45,  9.48batch/s]
xclip videos:  13%|█▎        | 67/498 [00:07<00:45,  9.37batch/s]
xclip videos:  14%|█▎        | 68/498 [00:07<00:46,  9.33batch/s]
xclip videos:  14%|█▍        | 70/498 [00:07<00:48,  8.89batch/s]
xclip videos:  14%|█▍        | 71/498 [00:07<00:48,  8.77batch/s]
xclip videos:  14%|█▍        | 72/498 [00:08<00:47,  9.03batch/s]
xclip videos:  15%|█▍        | 74/498 [00:08<00:46,  9.17batch/s]
xclip videos:  15%|█▌        | 76/498 [00:08<00:46,  8.98batch/s]
xclip videos:  15%|█▌        | 77/498 [00:08<00:48,  8.76batch/s]
xclip videos:  16%|█▌        | 78/498 [00:08<00:48,  8.62batch/s]
xclip videos:  16%|█▌        | 80/498 [00:08<00:46,  9.05batch/s]
xclip videos:  16%|█▋        | 81/498 [00:09<00:45,  9.15batch/s]
xclip videos:  16%|█▋        | 82/498 [00:09<00:45,  9.24batch/s]
xclip videos:  17%|█▋        | 83/498 [00:09<00:46,  9.02batch/s]
xclip videos:  17%|█▋        | 85/498 [00:09<00:48,  8.43batch/s]
xclip videos:  17%|█▋        | 86/498 [00:09<00:48,  8.45batch/s]
xclip videos:  18%|█▊        | 88/498 [00:09<00:48,  8.50batch/s]
xclip videos:  18%|█▊        | 89/498 [00:09<00:46,  8.80batch/s]
xclip videos:  18%|█▊        | 90/498 [00:10<00:44,  9.07batch/s]
xclip videos:  18%|█▊        | 92/498 [00:10<00:45,  8.92batch/s]
irra videos:  66%|██████▌   | 328/500 [00:49<00:26,  6.44batch/s]
xclip videos:  19%|█▉        | 95/498 [00:10<00:43,  9.29batch/s]
xclip videos:  19%|█▉        | 96/498 [00:10<00:43,  9.16batch/s]
xclip videos:  19%|█▉        | 97/498 [00:10<00:43,  9.22batch/s]
xclip videos:  20%|█▉        | 98/498 [00:10<00:43,  9.23batch/s]
xclip videos:  20%|██        | 100/498 [00:11<00:45,  8.83batch/s][A
xclip videos:  20%|██        | 102/498 [00:11<00:45,  8.78batch/s][A
xclip videos:  21%|██        | 103/498 [00:11<00:44,  8.82batch/s][A
xclip videos:  21%|██        | 104/498 [00:11<00:45,  8.66batch/s][A
xclip videos:  21%|██▏       | 106/498 [00:11<00:44,  8.75batch/s][A
xclip videos:  21%|██▏       | 107/498 [00:11<00:44,  8.77batch/s][A
xclip videos:  22%|██▏       | 109/498 [00:12<00:43,  8.93batch/s][A
xclip videos:  22%|██▏       | 110/498 [00:12<00:43,  8.89batch/s][A
xclip videos:  22%|██▏       | 112/498 [00:12<00:43,  8.79batch/s][A
xclip videos:  23%|██▎       | 113/498 [00:12<00:43,  8.84batch/s][A
xclip videos:  23%|██▎       | 115/498 [00:12<00:43,  8.86batch/s][A
xclip videos:  23%|██▎       | 116/498 [00:13<00:43,  8.79batch/s][A
xclip videos:  23%|██▎       | 117/498 [00:13<00:43,  8.84batch/s][A
xclip videos:  24%|██▎       | 118/498 [00:13<00:42,  8.95batch/s][A
xclip videos:  24%|██▍       | 119/498 [00:13<00:42,  8.99batch/s][A
xclip videos:  24%|██▍       | 121/498 [00:13<00:42,  8.89batch/s][A
xclip videos:  24%|██▍       | 122/498 [00:13<00:41,  9.12batch/s][A
xclip videos:  25%|██▍       | 123/498 [00:13<00:40,  9.27batch/s][A
xclip videos:  25%|██▌       | 125/498 [00:14<00:42,  8.84batch/s][A
xclip videos:  25%|██▌       | 126/498 [00:14<00:41,  8.92batch/s][A
xclip videos:  26%|██▌       | 127/498 [00:14<00:41,  8.90batch/s][A
xclip videos:  26%|██▌       | 128/498 [00:14<00:42,  8.77batch/s][A
xclip videos:  26%|██▌       | 129/498 [00:14<00:40,  9.02batch/s][A
xclip videos:  26%|██▋       | 131/498 [00:14<00:39,  9.22batch/s][A
xclip videos:  27%|██▋       | 132/498 [00:14<00:40,  9.10batch/s][A
xclip videos:  27%|██▋       | 133/498 [00:14<00:40,  9.07batch/s][A
xclip videos:  27%|██▋       | 134/498 [00:15<00:39,  9.22batch/s][A
xclip videos:  27%|██▋       | 135/498 [00:15<00:39,  9.29batch/s][A
xclip videos:  27%|██▋       | 136/498 [00:15<00:38,  9.32batch/s][A
xclip videos:  28%|██▊       | 138/498 [00:15<00:40,  8.97batch/s][A
xclip videos:  28%|██▊       | 139/498 [00:15<00:39,  9.11batch/s][A
xclip videos:  28%|██▊       | 140/498 [00:15<00:40,  8.86batch/s][A
xclip videos:  29%|██▊       | 142/498 [00:15<00:40,  8.75batch/s][A
xclip videos:  29%|██▊       | 143/498 [00:16<00:41,  8.64batch/s][A
xclip videos:  29%|██▉       | 144/498 [00:16<00:40,  8.72batch/s][A
xclip videos:  29%|██▉       | 146/498 [00:16<00:37,  9.40batch/s][A
xclip videos:  30%|██▉       | 147/498 [00:16<00:37,  9.38batch/s][A
xclip videos:  30%|██▉       | 149/498 [00:16<00:37,  9.43batch/s][A
xclip videos:  30%|███       | 150/498 [00:16<00:38,  9.12batch/s][A
xclip videos:  30%|███       | 151/498 [00:16<00:38,  9.08batch/s][A
xclip videos:  31%|███       | 152/498 [00:16<00:37,  9.15batch/s][A
xclip videos:  31%|███       | 153/498 [00:17<00:37,  9.32batch/s][A
xclip videos:  31%|███       | 155/498 [00:17<00:35,  9.64batch/s][A
xclip videos:  31%|███▏      | 156/498 [00:17<00:37,  9.09batch/s][A
xclip videos:  32%|███▏      | 158/498 [00:17<00:38,  8.74batch/s][A
xclip videos:  32%|███▏      | 159/498 [00:17<00:39,  8.55batch/s][A
xclip videos:  32%|███▏      | 161/498 [00:18<00:39,  8.59batch/s][A
xclip videos:  33%|███▎      | 162/498 [00:18<00:37,  8.89batch/s][A
xclip videos:  33%|███▎      | 163/498 [00:18<00:36,  9.14batch/s][A
xclip videos:  33%|███▎      | 164/498 [00:18<00:36,  9.14batch/s][A
xclip videos:  33%|███▎      | 166/498 [00:18<00:37,  8.83batch/s][A
xclip videos:  34%|███▎      | 167/498 [00:18<00:37,  8.79batch/s][A
xclip videos:  34%|███▍      | 169/498 [00:18<00:37,  8.74batch/s][A
xclip videos:  34%|███▍      | 170/498 [00:19<00:37,  8.70batch/s][A
xclip videos:  35%|███▍      | 172/498 [00:19<00:37,  8.69batch/s][A
xclip videos:  35%|███▍      | 173/498 [00:19<00:37,  8.55batch/s][A
xclip videos:  35%|███▌      | 175/498 [00:19<00:38,  8.49batch/s][A
xclip videos:  35%|███▌      | 176/498 [00:19<00:37,  8.59batch/s][A
irra videos:  78%|███████▊  | 391/500 [00:59<00:17,  6.32batch/s]
xclip videos:  36%|███▌      | 178/498 [00:19<00:34,  9.22batch/s][A
xclip videos:  36%|███▌      | 180/498 [00:20<00:33,  9.38batch/s][A
xclip videos:  36%|███▋      | 181/498 [00:20<00:35,  9.03batch/s][A
xclip videos:  37%|███▋      | 182/498 [00:20<00:34,  9.23batch/s][A
xclip videos:  37%|███▋      | 183/498 [00:20<00:33,  9.30batch/s][A
xclip videos:  37%|███▋      | 185/498 [00:20<00:33,  9.25batch/s][A
xclip videos:  37%|███▋      | 186/498 [00:20<00:33,  9.27batch/s][A
xclip videos:  38%|███▊      | 187/498 [00:20<00:33,  9.41batch/s][A
xclip videos:  38%|███▊      | 189/498 [00:21<00:34,  9.05batch/s][A
xclip videos:  38%|███▊      | 190/498 [00:21<00:34,  9.06batch/s][A
xclip videos:  38%|███▊      | 191/498 [00:21<00:33,  9.08batch/s][A
xclip videos:  39%|███▊      | 192/498 [00:21<00:33,  9.02batch/s][A
xclip videos:  39%|███▉      | 194/498 [00:21<00:33,  9.18batch/s][A
xclip videos:  39%|███▉      | 195/498 [00:21<00:33,  9.06batch/s][A
xclip videos:  39%|███▉      | 196/498 [00:21<00:33,  8.90batch/s][A
xclip videos:  40%|███▉      | 198/498 [00:22<00:32,  9.26batch/s][A
xclip videos:  40%|███▉      | 199/498 [00:22<00:32,  9.22batch/s][A
xclip videos:  40%|████      | 200/498 [00:22<00:32,  9.25batch/s][A
xclip videos:  40%|████      | 201/498 [00:22<00:32,  9.24batch/s][A
xclip videos:  41%|████      | 202/498 [00:22<00:31,  9.34batch/s][A
xclip videos:  41%|████      | 204/498 [00:22<00:30,  9.64batch/s][A
xclip videos:  41%|████      | 205/498 [00:22<00:30,  9.63batch/s][A
xclip videos:  41%|████▏     | 206/498 [00:22<00:30,  9.51batch/s][A
xclip videos:  42%|████▏     | 208/498 [00:23<00:29,  9.86batch/s][A
xclip videos:  42%|████▏     | 209/498 [00:23<00:29,  9.78batch/s][A
xclip videos:  42%|████▏     | 210/498 [00:23<00:29,  9.69batch/s][A
xclip videos:  43%|████▎     | 212/498 [00:23<00:30,  9.24batch/s][A
xclip videos:  43%|████▎     | 213/498 [00:23<00:30,  9.25batch/s][A
xclip videos:  43%|████▎     | 214/498 [00:23<00:30,  9.26batch/s][A
xclip videos:  43%|████▎     | 216/498 [00:24<00:32,  8.57batch/s][A
xclip videos:  44%|████▎     | 217/498 [00:24<00:33,  8.47batch/s][A
xclip videos:  44%|████▍     | 219/498 [00:24<00:32,  8.65batch/s][A
xclip videos:  44%|████▍     | 220/498 [00:24<00:33,  8.39batch/s][A
xclip videos:  45%|████▍     | 222/498 [00:24<00:32,  8.50batch/s][A
xclip videos:  45%|████▍     | 223/498 [00:24<00:31,  8.74batch/s][A
xclip videos:  45%|████▍     | 224/498 [00:24<00:30,  9.07batch/s][A
xclip videos:  45%|████▌     | 225/498 [00:25<00:30,  9.03batch/s][A
xclip videos:  46%|████▌     | 227/498 [00:25<00:28,  9.41batch/s][A
xclip videos:  46%|████▌     | 228/498 [00:25<00:29,  9.21batch/s][A
xclip videos:  46%|████▌     | 229/498 [00:25<00:28,  9.39batch/s][A
xclip videos:  46%|████▌     | 230/498 [00:25<00:28,  9.40batch/s][A
xclip videos:  47%|████▋     | 232/498 [00:25<00:27,  9.57batch/s][A
xclip videos:  47%|████▋     | 233/498 [00:25<00:28,  9.45batch/s][A
xclip videos:  47%|████▋     | 234/498 [00:26<00:28,  9.40batch/s][A
xclip videos:  47%|████▋     | 236/498 [00:26<00:26,  9.75batch/s][A
xclip videos:  48%|████▊     | 238/498 [00:26<00:28,  9.20batch/s][A
xclip videos:  48%|████▊     | 239/498 [00:26<00:28,  9.08batch/s][A
xclip videos:  48%|████▊     | 241/498 [00:26<00:29,  8.80batch/s][A
xclip videos:  49%|████▊     | 242/498 [00:26<00:29,  8.56batch/s][A
xclip videos:  49%|████▉     | 244/498 [00:27<00:29,  8.58batch/s][A
xclip videos:  49%|████▉     | 245/498 [00:27<00:29,  8.62batch/s][A
xclip videos:  50%|████▉     | 247/498 [00:27<00:28,  8.67batch/s][A
xclip videos:  50%|████▉     | 248/498 [00:27<00:28,  8.78batch/s][A
xclip videos:  50%|█████     | 249/498 [00:27<00:28,  8.71batch/s][A
xclip videos:  50%|█████     | 251/498 [00:27<00:26,  9.30batch/s][A
xclip videos:  51%|█████     | 252/498 [00:28<00:26,  9.31batch/s][A
xclip videos:  51%|█████     | 254/498 [00:28<00:26,  9.25batch/s][A
xclip videos:  51%|█████     | 255/498 [00:28<00:26,  9.17batch/s][A
xclip videos:  52%|█████▏    | 257/498 [00:28<00:25,  9.44batch/s][A
xclip videos:  52%|█████▏    | 258/498 [00:28<00:25,  9.60batch/s][A
xclip videos:  52%|█████▏    | 259/498 [00:28<00:24,  9.70batch/s][A
xclip videos:  52%|█████▏    | 261/498 [00:28<00:23,  9.92batch/s][A
xclip videos:  53%|█████▎    | 262/498 [00:29<00:23,  9.89batch/s][A
irra videos:  91%|█████████ | 455/500 [01:08<00:06,  7.12batch/s]
xclip videos:  53%|█████▎    | 264/498 [00:29<00:24,  9.66batch/s][A
xclip videos:  53%|█████▎    | 266/498 [00:29<00:23,  9.75batch/s][A
xclip videos:  54%|█████▎    | 267/498 [00:29<00:24,  9.62batch/s][A
xclip videos:  54%|█████▍    | 269/498 [00:29<00:24,  9.29batch/s][A
xclip videos:  54%|█████▍    | 270/498 [00:29<00:24,  9.17batch/s][A
xclip videos:  54%|█████▍    | 271/498 [00:30<00:24,  9.33batch/s][A
xclip videos:  55%|█████▍    | 273/498 [00:30<00:25,  8.77batch/s][A
xclip videos:  55%|█████▌    | 274/498 [00:30<00:24,  9.00batch/s][A
xclip videos:  55%|█████▌    | 275/498 [00:30<00:24,  9.15batch/s][A
xclip videos:  56%|█████▌    | 277/498 [00:30<00:24,  9.20batch/s][A
xclip videos:  56%|█████▌    | 278/498 [00:30<00:24,  8.95batch/s][A
xclip videos:  56%|█████▌    | 279/498 [00:30<00:25,  8.59batch/s][A
xclip videos:  56%|█████▋    | 281/498 [00:31<00:25,  8.55batch/s][A
xclip videos:  57%|█████▋    | 282/498 [00:31<00:24,  8.66batch/s][A
xclip videos:  57%|█████▋    | 283/498 [00:31<00:23,  8.97batch/s][A
xclip videos:  57%|█████▋    | 284/498 [00:31<00:24,  8.81batch/s][A
xclip videos:  57%|█████▋    | 286/498 [00:31<00:23,  8.96batch/s][A
xclip videos:  58%|█████▊    | 287/498 [00:31<00:23,  9.00batch/s][A
xclip videos:  58%|█████▊    | 288/498 [00:31<00:23,  9.08batch/s][A
xclip videos:  58%|█████▊    | 289/498 [00:32<00:22,  9.28batch/s][A
xclip videos:  58%|█████▊    | 290/498 [00:32<00:22,  9.20batch/s][A
xclip videos:  59%|█████▊    | 292/498 [00:32<00:21,  9.40batch/s][A
xclip videos:  59%|█████▉    | 293/498 [00:32<00:22,  9.31batch/s][A
xclip videos:  59%|█████▉    | 294/498 [00:32<00:22,  9.19batch/s][A
xclip videos:  59%|█████▉    | 295/498 [00:32<00:22,  9.08batch/s][A
xclip videos:  59%|█████▉    | 296/498 [00:32<00:22,  8.97batch/s][A
xclip videos:  60%|█████▉    | 297/498 [00:32<00:22,  9.02batch/s][A
xclip videos:  60%|█████▉    | 298/498 [00:33<00:22,  9.05batch/s][A
xclip videos:  60%|██████    | 299/498 [00:33<00:22,  8.94batch/s][A
xclip videos:  60%|██████    | 301/498 [00:33<00:21,  9.04batch/s][A
xclip videos:  61%|██████    | 302/498 [00:33<00:21,  9.18batch/s][A
xclip videos:  61%|██████    | 304/498 [00:33<00:21,  9.11batch/s][A
xclip videos:  61%|██████    | 305/498 [00:33<00:22,  8.76batch/s][A
xclip videos:  61%|██████▏   | 306/498 [00:33<00:23,  8.23batch/s][A
xclip videos:  62%|██████▏   | 307/498 [00:34<00:22,  8.52batch/s][A
xclip videos:  62%|██████▏   | 309/498 [00:34<00:20,  9.10batch/s][A
xclip videos:  62%|██████▏   | 310/498 [00:34<00:21,  8.92batch/s][A
xclip videos:  63%|██████▎   | 312/498 [00:34<00:21,  8.76batch/s][A
xclip videos:  63%|██████▎   | 313/498 [00:34<00:21,  8.73batch/s][A
xclip videos:  63%|██████▎   | 314/498 [00:34<00:20,  8.80batch/s][A
xclip videos:  63%|██████▎   | 316/498 [00:35<00:19,  9.16batch/s][A
xclip videos:  64%|██████▎   | 317/498 [00:35<00:19,  9.35batch/s][A
xclip videos:  64%|██████▍   | 318/498 [00:35<00:19,  9.24batch/s][A
xclip videos:  64%|██████▍   | 320/498 [00:35<00:19,  9.21batch/s][A
irra videos: 100%|██████████| 500/500 [01:15<00:00,  6.67batch/s]

irra texts:   0%|          | 0/63 [00:00<?, ?batch/s]
xclip videos:  64%|██████▍   | 321/498 [00:35<00:21,  8.36batch/s]
xclip videos:  65%|██████▍   | 322/498 [00:35<00:21,  8.23batch/s]
xclip videos:  65%|██████▍   | 323/498 [00:35<00:22,  7.66batch/s]
xclip videos:  65%|██████▌   | 324/498 [00:36<00:23,  7.53batch/s]
xclip videos:  65%|██████▌   | 325/498 [00:36<00:22,  7.64batch/s]
xclip videos:  65%|██████▌   | 326/498 [00:36<00:22,  7.60batch/s]
xclip videos:  66%|██████▌   | 327/498 [00:36<00:21,  7.79batch/s]
xclip videos:  66%|██████▌   | 328/498 [00:36<00:20,  8.10batch/s]
xclip videos:  66%|██████▌   | 329/498 [00:36<00:21,  7.98batch/s]
xclip videos:  66%|██████▋   | 330/498 [00:36<00:20,  8.18batch/s]
xclip videos:  66%|██████▋   | 331/498 [00:36<00:20,  8.26batch/s]
xclip videos:  67%|██████▋   | 332/498 [00:37<00:20,  7.98batch/s]
xclip videos:  67%|██████▋   | 333/498 [00:37<00:20,  8.01batch/s]
xclip videos:  67%|██████▋   | 334/498 [00:37<00:20,  8.10batch/s]
irra texts: 100%|██████████| 63/63 [00:01<00:00, 33.88batch/s]
xclip videos:  68%|██████▊   | 337/498 [00:38<00:35,  4.47batch/s]

-- none: R1 13.50  mAP 23.71
== IRRA | activitynet/sentence | uniform8

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:  68%|██████▊   | 339/498 [00:38<00:36,  4.37batch/s]
xclip videos:  68%|██████▊   | 340/498 [00:38<00:32,  4.85batch/s]
xclip videos:  68%|██████▊   | 341/498 [00:38<00:28,  5.59batch/s]
xclip videos:  69%|██████▊   | 342/498 [00:38<00:25,  6.17batch/s]
xclip videos:  69%|██████▉   | 343/498 [00:39<00:23,  6.66batch/s]
xclip videos:  69%|██████▉   | 344/498 [00:39<00:22,  6.99batch/s]
xclip videos:  69%|██████▉   | 345/498 [00:39<00:20,  7.60batch/s]
xclip videos:  69%|██████▉   | 346/498 [00:39<00:19,  7.78batch/s]
xclip videos:  70%|██████▉   | 347/498 [00:39<00:18,  7.99batch/s]
xclip videos:  70%|██████▉   | 348/498 [00:39<00:18,  8.02batch/s]
xclip videos:  70%|███████   | 349/498 [00:39<00:18,  8.26batch/s]
xclip videos:  70%|███████   | 350/498 [00:39<00:18,  8.15batch/s]
xclip videos:  70%|███████   | 351/498 [00:40<00:17,  8.33batch/s]
xclip videos:  71%|███████   | 352/498 [00:40<00:18,  8.08batch/s]
xclip videos:  71%|███████   | 353/498 [00:40<00:17,  8.51batch/s]
xclip videos:  71%|███████   | 354/498 [00:40<00:17,  8.46batch/s]
xclip videos:  71%|███████▏  | 355/498 [00:40<00:16,  8.47batch/s]
xclip videos:  71%|███████▏  | 356/498 [00:40<00:16,  8.49batch/s]
xclip videos:  72%|███████▏  | 357/498 [00:40<00:15,  8.84batch/s]
xclip videos:  72%|███████▏  | 358/498 [00:40<00:16,  8.44batch/s]
xclip videos:  72%|███████▏  | 359/498 [00:41<00:17,  8.00batch/s]
xclip videos:  72%|███████▏  | 360/498 [00:41<00:16,  8.32batch/s]A
xclip videos:  72%|███████▏  | 361/498 [00:41<00:16,  8.22batch/s]A
xclip videos:  73%|███████▎  | 362/498 [00:41<00:16,  8.25batch/s]A
xclip videos:  73%|███████▎  | 363/498 [00:41<00:15,  8.59batch/s]A
xclip videos:  73%|███████▎  | 364/498 [00:41<00:15,  8.48batch/s]A
xclip videos:  73%|███████▎  | 365/498 [00:41<00:15,  8.42batch/s]A
xclip videos:  74%|███████▎  | 367/498 [00:41<00:16,  8.17batch/s]A
irra texts:  59%|█████▊    | 133/227 [00:03<00:02, 36.56batch/s]
xclip videos:  74%|███████▍  | 369/498 [00:42<00:15,  8.59batch/s]A
xclip videos:  74%|███████▍  | 370/498 [00:42<00:15,  8.12batch/s]A
xclip videos:  74%|███████▍  | 371/498 [00:42<00:15,  8.45batch/s]A
xclip videos:  75%|███████▍  | 372/498 [00:42<00:14,  8.58batch/s]A
xclip videos:  75%|███████▍  | 373/498 [00:42<00:14,  8.61batch/s]A
xclip videos:  75%|███████▌  | 374/498 [00:42<00:14,  8.63batch/s]A
xclip videos:  75%|███████▌  | 375/498 [00:42<00:14,  8.58batch/s]A
xclip videos:  76%|███████▌  | 376/498 [00:42<00:13,  8.87batch/s]A
xclip videos:  76%|███████▌  | 377/498 [00:43<00:13,  9.03batch/s]A
xclip videos:  76%|███████▌  | 378/498 [00:43<00:13,  8.96batch/s]A
xclip videos:  76%|███████▌  | 379/498 [00:43<00:13,  8.66batch/s]A
xclip videos:  76%|███████▋  | 380/498 [00:43<00:13,  8.99batch/s]A
xclip videos:  77%|███████▋  | 382/498 [00:43<00:13,  8.62batch/s]A
xclip videos:  77%|███████▋  | 383/498 [00:43<00:13,  8.69batch/s]A
xclip videos:  77%|███████▋  | 384/498 [00:43<00:13,  8.16batch/s]A
xclip videos:  77%|███████▋  | 385/498 [00:44<00:13,  8.31batch/s]A
xclip videos:  78%|███████▊  | 386/498 [00:44<00:13,  8.51batch/s]A
irra texts: 100%|██████████| 227/227 [00:05<00:00, 41.31batch/s]
xclip videos:  79%|███████▉  | 395/498 [00:47<00:32,  3.19batch/s]

-- none: R1 6.50  mAP 12.87

xclip videos:  80%|███████▉  | 396/498 [00:47<00:30,  3.34batch/s]

== IRRA | activitynet/paragraph | vt_1fps_n12

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:  80%|███████▉  | 397/498 [00:47<00:28,  3.52batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

xclip videos:  80%|███████▉  | 398/498 [00:48<00:38,  2.58batch/s]
xclip videos:  80%|████████  | 400/498 [00:48<00:25,  3.91batch/s]
xclip videos:  81%|████████  | 401/498 [00:48<00:21,  4.50batch/s]
xclip videos:  81%|████████  | 403/498 [00:48<00:16,  5.78batch/s]
xclip videos:  81%|████████  | 404/498 [00:48<00:14,  6.36batch/s]
xclip videos:  81%|████████▏ | 405/498 [00:48<00:14,  6.59batch/s]
xclip videos:  82%|████████▏ | 406/498 [00:49<00:12,  7.22batch/s]
xclip videos:  82%|████████▏ | 407/498 [00:49<00:11,  7.62batch/s]
xclip videos:  82%|████████▏ | 408/498 [00:49<00:11,  8.01batch/s]
xclip videos:  82%|████████▏ | 410/498 [00:49<00:10,  8.11batch/s]
xclip videos:  83%|████████▎ | 411/498 [00:49<00:10,  8.09batch/s]A
xclip videos:  83%|████████▎ | 412/498 [00:49<00:10,  7.99batch/s]A
xclip videos:  83%|████████▎ | 414/498 [00:50<00:09,  8.43batch/s]A
xclip videos:  84%|████████▎ | 416/498 [00:50<00:09,  8.41batch/s]A
xclip videos:  84%|████████▎ | 417/498 [00:50<00:09,  8.61batch/s]A
xclip videos:  84%|████████▍ | 418/498 [00:50<00:09,  8.76batch/s]A
xclip videos:  84%|████████▍ | 419/498 [00:50<00:08,  8.90batch/s]A
xclip videos:  84%|████████▍ | 420/498 [00:50<00:08,  8.91batch/s]A
xclip videos:  85%|████████▍ | 421/498 [00:50<00:08,  8.76batch/s]A
xclip videos:  85%|████████▍ | 423/498 [00:51<00:08,  9.11batch/s]A
xclip videos:  85%|████████▌ | 424/498 [00:51<00:08,  8.90batch/s]A
xclip videos:  85%|████████▌ | 425/498 [00:51<00:08,  8.82batch/s]A
xclip videos:  86%|████████▌ | 426/498 [00:51<00:08,  8.98batch/s]A
xclip videos:  86%|████████▌ | 427/498 [00:51<00:07,  8.89batch/s]A
xclip videos:  86%|████████▌ | 429/498 [00:51<00:08,  8.49batch/s]A
xclip videos:  86%|████████▋ | 430/498 [00:51<00:08,  8.33batch/s]A
xclip videos:  87%|████████▋ | 432/498 [00:52<00:07,  8.76batch/s]A
xclip videos:  87%|████████▋ | 433/498 [00:52<00:07,  9.02batch/s]A
xclip videos:  87%|████████▋ | 434/498 [00:52<00:06,  9.21batch/s]A
xclip videos:  87%|████████▋ | 435/498 [00:52<00:06,  9.41batch/s]A
xclip videos:  88%|████████▊ | 437/498 [00:52<00:06,  9.32batch/s]A
xclip videos:  88%|████████▊ | 438/498 [00:52<00:06,  9.35batch/s]A
xclip videos:  88%|████████▊ | 439/498 [00:52<00:06,  9.28batch/s]A
xclip videos:  89%|████████▊ | 441/498 [00:53<00:06,  8.41batch/s]A
xclip videos:  89%|████████▉ | 442/498 [00:53<00:06,  8.56batch/s]A
xclip videos:  89%|████████▉ | 443/498 [00:53<00:06,  8.69batch/s]A
xclip videos:  89%|████████▉ | 444/498 [00:53<00:06,  8.85batch/s]A
xclip videos:  89%|████████▉ | 445/498 [00:53<00:05,  8.91batch/s]A
xclip videos:  90%|████████▉ | 447/498 [00:53<00:05,  8.64batch/s]A
xclip videos:  90%|████████▉ | 448/498 [00:53<00:06,  8.18batch/s]A
xclip videos:  90%|█████████ | 449/498 [00:54<00:05,  8.43batch/s]A
xclip videos:  91%|█████████ | 451/498 [00:54<00:05,  8.67batch/s]A
xclip videos:  91%|█████████ | 452/498 [00:54<00:05,  8.51batch/s]A
xclip videos:  91%|█████████ | 454/498 [00:54<00:05,  8.38batch/s]A
xclip videos:  91%|█████████▏| 455/498 [00:54<00:05,  8.41batch/s]A
xclip videos:  92%|█████████▏| 457/498 [00:54<00:05,  8.09batch/s]A
xclip videos:  92%|█████████▏| 458/498 [00:55<00:04,  8.48batch/s]A
xclip videos:  92%|█████████▏| 459/498 [00:55<00:04,  8.83batch/s]A
xclip videos:  92%|█████████▏| 460/498 [00:55<00:04,  8.98batch/s]A
xclip videos:  93%|█████████▎| 462/498 [00:55<00:03,  9.20batch/s]A
xclip videos:  93%|█████████▎| 463/498 [00:55<00:03,  8.87batch/s]A
xclip videos:  93%|█████████▎| 464/498 [00:55<00:03,  8.67batch/s]A
xclip videos:  94%|█████████▎| 466/498 [00:55<00:03,  8.85batch/s]A
xclip videos:  94%|█████████▍| 467/498 [00:56<00:03,  8.83batch/s]A
xclip videos:  94%|█████████▍| 468/498 [00:56<00:03,  8.85batch/s]A
xclip videos:  94%|█████████▍| 469/498 [00:56<00:03,  9.07batch/s]A
xclip videos:  94%|█████████▍| 470/498 [00:56<00:03,  9.04batch/s]A
xclip videos:  95%|█████████▍| 471/498 [00:56<00:03,  8.87batch/s]A
xclip videos:  95%|█████████▍| 473/498 [00:56<00:02,  9.40batch/s]A
xclip videos:  95%|█████████▌| 474/498 [00:56<00:02,  9.41batch/s]A
xclip videos:  96%|█████████▌| 476/498 [00:57<00:02,  9.24batch/s]A
xclip videos:  96%|█████████▌| 477/498 [00:57<00:02,  8.94batch/s]A
xclip videos:  96%|█████████▌| 478/498 [00:57<00:02,  9.20batch/s]A
xclip videos:  96%|█████████▌| 479/498 [00:57<00:02,  9.28batch/s]A
xclip videos:  97%|█████████▋| 481/498 [00:57<00:01,  9.58batch/s]A
xclip videos:  97%|█████████▋| 482/498 [00:57<00:01,  9.58batch/s]A
xclip videos:  97%|█████████▋| 483/498 [00:57<00:01,  9.46batch/s]A
xclip videos:  97%|█████████▋| 484/498 [00:57<00:01,  9.36batch/s]A
xclip videos:  97%|█████████▋| 485/498 [00:58<00:01,  9.20batch/s]A
xclip videos:  98%|█████████▊| 487/498 [00:58<00:01,  8.58batch/s]A
xclip videos:  98%|█████████▊| 488/498 [00:58<00:01,  8.74batch/s]A
xclip videos:  98%|█████████▊| 489/498 [00:58<00:01,  8.90batch/s]A
xclip videos:  98%|█████████▊| 490/498 [00:58<00:00,  9.02batch/s]A
xclip videos:  99%|█████████▉| 492/498 [00:58<00:00,  8.50batch/s]A
xclip videos:  99%|█████████▉| 493/498 [00:58<00:00,  8.40batch/s]A
xclip videos:  99%|█████████▉| 495/498 [00:59<00:00,  8.57batch/s]A
xclip videos: 100%|█████████▉| 496/498 [00:59<00:00,  8.65batch/s]A
xclip videos: 100%|██████████| 498/498 [00:59<00:00,  8.37batch/s]A
xclip texts:   0%|          | 0/63 [00:00<?, ?batch/s]
xclip texts:   8%|▊         | 5/63 [00:00<00:01, 43.28batch/s]s]
xclip texts:  16%|█▌        | 10/63 [00:00<00:01, 45.13batch/s]]
xclip texts:  24%|██▍       | 15/63 [00:00<00:01, 44.19batch/s]]
xclip texts:  32%|███▏      | 20/63 [00:00<00:00, 44.14batch/s]]
xclip texts:  40%|███▉      | 25/63 [00:00<00:00, 45.93batch/s]]
xclip texts:  48%|████▊     | 30/63 [00:00<00:00, 46.01batch/s]]
xclip texts:  57%|█████▋    | 36/63 [00:00<00:00, 47.17batch/s]]
xclip texts:  67%|██████▋   | 42/63 [00:00<00:00, 47.80batch/s]]
xclip texts:  75%|███████▍  | 47/63 [00:01<00:00, 42.38batch/s]]
xclip texts:  83%|████████▎ | 52/63 [00:01<00:00, 42.45batch/s]]
xclip texts:  90%|█████████ | 57/63 [00:01<00:00, 42.47batch/s]]
xclip texts: 100%|██████████| 63/63 [00:01<00:00, 43.28batch/s]]

irra videos:   9%|▉         | 90/995 [00:13<02:30,  6.00batch/s]
irra videos:   9%|▉         | 91/995 [00:13<03:20,  4.51batch/s]
irra videos:   9%|▉         | 92/995 [00:14<05:25,  2.78batch/s]
irra videos:   9%|▉         | 93/995 [00:14<06:05,  2.47batch/s]
irra videos:   9%|▉         | 94/995 [00:15<06:23,  2.35batch/s]
irra videos:  10%|▉         | 95/995 [00:15<07:02,  2.13batch/s]
irra videos:  10%|▉         | 96/995 [00:15<06:16,  2.39batch/s]
irra videos:  10%|▉         | 97/995 [00:16<05:19,  2.81batch/s]
irra videos:  10%|▉         | 98/995 [00:16<05:28,  2.73batch/s]

-- mean: R1 23.70  mAP 37.15
-- mean_s8: R1 23.70  mAP 37.15
-- max: R1 23.80  mAP 36.25
-- query_max: R1 23.10  mAP 36.61
== X-CLIP | activitynet/sentence | vt_1fps_n12

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  10%|▉         | 99/995 [00:16<05:57,  2.51batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

xclip texts:   0%|          | 0/227 [00:00<?, ?batch/s]
xclip texts:   3%|▎         | 6/227 [00:00<00:04, 52.98batch/s]s]
xclip texts:   5%|▌         | 12/227 [00:00<00:04, 50.88batch/s]]
xclip texts:   8%|▊         | 18/227 [00:00<00:04, 43.69batch/s]]
xclip texts:  12%|█▏        | 28/227 [00:00<00:04, 42.23batch/s]]
xclip texts:  15%|█▍        | 34/227 [00:00<00:04, 46.22batch/s]]
xclip texts:  17%|█▋        | 39/227 [00:00<00:04, 44.29batch/s]]
xclip texts:  19%|█▉        | 44/227 [00:01<00:04, 41.72batch/s]]
xclip texts:  22%|██▏       | 49/227 [00:01<00:04, 43.71batch/s]]
xclip texts:  24%|██▍       | 55/227 [00:01<00:03, 46.19batch/s]]
xclip texts:  30%|██▉       | 67/227 [00:01<00:03, 51.29batch/s]]
xclip texts:  32%|███▏      | 73/227 [00:01<00:03, 50.50batch/s]]
xclip texts:  35%|███▍      | 79/227 [00:01<00:02, 49.66batch/s]]
xclip texts:  37%|███▋      | 85/227 [00:01<00:02, 50.16batch/s]]
xclip texts:  40%|████      | 91/227 [00:01<00:02, 49.52batch/s]]
xclip texts:  42%|████▏     | 96/227 [00:02<00:02, 45.93batch/s]]
xclip texts:  44%|████▍     | 101/227 [00:02<00:02, 44.83batch/s]
xclip texts:  47%|████▋     | 107/227 [00:02<00:02, 47.51batch/s]
xclip texts:  52%|█████▏    | 118/227 [00:02<00:02, 48.29batch/s]
xclip texts:  54%|█████▍    | 123/227 [00:02<00:02, 46.74batch/s]
xclip texts:  57%|█████▋    | 129/227 [00:02<00:02, 48.23batch/s]
xclip texts:  59%|█████▉    | 134/227 [00:02<00:01, 47.34batch/s]
xclip texts:  61%|██████    | 139/227 [00:02<00:01, 46.98batch/s]
xclip texts:  63%|██████▎   | 144/227 [00:03<00:01, 46.13batch/s]
xclip texts:  69%|██████▊   | 156/227 [00:03<00:01, 51.05batch/s]
xclip texts:  71%|███████▏  | 162/227 [00:03<00:01, 48.77batch/s]
xclip texts:  74%|███████▍  | 168/227 [00:03<00:01, 49.60batch/s]
xclip texts:  77%|███████▋  | 174/227 [00:03<00:01, 50.65batch/s]
xclip texts:  79%|███████▉  | 180/227 [00:03<00:00, 48.54batch/s]
xclip texts:  81%|████████▏ | 185/227 [00:03<00:00, 47.31batch/s]
xclip texts:  86%|████████▌ | 195/227 [00:04<00:00, 44.76batch/s]
xclip texts:  89%|████████▊ | 201/227 [00:04<00:00, 46.58batch/s]
xclip texts:  91%|█████████ | 207/227 [00:04<00:00, 48.15batch/s]
xclip texts:  94%|█████████▍| 213/227 [00:04<00:00, 49.26batch/s]
xclip texts:  96%|█████████▋| 219/227 [00:04<00:00, 50.91batch/s]
xclip texts: 100%|██████████| 227/227 [00:04<00:00, 47.73batch/s]

irra videos:  14%|█▎        | 135/995 [00:21<01:52,  7.65batch/s]
irra videos:  14%|█▎        | 136/995 [00:22<02:38,  5.41batch/s]
irra videos:  14%|█▍        | 137/995 [00:22<03:50,  3.72batch/s]
irra videos:  14%|█▍        | 138/995 [00:23<05:01,  2.85batch/s]
irra videos:  14%|█▍        | 139/995 [00:23<04:57,  2.88batch/s]
irra videos:  14%|█▍        | 140/995 [00:24<05:46,  2.47batch/s]
irra videos:  14%|█▍        | 141/995 [00:24<05:30,  2.58batch/s]
irra videos:  14%|█▍        | 142/995 [00:25<05:59,  2.37batch/s]
irra videos:  14%|█▍        | 143/995 [00:25<06:12,  2.29batch/s]
irra videos:  14%|█▍        | 144/995 [00:25<06:04,  2.34batch/s]
irra videos:  15%|█▍        | 145/995 [00:26<05:34,  2.54batch/s]
irra videos:  15%|█▍        | 146/995 [00:26<05:57,  2.38batch/s]
irra videos:  15%|█▍        | 147/995 [00:27<05:30,  2.57batch/s]
irra videos:  15%|█▍        | 148/995 [00:27<05:55,  2.38batch/s]
irra videos:  15%|█▍        | 149/995 [00:27<05:32,  2.54batch/s]
irra videos:  15%|█▌        | 150/995 [00:28<05:21,  2.63batch/s]
irra videos:  15%|█▌        | 151/995 [00:28<04:38,  3.03batch/s]
irra videos:  15%|█▌        | 152/995 [00:28<05:06,  2.75batch/s]
irra videos:  15%|█▌        | 153/995 [00:29<05:22,  2.61batch/s]
irra videos:  15%|█▌        | 154/995 [00:29<06:42,  2.09batch/s]
irra videos:  16%|█▌        | 155/995 [00:30<07:34,  1.85batch/s]
irra videos:  16%|█▌        | 156/995 [00:30<06:38,  2.11batch/s]
irra videos:  16%|█▌        | 157/995 [00:31<06:05,  2.30batch/s]
irra videos:  16%|█▌        | 158/995 [00:31<05:04,  2.75batch/s]
irra videos:  16%|█▌        | 159/995 [00:31<04:36,  3.03batch/s]
irra videos:  16%|█▌        | 160/995 [00:32<04:17,  3.25batch/s]
irra videos:  16%|█▌        | 161/995 [00:32<04:04,  3.41batch/s]
irra videos:  16%|█▋        | 162/995 [00:32<04:08,  3.35batch/s]
irra videos:  16%|█▋        | 163/995 [00:33<04:44,  2.92batch/s]
irra videos:  16%|█▋        | 164/995 [00:33<04:43,  2.93batch/s]
irra videos:  17%|█▋        | 165/995 [00:33<04:04,  3.39batch/s]
irra videos:  17%|█▋        | 166/995 [00:33<03:34,  3.86batch/s]
irra videos:  17%|█▋        | 167/995 [00:33<03:29,  3.96batch/s]
irra videos:  17%|█▋        | 168/995 [00:34<03:19,  4.14batch/s]
irra videos:  17%|█▋        | 169/995 [00:34<05:00,  2.75batch/s]
irra videos:  17%|█▋        | 170/995 [00:35<07:15,  1.89batch/s]

-- mean: R1 11.89  mAP 20.45
-- mean_s8: R1 11.89  mAP 20.45
-- max: R1 10.98  mAP 19.45
-- query_max: R1 11.50  mAP 20.34
== X-CLIP | activitynet/paragraph | vt_2fps_n32

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  17%|█▋        | 171/995 [00:36<08:02,  1.71batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

xclip videos:   0%|          | 0/1726 [00:00<?, ?batch/s]
xclip videos:   0%|          | 2/1726 [00:00<03:07,  9.20batch/s]
xclip videos:   0%|          | 3/1726 [00:00<03:01,  9.52batch/s]
xclip videos:   0%|          | 4/1726 [00:00<03:05,  9.28batch/s]
xclip videos:   0%|          | 6/1726 [00:00<03:14,  8.84batch/s]
xclip videos:   0%|          | 7/1726 [00:00<03:20,  8.56batch/s]
xclip videos:   1%|          | 9/1726 [00:01<03:14,  8.83batch/s]
xclip videos:   1%|          | 10/1726 [00:01<03:12,  8.91batch/s][A
xclip videos:   1%|          | 11/1726 [00:01<03:21,  8.52batch/s][A
xclip videos:   1%|          | 12/1726 [00:01<03:19,  8.61batch/s][A
xclip videos:   1%|          | 13/1726 [00:01<03:11,  8.95batch/s][A
xclip videos:   1%|          | 14/1726 [00:01<03:07,  9.14batch/s][A
xclip videos:   1%|          | 16/1726 [00:01<03:06,  9.19batch/s][A
xclip videos:   1%|          | 17/1726 [00:01<03:06,  9.16batch/s][A
irra videos:  19%|█▊        | 185/995 [00:38<01:56,  6.96batch/s]
xclip videos:   1%|          | 20/1726 [00:02<03:00,  9.47batch/s][A
xclip videos:   1%|          | 21/1726 [00:02<03:03,  9.30batch/s][A
xclip videos:   1%|▏         | 23/1726 [00:02<03:09,  8.97batch/s][A
xclip videos:   1%|▏         | 24/1726 [00:02<03:12,  8.85batch/s][A
xclip videos:   1%|▏         | 25/1726 [00:02<03:15,  8.69batch/s][A
xclip videos:   2%|▏         | 27/1726 [00:03<03:12,  8.85batch/s][A
xclip videos:   2%|▏         | 28/1726 [00:03<03:10,  8.91batch/s][A
xclip videos:   2%|▏         | 29/1726 [00:03<03:08,  9.02batch/s][A
xclip videos:   2%|▏         | 30/1726 [00:03<03:09,  8.96batch/s][A
xclip videos:   2%|▏         | 31/1726 [00:03<03:07,  9.02batch/s][A
xclip videos:   2%|▏         | 33/1726 [00:03<03:00,  9.36batch/s][A
xclip videos:   2%|▏         | 34/1726 [00:03<03:01,  9.30batch/s][A
xclip videos:   2%|▏         | 35/1726 [00:03<02:59,  9.42batch/s][A
xclip videos:   2%|▏         | 36/1726 [00:03<03:01,  9.31batch/s][A
xclip videos:   2%|▏         | 38/1726 [00:04<03:06,  9.07batch/s][A
xclip videos:   2%|▏         | 39/1726 [00:04<03:09,  8.92batch/s][A
xclip videos:   2%|▏         | 40/1726 [00:04<03:22,  8.33batch/s][A
xclip videos:   2%|▏         | 41/1726 [00:04<03:28,  8.08batch/s][A
xclip videos:   2%|▏         | 43/1726 [00:04<03:15,  8.62batch/s][A
xclip videos:   3%|▎         | 44/1726 [00:04<03:11,  8.77batch/s][A
xclip videos:   3%|▎         | 45/1726 [00:05<03:10,  8.80batch/s][A
xclip videos:   3%|▎         | 46/1726 [00:05<03:10,  8.82batch/s][A
xclip videos:   3%|▎         | 48/1726 [00:05<03:01,  9.26batch/s][A
xclip videos:   3%|▎         | 49/1726 [00:05<03:01,  9.23batch/s][A
xclip videos:   3%|▎         | 51/1726 [00:05<02:59,  9.33batch/s][A
xclip videos:   3%|▎         | 52/1726 [00:05<02:57,  9.43batch/s][A
irra videos:  21%|██▏       | 212/995 [00:42<01:51,  7.00batch/s]
xclip videos:   3%|▎         | 55/1726 [00:06<02:55,  9.51batch/s][A
irra videos:  22%|██▏       | 214/995 [00:42<01:45,  7.38batch/s]
xclip videos:   3%|▎         | 57/1726 [00:06<02:50,  9.76batch/s][A
xclip videos:   3%|▎         | 58/1726 [00:06<02:51,  9.73batch/s][A
xclip videos:   3%|▎         | 60/1726 [00:06<02:49,  9.86batch/s][A
xclip videos:   4%|▎         | 61/1726 [00:06<02:53,  9.61batch/s][A
xclip videos:   4%|▎         | 62/1726 [00:06<02:59,  9.27batch/s][A
xclip videos:   4%|▎         | 63/1726 [00:06<03:00,  9.22batch/s][A
xclip videos:   4%|▍         | 65/1726 [00:07<02:54,  9.50batch/s][A
xclip videos:   4%|▍         | 66/1726 [00:07<02:58,  9.32batch/s][A
xclip videos:   4%|▍         | 67/1726 [00:07<03:04,  8.99batch/s][A
xclip videos:   4%|▍         | 69/1726 [00:07<03:02,  9.08batch/s][A
xclip videos:   4%|▍         | 70/1726 [00:07<03:02,  9.06batch/s][A
xclip videos:   4%|▍         | 71/1726 [00:07<02:58,  9.29batch/s][A
xclip videos:   4%|▍         | 72/1726 [00:07<02:57,  9.29batch/s][A
xclip videos:   4%|▍         | 74/1726 [00:08<02:57,  9.28batch/s][A
xclip videos:   4%|▍         | 75/1726 [00:08<03:00,  9.16batch/s][A
xclip videos:   4%|▍         | 76/1726 [00:08<03:00,  9.14batch/s][A
xclip videos:   4%|▍         | 77/1726 [00:08<03:02,  9.05batch/s][A
xclip videos:   5%|▍         | 78/1726 [00:08<03:01,  9.06batch/s][A
xclip videos:   5%|▍         | 80/1726 [00:08<03:03,  8.99batch/s][A
xclip videos:   5%|▍         | 81/1726 [00:08<03:10,  8.64batch/s][A
xclip videos:   5%|▍         | 82/1726 [00:09<03:18,  8.29batch/s][A
xclip videos:   5%|▍         | 84/1726 [00:09<03:06,  8.81batch/s][A
xclip videos:   5%|▍         | 85/1726 [00:09<03:11,  8.57batch/s][A
xclip videos:   5%|▌         | 87/1726 [00:09<03:04,  8.88batch/s][A
irra videos:  24%|██▍       | 239/995 [00:46<01:58,  6.37batch/s]
xclip videos:   5%|▌         | 89/1726 [00:09<02:51,  9.56batch/s][A
xclip videos:   5%|▌         | 91/1726 [00:10<02:53,  9.41batch/s][A
xclip videos:   5%|▌         | 92/1726 [00:10<02:55,  9.32batch/s][A
xclip videos:   5%|▌         | 93/1726 [00:10<02:55,  9.30batch/s][A
xclip videos:   5%|▌         | 94/1726 [00:10<02:57,  9.21batch/s][A
xclip videos:   6%|▌         | 95/1726 [00:10<03:01,  8.98batch/s][A
xclip videos:   6%|▌         | 97/1726 [00:10<02:48,  9.66batch/s][A
xclip videos:   6%|▌         | 99/1726 [00:10<02:48,  9.67batch/s][A
xclip videos:   6%|▌         | 100/1726 [00:10<02:46,  9.74batch/s]A
xclip videos:   6%|▌         | 101/1726 [00:11<02:47,  9.71batch/s]A
xclip videos:   6%|▌         | 102/1726 [00:11<02:48,  9.63batch/s]A
xclip videos:   6%|▌         | 103/1726 [00:11<02:49,  9.58batch/s]A
xclip videos:   6%|▌         | 105/1726 [00:11<02:47,  9.65batch/s]A
xclip videos:   6%|▌         | 106/1726 [00:11<02:47,  9.69batch/s]A
xclip videos:   6%|▌         | 107/1726 [00:11<02:49,  9.57batch/s]A
xclip videos:   6%|▋         | 108/1726 [00:11<02:51,  9.46batch/s]A
xclip videos:   6%|▋         | 109/1726 [00:11<02:48,  9.58batch/s]A
xclip videos:   6%|▋         | 111/1726 [00:12<02:47,  9.65batch/s]A
xclip videos:   6%|▋         | 112/1726 [00:12<02:53,  9.31batch/s]A
xclip videos:   7%|▋         | 113/1726 [00:12<02:56,  9.13batch/s]A
xclip videos:   7%|▋         | 115/1726 [00:12<02:58,  9.03batch/s]A
xclip videos:   7%|▋         | 116/1726 [00:12<02:57,  9.08batch/s]A
xclip videos:   7%|▋         | 117/1726 [00:12<02:55,  9.15batch/s]A
xclip videos:   7%|▋         | 118/1726 [00:12<02:55,  9.18batch/s]A
xclip videos:   7%|▋         | 119/1726 [00:13<02:56,  9.10batch/s]A
xclip videos:   7%|▋         | 120/1726 [00:13<02:53,  9.27batch/s]A
xclip videos:   7%|▋         | 122/1726 [00:13<02:44,  9.76batch/s]A
xclip videos:   7%|▋         | 123/1726 [00:13<02:47,  9.55batch/s]A
xclip videos:   7%|▋         | 124/1726 [00:13<02:48,  9.48batch/s]A
xclip videos:   7%|▋         | 126/1726 [00:13<02:54,  9.18batch/s]A
xclip videos:   7%|▋         | 127/1726 [00:13<02:57,  9.02batch/s]A
xclip videos:   7%|▋         | 129/1726 [00:14<02:54,  9.14batch/s]A
xclip videos:   8%|▊         | 130/1726 [00:14<02:59,  8.91batch/s]A
xclip videos:   8%|▊         | 132/1726 [00:14<02:57,  9.00batch/s]A
xclip videos:   8%|▊         | 133/1726 [00:14<02:55,  9.08batch/s]A
xclip videos:   8%|▊         | 134/1726 [00:14<02:55,  9.09batch/s]A
xclip videos:   8%|▊         | 136/1726 [00:14<02:52,  9.24batch/s]A
xclip videos:   8%|▊         | 137/1726 [00:14<02:51,  9.29batch/s]A
xclip videos:   8%|▊         | 138/1726 [00:15<02:50,  9.29batch/s]A
xclip videos:   8%|▊         | 139/1726 [00:15<02:49,  9.36batch/s]A
xclip videos:   8%|▊         | 140/1726 [00:15<02:47,  9.49batch/s]A
xclip videos:   8%|▊         | 142/1726 [00:15<02:48,  9.41batch/s]A
xclip videos:   8%|▊         | 143/1726 [00:15<02:50,  9.26batch/s]A
xclip videos:   8%|▊         | 144/1726 [00:15<02:50,  9.29batch/s]A
xclip videos:   8%|▊         | 145/1726 [00:15<02:49,  9.32batch/s]A
xclip videos:   8%|▊         | 146/1726 [00:15<02:53,  9.09batch/s]A
xclip videos:   9%|▊         | 148/1726 [00:16<02:44,  9.56batch/s]A
xclip videos:   9%|▊         | 150/1726 [00:16<02:43,  9.63batch/s]A
xclip videos:   9%|▊         | 151/1726 [00:16<02:45,  9.50batch/s]A
xclip videos:   9%|▉         | 152/1726 [00:16<02:46,  9.45batch/s]A
xclip videos:   9%|▉         | 153/1726 [00:16<02:48,  9.34batch/s]A
xclip videos:   9%|▉         | 155/1726 [00:16<02:48,  9.34batch/s]A
xclip videos:   9%|▉         | 156/1726 [00:16<02:46,  9.40batch/s]A
xclip videos:   9%|▉         | 157/1726 [00:17<02:44,  9.56batch/s]A
xclip videos:   9%|▉         | 158/1726 [00:17<02:45,  9.47batch/s]A
xclip videos:   9%|▉         | 159/1726 [00:17<02:52,  9.08batch/s]A
xclip videos:   9%|▉         | 161/1726 [00:17<02:45,  9.46batch/s]A
xclip videos:   9%|▉         | 162/1726 [00:17<02:53,  9.03batch/s]A
xclip videos:   9%|▉         | 163/1726 [00:17<02:58,  8.78batch/s]A
xclip videos:  10%|▉         | 165/1726 [00:17<02:49,  9.18batch/s]A
xclip videos:  10%|▉         | 167/1726 [00:18<02:53,  9.01batch/s]A
xclip videos:  10%|▉         | 168/1726 [00:18<02:57,  8.80batch/s]A
xclip videos:  10%|▉         | 169/1726 [00:18<03:01,  8.56batch/s]A
xclip videos:  10%|▉         | 171/1726 [00:18<02:58,  8.73batch/s]A
xclip videos:  10%|▉         | 172/1726 [00:18<02:57,  8.75batch/s]A
xclip videos:  10%|█         | 174/1726 [00:19<02:57,  8.73batch/s]A
xclip videos:  10%|█         | 176/1726 [00:19<02:51,  9.03batch/s]A
irra videos:  31%|███       | 307/995 [00:56<01:52,  6.12batch/s]
xclip videos:  10%|█         | 178/1726 [00:19<02:43,  9.47batch/s]A
xclip videos:  10%|█         | 179/1726 [00:19<02:43,  9.46batch/s]A
xclip videos:  10%|█         | 180/1726 [00:19<02:44,  9.39batch/s]A
xclip videos:  11%|█         | 182/1726 [00:19<02:45,  9.31batch/s]A
irra videos:  31%|███▏      | 312/995 [00:56<01:29,  7.61batch/s]
xclip videos:  11%|█         | 184/1726 [00:20<02:41,  9.56batch/s]A
xclip videos:  11%|█         | 186/1726 [00:20<02:41,  9.56batch/s]A
xclip videos:  11%|█         | 187/1726 [00:20<02:40,  9.57batch/s]A
irra videos:  32%|███▏      | 316/995 [00:57<01:29,  7.60batch/s]
xclip videos:  11%|█         | 189/1726 [00:20<02:37,  9.76batch/s]A
xclip videos:  11%|█         | 191/1726 [00:20<02:38,  9.66batch/s]A
irra videos:  32%|███▏      | 319/995 [00:57<01:32,  7.28batch/s]
xclip videos:  11%|█         | 193/1726 [00:20<02:35,  9.84batch/s]A
xclip videos:  11%|█         | 194/1726 [00:21<02:35,  9.87batch/s]A
xclip videos:  11%|█▏        | 196/1726 [00:21<02:34,  9.91batch/s]A
xclip videos:  11%|█▏        | 197/1726 [00:21<02:37,  9.70batch/s]A
xclip videos:  11%|█▏        | 198/1726 [00:21<02:39,  9.58batch/s]A
xclip videos:  12%|█▏        | 199/1726 [00:21<02:40,  9.52batch/s]A
xclip videos:  12%|█▏        | 201/1726 [00:21<02:38,  9.59batch/s]A
xclip videos:  12%|█▏        | 202/1726 [00:21<02:42,  9.35batch/s]A
xclip videos:  12%|█▏        | 203/1726 [00:22<02:50,  8.93batch/s]A
xclip videos:  12%|█▏        | 205/1726 [00:22<02:40,  9.45batch/s]A
irra videos:  33%|███▎      | 330/995 [00:59<01:34,  7.00batch/s]
xclip videos:  12%|█▏        | 207/1726 [00:22<02:37,  9.65batch/s]A
xclip videos:  12%|█▏        | 209/1726 [00:22<02:37,  9.62batch/s]A
xclip videos:  12%|█▏        | 210/1726 [00:22<02:37,  9.63batch/s]A
xclip videos:  12%|█▏        | 211/1726 [00:22<02:36,  9.66batch/s]A
xclip videos:  12%|█▏        | 212/1726 [00:22<02:35,  9.72batch/s]A
xclip videos:  12%|█▏        | 214/1726 [00:23<02:36,  9.65batch/s]A
xclip videos:  12%|█▏        | 215/1726 [00:23<02:38,  9.55batch/s]A
xclip videos:  13%|█▎        | 216/1726 [00:23<02:38,  9.51batch/s]A
xclip videos:  13%|█▎        | 217/1726 [00:23<02:39,  9.45batch/s]A
xclip videos:  13%|█▎        | 218/1726 [00:23<02:37,  9.56batch/s]A
xclip videos:  13%|█▎        | 220/1726 [00:23<02:45,  9.07batch/s]A
xclip videos:  13%|█▎        | 221/1726 [00:23<02:49,  8.90batch/s]A
xclip videos:  13%|█▎        | 223/1726 [00:24<02:49,  8.85batch/s]A
xclip videos:  13%|█▎        | 224/1726 [00:24<02:54,  8.62batch/s]A
xclip videos:  13%|█▎        | 226/1726 [00:24<02:55,  8.54batch/s]A
xclip videos:  13%|█▎        | 227/1726 [00:24<02:54,  8.59batch/s]A
xclip videos:  13%|█▎        | 229/1726 [00:24<02:51,  8.71batch/s]A
xclip videos:  13%|█▎        | 230/1726 [00:24<02:53,  8.63batch/s]A
xclip videos:  13%|█▎        | 231/1726 [00:25<02:50,  8.79batch/s]A
xclip videos:  13%|█▎        | 232/1726 [00:25<02:46,  8.99batch/s]A
xclip videos:  14%|█▎        | 234/1726 [00:25<02:41,  9.25batch/s]A
xclip videos:  14%|█▎        | 235/1726 [00:25<02:41,  9.22batch/s]A
xclip videos:  14%|█▎        | 237/1726 [00:25<02:46,  8.93batch/s]A
xclip videos:  14%|█▍        | 238/1726 [00:25<02:51,  8.70batch/s]A
xclip videos:  14%|█▍        | 239/1726 [00:26<02:54,  8.51batch/s]A
xclip videos:  14%|█▍        | 241/1726 [00:26<02:47,  8.86batch/s]A
xclip videos:  14%|█▍        | 242/1726 [00:26<02:54,  8.49batch/s]A
xclip videos:  14%|█▍        | 243/1726 [00:26<03:12,  7.71batch/s]A
xclip videos:  14%|█▍        | 244/1726 [00:26<03:17,  7.51batch/s]A
xclip videos:  14%|█▍        | 245/1726 [00:26<03:14,  7.60batch/s]A
xclip videos:  14%|█▍        | 247/1726 [00:27<02:59,  8.25batch/s]A
xclip videos:  14%|█▍        | 248/1726 [00:27<02:53,  8.50batch/s]A
xclip videos:  14%|█▍        | 249/1726 [00:27<02:46,  8.89batch/s]A
xclip videos:  14%|█▍        | 250/1726 [00:27<02:44,  8.96batch/s]A
xclip videos:  15%|█▍        | 251/1726 [00:27<02:41,  9.13batch/s]A
xclip videos:  15%|█▍        | 253/1726 [00:27<02:37,  9.35batch/s]A
xclip videos:  15%|█▍        | 254/1726 [00:27<02:37,  9.32batch/s]A
xclip videos:  15%|█▍        | 255/1726 [00:27<02:35,  9.46batch/s]A
xclip videos:  15%|█▍        | 256/1726 [00:27<02:35,  9.48batch/s]A
xclip videos:  15%|█▍        | 258/1726 [00:28<02:32,  9.65batch/s]A
irra videos:  37%|███▋      | 371/995 [01:05<01:24,  7.38batch/s]
xclip videos:  15%|█▌        | 261/1726 [00:28<02:28,  9.85batch/s]A
xclip videos:  15%|█▌        | 262/1726 [00:28<02:28,  9.83batch/s]A
xclip videos:  15%|█▌        | 263/1726 [00:28<02:30,  9.70batch/s]A
xclip videos:  15%|█▌        | 264/1726 [00:28<02:32,  9.57batch/s]A
xclip videos:  15%|█▌        | 265/1726 [00:28<02:37,  9.30batch/s]A
xclip videos:  15%|█▌        | 267/1726 [00:29<02:49,  8.61batch/s]A
xclip videos:  16%|█▌        | 268/1726 [00:29<02:46,  8.76batch/s]A
xclip videos:  16%|█▌        | 269/1726 [00:29<02:44,  8.88batch/s]A
xclip videos:  16%|█▌        | 270/1726 [00:29<02:42,  8.97batch/s]A
xclip videos:  16%|█▌        | 272/1726 [00:29<02:40,  9.06batch/s]A
xclip videos:  16%|█▌        | 273/1726 [00:29<02:39,  9.11batch/s]A
xclip videos:  16%|█▌        | 274/1726 [00:29<02:38,  9.17batch/s]A
xclip videos:  16%|█▌        | 276/1726 [00:30<02:44,  8.82batch/s]A
xclip videos:  16%|█▌        | 277/1726 [00:30<02:48,  8.59batch/s]A
xclip videos:  16%|█▌        | 279/1726 [00:30<02:42,  8.89batch/s]A
xclip videos:  16%|█▌        | 280/1726 [00:30<02:40,  9.02batch/s]A
xclip videos:  16%|█▋        | 281/1726 [00:30<02:37,  9.16batch/s]A
xclip videos:  16%|█▋        | 282/1726 [00:30<02:38,  9.11batch/s]A
xclip videos:  16%|█▋        | 284/1726 [00:31<02:30,  9.57batch/s]A
xclip videos:  17%|█▋        | 285/1726 [00:31<02:36,  9.22batch/s]A
xclip videos:  17%|█▋        | 287/1726 [00:31<02:35,  9.27batch/s]A
xclip videos:  17%|█▋        | 288/1726 [00:31<02:45,  8.67batch/s]A
xclip videos:  17%|█▋        | 289/1726 [00:31<02:51,  8.40batch/s]A
xclip videos:  17%|█▋        | 290/1726 [00:31<02:48,  8.51batch/s]A
xclip videos:  17%|█▋        | 291/1726 [00:31<02:48,  8.54batch/s]A
xclip videos:  17%|█▋        | 293/1726 [00:32<02:49,  8.47batch/s]A
xclip videos:  17%|█▋        | 294/1726 [00:32<02:47,  8.57batch/s]A
xclip videos:  17%|█▋        | 295/1726 [00:32<02:41,  8.85batch/s]A
xclip videos:  17%|█▋        | 296/1726 [00:32<02:41,  8.85batch/s]A
xclip videos:  17%|█▋        | 298/1726 [00:32<02:34,  9.27batch/s]A
irra videos:  40%|████      | 402/995 [01:09<01:21,  7.28batch/s]
xclip videos:  17%|█▋        | 300/1726 [00:32<02:29,  9.56batch/s]A
xclip videos:  17%|█▋        | 302/1726 [00:33<02:30,  9.45batch/s]A
xclip videos:  18%|█▊        | 303/1726 [00:33<02:30,  9.44batch/s]A
xclip videos:  18%|█▊        | 304/1726 [00:33<02:31,  9.38batch/s]A
xclip videos:  18%|█▊        | 305/1726 [00:33<02:31,  9.35batch/s]A
xclip videos:  18%|█▊        | 307/1726 [00:33<02:31,  9.36batch/s]A
xclip videos:  18%|█▊        | 308/1726 [00:33<02:33,  9.22batch/s]A
xclip videos:  18%|█▊        | 310/1726 [00:33<02:40,  8.83batch/s]A
xclip videos:  18%|█▊        | 311/1726 [00:34<02:40,  8.80batch/s]A
xclip videos:  18%|█▊        | 313/1726 [00:34<02:45,  8.53batch/s]A
xclip videos:  18%|█▊        | 314/1726 [00:34<02:44,  8.60batch/s]A
xclip videos:  18%|█▊        | 316/1726 [00:34<02:45,  8.52batch/s]A
xclip videos:  18%|█▊        | 317/1726 [00:34<02:48,  8.35batch/s]A
xclip videos:  18%|█▊        | 318/1726 [00:34<02:44,  8.54batch/s]A
xclip videos:  19%|█▊        | 320/1726 [00:35<02:32,  9.20batch/s]A
xclip videos:  19%|█▊        | 321/1726 [00:35<02:31,  9.25batch/s]A
xclip videos:  19%|█▊        | 322/1726 [00:35<02:30,  9.32batch/s]A
xclip videos:  19%|█▉        | 324/1726 [00:35<02:28,  9.42batch/s]A
xclip videos:  19%|█▉        | 325/1726 [00:35<02:31,  9.25batch/s]A
xclip videos:  19%|█▉        | 326/1726 [00:35<02:29,  9.37batch/s]A
xclip videos:  19%|█▉        | 327/1726 [00:35<02:29,  9.34batch/s]A
xclip videos:  19%|█▉        | 328/1726 [00:35<02:28,  9.41batch/s]A
xclip videos:  19%|█▉        | 330/1726 [00:36<02:36,  8.93batch/s]A
xclip videos:  19%|█▉        | 331/1726 [00:36<02:35,  8.96batch/s]A
xclip videos:  19%|█▉        | 332/1726 [00:36<02:31,  9.18batch/s]A
xclip videos:  19%|█▉        | 334/1726 [00:36<02:31,  9.16batch/s]A
xclip videos:  19%|█▉        | 335/1726 [00:36<02:35,  8.94batch/s]A
xclip videos:  20%|█▉        | 337/1726 [00:36<02:41,  8.58batch/s]A
xclip videos:  20%|█▉        | 338/1726 [00:37<02:38,  8.76batch/s]A
xclip videos:  20%|█▉        | 339/1726 [00:37<02:34,  9.00batch/s]A
xclip videos:  20%|█▉        | 341/1726 [00:37<02:38,  8.75batch/s]A
xclip videos:  20%|█▉        | 342/1726 [00:37<02:44,  8.42batch/s]A
xclip videos:  20%|█▉        | 344/1726 [00:37<02:40,  8.59batch/s]A
xclip videos:  20%|█▉        | 345/1726 [00:37<02:39,  8.66batch/s]A
xclip videos:  20%|██        | 347/1726 [00:38<02:37,  8.76batch/s]A
xclip videos:  20%|██        | 348/1726 [00:38<02:36,  8.81batch/s]A
xclip videos:  20%|██        | 349/1726 [00:38<02:38,  8.66batch/s]A
xclip videos:  20%|██        | 351/1726 [00:38<02:40,  8.56batch/s]A
xclip videos:  20%|██        | 352/1726 [00:38<02:49,  8.10batch/s]A
xclip videos:  20%|██        | 353/1726 [00:38<02:48,  8.16batch/s]A
xclip videos:  21%|██        | 355/1726 [00:39<02:40,  8.54batch/s]A
xclip videos:  21%|██        | 357/1726 [00:39<02:33,  8.92batch/s]A
xclip videos:  21%|██        | 358/1726 [00:39<02:30,  9.11batch/s]A
xclip videos:  21%|██        | 359/1726 [00:39<02:26,  9.30batch/s]A
xclip videos:  21%|██        | 360/1726 [00:39<02:25,  9.39batch/s]A
xclip videos:  21%|██        | 362/1726 [00:39<02:20,  9.70batch/s]A
xclip videos:  21%|██        | 363/1726 [00:39<02:23,  9.49batch/s]A
xclip videos:  21%|██        | 364/1726 [00:39<02:24,  9.44batch/s]A
xclip videos:  21%|██        | 366/1726 [00:40<02:24,  9.38batch/s]A
xclip videos:  21%|██▏       | 367/1726 [00:40<02:25,  9.35batch/s]A
xclip videos:  21%|██▏       | 368/1726 [00:40<02:24,  9.43batch/s]A
xclip videos:  21%|██▏       | 369/1726 [00:40<02:21,  9.57batch/s]A
xclip videos:  21%|██▏       | 370/1726 [00:40<02:21,  9.56batch/s]A
xclip videos:  22%|██▏       | 372/1726 [00:40<02:22,  9.50batch/s]A
xclip videos:  22%|██▏       | 373/1726 [00:40<02:21,  9.56batch/s]A
xclip videos:  22%|██▏       | 374/1726 [00:41<02:21,  9.58batch/s]A
xclip videos:  22%|██▏       | 376/1726 [00:41<02:28,  9.07batch/s]A
irra videos:  46%|████▌     | 460/995 [01:18<01:17,  6.86batch/s]

-- mean: R1 13.60  mAP 23.75
-- mean_s8: R1 13.60  mAP 23.75
-- max: R1 13.30  mAP 23.49
-- query_max: R1 13.50  mAP 23.87
== IRRA | activitynet/sentence | vt_1fps_n12

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:  63%|██████▎   | 1084/1726 [02:02<03:34,  3.00batch/s]

Window encode: 1000 tracklets, 1989 clips (window=8 stride=4 fps=1 max=12)

xclip videos:  63%|██████▎   | 1085/1726 [02:03<03:05,  3.46batch/s]
xclip videos:  63%|██████▎   | 1086/1726 [02:03<02:36,  4.08batch/s]
xclip videos:  63%|██████▎   | 1087/1726 [02:03<02:14,  4.75batch/s]
irra texts:   6%|▌         | 13/227 [00:00<00:06, 33.85batch/s]
xclip videos:  63%|██████▎   | 1088/1726 [02:03<02:00,  5.29batch/s]
xclip videos:  63%|██████▎   | 1089/1726 [02:03<01:49,  5.84batch/s]
xclip videos:  63%|██████▎   | 1091/1726 [02:03<01:26,  7.30batch/s]
irra texts:  14%|█▎        | 31/227 [00:00<00:05, 38.68batch/s]
xclip videos:  63%|██████▎   | 1093/1726 [02:04<01:18,  8.04batch/s]
xclip videos:  63%|██████▎   | 1094/1726 [02:04<01:18,  8.00batch/s]
xclip videos:  63%|██████▎   | 1095/1726 [02:04<01:20,  7.87batch/s]
xclip videos:  63%|██████▎   | 1096/1726 [02:04<01:19,  7.96batch/s]
xclip videos:  64%|██████▎   | 1097/1726 [02:04<01:18,  8.04batch/s]
xclip videos:  64%|██████▎   | 1098/1726 [02:04<01:15,  8.29batch/s]
xclip videos:  64%|██████▎   | 1099/1726 [02:04<01:14,  8.41batch/s]
xclip videos:  64%|██████▎   | 1100/1726 [02:04<01:13,  8.46batch/s]
xclip videos:  64%|██████▍   | 1101/1726 [02:04<01:12,  8.67batch/s]
xclip videos:  64%|██████▍   | 1102/1726 [02:05<01:12,  8.59batch/s]
xclip videos:  64%|██████▍   | 1103/1726 [02:05<01:11,  8.72batch/s]
xclip videos:  64%|██████▍   | 1104/1726 [02:05<01:12,  8.61batch/s]
xclip videos:  64%|██████▍   | 1105/1726 [02:05<01:12,  8.55batch/s]
xclip videos:  64%|██████▍   | 1106/1726 [02:05<01:12,  8.59batch/s]
xclip videos:  64%|██████▍   | 1107/1726 [02:05<01:15,  8.24batch/s]
xclip videos:  64%|██████▍   | 1108/1726 [02:05<01:14,  8.32batch/s]
xclip videos:  64%|██████▍   | 1109/1726 [02:05<01:14,  8.33batch/s]
xclip videos:  64%|██████▍   | 1110/1726 [02:06<01:15,  8.21batch/s]
xclip videos:  64%|██████▍   | 1111/1726 [02:06<01:12,  8.46batch/s]
xclip videos:  64%|██████▍   | 1112/1726 [02:06<01:17,  7.97batch/s]
xclip videos:  64%|██████▍   | 1113/1726 [02:06<01:18,  7.77batch/s]
xclip videos:  65%|██████▍   | 1114/1726 [02:06<01:21,  7.49batch/s]
irra texts:  67%|██████▋   | 153/227 [00:03<00:01, 41.85batch/s]
xclip videos:  65%|██████▍   | 1116/1726 [02:06<01:23,  7.31batch/s]
xclip videos:  65%|██████▍   | 1117/1726 [02:07<01:25,  7.14batch/s]
xclip videos:  65%|██████▍   | 1118/1726 [02:07<01:23,  7.29batch/s]
irra texts:  77%|███████▋  | 174/227 [00:04<00:01, 37.71batch/s]
xclip videos:  65%|██████▍   | 1119/1726 [02:07<01:21,  7.48batch/s]
xclip videos:  65%|██████▍   | 1120/1726 [02:07<01:22,  7.37batch/s]
xclip videos:  65%|██████▍   | 1121/1726 [02:07<01:20,  7.47batch/s]
xclip videos:  65%|██████▌   | 1122/1726 [02:07<01:21,  7.42batch/s]
xclip videos:  65%|██████▌   | 1123/1726 [02:07<01:21,  7.40batch/s]
xclip videos:  65%|██████▌   | 1124/1726 [02:07<01:20,  7.44batch/s]
irra texts:  90%|█████████ | 205/227 [00:05<00:00, 37.94batch/s]
xclip videos:  65%|██████▌   | 1125/1726 [02:08<01:18,  7.65batch/s]
xclip videos:  65%|██████▌   | 1126/1726 [02:08<01:17,  7.79batch/s]
xclip videos:  65%|██████▌   | 1127/1726 [02:08<01:18,  7.58batch/s]
irra texts: 100%|██████████| 227/227 [00:05<00:00, 41.08batch/s]h/s]
xclip videos:  68%|██████▊   | 1176/1726 [02:23<04:30,  2.03batch/s]

-- mean: R1 6.47  mAP 12.88
-- mean_s8: R1 6.47  mAP 12.88
-- max: R1 6.22  mAP 12.65
-- query_max: R1 6.61  mAP 13.21
== IRRA | activitynet/paragraph | vt_2fps_n32

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos:  68%|██████▊   | 1178/1726 [02:24<05:00,  1.82batch/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

xclip videos:  68%|██████▊   | 1179/1726 [02:24<04:22,  2.08batch/s]
xclip videos:  68%|██████▊   | 1180/1726 [02:24<03:22,  2.69batch/s]
xclip videos:  68%|██████▊   | 1182/1726 [02:24<02:09,  4.21batch/s]
xclip videos:  69%|██████▊   | 1183/1726 [02:24<01:48,  5.02batch/s]
xclip videos:  69%|██████▊   | 1184/1726 [02:25<01:33,  5.82batch/s]
xclip videos:  69%|██████▊   | 1185/1726 [02:25<01:25,  6.29batch/s]
xclip videos:  69%|██████▉   | 1187/1726 [02:25<01:16,  7.01batch/s]
xclip videos:  69%|██████▉   | 1188/1726 [02:25<01:16,  7.06batch/s]
xclip videos:  69%|██████▉   | 1189/1726 [02:25<01:15,  7.10batch/s]
xclip videos:  69%|██████▉   | 1190/1726 [02:25<01:15,  7.08batch/s]
xclip videos:  69%|██████▉   | 1191/1726 [02:26<01:14,  7.20batch/s]
xclip videos:  69%|██████▉   | 1193/1726 [02:26<01:09,  7.66batch/s]
xclip videos:  69%|██████▉   | 1194/1726 [02:26<01:11,  7.49batch/s]
xclip videos:  69%|██████▉   | 1195/1726 [02:26<01:09,  7.69batch/s]
xclip videos:  69%|██████▉   | 1196/1726 [02:26<01:07,  7.86batch/s]
xclip videos:  69%|██████▉   | 1198/1726 [02:26<01:04,  8.14batch/s]
xclip videos:  69%|██████▉   | 1199/1726 [02:27<01:06,  7.92batch/s]
xclip videos:  70%|██████▉   | 1200/1726 [02:27<01:06,  7.87batch/s]
xclip videos:  70%|██████▉   | 1201/1726 [02:27<01:05,  8.02batch/s]
xclip videos:  70%|██████▉   | 1202/1726 [02:27<01:02,  8.35batch/s]
xclip videos:  70%|██████▉   | 1203/1726 [02:27<01:00,  8.62batch/s]
xclip videos:  70%|██████▉   | 1204/1726 [02:27<01:00,  8.63batch/s]
xclip videos:  70%|██████▉   | 1205/1726 [02:27<00:59,  8.83batch/s]
xclip videos:  70%|██████▉   | 1207/1726 [02:27<00:56,  9.26batch/s]
xclip videos:  70%|██████▉   | 1208/1726 [02:28<00:55,  9.38batch/s]
xclip videos:  70%|███████   | 1209/1726 [02:28<00:55,  9.23batch/s]
xclip videos:  70%|███████   | 1211/1726 [02:28<00:57,  8.97batch/s]
xclip videos:  70%|███████   | 1212/1726 [02:28<00:57,  8.88batch/s]
xclip videos:  70%|███████   | 1214/1726 [02:28<00:57,  8.92batch/s]
xclip videos:  70%|███████   | 1215/1726 [02:28<00:58,  8.76batch/s]
xclip videos:  71%|███████   | 1217/1726 [02:29<00:59,  8.57batch/s]
xclip videos:  71%|███████   | 1218/1726 [02:29<00:57,  8.91batch/s]
xclip videos:  71%|███████   | 1219/1726 [02:29<00:55,  9.06batch/s]
xclip videos:  71%|███████   | 1220/1726 [02:29<00:54,  9.31batch/s]
xclip videos:  71%|███████   | 1222/1726 [02:29<00:54,  9.22batch/s]
xclip videos:  71%|███████   | 1223/1726 [02:29<00:56,  8.96batch/s]
xclip videos:  71%|███████   | 1224/1726 [02:29<00:56,  8.86batch/s]
xclip videos:  71%|███████   | 1226/1726 [02:30<00:55,  9.08batch/s]
xclip videos:  71%|███████   | 1227/1726 [02:30<00:55,  9.03batch/s]
xclip videos:  71%|███████   | 1228/1726 [02:30<00:54,  9.08batch/s]
xclip videos:  71%|███████   | 1229/1726 [02:30<00:53,  9.24batch/s]
xclip videos:  71%|███████▏  | 1231/1726 [02:30<00:54,  9.00batch/s]
xclip videos:  71%|███████▏  | 1232/1726 [02:30<00:55,  8.96batch/s]
xclip videos:  71%|███████▏  | 1234/1726 [02:30<00:54,  8.95batch/s]
xclip videos:  72%|███████▏  | 1235/1726 [02:31<00:56,  8.64batch/s]
xclip videos:  72%|███████▏  | 1236/1726 [02:31<00:59,  8.26batch/s]
xclip videos:  72%|███████▏  | 1237/1726 [02:31<00:57,  8.45batch/s]
xclip videos:  72%|███████▏  | 1238/1726 [02:31<00:56,  8.65batch/s]
xclip videos:  72%|███████▏  | 1239/1726 [02:31<00:54,  8.85batch/s]
xclip videos:  72%|███████▏  | 1241/1726 [02:31<00:56,  8.52batch/s]
xclip videos:  72%|███████▏  | 1242/1726 [02:31<01:00,  8.01batch/s]
xclip videos:  72%|███████▏  | 1243/1726 [02:32<00:59,  8.18batch/s]
xclip videos:  72%|███████▏  | 1245/1726 [02:32<00:58,  8.19batch/s]
xclip videos:  72%|███████▏  | 1246/1726 [02:32<00:59,  8.05batch/s]
xclip videos:  72%|███████▏  | 1247/1726 [02:32<00:59,  8.01batch/s]
xclip videos:  72%|███████▏  | 1249/1726 [02:32<00:57,  8.36batch/s]
xclip videos:  72%|███████▏  | 1250/1726 [02:32<00:54,  8.74batch/s]
xclip videos:  72%|███████▏  | 1251/1726 [02:32<00:55,  8.63batch/s]
xclip videos:  73%|███████▎  | 1252/1726 [02:33<00:54,  8.77batch/s]
xclip videos:  73%|███████▎  | 1253/1726 [02:33<00:55,  8.49batch/s]
xclip videos:  73%|███████▎  | 1254/1726 [02:33<00:57,  8.21batch/s]
xclip videos:  73%|███████▎  | 1256/1726 [02:33<00:53,  8.73batch/s]
xclip videos:  73%|███████▎  | 1257/1726 [02:33<00:53,  8.73batch/s]
xclip videos:  73%|███████▎  | 1258/1726 [02:33<00:57,  8.13batch/s]
xclip videos:  73%|███████▎  | 1260/1726 [02:34<00:57,  8.12batch/s]
xclip videos:  73%|███████▎  | 1261/1726 [02:34<00:56,  8.26batch/s]
xclip videos:  73%|███████▎  | 1262/1726 [02:34<00:53,  8.62batch/s]
xclip videos:  73%|███████▎  | 1264/1726 [02:34<00:56,  8.16batch/s]
xclip videos:  73%|███████▎  | 1265/1726 [02:34<00:59,  7.74batch/s]
xclip videos:  73%|███████▎  | 1266/1726 [02:34<00:59,  7.68batch/s]
xclip videos:  73%|███████▎  | 1268/1726 [02:35<00:56,  8.16batch/s]
xclip videos:  74%|███████▎  | 1269/1726 [02:35<00:56,  8.07batch/s]
xclip videos:  74%|███████▎  | 1270/1726 [02:35<00:54,  8.37batch/s]
xclip videos:  74%|███████▎  | 1272/1726 [02:35<00:50,  8.90batch/s]
xclip videos:  74%|███████▍  | 1273/1726 [02:35<00:52,  8.68batch/s]
xclip videos:  74%|███████▍  | 1274/1726 [02:35<00:50,  8.97batch/s]
xclip videos:  74%|███████▍  | 1276/1726 [02:35<00:48,  9.24batch/s]
xclip videos:  74%|███████▍  | 1277/1726 [02:36<00:48,  9.31batch/s]
xclip videos:  74%|███████▍  | 1278/1726 [02:36<00:48,  9.26batch/s]
xclip videos:  74%|███████▍  | 1280/1726 [02:36<00:50,  8.88batch/s]
xclip videos:  74%|███████▍  | 1281/1726 [02:36<00:51,  8.68batch/s]
xclip videos:  74%|███████▍  | 1282/1726 [02:36<00:51,  8.58batch/s]
xclip videos:  74%|███████▍  | 1283/1726 [02:36<00:50,  8.74batch/s]
xclip videos:  74%|███████▍  | 1284/1726 [02:36<00:50,  8.78batch/s]
xclip videos:  74%|███████▍  | 1285/1726 [02:36<00:49,  8.92batch/s]
xclip videos:  75%|███████▍  | 1287/1726 [02:37<00:48,  8.96batch/s]
xclip videos:  75%|███████▍  | 1288/1726 [02:37<00:48,  9.01batch/s]
xclip videos:  75%|███████▍  | 1290/1726 [02:37<00:47,  9.12batch/s]
xclip videos:  75%|███████▍  | 1291/1726 [02:37<00:46,  9.31batch/s]
xclip videos:  75%|███████▍  | 1292/1726 [02:37<00:45,  9.45batch/s]
xclip videos:  75%|███████▍  | 1294/1726 [02:37<00:47,  9.16batch/s]
xclip videos:  75%|███████▌  | 1295/1726 [02:38<00:47,  9.12batch/s]
xclip videos:  75%|███████▌  | 1296/1726 [02:38<00:46,  9.17batch/s]
xclip videos:  75%|███████▌  | 1297/1726 [02:38<00:46,  9.17batch/s]
xclip videos:  75%|███████▌  | 1298/1726 [02:38<00:47,  9.08batch/s]
xclip videos:  75%|███████▌  | 1300/1726 [02:38<00:46,  9.20batch/s]
xclip videos:  75%|███████▌  | 1301/1726 [02:38<00:47,  8.93batch/s]
xclip videos:  75%|███████▌  | 1302/1726 [02:38<00:47,  8.90batch/s]
xclip videos:  76%|███████▌  | 1304/1726 [02:39<00:48,  8.66batch/s]
xclip videos:  76%|███████▌  | 1305/1726 [02:39<00:47,  8.86batch/s]
xclip videos:  76%|███████▌  | 1306/1726 [02:39<00:46,  9.05batch/s]A
xclip videos:  76%|███████▌  | 1307/1726 [02:39<00:45,  9.12batch/s]A
xclip videos:  76%|███████▌  | 1308/1726 [02:39<00:45,  9.09batch/s]A
xclip videos:  76%|███████▌  | 1309/1726 [02:39<00:46,  9.02batch/s]A
xclip videos:  76%|███████▌  | 1310/1726 [02:39<00:46,  8.97batch/s]A
xclip videos:  76%|███████▌  | 1312/1726 [02:39<00:44,  9.40batch/s]A
xclip videos:  76%|███████▌  | 1314/1726 [02:40<00:44,  9.26batch/s]A
xclip videos:  76%|███████▌  | 1315/1726 [02:40<00:45,  9.03batch/s]A
xclip videos:  76%|███████▋  | 1317/1726 [02:40<00:46,  8.89batch/s]A
irra videos:   3%|▎         | 109/3451 [00:16<08:52,  6.28batch/s]
xclip videos:  76%|███████▋  | 1319/1726 [02:40<00:43,  9.44batch/s]A
xclip videos:  76%|███████▋  | 1320/1726 [02:40<00:43,  9.41batch/s]A
xclip videos:  77%|███████▋  | 1322/1726 [02:40<00:41,  9.64batch/s]A
xclip videos:  77%|███████▋  | 1323/1726 [02:41<00:41,  9.70batch/s]A
xclip videos:  77%|███████▋  | 1325/1726 [02:41<00:41,  9.62batch/s]A
xclip videos:  77%|███████▋  | 1326/1726 [02:41<00:42,  9.40batch/s]A
xclip videos:  77%|███████▋  | 1327/1726 [02:41<00:42,  9.37batch/s]A
xclip videos:  77%|███████▋  | 1328/1726 [02:41<00:43,  9.16batch/s]A
xclip videos:  77%|███████▋  | 1330/1726 [02:41<00:44,  8.87batch/s]A
xclip videos:  77%|███████▋  | 1331/1726 [02:41<00:44,  8.90batch/s]A
xclip videos:  77%|███████▋  | 1332/1726 [02:42<00:45,  8.69batch/s]A
xclip videos:  77%|███████▋  | 1333/1726 [02:42<00:45,  8.57batch/s]A
xclip videos:  77%|███████▋  | 1335/1726 [02:42<00:44,  8.82batch/s]A
xclip videos:  77%|███████▋  | 1336/1726 [02:42<00:43,  8.88batch/s]A
xclip videos:  77%|███████▋  | 1337/1726 [02:42<00:43,  8.98batch/s]A
xclip videos:  78%|███████▊  | 1338/1726 [02:42<00:44,  8.64batch/s]A
xclip videos:  78%|███████▊  | 1340/1726 [02:43<00:44,  8.72batch/s]A
xclip videos:  78%|███████▊  | 1341/1726 [02:43<00:42,  9.01batch/s]A
irra videos:   4%|▎         | 128/3451 [00:18<07:47,  7.11batch/s]
xclip videos:  78%|███████▊  | 1343/1726 [02:43<00:41,  9.28batch/s]A
xclip videos:  78%|███████▊  | 1344/1726 [02:43<00:42,  8.91batch/s]A
xclip videos:  78%|███████▊  | 1346/1726 [02:43<00:40,  9.28batch/s]A
xclip videos:  78%|███████▊  | 1347/1726 [02:43<00:40,  9.37batch/s]A
xclip videos:  78%|███████▊  | 1349/1726 [02:43<00:40,  9.29batch/s]A
xclip videos:  78%|███████▊  | 1350/1726 [02:44<00:41,  9.02batch/s]A
xclip videos:  78%|███████▊  | 1352/1726 [02:44<00:42,  8.76batch/s]A
xclip videos:  78%|███████▊  | 1353/1726 [02:44<00:42,  8.75batch/s]A
xclip videos:  79%|███████▊  | 1355/1726 [02:44<00:42,  8.79batch/s]A
xclip videos:  79%|███████▊  | 1357/1726 [02:44<00:41,  8.83batch/s]A
xclip videos:  79%|███████▊  | 1358/1726 [02:45<00:40,  9.00batch/s]A
xclip videos:  79%|███████▊  | 1359/1726 [02:45<00:39,  9.27batch/s]A
xclip videos:  79%|███████▉  | 1360/1726 [02:45<00:42,  8.59batch/s]A
xclip videos:  79%|███████▉  | 1361/1726 [02:45<00:43,  8.35batch/s]A
xclip videos:  79%|███████▉  | 1362/1726 [02:45<00:43,  8.39batch/s]A
xclip videos:  79%|███████▉  | 1364/1726 [02:45<00:41,  8.76batch/s]A
xclip videos:  79%|███████▉  | 1365/1726 [02:45<00:41,  8.74batch/s]A
xclip videos:  79%|███████▉  | 1367/1726 [02:46<00:40,  8.95batch/s]A
xclip videos:  79%|███████▉  | 1368/1726 [02:46<00:39,  9.13batch/s]A
xclip videos:  79%|███████▉  | 1369/1726 [02:46<00:38,  9.30batch/s]A
xclip videos:  79%|███████▉  | 1370/1726 [02:46<00:37,  9.45batch/s]A
xclip videos:  79%|███████▉  | 1372/1726 [02:46<00:36,  9.70batch/s]A
xclip videos:  80%|███████▉  | 1373/1726 [02:46<00:36,  9.60batch/s]A
xclip videos:  80%|███████▉  | 1375/1726 [02:46<00:38,  9.16batch/s]A
xclip videos:  80%|███████▉  | 1376/1726 [02:46<00:37,  9.27batch/s]A
xclip videos:  80%|███████▉  | 1377/1726 [02:47<00:37,  9.32batch/s]A
xclip videos:  80%|███████▉  | 1379/1726 [02:47<00:36,  9.40batch/s]A
xclip videos:  80%|███████▉  | 1380/1726 [02:47<00:37,  9.18batch/s]A
xclip videos:  80%|████████  | 1381/1726 [02:47<00:38,  8.94batch/s]A
xclip videos:  80%|████████  | 1383/1726 [02:47<00:36,  9.27batch/s]A
xclip videos:  80%|████████  | 1385/1726 [02:47<00:37,  9.00batch/s]A
xclip videos:  80%|████████  | 1386/1726 [02:48<00:38,  8.88batch/s]A
xclip videos:  80%|████████  | 1388/1726 [02:48<00:38,  8.88batch/s]A
xclip videos:  80%|████████  | 1389/1726 [02:48<00:37,  9.02batch/s]A
xclip videos:  81%|████████  | 1390/1726 [02:48<00:37,  9.00batch/s]A
xclip videos:  81%|████████  | 1391/1726 [02:48<00:37,  8.97batch/s]A
xclip videos:  81%|████████  | 1393/1726 [02:48<00:36,  9.13batch/s]A
xclip videos:  81%|████████  | 1394/1726 [02:49<00:40,  8.16batch/s]A
xclip videos:  81%|████████  | 1395/1726 [02:49<00:39,  8.48batch/s]A
xclip videos:  81%|████████  | 1396/1726 [02:49<00:37,  8.69batch/s]A
xclip videos:  81%|████████  | 1397/1726 [02:49<00:37,  8.71batch/s]A
xclip videos:  81%|████████  | 1398/1726 [02:49<00:37,  8.68batch/s]A
xclip videos:  81%|████████  | 1400/1726 [02:49<00:35,  9.13batch/s]A
xclip videos:  81%|████████  | 1401/1726 [02:49<00:35,  9.24batch/s]A
xclip videos:  81%|████████▏ | 1403/1726 [02:50<00:36,  8.85batch/s]A
xclip videos:  81%|████████▏ | 1404/1726 [02:50<00:40,  7.96batch/s]A
xclip videos:  81%|████████▏ | 1405/1726 [02:50<00:42,  7.59batch/s]A
irra videos:   5%|▌         | 176/3451 [00:25<07:48,  7.00batch/s]
xclip videos:  82%|████████▏ | 1407/1726 [02:50<00:41,  7.62batch/s]A
xclip videos:  82%|████████▏ | 1409/1726 [02:50<00:38,  8.24batch/s]A
xclip videos:  82%|████████▏ | 1410/1726 [02:50<00:37,  8.39batch/s]A
xclip videos:  82%|████████▏ | 1412/1726 [02:51<00:37,  8.36batch/s]A
xclip videos:  82%|████████▏ | 1413/1726 [02:51<00:37,  8.29batch/s]A
xclip videos:  82%|████████▏ | 1415/1726 [02:51<00:36,  8.42batch/s]A
xclip videos:  82%|████████▏ | 1416/1726 [02:51<00:36,  8.50batch/s]A
xclip videos:  82%|████████▏ | 1417/1726 [02:51<00:35,  8.80batch/s]A
xclip videos:  82%|████████▏ | 1419/1726 [02:51<00:35,  8.74batch/s]A
xclip videos:  82%|████████▏ | 1420/1726 [02:52<00:35,  8.61batch/s]A
xclip videos:  82%|████████▏ | 1422/1726 [02:52<00:33,  9.11batch/s]A
xclip videos:  82%|████████▏ | 1423/1726 [02:52<00:33,  9.16batch/s]A
xclip videos:  83%|████████▎ | 1424/1726 [02:52<00:32,  9.28batch/s]A
xclip videos:  83%|████████▎ | 1425/1726 [02:52<00:33,  9.08batch/s]A
xclip videos:  83%|████████▎ | 1427/1726 [02:52<00:34,  8.55batch/s]A
xclip videos:  83%|████████▎ | 1428/1726 [02:53<00:35,  8.44batch/s]A
xclip videos:  83%|████████▎ | 1430/1726 [02:53<00:34,  8.52batch/s]A
xclip videos:  83%|████████▎ | 1431/1726 [02:53<00:34,  8.58batch/s]A
xclip videos:  83%|████████▎ | 1432/1726 [02:53<00:33,  8.76batch/s]A
xclip videos:  83%|████████▎ | 1434/1726 [02:53<00:32,  8.97batch/s]A
xclip videos:  83%|████████▎ | 1435/1726 [02:53<00:32,  8.89batch/s]A
xclip videos:  83%|████████▎ | 1437/1726 [02:54<00:31,  9.15batch/s]A
xclip videos:  83%|████████▎ | 1438/1726 [02:54<00:30,  9.38batch/s]A
xclip videos:  83%|████████▎ | 1439/1726 [02:54<00:30,  9.50batch/s]A
xclip videos:  83%|████████▎ | 1441/1726 [02:54<00:29,  9.66batch/s]A
xclip videos:  84%|████████▎ | 1442/1726 [02:54<00:29,  9.56batch/s]A
xclip videos:  84%|████████▎ | 1443/1726 [02:54<00:29,  9.51batch/s]A
xclip videos:  84%|████████▎ | 1445/1726 [02:54<00:31,  8.97batch/s]A
xclip videos:  84%|████████▍ | 1446/1726 [02:54<00:31,  8.94batch/s]A
xclip videos:  84%|████████▍ | 1447/1726 [02:55<00:30,  9.15batch/s]A
xclip videos:  84%|████████▍ | 1449/1726 [02:55<00:30,  9.06batch/s]A
xclip videos:  84%|████████▍ | 1450/1726 [02:55<00:31,  8.82batch/s]A
xclip videos:  84%|████████▍ | 1452/1726 [02:55<00:31,  8.62batch/s]A
xclip videos:  84%|████████▍ | 1453/1726 [02:55<00:32,  8.45batch/s]A
xclip videos:  84%|████████▍ | 1455/1726 [02:56<00:30,  8.75batch/s]A
xclip videos:  84%|████████▍ | 1456/1726 [02:56<00:30,  8.84batch/s]A
xclip videos:  84%|████████▍ | 1457/1726 [02:56<00:29,  9.06batch/s]A
xclip videos:  85%|████████▍ | 1459/1726 [02:56<00:28,  9.31batch/s]A
xclip videos:  85%|████████▍ | 1460/1726 [02:56<00:28,  9.27batch/s]A
xclip videos:  85%|████████▍ | 1461/1726 [02:56<00:30,  8.81batch/s]A
xclip videos:  85%|████████▍ | 1463/1726 [02:56<00:31,  8.44batch/s]A
xclip videos:  85%|████████▍ | 1464/1726 [02:57<00:30,  8.51batch/s]A
xclip videos:  85%|████████▍ | 1465/1726 [02:57<00:30,  8.51batch/s]A
xclip videos:  85%|████████▍ | 1467/1726 [02:57<00:28,  9.03batch/s]A
xclip videos:  85%|████████▌ | 1468/1726 [02:57<00:29,  8.80batch/s]A
xclip videos:  85%|████████▌ | 1470/1726 [02:57<00:29,  8.56batch/s]A
xclip videos:  85%|████████▌ | 1471/1726 [02:57<00:31,  8.13batch/s]A
xclip videos:  85%|████████▌ | 1473/1726 [02:58<00:30,  8.33batch/s]A
xclip videos:  85%|████████▌ | 1474/1726 [02:58<00:30,  8.17batch/s]A
xclip videos:  85%|████████▌ | 1475/1726 [02:58<00:31,  8.09batch/s]A
xclip videos:  86%|████████▌ | 1476/1726 [02:58<00:30,  8.18batch/s]A
xclip videos:  86%|████████▌ | 1477/1726 [02:58<00:29,  8.39batch/s]A
xclip videos:  86%|████████▌ | 1479/1726 [02:58<00:28,  8.60batch/s]A
xclip videos:  86%|████████▌ | 1480/1726 [02:58<00:28,  8.66batch/s]A
xclip videos:  86%|████████▌ | 1482/1726 [02:59<00:29,  8.38batch/s]A
xclip videos:  86%|████████▌ | 1483/1726 [02:59<00:28,  8.40batch/s]A
xclip videos:  86%|████████▌ | 1485/1726 [02:59<00:27,  8.64batch/s]A
xclip videos:  86%|████████▌ | 1486/1726 [02:59<00:27,  8.84batch/s]A
xclip videos:  86%|████████▌ | 1487/1726 [02:59<00:26,  8.94batch/s]A
xclip videos:  86%|████████▌ | 1488/1726 [02:59<00:26,  9.04batch/s]A
xclip videos:  86%|████████▋ | 1490/1726 [03:00<00:25,  9.09batch/s]A
xclip videos:  86%|████████▋ | 1491/1726 [03:00<00:26,  8.99batch/s]A
xclip videos:  87%|████████▋ | 1493/1726 [03:00<00:27,  8.40batch/s]A
xclip videos:  87%|████████▋ | 1494/1726 [03:00<00:27,  8.34batch/s]A
xclip videos:  87%|████████▋ | 1495/1726 [03:00<00:27,  8.40batch/s]A
xclip videos:  87%|████████▋ | 1497/1726 [03:00<00:27,  8.36batch/s]A
xclip videos:  87%|████████▋ | 1498/1726 [03:01<00:27,  8.41batch/s]A
xclip videos:  87%|████████▋ | 1500/1726 [03:01<00:26,  8.49batch/s]A
xclip videos:  87%|████████▋ | 1501/1726 [03:01<00:27,  8.31batch/s]A
xclip videos:  87%|████████▋ | 1503/1726 [03:01<00:25,  8.59batch/s]A
xclip videos:  87%|████████▋ | 1504/1726 [03:01<00:25,  8.64batch/s]A
xclip videos:  87%|████████▋ | 1505/1726 [03:01<00:25,  8.65batch/s]A
xclip videos:  87%|████████▋ | 1507/1726 [03:02<00:24,  8.99batch/s]A
xclip videos:  87%|████████▋ | 1508/1726 [03:02<00:24,  8.99batch/s]A
xclip videos:  87%|████████▋ | 1509/1726 [03:02<00:24,  8.78batch/s]A
xclip videos:  87%|████████▋ | 1510/1726 [03:02<00:24,  8.76batch/s]A
xclip videos:  88%|████████▊ | 1512/1726 [03:02<00:22,  9.33batch/s]A
xclip videos:  88%|████████▊ | 1513/1726 [03:02<00:22,  9.34batch/s]A
xclip videos:  88%|████████▊ | 1514/1726 [03:02<00:22,  9.31batch/s]A
xclip videos:  88%|████████▊ | 1515/1726 [03:02<00:22,  9.31batch/s]A
xclip videos:  88%|████████▊ | 1516/1726 [03:03<00:22,  9.24batch/s]A
xclip videos:  88%|████████▊ | 1518/1726 [03:03<00:22,  9.25batch/s]A
xclip videos:  88%|████████▊ | 1519/1726 [03:03<00:22,  9.24batch/s]A
xclip videos:  88%|████████▊ | 1521/1726 [03:03<00:23,  8.89batch/s]A
xclip videos:  88%|████████▊ | 1522/1726 [03:03<00:23,  8.81batch/s]A
xclip videos:  88%|████████▊ | 1523/1726 [03:03<00:22,  9.02batch/s]A
xclip videos:  88%|████████▊ | 1524/1726 [03:03<00:22,  8.87batch/s]A
xclip videos:  88%|████████▊ | 1526/1726 [03:04<00:23,  8.47batch/s]A
xclip videos:  88%|████████▊ | 1527/1726 [03:04<00:23,  8.52batch/s]A
xclip videos:  89%|████████▊ | 1528/1726 [03:04<00:23,  8.51batch/s]A
xclip videos:  89%|████████▊ | 1529/1726 [03:04<00:25,  7.82batch/s]A
xclip videos:  89%|████████▊ | 1530/1726 [03:04<00:26,  7.42batch/s]A
xclip videos:  89%|████████▉ | 1532/1726 [03:04<00:24,  7.76batch/s]A
xclip videos:  89%|████████▉ | 1533/1726 [03:05<00:24,  7.89batch/s]A
xclip videos:  89%|████████▉ | 1535/1726 [03:05<00:24,  7.81batch/s]A
xclip videos:  89%|████████▉ | 1536/1726 [03:05<00:24,  7.83batch/s]A
xclip videos:  89%|████████▉ | 1538/1726 [03:05<00:22,  8.28batch/s]A
xclip videos:  89%|████████▉ | 1539/1726 [03:05<00:21,  8.59batch/s]A
xclip videos:  89%|████████▉ | 1540/1726 [03:05<00:21,  8.74batch/s]A
xclip videos:  89%|████████▉ | 1541/1726 [03:06<00:21,  8.77batch/s]A
xclip videos:  89%|████████▉ | 1542/1726 [03:06<00:20,  9.02batch/s]A
xclip videos:  89%|████████▉ | 1544/1726 [03:06<00:19,  9.29batch/s]A
xclip videos:  90%|████████▉ | 1545/1726 [03:06<00:19,  9.17batch/s]A
xclip videos:  90%|████████▉ | 1547/1726 [03:06<00:20,  8.95batch/s]A
xclip videos:  90%|████████▉ | 1548/1726 [03:06<00:19,  8.90batch/s]A
xclip videos:  90%|████████▉ | 1549/1726 [03:06<00:20,  8.82batch/s]A
xclip videos:  90%|████████▉ | 1551/1726 [03:07<00:20,  8.72batch/s]A
xclip videos:  90%|████████▉ | 1552/1726 [03:07<00:20,  8.62batch/s]A
xclip videos:  90%|████████▉ | 1553/1726 [03:07<00:20,  8.36batch/s]A
xclip videos:  90%|█████████ | 1555/1726 [03:07<00:20,  8.49batch/s]A

-- mean: R1 28.60  mAP 41.53
-- mean_s8: R1 28.40  mAP 41.62
-- max: R1 18.60  mAP 30.05
-- query_max: R1 25.80  mAP 39.15

irra videos:  13%|█▎        | 450/3451 [01:10<21:50,  2.29batch/s]

== X-CLIP | activitynet/sentence | vt_2fps_n32

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

xclip texts:   0%|          | 0/227 [00:00<?, ?batch/s]
xclip texts:   3%|▎         | 6/227 [00:00<00:04, 53.02batch/s]/s]
xclip texts:   5%|▌         | 12/227 [00:00<00:04, 43.50batch/s]s]
xclip texts:   8%|▊         | 18/227 [00:00<00:04, 46.61batch/s]s]
xclip texts:  11%|█         | 24/227 [00:00<00:04, 48.32batch/s]s]
xclip texts:  13%|█▎        | 30/227 [00:00<00:03, 50.01batch/s]s]
xclip texts:  16%|█▌        | 36/227 [00:00<00:03, 48.41batch/s]s]
xclip texts:  18%|█▊        | 41/227 [00:00<00:03, 46.59batch/s]s]
xclip texts:  23%|██▎       | 53/227 [00:01<00:03, 50.37batch/s]s]
xclip texts:  26%|██▌       | 59/227 [00:01<00:03, 50.13batch/s]s]
xclip texts:  29%|██▊       | 65/227 [00:01<00:03, 48.85batch/s]s]
xclip texts:  31%|███▏      | 71/227 [00:01<00:03, 50.24batch/s]s]
xclip texts:  34%|███▍      | 77/227 [00:01<00:02, 50.77batch/s]s]
xclip texts:  37%|███▋      | 83/227 [00:01<00:02, 51.05batch/s]s]
xclip texts:  39%|███▉      | 89/227 [00:01<00:02, 51.28batch/s]s]
xclip texts:  42%|████▏     | 95/227 [00:01<00:02, 50.96batch/s]s]
xclip texts:  44%|████▍     | 101/227 [00:02<00:02, 50.05batch/s]]
xclip texts:  47%|████▋     | 107/227 [00:02<00:02, 49.69batch/s]]
xclip texts:  50%|████▉     | 113/227 [00:02<00:02, 49.96batch/s]]
xclip texts:  52%|█████▏    | 119/227 [00:02<00:02, 49.65batch/s]]
xclip texts:  57%|█████▋    | 130/227 [00:02<00:01, 50.42batch/s]]
xclip texts:  60%|█████▉    | 136/227 [00:02<00:01, 50.24batch/s]]
xclip texts:  63%|██████▎   | 142/227 [00:02<00:01, 46.36batch/s]]
xclip texts:  65%|██████▍   | 147/227 [00:03<00:01, 45.15batch/s]]
xclip texts:  67%|██████▋   | 152/227 [00:03<00:01, 45.75batch/s]]
xclip texts:  69%|██████▉   | 157/227 [00:03<00:01, 46.48batch/s]]
xclip texts:  74%|███████▍  | 168/227 [00:03<00:01, 46.83batch/s]]
xclip texts:  77%|███████▋  | 174/227 [00:03<00:01, 48.92batch/s]]
xclip texts:  79%|███████▉  | 179/227 [00:03<00:01, 46.55batch/s]]
xclip texts:  83%|████████▎ | 189/227 [00:03<00:00, 42.15batch/s]]
xclip texts:  86%|████████▌ | 195/227 [00:04<00:00, 45.24batch/s]]
xclip texts:  88%|████████▊ | 200/227 [00:04<00:00, 42.45batch/s]]
xclip texts:  91%|█████████ | 206/227 [00:04<00:00, 44.98batch/s]]
xclip texts:  93%|█████████▎| 212/227 [00:04<00:00, 46.71batch/s]]
xclip texts:  96%|█████████▌| 217/227 [00:04<00:00, 45.65batch/s]]
xclip texts:  98%|█████████▊| 223/227 [00:04<00:00, 47.12batch/s]]
xclip texts: 100%|██████████| 227/227 [00:04<00:00, 47.67batch/s]]

irra videos:  14%|█▍        | 487/3451 [01:15<10:43,  4.61batch/s]
irra videos:  14%|█▍        | 488/3451 [01:16<14:15,  3.47batch/s]
irra videos:  14%|█▍        | 489/3451 [01:16<16:21,  3.02batch/s]
irra videos:  14%|█▍        | 490/3451 [01:17<20:37,  2.39batch/s]
irra videos:  14%|█▍        | 491/3451 [01:17<21:15,  2.32batch/s]
irra videos:  14%|█▍        | 492/3451 [01:18<25:24,  1.94batch/s]
irra videos:  14%|█▍        | 493/3451 [01:18<22:44,  2.17batch/s]
irra videos:  14%|█▍        | 494/3451 [01:19<23:01,  2.14batch/s]
irra videos:  14%|█▍        | 495/3451 [01:19<23:58,  2.06batch/s]
irra videos:  14%|█▍        | 496/3451 [01:20<26:12,  1.88batch/s]
irra videos:  14%|█▍        | 497/3451 [01:21<25:32,  1.93batch/s]
irra videos:  14%|█▍        | 498/3451 [01:21<24:30,  2.01batch/s]
irra videos:  14%|█▍        | 499/3451 [01:22<25:28,  1.93batch/s]
irra videos:  14%|█▍        | 500/3451 [01:22<27:34,  1.78batch/s]
irra videos:  15%|█▍        | 501/3451 [01:23<25:38,  1.92batch/s]
irra videos:  15%|█▍        | 502/3451 [01:23<27:46,  1.77batch/s]
irra videos:  15%|█▍        | 503/3451 [01:24<26:51,  1.83batch/s]
irra videos:  15%|█▍        | 504/3451 [01:24<27:49,  1.77batch/s]
irra videos:  15%|█▍        | 505/3451 [01:25<23:19,  2.10batch/s]
irra videos:  15%|█▍        | 506/3451 [01:25<20:50,  2.36batch/s]
irra videos:  15%|█▍        | 507/3451 [01:25<18:25,  2.66batch/s]
irra videos:  15%|█▍        | 508/3451 [01:26<16:42,  2.94batch/s]
irra videos:  15%|█▍        | 509/3451 [01:26<15:00,  3.27batch/s]
irra videos:  15%|█▍        | 510/3451 [01:26<14:07,  3.47batch/s]
irra videos:  15%|█▍        | 511/3451 [01:26<13:33,  3.62batch/s]
irra videos:  15%|█▍        | 512/3451 [01:27<13:05,  3.74batch/s]
irra videos:  15%|█▍        | 513/3451 [01:27<13:56,  3.51batch/s]
irra videos:  15%|█▍        | 514/3451 [01:27<13:26,  3.64batch/s]
irra videos:  15%|█▍        | 515/3451 [01:27<12:55,  3.79batch/s]
irra videos:  15%|█▍        | 516/3451 [01:28<11:56,  4.10batch/s]
irra videos:  15%|█▍        | 517/3451 [01:28<12:23,  3.95batch/s]
irra videos:  15%|█▌        | 518/3451 [01:29<26:34,  1.84batch/s]

-- mean: R1 13.38  mAP 22.61
-- mean_s8: R1 13.22  mAP 22.68
-- max: R1 9.21  mAP 16.43
-- query_max: R1 13.19  mAP 22.68
== X-CLIP | activitynet/paragraph | reid_8fps_n64

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  15%|█▌        | 519/3451 [01:30<30:17,  1.61batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

xclip videos:   0%|          | 1/3653 [00:00<07:31,  8.09batch/s]]
xclip videos:   0%|          | 2/3653 [00:00<07:25,  8.20batch/s]]
xclip videos:   0%|          | 3/3653 [00:00<07:39,  7.94batch/s]]
xclip videos:   0%|          | 5/3653 [00:00<07:13,  8.42batch/s]]
xclip videos:   0%|          | 7/3653 [00:00<06:58,  8.71batch/s]]
xclip videos:   0%|          | 8/3653 [00:00<06:44,  9.00batch/s]]
xclip videos:   0%|          | 10/3653 [00:01<06:46,  8.96batch/s]
xclip videos:   0%|          | 11/3653 [00:01<06:58,  8.70batch/s]
xclip videos:   0%|          | 13/3653 [00:01<07:15,  8.36batch/s]
xclip videos:   0%|          | 14/3653 [00:01<07:19,  8.28batch/s]
xclip videos:   0%|          | 16/3653 [00:01<06:59,  8.68batch/s]
xclip videos:   0%|          | 17/3653 [00:01<07:01,  8.63batch/s]
xclip videos:   1%|          | 19/3653 [00:02<06:45,  8.96batch/s]
xclip videos:   1%|          | 20/3653 [00:02<07:17,  8.31batch/s]
xclip videos:   1%|          | 21/3653 [00:02<07:52,  7.68batch/s]
xclip videos:   1%|          | 22/3653 [00:02<07:55,  7.64batch/s]
xclip videos:   1%|          | 23/3653 [00:02<08:32,  7.08batch/s]
xclip videos:   1%|          | 24/3653 [00:02<08:06,  7.45batch/s]
xclip videos:   1%|          | 25/3653 [00:03<07:39,  7.90batch/s]
xclip videos:   1%|          | 27/3653 [00:03<07:06,  8.50batch/s]
xclip videos:   1%|          | 28/3653 [00:03<07:20,  8.23batch/s]
xclip videos:   1%|          | 29/3653 [00:03<07:26,  8.11batch/s]
xclip videos:   1%|          | 31/3653 [00:03<07:24,  8.14batch/s]
xclip videos:   1%|          | 32/3653 [00:03<07:23,  8.17batch/s]
xclip videos:   1%|          | 33/3653 [00:03<07:08,  8.44batch/s]
xclip videos:   1%|          | 34/3653 [00:04<06:58,  8.65batch/s]
xclip videos:   1%|          | 35/3653 [00:04<06:50,  8.82batch/s]
xclip videos:   1%|          | 37/3653 [00:04<06:46,  8.90batch/s]
xclip videos:   1%|          | 39/3653 [00:04<06:50,  8.80batch/s]
xclip videos:   1%|          | 40/3653 [00:04<06:53,  8.73batch/s]
xclip videos:   1%|          | 42/3653 [00:04<06:41,  8.99batch/s]
xclip videos:   1%|          | 43/3653 [00:05<06:36,  9.11batch/s]
xclip videos:   1%|          | 44/3653 [00:05<06:32,  9.19batch/s]
xclip videos:   1%|          | 45/3653 [00:05<06:33,  9.16batch/s]
xclip videos:   1%|▏         | 47/3653 [00:05<06:27,  9.31batch/s]
xclip videos:   1%|▏         | 48/3653 [00:05<06:27,  9.31batch/s]
xclip videos:   1%|▏         | 49/3653 [00:05<06:30,  9.24batch/s]
xclip videos:   1%|▏         | 50/3653 [00:05<06:33,  9.16batch/s]
xclip videos:   1%|▏         | 51/3653 [00:05<06:37,  9.06batch/s]
xclip videos:   1%|▏         | 53/3653 [00:06<06:50,  8.77batch/s]
xclip videos:   1%|▏         | 54/3653 [00:06<06:54,  8.67batch/s]
xclip videos:   2%|▏         | 55/3653 [00:06<06:45,  8.87batch/s]
xclip videos:   2%|▏         | 57/3653 [00:06<06:48,  8.80batch/s]
xclip videos:   2%|▏         | 58/3653 [00:06<06:46,  8.85batch/s]
xclip videos:   2%|▏         | 59/3653 [00:06<06:45,  8.86batch/s]
xclip videos:   2%|▏         | 60/3653 [00:06<06:48,  8.80batch/s]
xclip videos:   2%|▏         | 61/3653 [00:07<06:56,  8.63batch/s]
xclip videos:   2%|▏         | 63/3653 [00:07<07:07,  8.39batch/s]
xclip videos:   2%|▏         | 64/3653 [00:07<07:09,  8.35batch/s]
xclip videos:   2%|▏         | 65/3653 [00:07<07:07,  8.38batch/s]
xclip videos:   2%|▏         | 66/3653 [00:07<07:01,  8.52batch/s]
xclip videos:   2%|▏         | 67/3653 [00:07<06:52,  8.70batch/s]
xclip videos:   2%|▏         | 69/3653 [00:08<06:48,  8.78batch/s]
xclip videos:   2%|▏         | 70/3653 [00:08<06:47,  8.78batch/s]
xclip videos:   2%|▏         | 71/3653 [00:08<06:49,  8.76batch/s]
xclip videos:   2%|▏         | 72/3653 [00:08<06:53,  8.67batch/s]
xclip videos:   2%|▏         | 73/3653 [00:08<07:08,  8.35batch/s]
xclip videos:   2%|▏         | 74/3653 [00:08<07:21,  8.11batch/s]
xclip videos:   2%|▏         | 76/3653 [00:08<07:21,  8.10batch/s]
xclip videos:   2%|▏         | 77/3653 [00:09<07:20,  8.12batch/s]
xclip videos:   2%|▏         | 79/3653 [00:09<07:15,  8.21batch/s]
xclip videos:   2%|▏         | 80/3653 [00:09<07:08,  8.33batch/s]
xclip videos:   2%|▏         | 82/3653 [00:09<06:34,  9.04batch/s]
xclip videos:   2%|▏         | 83/3653 [00:09<06:27,  9.21batch/s]
xclip videos:   2%|▏         | 84/3653 [00:09<06:55,  8.59batch/s]
xclip videos:   2%|▏         | 85/3653 [00:09<07:49,  7.60batch/s]
xclip videos:   2%|▏         | 86/3653 [00:10<08:05,  7.34batch/s]
xclip videos:   2%|▏         | 87/3653 [00:10<07:57,  7.48batch/s]
xclip videos:   2%|▏         | 89/3653 [00:10<07:10,  8.28batch/s]
xclip videos:   2%|▏         | 90/3653 [00:10<07:10,  8.27batch/s]
xclip videos:   3%|▎         | 92/3653 [00:10<07:15,  8.17batch/s]
xclip videos:   3%|▎         | 93/3653 [00:10<07:14,  8.19batch/s]
xclip videos:   3%|▎         | 94/3653 [00:11<07:02,  8.42batch/s]
xclip videos:   3%|▎         | 96/3653 [00:11<06:39,  8.91batch/s]
irra videos:  17%|█▋        | 594/3451 [01:43<07:10,  6.64batch/s]
xclip videos:   3%|▎         | 98/3653 [00:11<06:20,  9.34batch/s]
xclip videos:   3%|▎         | 99/3653 [00:11<06:21,  9.32batch/s]
xclip videos:   3%|▎         | 101/3653 [00:11<06:21,  9.30batch/s][A
xclip videos:   3%|▎         | 102/3653 [00:11<06:27,  9.17batch/s][A
xclip videos:   3%|▎         | 103/3653 [00:12<06:29,  9.11batch/s][A
xclip videos:   3%|▎         | 104/3653 [00:12<06:27,  9.16batch/s][A
xclip videos:   3%|▎         | 106/3653 [00:12<06:21,  9.30batch/s][A
xclip videos:   3%|▎         | 107/3653 [00:12<06:45,  8.74batch/s][A
xclip videos:   3%|▎         | 109/3653 [00:12<07:42,  7.66batch/s][A
xclip videos:   3%|▎         | 110/3653 [00:12<07:39,  7.71batch/s][A
xclip videos:   3%|▎         | 111/3653 [00:13<07:28,  7.89batch/s][A
xclip videos:   3%|▎         | 113/3653 [00:13<07:09,  8.25batch/s][A
xclip videos:   3%|▎         | 114/3653 [00:13<07:01,  8.39batch/s][A
xclip videos:   3%|▎         | 115/3653 [00:13<06:57,  8.47batch/s][A
xclip videos:   3%|▎         | 116/3653 [00:13<06:55,  8.51batch/s][A
xclip videos:   3%|▎         | 117/3653 [00:13<06:56,  8.50batch/s][A
xclip videos:   3%|▎         | 119/3653 [00:13<06:39,  8.85batch/s][A
xclip videos:   3%|▎         | 120/3653 [00:14<06:38,  8.86batch/s][A
xclip videos:   3%|▎         | 121/3653 [00:14<06:38,  8.86batch/s][A
xclip videos:   3%|▎         | 122/3653 [00:14<06:35,  8.92batch/s][A
xclip videos:   3%|▎         | 123/3653 [00:14<06:35,  8.93batch/s][A
xclip videos:   3%|▎         | 125/3653 [00:14<06:32,  9.00batch/s][A
xclip videos:   3%|▎         | 126/3653 [00:14<06:29,  9.07batch/s][A
xclip videos:   4%|▎         | 128/3653 [00:14<06:32,  8.98batch/s][A
xclip videos:   4%|▎         | 129/3653 [00:15<06:58,  8.42batch/s][A
xclip videos:   4%|▎         | 130/3653 [00:15<06:59,  8.39batch/s][A
xclip videos:   4%|▎         | 131/3653 [00:15<06:52,  8.53batch/s][A
xclip videos:   4%|▎         | 132/3653 [00:15<06:58,  8.41batch/s][A
xclip videos:   4%|▎         | 134/3653 [00:15<06:44,  8.69batch/s][A
xclip videos:   4%|▎         | 135/3653 [00:15<06:40,  8.78batch/s][A
xclip videos:   4%|▍         | 137/3653 [00:16<06:33,  8.94batch/s][A
xclip videos:   4%|▍         | 138/3653 [00:16<06:44,  8.69batch/s][A
xclip videos:   4%|▍         | 139/3653 [00:16<06:49,  8.58batch/s][A
xclip videos:   4%|▍         | 140/3653 [00:16<06:53,  8.49batch/s][A
xclip videos:   4%|▍         | 141/3653 [00:16<06:47,  8.61batch/s][A
xclip videos:   4%|▍         | 143/3653 [00:16<06:34,  8.91batch/s][A
xclip videos:   4%|▍         | 144/3653 [00:16<06:34,  8.90batch/s][A
xclip videos:   4%|▍         | 145/3653 [00:16<06:37,  8.83batch/s][A
xclip videos:   4%|▍         | 147/3653 [00:17<06:32,  8.94batch/s][A
xclip videos:   4%|▍         | 148/3653 [00:17<06:28,  9.01batch/s][A
xclip videos:   4%|▍         | 149/3653 [00:17<06:43,  8.68batch/s][A
xclip videos:   4%|▍         | 151/3653 [00:17<06:38,  8.79batch/s][A
xclip videos:   4%|▍         | 152/3653 [00:17<06:40,  8.75batch/s][A
xclip videos:   4%|▍         | 153/3653 [00:17<06:44,  8.66batch/s][A
xclip videos:   4%|▍         | 155/3653 [00:18<06:32,  8.90batch/s][A
xclip videos:   4%|▍         | 156/3653 [00:18<06:39,  8.75batch/s][A
xclip videos:   4%|▍         | 157/3653 [00:18<06:35,  8.85batch/s][A
xclip videos:   4%|▍         | 159/3653 [00:18<06:30,  8.95batch/s][A
xclip videos:   4%|▍         | 160/3653 [00:18<06:43,  8.65batch/s][A
xclip videos:   4%|▍         | 161/3653 [00:18<07:01,  8.29batch/s][A
xclip videos:   4%|▍         | 163/3653 [00:19<07:03,  8.25batch/s][A
xclip videos:   4%|▍         | 164/3653 [00:19<06:58,  8.33batch/s][A
xclip videos:   5%|▍         | 165/3653 [00:19<06:56,  8.38batch/s][A
xclip videos:   5%|▍         | 166/3653 [00:19<07:03,  8.24batch/s][A
xclip videos:   5%|▍         | 167/3653 [00:19<07:00,  8.29batch/s][A
xclip videos:   5%|▍         | 168/3653 [00:19<07:05,  8.19batch/s][A
xclip videos:   5%|▍         | 170/3653 [00:19<06:45,  8.60batch/s][A
xclip videos:   5%|▍         | 171/3653 [00:19<07:01,  8.27batch/s][A
xclip videos:   5%|▍         | 172/3653 [00:20<07:08,  8.13batch/s][A
xclip videos:   5%|▍         | 174/3653 [00:20<06:55,  8.36batch/s][A
xclip videos:   5%|▍         | 175/3653 [00:20<06:55,  8.37batch/s][A
xclip videos:   5%|▍         | 176/3653 [00:20<06:53,  8.41batch/s][A
xclip videos:   5%|▍         | 177/3653 [00:20<06:48,  8.51batch/s][A
xclip videos:   5%|▍         | 178/3653 [00:20<06:48,  8.50batch/s][A
xclip videos:   5%|▍         | 180/3653 [00:21<06:47,  8.52batch/s][A
xclip videos:   5%|▍         | 181/3653 [00:21<06:46,  8.55batch/s][A
xclip videos:   5%|▍         | 182/3653 [00:21<06:50,  8.46batch/s][A
xclip videos:   5%|▌         | 184/3653 [00:21<07:01,  8.22batch/s][A
xclip videos:   5%|▌         | 186/3653 [00:21<06:59,  8.27batch/s][A
xclip videos:   5%|▌         | 187/3653 [00:21<06:51,  8.42batch/s][A
xclip videos:   5%|▌         | 188/3653 [00:22<06:44,  8.57batch/s][A
xclip videos:   5%|▌         | 189/3653 [00:22<06:45,  8.54batch/s][A
xclip videos:   5%|▌         | 191/3653 [00:22<06:48,  8.48batch/s][A
xclip videos:   5%|▌         | 192/3653 [00:22<07:17,  7.91batch/s][A
xclip videos:   5%|▌         | 193/3653 [00:22<07:17,  7.90batch/s][A
xclip videos:   5%|▌         | 195/3653 [00:22<07:20,  7.86batch/s][A
xclip videos:   5%|▌         | 196/3653 [00:23<07:13,  7.97batch/s][A
xclip videos:   5%|▌         | 198/3653 [00:23<07:07,  8.08batch/s][A
xclip videos:   5%|▌         | 199/3653 [00:23<07:00,  8.22batch/s][A
xclip videos:   5%|▌         | 200/3653 [00:23<06:48,  8.46batch/s][A
xclip videos:   6%|▌         | 202/3653 [00:23<06:47,  8.48batch/s][A
xclip videos:   6%|▌         | 203/3653 [00:23<06:51,  8.39batch/s][A
xclip videos:   6%|▌         | 205/3653 [00:24<06:37,  8.66batch/s][A
xclip videos:   6%|▌         | 206/3653 [00:24<06:37,  8.67batch/s][A
xclip videos:   6%|▌         | 207/3653 [00:24<06:31,  8.81batch/s][A
xclip videos:   6%|▌         | 209/3653 [00:24<06:18,  9.09batch/s][A
xclip videos:   6%|▌         | 210/3653 [00:24<06:25,  8.92batch/s][A
xclip videos:   6%|▌         | 211/3653 [00:24<06:29,  8.84batch/s][A
xclip videos:   6%|▌         | 212/3653 [00:24<06:27,  8.89batch/s][A
xclip videos:   6%|▌         | 214/3653 [00:25<06:22,  9.00batch/s][A
xclip videos:   6%|▌         | 215/3653 [00:25<06:16,  9.13batch/s][A
xclip videos:   6%|▌         | 216/3653 [00:25<06:11,  9.26batch/s][A
xclip videos:   6%|▌         | 218/3653 [00:25<06:26,  8.90batch/s][A
xclip videos:   6%|▌         | 219/3653 [00:25<06:44,  8.50batch/s][A
xclip videos:   6%|▌         | 221/3653 [00:25<06:49,  8.39batch/s][A
xclip videos:   6%|▌         | 222/3653 [00:25<06:38,  8.61batch/s][A
xclip videos:   6%|▌         | 223/3653 [00:26<06:24,  8.91batch/s][A
xclip videos:   6%|▌         | 225/3653 [00:26<06:19,  9.04batch/s][A
xclip videos:   6%|▌         | 226/3653 [00:26<06:15,  9.12batch/s][A
xclip videos:   6%|▌         | 227/3653 [00:26<06:26,  8.87batch/s][A
xclip videos:   6%|▌         | 228/3653 [00:26<06:40,  8.54batch/s][A
xclip videos:   6%|▋         | 229/3653 [00:26<06:28,  8.81batch/s][A
xclip videos:   6%|▋         | 231/3653 [00:26<06:18,  9.03batch/s][A
xclip videos:   6%|▋         | 232/3653 [00:27<06:25,  8.88batch/s][A
xclip videos:   6%|▋         | 234/3653 [00:27<06:53,  8.27batch/s][A
xclip videos:   6%|▋         | 235/3653 [00:27<07:00,  8.13batch/s][A
xclip videos:   6%|▋         | 236/3653 [00:27<06:59,  8.15batch/s][A
xclip videos:   7%|▋         | 238/3653 [00:27<06:36,  8.61batch/s][A
xclip videos:   7%|▋         | 239/3653 [00:27<06:40,  8.52batch/s][A
xclip videos:   7%|▋         | 240/3653 [00:28<06:39,  8.55batch/s][A
xclip videos:   7%|▋         | 242/3653 [00:28<06:35,  8.63batch/s][A
xclip videos:   7%|▋         | 243/3653 [00:28<06:56,  8.20batch/s][A
xclip videos:   7%|▋         | 244/3653 [00:28<07:02,  8.07batch/s][A
xclip videos:   7%|▋         | 245/3653 [00:28<06:55,  8.21batch/s][A
xclip videos:   7%|▋         | 247/3653 [00:28<06:46,  8.38batch/s][A
xclip videos:   7%|▋         | 248/3653 [00:29<06:50,  8.30batch/s][A
xclip videos:   7%|▋         | 249/3653 [00:29<06:49,  8.31batch/s][A
xclip videos:   7%|▋         | 250/3653 [00:29<06:52,  8.26batch/s][A
xclip videos:   7%|▋         | 251/3653 [00:29<06:46,  8.37batch/s][A
xclip videos:   7%|▋         | 253/3653 [00:29<06:54,  8.21batch/s][A
xclip videos:   7%|▋         | 254/3653 [00:29<06:42,  8.44batch/s][A
xclip videos:   7%|▋         | 256/3653 [00:29<06:18,  8.99batch/s][A
xclip videos:   7%|▋         | 257/3653 [00:30<06:12,  9.11batch/s][A
xclip videos:   7%|▋         | 258/3653 [00:30<06:07,  9.25batch/s][A
xclip videos:   7%|▋         | 260/3653 [00:30<06:16,  9.01batch/s][A
xclip videos:   7%|▋         | 261/3653 [00:30<06:46,  8.35batch/s][A
xclip videos:   7%|▋         | 262/3653 [00:30<07:07,  7.94batch/s][A
xclip videos:   7%|▋         | 264/3653 [00:30<07:28,  7.56batch/s][A
xclip videos:   7%|▋         | 265/3653 [00:31<07:26,  7.59batch/s][A
xclip videos:   7%|▋         | 267/3653 [00:31<07:23,  7.63batch/s][A
xclip videos:   7%|▋         | 268/3653 [00:31<07:26,  7.58batch/s][A
xclip videos:   7%|▋         | 269/3653 [00:31<07:33,  7.47batch/s][A
xclip videos:   7%|▋         | 271/3653 [00:31<07:01,  8.02batch/s][A
xclip videos:   7%|▋         | 272/3653 [00:31<06:55,  8.14batch/s][A
xclip videos:   8%|▊         | 274/3653 [00:32<06:50,  8.24batch/s][A
xclip videos:   8%|▊         | 275/3653 [00:32<06:50,  8.22batch/s][A
xclip videos:   8%|▊         | 276/3653 [00:32<06:56,  8.11batch/s][A
xclip videos:   8%|▊         | 278/3653 [00:32<06:45,  8.32batch/s][A
xclip videos:   8%|▊         | 279/3653 [00:32<07:14,  7.76batch/s][A
xclip videos:   8%|▊         | 280/3653 [00:32<07:06,  7.91batch/s][A
xclip videos:   8%|▊         | 282/3653 [00:33<07:09,  7.85batch/s][A
xclip videos:   8%|▊         | 283/3653 [00:33<07:05,  7.91batch/s][A
xclip videos:   8%|▊         | 284/3653 [00:33<07:02,  7.98batch/s][A
xclip videos:   8%|▊         | 286/3653 [00:33<06:52,  8.16batch/s][A
xclip videos:   8%|▊         | 287/3653 [00:33<06:46,  8.27batch/s][A
xclip videos:   8%|▊         | 288/3653 [00:33<06:37,  8.46batch/s][A
xclip videos:   8%|▊         | 290/3653 [00:34<06:26,  8.71batch/s][A
xclip videos:   8%|▊         | 291/3653 [00:34<06:33,  8.53batch/s][A
xclip videos:   8%|▊         | 292/3653 [00:34<06:38,  8.44batch/s][A
xclip videos:   8%|▊         | 294/3653 [00:34<06:32,  8.57batch/s][A
xclip videos:   8%|▊         | 295/3653 [00:34<06:48,  8.21batch/s][A
xclip videos:   8%|▊         | 297/3653 [00:35<06:56,  8.05batch/s][A
xclip videos:   8%|▊         | 298/3653 [00:35<07:02,  7.95batch/s][A
xclip videos:   8%|▊         | 299/3653 [00:35<07:10,  7.79batch/s][A
xclip videos:   8%|▊         | 300/3653 [00:35<07:09,  7.80batch/s][A
xclip videos:   8%|▊         | 302/3653 [00:35<07:02,  7.94batch/s][A
xclip videos:   8%|▊         | 303/3653 [00:35<06:50,  8.17batch/s][A
xclip videos:   8%|▊         | 304/3653 [00:35<06:36,  8.44batch/s][A
xclip videos:   8%|▊         | 306/3653 [00:36<06:21,  8.77batch/s][A
xclip videos:   8%|▊         | 307/3653 [00:36<06:20,  8.78batch/s][A
xclip videos:   8%|▊         | 308/3653 [00:36<06:22,  8.73batch/s][A
xclip videos:   8%|▊         | 309/3653 [00:36<06:16,  8.88batch/s][A
xclip videos:   9%|▊         | 311/3653 [00:36<06:06,  9.13batch/s][A
xclip videos:   9%|▊         | 312/3653 [00:36<06:15,  8.90batch/s][A
xclip videos:   9%|▊         | 314/3653 [00:37<06:14,  8.91batch/s][A
xclip videos:   9%|▊         | 315/3653 [00:37<06:09,  9.03batch/s][A
xclip videos:   9%|▊         | 316/3653 [00:37<06:09,  9.04batch/s][A
xclip videos:   9%|▊         | 317/3653 [00:37<06:10,  9.00batch/s][A
xclip videos:   9%|▊         | 318/3653 [00:37<06:15,  8.88batch/s][A
xclip videos:   9%|▊         | 319/3653 [00:37<06:10,  9.00batch/s][A
xclip videos:   9%|▉         | 321/3653 [00:37<05:55,  9.37batch/s][A
xclip videos:   9%|▉         | 322/3653 [00:37<05:55,  9.37batch/s][A
xclip videos:   9%|▉         | 323/3653 [00:38<06:08,  9.03batch/s][A
xclip videos:   9%|▉         | 325/3653 [00:38<05:58,  9.28batch/s][A
xclip videos:   9%|▉         | 327/3653 [00:38<06:09,  8.99batch/s][A
xclip videos:   9%|▉         | 328/3653 [00:38<06:13,  8.91batch/s][A
xclip videos:   9%|▉         | 330/3653 [00:38<06:23,  8.66batch/s][A
xclip videos:   9%|▉         | 331/3653 [00:38<06:30,  8.50batch/s][A
xclip videos:   9%|▉         | 332/3653 [00:39<06:44,  8.22batch/s][A
xclip videos:   9%|▉         | 333/3653 [00:39<06:46,  8.18batch/s][A
xclip videos:   9%|▉         | 334/3653 [00:39<06:40,  8.28batch/s][A
xclip videos:   9%|▉         | 335/3653 [00:39<06:31,  8.47batch/s][A
xclip videos:   9%|▉         | 337/3653 [00:39<06:21,  8.69batch/s][A
xclip videos:   9%|▉         | 338/3653 [00:39<06:30,  8.49batch/s][A
xclip videos:   9%|▉         | 340/3653 [00:39<06:23,  8.63batch/s][A
xclip videos:   9%|▉         | 341/3653 [00:40<06:17,  8.77batch/s][A
xclip videos:   9%|▉         | 342/3653 [00:40<06:27,  8.53batch/s][A
xclip videos:   9%|▉         | 344/3653 [00:40<06:44,  8.17batch/s][A
xclip videos:   9%|▉         | 345/3653 [00:40<06:32,  8.43batch/s][A
xclip videos:   9%|▉         | 346/3653 [00:40<06:27,  8.53batch/s][A
xclip videos:   9%|▉         | 347/3653 [00:40<06:22,  8.64batch/s][A
xclip videos:  10%|▉         | 349/3653 [00:41<06:27,  8.52batch/s][A
xclip videos:  10%|▉         | 350/3653 [00:41<06:36,  8.33batch/s][A
xclip videos:  10%|▉         | 351/3653 [00:41<06:37,  8.31batch/s][A
xclip videos:  10%|▉         | 353/3653 [00:41<06:24,  8.59batch/s][A
xclip videos:  10%|▉         | 354/3653 [00:41<06:27,  8.52batch/s][A
xclip videos:  10%|▉         | 355/3653 [00:41<06:39,  8.26batch/s][A
xclip videos:  10%|▉         | 357/3653 [00:42<06:51,  8.01batch/s][A
xclip videos:  10%|▉         | 358/3653 [00:42<06:50,  8.04batch/s][A
xclip videos:  10%|▉         | 359/3653 [00:42<06:44,  8.14batch/s][A
xclip videos:  10%|▉         | 361/3653 [00:42<06:50,  8.01batch/s][A
xclip videos:  10%|▉         | 362/3653 [00:42<06:39,  8.24batch/s][A
xclip videos:  10%|▉         | 363/3653 [00:42<06:53,  7.96batch/s][A
xclip videos:  10%|▉         | 364/3653 [00:42<07:00,  7.83batch/s][A
xclip videos:  10%|█         | 366/3653 [00:43<06:38,  8.24batch/s][A
xclip videos:  10%|█         | 367/3653 [00:43<06:27,  8.49batch/s][A
xclip videos:  10%|█         | 368/3653 [00:43<06:26,  8.50batch/s][A
xclip videos:  10%|█         | 369/3653 [00:43<06:18,  8.67batch/s][A
xclip videos:  10%|█         | 371/3653 [00:43<06:12,  8.81batch/s][A
xclip videos:  10%|█         | 372/3653 [00:43<06:14,  8.77batch/s][A
xclip videos:  10%|█         | 374/3653 [00:44<06:11,  8.83batch/s][A
xclip videos:  10%|█         | 375/3653 [00:44<06:12,  8.79batch/s][A
xclip videos:  10%|█         | 376/3653 [00:44<06:18,  8.65batch/s][A
xclip videos:  10%|█         | 378/3653 [00:44<06:17,  8.67batch/s][A

-- mean: R1 27.70  mAP 41.50
-- mean_s8: R1 27.90  mAP 41.90
-- max: R1 15.30  mAP 25.46
-- query_max: R1 25.10  mAP 39.18

irra videos:  99%|█████████▉| 3411/3451 [08:41<00:14,  2.78batch/s]

== X-CLIP | activitynet/sentence | reid_8fps_n64

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos:  99%|█████████▉| 3412/3451 [08:42<00:21,  1.81batch/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

xclip texts:   0%|          | 0/227 [00:00<?, ?batch/s]
xclip texts:   2%|▏         | 4/227 [00:00<00:06, 36.95batch/s]h/s]
xclip texts:   4%|▍         | 10/227 [00:00<00:04, 45.18batch/s]/s]
xclip texts:  10%|▉         | 22/227 [00:00<00:03, 52.46batch/s]/s]
xclip texts:  12%|█▏        | 28/227 [00:00<00:03, 51.45batch/s]/s]
xclip texts:  15%|█▍        | 34/227 [00:00<00:03, 50.76batch/s]/s]
xclip texts:  18%|█▊        | 40/227 [00:00<00:03, 48.56batch/s]/s]
xclip texts:  20%|█▉        | 45/227 [00:00<00:03, 45.88batch/s]/s]
xclip texts:  22%|██▏       | 51/227 [00:01<00:03, 48.04batch/s]/s]
xclip texts:  25%|██▍       | 56/227 [00:01<00:03, 46.79batch/s]/s]
xclip texts:  27%|██▋       | 61/227 [00:01<00:03, 43.48batch/s]/s]
xclip texts:  32%|███▏      | 72/227 [00:01<00:03, 45.05batch/s]/s]
xclip texts:  34%|███▍      | 78/227 [00:01<00:03, 47.51batch/s]/s]
xclip texts:  37%|███▋      | 83/227 [00:01<00:03, 47.16batch/s]/s]
xclip texts:  41%|████      | 93/227 [00:01<00:02, 47.88batch/s]/s]
xclip texts:  43%|████▎     | 98/227 [00:02<00:02, 45.30batch/s]/s]
xclip texts:  45%|████▌     | 103/227 [00:02<00:02, 45.28batch/s]s]
xclip texts:  48%|████▊     | 108/227 [00:02<00:02, 43.03batch/s]s]
xclip texts:  53%|█████▎    | 120/227 [00:02<00:02, 49.42batch/s]s]
xclip texts:  56%|█████▌    | 126/227 [00:02<00:02, 49.62batch/s]s]
xclip texts:  58%|█████▊    | 132/227 [00:02<00:01, 48.30batch/s]s]
xclip texts:  60%|██████    | 137/227 [00:02<00:01, 46.66batch/s]s]
xclip texts:  63%|██████▎   | 143/227 [00:03<00:01, 49.11batch/s]s]
xclip texts:  65%|██████▌   | 148/227 [00:03<00:01, 45.18batch/s]s]
xclip texts:  70%|██████▉   | 158/227 [00:03<00:01, 46.59batch/s]s]
xclip texts:  72%|███████▏  | 164/227 [00:03<00:01, 49.15batch/s]s]
xclip texts:  74%|███████▍  | 169/227 [00:03<00:01, 48.01batch/s]s]
xclip texts:  77%|███████▋  | 174/227 [00:03<00:01, 46.36batch/s]s]
xclip texts:  79%|███████▉  | 179/227 [00:03<00:01, 47.25batch/s]s]
xclip texts:  84%|████████▎ | 190/227 [00:04<00:00, 45.53batch/s]s]
xclip texts:  86%|████████▋ | 196/227 [00:04<00:00, 47.85batch/s]s]
xclip texts:  89%|████████▉ | 202/227 [00:04<00:00, 49.68batch/s]s]
xclip texts:  91%|█████████ | 207/227 [00:04<00:00, 49.20batch/s]s]
xclip texts:  94%|█████████▍| 213/227 [00:04<00:00, 50.80batch/s]s]
xclip texts:  96%|█████████▋| 219/227 [00:04<00:00, 51.81batch/s]s]
xclip texts: 100%|██████████| 227/227 [00:04<00:00, 47.71batch/s]s]

irra videos: 100%|█████████▉| 3448/3451 [08:48<00:00,  6.72batch/s]
irra videos: 100%|█████████▉| 3449/3451 [08:48<00:00,  5.06batch/s]
irra videos: 100%|█████████▉| 3450/3451 [08:48<00:00,  3.69batch/s]
irra videos: 100%|██████████| 3451/3451 [08:49<00:00,  6.52batch/s]
irra texts: 100%|██████████| 63/63 [00:05<00:00, 12.04batch/s]

-- mean: R1 14.40  mAP 25.07
-- mean_s8: R1 14.50  mAP 25.22
-- max: R1 12.30  mAP 21.85
-- query_max: R1 15.10  mAP 25.77
== IRRA | activitynet/sentence | vt_2fps_n32

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 6902 clips (window=8 stride=4 fps=2 max=32)

irra texts:   2%|▏         | 5/227 [00:01<01:04,  3.46batch/s]

-- mean: R1 14.04  mAP 23.59
-- mean_s8: R1 13.91  mAP 23.59
-- max: R1 7.41  mAP 13.75
-- query_max: R1 12.75  mAP 23.15

irra texts: 100%|██████████| 227/227 [00:04<00:00, 47.09batch/s]

-- mean: R1 7.08  mAP 13.82
-- mean_s8: R1 7.30  mAP 13.99
-- max: R1 5.97  mAP 12.46
-- query_max: R1 7.82  mAP 14.82
== IRRA | activitynet/paragraph | reid_8fps_n64

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

irra videos: 100%|██████████| 7306/7306 [10:17<00:00, 11.84batch/s]
irra texts: 100%|██████████| 63/63 [00:00<00:00, 74.24batch/s]

-- mean: R1 15.10  mAP 25.68
-- mean_s8: R1 15.10  mAP 25.80
-- max: R1 9.70  mAP 18.61
-- query_max: R1 16.40  mAP 27.20
== IRRA | activitynet/sentence | reid_8fps_n64

Decode windows:   0%|          | 0/1000 [00:00<?, ?video/s]

Window encode: 1000 tracklets, 14612 clips (window=8 stride=4 fps=8 max=64)

irra texts: 100%|██████████| 227/227 [00:02<00:00, 81.75batch/s]

-- mean: R1 7.33  mAP 14.13
-- mean_s8: R1 7.27  mAP 14.08
-- max: R1 4.56  mAP 10.44
-- query_max: R1 8.29  mAP 15.40
IRRA and X-CLIP retry done

## 5. Tables

Reads ActivityNet results from every results folder it can find: this session's `zero_shot_results/`, plus any attached Kaggle inputs that contain a `zero_shot_results` folder (other groups, earlier runs). Each table is shown here and saved as CSV and Markdown under `zero_shot_results/tables/`.

Accuracy cells use each model's **best Rank-1 setting** per ActivityNet subset (protocol and pool are shown in the settings table). All numbers are percentages except MdR (median rank).

In [11]:
import numpy as np

KEY = ["dataset", "subset", "model", "protocol", "pool"]


def collect_rows():
    roots = [RESULTS_ROOT]
    if Path("/kaggle/input").is_dir():
        roots += [p for p in Path("/kaggle/input").rglob("zero_shot_results") if p.is_dir()]
    rows = []
    for root in dict.fromkeys(roots):
        for path in root.rglob("*.json"):
            try:
                row = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(row, dict) or "Rank-1" not in row:
                continue
            if row.get("status", "complete") != "complete" or row.get("dataset") != "activitynet":
                continue
            rows.append(row)
    if not rows:
        return pd.DataFrame(
            columns=KEY + ["Rank-1", "mAP", "mINP", "protocol_type", "gallery_cached", "Model", "Dataset",
                           "video_ms_per_item", "peak_gpu_gb", "total_s"]
        )
    frame = pd.DataFrame(rows)
    if "protocol_type" not in frame:
        frame["protocol_type"] = np.where(frame["pool"] == "none", "single", "window")
    frame["protocol_type"] = frame["protocol_type"].fillna(
        pd.Series(np.where(frame["pool"] == "none", "single", "window"), index=frame.index)
    )
    frame["created_at"] = frame.get("created_at", pd.Series(dtype=str)).fillna("")
    frame["gallery_cached"] = frame.get("gallery_cached", False)
    frame["gallery_cached"] = frame["gallery_cached"].fillna(False).astype(bool)
    frame = frame.sort_values("created_at").drop_duplicates(KEY, keep="last")
    frame["Model"] = frame["model"].map(lambda m: PRETTY.get(m, m))
    frame["Dataset"] = frame["dataset"].map(lambda d: DATASETS.get(d, {}).get("label", d))
    return frame.reset_index(drop=True)


RESULTS = collect_rows()
print(f"{len(RESULTS)} result rows from {RESULTS['model'].nunique() if len(RESULTS) else 0} models", flush=True)
BEST = (
    RESULTS.sort_values(["Rank-1", "mAP"], ascending=False, kind="mergesort")
    .groupby(["dataset", "subset", "model"], as_index=False)
    .head(1)
    .reset_index(drop=True)
)
TABLES = {}


def column_order(dataset):
    return [s for s in DATASETS.get(dataset, {}).get("subsets", []) if s in set(BEST.loc[BEST.dataset == dataset, "subset"])]


def setting_text(row):
    return row["protocol"] if row["pool"] in ("none", None) or pd.isna(row["pool"]) else f"{row['protocol']} / {row['pool']}"

104 result rows from 4 models

### 5.1 Leaderboard per dataset (Rank-1 / mAP / mINP)

In [12]:
for dataset in [d for d in DATASETS if d in set(BEST["dataset"])]:
    part = BEST[BEST.dataset == dataset].copy()
    subsets = column_order(dataset)
    part["cell"] = part.apply(lambda r: f"{r['Rank-1']:.2f} / {r['mAP']:.2f} / {r.get('mINP', np.nan):.2f}", axis=1)
    part["setting"] = part.apply(setting_text, axis=1)
    order = part.groupby("Model")["Rank-1"].mean().sort_values(ascending=False).index
    board = part.pivot(index="Model", columns="subset", values="cell").reindex(index=order, columns=subsets)
    board["mean Rank-1"] = part.groupby("Model")["Rank-1"].mean().reindex(order).round(2)
    settings = part.pivot(index="Model", columns="subset", values="setting").reindex(index=order, columns=subsets)
    label = DATASETS[dataset]["label"]
    TABLES[f"leaderboard_{dataset}"] = board
    TABLES[f"best_setting_{dataset}"] = settings
    display(Markdown(f"#### {label}"))
    display(board)
    display(Markdown(f"Best setting per cell ({label})"))
    display(settings)

#### ActivityNet Captions

subset,paragraph,sentence,mean Rank-1
Model,,,
Perception Encoder L/14,68.10 / 78.87 / 78.87,41.91 / 54.83 / 54.83,55.01
SigLIP 2 So400m,57.10 / 70.18 / 70.18,35.11 / 48.51 / 48.51,46.11
X-CLIP,28.60 / 41.53 / 41.53,14.04 / 23.59 / 23.59,21.32
IRRA,16.40 / 27.20 / 27.20,8.29 / 15.40 / 15.40,12.35

Best setting per cell (ActivityNet Captions)

subset                                   paragraph                   sentence
Model
Perception Encoder L/14    vt_2fps_n32 / query_max  reid_8fps_n64 / query_max
SigLIP 2 So400m          reid_8fps_n64 / query_max  reid_8fps_n64 / query_max
X-CLIP                          vt_2fps_n32 / mean       reid_8fps_n64 / mean
IRRA                     reid_8fps_n64 / query_max  reid_8fps_n64 / query_max

### 5.2 Protocol and pool comparison (top three models, Rank-1)

In [13]:
for dataset in [d for d in DATASETS if DATASETS[d]["protocols"] == "video" and d in set(RESULTS["dataset"])]:
    part = RESULTS[RESULTS.dataset == dataset].copy()
    top = part.groupby("Model")["Rank-1"].max().sort_values(ascending=False).head(3).index
    part = part[part.Model.isin(top)]
    part["pool"] = part["pool"].replace({"none": "-"})
    table = part.pivot_table(index=["Model", "protocol", "pool"], columns="subset", values="Rank-1", aggfunc="max")
    table = table.reindex(columns=column_order(dataset)).round(2)
    table = table.reindex(top, level=0)
    TABLES[f"protocols_{dataset}"] = table
    display(Markdown(f"#### {DATASETS[dataset]['label']}"))
    display(table)

#### ActivityNet Captions

subset                                           paragraph  sentence
Model                   protocol      pool
Perception Encoder L/14 reid_8fps_n64 max             58.5     33.62
                                      mean            64.8     38.73
                                      mean_s8         65.3     38.93
                                      query_max       67.5     41.91
                        uniform8      -               62.1     36.25
                        vt_1fps_n12   max             63.1     37.43
                                      mean            63.2     37.30
                                      mean_s8         63.2     37.30
                                      query_max       64.9     37.79
                        vt_2fps_n32   max             64.0     36.80
                                      mean            64.8     38.62
                                      mean_s8         64.9     38.40
                                      query_max       68.1     41.17
SigLIP 2 So400m         reid_8fps_n64 max             50.4     28.12
                                      mean            54.4     31.08
                                      mean_s8         53.9     30.69
                                      query_max       57.1     35.11
                        uniform8      -               51.8     28.50
                        vt_1fps_n12   max             51.8     29.97
                                      mean            52.2     29.91
                                      mean_s8         52.2     29.91
                                      query_max       53.2     30.61
                        vt_2fps_n32   max             52.9     29.89
                                      mean            54.8     30.94
                                      mean_s8         54.4     30.58
                                      query_max       56.1     33.78
X-CLIP                  reid_8fps_n64 max             15.3      7.41
                                      mean            27.7     14.04
                                      mean_s8         27.9     13.91
                                      query_max       25.1     12.75
                        uniform8      -               21.2      9.81
                        vt_1fps_n12   max             23.8     10.98
                                      mean            23.7     11.89
                                      mean_s8         23.7     11.89
                                      query_max       23.1     11.50
                        vt_2fps_n32   max             18.6      9.21
                                      mean            28.6     13.38
                                      mean_s8         28.4     13.22
                                      query_max       25.8     13.19

### 5.3 ActivityNet Captions: paragraph vs sentence queries

Same gallery, different queries. Paragraph queries describe the whole video and are mostly longer than the 32 to 77 token text window of the CLIP-style encoders (the tail is truncated); sentence queries describe one event of the video.

In [14]:
anet = BEST[BEST.dataset == "activitynet"]
if len(anet):
    gap = anet.pivot(index="Model", columns="subset", values="Rank-1").reindex(columns=["paragraph", "sentence"])
    gap["paragraph - sentence"] = gap["paragraph"] - gap["sentence"]
    gap = gap.sort_values("paragraph", ascending=False).round(2)
    TABLES["activitynet_paragraph_vs_sentence"] = gap
    display(gap)
else:
    print("No ActivityNet rows yet")

subset                   paragraph  sentence  paragraph - sentence
Model
Perception Encoder L/14       68.1     41.91                 26.19
SigLIP 2 So400m               57.1     35.11                 21.99
X-CLIP                        28.6     14.04                 14.56
IRRA                          16.4      8.29                  8.11

### 5.4 Speed and GPU (Tesla T4)

In [15]:
if len(RESULTS):
    fresh = RESULTS[~RESULTS["gallery_cached"]]
    single = fresh[fresh["protocol_type"] == "single"]
    windows = fresh[fresh["protocol_type"] == "window"]
    speed = pd.DataFrame(
        {
            "ms / clip (single clip)": single.groupby("Model")["video_ms_per_item"].median(),
            "ms / clip (windows)": windows.groupby("Model")["video_ms_per_item"].median(),
            "peak GPU GB": RESULTS.groupby("Model")["peak_gpu_gb"].max(),
            "total minutes": RESULTS.groupby("Model")["total_s"].sum() / 60.0,
            "rows": RESULTS.groupby("Model").size(),
        }
    )
    speed = speed.sort_values("ms / clip (single clip)").round(2)
    TABLES["speed_gpu"] = speed
    display(speed)

,ms / clip (single clip),ms / clip (windows),peak GPU GB,total minutes,rows
Model,,,,,
X-CLIP,30.76,29.94,0.45,49.25,26
IRRA,75.02,76.75,0.61,90.68,26
Perception Encoder L/14,374.51,375.85,1.32,639.64,26
SigLIP 2 So400m,486.44,486.05,2.23,822.98,26

### 5.5 Save tables

In [16]:
def markdown_table(frame):
    frame = frame.reset_index() if not isinstance(frame.index, pd.RangeIndex) else frame
    headers = [str(c) for c in frame.columns]

    def cell(value):
        if isinstance(value, float):
            return "-" if np.isnan(value) else f"{value:.2f}"
        return str(value)

    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for _, row in frame.iterrows():
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


TABLE_DIR = RESULTS_ROOT / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)
RESULTS.to_csv(TABLE_DIR / "all_rows.csv", index=False)
DATASET_SUMMARY.to_csv(TABLE_DIR / "datasets.csv", index=False)
report = ["# Zero-shot results", "", "## Datasets", "", markdown_table(DATASET_SUMMARY.drop(columns=["root"]))]
for name, table in TABLES.items():
    table.to_csv(TABLE_DIR / f"{name}.csv")
    report += ["", f"## {name}", "", markdown_table(table)]
(TABLE_DIR / "report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
print("Wrote", sorted(p.name for p in TABLE_DIR.iterdir()), flush=True)

Wrote ['activitynet_paragraph_vs_sentence.csv', 'all_rows.csv', 'best_setting_activitynet.csv', 'datasets.csv', 'leaderboard_activitynet.csv', 'protocols_activitynet.csv', 'report.md', 'speed_gpu.csv']