# Zero-shot text-to-tracklet benchmark

Frozen image and video language models, scored zero-shot on three caption-to-person retrieval datasets. Every caption is a query; its positives are the gallery items of the same identity.

| Dataset | Gallery | Queries | What the captions describe |
|---|---|---|---|
| **TVPReid** (`prid`, `ilids`, `duke`) | 820 test videos | 2 per video | appearance, some motion and scene |
| **RSTPReid** (`test`) | 1,000 still images, 200 IDs | 2 per image | appearance (MSMT17 cameras) |
| **GroOT-MOT17** (`all`, `appearance`, `action`, `combined`) | one mp4 per MOT17 track | 1 appearance + 1 action per track, plus 1 refined combined sentence | `appearance`, `action`, and `combined` are scored separately |

CUHK-PEDES is excluded because IRRA was trained on it; every dataset here is zero-shot for every model.

**How to run**

1. GPU T4, Internet on. Add a Kaggle secret named `hugging_face` (needed for the gated InternVideo2-1B-s2 checkpoint in the `base` group).
2. Pick `ENV_GROUP` in the configuration cell. The groups need different `transformers` versions, so each group is its own Kaggle session:
   - `base`: SigLIP 2, Perception Encoder, IRRA, InternVideo2-1B-s2, X-CLIP, LanguageBind, InternVideo2 CLIP-S
   - `extended_modern`: OpenAI CLIP ViT-L/14, Jina CLIP v2, Qwen3-VL-Embedding-2B
   - `extended_gme`: GME-Qwen2-VL-2B
3. Run All. Every result row is written as JSON the moment it finishes, so a restarted session skips what is done.
4. To combine groups, save each session's `/kaggle/working/zero_shot_results` as a Kaggle dataset and attach it; the tables section merges every results folder it finds.

## 1. Configuration

In [1]:
from pathlib import Path

ENV_GROUP = "base"  # "base", "extended_modern", or "extended_gme" (one Kaggle session each)
RUN_DATASETS = ["tvpreid", "rstpreid", "groot_mot17"]

MODEL_GROUPS = {
    "base": [
        "siglip2",
        "pe_core_l14",
        "irra",
        "internvideo2_s2_1b",
        "xclip",
        "languagebind",
        "internvideo2",
    ],
    "extended_modern": ["openai_clip_vit_l14", "jina_clip_v2", "qwen3_vl_embed_2b"],
    "extended_gme": ["gme_qwen2_vl_2b"],
}
MODELS = MODEL_GROUPS[ENV_GROUP]

# "video": single-clip and sliding-window protocols. "image": one still per item,
# so only the single-clip protocol (the frame is repeated to fill the clip).
DATASETS = {
    "tvpreid": {"label": "TVPReid", "subsets": ["prid", "ilids", "duke"], "protocols": "video"},
    "rstpreid": {"label": "RSTPReid", "subsets": ["test"], "protocols": "image"},
    "groot_mot17": {"label": "GroOT-MOT17", "subsets": ["all", "appearance", "action", "combined"], "protocols": "video"},
}
SPLIT = "test"
DEVICE = "cuda"
BATCH = 4
TEXT_BATCH = 16
POOLS = ("mean", "mean_s8", "max", "query_max")

# 1B-s2 is built for 4-frame clips; every other model uses 8.
NATIVE_FRAMES = {"internvideo2_s2_1b": 4}
MODEL_BATCH = {
    "siglip2": 1,
    "pe_core_l14": 1,
    "irra": 2,
    "internvideo2_s2_1b": 1,
    "internvideo2": 2,
    "languagebind": 2,
    "openai_clip_vit_l14": 4,
    "jina_clip_v2": 1,
    "gme_qwen2_vl_2b": 1,
    "qwen3_vl_embed_2b": 1,
}
MODEL_TEXT_BATCH = {"jina_clip_v2": 8, "gme_qwen2_vl_2b": 8, "qwen3_vl_embed_2b": 1}

SINGLE_PROTOCOLS = [
    {"name": "uniform8", "num_frames": 8, "frame_sample": "uniform", "family": "clip8"},
    {"name": "uniform4", "num_frames": 4, "frame_sample": "uniform", "family": "s2"},
    {"name": "middle4", "num_frames": 4, "frame_sample": "middle", "family": "s2", "video_only": True},
]
WINDOW_PROTOCOLS = [
    {"name": "vt_1fps_n12", "sample_fps": 1.0, "max_frames": 12, "stride": 4},
    {"name": "vt_2fps_n32", "sample_fps": 2.0, "max_frames": 32, "stride": 4},
    {"name": "reid_8fps_n64", "sample_fps": 8.0, "max_frames": 64, "stride": 4},
]

PRETTY = {
    "irra": "IRRA",
    "pe_core_l14": "Perception Encoder L/14",
    "siglip2": "SigLIP 2 So400m",
    "internvideo2": "InternVideo2 CLIP-S",
    "internvideo2_s2_1b": "InternVideo2-1B-s2",
    "languagebind": "LanguageBind",
    "xclip": "X-CLIP",
    "openai_clip_vit_l14": "OpenAI CLIP L/14",
    "jina_clip_v2": "Jina CLIP v2",
    "gme_qwen2_vl_2b": "GME-Qwen2-VL-2B",
    "qwen3_vl_embed_2b": "Qwen3-VL-Embedding-2B",
}

WORK = Path("/kaggle/working") if Path("/kaggle/working").is_dir() else Path("results")
RESULTS_ROOT = WORK / "zero_shot_results"
RESULTS_DIR = RESULTS_ROOT / ENV_GROUP
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
unknown = [d for d in RUN_DATASETS if d not in DATASETS]
if unknown:
    raise ValueError(f"Unknown datasets {unknown}; choose from {list(DATASETS)}")
print("Group", ENV_GROUP, "models", MODELS, flush=True)
print("Datasets", RUN_DATASETS, "results", RESULTS_DIR, flush=True)

Group base models ['siglip2', 'pe_core_l14', 'irra', 'internvideo2_s2_1b', 'xclip', 'languagebind', 'internvideo2']
Datasets ['tvpreid', 'rstpreid', 'groot_mot17'] results /kaggle/working/zero_shot_results/base

## 2. Setup

Clones the repo (and OpenGVLab/InternVideo when 1B-s2 is in the group), installs the group's dependencies, checks the package version, and loads the Hugging Face token. If `transformers` was already imported with a different version, restart the session and run again.

In [2]:
import os
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version

SHAWAF_URL = "https://github.com/BASSAT-BASSAT/Benchmarking-Video-Image-language-models-for-Tracklet-retrieval-.git"
INTERNVIDEO_URL = "https://github.com/OpenGVLab/InternVideo.git"
EXPECTED = "0.1.18"
TORCH_INDEX = "https://download.pytorch.org/whl/cu126"


def run(cmd, cwd=None):
    print("+", " ".join(map(str, cmd)), flush=True)
    subprocess.check_call([str(part) for part in cmd], cwd=str(cwd) if cwd else None)


def installed(name):
    try:
        return version(name)
    except PackageNotFoundError:
        return None


def sync_repo(url, path):
    if path.exists():
        run(["git", "fetch", "origin"], cwd=path)
        run(["git", "reset", "--hard", "origin/main"], cwd=path)
    else:
        run(["git", "clone", url, str(path)])


NEEDS_INTERNVIDEO = "internvideo2_s2_1b" in MODELS
ON_KAGGLE = Path("/kaggle/working").is_dir()
transformers_before = installed("transformers")
transformers_loaded = "transformers" in sys.modules

if ON_KAGGLE:
    shawaf_dir = Path("/kaggle/working/shawaf-vlm")
    intern_dir = Path("/kaggle/working/InternVideo")
    sync_repo(SHAWAF_URL, shawaf_dir)
    if NEEDS_INTERNVIDEO:
        sync_repo(INTERNVIDEO_URL, intern_dir)
    if ENV_GROUP == "base":
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[all]"])
        run(
            [
                sys.executable, "-m", "pip", "install", "-q",
                "einops", "timm", "av", "imageio", "librosa", "soundfile",
                "pandas", "pyyaml", "scipy", "wandb", "gdown",
            ]
        )
        try:
            run([sys.executable, "-m", "pip", "install", "-q", "decord"])
        except subprocess.CalledProcessError:
            print("decord wheel failed; the 1B-s2 path stubs it and uses PyAV", flush=True)
    else:
        if not (installed("torch") or "").startswith("2.8.0"):
            run([sys.executable, "-m", "pip", "install", "-q", "--index-url", TORCH_INDEX, "torch==2.8.0", "torchvision==0.23.0"])
        run([sys.executable, "-m", "pip", "install", "-q", "-e", f"{shawaf_dir}[{ENV_GROUP}]", "gdown>=5.2", "pandas"])
else:
    here = Path.cwd().resolve()
    shawaf_dir = here
    for candidate in [here, *here.parents]:
        if (candidate / "shawaf_vlm").is_dir() and (candidate / "pyproject.toml").is_file():
            shawaf_dir = candidate
            break
    intern_dir = shawaf_dir / "InternVideo"
    if NEEDS_INTERNVIDEO and not intern_dir.is_dir():
        run(["git", "clone", INTERNVIDEO_URL, str(intern_dir)], cwd=shawaf_dir)

transformers_after = installed("transformers")
if transformers_loaded and transformers_after != transformers_before:
    raise RuntimeError(
        f"transformers changed from {transformers_before} to {transformers_after} after it was "
        "imported. Restart the session, then Run All again."
    )

if NEEDS_INTERNVIDEO:
    os.environ["INTERNVIDEO_ROOT"] = str(intern_dir)
if str(shawaf_dir) not in sys.path:
    sys.path.insert(0, str(shawaf_dir))
for name in list(sys.modules):
    if name == "shawaf_vlm" or name.startswith("shawaf_vlm."):
        del sys.modules[name]

import shawaf_vlm

print("shawaf_vlm", shawaf_vlm.__version__, shawaf_vlm.__file__, flush=True)
print("transformers", transformers_after, flush=True)
if shawaf_vlm.__version__ != EXPECTED:
    raise RuntimeError(
        f"Expected shawaf_vlm {EXPECTED}, found {shawaf_vlm.__version__}. "
        "Restart the session and run this cell again after origin/main updates."
    )

token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
if not token and ON_KAGGLE:
    try:
        from kaggle_secrets import UserSecretsClient

        token = UserSecretsClient().get_secret("hugging_face")
    except Exception as exc:
        print("No hugging_face secret:", type(exc).__name__, flush=True)
if token:
    os.environ["HF_TOKEN"] = token
    os.environ["HUGGING_FACE_HUB_TOKEN"] = token
    from huggingface_hub import login

    login(token=token, add_to_git_credential=False)
    print("Hugging Face token loaded", flush=True)
elif NEEDS_INTERNVIDEO:
    raise RuntimeError(
        "Hugging Face token missing. InternVideo2-1B-s2 is gated: add a Kaggle secret "
        "named hugging_face and attach it to this notebook."
    )
else:
    print("No Hugging Face token; public datasets and models only", flush=True)

+ git clone https://github.com/BASSAT-BASSAT/Benchmarking-Video-Image-language-models-for-Tracklet-retrieval-.git /kaggle/working/shawaf-vlm

Cloning into '/kaggle/working/shawaf-vlm'...

+ git clone https://github.com/OpenGVLab/InternVideo.git /kaggle/working/InternVideo

Cloning into '/kaggle/working/InternVideo'...

+ /usr/bin/python3 -m pip install -q -e /kaggle/working/shawaf-vlm[all]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 2.0 MB/s eta 0:00:00
+ /usr/bin/python3 -m pip install -q einops timm av imageio librosa soundfile pandas pyyaml scipy wandb gdown
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.8/35.8 MB 55.2 MB/s eta 0:00:00
+ /usr/bin/python3 -m pip install -q decord
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.6/13.6 MB 78.9 MB/s eta 0:00:00
shawaf_vlm 0.1.18 /kaggle/working/shawaf-vlm/shawaf_vlm/__init__.py
transformers 5.0.0

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face token loaded

## 3. Datasets

TVPReid and GroOT-MOT17 download only their test mp4s from the Hugging Face Hub (`bassatbassat/TVPReid`, `bassatbassat/GroOT-MOT17`). RSTPReid downloads its archive from the authors' Google Drive, or uses an attached Kaggle input that contains `data_captions.json` and `imgs/`.

In [3]:
import pandas as pd
from IPython.display import Markdown, display

from shawaf_vlm.data import (
    discover_local_groot,
    download_groot,
    download_rstpreid,
    download_tvpreid,
    load_groot,
    load_rstpreid,
    load_tvpreid,
)

DATA_ROOTS = {}
if "tvpreid" in RUN_DATASETS:
    DATA_ROOTS["tvpreid"] = download_tvpreid(configs=tuple(DATASETS["tvpreid"]["subsets"]), split=SPLIT)
if "rstpreid" in RUN_DATASETS:
    DATA_ROOTS["rstpreid"] = download_rstpreid()
if "groot_mot17" in RUN_DATASETS:
    DATA_ROOTS["groot_mot17"] = discover_local_groot() or download_groot(
        configs=tuple(DATASETS["groot_mot17"]["subsets"]), split=SPLIT
    )


def load_split(dataset, subset):
    root = DATA_ROOTS[dataset]
    if dataset == "tvpreid":
        return load_tvpreid(subset, split=SPLIT, root=root)
    if dataset == "rstpreid":
        return load_rstpreid(root, split=subset)
    if dataset == "groot_mot17":
        return load_groot(subset, split=SPLIT, root=root)
    raise ValueError(dataset)


summary = []
for dataset in RUN_DATASETS:
    for subset in DATASETS[dataset]["subsets"]:
        splits = load_split(dataset, subset)
        per_id = pd.Series([g.person_id for g in splits.gallery]).value_counts()
        positives = pd.Series([per_id.get(q.person_id, 0) for q in splits.query])
        summary.append(
            {
                "dataset": DATASETS[dataset]["label"],
                "subset": subset,
                "queries": len(splits.query),
                "gallery": len(splits.gallery),
                "identities": int(per_id.size),
                "positives / query": round(float(positives.mean()), 2),
                "root": str(DATA_ROOTS[dataset]),
            }
        )
DATASET_SUMMARY = pd.DataFrame(summary)
display(DATASET_SUMMARY)

Hub repo : bassatbassat/TVPReid
Split    : test only
Configs  : prid, ilids, duke

Metadata:   0%|          | 0/3 [00:00<?, ?file/s]

Videos   : 820 files (820 to fetch)

Videos test:   0%|          | 0/820 [00:00<?, ?file/s]

RSTPReid : downloading Drive id 1HTeDZUVrZr6nL56ZlkYBNqjSWh3IGV2X

Downloading...
From (original): https://drive.google.com/uc?id=1HTeDZUVrZr6nL56ZlkYBNqjSWh3IGV2X
From (redirected): https://drive.google.com/uc?id=1HTeDZUVrZr6nL56ZlkYBNqjSWh3IGV2X&confirm=t&uuid=60064148-c0bf-464c-a348-ad09fb07bc9b
To: /kaggle/working/RSTPReid/RSTPReid.zip
100%|██████████| 502M/502M [00:06<00:00, 74.6MB/s]

RSTPReid : /kaggle/working/RSTPReid
Hub repo : bassatbassat/GroOT-MOT17
Split    : test only
Configs  : all, appearance, action, combined

Metadata:   0%|          | 0/4 [00:00<?, ?file/s]

Videos   : 454 files (454 to fetch)

Videos test:   0%|          | 0/454 [00:00<?, ?file/s]

,dataset,subset,queries,gallery,identities,positives / query,root
0,TVPReid,prid,284,142,142,1.0,/kaggle/working/TVPReid
1,TVPReid,ilids,150,75,75,1.0,/kaggle/working/TVPReid
2,TVPReid,duke,1206,603,603,1.0,/kaggle/working/TVPReid
3,RSTPReid,test,2000,1000,200,5.0,/kaggle/working/RSTPReid
4,GroOT-MOT17,all,798,454,454,1.0,/kaggle/working/GroOT-MOT17
5,GroOT-MOT17,appearance,344,454,454,1.0,/kaggle/working/GroOT-MOT17
6,GroOT-MOT17,action,454,454,454,1.0,/kaggle/working/GroOT-MOT17
7,GroOT-MOT17,combined,344,454,454,1.0,/kaggle/working/GroOT-MOT17

## 4. Run

Order: model, then dataset, then protocol, then subset. Each finished row is saved to `zero_shot_results/<group>/<dataset>/<model>_<subset>_<protocol>_<pool>.json` and skipped on rerun.

GroOT's four subsets share one gallery, so gallery embeddings are reused across `all`, `appearance`, `action`, and `combined` within a protocol (those rows are marked `gallery_cached`; speed is read from the uncached row).

In [4]:
import gc
import json
import traceback
from datetime import datetime, timezone

from shawaf_vlm.eval_loop import evaluate_text_to_tracklet, evaluate_text_to_tracklet_windows
from shawaf_vlm.metrics import format_metrics
from shawaf_vlm.models import build_encoder
from shawaf_vlm.models.runtime import ensure_cuda_healthy

METRIC_KEYS = [
    "Rank-1", "Rank-5", "Rank-10", "Rank-20", "Rank-50",
    "mAP", "MdR", "MnR", "nDCG@10", "mINP",
    "num_valid_queries", "num_gallery", "num_clips",
    "decode_s", "video_s", "text_s", "score_s", "total_s",
    "video_ms_per_item", "peak_gpu_gb", "reserved_gpu_gb",
]


class StopModel(Exception):
    """CUDA OOM: stop this model, keep benchmark settings unchanged."""


class GalleryCache:
    """Reuse the last gallery embedding when the exact same frame lists come back."""

    def __init__(self, encoder):
        self.encoder = encoder
        self._key = None
        self._features = None
        self.last_hit = False

    def encode_videos(self, videos, batch_size=4):
        key = tuple(tuple(str(path) for path in clip) for clip in videos)
        if key == self._key:
            self.last_hit = True
            return self._features
        self.last_hit = False
        self._features = self.encoder.encode_videos(videos, batch_size=batch_size)
        self._key = key
        return self._features

    def encode_texts(self, texts, batch_size=32):
        return self.encoder.encode_texts(texts, batch_size=batch_size)

    def __getattr__(self, name):
        return getattr(self.encoder, name)


def family(model):
    return "s2" if model in NATIVE_FRAMES else "clip8"


def protocols_for(model, dataset):
    kind = DATASETS[dataset]["protocols"]
    specs = []
    for spec in SINGLE_PROTOCOLS:
        if spec["family"] != family(model):
            continue
        if kind == "image" and spec.get("video_only"):
            continue
        specs.append({**spec, "type": "single"})
    if kind == "video":
        specs.extend({**spec, "type": "window"} for spec in WINDOW_PROTOCOLS)
    return specs


def sampling_text(model, spec):
    if spec["type"] == "single":
        return f"{spec['frame_sample']} {spec['num_frames']} frames"
    return (
        f"sliding windows of {NATIVE_FRAMES.get(model, 8)}, stride {spec['stride']}, "
        f"{spec['sample_fps']:g} fps, cap {spec['max_frames']} frames"
    )


def result_path(dataset, model, subset, protocol, pool):
    return RESULTS_DIR / dataset / f"{model}_{subset}_{protocol}_{pool}.json"


def expected_paths(dataset, model, subset, spec):
    pools = ["none"] if spec["type"] == "single" else list(POOLS)
    return [result_path(dataset, model, subset, spec["name"], pool) for pool in pools]


def is_complete(path):
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("status") == "complete"
    except Exception:
        return False


def save_row(dataset, model, subset, spec, pool, metrics=None, error=None, cached=False):
    row = {
        "group": ENV_GROUP,
        "dataset": dataset,
        "subset": subset,
        "model": model,
        "protocol": spec["name"],
        "protocol_type": spec["type"],
        "pool": pool,
        "sampling": sampling_text(model, spec),
        "gallery_cached": bool(cached),
        "status": "failed" if error else "complete",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    if metrics is not None:
        row.update({key: float(metrics[key]) for key in METRIC_KEYS if key in metrics})
    if error is not None:
        row["error"] = str(error)[:2000]
    path = result_path(dataset, model, subset, spec["name"], pool)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(row, indent=2), encoding="utf-8")


def clean_cuda():
    gc.collect()
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def run_one(encoder, model, dataset, subset, spec):
    paths = expected_paths(dataset, model, subset, spec)
    if all(is_complete(path) for path in paths):
        print(f"skip {model} {dataset}/{subset} {spec['name']}", flush=True)
        return
    splits = load_split(dataset, subset)
    cache = WORK / "frame_cache" / dataset
    batch = MODEL_BATCH.get(model, BATCH)
    text_batch = MODEL_TEXT_BATCH.get(model, TEXT_BATCH)
    print(f"== {PRETTY.get(model, model)} | {dataset}/{subset} | {spec['name']} ({sampling_text(model, spec)})", flush=True)
    try:
        if spec["type"] == "single":
            scored = {
                "none": evaluate_text_to_tracklet(
                    encoder,
                    splits,
                    num_frames=spec["num_frames"],
                    batch_size=batch,
                    text_batch_size=text_batch,
                    junk_same_camera=False,
                    frame_cache=cache,
                    frame_sample=spec["frame_sample"],
                )
            }
        else:
            scored = evaluate_text_to_tracklet_windows(
                encoder,
                splits,
                num_frames=NATIVE_FRAMES.get(model, 8),
                stride=spec["stride"],
                sample_fps=spec["sample_fps"],
                max_frames=spec["max_frames"],
                pools=POOLS,
                batch_size=batch,
                text_batch_size=text_batch,
                junk_same_camera=False,
                frame_cache=cache,
            )
    except RuntimeError as exc:
        pools = ["none"] if spec["type"] == "single" else list(POOLS)
        for pool in pools:
            save_row(dataset, model, subset, spec, pool, error=exc)
        if "out of memory" in str(exc).lower():
            raise StopModel(str(exc)) from exc
        raise
    for pool, metrics in scored.items():
        save_row(dataset, model, subset, spec, pool, metrics=metrics, cached=encoder.last_hit)
        print(f"-- {pool}: R1 {metrics['Rank-1']:.2f}  mAP {metrics['mAP']:.2f}  mINP {metrics.get('mINP', float('nan')):.2f}", flush=True)

In [5]:
ensure_cuda_healthy(DEVICE)

for model in MODELS:
    jobs = [
        (dataset, spec, subset)
        for dataset in RUN_DATASETS
        for spec in protocols_for(model, dataset)
        for subset in DATASETS[dataset]["subsets"]
    ]
    todo = [job for job in jobs if not all(is_complete(p) for p in expected_paths(job[0], model, job[2], job[1]))]
    print(f"\n######## {PRETTY.get(model, model)}: {len(todo)} of {len(jobs)} runs to do", flush=True)
    if not todo:
        continue
    try:
        encoder = GalleryCache(build_encoder(model, device=DEVICE))
    except Exception:
        traceback.print_exc()
        print(f"Could not build {model}; skipping it", flush=True)
        clean_cuda()
        continue
    try:
        for dataset, spec, subset in todo:
            run_one(encoder, model, dataset, subset, spec)
    except StopModel as exc:
        print(f"CUDA OOM on {model}; stopping this model: {exc}", flush=True)
    finally:
        del encoder
        clean_cuda()

print("Done", flush=True)

######## SigLIP 2 So400m: 29 of 29 runs to do

The image processor of type `SiglipImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== SigLIP 2 So400m | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

siglip2 videos: 100%|██████████| 142/142 [00:59<00:00,  2.38batch/s]
siglip2 texts: 100%|██████████| 18/18 [00:00<00:00, 18.45batch/s]

-- none: R1 33.45  mAP 48.64  mINP 48.64
== SigLIP 2 So400m | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

siglip2 videos: 100%|██████████| 75/75 [00:33<00:00,  2.25batch/s]
siglip2 texts: 100%|██████████| 10/10 [00:00<00:00, 18.38batch/s]

-- none: R1 14.67  mAP 25.85  mINP 25.85
== SigLIP 2 So400m | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

siglip2 videos: 100%|██████████| 603/603 [04:23<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 76/76 [00:04<00:00, 18.09batch/s]

-- none: R1 17.58  mAP 27.45  mINP 27.45
== SigLIP 2 So400m | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos: 100%|██████████| 163/163 [01:11<00:00,  2.28batch/s]
siglip2 texts: 100%|██████████| 18/18 [00:00<00:00, 18.27batch/s]

-- mean: R1 32.75  mAP 48.01  mINP 48.01
-- mean_s8: R1 32.75  mAP 48.01  mINP 48.01
-- max: R1 33.10  mAP 48.01  mINP 48.01
-- query_max: R1 33.10  mAP 47.69  mINP 47.69
== SigLIP 2 So400m | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos: 100%|██████████| 76/76 [00:33<00:00,  2.30batch/s]
siglip2 texts: 100%|██████████| 10/10 [00:00<00:00, 19.10batch/s]

-- mean: R1 17.33  mAP 26.25  mINP 26.25
-- mean_s8: R1 17.33  mAP 26.25  mINP 26.25
-- max: R1 17.33  mAP 26.25  mINP 26.25
-- query_max: R1 17.33  mAP 26.30  mINP 26.30
== SigLIP 2 So400m | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos: 100%|██████████| 1001/1001 [07:17<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 76/76 [00:04<00:00, 18.10batch/s]

-- mean: R1 18.16  mAP 27.96  mINP 27.96
-- mean_s8: R1 18.16  mAP 27.96  mINP 27.96
-- max: R1 17.91  mAP 27.87  mINP 27.87
-- query_max: R1 20.07  mAP 29.79  mINP 29.79
== SigLIP 2 So400m | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos: 100%|██████████| 345/345 [02:31<00:00,  2.28batch/s]
siglip2 texts: 100%|██████████| 18/18 [00:00<00:00, 18.18batch/s]

-- mean: R1 32.75  mAP 48.45  mINP 48.45
-- mean_s8: R1 33.45  mAP 48.97  mINP 48.97
-- max: R1 34.15  mAP 48.48  mINP 48.48
-- query_max: R1 30.28  mAP 46.89  mINP 46.89
== SigLIP 2 So400m | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos: 100%|██████████| 127/127 [00:55<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 10/10 [00:00<00:00, 18.99batch/s]

-- mean: R1 16.00  mAP 27.27  mINP 27.27
-- mean_s8: R1 15.33  mAP 26.96  mINP 26.96
-- max: R1 15.33  mAP 26.69  mINP 26.69
-- query_max: R1 16.00  mAP 27.08  mINP 27.08
== SigLIP 2 So400m | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos: 100%|██████████| 2561/2561 [18:39<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 76/76 [00:04<00:00, 18.16batch/s]

-- mean: R1 19.98  mAP 29.58  mINP 29.58
-- mean_s8: R1 19.24  mAP 28.83  mINP 28.83
-- max: R1 17.83  mAP 27.78  mINP 27.78
-- query_max: R1 20.81  mAP 31.73  mINP 31.73
== SigLIP 2 So400m | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos: 100%|██████████| 1435/1435 [10:26<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 18/18 [00:00<00:00, 18.40batch/s]

-- mean: R1 32.04  mAP 48.38  mINP 48.38
-- mean_s8: R1 32.04  mAP 48.73  mINP 48.73
-- max: R1 32.04  mAP 48.08  mINP 48.08
-- query_max: R1 35.56  mAP 50.84  mINP 50.84
== SigLIP 2 So400m | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos: 100%|██████████| 632/632 [04:36<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 10/10 [00:00<00:00, 18.94batch/s]

-- mean: R1 16.67  mAP 27.20  mINP 27.20
-- mean_s8: R1 16.67  mAP 27.19  mINP 27.19
-- max: R1 14.67  mAP 25.90  mINP 25.90
-- query_max: R1 18.67  mAP 28.88  mINP 28.88
== SigLIP 2 So400m | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos: 100%|██████████| 8522/8522 [1:02:01<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 76/76 [00:04<00:00, 18.14batch/s]

-- mean: R1 19.40  mAP 29.50  mINP 29.50
-- mean_s8: R1 19.40  mAP 29.34  mINP 29.34
-- max: R1 17.25  mAP 26.44  mINP 26.44
-- query_max: R1 21.97  mAP 33.03  mINP 33.03
== SigLIP 2 So400m | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

siglip2 videos: 100%|██████████| 1000/1000 [07:22<00:00,  2.26batch/s]
siglip2 texts: 100%|██████████| 125/125 [00:06<00:00, 18.01batch/s]

-- none: R1 41.00  mAP 29.34  mINP 2.07
== SigLIP 2 So400m | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

siglip2 videos: 100%|██████████| 454/454 [03:18<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 50/50 [00:02<00:00, 18.26batch/s]

-- none: R1 12.16  mAP 17.81  mINP 17.81
== SigLIP 2 So400m | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.79batch/s]

-- none: R1 25.58  mAP 34.06  mINP 34.06
== SigLIP 2 So400m | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

siglip2 texts: 100%|██████████| 29/29 [00:01<00:00, 18.76batch/s]

-- none: R1 1.98  mAP 5.49  mINP 5.49
== SigLIP 2 So400m | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.76batch/s]

-- none: R1 26.16  mAP 35.86  mINP 35.86
== SigLIP 2 So400m | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

siglip2 videos: 100%|██████████| 556/556 [04:02<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 50/50 [00:02<00:00, 18.29batch/s]

-- mean: R1 8.65  mAP 13.54  mINP 13.54
-- mean_s8: R1 8.65  mAP 13.54  mINP 13.54
-- max: R1 8.02  mAP 13.22  mINP 13.22
-- query_max: R1 8.27  mAP 13.41  mINP 13.41
== SigLIP 2 So400m | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.81batch/s]

-- mean: R1 18.31  mAP 26.10  mINP 26.10
-- mean_s8: R1 18.31  mAP 26.10  mINP 26.10
-- max: R1 17.15  mAP 25.44  mINP 25.44
-- query_max: R1 17.44  mAP 25.63  mINP 25.63
== SigLIP 2 So400m | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

siglip2 texts: 100%|██████████| 29/29 [00:01<00:00, 18.84batch/s]

-- mean: R1 1.32  mAP 4.02  mINP 4.02
-- mean_s8: R1 1.32  mAP 4.02  mINP 4.02
-- max: R1 1.10  mAP 3.95  mINP 3.95
-- query_max: R1 1.32  mAP 4.14  mINP 4.14
== SigLIP 2 So400m | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.86batch/s]

-- mean: R1 20.35  mAP 28.55  mINP 28.55
-- mean_s8: R1 20.35  mAP 28.55  mINP 28.55
-- max: R1 20.93  mAP 28.75  mINP 28.75
-- query_max: R1 21.80  mAP 29.28  mINP 29.28
== SigLIP 2 So400m | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

siglip2 videos: 100%|██████████| 935/935 [06:47<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 50/50 [00:02<00:00, 18.17batch/s]

-- mean: R1 9.27  mAP 15.00  mINP 15.00
-- mean_s8: R1 9.77  mAP 15.21  mINP 15.21
-- max: R1 9.15  mAP 14.70  mINP 14.70
-- query_max: R1 9.77  mAP 15.16  mINP 15.16
== SigLIP 2 So400m | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.84batch/s]

-- mean: R1 18.90  mAP 28.52  mINP 28.52
-- mean_s8: R1 20.06  mAP 29.00  mINP 29.00
-- max: R1 18.90  mAP 28.10  mINP 28.10
-- query_max: R1 19.77  mAP 28.63  mINP 28.63
== SigLIP 2 So400m | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

siglip2 texts: 100%|██████████| 29/29 [00:01<00:00, 18.72batch/s]

-- mean: R1 1.98  mAP 4.76  mINP 4.76
-- mean_s8: R1 1.98  mAP 4.77  mINP 4.77
-- max: R1 1.76  mAP 4.54  mINP 4.54
-- query_max: R1 2.20  mAP 4.94  mINP 4.94
== SigLIP 2 So400m | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.73batch/s]

-- mean: R1 23.26  mAP 32.49  mINP 32.49
-- mean_s8: R1 23.26  mAP 32.47  mINP 32.47
-- max: R1 21.22  mAP 31.45  mINP 31.45
-- query_max: R1 22.97  mAP 33.00  mINP 33.00
== SigLIP 2 So400m | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

siglip2 videos: 100%|██████████| 3558/3558 [25:51<00:00,  2.29batch/s]
siglip2 texts: 100%|██████████| 50/50 [00:03<00:00, 16.18batch/s]

-- mean: R1 12.03  mAP 17.83  mINP 17.83
-- mean_s8: R1 11.78  mAP 17.64  mINP 17.64
-- max: R1 11.65  mAP 17.41  mINP 17.41
-- query_max: R1 11.78  mAP 17.99  mINP 17.99
== SigLIP 2 So400m | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.86batch/s]

-- mean: R1 25.29  mAP 34.49  mINP 34.49
-- mean_s8: R1 24.71  mAP 34.06  mINP 34.06
-- max: R1 24.42  mAP 33.75  mINP 33.75
-- query_max: R1 24.42  mAP 34.68  mINP 34.68
== SigLIP 2 So400m | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

siglip2 texts: 100%|██████████| 29/29 [00:01<00:00, 18.78batch/s]

-- mean: R1 1.98  mAP 5.21  mINP 5.21
-- mean_s8: R1 1.98  mAP 5.20  mINP 5.20
-- max: R1 1.98  mAP 5.04  mINP 5.04
-- query_max: R1 2.20  mAP 5.34  mINP 5.34
== SigLIP 2 So400m | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

siglip2 texts: 100%|██████████| 22/22 [00:01<00:00, 18.84batch/s]

-- mean: R1 25.00  mAP 35.29  mINP 35.29
-- mean_s8: R1 25.00  mAP 35.47  mINP 35.47
-- max: R1 25.87  mAP 35.10  mINP 35.10
-- query_max: R1 27.91  mAP 38.92  mINP 38.92

######## Perception Encoder L/14: 29 of 29 runs to do
Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== Perception Encoder L/14 | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

pe_core_l14 videos: 100%|██████████| 142/142 [00:35<00:00,  4.02batch/s]
pe_core_l14 texts: 100%|██████████| 18/18 [00:00<00:00, 32.48batch/s]

-- none: R1 38.03  mAP 51.55  mINP 51.55
== Perception Encoder L/14 | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

pe_core_l14 videos: 100%|██████████| 75/75 [00:18<00:00,  3.99batch/s]
pe_core_l14 texts: 100%|██████████| 10/10 [00:00<00:00, 42.33batch/s]

-- none: R1 18.00  mAP 30.62  mINP 30.62
== Perception Encoder L/14 | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

pe_core_l14 videos: 100%|██████████| 603/603 [02:27<00:00,  4.09batch/s]
pe_core_l14 texts: 100%|██████████| 76/76 [00:01<00:00, 41.15batch/s]

-- none: R1 14.84  mAP 24.89  mINP 24.89
== Perception Encoder L/14 | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 videos: 100%|██████████| 163/163 [00:39<00:00,  4.09batch/s]
pe_core_l14 texts: 100%|██████████| 18/18 [00:00<00:00, 41.73batch/s]

-- mean: R1 35.56  mAP 48.94  mINP 48.94
-- mean_s8: R1 35.56  mAP 48.94  mINP 48.94
-- max: R1 35.56  mAP 48.89  mINP 48.89
-- query_max: R1 34.51  mAP 48.33  mINP 48.33
== Perception Encoder L/14 | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 videos: 100%|██████████| 76/76 [00:18<00:00,  4.07batch/s]
pe_core_l14 texts: 100%|██████████| 10/10 [00:00<00:00, 42.34batch/s]

-- mean: R1 16.67  mAP 29.79  mINP 29.79

-- mean_s8: R1 16.67  mAP 29.79  mINP 29.79
-- max: R1 16.67  mAP 29.79  mINP 29.79
-- query_max: R1 16.67  mAP 29.86  mINP 29.86
== Perception Encoder L/14 | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 videos: 100%|██████████| 1001/1001 [04:06<00:00,  4.07batch/s]
pe_core_l14 texts: 100%|██████████| 76/76 [00:01<00:00, 41.09batch/s]

-- mean: R1 14.01  mAP 24.49  mINP 24.49
-- mean_s8: R1 14.01  mAP 24.49  mINP 24.49
-- max: R1 14.68  mAP 24.75  mINP 24.75
-- query_max: R1 15.09  mAP 25.34  mINP 25.34
== Perception Encoder L/14 | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 videos: 100%|██████████| 345/345 [01:24<00:00,  4.07batch/s]
pe_core_l14 texts: 100%|██████████| 18/18 [00:00<00:00, 41.77batch/s]

-- mean: R1 34.15  mAP 49.05  mINP 49.05
-- mean_s8: R1 34.15  mAP 49.09  mINP 49.09
-- max: R1 34.51  mAP 49.08  mINP 49.08
-- query_max: R1 34.86  mAP 49.00  mINP 49.00
== Perception Encoder L/14 | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 videos: 100%|██████████| 127/127 [00:31<00:00,  4.09batch/s]
pe_core_l14 texts: 100%|██████████| 10/10 [00:00<00:00, 42.51batch/s]

-- mean: R1 19.33  mAP 31.47  mINP 31.47
-- mean_s8: R1 19.33  mAP 31.58  mINP 31.58
-- max: R1 19.33  mAP 31.32  mINP 31.32
-- query_max: R1 19.33  mAP 31.62  mINP 31.62
== Perception Encoder L/14 | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 videos: 100%|██████████| 2561/2561 [10:28<00:00,  4.07batch/s]
pe_core_l14 texts: 100%|██████████| 76/76 [00:01<00:00, 41.22batch/s]

-- mean: R1 13.76  mAP 24.46  mINP 24.46
-- mean_s8: R1 13.76  mAP 24.24  mINP 24.24
-- max: R1 13.85  mAP 23.62  mINP 23.62
-- query_max: R1 16.00  mAP 26.92  mINP 26.92
== Perception Encoder L/14 | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 videos: 100%|██████████| 1435/1435 [05:51<00:00,  4.08batch/s]
pe_core_l14 texts: 100%|██████████| 18/18 [00:00<00:00, 41.70batch/s]

-- mean: R1 38.03  mAP 51.94  mINP 51.94
-- mean_s8: R1 38.38  mAP 52.04  mINP 52.04
-- max: R1 36.62  mAP 51.50  mINP 51.50
-- query_max: R1 35.56  mAP 50.31  mINP 50.31
== Perception Encoder L/14 | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 videos: 100%|██████████| 632/632 [02:35<00:00,  4.08batch/s]
pe_core_l14 texts: 100%|██████████| 10/10 [00:00<00:00, 42.13batch/s]

-- mean: R1 18.00  mAP 30.69  mINP 30.69
-- mean_s8: R1 18.67  mAP 31.46  mINP 31.46
-- max: R1 18.00  mAP 31.12  mINP 31.12
-- query_max: R1 19.33  mAP 32.55  mINP 32.55
== Perception Encoder L/14 | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 videos: 100%|██████████| 8522/8522 [34:50<00:00,  4.08batch/s]
pe_core_l14 texts: 100%|██████████| 76/76 [00:01<00:00, 40.96batch/s]

-- mean: R1 15.01  mAP 25.18  mINP 25.18
-- mean_s8: R1 14.34  mAP 24.77  mINP 24.77
-- max: R1 13.27  mAP 22.71  mINP 22.71
-- query_max: R1 17.66  mAP 28.12  mINP 28.12
== Perception Encoder L/14 | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

pe_core_l14 videos: 100%|██████████| 1000/1000 [04:11<00:00,  3.98batch/s]
pe_core_l14 texts: 100%|██████████| 125/125 [00:03<00:00, 40.89batch/s]

-- none: R1 37.40  mAP 29.09  mINP 2.42
== Perception Encoder L/14 | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

pe_core_l14 videos: 100%|██████████| 454/454 [01:51<00:00,  4.08batch/s]
pe_core_l14 texts: 100%|██████████| 50/50 [00:01<00:00, 42.47batch/s]

-- none: R1 12.28  mAP 18.78  mINP 18.78
== Perception Encoder L/14 | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 42.30batch/s]

-- none: R1 24.42  mAP 35.11  mINP 35.11
== Perception Encoder L/14 | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

pe_core_l14 texts: 100%|██████████| 29/29 [00:00<00:00, 43.92batch/s]

-- none: R1 3.08  mAP 6.40  mINP 6.40
== Perception Encoder L/14 | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.02batch/s]

-- none: R1 28.20  mAP 37.49  mINP 37.49
== Perception Encoder L/14 | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 videos: 100%|██████████| 556/556 [02:16<00:00,  4.09batch/s]
pe_core_l14 texts: 100%|██████████| 50/50 [00:01<00:00, 42.46batch/s]

-- mean: R1 9.15  mAP 15.03  mINP 15.03
-- mean_s8: R1 9.15  mAP 15.03  mINP 15.03
-- max: R1 9.40  mAP 15.15  mINP 15.15
-- query_max: R1 9.52  mAP 15.21  mINP 15.21
== Perception Encoder L/14 | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.70batch/s]

-- mean: R1 18.31  mAP 27.97  mINP 27.97
-- mean_s8: R1 18.31  mAP 27.97  mINP 27.97
-- max: R1 18.60  mAP 28.04  mINP 28.04
-- query_max: R1 19.19  mAP 28.38  mINP 28.38
== Perception Encoder L/14 | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 texts: 100%|██████████| 29/29 [00:00<00:00, 43.97batch/s]

-- mean: R1 2.20  mAP 5.23  mINP 5.23
-- mean_s8: R1 2.20  mAP 5.23  mINP 5.23
-- max: R1 2.42  mAP 5.39  mINP 5.39
-- query_max: R1 2.20  mAP 5.22  mINP 5.22
== Perception Encoder L/14 | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.75batch/s]

-- mean: R1 22.09  mAP 30.97  mINP 30.97
-- mean_s8: R1 22.09  mAP 30.97  mINP 30.97
-- max: R1 21.80  mAP 30.91  mINP 30.91
-- query_max: R1 22.38  mAP 31.13  mINP 31.13
== Perception Encoder L/14 | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 videos: 100%|██████████| 935/935 [03:48<00:00,  4.09batch/s]
pe_core_l14 texts: 100%|██████████| 50/50 [00:01<00:00, 42.71batch/s]

-- mean: R1 11.65  mAP 17.89  mINP 17.89
-- mean_s8: R1 11.78  mAP 17.94  mINP 17.94
-- max: R1 11.15  mAP 17.55  mINP 17.55
-- query_max: R1 11.15  mAP 17.38  mINP 17.38
== Perception Encoder L/14 | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.29batch/s]

-- mean: R1 23.26  mAP 33.16  mINP 33.16
-- mean_s8: R1 23.84  mAP 33.46  mINP 33.46
-- max: R1 21.51  mAP 32.06  mINP 32.06
-- query_max: R1 22.38  mAP 32.33  mINP 32.33
== Perception Encoder L/14 | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 texts: 100%|██████████| 29/29 [00:00<00:00, 43.62batch/s]

-- mean: R1 2.86  mAP 6.32  mINP 6.32
-- mean_s8: R1 2.64  mAP 6.18  mINP 6.18
-- max: R1 3.30  mAP 6.55  mINP 6.55
-- query_max: R1 2.64  mAP 6.06  mINP 6.06
== Perception Encoder L/14 | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.52batch/s]

-- mean: R1 24.71  mAP 35.33  mINP 35.33
-- mean_s8: R1 25.00  mAP 35.43  mINP 35.43
-- max: R1 25.87  mAP 35.68  mINP 35.68
-- query_max: R1 26.16  mAP 35.70  mINP 35.70
== Perception Encoder L/14 | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 videos: 100%|██████████| 3558/3558 [14:31<00:00,  4.08batch/s]
pe_core_l14 texts: 100%|██████████| 50/50 [00:01<00:00, 42.99batch/s]

-- mean: R1 12.41  mAP 19.20  mINP 19.20
-- mean_s8: R1 12.28  mAP 19.11  mINP 19.11
-- max: R1 10.90  mAP 17.29  mINP 17.29
-- query_max: R1 11.78  mAP 18.54  mINP 18.54
== Perception Encoder L/14 | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.73batch/s]

-- mean: R1 25.00  mAP 36.25  mINP 36.25
-- mean_s8: R1 25.29  mAP 36.46  mINP 36.46
-- max: R1 22.09  mAP 32.40  mINP 32.40
-- query_max: R1 24.13  mAP 35.62  mINP 35.62
== Perception Encoder L/14 | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 texts: 100%|██████████| 29/29 [00:00<00:00, 43.85batch/s]

-- mean: R1 2.86  mAP 6.27  mINP 6.27
-- mean_s8: R1 2.42  mAP 5.97  mINP 5.97
-- max: R1 2.42  mAP 5.85  mINP 5.85
-- query_max: R1 2.42  mAP 5.60  mINP 5.60
== Perception Encoder L/14 | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

pe_core_l14 texts: 100%|██████████| 22/22 [00:00<00:00, 43.64batch/s]

-- mean: R1 29.36  mAP 39.19  mINP 39.19
-- mean_s8: R1 29.36  mAP 39.14  mINP 39.14
-- max: R1 26.16  mAP 35.99  mINP 35.99
-- query_max: R1 28.78  mAP 39.45  mINP 39.45

######## IRRA: 29 of 29 runs to do

Downloading...
From (original): https://drive.google.com/uc?id=1OBhFhpZpltRMZ88K6ceNUv4vZgevsFCW
From (redirected): https://drive.google.com/uc?id=1OBhFhpZpltRMZ88K6ceNUv4vZgevsFCW&confirm=t&uuid=95b4007e-8fa6-40bf-a2b5-270cb945436d
To: /root/.cache/shawaf/irra/irra_cuhk.zip
100%|██████████| 1.03G/1.03G [00:11<00:00, 89.3MB/s]

Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== IRRA | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

irra videos: 100%|██████████| 71/71 [00:05<00:00, 14.06batch/s]
irra texts: 100%|██████████| 18/18 [00:00<00:00, 71.80batch/s]

-- none: R1 65.49  mAP 75.30  mINP 75.30
== IRRA | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

irra videos: 100%|██████████| 38/38 [00:02<00:00, 15.13batch/s]
irra texts: 100%|██████████| 10/10 [00:00<00:00, 82.70batch/s]

-- none: R1 28.00  mAP 39.71  mINP 39.71

== IRRA | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

irra videos: 100%|██████████| 302/302 [00:20<00:00, 14.87batch/s]
irra texts: 100%|██████████| 76/76 [00:00<00:00, 80.18batch/s]

-- none: R1 35.82  mAP 48.14  mINP 48.14
== IRRA | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

irra videos: 100%|██████████| 82/82 [00:05<00:00, 14.78batch/s]
irra texts: 100%|██████████| 18/18 [00:00<00:00, 79.29batch/s]

-- mean: R1 63.03  mAP 73.31  mINP 73.31
-- mean_s8: R1 63.03  mAP 73.31  mINP 73.31
-- max: R1 63.38  mAP 73.42  mINP 73.42
-- query_max: R1 63.03  mAP 73.26  mINP 73.26
== IRRA | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

irra videos: 100%|██████████| 38/38 [00:02<00:00, 14.84batch/s]
irra texts: 100%|██████████| 10/10 [00:00<00:00, 81.96batch/s]

-- mean: R1 27.33  mAP 38.85  mINP 38.85
-- mean_s8: R1 27.33  mAP 38.85  mINP 38.85
-- max: R1 27.33  mAP 38.85  mINP 38.85
-- query_max: R1 27.33  mAP 38.86  mINP 38.86
== IRRA | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

irra videos: 100%|██████████| 501/501 [00:34<00:00, 14.71batch/s]
irra texts: 100%|██████████| 76/76 [00:00<00:00, 78.34batch/s]

-- mean: R1 35.66  mAP 47.86  mINP 47.86
-- mean_s8: R1 35.66  mAP 47.86  mINP 47.86
-- max: R1 35.57  mAP 47.77  mINP 47.77
-- query_max: R1 35.90  mAP 48.49  mINP 48.49
== IRRA | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

irra videos: 100%|██████████| 173/173 [00:11<00:00, 15.15batch/s]
irra texts: 100%|██████████| 18/18 [00:00<00:00, 81.61batch/s]

-- mean: R1 62.32  mAP 73.33  mINP 73.33
-- mean_s8: R1 63.03  mAP 73.76  mINP 73.76
-- max: R1 62.68  mAP 73.57  mINP 73.57
-- query_max: R1 62.68  mAP 73.19  mINP 73.19
== IRRA | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

irra videos: 100%|██████████| 64/64 [00:04<00:00, 15.00batch/s]
irra texts: 100%|██████████| 10/10 [00:00<00:00, 84.78batch/s]

-- mean: R1 30.00  mAP 41.27  mINP 41.27
-- mean_s8: R1 30.00  mAP 41.29  mINP 41.29
-- max: R1 29.33  mAP 40.77  mINP 40.77
-- query_max: R1 28.67  mAP 40.68  mINP 40.68
== IRRA | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

irra videos: 100%|██████████| 1281/1281 [01:26<00:00, 14.73batch/s]
irra texts: 100%|██████████| 76/76 [00:00<00:00, 81.50batch/s]

-- mean: R1 36.65  mAP 48.82  mINP 48.82
-- mean_s8: R1 36.24  mAP 48.47  mINP 48.47
-- max: R1 34.08  mAP 46.67  mINP 46.67
-- query_max: R1 37.73  mAP 50.54  mINP 50.54
== IRRA | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

irra videos: 100%|██████████| 718/718 [00:48<00:00, 14.90batch/s]
irra texts: 100%|██████████| 18/18 [00:00<00:00, 82.07batch/s]

-- mean: R1 65.85  mAP 75.69  mINP 75.69
-- mean_s8: R1 66.55  mAP 76.09  mINP 76.09
-- max: R1 65.14  mAP 75.58  mINP 75.58
-- query_max: R1 65.14  mAP 75.18  mINP 75.18
== IRRA | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

irra videos: 100%|██████████| 316/316 [00:21<00:00, 14.97batch/s]
irra texts: 100%|██████████| 10/10 [00:00<00:00, 84.46batch/s]

-- mean: R1 27.33  mAP 39.91  mINP 39.91
-- mean_s8: R1 26.00  mAP 39.16  mINP 39.16
-- max: R1 26.00  mAP 39.08  mINP 39.08
-- query_max: R1 28.00  mAP 39.68  mINP 39.68
== IRRA | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

irra videos: 100%|██████████| 4261/4261 [04:51<00:00, 14.60batch/s]
irra texts: 100%|██████████| 76/76 [00:00<00:00, 81.90batch/s]

-- mean: R1 36.07  mAP 48.49  mINP 48.49
-- mean_s8: R1 36.65  mAP 48.73  mINP 48.73
-- max: R1 32.34  mAP 43.72  mINP 43.72
-- query_max: R1 38.06  mAP 50.79  mINP 50.79
== IRRA | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

irra videos: 100%|██████████| 500/500 [00:46<00:00, 10.75batch/s]
irra texts: 100%|██████████| 125/125 [00:01<00:00, 82.08batch/s]

-- none: R1 53.30  mAP 39.71  mINP 3.35
== IRRA | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

irra videos: 100%|██████████| 227/227 [00:16<00:00, 13.94batch/s]
irra texts: 100%|██████████| 50/50 [00:00<00:00, 87.36batch/s]

-- none: R1 11.90  mAP 18.52  mINP 18.52
== IRRA | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

irra texts: 100%|██████████| 22/22 [00:00<00:00, 88.84batch/s]

-- none: R1 24.71  mAP 36.67  mINP 36.67
== IRRA | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

irra texts: 100%|██████████| 29/29 [00:00<00:00, 88.20batch/s]

-- none: R1 2.20  mAP 4.76  mINP 4.76
== IRRA | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

irra texts: 100%|██████████| 22/22 [00:00<00:00, 87.85batch/s]

-- none: R1 28.20  mAP 41.43  mINP 41.43
== IRRA | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

irra videos: 100%|██████████| 278/278 [00:20<00:00, 13.79batch/s]
irra texts: 100%|██████████| 50/50 [00:00<00:00, 86.25batch/s]

-- mean: R1 8.90  mAP 14.96  mINP 14.96
-- mean_s8: R1 8.90  mAP 14.96  mINP 14.96
-- max: R1 8.77  mAP 14.94  mINP 14.94
-- query_max: R1 8.65  mAP 14.90  mINP 14.90
== IRRA | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 88.22batch/s]

-- mean: R1 19.77  mAP 30.94  mINP 30.94
-- mean_s8: R1 19.77  mAP 30.94  mINP 30.94
-- max: R1 19.48  mAP 30.86  mINP 30.86
-- query_max: R1 18.90  mAP 30.59  mINP 30.59
== IRRA | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

irra texts: 100%|██████████| 29/29 [00:00<00:00, 88.69batch/s]

-- mean: R1 0.66  mAP 2.85  mINP 2.85
-- mean_s8: R1 0.66  mAP 2.85  mINP 2.85
-- max: R1 0.66  mAP 2.88  mINP 2.88
-- query_max: R1 0.88  mAP 3.01  mINP 3.01
== IRRA | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 88.42batch/s]

-- mean: R1 22.97  mAP 34.74  mINP 34.74
-- mean_s8: R1 22.97  mAP 34.74  mINP 34.74
-- max: R1 22.38  mAP 34.38  mINP 34.38
-- query_max: R1 22.67  mAP 34.49  mINP 34.49
== IRRA | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

irra videos: 100%|██████████| 468/468 [00:34<00:00, 13.59batch/s]
irra texts: 100%|██████████| 50/50 [00:00<00:00, 86.51batch/s]

-- mean: R1 11.03  mAP 17.47  mINP 17.47
-- mean_s8: R1 11.03  mAP 17.53  mINP 17.53
-- max: R1 11.03  mAP 17.21  mINP 17.21
-- query_max: R1 10.78  mAP 17.47  mINP 17.47
== IRRA | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 88.26batch/s]

-- mean: R1 22.97  mAP 34.66  mINP 34.66
-- mean_s8: R1 22.97  mAP 34.78  mINP 34.78
-- max: R1 23.26  mAP 34.12  mINP 34.12
-- query_max: R1 22.97  mAP 34.85  mINP 34.85
== IRRA | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

irra texts: 100%|██████████| 29/29 [00:00<00:00, 87.11batch/s]

-- mean: R1 1.98  mAP 4.44  mINP 4.44
-- mean_s8: R1 1.98  mAP 4.46  mINP 4.46
-- max: R1 1.76  mAP 4.40  mINP 4.40
-- query_max: R1 1.54  mAP 4.30  mINP 4.30
== IRRA | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 87.33batch/s]

-- mean: R1 28.20  mAP 39.76  mINP 39.76
-- mean_s8: R1 28.49  mAP 40.01  mINP 40.01
-- max: R1 28.20  mAP 39.18  mINP 39.18
-- query_max: R1 28.49  mAP 40.83  mINP 40.83
== IRRA | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

irra videos: 100%|██████████| 1779/1779 [02:08<00:00, 13.83batch/s]
irra texts: 100%|██████████| 50/50 [00:00<00:00, 87.54batch/s]

-- mean: R1 10.78  mAP 17.75  mINP 17.75
-- mean_s8: R1 10.78  mAP 17.76  mINP 17.76
-- max: R1 10.53  mAP 16.64  mINP 16.64
-- query_max: R1 10.03  mAP 17.29  mINP 17.29
== IRRA | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 73.39batch/s]

-- mean: R1 22.67  mAP 35.33  mINP 35.33
-- mean_s8: R1 22.97  mAP 35.61  mINP 35.61
-- max: R1 21.80  mAP 32.24  mINP 32.24
-- query_max: R1 20.93  mAP 34.01  mINP 34.01
== IRRA | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

irra texts: 100%|██████████| 29/29 [00:00<00:00, 88.40batch/s]

-- mean: R1 1.76  mAP 4.43  mINP 4.43
-- mean_s8: R1 1.54  mAP 4.23  mINP 4.23
-- max: R1 1.98  mAP 4.82  mINP 4.82
-- query_max: R1 1.76  mAP 4.63  mINP 4.63
== IRRA | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

irra texts: 100%|██████████| 22/22 [00:00<00:00, 85.90batch/s]

-- mean: R1 27.03  mAP 41.11  mINP 41.11
-- mean_s8: R1 26.45  mAP 41.02  mINP 41.02
-- max: R1 25.58  mAP 36.70  mINP 36.70
-- query_max: R1 29.36  mAP 42.39  mINP 42.39

######## InternVideo2-1B-s2: 36 of 36 runs to do

/usr/local/lib/python3.12/dist-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvl_clip_vision.py:148: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvideo2.py:148: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)
/usr/local/lib/python3.12/dist-packages/timm/models/registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
/kaggle/working/InternVideo/InternVideo2/multi_modality/models/backbones/internvideo2/internvideo2_clip_vision.py:143: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast(enabled=False)

No module named 'deepspeed'
deepspeed is not installed!!!
Building InternVideo2-1B-s2 on CPU (flash-attn off, 4 frames, fp16 on CUDA)
Loaded InternVideo2-stage2_1b-224p-f4.pt: 1023 tensors, missing 0, unexpected 0
Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== InternVideo2-1B-s2 | tvpreid/prid | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

internvideo2_s2_1b videos:   0%|          | 0/142 [00:00<?, ?batch/s]/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:232: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  check_backward_validity(args)
internvideo2_s2_1b videos: 100%|██████████| 142/142 [00:38<00:00,  3.65batch/s]
internvideo2_s2_1b texts: 100%|██████████| 18/18 [00:00<00:00, 44.32batch/s]

-- none: R1 4.23  mAP 10.78  mINP 10.78
== InternVideo2-1B-s2 | tvpreid/ilids | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 75/75 [00:20<00:00,  3.70batch/s]
internvideo2_s2_1b texts: 100%|██████████| 10/10 [00:00<00:00, 50.14batch/s]

-- none: R1 2.67  mAP 8.92  mINP 8.92
== InternVideo2-1B-s2 | tvpreid/duke | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 603/603 [02:40<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 76/76 [00:01<00:00, 48.67batch/s]

-- none: R1 1.33  mAP 3.64  mINP 3.64
== InternVideo2-1B-s2 | tvpreid/prid | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 142/142 [00:37<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 18/18 [00:00<00:00, 48.55batch/s]

-- none: R1 2.46  mAP 9.74  mINP 9.74
== InternVideo2-1B-s2 | tvpreid/ilids | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 75/75 [00:19<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 10/10 [00:00<00:00, 47.65batch/s]

-- none: R1 2.00  mAP 8.50  mINP 8.50
== InternVideo2-1B-s2 | tvpreid/duke | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 603/603 [02:41<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 76/76 [00:01<00:00, 49.04batch/s]

-- none: R1 1.74  mAP 3.93  mINP 3.93
== InternVideo2-1B-s2 | tvpreid/prid | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 250 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b videos: 100%|██████████| 250/250 [01:06<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 18/18 [00:00<00:00, 49.42batch/s]

-- mean: R1 2.82  mAP 9.78  mINP 9.78
-- mean_s8: R1 2.46  mAP 9.58  mINP 9.58
-- max: R1 2.82  mAP 10.09  mINP 10.09
-- query_max: R1 2.82  mAP 9.89  mINP 9.89
== InternVideo2-1B-s2 | tvpreid/ilids | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 106 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b videos: 100%|██████████| 106/106 [00:28<00:00,  3.73batch/s]
internvideo2_s2_1b texts: 100%|██████████| 10/10 [00:00<00:00, 48.54batch/s]

-- mean: R1 2.67  mAP 8.85  mINP 8.85
-- mean_s8: R1 2.67  mAP 8.82  mINP 8.82
-- max: R1 2.67  mAP 8.83  mINP 8.83
-- query_max: R1 2.67  mAP 8.82  mINP 8.82

== InternVideo2-1B-s2 | tvpreid/duke | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1581 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b videos: 100%|██████████| 1581/1581 [07:01<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 76/76 [00:01<00:00, 49.21batch/s]

-- mean: R1 1.66  mAP 3.83  mINP 3.83
-- mean_s8: R1 1.82  mAP 3.82  mINP 3.82
-- max: R1 0.91  mAP 3.23  mINP 3.23
-- query_max: R1 1.82  mAP 4.15  mINP 4.15
== InternVideo2-1B-s2 | tvpreid/prid | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 459 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b videos: 100%|██████████| 459/459 [02:02<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 18/18 [00:00<00:00, 48.35batch/s]

-- mean: R1 2.82  mAP 9.92  mINP 9.92
-- mean_s8: R1 2.82  mAP 10.05  mINP 10.05
-- max: R1 2.82  mAP 10.26  mINP 10.26
-- query_max: R1 3.17  mAP 10.12  mINP 10.12
== InternVideo2-1B-s2 | tvpreid/ilids | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 198 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b videos: 100%|██████████| 198/198 [00:52<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 10/10 [00:00<00:00, 47.71batch/s]

-- mean: R1 3.33  mAP 8.92  mINP 8.92
-- mean_s8: R1 3.33  mAP 9.01  mINP 9.01
-- max: R1 3.33  mAP 8.91  mINP 8.91
-- query_max: R1 4.00  mAP 10.26  mINP 10.26

== InternVideo2-1B-s2 | tvpreid/duke | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 3157 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b videos: 100%|██████████| 3157/3157 [14:04<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 76/76 [00:01<00:00, 48.53batch/s]

-- mean: R1 1.49  mAP 3.92  mINP 3.92
-- mean_s8: R1 1.41  mAP 3.79  mINP 3.79
-- max: R1 1.08  mAP 3.15  mINP 3.15
-- query_max: R1 1.58  mAP 3.93  mINP 3.93
== InternVideo2-1B-s2 | tvpreid/prid | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1577 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b videos: 100%|██████████| 1577/1577 [07:01<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 18/18 [00:00<00:00, 48.22batch/s]

-- mean: R1 2.46  mAP 9.68  mINP 9.68
-- mean_s8: R1 2.46  mAP 9.50  mINP 9.50
-- max: R1 2.11  mAP 8.81  mINP 8.81
-- query_max: R1 2.82  mAP 9.60  mINP 9.60
== InternVideo2-1B-s2 | tvpreid/ilids | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 707 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b videos: 100%|██████████| 707/707 [03:08<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 10/10 [00:00<00:00, 47.39batch/s]

-- mean: R1 2.00  mAP 7.60  mINP 7.60
-- mean_s8: R1 2.67  mAP 8.05  mINP 8.05
-- max: R1 2.00  mAP 7.65  mINP 7.65
-- query_max: R1 2.00  mAP 8.23  mINP 8.23
== InternVideo2-1B-s2 | tvpreid/duke | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 9125 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b videos: 100%|██████████| 9125/9125 [40:36<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 76/76 [00:01<00:00, 47.61batch/s]

-- mean: R1 1.24  mAP 3.90  mINP 3.90
-- mean_s8: R1 1.41  mAP 3.92  mINP 3.92
-- max: R1 0.75  mAP 2.92  mINP 2.92
-- query_max: R1 1.41  mAP 4.06  mINP 4.06
== InternVideo2-1B-s2 | rstpreid/test | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 1000/1000 [04:30<00:00,  3.70batch/s]
internvideo2_s2_1b texts: 100%|██████████| 125/125 [00:02<00:00, 48.21batch/s]

-- none: R1 5.15  mAP 4.53  mINP 0.25
== InternVideo2-1B-s2 | groot_mot17/all | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 454/454 [02:01<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 50/50 [00:01<00:00, 49.69batch/s]

-- none: R1 0.25  mAP 2.02  mINP 2.02
== InternVideo2-1B-s2 | groot_mot17/appearance | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.04batch/s]

-- none: R1 0.29  mAP 2.43  mINP 2.43
== InternVideo2-1B-s2 | groot_mot17/action | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 29/29 [00:00<00:00, 49.93batch/s]

-- none: R1 0.22  mAP 1.70  mINP 1.70
== InternVideo2-1B-s2 | groot_mot17/combined | uniform4 (uniform 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.37batch/s]

-- none: R1 0.87  mAP 3.11  mINP 3.11
== InternVideo2-1B-s2 | groot_mot17/all | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b videos: 100%|██████████| 454/454 [02:01<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 50/50 [00:01<00:00, 48.91batch/s]

-- none: R1 0.38  mAP 2.12  mINP 2.12
== InternVideo2-1B-s2 | groot_mot17/appearance | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 48.36batch/s]

-- none: R1 0.29  mAP 2.46  mINP 2.46
== InternVideo2-1B-s2 | groot_mot17/action | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 29/29 [00:00<00:00, 49.17batch/s]

-- none: R1 0.44  mAP 1.87  mINP 1.87
== InternVideo2-1B-s2 | groot_mot17/combined | middle4 (middle 4 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.28batch/s]

-- none: R1 0.87  mAP 3.23  mINP 3.23
== InternVideo2-1B-s2 | groot_mot17/all | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 758 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b videos: 100%|██████████| 758/758 [03:22<00:00,  3.74batch/s]
internvideo2_s2_1b texts: 100%|██████████| 50/50 [00:01<00:00, 48.01batch/s]

-- mean: R1 0.25  mAP 1.91  mINP 1.91
-- mean_s8: R1 0.25  mAP 1.98  mINP 1.98
-- max: R1 0.75  mAP 2.27  mINP 2.27
-- query_max: R1 0.25  mAP 1.93  mINP 1.93
== InternVideo2-1B-s2 | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 758 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 50.81batch/s]

-- mean: R1 0.29  mAP 2.33  mINP 2.33
-- mean_s8: R1 0.29  mAP 2.33  mINP 2.33
-- max: R1 0.87  mAP 2.78  mINP 2.78
-- query_max: R1 0.29  mAP 2.33  mINP 2.33
== InternVideo2-1B-s2 | groot_mot17/action | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 758 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b texts: 100%|██████████| 29/29 [00:00<00:00, 49.59batch/s]

-- mean: R1 0.22  mAP 1.60  mINP 1.60
-- mean_s8: R1 0.22  mAP 1.71  mINP 1.71
-- max: R1 0.66  mAP 1.88  mINP 1.88
-- query_max: R1 0.22  mAP 1.63  mINP 1.63
== InternVideo2-1B-s2 | groot_mot17/combined | vt_1fps_n12 (sliding windows of 4, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 758 clips (window=4 stride=4 fps=1 max=12)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.61batch/s]

-- mean: R1 0.29  mAP 2.67  mINP 2.67
-- mean_s8: R1 0.29  mAP 2.78  mINP 2.78
-- max: R1 1.45  mAP 3.52  mINP 3.52
-- query_max: R1 0.29  mAP 2.59  mINP 2.59
== InternVideo2-1B-s2 | groot_mot17/all | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 1222 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b videos: 100%|██████████| 1222/1222 [05:25<00:00,  3.76batch/s]
internvideo2_s2_1b texts: 100%|██████████| 50/50 [00:01<00:00, 49.69batch/s]

-- mean: R1 0.38  mAP 2.01  mINP 2.01
-- mean_s8: R1 0.25  mAP 1.92  mINP 1.92
-- max: R1 0.25  mAP 2.22  mINP 2.22
-- query_max: R1 0.25  mAP 1.92  mINP 1.92
== InternVideo2-1B-s2 | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 1222 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 50.64batch/s]

-- mean: R1 0.29  mAP 2.38  mINP 2.38
-- mean_s8: R1 0.29  mAP 2.27  mINP 2.27
-- max: R1 0.29  mAP 2.73  mINP 2.73
-- query_max: R1 0.29  mAP 2.35  mINP 2.35
== InternVideo2-1B-s2 | groot_mot17/action | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 1222 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b texts: 100%|██████████| 29/29 [00:00<00:00, 50.22batch/s]

-- mean: R1 0.44  mAP 1.73  mINP 1.73
-- mean_s8: R1 0.22  mAP 1.65  mINP 1.65
-- max: R1 0.22  mAP 1.83  mINP 1.83
-- query_max: R1 0.22  mAP 1.60  mINP 1.60
== InternVideo2-1B-s2 | groot_mot17/combined | vt_2fps_n32 (sliding windows of 4, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 1222 clips (window=4 stride=4 fps=2 max=32)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.26batch/s]

-- mean: R1 0.87  mAP 2.97  mINP 2.97
-- mean_s8: R1 0.58  mAP 2.77  mINP 2.77
-- max: R1 0.29  mAP 3.26  mINP 3.26
-- query_max: R1 0.58  mAP 2.73  mINP 2.73
== InternVideo2-1B-s2 | groot_mot17/all | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3993 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b videos: 100%|██████████| 3993/3993 [17:45<00:00,  3.75batch/s]
internvideo2_s2_1b texts: 100%|██████████| 50/50 [00:01<00:00, 48.93batch/s]

-- mean: R1 0.25  mAP 2.00  mINP 2.00
-- mean_s8: R1 0.25  mAP 2.05  mINP 2.05
-- max: R1 0.25  mAP 2.21  mINP 2.21
-- query_max: R1 0.25  mAP 1.95  mINP 1.95
== InternVideo2-1B-s2 | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3993 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 49.95batch/s]

-- mean: R1 0.29  mAP 2.47  mINP 2.47
-- mean_s8: R1 0.29  mAP 2.52  mINP 2.52
-- max: R1 0.29  mAP 2.72  mINP 2.72
-- query_max: R1 0.29  mAP 2.43  mINP 2.43
== InternVideo2-1B-s2 | groot_mot17/action | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3993 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b texts: 100%|██████████| 29/29 [00:00<00:00, 50.52batch/s]

-- mean: R1 0.22  mAP 1.65  mINP 1.65
-- mean_s8: R1 0.22  mAP 1.69  mINP 1.69
-- max: R1 0.22  mAP 1.82  mINP 1.82
-- query_max: R1 0.22  mAP 1.59  mINP 1.59
== InternVideo2-1B-s2 | groot_mot17/combined | reid_8fps_n64 (sliding windows of 4, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3993 clips (window=4 stride=4 fps=8 max=64)

internvideo2_s2_1b texts: 100%|██████████| 22/22 [00:00<00:00, 50.18batch/s]

-- mean: R1 0.87  mAP 3.24  mINP 3.24
-- mean_s8: R1 0.87  mAP 3.32  mINP 3.32
-- max: R1 1.16  mAP 3.52  mINP 3.52
-- query_max: R1 0.87  mAP 3.06  mINP 3.06

######## X-CLIP: 29 of 29 runs to do
Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== X-CLIP | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

xclip videos: 100%|██████████| 36/36 [00:07<00:00,  5.07batch/s]
xclip texts: 100%|██████████| 18/18 [00:00<00:00, 35.25batch/s]

-- none: R1 2.46  mAP 7.42  mINP 7.42
== X-CLIP | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

xclip videos: 100%|██████████| 19/19 [00:02<00:00,  9.18batch/s]
xclip texts: 100%|██████████| 10/10 [00:00<00:00, 55.84batch/s]

-- none: R1 3.33  mAP 8.90  mINP 8.90

== X-CLIP | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

xclip videos: 100%|██████████| 151/151 [00:17<00:00,  8.49batch/s]
xclip texts: 100%|██████████| 76/76 [00:01<00:00, 54.50batch/s]

-- none: R1 0.50  mAP 3.13  mINP 3.13
== X-CLIP | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

xclip videos: 100%|██████████| 41/41 [00:04<00:00,  9.18batch/s]
xclip texts: 100%|██████████| 18/18 [00:00<00:00, 54.77batch/s]

-- mean: R1 4.58  mAP 8.41  mINP 8.41
-- mean_s8: R1 4.58  mAP 8.41  mINP 8.41
-- max: R1 4.93  mAP 8.63  mINP 8.63
-- query_max: R1 4.93  mAP 8.62  mINP 8.62
== X-CLIP | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

xclip videos: 100%|██████████| 19/19 [00:02<00:00,  9.16batch/s]
xclip texts: 100%|██████████| 10/10 [00:00<00:00, 57.56batch/s]

-- mean: R1 0.67  mAP 7.19  mINP 7.19
-- mean_s8: R1 0.67  mAP 7.19  mINP 7.19
-- max: R1 0.67  mAP 7.13  mINP 7.13
-- query_max: R1 0.67  mAP 7.19  mINP 7.19
== X-CLIP | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

xclip videos: 100%|██████████| 251/251 [00:29<00:00,  8.53batch/s]
xclip texts: 100%|██████████| 76/76 [00:01<00:00, 55.69batch/s]

-- mean: R1 0.66  mAP 2.93  mINP 2.93
-- mean_s8: R1 0.66  mAP 2.93  mINP 2.93
-- max: R1 0.50  mAP 2.82  mINP 2.82
-- query_max: R1 0.66  mAP 2.86  mINP 2.86
== X-CLIP | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

xclip videos: 100%|██████████| 87/87 [00:10<00:00,  8.66batch/s]
xclip texts: 100%|██████████| 18/18 [00:00<00:00, 54.00batch/s]

-- mean: R1 3.52  mAP 8.15  mINP 8.15
-- mean_s8: R1 3.52  mAP 8.19  mINP 8.19
-- max: R1 3.52  mAP 8.19  mINP 8.19
-- query_max: R1 3.17  mAP 7.75  mINP 7.75
== X-CLIP | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

xclip videos: 100%|██████████| 32/32 [00:03<00:00,  9.05batch/s]
xclip texts: 100%|██████████| 10/10 [00:00<00:00, 49.55batch/s]

-- mean: R1 5.33  mAP 10.52  mINP 10.52
-- mean_s8: R1 4.67  mAP 10.12  mINP 10.12
-- max: R1 3.33  mAP 9.85  mINP 9.85
-- query_max: R1 2.67  mAP 9.21  mINP 9.21

== X-CLIP | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

xclip videos: 100%|██████████| 641/641 [01:15<00:00,  8.51batch/s]
xclip texts: 100%|██████████| 76/76 [00:01<00:00, 53.49batch/s]

-- mean: R1 1.33  mAP 3.83  mINP 3.83
-- mean_s8: R1 1.33  mAP 3.85  mINP 3.85
-- max: R1 1.24  mAP 3.64  mINP 3.64
-- query_max: R1 1.00  mAP 3.42  mINP 3.42
== X-CLIP | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

xclip videos: 100%|██████████| 359/359 [00:41<00:00,  8.70batch/s]
xclip texts: 100%|██████████| 18/18 [00:00<00:00, 55.38batch/s]

-- mean: R1 4.93  mAP 10.05  mINP 10.05
-- mean_s8: R1 4.93  mAP 9.83  mINP 9.83
-- max: R1 3.17  mAP 8.53  mINP 8.53
-- query_max: R1 2.82  mAP 8.77  mINP 8.77
== X-CLIP | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

xclip videos: 100%|██████████| 158/158 [00:18<00:00,  8.69batch/s]
xclip texts: 100%|██████████| 10/10 [00:00<00:00, 55.51batch/s]

-- mean: R1 3.33  mAP 9.37  mINP 9.37
-- mean_s8: R1 3.33  mAP 9.23  mINP 9.23
-- max: R1 4.00  mAP 9.95  mINP 9.95
-- query_max: R1 4.00  mAP 9.63  mINP 9.63
== X-CLIP | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

xclip videos: 100%|██████████| 2131/2131 [04:09<00:00,  8.55batch/s]
xclip texts: 100%|██████████| 76/76 [00:01<00:00, 54.18batch/s]

-- mean: R1 1.41  mAP 3.95  mINP 3.95
-- mean_s8: R1 1.41  mAP 3.94  mINP 3.94
-- max: R1 1.16  mAP 3.62  mINP 3.62
-- query_max: R1 1.41  mAP 3.79  mINP 3.79
== X-CLIP | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

xclip videos: 100%|██████████| 250/250 [00:39<00:00,  6.37batch/s]
xclip texts: 100%|██████████| 125/125 [00:02<00:00, 54.64batch/s]

-- none: R1 1.40  mAP 2.26  mINP 0.17
== X-CLIP | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

xclip videos: 100%|██████████| 114/114 [00:14<00:00,  7.95batch/s]
xclip texts: 100%|██████████| 50/50 [00:00<00:00, 60.27batch/s]

-- none: R1 1.13  mAP 3.43  mINP 3.43
== X-CLIP | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 61.64batch/s]

-- none: R1 2.03  mAP 5.54  mINP 5.54
== X-CLIP | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

xclip texts: 100%|██████████| 29/29 [00:00<00:00, 62.32batch/s]

-- none: R1 0.44  mAP 1.83  mINP 1.83
== X-CLIP | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 59.14batch/s]

-- none: R1 1.45  mAP 5.50  mINP 5.50
== X-CLIP | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

xclip videos: 100%|██████████| 139/139 [00:17<00:00,  8.00batch/s]
xclip texts: 100%|██████████| 50/50 [00:00<00:00, 63.32batch/s]

-- mean: R1 0.75  mAP 2.81  mINP 2.81
-- mean_s8: R1 0.75  mAP 2.81  mINP 2.81
-- max: R1 0.75  mAP 2.92  mINP 2.92
-- query_max: R1 0.63  mAP 2.78  mINP 2.78
== X-CLIP | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 61.57batch/s]

-- mean: R1 1.74  mAP 4.72  mINP 4.72
-- mean_s8: R1 1.74  mAP 4.72  mINP 4.72
-- max: R1 1.74  mAP 4.93  mINP 4.93
-- query_max: R1 1.45  mAP 4.67  mINP 4.67
== X-CLIP | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

xclip texts: 100%|██████████| 29/29 [00:00<00:00, 62.98batch/s]

-- mean: R1 0.00  mAP 1.35  mINP 1.35
-- mean_s8: R1 0.00  mAP 1.35  mINP 1.35
-- max: R1 0.00  mAP 1.39  mINP 1.39
-- query_max: R1 0.00  mAP 1.34  mINP 1.34
== X-CLIP | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 60.84batch/s]

-- mean: R1 2.91  mAP 5.45  mINP 5.45
-- mean_s8: R1 2.91  mAP 5.45  mINP 5.45
-- max: R1 2.62  mAP 5.29  mINP 5.29
-- query_max: R1 2.91  mAP 5.42  mINP 5.42
== X-CLIP | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

xclip videos: 100%|██████████| 234/234 [00:29<00:00,  7.97batch/s]
xclip texts: 100%|██████████| 50/50 [00:00<00:00, 62.74batch/s]

-- mean: R1 1.00  mAP 3.30  mINP 3.30
-- mean_s8: R1 1.25  mAP 3.49  mINP 3.49
-- max: R1 1.13  mAP 3.22  mINP 3.22
-- query_max: R1 0.88  mAP 3.16  mINP 3.16
== X-CLIP | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 62.27batch/s]

-- mean: R1 2.03  mAP 5.53  mINP 5.53
-- mean_s8: R1 2.62  mAP 5.93  mINP 5.93
-- max: R1 2.03  mAP 5.19  mINP 5.19
-- query_max: R1 1.45  mAP 5.10  mINP 5.10
== X-CLIP | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

xclip texts: 100%|██████████| 29/29 [00:00<00:00, 62.91batch/s]

-- mean: R1 0.22  mAP 1.61  mINP 1.61
-- mean_s8: R1 0.22  mAP 1.64  mINP 1.64
-- max: R1 0.44  mAP 1.72  mINP 1.72
-- query_max: R1 0.44  mAP 1.70  mINP 1.70
== X-CLIP | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 61.00batch/s]

-- mean: R1 2.33  mAP 5.84  mINP 5.84
-- mean_s8: R1 2.91  mAP 6.36  mINP 6.36
-- max: R1 2.03  mAP 5.41  mINP 5.41
-- query_max: R1 2.33  mAP 5.94  mINP 5.94
== X-CLIP | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

xclip videos: 100%|██████████| 890/890 [01:52<00:00,  7.92batch/s]
xclip texts: 100%|██████████| 50/50 [00:01<00:00, 42.29batch/s]

-- mean: R1 1.38  mAP 3.93  mINP 3.93
-- mean_s8: R1 1.25  mAP 3.95  mINP 3.95
-- max: R1 1.00  mAP 2.93  mINP 2.93
-- query_max: R1 1.13  mAP 3.87  mINP 3.87
== X-CLIP | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 63.52batch/s]

-- mean: R1 2.62  mAP 6.70  mINP 6.70
-- mean_s8: R1 2.62  mAP 6.87  mINP 6.87
-- max: R1 2.03  mAP 4.82  mINP 4.82
-- query_max: R1 2.33  mAP 6.90  mINP 6.90
== X-CLIP | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

xclip texts: 100%|██████████| 29/29 [00:00<00:00, 63.61batch/s]

-- mean: R1 0.44  mAP 1.83  mINP 1.83
-- mean_s8: R1 0.22  mAP 1.73  mINP 1.73
-- max: R1 0.22  mAP 1.49  mINP 1.49
-- query_max: R1 0.22  mAP 1.56  mINP 1.56
== X-CLIP | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

xclip texts: 100%|██████████| 22/22 [00:00<00:00, 62.29batch/s]

-- mean: R1 2.03  mAP 5.88  mINP 5.88
-- mean_s8: R1 2.03  mAP 5.95  mINP 5.95
-- max: R1 0.58  mAP 4.27  mINP 4.27
-- query_max: R1 1.74  mAP 5.63  mINP 5.63

######## LanguageBind: 29 of 29 runs to do
LanguageBind loaded 1047/1047 tensors from pytorch_model.bin
Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== LanguageBind | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

languagebind videos: 100%|██████████| 71/71 [00:33<00:00,  2.11batch/s]
languagebind texts: 100%|██████████| 18/18 [00:00<00:00, 46.22batch/s]

-- none: R1 11.62  mAP 21.18  mINP 21.18
== LanguageBind | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

languagebind videos: 100%|██████████| 38/38 [00:15<00:00,  2.53batch/s]
languagebind texts: 100%|██████████| 10/10 [00:00<00:00, 49.40batch/s]

-- none: R1 12.00  mAP 20.48  mINP 20.48
== LanguageBind | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

languagebind videos: 100%|██████████| 302/302 [01:58<00:00,  2.55batch/s]
languagebind texts: 100%|██████████| 76/76 [00:01<00:00, 49.39batch/s]

-- none: R1 6.30  mAP 13.25  mINP 13.25
== LanguageBind | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

languagebind videos: 100%|██████████| 82/82 [00:31<00:00,  2.57batch/s]
languagebind texts: 100%|██████████| 18/18 [00:00<00:00, 47.03batch/s]

-- mean: R1 11.97  mAP 22.52  mINP 22.52
-- mean_s8: R1 11.97  mAP 22.52  mINP 22.52
-- max: R1 11.27  mAP 22.55  mINP 22.55
-- query_max: R1 11.97  mAP 22.13  mINP 22.13
== LanguageBind | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

languagebind videos: 100%|██████████| 38/38 [00:14<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 10/10 [00:00<00:00, 47.18batch/s]

-- mean: R1 8.67  mAP 18.31  mINP 18.31
-- mean_s8: R1 8.67  mAP 18.31  mINP 18.31
-- max: R1 8.67  mAP 18.42  mINP 18.42
-- query_max: R1 8.67  mAP 18.31  mINP 18.31

== LanguageBind | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

languagebind videos: 100%|██████████| 501/501 [03:17<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 76/76 [00:01<00:00, 48.24batch/s]

-- mean: R1 6.55  mAP 13.62  mINP 13.62
-- mean_s8: R1 6.55  mAP 13.62  mINP 13.62
-- max: R1 7.13  mAP 13.70  mINP 13.70
-- query_max: R1 6.80  mAP 13.93  mINP 13.93
== LanguageBind | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

languagebind videos: 100%|██████████| 173/173 [01:08<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 18/18 [00:00<00:00, 47.95batch/s]

-- mean: R1 16.20  mAP 24.82  mINP 24.82
-- mean_s8: R1 15.49  mAP 24.50  mINP 24.50
-- max: R1 14.79  mAP 24.73  mINP 24.73
-- query_max: R1 16.20  mAP 24.04  mINP 24.04
== LanguageBind | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

languagebind videos: 100%|██████████| 64/64 [00:25<00:00,  2.55batch/s]
languagebind texts: 100%|██████████| 10/10 [00:00<00:00, 48.47batch/s]

-- mean: R1 11.33  mAP 21.17  mINP 21.17
-- mean_s8: R1 11.33  mAP 21.27  mINP 21.27
-- max: R1 11.33  mAP 20.40  mINP 20.40
-- query_max: R1 12.00  mAP 21.62  mINP 21.62
== LanguageBind | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

languagebind videos: 100%|██████████| 1281/1281 [08:24<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 76/76 [00:01<00:00, 48.14batch/s]

-- mean: R1 5.72  mAP 13.56  mINP 13.56
-- mean_s8: R1 6.05  mAP 13.62  mINP 13.62
-- max: R1 6.63  mAP 12.55  mINP 12.55
-- query_max: R1 7.05  mAP 14.47  mINP 14.47
== LanguageBind | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

languagebind videos: 100%|██████████| 718/718 [04:42<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 18/18 [00:00<00:00, 47.48batch/s]

-- mean: R1 14.44  mAP 23.26  mINP 23.26
-- mean_s8: R1 15.14  mAP 23.37  mINP 23.37
-- max: R1 11.97  mAP 21.90  mINP 21.90
-- query_max: R1 14.44  mAP 23.63  mINP 23.63
== LanguageBind | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

languagebind videos: 100%|██████████| 316/316 [02:04<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 10/10 [00:00<00:00, 50.36batch/s]

-- mean: R1 12.67  mAP 22.09  mINP 22.09
-- mean_s8: R1 12.67  mAP 21.99  mINP 21.99
-- max: R1 8.00  mAP 17.28  mINP 17.28
-- query_max: R1 11.33  mAP 21.67  mINP 21.67
== LanguageBind | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

languagebind videos: 100%|██████████| 4261/4261 [28:00<00:00,  2.54batch/s]
languagebind texts: 100%|██████████| 76/76 [00:01<00:00, 49.36batch/s]

-- mean: R1 7.30  mAP 14.46  mINP 14.46
-- mean_s8: R1 6.97  mAP 14.05  mINP 14.05
-- max: R1 4.64  mAP 10.06  mINP 10.06
-- query_max: R1 6.38  mAP 14.05  mINP 14.05
== LanguageBind | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

languagebind videos: 100%|██████████| 500/500 [03:29<00:00,  2.39batch/s]
languagebind texts: 100%|██████████| 125/125 [00:02<00:00, 48.13batch/s]

-- none: R1 15.55  mAP 11.36  mINP 0.52
== LanguageBind | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

languagebind videos: 100%|██████████| 227/227 [01:30<00:00,  2.50batch/s]
languagebind texts: 100%|██████████| 50/50 [00:01<00:00, 49.61batch/s]

-- none: R1 7.02  mAP 11.68  mINP 11.68
== LanguageBind | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 49.43batch/s]

-- none: R1 13.95  mAP 21.83  mINP 21.83
== LanguageBind | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

languagebind texts: 100%|██████████| 29/29 [00:00<00:00, 50.43batch/s]

-- none: R1 1.76  mAP 3.99  mINP 3.99
== LanguageBind | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 49.88batch/s]

-- none: R1 15.70  mAP 23.53  mINP 23.53
== LanguageBind | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

languagebind videos: 100%|██████████| 278/278 [01:50<00:00,  2.50batch/s]
languagebind texts: 100%|██████████| 50/50 [00:01<00:00, 49.55batch/s]

-- mean: R1 5.14  mAP 9.46  mINP 9.46
-- mean_s8: R1 5.14  mAP 9.46  mINP 9.46
-- max: R1 5.01  mAP 9.44  mINP 9.44
-- query_max: R1 5.26  mAP 9.55  mINP 9.55
== LanguageBind | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 50.44batch/s]

-- mean: R1 10.47  mAP 17.73  mINP 17.73
-- mean_s8: R1 10.47  mAP 17.73  mINP 17.73
-- max: R1 9.88  mAP 17.56  mINP 17.56
-- query_max: R1 11.05  mAP 18.17  mINP 18.17
== LanguageBind | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

languagebind texts: 100%|██████████| 29/29 [00:00<00:00, 50.99batch/s]

-- mean: R1 1.10  mAP 3.19  mINP 3.19
-- mean_s8: R1 1.10  mAP 3.19  mINP 3.19
-- max: R1 1.32  mAP 3.28  mINP 3.28
-- query_max: R1 0.88  mAP 3.01  mINP 3.01
== LanguageBind | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 50.09batch/s]

-- mean: R1 12.79  mAP 17.98  mINP 17.98
-- mean_s8: R1 12.79  mAP 17.98  mINP 17.98
-- max: R1 11.92  mAP 17.76  mINP 17.76
-- query_max: R1 11.63  mAP 17.19  mINP 17.19
== LanguageBind | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

languagebind videos: 100%|██████████| 468/468 [03:07<00:00,  2.50batch/s]
languagebind texts: 100%|██████████| 50/50 [00:01<00:00, 49.06batch/s]

-- mean: R1 6.02  mAP 10.54  mINP 10.54
-- mean_s8: R1 5.89  mAP 10.45  mINP 10.45
-- max: R1 5.76  mAP 10.14  mINP 10.14
-- query_max: R1 6.02  mAP 10.54  mINP 10.54
== LanguageBind | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 50.57batch/s]

-- mean: R1 11.92  mAP 19.20  mINP 19.20
-- mean_s8: R1 11.63  mAP 18.97  mINP 18.97
-- max: R1 11.05  mAP 18.12  mINP 18.12
-- query_max: R1 11.92  mAP 19.44  mINP 19.44
== LanguageBind | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

languagebind texts: 100%|██████████| 29/29 [00:00<00:00, 49.86batch/s]

-- mean: R1 1.54  mAP 3.97  mINP 3.97
-- mean_s8: R1 1.54  mAP 4.00  mINP 4.00
-- max: R1 1.76  mAP 4.09  mINP 4.09
-- query_max: R1 1.54  mAP 3.81  mINP 3.81
== LanguageBind | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 50.22batch/s]

-- mean: R1 13.37  mAP 19.82  mINP 19.82
-- mean_s8: R1 12.79  mAP 19.52  mINP 19.52
-- max: R1 13.95  mAP 19.86  mINP 19.86
-- query_max: R1 12.50  mAP 19.70  mINP 19.70
== LanguageBind | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

languagebind videos: 100%|██████████| 1779/1779 [11:52<00:00,  2.50batch/s]
languagebind texts: 100%|██████████| 50/50 [00:01<00:00, 49.72batch/s]

-- mean: R1 6.52  mAP 11.75  mINP 11.75
-- mean_s8: R1 6.39  mAP 11.56  mINP 11.56
-- max: R1 5.14  mAP 10.05  mINP 10.05
-- query_max: R1 7.64  mAP 12.23  mINP 12.23
== LanguageBind | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 45.49batch/s]

-- mean: R1 13.37  mAP 22.05  mINP 22.05
-- mean_s8: R1 13.37  mAP 21.82  mINP 21.82
-- max: R1 10.47  mAP 18.16  mINP 18.16
-- query_max: R1 14.83  mAP 22.95  mINP 22.95
== LanguageBind | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

languagebind texts: 100%|██████████| 29/29 [00:00<00:00, 50.51batch/s]

-- mean: R1 1.32  mAP 3.94  mINP 3.94
-- mean_s8: R1 1.10  mAP 3.79  mINP 3.79
-- max: R1 1.10  mAP 3.91  mINP 3.91
-- query_max: R1 2.20  mAP 4.12  mINP 4.12
== LanguageBind | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

languagebind texts: 100%|██████████| 22/22 [00:00<00:00, 50.56batch/s]

-- mean: R1 14.83  mAP 22.10  mINP 22.10
-- mean_s8: R1 14.53  mAP 21.72  mINP 21.72
-- max: R1 11.92  mAP 17.60  mINP 17.60
-- query_max: R1 16.28  mAP 23.89  mINP 23.89

######## InternVideo2 CLIP-S: 29 of 29 runs to do
InternVideo2Config {
  "architectures": [
    "InternVideo2_CLIP_small"
  ],
  "auto_map": {
    "AutoConfig": "config.InternVideo2Config",
    "AutoModel": "modeling_internvideo2encoder.InternVideo2_CLIP_small"
  },
  "auto_resume": false,
  "batch_size": 64,
  "batch_size_test": 4,
  "best_key": [
    "msrvtt_1k_test_match",
    "t2v_r1"
  ],
  "compile_model": false,
  "criterion": {
    "clip_loss_ratio": [
      1.0,
      1.0
    ],
    "distill_final_features": true,
    "loss_weight": {
      "mlm": 1.0,
      "mvm": 0.0,
      "uta": 0.0,
      "vtc": 1.0,
      "vtm": 1.0
    },
    "mlm_masking_prob": 0.5,
    "vtm_hard_neg": true
  },
  "debug": false,
  "deep_fusion": false,
  "deepspeed": {
    "enable": true,
    "stage": 1
  },
  "delete_ds_optim_states": true,
  "device": "cuda",
  "dist_url": "env://",
  "dtype": "float16",
  "evaluate": false,
  "evaluation": {
    "eval_frame_ensemble": "concat",
    "eval_offload": true,
    "eval_x_only": false,
    "k_test": 128
  },
  "gradient_checkpointing": true,
  "inputs": {
    "batch_size": {
      "image": 64,
      "video": 64
    },
    "batch_size_test": {
      "image": 4,
      "video": 4
    },
    "image_res": 224,
    "max_txt_l": {
      "image": 32,
      "video": 32
    },
    "video_input": {
      "num_frames": 8,
      "num_frames_test": 8,
      "random_aug": false,
      "sample_type": "middle",
      "sample_type_test": "middle"
    }
  },
  "jump_evaluate": false,
  "log_freq": 100,
  "max_txt_l": 32,
  "mode": "pt",
  "model": {
    "embed_dim": 1024,
    "find_unused_parameters": false,
    "freeze_text": true,
    "freeze_vision": true,
    "load_vision_ckpt_from_internvideo2_stage2": false,
    "model_cls": "InternVideo2_CLIP_small",
    "multimodal": {
      "enable": true
    },
    "open_text_projection": false,
    "open_vision_clip_projector": true,
    "temp": 0.01,
    "temp_min": 0.01,
    "text_encoder": {
      "embed_dim": 512,
      "image_cfg": {
        "image_size": 224,
        "model_name": "vit_b16"
      },
      "text_cfg": {
        "causal_masking": true,
        "context_length": 77,
        "dim": 512,
        "ffn_multiplier_per_layer": 4.0,
        "model_name": "base",
        "n_heads_per_layer": 8,
        "n_transformer_layers": 12,
        "norm_layer": "layer_norm_fp32",
        "vocab_size": 49408
      }
    },
    "vision_encoder": {
      "align_dim": 512,
      "attn_pool_num_heads": 16,
      "checkpoint_num": 0,
      "clip_embed_dim": 768,
      "depth": 24,
      "drop_cls_token": false,
      "drop_path_rate": 0.0,
      "embed_dim": 1024,
      "fused_mlp_heuristic": 1,
      "head_drop_path_rate": 0.0,
      "img_size": 224,
      "in_chans": 3,
      "init_values": 0.1,
      "layerscale_no_force_fp32": true,
      "mlp_ratio": 4,
      "name": "internvideo2_1B",
      "num_frames": 8,
      "num_heads": 16,
      "patch_size": 14,
      "qk_normalization": true,
      "qkv_bias": false,
      "sep_pos_embed": false,
      "tubelet_size": 1,
      "use_checkpoint": false,
      "use_flash_attn": false,
      "use_fused_mlp": false,
      "use_fused_rmsnorm": false
    }
  },
  "model_type": "internvideo2",
  "num_frames": 8,
  "num_frames_test": 8,
  "num_workers": 6,
  "optimizer": {
    "different_lr": {
      "enable": false,
      "lr": 0.001,
      "module_names": []
    },
    "lr": 5e-05,
    "max_grad_norm": 3.0,
    "opt": "adamW",
    "opt_betas": [
      0.9,
      0.98
    ],
    "weight_decay": 0.05
  },
  "output_dir": null,
  "pretrained_path": "",
  "resume": false,
  "save_ckpt_iter": null,
  "save_latest": true,
  "scheduler": {
    "epochs": 10,
    "min_lr_multi": 0.01,
    "sched": "cosine",
    "warmup_epochs": 1
  },
  "seed": 42,
  "test_file": {
    "didemo_ret_test": "available_corpus[\"didemo_ret_test\"]",
    "msrvtt_1k_test": "available_corpus[\"msrvtt_1k_test\"]"
  },
  "test_types": [
    "msrvtt_1k_test",
    "didemo_ret_test"
  ],
  "text_enc": "bert_large",
  "tokenizer": null,
  "train_file": "available_corpus[\"pretrain_example_data_1B\"]",
  "transformers_version": "5.0.0",
  "use_bf16": true,
  "use_flash_sdp": false,
  "use_half_precision": false,
  "use_mem_efficient_sdp": false,
  "wandb": {
    "enable": false,
    "entity": "opengvlab",
    "project": "InternVideo2-Stage2"
  }
}

InternVideo2 loaded 484/484 tensors (missing=0 unexpected=0)
Model device: cuda:0 dtype=torch.float16 requested=cuda (Tesla T4)
== InternVideo2 CLIP-S | tvpreid/prid | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/142 [00:00<?, ?video/s]

internvideo2 videos: 100%|██████████| 71/71 [00:53<00:00,  1.33batch/s]
internvideo2 texts: 100%|██████████| 18/18 [00:00<00:00, 66.03batch/s]

-- none: R1 30.99  mAP 42.97  mINP 42.97
== InternVideo2 CLIP-S | tvpreid/ilids | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/75 [00:00<?, ?video/s]

internvideo2 videos: 100%|██████████| 38/38 [00:26<00:00,  1.41batch/s]
internvideo2 texts: 100%|██████████| 10/10 [00:00<00:00, 73.29batch/s]

-- none: R1 12.00  mAP 24.01  mINP 24.01
== InternVideo2 CLIP-S | tvpreid/duke | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/603 [00:00<?, ?video/s]

internvideo2 videos: 100%|██████████| 302/302 [03:37<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 76/76 [00:01<00:00, 74.71batch/s]

-- none: R1 14.76  mAP 23.53  mINP 23.53
== InternVideo2 CLIP-S | tvpreid/prid | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 163 clips (window=8 stride=4 fps=1 max=12)

internvideo2 videos: 100%|██████████| 82/82 [00:58<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 18/18 [00:00<00:00, 73.80batch/s]

-- mean: R1 29.93  mAP 39.99  mINP 39.99
-- mean_s8: R1 29.93  mAP 39.99  mINP 39.99
-- max: R1 30.28  mAP 40.17  mINP 40.17
-- query_max: R1 29.93  mAP 39.85  mINP 39.85
== InternVideo2 CLIP-S | tvpreid/ilids | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 76 clips (window=8 stride=4 fps=1 max=12)

internvideo2 videos: 100%|██████████| 38/38 [00:27<00:00,  1.38batch/s]
internvideo2 texts: 100%|██████████| 10/10 [00:00<00:00, 74.56batch/s]

-- mean: R1 10.67  mAP 21.88  mINP 21.88
-- mean_s8: R1 10.67  mAP 21.88  mINP 21.88
-- max: R1 10.67  mAP 21.88  mINP 21.88
-- query_max: R1 10.67  mAP 21.88  mINP 21.88
== InternVideo2 CLIP-S | tvpreid/duke | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 1001 clips (window=8 stride=4 fps=1 max=12)

internvideo2 videos: 100%|██████████| 501/501 [06:01<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 76/76 [00:01<00:00, 73.25batch/s]

-- mean: R1 15.92  mAP 24.49  mINP 24.49
-- mean_s8: R1 15.92  mAP 24.49  mINP 24.49
-- max: R1 15.75  mAP 24.00  mINP 24.00
-- query_max: R1 16.67  mAP 25.12  mINP 25.12
== InternVideo2 CLIP-S | tvpreid/prid | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 345 clips (window=8 stride=4 fps=2 max=32)

internvideo2 videos: 100%|██████████| 173/173 [02:04<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 18/18 [00:00<00:00, 73.20batch/s]

-- mean: R1 30.63  mAP 41.86  mINP 41.86
-- mean_s8: R1 30.99  mAP 42.05  mINP 42.05
-- max: R1 32.39  mAP 43.77  mINP 43.77
-- query_max: R1 28.87  mAP 40.81  mINP 40.81
== InternVideo2 CLIP-S | tvpreid/ilids | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 127 clips (window=8 stride=4 fps=2 max=32)

internvideo2 videos: 100%|██████████| 64/64 [00:45<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 10/10 [00:00<00:00, 77.73batch/s]

-- mean: R1 10.67  mAP 22.11  mINP 22.11
-- mean_s8: R1 10.67  mAP 22.19  mINP 22.19
-- max: R1 10.67  mAP 22.38  mINP 22.38
-- query_max: R1 10.67  mAP 21.78  mINP 21.78
== InternVideo2 CLIP-S | tvpreid/duke | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 2561 clips (window=8 stride=4 fps=2 max=32)

internvideo2 videos: 100%|██████████| 1281/1281 [15:25<00:00,  1.38batch/s]
internvideo2 texts: 100%|██████████| 76/76 [00:01<00:00, 71.94batch/s]

-- mean: R1 17.74  mAP 26.06  mINP 26.06
-- mean_s8: R1 17.66  mAP 26.07  mINP 26.07
-- max: R1 14.84  mAP 23.23  mINP 23.23
-- query_max: R1 17.58  mAP 27.04  mINP 27.04
== InternVideo2 CLIP-S | tvpreid/prid | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/142 [00:00<?, ?video/s]

Window encode: 142 tracklets, 1435 clips (window=8 stride=4 fps=8 max=64)

internvideo2 videos: 100%|██████████| 718/718 [08:38<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 18/18 [00:00<00:00, 75.18batch/s]

-- mean: R1 31.34  mAP 43.65  mINP 43.65
-- mean_s8: R1 31.34  mAP 43.75  mINP 43.75
-- max: R1 30.99  mAP 44.58  mINP 44.58
-- query_max: R1 29.58  mAP 42.82  mINP 42.82
== InternVideo2 CLIP-S | tvpreid/ilids | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/75 [00:00<?, ?video/s]

Window encode: 75 tracklets, 632 clips (window=8 stride=4 fps=8 max=64)

internvideo2 videos: 100%|██████████| 316/316 [03:48<00:00,  1.38batch/s]
internvideo2 texts: 100%|██████████| 10/10 [00:00<00:00, 47.89batch/s]

-- mean: R1 11.33  mAP 23.36  mINP 23.36
-- mean_s8: R1 11.33  mAP 23.36  mINP 23.36
-- max: R1 9.33  mAP 21.72  mINP 21.72
-- query_max: R1 13.33  mAP 24.14  mINP 24.14
== InternVideo2 CLIP-S | tvpreid/duke | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/603 [00:00<?, ?video/s]

Window encode: 603 tracklets, 8522 clips (window=8 stride=4 fps=8 max=64)

internvideo2 videos: 100%|██████████| 4261/4261 [51:18<00:00,  1.38batch/s]
internvideo2 texts: 100%|██████████| 76/76 [00:01<00:00, 75.17batch/s]

-- mean: R1 17.33  mAP 26.44  mINP 26.44
-- mean_s8: R1 17.08  mAP 26.36  mINP 26.36
-- max: R1 14.59  mAP 21.99  mINP 21.99
-- query_max: R1 18.49  mAP 28.36  mINP 28.36
== InternVideo2 CLIP-S | rstpreid/test | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/1000 [00:00<?, ?video/s]

internvideo2 videos: 100%|██████████| 500/500 [06:13<00:00,  1.34batch/s]
internvideo2 texts: 100%|██████████| 125/125 [00:01<00:00, 72.11batch/s]

-- none: R1 27.00  mAP 21.34  mINP 1.55
== InternVideo2 CLIP-S | groot_mot17/all | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2 videos: 100%|██████████| 227/227 [02:43<00:00,  1.38batch/s]
internvideo2 texts: 100%|██████████| 50/50 [00:00<00:00, 80.93batch/s]

-- none: R1 9.15  mAP 14.44  mINP 14.44
== InternVideo2 CLIP-S | groot_mot17/appearance | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 77.29batch/s]

-- none: R1 18.31  mAP 27.11  mINP 27.11
== InternVideo2 CLIP-S | groot_mot17/action | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2 texts: 100%|██████████| 29/29 [00:00<00:00, 75.77batch/s]

-- none: R1 2.20  mAP 4.83  mINP 4.83
== InternVideo2 CLIP-S | groot_mot17/combined | uniform8 (uniform 8 frames)

Decode frames:   0%|          | 0/454 [00:00<?, ?video/s]

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 78.26batch/s]

-- none: R1 22.97  mAP 31.33  mINP 31.33
== InternVideo2 CLIP-S | groot_mot17/all | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

internvideo2 videos: 100%|██████████| 278/278 [03:20<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 50/50 [00:00<00:00, 80.68batch/s]

-- mean: R1 6.52  mAP 11.67  mINP 11.67
-- mean_s8: R1 6.52  mAP 11.67  mINP 11.67
-- max: R1 6.52  mAP 11.61  mINP 11.61
-- query_max: R1 6.89  mAP 11.83  mINP 11.83
== InternVideo2 CLIP-S | groot_mot17/appearance | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 81.52batch/s]

-- mean: R1 13.66  mAP 22.04  mINP 22.04
-- mean_s8: R1 13.66  mAP 22.04  mINP 22.04
-- max: R1 13.37  mAP 21.74  mINP 21.74
-- query_max: R1 14.53  mAP 22.51  mINP 22.51
== InternVideo2 CLIP-S | groot_mot17/action | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

internvideo2 texts: 100%|██████████| 29/29 [00:00<00:00, 80.70batch/s]

-- mean: R1 1.10  mAP 3.80  mINP 3.80
-- mean_s8: R1 1.10  mAP 3.80  mINP 3.80
-- max: R1 1.32  mAP 3.94  mINP 3.94
-- query_max: R1 1.10  mAP 3.74  mINP 3.74
== InternVideo2 CLIP-S | groot_mot17/combined | vt_1fps_n12 (sliding windows of 8, stride 4, 1 fps, cap 12 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 556 clips (window=8 stride=4 fps=1 max=12)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 77.38batch/s]

-- mean: R1 17.73  mAP 25.20  mINP 25.20
-- mean_s8: R1 17.73  mAP 25.20  mINP 25.20
-- max: R1 17.44  mAP 25.25  mINP 25.25
-- query_max: R1 18.02  mAP 25.31  mINP 25.31
== InternVideo2 CLIP-S | groot_mot17/all | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

internvideo2 videos: 100%|██████████| 468/468 [05:37<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 50/50 [00:00<00:00, 80.41batch/s]

-- mean: R1 8.77  mAP 14.21  mINP 14.21
-- mean_s8: R1 8.77  mAP 14.17  mINP 14.17
-- max: R1 8.15  mAP 13.50  mINP 13.50
-- query_max: R1 8.15  mAP 13.58  mINP 13.58
== InternVideo2 CLIP-S | groot_mot17/appearance | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 82.14batch/s]

-- mean: R1 18.02  mAP 26.65  mINP 26.65
-- mean_s8: R1 18.02  mAP 26.49  mINP 26.49
-- max: R1 16.28  mAP 25.02  mINP 25.02
-- query_max: R1 16.57  mAP 25.57  mINP 25.57
== InternVideo2 CLIP-S | groot_mot17/action | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

internvideo2 texts: 100%|██████████| 29/29 [00:00<00:00, 80.47batch/s]

-- mean: R1 1.76  mAP 4.79  mINP 4.79
-- mean_s8: R1 1.76  mAP 4.84  mINP 4.84
-- max: R1 1.98  mAP 4.77  mINP 4.77
-- query_max: R1 1.76  mAP 4.49  mINP 4.49
== InternVideo2 CLIP-S | groot_mot17/combined | vt_2fps_n32 (sliding windows of 8, stride 4, 2 fps, cap 32 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 935 clips (window=8 stride=4 fps=2 max=32)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 78.99batch/s]

-- mean: R1 23.26  mAP 30.41  mINP 30.41
-- mean_s8: R1 23.84  mAP 30.63  mINP 30.63
-- max: R1 18.60  mAP 27.02  mINP 27.02
-- query_max: R1 22.38  mAP 30.27  mINP 30.27
== InternVideo2 CLIP-S | groot_mot17/all | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

internvideo2 videos: 100%|██████████| 1779/1779 [21:24<00:00,  1.39batch/s]
internvideo2 texts: 100%|██████████| 50/50 [00:00<00:00, 81.59batch/s]

-- mean: R1 9.27  mAP 14.96  mINP 14.96
-- mean_s8: R1 9.77  mAP 15.29  mINP 15.29
-- max: R1 6.27  mAP 11.72  mINP 11.72
-- query_max: R1 8.40  mAP 14.33  mINP 14.33
== InternVideo2 CLIP-S | groot_mot17/appearance | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 81.75batch/s]

-- mean: R1 18.60  mAP 27.41  mINP 27.41
-- mean_s8: R1 19.19  mAP 27.88  mINP 27.88
-- max: R1 12.50  mAP 20.98  mINP 20.98
-- query_max: R1 16.57  mAP 27.00  mINP 27.00
== InternVideo2 CLIP-S | groot_mot17/action | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

internvideo2 texts: 100%|██████████| 29/29 [00:00<00:00, 83.51batch/s]

-- mean: R1 2.20  mAP 5.53  mINP 5.53
-- mean_s8: R1 2.64  mAP 5.76  mINP 5.76
-- max: R1 1.54  mAP 4.70  mINP 4.70
-- query_max: R1 2.20  mAP 4.73  mINP 4.73
== InternVideo2 CLIP-S | groot_mot17/combined | reid_8fps_n64 (sliding windows of 8, stride 4, 8 fps, cap 64 frames)

Decode windows:   0%|          | 0/454 [00:00<?, ?video/s]

Window encode: 454 tracklets, 3558 clips (window=8 stride=4 fps=8 max=64)

internvideo2 texts: 100%|██████████| 22/22 [00:00<00:00, 78.00batch/s]

-- mean: R1 24.71  mAP 32.60  mINP 32.60
-- mean_s8: R1 23.84  mAP 32.38  mINP 32.38
-- max: R1 15.70  mAP 23.18  mINP 23.18
-- query_max: R1 22.97  mAP 32.48  mINP 32.48
Done

## 5. Tables

Reads every results folder it can find: this session's `zero_shot_results/`, plus any attached Kaggle inputs that contain a `zero_shot_results` folder (other groups, earlier runs). Each table is shown here and saved as CSV and Markdown under `zero_shot_results/tables/`.

Accuracy cells use each model's **best Rank-1 setting** per dataset subset (protocol and pool are shown in the settings table). All numbers are percentages except MdR (median rank).

In [6]:
import numpy as np

KEY = ["dataset", "subset", "model", "protocol", "pool"]
LEGACY_TVPREID = {"prid", "ilids", "duke"}


def collect_rows():
    roots = [RESULTS_ROOT]
    if Path("/kaggle/input").is_dir():
        roots += [p for p in Path("/kaggle/input").rglob("zero_shot_results") if p.is_dir()]
    rows = []
    for root in dict.fromkeys(roots):
        for path in root.rglob("*.json"):
            try:
                row = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue
            if not isinstance(row, dict) or "Rank-1" not in row:
                continue
            if "dataset" not in row and row.get("subset") in LEGACY_TVPREID:
                row["dataset"] = "tvpreid"
                row.setdefault("protocol_type", "single" if row.get("pool") == "none" else "window")
            if row.get("status", "complete") != "complete" or "dataset" not in row:
                continue
            rows.append(row)
    if not rows:
        return pd.DataFrame(
            columns=KEY + ["Rank-1", "mAP", "mINP", "protocol_type", "gallery_cached", "Model", "Dataset",
                           "video_ms_per_item", "peak_gpu_gb", "total_s"]
        )
    frame = pd.DataFrame(rows)
    if "protocol_type" not in frame:
        frame["protocol_type"] = np.where(frame["pool"] == "none", "single", "window")
    frame["protocol_type"] = frame["protocol_type"].fillna(
        pd.Series(np.where(frame["pool"] == "none", "single", "window"), index=frame.index)
    )
    frame["created_at"] = frame.get("created_at", pd.Series(dtype=str)).fillna("")
    frame["gallery_cached"] = frame.get("gallery_cached", False)
    frame["gallery_cached"] = frame["gallery_cached"].fillna(False).astype(bool)
    frame = frame.sort_values("created_at").drop_duplicates(KEY, keep="last")
    frame["Model"] = frame["model"].map(lambda m: PRETTY.get(m, m))
    frame["Dataset"] = frame["dataset"].map(lambda d: DATASETS.get(d, {}).get("label", d))
    return frame.reset_index(drop=True)


RESULTS = collect_rows()
print(f"{len(RESULTS)} result rows from {RESULTS['model'].nunique() if len(RESULTS) else 0} models", flush=True)
BEST = (
    RESULTS.sort_values(["Rank-1", "mAP"], ascending=False, kind="mergesort")
    .groupby(["dataset", "subset", "model"], as_index=False)
    .head(1)
    .reset_index(drop=True)
)
TABLES = {}


def column_order(dataset):
    return [s for s in DATASETS.get(dataset, {}).get("subsets", []) if s in set(BEST.loc[BEST.dataset == dataset, "subset"])]


def setting_text(row):
    return row["protocol"] if row["pool"] in ("none", None) or pd.isna(row["pool"]) else f"{row['protocol']} / {row['pool']}"

651 result rows from 7 models

### 5.1 Leaderboard per dataset (Rank-1 / mAP / mINP)

In [7]:
for dataset in [d for d in DATASETS if d in set(BEST["dataset"])]:
    part = BEST[BEST.dataset == dataset].copy()
    subsets = column_order(dataset)
    part["cell"] = part.apply(lambda r: f"{r['Rank-1']:.2f} / {r['mAP']:.2f} / {r.get('mINP', np.nan):.2f}", axis=1)
    part["setting"] = part.apply(setting_text, axis=1)
    order = part.groupby("Model")["Rank-1"].mean().sort_values(ascending=False).index
    board = part.pivot(index="Model", columns="subset", values="cell").reindex(index=order, columns=subsets)
    board["mean Rank-1"] = part.groupby("Model")["Rank-1"].mean().reindex(order).round(2)
    settings = part.pivot(index="Model", columns="subset", values="setting").reindex(index=order, columns=subsets)
    label = DATASETS[dataset]["label"]
    TABLES[f"leaderboard_{dataset}"] = board
    TABLES[f"best_setting_{dataset}"] = settings
    display(Markdown(f"#### {label}"))
    display(board)
    display(Markdown(f"Best setting per cell ({label})"))
    display(settings)

#### TVPReid

subset,prid,ilids,duke,mean Rank-1
Model,,,,
IRRA,66.55 / 76.09 / 76.09,30.00 / 41.29 / 41.29,38.06 / 50.79 / 50.79,44.87
SigLIP 2 So400m,35.56 / 50.84 / 50.84,18.67 / 28.88 / 28.88,21.97 / 33.03 / 33.03,25.40
Perception Encoder L/14,38.38 / 52.04 / 52.04,19.33 / 32.55 / 32.55,17.66 / 28.12 / 28.12,25.13
InternVideo2 CLIP-S,32.39 / 43.77 / 43.77,13.33 / 24.14 / 24.14,18.49 / 28.36 / 28.36,21.41
LanguageBind,16.20 / 24.82 / 24.82,12.67 / 22.09 / 22.09,7.30 / 14.46 / 14.46,12.05
X-CLIP,4.93 / 10.05 / 10.05,5.33 / 10.52 / 10.52,1.41 / 3.95 / 3.95,3.89
InternVideo2-1B-s2,4.23 / 10.78 / 10.78,4.00 / 10.26 / 10.26,1.82 / 4.15 / 4.15,3.35

Best setting per cell (TVPReid)

subset,prid,ilids,duke
Model,,,
IRRA,reid_8fps_n64 / mean_s8,vt_2fps_n32 / mean_s8,reid_8fps_n64 / query_max
SigLIP 2 So400m,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max
Perception Encoder L/14,reid_8fps_n64 / mean_s8,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max
InternVideo2 CLIP-S,vt_2fps_n32 / max,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max
LanguageBind,vt_2fps_n32 / mean,reid_8fps_n64 / mean,reid_8fps_n64 / mean
X-CLIP,reid_8fps_n64 / mean,vt_2fps_n32 / mean,reid_8fps_n64 / mean
InternVideo2-1B-s2,uniform4,vt_2fps_n32 / query_max,vt_1fps_n12 / query_max

#### RSTPReid

subset                                   test  mean Rank-1
Model
IRRA                     53.30 / 39.71 / 3.35        53.30
SigLIP 2 So400m          41.00 / 29.34 / 2.07        41.00
Perception Encoder L/14  37.40 / 29.09 / 2.42        37.40
InternVideo2 CLIP-S      27.00 / 21.34 / 1.55        27.00
LanguageBind             15.55 / 11.36 / 0.52        15.55
InternVideo2-1B-s2         5.15 / 4.53 / 0.25         5.15
X-CLIP                     1.40 / 2.26 / 0.17         1.40

Best setting per cell (RSTPReid)

subset                       test
Model
IRRA                     uniform8
SigLIP 2 So400m          uniform8
Perception Encoder L/14  uniform8
InternVideo2 CLIP-S      uniform8
LanguageBind             uniform8
InternVideo2-1B-s2       uniform4
X-CLIP                   uniform8

#### GroOT-MOT17

subset,all,appearance,action,combined,mean Rank-1
Model,,,,,
Perception Encoder L/14,12.41 / 19.20 / 19.20,25.29 / 36.46 / 36.46,3.30 / 6.55 / 6.55,29.36 / 39.19 / 39.19,17.59
IRRA,11.90 / 18.52 / 18.52,24.71 / 36.67 / 36.67,2.20 / 4.76 / 4.76,29.36 / 42.39 / 42.39,17.04
SigLIP 2 So400m,12.16 / 17.81 / 17.81,25.58 / 34.06 / 34.06,2.20 / 5.34 / 5.34,27.91 / 38.92 / 38.92,16.96
InternVideo2 CLIP-S,9.77 / 15.29 / 15.29,19.19 / 27.88 / 27.88,2.64 / 5.76 / 5.76,24.71 / 32.60 / 32.60,14.08
LanguageBind,7.64 / 12.23 / 12.23,14.83 / 22.95 / 22.95,2.20 / 4.12 / 4.12,16.28 / 23.89 / 23.89,10.24
X-CLIP,1.38 / 3.93 / 3.93,2.62 / 6.87 / 6.87,0.44 / 1.83 / 1.83,2.91 / 6.36 / 6.36,1.84
InternVideo2-1B-s2,0.75 / 2.27 / 2.27,0.87 / 2.78 / 2.78,0.66 / 1.88 / 1.88,1.45 / 3.52 / 3.52,0.93

Best setting per cell (GroOT-MOT17)

subset,all,appearance,action,combined
Model,,,,
Perception Encoder L/14,reid_8fps_n64 / mean,reid_8fps_n64 / mean_s8,vt_2fps_n32 / max,reid_8fps_n64 / mean
IRRA,uniform8,uniform8,uniform8,reid_8fps_n64 / query_max
SigLIP 2 So400m,uniform8,uniform8,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max
InternVideo2 CLIP-S,reid_8fps_n64 / mean_s8,reid_8fps_n64 / mean_s8,reid_8fps_n64 / mean_s8,reid_8fps_n64 / mean
LanguageBind,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max,reid_8fps_n64 / query_max
X-CLIP,reid_8fps_n64 / mean,reid_8fps_n64 / mean_s8,uniform8,vt_2fps_n32 / mean_s8
InternVideo2-1B-s2,vt_1fps_n12 / max,vt_1fps_n12 / max,vt_1fps_n12 / max,vt_1fps_n12 / max

### 5.2 Cross-dataset Rank-1 matrix

In [8]:
if len(BEST):
    BEST["column"] = BEST.apply(lambda r: f"{DATASETS.get(r['dataset'], {}).get('label', r['dataset'])} {r['subset']}", axis=1)
    columns = [
        f"{DATASETS[d]['label']} {s}"
        for d in DATASETS
        for s in column_order(d)
    ]
    matrix = BEST.pivot(index="Model", columns="column", values="Rank-1").reindex(columns=columns)
    matrix["Mean"] = matrix.mean(axis=1)
    matrix = matrix.sort_values("Mean", ascending=False).round(2)
    TABLES["cross_dataset_rank1"] = matrix
    try:
        display(matrix.style.format("{:.2f}", na_rep="-").background_gradient(cmap="Greens", axis=0))
    except Exception:
        display(matrix)

### 5.3 Protocol and pool comparison (top three models per video dataset, Rank-1)

In [9]:
for dataset in [d for d in DATASETS if DATASETS[d]["protocols"] == "video" and d in set(RESULTS["dataset"])]:
    part = RESULTS[RESULTS.dataset == dataset].copy()
    top = part.groupby("Model")["Rank-1"].max().sort_values(ascending=False).head(3).index
    part = part[part.Model.isin(top)]
    part["pool"] = part["pool"].replace({"none": "-"})
    table = part.pivot_table(index=["Model", "protocol", "pool"], columns="subset", values="Rank-1", aggfunc="max")
    table = table.reindex(columns=column_order(dataset)).round(2)
    table = table.reindex(top, level=0)
    TABLES[f"protocols_{dataset}"] = table
    display(Markdown(f"#### {DATASETS[dataset]['label']}"))
    display(table)

#### TVPReid

subset                                            prid  ilids   duke
Model                   protocol      pool
IRRA                    reid_8fps_n64 max        65.14  26.00  32.34
                                      mean       65.85  27.33  36.07
                                      mean_s8    66.55  26.00  36.65
                                      query_max  65.14  28.00  38.06
                        uniform8      -          65.49  28.00  35.82
                        vt_1fps_n12   max        63.38  27.33  35.57
                                      mean       63.03  27.33  35.66
                                      mean_s8    63.03  27.33  35.66
                                      query_max  63.03  27.33  35.90
                        vt_2fps_n32   max        62.68  29.33  34.08
                                      mean       62.32  30.00  36.65
                                      mean_s8    63.03  30.00  36.24
                                      query_max  62.68  28.67  37.73
Perception Encoder L/14 reid_8fps_n64 max        36.62  18.00  13.27
                                      mean       38.03  18.00  15.01
                                      mean_s8    38.38  18.67  14.34
                                      query_max  35.56  19.33  17.66
                        uniform8      -          38.03  18.00  14.84
                        vt_1fps_n12   max        35.56  16.67  14.68
                                      mean       35.56  16.67  14.01
                                      mean_s8    35.56  16.67  14.01
                                      query_max  34.51  16.67  15.09
                        vt_2fps_n32   max        34.51  19.33  13.85
                                      mean       34.15  19.33  13.76
                                      mean_s8    34.15  19.33  13.76
                                      query_max  34.86  19.33  16.00
SigLIP 2 So400m         reid_8fps_n64 max        32.04  14.67  17.25
                                      mean       32.04  16.67  19.40
                                      mean_s8    32.04  16.67  19.40
                                      query_max  35.56  18.67  21.97
                        uniform8      -          33.45  14.67  17.58
                        vt_1fps_n12   max        33.10  17.33  17.91
                                      mean       32.75  17.33  18.16
                                      mean_s8    32.75  17.33  18.16
                                      query_max  33.10  17.33  20.07
                        vt_2fps_n32   max        34.15  15.33  17.83
                                      mean       32.75  16.00  19.98
                                      mean_s8    33.45  15.33  19.24
                                      query_max  30.28  16.00  20.81

#### GroOT-MOT17

subset                                             all  appearance  action  \
Model                   protocol      pool
IRRA                    reid_8fps_n64 max        10.53       21.80    1.98
                                      mean       10.78       22.67    1.76
                                      mean_s8    10.78       22.97    1.54
                                      query_max  10.03       20.93    1.76
                        uniform8      -          11.90       24.71    2.20
                        vt_1fps_n12   max         8.77       19.48    0.66
                                      mean        8.90       19.77    0.66
                                      mean_s8     8.90       19.77    0.66
                                      query_max   8.65       18.90    0.88
                        vt_2fps_n32   max        11.03       23.26    1.76
                                      mean       11.03       22.97    1.98
                                      mean_s8    11.03       22.97    1.98
                                      query_max  10.78       22.97    1.54
Perception Encoder L/14 reid_8fps_n64 max        10.90       22.09    2.42
                                      mean       12.41       25.00    2.86
                                      mean_s8    12.28       25.29    2.42
                                      query_max  11.78       24.13    2.42
                        uniform8      -          12.28       24.42    3.08
                        vt_1fps_n12   max         9.40       18.60    2.42
                                      mean        9.15       18.31    2.20
                                      mean_s8     9.15       18.31    2.20
                                      query_max   9.52       19.19    2.20
                        vt_2fps_n32   max        11.15       21.51    3.30
                                      mean       11.65       23.26    2.86
                                      mean_s8    11.78       23.84    2.64
                                      query_max  11.15       22.38    2.64
SigLIP 2 So400m         reid_8fps_n64 max        11.65       24.42    1.98
                                      mean       12.03       25.29    1.98
                                      mean_s8    11.78       24.71    1.98
                                      query_max  11.78       24.42    2.20
                        uniform8      -          12.16       25.58    1.98
                        vt_1fps_n12   max         8.02       17.15    1.10
                                      mean        8.65       18.31    1.32
                                      mean_s8     8.65       18.31    1.32
                                      query_max   8.27       17.44    1.32
                        vt_2fps_n32   max         9.15       18.90    1.76
                                      mean        9.27       18.90    1.98
                                      mean_s8     9.77       20.06    1.98
                                      query_max   9.77       19.77    2.20

subset                                           combined
Model                   protocol      pool
IRRA                    reid_8fps_n64 max           25.58
                                      mean          27.03
                                      mean_s8       26.45
                                      query_max     29.36
                        uniform8      -             28.20
                        vt_1fps_n12   max           22.38
                                      mean          22.97
                                      mean_s8       22.97
                                      query_max     22.67
                        vt_2fps_n32   max           28.20
                                      mean          28.20
                                      mean_s8       28.49
                                      query_max     28.49
Perception Encoder L/14 reid_8fps_n64 max           26.16
                                      mean          29.36
                                      mean_s8       29.36
                                      query_max     28.78
                        uniform8      -             28.20
                        vt_1fps_n12   max           21.80
                                      mean          22.09
                                      mean_s8       22.09
                                      query_max     22.38
                        vt_2fps_n32   max           25.87
                                      mean          24.71
                                      mean_s8       25.00
                                      query_max     26.16
SigLIP 2 So400m         reid_8fps_n64 max           25.87
                                      mean          25.00
                                      mean_s8       25.00
                                      query_max     27.91
                        uniform8      -             26.16
                        vt_1fps_n12   max           20.93
                                      mean          20.35
                                      mean_s8       20.35
                                      query_max     21.80
                        vt_2fps_n32   max           21.22
                                      mean          23.26
                                      mean_s8       23.26
                                      query_max     22.97

### 5.4 GroOT-MOT17: appearance vs action vs combined captions

Same gallery, different queries. A large positive gap means the model matches clothing and looks, not motion. Action captions repeat a lot across tracks ("a person walking on the street"), so low action Rank-1 is expected for every model.

In [10]:
groot = BEST[BEST.dataset == "groot_mot17"]
if len(groot):
    gap = groot.pivot(index="Model", columns="subset", values="Rank-1").reindex(columns=["appearance", "action", "combined", "all"])
    gap["appearance - action"] = gap["appearance"] - gap["action"]
    gap["combined - appearance"] = gap["combined"] - gap["appearance"]
    gap = gap.sort_values("appearance", ascending=False).round(2)
    TABLES["groot_appearance_vs_action"] = gap
    display(gap)
else:
    print("No GroOT-MOT17 rows yet")

subset,appearance,action,combined,all,appearance - action,combined - appearance
Model,,,,,,
SigLIP 2 So400m,25.58,2.20,27.91,12.16,23.38,2.33
Perception Encoder L/14,25.29,3.30,29.36,12.41,21.99,4.07
IRRA,24.71,2.20,29.36,11.90,22.51,4.65
InternVideo2 CLIP-S,19.19,2.64,24.71,9.77,16.54,5.52
LanguageBind,14.83,2.20,16.28,7.64,12.62,1.45
X-CLIP,2.62,0.44,2.91,1.38,2.18,0.29
InternVideo2-1B-s2,0.87,0.66,1.45,0.75,0.21,0.58

### 5.5 Speed and GPU (Tesla T4)

In [11]:
if len(RESULTS):
    fresh = RESULTS[~RESULTS["gallery_cached"]]
    single = fresh[fresh["protocol_type"] == "single"]
    windows = fresh[fresh["protocol_type"] == "window"]
    speed = pd.DataFrame(
        {
            "ms / clip (single clip)": single.groupby("Model")["video_ms_per_item"].median(),
            "ms / clip (windows)": windows.groupby("Model")["video_ms_per_item"].median(),
            "peak GPU GB": RESULTS.groupby("Model")["peak_gpu_gb"].max(),
            "total minutes": RESULTS.groupby("Model")["total_s"].sum() / 60.0,
            "rows": RESULTS.groupby("Model").size(),
        }
    )
    speed = speed.sort_values("ms / clip (single clip)").round(2)
    TABLES["speed_gpu"] = speed
    display(speed)

,ms / clip (single clip),ms / clip (windows),peak GPU GB,total minutes,rows
Model,,,,,
X-CLIP,31.59,29.21,0.45,42.37,92
IRRA,35.60,34.02,0.31,48.62,92
LanguageBind,200.43,197.30,1.22,272.11,92
Perception Encoder L/14,248.91,245.24,1.32,336.79,92
InternVideo2-1B-s2,267.11,267.03,2.81,429.69,99
InternVideo2 CLIP-S,361.04,361.18,1.54,494.57,92
SigLIP 2 So400m,436.66,436.75,2.23,614.64,92

### 5.6 Save tables

In [12]:
def markdown_table(frame):
    frame = frame.reset_index() if not isinstance(frame.index, pd.RangeIndex) else frame
    headers = [str(c) for c in frame.columns]

    def cell(value):
        if isinstance(value, float):
            return "-" if np.isnan(value) else f"{value:.2f}"
        return str(value)

    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for _, row in frame.iterrows():
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


TABLE_DIR = RESULTS_ROOT / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)
RESULTS.to_csv(TABLE_DIR / "all_rows.csv", index=False)
DATASET_SUMMARY.to_csv(TABLE_DIR / "datasets.csv", index=False)
report = ["# Zero-shot results", "", "## Datasets", "", markdown_table(DATASET_SUMMARY.drop(columns=["root"]))]
for name, table in TABLES.items():
    table.to_csv(TABLE_DIR / f"{name}.csv")
    report += ["", f"## {name}", "", markdown_table(table)]
(TABLE_DIR / "report.md").write_text("\n".join(report) + "\n", encoding="utf-8")
print("Wrote", sorted(p.name for p in TABLE_DIR.iterdir()), flush=True)

Wrote ['all_rows.csv', 'best_setting_groot_mot17.csv', 'best_setting_rstpreid.csv', 'best_setting_tvpreid.csv', 'cross_dataset_rank1.csv', 'datasets.csv', 'groot_appearance_vs_action.csv', 'leaderboard_groot_mot17.csv', 'leaderboard_rstpreid.csv', 'leaderboard_tvpreid.csv', 'protocols_groot_mot17.csv', 'protocols_tvpreid.csv', 'report.md', 'speed_gpu.csv']

## Reference: earlier TVPReid run (base group)

Tesla T4, TVPReid test. Each accuracy cell is **Rank-1 / mAP / MdR** for that model's best Rank-1 on the subset. Milliseconds per clip and peak GPU are stable across protocols. Duke video encode is the wall clock of the run that set that model's best Duke Rank-1.

### Rank-1 / mAP / median rank

| Model | PRID | iLIDS | Duke |
|---|---:|---:|---:|
| IRRA | **66.55** / 76.09 / 1 | **30.00** / 41.27 / 5 | **38.06** / 50.79 / 2 |
| Perception Encoder L/14 | 38.38 / 52.04 / 2 | 19.33 / 32.55 / 6 | 17.66 / 28.12 / 11 |
| SigLIP 2 So400m | 35.56 / 50.84 / 3 | 18.67 / 28.88 / 10 | 21.97 / 33.03 / 7 |
| InternVideo2 CLIP-S | 32.39 / 43.77 / 4 | 13.33 / 24.14 / 11.5 | 18.49 / 28.36 / 12 |
| LanguageBind | 16.20 / 24.82 / 16 | 12.67 / 22.09 / 14 | 7.30 / 14.46 / 40.5 |
| X-CLIP | 4.93 / 10.05 / 43.5 | 5.33 / 10.52 / 38.5 | 1.41 / 3.95 / 164 |
| InternVideo2-1B-s2 | 4.23 / 10.78 / 34.5 | 4.00 / 10.26 / 29 | 1.82 / 3.82 / 159 |

### Setting, speed, and GPU

| Model | Best setting | ms / clip | Peak GPU | Duke video encode |
|---|---|---:|---:|---:|
| IRRA | PRID 8 fps `mean_s8`; iLIDS 2 fps `mean`; Duke 8 fps `query_max` | 34 | 0.31 GB | 4.8 min |
| Perception Encoder L/14 | PRID 8 fps `mean_s8`; iLIDS and Duke 8 fps `query_max` | 238 | 1.32 GB | 33.8 min |
| SigLIP 2 So400m | 8 fps `query_max` on all three subsets | 421 | 2.23 GB | 59.8 min |
| InternVideo2 CLIP-S | PRID 2 fps `max`; iLIDS and Duke 8 fps `query_max` | 354 | 1.54 GB | 50.2 min |
| LanguageBind | PRID 2 fps `mean`; iLIDS and Duke 8 fps `mean` | 192 | 1.22 GB | 27.2 min |
| X-CLIP | PRID and Duke 8 fps `mean`; iLIDS 2 fps `mean` | 30 | 0.45 GB | 4.2 min |
| InternVideo2-1B-s2 | PRID uniform 4; iLIDS 2 fps `query_max`; Duke 1 fps `mean_s8` | 262 | 2.81 GB | 6.9 min |